### ISSUE TITLE
Delete old BOM

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#10]
[repo ]( https://github.com/microprofile/microprofile-bom)not marked as deprecated but I (Triber Cesar) think can also be deleted since now the BOM is been maintained on the github/eclipse repositories. I guess kenfinnigan is the one you can ask for confirmation.

**Comment by kenfinnigan** [comment]
I don't see any issue with archiving/deleting that repository

**Comment by kwsutter** [comment]
Just to be clear, this is the [microprofile-bom repo in the MicroProfile github](https://github.com/microprofile/microprofile-bom) namespace, not the Eclipse namespace.  So, this [repo](https://github.com/microprofile/microprofile-bom) is not needed at all anymore.  Go ahead and delete/archive it.

The [Eclipse microprofile-bom repo](https://github.com/eclipse/microprofile-bom) has an updated README that indicates it is deprecated.

**Comment by aeiras** [comment]
thank you both for confirming 👍

**Comment by aeiras** [comment]
@dblevins can you archive or delete this repo? thanks-- i don't have the access to complete clean up.

**Comment by aeiras** [comment]
@dblevins this ticket is closed.
