### ISSUE TITLE
MP Workshop in Montreal

### ISSUE THREAD

**Issue by yeekangc** [microprofile/microprofile-marketing#100]
Name of the speaker: YK Chang (and the Open Liberty team)
Name of the session: Building Java Microservices in an Open Cloud-Native World
Twitter or/& git account, if available: @yeekangc (on Git)
Link of the event or short session abstract:
https://www.eventbrite.com/e/workshop-building-java-microservices-in-an-open-cloud-native-world-tickets-61097400971?aff=ebapi

Date/time/location:
Wed, May 29, 2019
8:30 AM – 12:00 PM EDT

IBM Canada
1 Place Ville Marie, 22e étage
Montreal, QC H3B 4M7

Message:
Join us in Montreal Wednesday May 29th to learn how you can easily build #java #microservices with open and standards-based technologies! @MicroProfileIO @OpenLibertyIO

**Comment by rstjames** [comment]
@yeekangc Your session had been scheduled on MP twitter for today (Friday and 28th) 
This is the image that will go with the tweet. 

![MicroProfile-IBM-Montreal-YK](https://user-images.githubusercontent.com/12132146/58313837-c6b67900-7e0e-11e9-8f89-21f71001e7fe.png)

**Comment by yeekangc** [comment]
Thank you, @rstjames!
