### ISSUE TITLE
Update microprofile.io to be more developer focused

### ISSUE THREAD

**Issue by aguibert** [microprofile/microprofile-marketing#101]
I've started an [email discussion on the Microprofile mailing list](https://groups.google.com/forum/#!topic/microprofile/PlkcDmxk7b0) about updating the website content to provide more concrete information from a developer perspective.

Ondro pointed out that the website is not directly source controlled in Github, and the marketing folks "hold the keys" so to speak. Is there a process for MP contributors such as myself proposing updates to the website?

**Comment by aeiras** [comment]
Hola Andy @aguibert, 

Your forum write up is fantastic. Let me point you out at the website work skelleton where new features and adjustments go first before implementation in the website. You are so most welcomed to help make the MP site better. Thank you for thinking as a developer and using that mind for a clearer website. 

Question, would you be able to implement front-end features to help adjust website?

Please check document and using "suggestive mode" add whatever is missing from document. 

[Website Skelleton](https://docs.google.com/document/d/1Ga7Z1aVgq4EcE19mSg5Ig9zugg3xqlXOkZnqsheX61o/edit?usp=sharing)

**Comment by aguibert** [comment]
> Question, would you be able to implement front-end features to help adjust website?

I don't consider myself a front-end developer, but I can make changes/alterations if the basic framework is already established (which I expect it is). Also, I have no idea what back the website. I heard on the mailing list it's a WordPress website? I haven't done much with WordPress, but as far as I know it doesn't require coding.

Regarding the website skelleton document you linked, I'm not sure what this document is for or where to add my feedback. I'd rather make the changes to the website directly myself (ideally in a suggestive mode) rather than trying to relay my specific feedback to marketing.

**Comment by aeiras** [comment]
Thanks for the follow up Andy. 

Not everything in the Website is wordpress. Let me add Ryan to this ticket since he lead the effort to make website less technical. @rstjames. Please provide us with an update here or bring the thread via forum reference so that Andy gets an idea of what currently is at stake with MP site. 

- There are 11 admins distrubuted accross Contributors. The access is restricted and [documented here](https://docs.google.com/document/d/1q0Xw4XJcoVq1V5vPWe9KR__WKoGc0e-X5cD3tnBsIKw/edit). In the past, the website has been broken **multiple times** and we were not able to track who did what, so cut to the bare minimum the Admins to what it is today.  Why? Repairing the bug (s) that caused the website to be broken for days has always taken a MASSIVE investment of time. Negative. 

Therefore, the skelleton that I provided is what we currently use to prioritize what adjustments are needed NOW or LATER in the website before they get submitted as a git issue for completion. 
Most of that work is presented during the MP Community calls before the work starts to enable anyone to on those calls to provide feedback, if any. 

If you use "suggestive mode" and submit an issue via this channel for reference, that is most helpful. 

We cannot add you as Admin b/c INFRA techical has technical Admins not listed under the Marketing Drive.  There are subparts to how the website is controlled by need and TOOLING. 

I hope this helps.

**Comment by aeiras** [comment]
@dblevins  you are most welcomed to update Andy on what we (Contributors) plan to do to make website really OSS friendly. :)

**Comment by aguibert** [comment]
I certainly sympathize with the reasoning behind restricting access due to repeated site breakages with no record of who did what. However, the edits I had in mind would be difficult to convey in the skelleton document. If possible, I'd like to make my changes in draft mode or something, and then have an admin review/approve my changes -- that's how OSS is supposed to work right? 😉 I see Kevin Sutter is listed as an Admin, so I will check with him tomorrow since we are co-located to see what my options are.

Before I do any of this, I think it would be a good discussion topic for the next MP Community hangout (June 11th). Especially since Ryan has led an effort to make the website less technical, I don't want to work counter to his efforts without understanding the reasoning first.

**Comment by aeiras** [comment]
I love your reply, +1 to everything you stated above. Please add topic (issue with small reference for those readers who won't do the homework before the call)  to **the agenda for next Community call**. Added David to this thread too b/c though Ryan was involved, David lead the effort to make it less technical - the two parts are a bit messy but today it is better than the past. And as you say, we want MP site to be as OSS friendly welcoming anyone to make it better by collaboration that means more than 1 person pushing stuff to the world. :)

**Comment by rstjames** [comment]
Hi @aguibert 
Not sure if you had time on that community call (July 11th ) to share what you would like to do. 
I would strongly push that we keep all changes done on the wordpress UI especially until we know what changes want to be made and why. I have ran into many issues in the past when people would start to make changes on a wodpress site without using the WP backend and from there it was a chain reaction for future issues.  I am more than happy to make changes on the wordpress site when the suggestions are approved. 

If you would like to hop on a call and discuss things with me (who ever else would like to join we can ) Then we can share to the community what came out of the meeting.

**Comment by aguibert** [comment]
Hi Ryan, yea lets hop on a call to discuss the changes. I'm happy to let you make the changes for me =)

Drop me an email (you can find my email in my github profile) and we can set up time/logistics.

**Comment by aeiras** [comment]
This ticket is correlated to this ticket: https://github.com/eclipse/microprofile-marketing/issues/224.

**Comment by aguibert** [comment]
hi @rstjames and @aeiras, can we meet sometime to go over ideas for changes to microprofile.io? I'd be happy to contribute ideas and then let Ryan who is a WP expert make the changes

**Comment by aeiras** [comment]
Hey Andy, @aguibert 

The Projects page needs our love for sure, our means the DOERS in the Repos. 
The page is automatically updated directly via git. It seems b/c new Repos have not been linked, we are missing the updates across. Currently 24 Repos, all of them ought to be a part of this page. 

To that I say, YES-- lets look into this. 
Please add topic to next Community hangout to take a few minutes to discuss b/c the page is not a part of the WordPress person admin needed to update. There is where I see the lack of understanding when I see your wonderful follow up.

**Comment by aguibert** [comment]
@aeiras this topic has already been brought up on the MP hangout (see meeting minutes from June 11th 2019) and it's also been brought up on the mailing list. At this point I think we have agreement from the community so we just need to execute now.

Is @rstjames still involved with MP? Last I heard he was the website design expert, so I'd like to meet with him next to go over some ideas.

**Comment by rsoika** [comment]
I analyzed the problem a little bit more and from my view its the in-line-code style only like

     ...accessed via `ConfigProvider#getConfig()`.....

this can be fixed by replacing it with an italic style (underscore):

    ...accessed via _ConfigProvider#getConfig()_......

Only the readme.adoc files are affected. So it could be fixed by changing those parts of the readme files in github. I already tried to provide a push request for the microprofile-health project but was not able to comment my change in the right way with the correct signature so it was rejected.

**Comment by aeiras** [comment]
wow you are amazing @rsoika!

Can you provide a screen shot that shows the issue you encountered? We need to fix that first so that you can submit the change for review without "secretaries" 

Awesome follow up,

**Comment by aeiras** [comment]
@kwsutter  & @jclingan we have an issue with configuration of some sort. Trying to figure out with the help of Ralph the root. 

If either of you are able to throw some eyes at this,  that would be most helpful.  Thanks-
 If not able, I will get to it by the end of tmw. Cheers

**Comment by rsoika** [comment]
Here an example from microprofile-health:
current status:
-------------------------------------------
![image](https://user-images.githubusercontent.com/1339124/72742804-c8595c00-3baa-11ea-9b52-eed28a4cfc3d.png)
-------------------------------------------

with the replacement of inline-code to italic style:
-------------------------------------------
![image](https://user-images.githubusercontent.com/1339124/72742900-f2128300-3baa-11ea-958f-952139cf65c4.png)
-------------------------------------------

I am not able to test the complete process. But I guess this will solve the problem

**Comment by aguibert** [comment]
hi @rsoika and @aeiras, the issue you are discussing is separate from the intent of this github issue. This issue is for discussion about a high-level redesign of the microprofile.io website, but you are discussing a code formatting issue. Can you please move the discussion to a dedicated github issue?

**Comment by aeiras** [comment]
You are correct Andy, there are many pieces to this task. Your recommendation is excellent. @rsoika do you know what git to use? main one works.

**Comment by Emily-Jiang** [comment]
@rstjames how about meet up this week or next week with @aguibert and me to discuss this issues regarding microprofile.io improvement?

**Comment by aguibert** [comment]
After a webex call between @Emily-Jiang, myself, and @rstjames, we've decided to pick this item up again. Since there is a lot of work to be done, we are going to break it down into 3 phases, each will be tracked by a separate work item:

## Phase 1: Update microprofile.io homepage to show the component "tower" (#285) 

## Phase 2: Create new template for each MP component (#286)

## Phase 3: Socialize template from phase 2 and allow components to start updating to the new template format (#287)

**Comment by aeiras** [comment]
Hola @aguibert, 

The work done this year adjust the main page of MP is wonderful. 
More work will be completed in 2021 around Projects' page. 

I will close this ticket since the other tickets already contain the future work focus. Super fun stuff!
