### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor.

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#104]
Name: Edwin Derks
Email: ederks85@gmail.com

**Comment by rstjames** [comment]
You've just been added as a WP MicroProfile blog contributor. You could get an email with a WP password and login information. 
Here is a link that will explain the process of contributing to the MP blog. https://github.com/microprofile/wpsite?
Welcome and thank you for your future contributions!

Have a great day,
Ryan St. James
