### ISSUE TITLE
MP Blog post on Security with JWT

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#105]
Just to let you know, I have a blog entry available on the Tomitribe website.
Here is the tweet for it

https://twitter.com/tomitribe/status/1134104729628422145

If you want to cross post if with MicroProfile. That's ok.

**Comment by aeiras** [comment]
@jeanouii please read the contribution guidelines CTA directly from the MP blog link. I will close this ticket to enable a proper follow up. :)
