### ISSUE TITLE
Update the site and prepare marketing for MP 3.0 release

### ISSUE THREAD

**Issue by OndroMih** [microprofile/microprofile-marketing#106]
MP 3.0 is about to be release next week: https://groups.google.com/d/msg/microprofile/Fffl5STEUmc/gv6K_OOuAgAJ

**Comment by aeiras** [comment]
Thank you amazing @OndroMih and Kevin! :) 

- [Blog Announcement using Kevin's wiki shared via forum- word draft](https://docs.google.com/document/d/1LEBgIJO9XQDagHfO7w2CSI85vWJqH8YOqueVyVBrVV4/edit#)

- [wordpress import blog above](https://microprofile.io/wp-admin/post.php?post=6242&action=edit) completed under draft version
Only editors or Admin have access (100% content from word draft that welcomes anyone to suggest edits, if needed)
- [New ticket created: Design banner and twitter push ](https://github.com/eclipse/microprofile-marketing/issues/107)

**Comment by aeiras** [comment]
@rstjames where is the Release wiki documentation that MP releases have followed from past iterations?

If not available, we can start the wiki in this Repo wiki currently empty. FYI to bring attention to next Marketing meeting to enable those active to collaborate on the Wiki.

**Comment by cealsair** [comment]
I'm working on this already. I'll update ticket as soon as draft is ready to be reviewed. Thank you

**Comment by aeiras** [comment]
that is wonderful @cealsair! we have the template ready, so I copy/paste. 
Please do not adjust the first sentence of the template already as part of the draft annoucement.

Gracias!
