### ISSUE TITLE
Twitter MP 3.0 Release Announcement 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#107]
Ryan, 

Lets create a nice design for 3.0 release due on June 11th. Therefore all work must be completed and scheduled before the 11th.  Thanks! 

[Original ticket](https://github.com/eclipse/microprofile-marketing/issues/106)

**Comment by aeiras** [comment]
I have added the draft of [ blog annoucement](https://microprofile.io/wp-admin/post.php?post=6242&action=edit) in MP wordpress under draft. 
It misses the picture of the header. Can we add header the traditional pic header with updated version to the draft? 
Questions, shoot! :)  @rstjames

**Comment by rstjames** [comment]
@aeiras I will add the visual that I create for the 3.0 release card on the home page. 
This will be done tomorrow morning.

**Comment by aeiras** [comment]
Just great! 💛

**Comment by rstjames** [comment]
The release image and tweet has been set for M
![MicroProfile-3 0-release](https://user-images.githubusercontent.com/12132146/59352939-2e7f2600-8d22-11e9-8a0b-3599fffea5cf.png)
onday sense @cealsair has already tweeted about it .
