### ISSUE TITLE
Releases Designs

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#108]
@rstjames please make sure that the orignal file is dropped and housed under the Release folder >[Design](https://drive.google.com/drive/folders/1MLxGW3XsLKqKxSbnHFQgUurZ-WCveCAH)

**Design Requirements:** 
- imagine _must_ be adjustable by anyone besides you

- imagine must be the same use for the Blog annoucement header and the twitter push

All means that 1 image must be scalable and easibly adjustable by anyone in branding. 

Questions, shoot!

**Comment by rstjames** [comment]
3 designs have been added. 1 speaker, 2 speaker and 3 speakers 
https://drive.google.com/open?id=1MLxGW3XsLKqKxSbnHFQgUurZ-WCveCAH

**Comment by aeiras** [comment]
really like the option of multiple speakers card, great Ryan! 

Feedback @rstjames 

- Replace Conferences to Event

- Add git option below twitter

- instead of the dark background, lets use the MP 3.0 and future releases as the backdrop of the design. (MP has 3 releases per year, *using that design* won't be a monthly hustle as releases as set in stone with formal dates that gives us plently of time to update to latest version) 

- lets make the MicroProfile and the mark larger using the entire upper section of the card. 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/10731224/59227636-b2060f00-8b8a-11e9-9611-d155a808a89c.png">

**Comment by rstjames** [comment]
@aeiras 
_instead of the dark background,_ 
We can not do this or the text will not be visible. This is why the background is darker and follows the branding of MP 

_lets make the MicroProfile and the mark larger using the entire upper section of the card._
I will make it a little larger but we can not fill the space. In the file there is a live area this logo was stay in or it will be cut off when posted.

**Comment by rstjames** [comment]
@aeiras Just realizing this is for releases. I confused this with another ticket for Sessions... I need to make new images.

**Comment by rstjames** [comment]
already made a release image that will go out on monday. Because @cealsair already sent out an tweet today. Refer to this ticket https://github.com/eclipse/microprofile/releases/tag/3.0

This is the image being used:
![MicroProfile-3 0-release](https://user-images.githubusercontent.com/12132146/59289653-db03ce00-8c76-11e9-9bfb-435587d54726.png)

**Comment by rstjames** [comment]
@aeiras Folder has been updated with new files.

**Comment by aeiras** [comment]
very cool!
