### ISSUE TITLE
Create a Wiki that documents MP Releases Steps

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#109]
[MP Release Guidelines-Marketing](https://github.com/eclipse/microprofile-marketing/wiki/How-to-Process-MicroProfile-Releases)

**Comment by aeiras** [comment]
@rstjames using this wiki, we can start populating the branding side of what happens with each release. As you know, the next release will be technical and heavy populated by the 3 MicroProfilers involved in the release. questions, shoot. Please bring it up to the next Marketing meeting to enable others to help with the write up directly via this wiki Repo. Thanks.

**Comment by rstjames** [comment]
@aeiras Updated

**Comment by cealsair** [comment]
The process is detailed in the following document already:
https://drive.google.com/drive/u/1/folders/1Dq3Cvt2DHt9VnApwyAZ-M61rC19BA4GB

@aeiras could you please update your wiki page with the content of the doc above?

Thank you,
Cesar

**Comment by aeiras** [comment]
pretty wonderful, thanks @cealsair!
