### ISSUE TITLE
Create card for MicroProfile 3.0 release to place on MicroProfile.io landing page

### ISSUE THREAD

**Issue by cealsair** [microprofile/microprofile-marketing#111]
The text for the card follows:
"Eclipse MicroProfile 3.0, which builds on the 2.2 version, updates the Rest Client, Metrics, and Health Check APIs. This release introduces specification improvements, clarifications, and a richer set of capabilities."

**Comment by aeiras** [comment]
@cealsair the template used to update MP 3.0 is great, you rock! 

I have submitted a few changes directly on the draft. 
The draft misses the header but @rstjames will make sure it is added before scheduling the tweet.

**Comment by rstjames** [comment]
Tweet has been made and scheduled for Monday sense @cealsair Cesar already sent out a tweet today. This will catch some more people who might have missed it today.

**Comment by rstjames** [comment]
Blog header image, links on home page, 2nd card info and visuals have been updated on the site. 
@cealsair @aeiras
