### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor.

### ISSUE THREAD

**Issue by rsoika** [microprofile/microprofile-marketing#112]
Ralph Soika
ralph.soika@imixs.com

**Comment by aeiras** [comment]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/10731224/59312301-83a73300-8c61-11e9-9ed6-b5f6f8425a19.png">

Thank you choosing to become THE 39 #MicroProfile content/video/tutorials Contributor Ralph!
