### ISSUE TITLE
JCONF COLOMBIA 2019

### ISSUE THREAD

**Issue by otaviojava** [microprofile/microprofile-marketing#113]
Question: Does MP cover Jakarta EE related? I did not find anything on the Jakarta EE projects:
https://github.com/jakartaee

* Conference: JCONF COLOMBIA 2019
* Name of the session: Jakarta EE Meets NoSQL in the Cloud age
* Name of the speaker: Otavio Santana
* link of the event: http://www.jconfcolombia.org/2019/index_EN.html
* Twitter: @otaviojava
* Date: July 5th and 6th 2019
* Location: Medellín, Colombia
* tweet message:  Let's move Jakarta EE forward with the first specification: #Jakarta #NoSQL with an easy way to move your enterprise application to the cloud.

**Comment by aeiras** [comment]
Hola beautiful Otavio! 
Your session seems to has nothing to do with MP. Please submit it to the Jakarta ee community forum instead for proper coverage! Cheers

**Comment by otaviojava** [comment]
Hey @aeiras , how is going?
are you referring to the email list?
https://accounts.eclipse.org/mailing-list/jakarta.ee-community

**Comment by aeiras** [comment]
Copy paste as you have provided everything perfectly above & send it to the WG EMAIL 📧 with CC:  jakartaee_news@eclipse.org! 

💪🏼 Questions ping me via this issue & close that email with the requirement to get a reply of receiving your submission! Thanks for sharing Jakarta EE magic! ✨
