### ISSUE TITLE
new post review: MP Config CustomSources with Database

### ISSUE THREAD

**Issue by rsoika** [microprofile/microprofile-marketing#114]
please review my new blog post about 
MP Config CustomSources with Database

https://microprofile.io/wp-admin/post.php?post=6253&action=edit

I am not sure about the best title for the blog:

Microprofile CustomConfigSource and EJBs
Microprofile CustomConfigSource and Database
Microprofile CustomConfigSource and CDIs

**Comment by aeiras** [comment]
Ralph, 

Review is based on Dev-MicroProfilers' ability to provide technical review assistance based on their own priorities. 
 Without private exchanges with wonderful Mark and Emily, I have blindly *just* add them to this ticket b/c the two of them are the Conf JSR spec leads.   _Hola you two_, can you please delegate to others  via comments or own review of the blog? Soft deadlines for reviews are 5 work days not including the wknd. :) Thanks for being awesome.

**Comment by aeiras** [comment]
@rsoika 
Hola Ralph, I have reviewed your blog, now [published ](https://microprofile.io/blog/)

Please note the few adjustments in copy/edit done, hopefully you can see why it was adjusted on such a way. Your future MPblogs could be first dropped on[ MP blog drive](https://drive.google.com/drive/folders/1yonVuzmgpH_Mr3WgoqQEYywoJJjOmKBD) to enable "suggestive mode" collaboration, before blog is imported to WordPress!

Congratulations on publishing your very 1st MPblog! if you tweet, we could re-tweet it.

**Comment by aeiras** [comment]
Because of the thises of your blog: _In this Blog I will show how you can implement a Microprofile ConfigSource based on values read from a Database._ title uses Database :)

**Comment by rsoika** [comment]
@aeiras  this is great, thanks a lot for your help!

**Comment by aeiras** [comment]
It is my pleasure Ralph! :) you followed up quickly and nicely on adding your MP blog to the website. Thanks for being patient while we got to your ticket! 

Please close ticket, if you push the MPBlog via twitter, we can MP re-tweet it-- optional step. 

Most importantly, thanks for scalling what you are leaning about MP and choosing to share it via writtenform. It is actions like yours what make being an OSS Contributor fun & light! cheers
