### ISSUE TITLE
MP Architecture call moves to Zoom video instead of Bluejeans

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#115]
@rstjames just found out that we finally dropped bluejeans from MP architecture call. We need to drop old link for the recurring reminders of the call with new [link](https://eclipse.zoom.us/j/949859967) 
Thank you! 

Please use this thread for reference. https://twitter.com/cajasmota/status/1141048807368658945

**Comment by aeiras** [comment]
@rstjames this fix will need to reach all 2019 already scheduled pushed. sucks but there is no way around it. thank you!

**Comment by rstjames** [comment]
Join & #contribute to the @MicroProfileIO Architecture Call every 4 weeks on Tuesday.  http://bit.ly/2V4TwkY #Proactively help open & close PRs during each meeting. Add what matters to you to the agenda via minutes https://bit.ly/2UMWIBx
See you there! 

#OSS #opensource 

______________________________

Join TOMORROW’S @MicroProfileIO Architecture Call & #contribute. http://bit.ly/2V4TwkY #Proactively help open & close PRs during each meeting. Add what matters to you to the agenda via minutes http://bit.ly/2UMWIBx
See you there! 

#OSS #opensource
