### ISSUE TITLE
[Follow up] Spanish Blog draft 5/29/19 by Jorge

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#116]
Jorge @Motojo, 

Earlier this week, I noticed under WordPress content review that you have a working- blog still dated 5/29. Without rush, adding a reminder for you here. :)  Remember you are most welcomed to use the blog drive draft first to welcome Spanish review, if you consider it valuable. https://drive.google.com/drive/folders/1yonVuzmgpH_Mr3WgoqQEYywoJJjOmKBD
<img width="893" alt="image" src="https://user-images.githubusercontent.com/10731224/59953794-93c7cb00-9436-11e9-8938-65f9c4bf46d1.png">

[WP link](https://microprofile.io/wp-admin/post.php?post=6235&action=edit)

**Comment by cajasmota** [comment]
Thank you @aeiras 
I didn't knew about the blog drive for drafts...
I will use it from now :D

**Comment by aeiras** [comment]
Your feedback will go directly to the content guidelines to make sure the drive for draft is stated clearly as an option to use for copy/edit help - etc! Just amazing 😉 form to follow up via this ticket #LatinArmada MicroProfiler 🥋
🤗

**Comment by aeiras** [comment]
@Motojo, 
 DO: 
[Feel welcomed to submit a PR with improvements if you find that guidelines can be improved Jorge](https://github.com/microprofile/wpsite/blob/master/README.md)

Cheers!

**Comment by cajasmota** [comment]
@aeiras 

The drafts (Spanish and English) are ready to review at the blog drive for drafts...
Do I need to create an issue here on github for them ?

**Comment by aeiras** [comment]
Yes! 💛  Jorge💪🏼
One per blog- specially if you have written same blog in your native language & also in English, you need two submit 2 tickets 🎫! ⭐️ Formidable form
