### ISSUE TITLE
[Blog] [Review] [Spanish] Microprofile and Bean Validation blog post draft 

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#117]
Hello everyone, I just wrote a blog post about Bean Validation and MicroProfile, can you review it please?

This one is located at the blog drive for drafts, spanish version

thanks!

**Comment by cajasmota** [comment]
Hello!
I just moved the post from the drive for drafts to Wordpress, also submitted it for review.

The post can be found at: https://microprofile.io/?p=6235&preview=true

**Comment by aeiras** [comment]
@Motojo i will process this content today :)

**Comment by aeiras** [comment]
[Published](https://microprofile.io/2019/07/10/valida-tus-microservicios-con-microprofile-y-bean-validation/)

Please #LatinArmada tweet and we will retweet from the MP handle! :)

**Comment by cajasmota** [comment]
Thanks @aeiras !

I just noticed that the first block of text on the spanish version is missing... and I can't edit the post after is published :( 

https://docs.google.com/document/d/1N9KE50dp8UXkmfRnx_YyKnb0lFcMBjvznJWQRHpJTjg/edit

**Comment by aeiras** [comment]
Yes, i noticed that too and tried to add it and for some reason I cannot. 

can you log-out and try it again?

**Comment by aeiras** [comment]
@Motojo go to wordpress to do changes directly. you as the contributor have full access to adjust it. 

not sure why i cannot do it. Just log-in as an Admin instead of editor and cannot do it. maybe a temporary WP bug... lets see

**Comment by cajasmota** [comment]
I just duplicated the post and fixed it, also I submitted it for review

Can you delete the previous one and publish the new/fixed one please ?

**Comment by aeiras** [comment]
that worked perfectly Jorge! 

here you go: 

- [ X] [2nd try with repo link! : )](https://microprofile.io/2019/07/10/validate-your-microservices-with-microprofile-and-bean-validation/)
