### ISSUE TITLE
[Blog] [Review] [English] Microprofile and Bean Validation blog post draft

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#118]
Hello everyone, I just wrote a blog post about Bean Validation and MicroProfile, can you review it please?

This one is located at the blog drive for drafts, english version

thanks!

**Comment by cajasmota** [comment]
Hello!
I just moved the post from the drive for drafts to Wordpress, also submitted it for review.

The post can be found at: https://microprofile.io/?p=6281&preview=true

**Comment by aeiras** [comment]
@Motojo  i will process this content today :)

**Comment by aeiras** [comment]
Jorge, 

[Published](https://microprofile.io/2019/07/10/validate-your-microservices-with-microprofile-and-bean-validation/)

did you submit the git PR into MP repo yet? If not, highly recommend you submit it to the repo :) 

Again- tweet so we can push via the MP handle.

**Comment by cajasmota** [comment]
Thanks @aeiras 

Into what repository can I submit the PR ?

**Comment by aeiras** [comment]
I will say, ask in the forum first. 
At first hand it is in the main repo, but when unsure, just share the actual post published in english to enable feedback. :)

**Comment by cajasmota** [comment]
hi @aeiras 
I got a problem with the english version of this post.

Yesterday it was published, I tweeted about it and even the MicroProfile Twitter account retweeted the post.... 

but after that the post went from published to scheduled to publish today, and the URL of the post changed and everyone who see it on twitter gets an 404 errror page.

https://twitter.com/anbusampath/status/1149176981025505281
https://twitter.com/gunnarmorling/status/1149188749043146752

The URL changed from:
https://microprofile.io/2019/07/10/validate-your-microservices-with-microprofile-and-bean-validation/

to:
https://microprofile.io/2019/07/11/validate-your-microservices-with-microprofile-and-bean-validation/

**Comment by aeiras** [comment]
@Motojo, 

You are correct, something was changed and sadly I cannot backtrace it to see what happen or adjust it to original published date and time.   I am sorry that media tweets are also a mess. We can do better. Lets try again.   

- [ X] Are you ok to retry with media the english tweet? I have un-retweet it just now and we can try again. there is no other way. Gracias. 

Thanks for being wonderful and understanding. I have sent to the MP forum a quick follow up :) sort of related to this!

**Comment by cajasmota** [comment]
hi @aeiras 

I already made a new tweet about it:
https://twitter.com/cajasmota/status/1149354453260210177

Thanks to you to follow up this kind of problems :)

**Comment by aeiras** [comment]
Gracias por ser parte de las mejoras que son posibles con acciones como las tuyas Jorge! 

Abrazos Latino :)
