### ISSUE TITLE
[Content Contribution]  NewsLetter 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#119]
Via MP [forum thread](https://groups.google.com/forum/#!topic/microprofile/VajnJuPkpTQ)
MicroProfiler Gordon reminded us of bringing forth MP NewsLetter as a valuable feature that could be implemented in Q3. (first we need to tackle the logistics and keep it as bare and minimal to avoid delays) Thanks awesome @hutchig :)  

Last year, a big part of the MP website got moved to wordPress, before that-- the creation of MicroProfile monthly (_we could start with quarterly timeline_)  newsletter was not possible. 

-  Brainstorming welcomes MicroProfilers to contribute  shapping the very first iteration in Q3 of the letter [.1v_draft Content NewsLetter & Logistics] (https://drive.google.com/drive/folders/1rCCF2pjEgLVUZz5nvUZeUAS3ktaztxO1)

**Comment by Emily-Jiang** [comment]
I am sure about the need of creating MP newsletter. Eclipse Newsletter reaches a big audience and they always ask for input. If anyone wants to write any blogs, I would recommend to go there. What is the difference of doing the newsletter and publishing the blogs directly on wordpress? I don't feel there is an immediate need for this.

**Comment by aeiras** [comment]
hey beautiful Emily, 

We are not talking about not contributing to the EF Newletter. On the contrary, this is a totally new feature exclusive to MicroProfile. 
As such, allow me to explain why I disagree with not prioritizing this initiave. MP has *finally* the tooling via wordpress to implement the monthly newsletter without major husle & without major dedicated time to push it forward each month- if something that is reitarable is not scable, thats just a waist of implemention & a waist of human capital resources. :)  

MicroProfile can benefit from at least 1 page monthly newsletter if it chooses to be more transparent and constant on how it shares its develpment accross. Something like a picture of it, that won't be the same the next month b/c as an ### OSS project its growth is fluid. 

As added to the brainstorming draft[ GOALS]

- [ https://github.com/eclipse/microprofile-marketing/issues/103] already in motion- work in progress 

(https://docs.google.com/document/d/1Zby7N_x8iYft5ZLZz_WHsSCUOumORfeeNDi_Bu9CtkA/edit#heading=h.oymnw3nlvwib) for the newsletter
- share exact stats of the particular month, example May: 
<img width="159" alt="image" src="https://user-images.githubusercontent.com/10731224/59985343-e72c4b80-95e5-11e9-956c-04eea7a2d96e.png">
-focused on core goals broadcasting that are a constant:
GOALS

- [ Content]  Compile into one [1] written document anything MP worthy 

- [ Newsletter how to iterations]  Foster Steward mentality — scale/minimal debt

- [Forum highlight:  ]  State the hottest / gruesome MP forum topic via a short summary
Contribute via: forum,  Repo & hangout [links] 

- [Stats count on #: ]   A) google forum member count; b) project individual monthly commits activity; C) twitter members; d) number of MP committers… 

- [Call-to-Action: ]  initiatives relevant to the respective month- relevant to the future month

Example: 

- For MP Speaker : Submit your session

- For Content creators: Submit your blog/video/tutorial/presentation

- OUTreach welcome to MP: Participate on Interview Onboarding of new Microprofiler

- [ Constant resources] 

 added to the footer of letter: 
Link to wiki on how to start contributing 
Inventory of MP written [likely housed under new resource page] content available: case studies (0); business white paper(1); technical white paper(1); e-books (1)

**Comment by aeiras** [comment]
discussed for the June 7th marketing [call](https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit#bookmark=id.5i2c07v5r0b1)

and related to [[MP Blog] RSS, Subscribe Button and Automatic Email Notification #516](https://github.com/eclipse/microprofile-marketing/issues/516)

the conversation will be ongoing based on gauging the need by the readers to consume such newsletter.

**Comment by aeiras** [comment]
discussed months ago and not desirable for now.
