### ISSUE TITLE
Contributor's/Committer Must know Guidelines

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#12]
draft being created by Heiko! :)

**Comment by aeiras** [comment]
@phillip-kruger thanks for being awesome! :)

**Comment by phillip-kruger** [comment]
Traveling at the moment. Will get to this a.s.a.p

**Comment by phillip-kruger** [comment]
The requirement is to change the link "Want to become a contributor? " on this page "https://microprofile.io/contributors/" to not go to the yaml file as it currently does:

![image](https://user-images.githubusercontent.com/6836179/56973502-3f5a4a80-6b6d-11e9-9a90-34008b836d86.png)
currently goes to:
![image](https://user-images.githubusercontent.com/6836179/56973540-5305b100-6b6d-11e9-8bb4-4b089330953c.png)

What I have done:
- Copied the text from one of the project CONTRIBUTE.md and modify it to be more general. We might want to get someone with copywriter skills to look it over.
- Use the github API to query all microprofile projects in the eclipse org, and list them in a page with links to them.
- Use bootstrap on the page, but we need some wordpress expert to make this work in wordpress and make it pretty. Mine it just to show. 

This is how it currently looks like:
![image](https://user-images.githubusercontent.com/6836179/56973885-09699600-6b6e-11e9-81ef-b82edb3eb8ca.png)

See attached files:

[contribute_page.zip](https://github.com/eclipse/microprofile-marketing/files/3131967/contribute_page.zip)

**Comment by aeiras** [comment]
@phillip-kruger the updates are already pretty good. I hope you can join today's hangout and have added this follow up to the agenda :) thanks for being awesome!

**Comment by phillip-kruger** [comment]
Bug in the prev javascript. See this rather.
[contribute_page.zip](https://github.com/eclipse/microprofile-marketing/files/3132794/contribute_page.zip)

@pilhuhn - maybe you can have a look as this might overlap with what you said you have on your TODO list ?

**Comment by phillip-kruger** [comment]
B.t.w. if it's not clear in the screenshot above, the project are being pull in dynamically, so if we add a new project it should 'show up' in the page.

We might be able to do this better (I am not great with JavaScript) and we should cache the result locally I would suggest. But for now any feedback welcomed.

**Comment by phillip-kruger** [comment]
@Emily-Jiang please can you also look as you had some ideas w.r.t this. Thanks

**Comment by aeiras** [comment]
hey beautiful MicroProfilers, 

Once again this week and last we were asked via the forum and via the hangout HOW to Contribute. 

We need the general link that was last populated so that it can be added to the MP. contributor's Call-2-Action bottom page. 

@phillip-kruger can you please own the follow up? Thanks!

**Comment by phillip-kruger** [comment]
Hi @aeiras .

Yes this has been here a while. I would really want someone (@pilhuhn / @Emily-Jiang / anyone else) to look this over. And then we need (I assume @rstjames ) to get this into the wordpress site?

**Comment by pilhuhn** [comment]
I think this is pretty cool (thanks for doing that!!!) and works nicely. 
The only comment I have is that the ordering of the bullet points should be changed. 
The current list shows some "pretty heavy" contributions at the top, while _I_ have the feeling that we should start with the easy ones 

* join meetings
* join discussions
* join project chat on gitter
* open issues
* provide pull-requests

Ah and for "Join Gitter", the sentence could have an addition of (the chat icon on each project in the list below). As it stands right now, users may feel a bit lost.

**Comment by phillip-kruger** [comment]
Hi @pilhuhn. Awesome, thanks for the feedback!

I'll change a.s.a.p.

Thanks :)

**Comment by aeiras** [comment]
Correct @phillip-kruger! 
As soon as the document is curated, @rstjames will add it as the CTA in the Contributor's page in the website. :)

**Comment by phillip-kruger** [comment]
Hi @pilhuhn and @aeiras .

Changes done as request (see attached) @rstjames can have a look to get this into wordpress.

[contribute_page.zip](https://github.com/eclipse/microprofile-marketing/files/3412234/contribute_page.zip)

**Comment by aeiras** [comment]
everyone who work on the doc is formidable. !:) 
 
@rstjames do you need anything else to update the Call to Action bottom from MP Contributor's page?

**Comment by rstjames** [comment]
@phillip-kruger @aeiras 

Sorry bit confused what you guys want done? I looked at the file and links me to a new page. 
- You want this to replace the top "contributors" link ? ( then the text should change to have it make sense)

Also sorry just seeing this ticket now... seems to be bit old.

**Comment by aeiras** [comment]
correct @rstjames, 

the Call to action on the Contributor's page needs to be adjusted. 
We are focusing on how easy it is to become a Contributor and the newest wiki provides a comprehensive documentation on where to go depending on the individual's interest. 

Follow up questions welcomed and thanks @phillip-kruger for owning task :)

**Comment by aeiras** [comment]
@rstjames, 

On Monday, can we please prioritize fixing the "Want to become a contributor" by first **changing** CTA to:

1. Become a MicroProfiler by

@phillip-kruger  zipfile above: contribute_page.zip is ready to go with exact data. it needs to be fixed. amazing stuff. :) 

Thank you,

**Comment by aeiras** [comment]
@phillip-kruger lets also add to the zip:

- below _Contribute Content
lets adjust it first to state:  _via blogs, tutorials, videos_, etc_ [please adjust it to make it general]

Speaking about MicroProfile: tell us via [MicroProfile Sessions_Social Media Coverage](https://github.com/eclipse/microprofile-marketing/issues)

Thanks awesome MicroProfiler

**Comment by rstjames** [comment]
@phillip-kruger I am trying to update the link but the zip you attached is not really a link. I attached it to the button but it did not work . 

Is it hosted somewhere or am I doing something wrong....

**Comment by aeiras** [comment]
@rstjames, 

I have created the Wiki under MKTG repo to enable the file to become a living document that can be easily adjusted by anyone with PRs. 

[Wiki](https://github.com/eclipse/microprofile-marketing/wiki/How-to-Become-a-MicroProfile-Who-Moves-Project-Forward!)

Are you able to copy/paste and create a-new or do you require further assitance?
@phillip-kruger you are most welcomed to import the awesome data in the wiki. :)

Anything a miss, lets fix it. Cheers

**Comment by phillip-kruger** [comment]
Hi @rstjames 
I can download the zip: [https://github.com/eclipse/microprofile-marketing/files/3132794/contribute_page.zip](https://github.com/eclipse/microprofile-marketing/files/3132794/contribute_page.zip)

Let me know if this does not work for you and we can make another plan

**Comment by rstjames** [comment]
Hi @phillip-kruger 
Ok so you want them to download a zip instead of sending them to a web page. Seem strange and adds an extra step but if its done this way for a reason I will add the link to the page.

**Comment by rstjames** [comment]
@aeiras @phillip-kruger I just saw Amelia's comment above ours. 
Do we think its better to send them to a wiki where we can explain/give details on what they are downloading?

**Comment by phillip-kruger** [comment]
No. The zip contains html and js. Its an example of how the page should
look like.

So no download, but that html (also see screenshots in the thread) in the
wordpress site

**Comment by aeiras** [comment]
@phillip-kruger, 

Ryan has nicely updated the call to action to the zip, thanks Triber! @rstjames 

Now, the C2A is not scalable as project continues to evolve and we need it to be Wiki PR friendly to welcome betterment by the users who get to it.

For instance, with current new set up, it took me 3 clicks to get to **how to** 
Wiki is ready to welcome a version of what you nicely have put into place in the zip. if we drop the example and leave just the parts, I think that can work nicer. However, i might not be understanding your reasoning so always happy to weight until the next Hangout to discuss. :) 

[How to Become a MicroProfile Who Moves Project Forward](https://github.com/eclipse/microprofile-marketing/wiki/How-to-Become-a-MicroProfile-Who-Moves-Project-Forward!)

**Comment by phillip-kruger** [comment]
Hi @aeiras.
Happy to change it to the wiki. Just want to check if I understand you correctly. We are saying that rather than updating the Wordpress site, we can create a wiki page with the "How to contribute" page ? Is that correct ?

**Comment by rstjames** [comment]
@phillip-kruger @aeiras 
I think we need to have a call. Not sure we are all on the same page. If I understand it now... the HTML/ zip is to implement into the wordpress site as a MP webpage? 

Please let me know what days and times work for you. 
Ryan

**Comment by phillip-kruger** [comment]
@rstjames happy to do a call. I am fairly open tomorrow ( i am +02:00).

Ler me know.

**Comment by aeiras** [comment]
hey you two, @phillip-kruger and @rstjames, 

The call is too early for me, so via this thread-- I will do my best to clarify the vision of Call 2 action:

-  CTA needs to use same standards as the C2A we have today for contributing content to wordpress. 

- the Wiki needs to exist under Git for that reason, only then this page will be the ownership of anyone who collaborates in MP. Example, today-- the blog wiki has 5 contributors instead of just 1 person managing. 

- we don't want the C2A to be human handled or live in Worpress. That is not needed or healthy. 

I hope that helps clarify that Wiki is needed as we are using Blog wiki as the root example for process. Thank you both for meeting and soon closing this awesome ticket :)

**Comment by cesarhernandezgt** [comment]
Hi @aeiras @phillip-kruger @rstjames 

Currently when you visit the page: https://microprofile.io/contributors/ and you click the button "Become a MicroProfile Contributor", the website user obtains a zip file containing the html page and javascript created by Phillip.

I have a proposal reusing as much as possible what we currently have:

1. I created this draft page on wpengine https://microprofile.io/?page_id=6417&preview=true (you need to be authenticated to see the page)  containing 90% of the html page from the zip file.
2.  I removed the project section since my opinion is that the website already have a section with the project content.  
3. The purpose of the contributor page is that this is the redirect the user would get after clicking on the "Become a MicroProfile Contributor" from the  https://microprofile.io/contributors/  page.

![image](https://user-images.githubusercontent.com/1454523/66962099-6dedb400-f02d-11e9-8a17-b782337467e3.png)

As for the Javascript code to show the list of projects, I see a big opportunity to replace the current API call the current website does to the REST endpoint to display: https://microprofile.io/projects/.   The current /project page rendering isn't  smooth as we would like. One issue that I think we can discuss in other thread is the fact that proposed Javascript from the zip file depends on Github public API but that API has a rate limit that we can eventually reach and that was the reason we have a Rest endpoint that does the caching for us.

**Comment by aeiras** [comment]
@cesarhernandezgt way to rock it with feedback! 

First, please lets use this ticket for the Project's page +1 on your feedback as it needs to be updated directly via Git activity and not a human [Update microprofile.io to be more developer focused #101](https://github.com/eclipse/microprofile-marketing/issues/101)

**Comment by aeiras** [comment]
@cesarhernandezgt, 

Main reason this issue exist is How to enable contributors to jump in without major acquirement of knowledge. 
If we go your route, can the page be adjusted by anyone? **if the requirement is that a WordPress Admin must update this page** is the it for it to go live, that is a flat no. We want something that can welcome improvement as new comers join and via actions make the HOW TO better. 

Thanks for the follow up,

**Comment by cesarhernandezgt** [comment]
@aeiras 
Base on your feedback, having wp engine author granths is not an option. This mean the process that is currently in place for blog post/interviews is out of the scope for the /contribute page.

The only approach I can think at the moment for making the /contribue page body as open as possible is kep the text in a readme from a github project, what a better place than: https://github.com/eclipse/microprofile repo.

My proposal straight forward proposal:

1. Let's move the text into https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc
2. That would be the redirect the user would get after clicking on the "Become a MicroProfile Contributor" from the https://microprofile.io/contributors/ page.

Othe proposal could be pulling the content from https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc using github API so the /contribute page as will be rendered inside microprofile.io instead of a redirect to the github project readme file.  But here we will be facing the same issue I described in my previous comment about Github API rate limiting and the need for caching the content somewhere.

**Comment by cesarhernandezgt** [comment]
I opened a PR for second approach: https://github.com/eclipse/microprofile/pull/137

**Comment by aeiras** [comment]
merged!

**Comment by aeiras** [comment]
@rstjames please update the C2A link and lets close this ticket :) 

@phillip-kruger your work on this was wonderful!!!!

**Comment by rstjames** [comment]
link is updated.
