### ISSUE TITLE
[media session template] for MP Interviews 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#121]
[Minimal requirements from first interview ticket](https://github.com/eclipse/microprofile-marketing/issues/123)

**Comment by rstjames** [comment]
@aeiras do you have some more info about this?

**Comment by aeiras** [comment]
@rstjames thanks for follow up, i added the first ticket as the base for the design & logistics! :) 
I will close that ticket since i created the design poorly  but on time. 
The drive has the space for the final designs to be dropped in. Please use this ticket to show a few versions to enable feedback before choosing 1 or 2 that are fun to use.
