### ISSUE TITLE
MP twitter handler

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#124]
Who has the MP twitter handler? Is it possible for me to access the twitter handle as well? Please let me know what process to follow.

**Comment by aeiras** [comment]
hey @Emily-Jiang, 

Go to the Media Management [document](https://docs.google.com/document/d/1O-p8HJxs13WEZs8Sl2NNrLuh4ofRngV_EKMDJJYa91g/edit) and follow up the setps process . :) 

Abrazos,

**Comment by aeiras** [comment]
haven't seen a follow up @Emily-Jiang! I will close ticket anyways and you can send email whenever is good for you. Hugs.
