### ISSUE TITLE
Help establish a virtual MicroProfile User Group or "MUG"

### ISSUE THREAD

**Issue by hutchig** [microprofile/microprofile-marketing#125]
The proposed MicroProfile User Group's primary goal is to help users get the most out of the MicroProfile movement. 

Underneath that goal, this issue tracks a social media marketing exercise that is to help
establish 'the' MUG and get it going.  The MUG (singular) is the global/virtual MicroProfile user group that is for any geography.

A primary objective of the MUG is to increase the flow of information and influence
**from users to implementors.**

To achieve this a vital long term aim is that it will be self supporting 
and **run and controlled by users**.

To attract users to take control of this group we need to target benefits to them
as people - "What's in it for them?"

1 - more influence on MicroProfile = better libraries
(and forgive me is this sounds cynical...)
2- the ability to say things in LinkedIn like "Chair of MicroProfile User Group 2020-present"
3 - the feeling that the vendors are giving them what they want

Using the definite article "the" implies a lot more kudos - hopefully enough to make
"founder" something that could go on a linked in profile anyway. 

**As such I request that noone rushes in and sets up such a group before
we have an opportunity to approach some of the prominant/active
users if they are interested in being 'in' (or better yet 'in control')
from day 0.**

I will troll through the existing MP activity and filter out
Payara/Tomitribe/Redhat/IBM 

These above goals are simply not covered by the admirable effort in
doing more pitches to existing Java User Groups.

As per:
https://groups.google.com/d/msg/microprofile/RA_-uai7U9g/W7XBwM9HBQAJ

With use of MicroProfile rising (https://github.com/search?q=microprofile)
I was wondering if the time was coming where a MicroProfile user group(s)  would appear,
if not dotted around then perhaps an internet/virtual based one?
Would it be confusing or partisan that a MUG would be MicroProfile focused and not Jakarta
or does it suit us to position MicroProfile as a bit more guerilla grass roots than Jakarta?
Is there enough 'space' between a MicroProfile User Group and the established network of JUGs
for there to be any value in the idea?

It is probably mostly the same set of people after all.

Of course for any local user group, whether it existed and what they did would be up to them.
Perhaps it could be good though for us to advocate for a global MUG but we'd have to get
the timing right. 

As well as the expected, there might be some'gaps' that exist at the moment that a MUG
might be a good angle to approach from:

1) There is no 'fanzine' written by and for users yet - but this opportunity might be attractive to independants when
the audience is the right size (I loved what Phillip Krüger (now at Redhat) did :-) )

2) There is no MicroProfile conference that relates to our emerging technology and ecosystem.
(I love the way devoxx is "from developers for developers")

3) How much requirements suggestion/prioritisation is there across and between the specs
that is initated by end users? I know much of it is by proxy but perhaps end users could benefit
from association?

Just thoughts, other people may have radically different ones. What are they?

**Comment by cajasmota** [comment]
Hello!

For this topic:  

> _2. There is no MicroProfile conference that relates to our emerging technology and ecosystem.
> (I love the way devoxx is "from developers for developers")_

There is an idea I've thinking about for some time, and a global "MUG" or something will be helpflul for that... What if local  JUG's, MUGs, or anyone organizes _micro conferences_ about MicroProfile? (no pun intended)

Not a big conference, just a day or half day with some talks and/or workshops focused only on MicroProfile?

As a MicroProfile contributors we can make an skeleton of how the micro conference can be organized, generate some assets like images for stickers, templates for presentations, maybe T-Shirt design, a recomendend agenda, etc so the organizers can focus on the venue, local sponsorship (if applicable) and CFP's.

the idea is to get in a period of time (3 months,  6,months, 1 year, etc) the "same event" replicated around the world organized by local user groups.

A succesful example of this type of micro conferences are the new _kotlin everywhere_ events around the world

**Comment by aeiras** [comment]
I love that many potential microprofile, code first, virtual & in person events could easily be set up if JUGs choose to own such options that they themselves will help create & participate as core stake holders from day 1! 

Gordon- I had such a fun time on the MUG topic this wknd 💛

**Comment by hutchig** [comment]
Love the concept of a MicroConference @Motojo :-) I was not aware of the Kotlin/Everywhere meme - reminds me of TEDx a bit. I could imagine a MicroConference happening as 1 one day event where I work.

**Comment by hutchig** [comment]
My belief is that creating a "JUG Roadshow" as per
https://groups.google.com/d/msg/microprofile/RA_-uai7U9g/duDAm7x0BQAJ
and framing it as a 'better' approach than this idea, which should be closed,
is not addressing the goal of this work-item.

I don't see any reason that JUG visits and a central MUG can't co-exist and
progress independantly.

**Comment by cesarhernandezgt** [comment]
+1 to MicroConference, they can be a mix of remote and onsite events too.
My 2 cent's is that it's easier for a JUG to embrace a "MicroProfile chapter" instead of creating from scratch an entirely new community "MicroProfile User Group"

**Comment by aeiras** [comment]
Set well stablished JUGs could do that as it is easier than renaming itself to be a participant. 

MicroProfile Chapter sounds wonderful Cesar !+1

**Comment by aeiras** [comment]
given the provided feedback via this ticket and [related ticket](https://github.com/eclipse/microprofile-marketing/issues/126) are you ok to close this ticket @hutchig?

If I missed something, do let me know. Currently seeing the inventory of issues and linking them to end Oct lighter. :) Thank you!

**Comment by aeiras** [comment]
We decided that there is no need for a new agreement during the Community call. 
Using the MP branding is open to anyone who wants to use it. :)
