### ISSUE TITLE
Help organizing "MicroConferences" about MicroProfile

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#126]
Hello!

This is related to #125 but it should be discused as a separated topic.
Also I will try to expose the idea on the Community Call of June 25.

For this on the #125 issue:

```
2. There is no MicroProfile conference that relates to our emerging technology and ecosystem.
(I love the way devoxx is "from developers for developers")
```

There is an idea I've thinking about for some time, and a global "MUG" or something will be helpful for that... What if local JUG's, MUGs, or anyone organizes micro conferences about MicroProfile? (no pun intended)

Not a big conference, just a day or half day with some talks and/or workshops focused only on MicroProfile?

As a MicroProfile contributors we can make an skeleton of how the micro conference can be organized, generate some assets like images for stickers, templates for presentations, maybe T-Shirt design, a recomendend agenda, etc so the organizers can focus on the venue, local sponsorship (if applicable) and CFP's.

the idea is to get in a period of time (3 months, 6,months, 1 year, etc) the "same event" replicated around the world organized by local user groups.

A succesful example of this type of micro conferences are the new kotlin everywhere events around the world

**Comment by hutchig** [comment]
Love the concept of a MicroConference @Motojo :-) I was not aware of the Kotlin/Everywhere meme - reminds me of TEDx a bit. I could imagine a MicroConference happening as 1 one day event where I work - low cost 1 day event.

**Comment by aeiras** [comment]
beyond wonderful wonderful @Motojo! 
great form on how to use ticket and trace history. You rock 💯

**Comment by cajasmota** [comment]
We can create a guide or template of how the event can be organized...
Again... the idea is to get the "same event",sharing a name, for example **MicroConference** XXXX City)

for example the  guide would be something like this:

https://docs.google.com/presentation/d/e/2PACX-1vRgpxfZ8nj2V3J_dfI9Z9_YW4vdP-neemsRlQHAVt0f8T614HAQIJQaoIKCMvVsafbg87uT-pppl-0Z/pub?start=false&loop=false&delayms=60000&slide=id.g4c0cd0eecf_0_1867

**Comment by aeiras** [comment]
MicroProfilers, 
@Emily-Jiang already transferred the [events excel sheet](https://docs.google.com/spreadsheets/d/1ThPhMwRsfLob1n0up0sUCzOEdfJUGVZVmakEyYcS5bU/edit#gid=0) to the MP conference drive. 

Given that events are self-organized, the next step is to create & scheduler a recurring media push to remind any interested Group: user/JUG/Conf to add their events in the sheet and submit git tickets for media coverage.  

@Motojo can you please help us close this ticket so that we can move to the next step git issue? Thank you, please pull me in once you do :)

**Comment by cajasmota** [comment]
Closing this issue :)

**Comment by aeiras** [comment]
[[Schedule a constant media push] Communities organizing events with focus on MP](https://github.com/eclipse/microprofile-marketing/issues/220)
