### ISSUE TITLE
MicroProfile comunity calls twitter image

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#127]
On Twitter the image of every tweet that anounces the comunnity calls says _bi-monthly_ but the calls occurs bi-weekly 

![image](https://user-images.githubusercontent.com/5105329/60125752-af3e1900-9749-11e9-9278-fbea7c7201d4.png)

**Comment by aeiras** [comment]
hey LatinArmada Jorge, 

bi-weekly & bi-monthly mean the same thing :)

**Comment by cajasmota** [comment]
oh... I thought it means every two months haha
sorry

**Comment by aeiras** [comment]
hahha, totally cool. I also get confused with the need to use both words. :) lol
