### ISSUE TITLE
MP Marketing announcement for standalone releases

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#128]
On 9th July, we would like to release MP Reactive Messaging and MP Context Propagation. Can Marketing team announce this releases? Please let me know what info you need for getting this to happen.

**Comment by aeiras** [comment]
@Emily-Jiang this is actually great as you can start documenting the wiki now ready to take everyone through the process. HERE is the[ issue: ](https://github.com/eclipse/microprofile-marketing/issues/109)

Note that the drive working document with the draft of what is used for the other releases is [here](https://drive.google.com/drive/folders/0B8_67yGf9LkLX096QUdxcTdueWs). 

Thanks for being the very first coder to push this awesome iniative. :) you are beyond awesome!

**Comment by aeiras** [comment]
This topic was covered on the 10/8 MP architecture call with @xstefank bringing it up. :)
We decided that a blog added to MP via original content &/or crosspost suffices to update patches. therefore, closing this ticket.
