### ISSUE TITLE
Dublin JUG - MicroProfile and Istio

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#129]
Conference Name: Dublin JUG
Conference website and social media links: https://ti.to/dublin-java-user-group/July-2019-Microprofile-Istio-Java-Champion-Emily-Jiang

About the session Title: MicroProfile and Istio with Java Champion Emily Jiang
Date and hour: 31st July
Tweet message: Join @emilyfhjiang @Java_Champions @IBMDeveloperUK  @DubJug on 31st July for 2 talks on #MicroProfile #Istio #Cloud. Free registration: https://ti.to/dublin-java-user-group/July-2019-Microprofile-Istio-Java-Champion-Emily-Jiang
Speaker name: Emily Jiang (@emilyfhjiang)

**Comment by rstjames** [comment]
![Microprofile-DublinJavaUserGroup-EmilyJiang](https://user-images.githubusercontent.com/12132146/61463085-01064780-a974-11e9-860b-50b4ea8d8fad.png)
@Emily-Jiang all scheduled
