### ISSUE TITLE
Skills matter keynote by Emily Jiang

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#130]
Conference Name: Skill Matters
Conference website and social media links: https://skillsmatter.com/meetups/12459-keynote-by-emily-jiang-on-on-stage-hacking-build-12-factor-microservices-in-an-hour#overview

About the session Title: Keynote by Emily Jiang on On Stage Hacking: Build 12-Factor Microservices in an hour
Date and hour: 23rd July
Tweet message: Join @emilyfhjiang @Java_Champions @IBMDeveloperUK @skillsmatter on 23rd July for a live coding session on #MicroProfile #12factor #microservice. After the talk, you should know how to create your own 12factor microservices easily https://skillsmatter.com/meetups/12459-keynote-by-emily-jiang-on-on-stage-hacking-build-12-factor-microservices-in-an-hour#overview 
Speaker name: Emily Jiang (@emilyfhjiang)

**Comment by Emily-Jiang** [comment]
@aeiras @rstjames can you twitter the above asap so that people can sign up for this?

**Comment by rstjames** [comment]
Join @emilyfhjiang @Java_Champions @IBMDeveloperUK @skillsmatter on July 23rd for a live coding session on @MicroProfileIO #12factor #microservice. After the talk, you should know how to create your own 12factor #microservices easily http://bit.ly/2ZU20gB 

#codenode #opensource

![MicroProfile-KEYNOTE-Emily](https://user-images.githubusercontent.com/12132146/60283363-43a2aa00-9909-11e9-86d9-849c65780358.png)
