### ISSUE TITLE
[WordPress timezone] What is it? AND did anything change in WP? 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#133]
@rstjames, 

Today, we have encountered issues with the posting of content via the blog.

I need to know what timezone is being used and if not using PDT, please set it to that timezone. Thanks!

<img width="277" alt="image" src="https://user-images.githubusercontent.com/10731224/61013100-207af000-a336-11e9-8372-47ad01427d27.png">

Also, I have a question about wordpress. Did anything was changed on how we review & publish blogs?  
It seems that after a blog is published, there is no way to edit the published post. This we want to revert to old version. Making duplicates and having to redo the work is not scalable.

**Comment by rstjames** [comment]
@aeiras 
can view the timezone in general settings. 
<img width="633" alt="Screenshot 2019-07-17 17 44 11" src="https://user-images.githubusercontent.com/12132146/61390241-ad83f300-a8ba-11e9-952a-731c1eb73528.png">

As for editing blog post. Nothing has changed. It should be able to edit. WIth our more info or example I can not give a better explanation or solution

**Comment by aeiras** [comment]
@rstjames please lets change it to PDT.

**Comment by rstjames** [comment]
@aeiras May I ask why? Will we inform people that it is now PDT? Don't see how this fixes anything when a lot of the people are in Europe/ all over the world. Just curious. OK changing to whatever :) 

But in wordpress we can set UTC time. I believe PDT is +7 hours. Or we set it by city. 
<img width="247" alt="Screenshot 2019-07-19 13 40 50" src="https://user-images.githubusercontent.com/12132146/61532670-d7f4be00-aa2a-11e9-8ee0-0174a859701e.png">

**Comment by aeiras** [comment]
For now, let’s change it. It is based where the reviewers are located, in this case the 2 more actives are in the USA. 
Bias reason— currently I am the one publishing 95% of the content, when publishing  or scheduling it  becomes problematic due to time zone. Thanks!

**Comment by Emily-Jiang** [comment]
We need to put the blog review in our routine. I plan to review and publish blogs. Thank you @aeiras for doing the majority of publishes! Can't we set time zone to either UTC or GMT? It is weird to set to some arbitrary timezone though.

My 2cents.

**Comment by rstjames** [comment]
@aeiras I agree to keep it a neutral time like UTC. This makes sense for everyone all around the world.

**Comment by aeiras** [comment]
First, it is wonderful to hear that you plan to help review and publish more incoming content @Emily-Jiang, YEAYY! :)

If that is the case, yes, lets keep UTC - Coordinated Universal time

<img width="704" alt="image" src="https://user-images.githubusercontent.com/10731224/61738678-a7b96200-ad3f-11e9-94d1-c6d546e5cac6.png">

I have added the UTC time to the [blog guidelines ](https://github.com/microprofile/wpsite/blob/master/README.md)

Please @rstjames confirm by closing this ticket that time is adjusted to match this exchange. Thanks!

**Comment by rstjames** [comment]
@aeiras It was not adjusted from the original UTC +0
