### ISSUE TITLE
Solicitud de usuario para ser agregado a WP MicroProfiler como nuevo Contributor

### ISSUE THREAD

**Issue by geovannymcode** [microprofile/microprofile-marketing#134]
Solicitud de usuario para ser agregado a WP MicroProfiler como nuevo Contributor.

Geovanny Mendoza Gonzalez
Líder de la comunidad Java Barranquilla "JUGBAQ" 
email: Geovanny0401@gmail.com

**Comment by aeiras** [comment]
Que chevere verte aqui Geovanny! 
Bienvenido a contribuir MP videos, tutorials, sesiones, blogs, etc 👍 :) 

<img width="948" alt="image" src="https://user-images.githubusercontent.com/10731224/61017551-75276680-a348-11e9-87e8-56027ca81dd1.png">

**Comment by geovannymcode** [comment]
Gracias Amelia @aeiras
