### ISSUE TITLE
Request to be added as a WP MicroProfiler Editor

### ISSUE THREAD

**Issue by kenfinnigan** [microprofile/microprofile-marketing#135]
Be added as WP Editor

kfinniga@redhat.com
Ken Finnigan

**Comment by kenfinnigan** [comment]
This is now resolved

**Comment by aeiras** [comment]
Glad you are covered. 

Editor means that you are willing to review and post other contributors' blogs? Is that correct?

If you are only becoming an editor to publish your own blogs, your access will be a contributor that needs to follow the steps as the blog guidelines indicates. 

Please advice and thanks for being awesome @kenfinnigan !:)

**Comment by aeiras** [comment]
Please follow up so that we can add you to the document that traced today's editors and who does what. ticket is reopened.

**Comment by kenfinnigan** [comment]
Can't say I'll review everything, but certainly intend to review when I can.

Clement had asked me to review the Reactive Messaging post from him, but I found out I couldn't. Hence the request

**Comment by aeiras** [comment]
perfect! :) thank you for confirming your Editor status. 

You just got a little bit more awesome MicroProfiler. :) 
[MP.io WP Admins Access](https://docs.google.com/document/d/1q0Xw4XJcoVq1V5vPWe9KR__WKoGc0e-X5cD3tnBsIKw/edit)

To the wonderful contributor who got to this ticket but didn't follow the steps to document access, please own ticket and make sure to update the documents and ensure that when an Admin in MP wordpress is added it is stated in the ticket as it is here. Questions, shoot!
