### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by joedayz** [microprofile/microprofile-marketing#136]
Name: José Amadeo Díaz Díaz
Email: jamdiazdiaz@gmail.com

**Comment by aeiras** [comment]
@joedayz, 
Thank you for becoming the 45 MP WordPress Contributor Jose! **you ROCK** :) 
<img width="964" alt="image" src="https://user-images.githubusercontent.com/10731224/61085717-c9ccef00-a3e5-11e9-982d-9d8895e5cc31.png">

las tildes en tus nombre y apellido son consideradas especial caracteres y no son posibles en tu "user ID".  Por esa razón ves tu nombres sin acentos. -logistics of wordpress
