### ISSUE TITLE
SouJava - MicroProfile para o Desenvolvedor Ocupado

### ISSUE THREAD

**Issue by Daniel-Dos** [microprofile/microprofile-marketing#138]
Conference Name: SouJava

Conference website and social media links: 
https://www.meetup.com/pt-BR/SouJava/events/263103256/ 

 and media : 
https://drive.google.com/drive/folders/1pwiY9rLewi7uLL9gT9ReNydpADyXXQf0

About the session Title: MicroProfile para o Desenvolvedor Ocupado by Víctor Orozco (@tuxtor)
Date and hour: 18st July at 7:00 p.m. Brazil-SP

Twiiter  : https://twitter.com/DanielDiasJava/status/1149892193781473281

Tweet message:  Join @tuxtor next week (7/18) at another @soujava meetup, come learn about @MicroProfileIO at 7:00 PM in SP:  Free registration: https://www.meetup.com/pt-BR/SouJava/events/263103256/

**Comment by aeiras** [comment]
@Daniel-Dos, 

This is great. It is likely the design team won't get to it given that 2 weeks notice is asked to make sure item gets pushed. 

Yet, this is great as you and the SOUjava team already created a design that we can use :) excellent work on that!

**Comment by Daniel-Dos** [comment]
Hi @aeiras ,

No problems .

happy that the template can be used by other people : )

Thank you very much

**Comment by aeiras** [comment]
Thank YOU for scaling via actions at each opportunity! great form & stand Dani 💯 MP wonderful and fun.
