### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by diakogiannis** [microprofile/microprofile-marketing#139]
Name: Alexius Diakogiannis
Email: alexius.diakogiannis@gmail.com

**Comment by aeiras** [comment]
Welcome to MP WordPress Alexius! 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/10731224/61235033-60045c00-a6e9-11e9-8633-ca19c355cdc2.png">
