### ISSUE TITLE
[SOUjava{Rio}] Provided Meet-up design general form to be used for MP sessions

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#140]
[Meet-up templates by SOUjava](https://drive.google.com/drive/folders/1pwiY9rLewi7uLL9gT9ReNydpADyXXQf0)

@Daniel-Dos this is the other ticket that helps track your team's MP Meet-up design that can be used by others! :)

**Comment by Daniel-Dos** [comment]
thanks @aeiras :  )
