### ISSUE TITLE
OUGPY - Oracle Groundbreakers -  Continuous Load Testing for Containerized Java Eclipse MicroProfile Applications 

### ISSUE THREAD

**Issue by cbustamantem** [microprofile/microprofile-marketing#141]
Conference Name: Oracle GroundBreakers

Conference website and social media links:
https://twitter.com/ougpy/status/1150861210490851328

About the session Title: Continuous Load Testing for Containerized Java Eclipse MicroProfile Applications @cbustamantem
Date and hour: 8 Ago  Asunción -  Paraguay 

Twiiter : https://twitter.com/cbustamantem/status/1150870593635532800

Tweet message: Cordialmente invitados a la charla
Continuous Load Testing for Containerized Java Eclipse MicroProfile Applications
@MicroProfileIO
 #Java  #Docker   
@ougpy

**Comment by rstjames** [comment]
@cbustamantem do you have a date for this season? Also what is your twitter?

**Comment by aeiras** [comment]
Hola Carlos @cbustamantem, 
It seems that there is no set time for your MP session. That is ok. 
Please confirm below, i found data so that @rstjames gets it out via media. :) Gracias for el MP ticket!
 
Name of speaker: Carlos Bustamante
Twitter handle: https://twitter.com/cbustamantem
day & time (all day not set times): Aug 8th, 2019 -- 9am to 6pm Paraguay time

Push via twitter with all speakers: https://twitter.com/ougpy/status/1151228405129646081

**Comment by cbustamantem** [comment]
Greetings Ryan
   My twitter is @cbustamantem <https://twitter.com/cbustamantem>, the date
of the event will be 08-Ago-19, and will take all the day from 09.00 am.
Thanks for your support

Gracias Amelia por las instrucciones y coordinación.

Saludos cordiales
Carlos Bustamante

**Comment by rstjames** [comment]
@cbustamantem @aeiras 
Ok with this image?
![MicroProfile-session-CarlosBustamante](https://user-images.githubusercontent.com/12132146/61864516-de26e680-aed1-11e9-9ddf-a9c4cf19d0c4.png)

Tweet:
Tweet message: Cordialmente invitados a la charla "Continuous Load Testing for Containerized Java Eclipse MicroProfile Applications" @cbustamantem @ougpy 
más información: https://twitter.com/ougpy/status/1151228405129646081

@MicroProfileIO #Java #Docker #opensource #oss @java

**Comment by cbustamantem** [comment]
Greetings Ryan
  Is a nice surprice to see this level of support, thank you in advance,
but a i have a request,  let me explain in this event,  i will talk about
Eclipse MicroProfile with my partner (Arnaldo Ayala @aayalapy
<https://twitter.com/aayalapy>)  for that reason, if is not a big trouble,
if you can add the name of my partner and his picture (the same of the
twitter account).

Thanks for your support
Carlos B.

**Comment by rstjames** [comment]
updated image:
![MicroProfile-session-CarlosBustamante](https://user-images.githubusercontent.com/12132146/61934182-01ac6880-af88-11e9-9cd3-c8a3b137a3f6.png)
@cbustamantem

**Comment by cbustamantem** [comment]
Hi Ryan
   Excelent, that is awesome!!, again, thanks in advance for your support
and for your patience in this request.

Best regards,
Carlos Bustamante

**Comment by rstjames** [comment]
all scheduled to go out 1 day before and 4 days before. @cbustamantem
