### ISSUE TITLE
[Blog] MicroProfile: How it has evolved and where it’s headed?

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#142]
Last year I wrote a blog to present MicroProfile. One year later, I thought it was a good opportunity to look backwards and see what we have achieved all together.

Here is a link if you want to cross post with MicroProfile twitter handle.

https://www.tomitribe.com/blog/microprofile-how-it-has-evolved-and-where-its-headed/

**Comment by aeiras** [comment]
@jeanouii please refer to the MP blog guidelines, you must do all the work yourself. 

If guidelines are not clear, please send PRs against it making it clearer for future potential contributors. 

You rock!

**Comment by jeanouii** [comment]
The blog is available 
Here is the preview page
https://microprofile.io/?p=6319&preview_id=6319&preview_nonce=97ee0f5b56&post_format=standard&_thumbnail_id=-1&preview=true

**Comment by aeiras** [comment]
@jeanouii thank you for adding your MP blog to wordpress. 
One improvement is to include a header picture, if you can. 👍 

[Your blog is Published](https://microprofile.io/2019/07/23/microprofile-how-it-has-evolved-and-where-its-headed/)

Please re-tweet, so MP handle can re-tweet your MPblog.
