### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#143]
Jean-Louis Monteiro
jlmonteiro@tomitribe.com

If you need help on the editor part of things, feel free to also add me in that group

**Comment by aeiras** [comment]
Thank you for choosing to become the 47 MP WordPress Content Contributor @jeanouii! 
<img width="892" alt="image" src="https://user-images.githubusercontent.com/10731224/61309716-93a5bb80-a7a7-11e9-8ce2-82b9a9f8a050.png">
