### ISSUE TITLE
I code java MicroProfile workshop

### ISSUE THREAD

**Issue by phillip-kruger** [microprofile/microprofile-marketing#144]
Name of the facilitators : Ivar Grimstad & Phillip Kruger
Name of the workshop: Implementing Microservices with Eclipse MicroProfile
Twitter accounts: @ivar_grimstad & @phillipkruger
Link of the event: http://j-sa.co/schedule-java/
Date/ time/location: 24 July 2019 09h00 in Johannesburg, South Africa
Tweet message: South African developers: Learn about the MicroProfile programming model for developing microservice applications.

**Comment by rstjames** [comment]
South African developers: Come join @ivar_grimstad & @phillipkruger @JavaAfrica for a workshop about @MicroProfile.IO programming model for developing #microservice applications. 
24 July 2019 9:00, Johannesburg, South Africa
More info: http://j-sa.co/schedule-java/
#opensource #oss 

![MP-ICodeJava-workshop](https://user-images.githubusercontent.com/12132146/61454420-29387b00-a961-11e9-8fb8-e431d6b447b0.png)

@phillip-kruger

**Comment by phillip-kruger** [comment]
Thanks !
