### ISSUE TITLE
I code java MicroProfile GraphQL

### ISSUE THREAD

**Issue by phillip-kruger** [microprofile/microprofile-marketing#145]
Name of the speaker : Phillip Kruger
Name of the session: Writing better APIs with MicroProfile GraphQL
Twitter accounts: @phillipkruger
Link of the event: http://j-sa.co/schedule-java/
Date/ time/location: 25 July 2019 11h35 in Johannesburg, South Africa
Tweet message: South African developers: Come hear what the MicroProfile GraphQL workgroup has been up to and learn about the upcoming MicroProfile GraphQL API

**Comment by rstjames** [comment]
@phillip-kruger 
Tweets are scheduled
South African developers: Come hear what the @MicroProfileIO #GraphQL workgroup has been up to and learn about the upcoming MicroProfile GraphQL API with @phillipkruger @JavaAfrica

Learn more: http://j-sa.co/schedule-java/ 

#opensource #oss 

![MP-Media-Phillip-Kruger-Speaker](https://user-images.githubusercontent.com/12132146/61453042-70bd0800-a95d-11e9-945e-b120f03f13e4.png)

**Comment by phillip-kruger** [comment]
Thanks
