### ISSUE TITLE
MP talk at JCON2019

### ISSUE THREAD

**Issue by maikheene** [microprofile/microprofile-marketing#148]
*Name of the speakers*
* Maik Wolf
  * Twitter: https://twitter.com/da_mwolf
* Daniel Krämer
    * Github (for profile picture only): https://github.com/dkraemer-anderScore
     * Twitter: https://twitter.com/anderScoreGmbH

*Name of the session (German)*
Java EE + MicroProfile - das bessere Spring Boot?

*Link to event*
    https://jcon.xdev.cloud/

*Date/Time/Location*
Thursday - 9/26/19 - 03:00 - 03:45PM (German Time) - Dusseldorf

*Message*
Join @da_mwolf & @anderScoreGmbH at @jcon_conference to learn if @JakartaEE @MicroProfileIO are better than @springboot - Thursday, September 26th. More info: https://jcon.xdev.cloud/ 
See you in Dusseldorf (Germany)

#JCON2019

Thank you so much for your media marketing support :)

Kind regards
Maik

**Comment by rstjames** [comment]
2 Tweets have been scheduled for sep 17th and Sep 25th.
![MicroProfile-Jcon-MaikWolf](https://user-images.githubusercontent.com/12132146/61532036-e80b9e00-aa28-11e9-98be-226bcbd7bf61.png)
