### ISSUE TITLE
Virtual Session/IBM Middleware User Community: A New and Smart Way to Build Cloud-Native Microservices - MicroProfile

### ISSUE THREAD

**Issue by yeekangc** [microprofile/microprofile-marketing#149]
@Emily-Jiang and I have a virtual session on the coming Wednesday to talk about MicroProfile.  If it's appropriate, we would be glad to have a message out from @MicroProfileIO about it.  Just remember this and hope there is still enough time for the team to consider.  Sorry for the short notice!  Thank you.

Name of the speaker:
Emily Jiang
YK Chang

Name of the session:
A New and Smart Way to Build Cloud-Native Microservices - MicroProfile

Twitter or/& git account, if available:
@emilyfhjiang
@yeekangc

Link of the event or short session abstract:
This is an online session via the IBM middleware user community.  Registration link and the abstract at URL below.

https://community.ibm.com/community/user/imwuc/events/event-description?CalendarEventKey=0d92123c-38ba-4293-ae95-d6ee386abc74&CommunityKey=b382f2ab-42f1-4932-aa8b-8786ca722d55&Home=%2fcommunity%2fuser%2fimwuc%2fevents%2fupcomingwebcasts

Date/time/location:
Online session @ Jul 24, 2019 from 10:00 AM to 11:00 AM ET

Speaker must provide a "tweet message" for their session:
Curious about cloud-native Java?  Come join us to take a look at Eclipse MicroProfile, the new and smart way to build cloud-native microservices in Java!

**Comment by aeiras** [comment]
Hola @yeekangc and @Emily-Jiang, 

Not sure Ryan will get to this ticket as 2 weeks are recommended. I want to point you out to the speaker resources media designs available that you can use when tickets are submitted too close to event and are likely to miss media coverage. 

[MP Media designs available](https://drive.google.com/drive/folders/1whC7SmGGGdP0u5xyck3U-74s8J5s5tV_)

**Comment by yeekangc** [comment]
Thank you, @aeiras.  We will keep the resources in mind and use them next time.
