### ISSUE TITLE
Approval to update LJC's new logo 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#150]
It appears JLC has a new logo and I would like to update it on the MP site and other materials.

**Comment by aeiras** [comment]
Hey amazing @karianna- Martijn, 

While working on the MP white paper, Ryan noticed the JLC is different. if yes, can you help update the JUG logo by attending the [drive files ](https://drive.google.com/drive/folders/0B7PK4ZIk1mjAUnRWMVJ4SWdYcWc)and following up via this git issue? 

Thanks and abrazos #usualsuspects :)

**Comment by karianna** [comment]
All good thanks!

**Comment by karianna** [comment]
Logo package uploaded.

**Comment by aeiras** [comment]
you are wonderful @karianna- thanks for quickly updating newest LJC logo! :) already updated across by @rstjames!
