### ISSUE TITLE
[Blog] Review blog post on migrating apps from Metrics 1.x to 2.0

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#151]
In draft in Wordpress: https://microprofile.io/wp-admin/post.php?post=6332&action=edit

Thanks

**Comment by pilhuhn** [comment]
While I see no issue in linking to the original article, I think that the article is a bit sparse and could have a bit more "motivational text".

**Comment by lauracowen** [comment]
Sorry, didn't see this notification. Thanks for the feedback - you make a good point. I've updated the abstract to hopefully be a bit more interesting (but can do more if you think it necessary).

**Comment by aeiras** [comment]
what is the status of the blog review @pilhuhn ? :)

**Comment by lauracowen** [comment]
@pilhuhn Is there anything else you'd like me to do do with this post before you can publish it?

**Comment by aeiras** [comment]
@lauracowen, 

It is your call if you are happy to published blog. Currently status is:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/10731224/65728813-01f0df00-e071-11e9-8e80-4d8bf1d9fd22.png">

**Comment by lauracowen** [comment]
Hi, yes, I think it's fine to be published. It's still relevant and potentially useful to MicroProfile Metrics users as it's not tied to a particular date really. I'll publish it when David (first author) has registered on the site (I think he's requested an ID).

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/207  +1 on value
to publish David's content!
Amelia Eiras
https://twitter.com/ameliaeiras
Tribe: http://tomitribe.com      https://tribestream.io
OSS:  https://tomitribe.io        http://microprofile.io

**Comment by lauracowen** [comment]
Thank you! Published. Well, will be when the server time catches up with UK time...
