### ISSUE TITLE
MP workshop at GroundbreakersTour LATAM 2019 (Colombia)

### ISSUE THREAD

**Issue by acelopezco** [microprofile/microprofile-marketing#152]
Name of the speakers:
Otavio Santana
Alexis Lopez

Name of the session
MicroServices using MicroProfile HOL

twitter
@otaviojava
@acelopezco

Github repo
https://github.com/EventosJEspanol/latin-america-micro-profile

Link to the event
http://asuoc.org.co/

Date/Time/Location:
August 16th 2019/9AM/Cartagena, Colombia

Tweet Message:
Come to this workshop to learn about @MicroProfileIO by implementing one or two microservices and deploying them to the cloud @asuoc #GroundbreakersTour 
📅 August 16th 2019 9AM
📍 Cartagena, Colombia 
🌐 Info and RSVPs: http://www.asuoc.org.co/

**Comment by rstjames** [comment]
@acelopezco I will schedule this today
![MicroProfile-Alexis-otavio-GroundBreakersTour-Colombia](https://user-images.githubusercontent.com/12132146/62540102-137aef00-b857-11e9-9baa-df242ac617aa.png)
