### ISSUE TITLE
MP workshop at JConf Guatemala conference

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#153]
Name of the speaker: Cesar Hernandez and Jose Diaz
Name of the session: [workshop] Desarrollo de microservicios en Java con MicroProfile
twitter or/& git account, if available: @cesarHgt @jamdiazdiaz
link of the event or short session abstract: http://www.guate-jug.net/jconf2019/
Date/ time/location: November 9th. 2019
Tweet message: Join us at Jconf Guatemala on Saturday, November 9th to learn how you can easily build #java #microservices with open and standards-based technologies! @MicroProfileIO @guatejug @ApacheTomEE

**Comment by rstjames** [comment]
Scheduled for day before and 5 days before. 
![MicroProfile-JConf-Guatemala](https://user-images.githubusercontent.com/12132146/62856431-33962c80-bcf5-11e9-9f9e-388646ddc076.png)
