### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#154]
Rustam Mehmandarov
mehmandarov [ættt] gmail dott com

Feel free to also add me to the Editors' group, if you need any help there.

**Comment by aeiras** [comment]
Rustam-- How fun welcoming to you contributing MP diverse content directly via MPwordpress! 

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/10731224/62153519-929d7f80-b2b9-11e9-9405-d3bbcb0d9d90.png">

**Comment by Emily-Jiang** [comment]
Thank you @aeiras for your prompt help ! @mehmandarov did a great blog on MicroProfile, which is why I invited him to contribute the series of blogs in our site. Look forward to seeing the content appearing on microprofile.io!

**Comment by aeiras** [comment]
you are wonderful to reach out when you see great content via media and recommend the author to share it via MP.blog! I do the same and more times than not, she/he joins the fun :) community fun!
