### ISSUE TITLE
MP session at GroundbreakersTour LATAM 2019 (Ecuador)

### ISSUE THREAD

**Issue by acelopezco** [microprofile/microprofile-marketing#155]
Name of the speakers:
Alexis Lopez

Name of the session
MicroServices for JEE Developers

twitter
@acelopezco

Link to the event
https://www.javaday.ec

Date/Time/Location:
August 13th 2019/10AM/Quito, Ecuador

Tweet Message:
Come to this session to learn about @MicroProfileIO and how you can contribute to the project @EcuadorJUG #GroundbreakersTour #JavaDayEcuador
📅 August 13th 2019 10AM
📍 Quito, Ecuador
🌐 Info and RSVPs: https://www.javaday.ec/

**Comment by rstjames** [comment]
@acelopezco I will send it out today and the day before. 
![MicroProfile-AlexisLopez-GroundBreakersTour-Ecuador](https://user-images.githubusercontent.com/12132146/62524985-e4ed1c00-b836-11e9-8c3a-0d8c7b29e3c3.png)

**Comment by jeanouii** [comment]
@acelopezco 2 quick and small notes
MicroServices is usually spelled Microservices (lowercase s for services)
I believe JEE should not be used. It's either J2EE or Java EE but not JEE.

**Comment by acelopezco** [comment]
@jeanouii thanks for the info. I'll definitely take that into account for future sessions
