### ISSUE TITLE
MP session at GroundbreakersTour LATAM 2019 (Peru)

### ISSUE THREAD

**Issue by acelopezco** [microprofile/microprofile-marketing#156]
Name of the speakers:
Alexis Lopez

Name of the session
MicroServices for JEE Developers

twitter
@acelopezco

Link to the event
http://www.peoug.org/ogbtour2019/

Date/Time/Location:
August 28th 2019/9AM/Lima, Peru

Tweet Message:
Come to this session to learn about @MicroProfileIO and how you can contribute to the project @peoug #GroundbreakersTour 
📅 August 28th 2019 9AM
📍 Lima, Peru
🌐 Info and RSVPs: http://www.peoug.org/ogbtour2019/

**Comment by rstjames** [comment]
![MicroProfile-AlexisLopez-GroundBreakersTour](https://user-images.githubusercontent.com/12132146/62524406-d9e5bc00-b835-11e9-9262-a61a7d4e033b.png)
@acelopezco I will schedule it to go out 5 days before and day before from MP twitter handle
