### ISSUE TITLE
[White Paper 2019 Media push]  design 1- General 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#157]
@rstjames, 

Without rush, lets create 2 effective yet fun designs for paper media push to hold true for the rest of 2019.  
2nd ticket coming up with requirements. :) 

Design minimum requirements for general message push:

1.  contain the MP coffee cup
2. Lars' pic
3.  description for design and tweet next week.

**Comment by aeiras** [comment]
@rstjames, 

**Media Description:**

#MicroProfile is the #OpenSource Enterprise #Java project for a #MicroservicesArchitecture that enables users and developers alike to innovate across its multiple APIs. @mobileLarson's 45 pages white paper explains why NOW is the best time to check out @MicroProfileIO! 
#OSS @java

**Comment by rstjames** [comment]
@aeiras Need to shorten the message to fit a link to the WP. 
<img width="467" alt="Screenshot 2019-08-13 18 48 54" src="https://user-images.githubusercontent.com/12132146/62960488-06cc3d00-bdfb-11e9-8139-d32b4eaed6c1.png">

Link to landing page: http://bit.ly/2YMZcWr

**Comment by aeiras** [comment]
1 character left :) maybe a yellow heart, lol thanks Ryan!

#MicroProfile is the #OpenSource Enterprise #Java for a #MicroservicesArchitecture that enables users and developers to innovate across multiple APIs. @mobileLarson's white paper explains why NOW is the best time to check out @MicroProfileIO! 
http://bit.ly/2YMZcWr

#OSS @java

**Comment by aeiras** [comment]
@rstjames, I see this tweet went out[ today](https://twitter.com/MicroProfileIO/status/1184501000956190723?s=20): 

Is it scheduled to go weekly on wed for the rest of 2019? If so, lets close this ticket and thank YOU!
