### ISSUE TITLE
[White Paper Media push] design 2- MP APIs focus

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#158]
@rstjames, 

Design minimum requirements for APIs focus:

1.  contain the MP coffee cup
2. focus on APIs
3.  description for design and tweet next week.

**Comment by rstjames** [comment]
@aeiras 3 versions but I need new text for what we want to push . (API)
![MicroProfile-whitepaper-2](https://user-images.githubusercontent.com/12132146/62625578-cd409100-b925-11e9-8c63-d05d55f8cfad.png)
![MicroProfile-whitepaper-3](https://user-images.githubusercontent.com/12132146/62625582-cd409100-b925-11e9-907e-beb0d92723bb.png)
![MicroProfile-whitepaper-4](https://user-images.githubusercontent.com/12132146/62625584-cd409100-b925-11e9-8c6e-fbea81d5103f.png)

**Comment by aeiras** [comment]
@rstjames, 
The designs above are subtable for the [general push design](https://github.com/eclipse/microprofile-marketing/issues/157). 

I was imagining something 100% focus on MP APIs for design 2:

MicroProfile specifications: 

- [ 1] MicroProfile Config

- [2 ] MicroProfile Fault Tolerance

- [ 3] MicroProfile Health Check

- [ 4] MicroProfile Metrics

- [5 ] MicroProfile Open API

- [ 6] MicroProfile Rest Client

- [7 ] MicroProfile JWT Authentication

- [8 ] MicroProfile Open Tracing API

**Comment by aeiras** [comment]
@rstjames 

**Draft media push description:**

#MicroProfileAPIs evolve with three annual releases achieved by an #OSS community-driven process that encourages the APIs to extend the most common-valuable #JSRs. @@MicroProfileIO eliminates the risk of vendor lock-in and maintains the developers' freedom of choice.

**Comment by aeiras** [comment]
though there are about 11 APIs in the works, 8 are stablished so we will just highlight those this time around. : thanks for bringing effective designs to task Ryan. :)

**Comment by rstjames** [comment]
@aeiras I do not have the time to make 8 different visuals for the APIs. I think you can call attention to different APIs with different tweet messages.

**Comment by aeiras** [comment]
@rstjames message received, you have a good point as the API's don't have logos. 

I like the 3rd design above, additions could be:

- [writer ]Name of Lars

- [API ]  learn more about the MicroProfiles APIs

- [ API's quotes]  I will get this from the document. How many do you recommend we circulate?
