### ISSUE TITLE
[Twitter Banner adjustments] brainstorming

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#160]
@rstjames, 

While working on Lars' white paper, we created such a cute designs. 
I would love for some of them to be integrated across MP public areas: Website, Media outlets... 

Must:

- [ Twitter banner] : add 
the cute coffee MP cup
Duke Choice award 2018
Community First

- [Website ] : add
the cute coffee MP cup
Community First

**Comment by rstjames** [comment]
@aeiras need access to twitter main to update the images.

**Comment by aeiras** [comment]
Access granted only for design/branding usage/ Thanks Ryan!
