### ISSUE TITLE
Interview Edwin Derks for MP Blog

### ISSUE THREAD

**Issue by davidsalter** [microprofile/microprofile-marketing#161]
David Salter to interview Edwin Derks on how involvement in MP started and create a MP blog out of the results

**Comment by davidsalter** [comment]
Link to Google Docs interview:

https://docs.google.com/document/d/1fUjtK_Uud5NkLkVO3HfcMAv-2RXFNc826PS-zmBqnzc/edit

**Comment by ederks85** [comment]
Thanks David, just to let you know: I will provide the answers on Friday

**Comment by ederks85** [comment]
@davidsalter I have provided the answers. Please let me know if there is anything unclear, or I have used weird words or sentences, since I'm not a native English speaker.

I'm looking forward to the result! Good luck :)

**Comment by aeiras** [comment]
Hey beautiful MicroProfilers @ederks85 & @davidsalter, 

- [1]  Added Edwin and myself to this ticket  

- [2 ] Quickly checked without reading the Q&A & it misses @ederks85 pic and bio

- [3 ] Optional: before Q&A gets moved to Wordpress, should you want to- we can have our copy/editor review for minor grammatical errors as Edwin is explicit on being non-native english speaker. :)

- [ 4] I am beyond happy to be your wordpress reviewer & publisher and push media steps, etc

Both of you are wonderful,

**Comment by ederks85** [comment]
[1] Check :)
[2] Pic and bio added to the doc, please adjust in whatever fashion necessary
[3] Yes, please. Unless David doesn't think it's necessary
[4] Yes please. In my opinion, this was perfect to add the final touch to the previous blog

**Comment by ederks85** [comment]
I accidentally unassigned... was trying to give the issue back to you guys :)

**Comment by aeiras** [comment]
- [3 ] @davidsalter feedback needed when he gets to this project :) 

- [ 4]  good feedback Edwin, thanks for scaling the fun on boarding interview by being the chain from the very first iteration, you rock! :) 

Note: I heard that David S. will become the next interviewee, little by little via actions we are achieving a bullet proof fun process, with [Cesar Hernandez](https://github.com/cesarhernandezgt) as the interviewer after _your interview_ goes live! :) love it!

**Comment by davidsalter** [comment]
@aeiras @ederks85  - Thanks.  Will aim to get this completed this weekend.

**Comment by davidsalter** [comment]
@aeiras  @ederks85 

I've completed the interview and completed the proposed blog post in the Google Docs document.

[3] I've gone through the replies by Edwin and the English is excellent !  I'm happy that this reads well :)

Can both of you hae a read and check that this looks ok from your points of view ?

**Comment by ederks85** [comment]
Looks good to me. Let's take it to the press :)

**Comment by aeiras** [comment]
@ederks85 and @davidsalter, 

Just read the blog, beautifully written. It made me smile as it shares through much simplicity Edwin's ride thus far. I learned quite a bit about you Edwin, beyond awesome. 
Do you think we can publish it by this Thursday? Next week is also ok, up to you! Thank YOU!
 
I suggested a few things, nothing huge. Please review when you time works. 

@rstjames, two things:

- [1 ]  can you help prioritize a design for the MP to MP onboarding interviews Ryan? ETA this week publishing. 
[Design Requirements via issue ](https://github.com/eclipse/microprofile-marketing/issues/121)

- [2 ] lets schedule it for Thursday to give us time to get a design that is scalable for future interviews.

**Comment by ederks85** [comment]
Please publish it on Thursday if possible. I don't see any reason to wait :)

**Comment by rstjames** [comment]
@ederks85 can you please write up a tweet message so I can push it on MP social media?

**Comment by rstjames** [comment]
@aeiras 
I am not seeing a draft in MP blog... ? 
Or will there not be one? @ederks85 If not, please provide where this interview is hosted. 

What is needed from my side? Only social media?

**Comment by ederks85** [comment]
@rstjames I would think that @davidsalter is going to create the blog. Otherwise I would have provided a nice interview about myself 😄

**Comment by rstjames** [comment]
@davidsalter @aeiras @ederks85 
If you all would like this to go out on Thursday please let me know when the blog is ready... and if you need my help with anything.

**Comment by aeiras** [comment]
@rstjames thanks for jumping onto design and media, lets use the other ticket to create the interview design. For that, lets make the interviewee bigger than life and drop the style for speaker design from interviews. What we need is something that is scalable & fun and focus on the person above all. Once we have a design that is awesome, I will write up the description. 

About the blog publication, it is still being reviewed as yesterday I added stuff for David and Edwin to see.

**Comment by davidsalter** [comment]
Hi all.  I'm going to finish the blog post tomorrow.  Will ping you all when its done :)

**Comment by davidsalter** [comment]
@aeiras @ederks85 @rstjames I've created the draft post in wp.  Can you check that it all looks ok ?

I've been through and accepted the amendments suggested by Amelia and Edwin, so all looks good to me :)

**Comment by aeiras** [comment]
@davidsalter, 

Reviewed and approved, YEay! :) 

@rstjames lets create a super fun design, eta tmw. 
below is the media description. **FYI:** Lets re-write the link to MPinterviews if at all possible, just as we did for the white paper. Publish for this thursday first thing in the AM. thank you!

_#MicroProfileInterview: @edwinderks into💛@MicroProfileIO with @GeefyGeorge. [The #MPHangout] "is Edwin checkup to either pick up new tasks, get informed or share thoughts. He finds it more helpful and energizing to speak to everybody involved in person."_

**Comment by aeiras** [comment]
@ederks85 & @davidsalter is you can make better the media description, please just provide comments :) betterment is always possible! you two did an amazing job on 2nd MP to MP onboarding fun/ thankYOU!

**Comment by aeiras** [comment]
@rstjames, 

Amazing David added the first header design I quickly created from general template which we must drop on this and future interviews. 
Just as we created the podcast cool design, lets do something similar for this blog media header. FYI. 

@ederks85 I adjusted your bio to link the website of your employer. Please look at it for double eyes, correct stuff if I made a mistake. forgot to add important links via the word version, so fixes are added directly on the WP version. :)

**Comment by ederks85** [comment]
@aeiras @rstjames  I want to check/verify the contents of the blog in WP. Can you confirm if I have sufficient rights to do so? I can't seem to access it, since I only see the "Duplicate This" option

**Comment by aeiras** [comment]
@ederks85, 

Your interview and past work on project shows your intent on how much it matters to you to enable others to DO and to share stuff related to MP. As such, I was about to create a new ticket to invite you to join the WPaccess as an Editor and everything that comes with that responsability. 

Given _your_ current MP work and dedication, I have skipped that ticket and via this comment share with you that you are the newest Editor for **others' review and content publishing** for MP. 
That is documented [here](https://docs.google.com/document/d/1q0Xw4XJcoVq1V5vPWe9KR__WKoGc0e-X5cD3tnBsIKw/edit)

Let me know if you want to adjust such access or if you are ok to own it beyond this week's project interview fun! No pressure  :) 
<img width="999" alt="image" src="https://user-images.githubusercontent.com/10731224/62979728-6ca7cd00-bdd9-11e9-9acd-36f2f6caaa47.png">

**Comment by ederks85** [comment]
@aeiras
Thanks for promoting me to Editor, this means a lot to me!

To get back to your earlier question: the link to my employer in the post is perfect like this, so it is good to go from my side

**Comment by aeiras** [comment]
Thanks for checking that link that is a part of your short bio. [please keep it in mind for future short profiles] 
About this project--   you and @davidsalter have completed quickly 2nd MP-MP interview iteration, KUDOS! 
Your interview will go live this Thursday :) 

- [NOW ] it is for @rstjames & me to own the final 2 steps!

**Comment by rstjames** [comment]
@aeiras Updated the top image for the blog. I will reuse this for the Social media push. 
<img width="1245" alt="Screenshot 2019-08-14 13 34 42" src="https://user-images.githubusercontent.com/12132146/63018091-4e54d680-be98-11e9-8a31-4da4477979a5.png">

**Comment by rstjames** [comment]
Social media image :

![MicroProfile-OnboardingInterview-EdwinDerks](https://user-images.githubusercontent.com/12132146/63022839-0fc51900-bea4-11e9-875c-82a41d674a05.png)

**Comment by rstjames** [comment]
option 2:
![MicroProfile-OnboardingInterview-EdwinDerks-2](https://user-images.githubusercontent.com/12132146/63025583-ced00300-bea9-11e9-86cd-0ffbda8878f0.png)

I prefer option 1

**Comment by davidsalter** [comment]
> Thanks for checking that link that is a part of your short bio. [please keep it in mind for future short profiles]
> About this project-- you and @davidsalter have completed quickly 2nd MP-MP interview iteration, KUDOS!
> Your interview will go live this Thursday :)
> 
>     * [NOW ] it is for @rstjames & me to own the final 2 steps!

Thank you Ameila. It's been a lot of fun !

**Comment by aeiras** [comment]
Ryan, 

Option 1 & the blog header ROCK 🎸- beautiful work @rstjames! 

Please drop the 2 designs into the clean template folder for easier access & reference use! 

If ready, we could push it today instead of tmw Ryan. I leave that up to you! 💛let’s do this!

**Comment by rstjames** [comment]
@aeiras do we have a tweet message?

**Comment by aeiras** [comment]
Yes, see the italics from above msg! 18hrs ago.

**Comment by rstjames** [comment]
Confirming this is the tweet to use. 
#MicroProfileInterview: @edwinderks into @MicroProfileIO with @GeefyGeorge. 💛[The #MPHangout] "is Edwin checkup to either pick up new tasks, get informed or share thoughts. He finds it more helpful and energizing to speak to everybody involved in person."

@aeiras what is this "[The #MPHangout]"? why is it in [   ] ?

**Comment by aeiras** [comment]
It is the brackets that add the hangout. The quote misses it bc it is part of a great paragraph. 
If you have a way to add it without brackets but still keep the quote reference that focus on hangout THEN that’s great.

**Comment by rstjames** [comment]
**New tweet suggestion:**  
#MicroProfileInterview: @edwinderks shares his experience about on-boarding into @MicroProfile.IO with @GeefyGeorge. Edwin's provides a valuable input in optimizing the welcoming process & hopefully inspires you to join as a member too. {link}
#opensource  #community

**Comment by aeiras** [comment]
Pretty great improvement @rstjames! 
Let’s run your version that uses the blog intro thesis! 
That description will be added as the standard for future interview media messages! 

Let’s run it, add the link of the tweet here & close ticket! 

Thanks for 🎸💛 💪🏼

**Comment by rstjames** [comment]
Final tweet: 
#MicroProfileInterview: @edwinderks shares his experience about on-boarding into @MicroProfileIO with @GeefyGeorge. Edwin provides valuable input in optimizing the welcoming process & hopefully inspires you to join as a member too.
http://bit.ly/2Z2ePZz

#oss #opensource

**Comment by aeiras** [comment]
approved!

**Comment by aeiras** [comment]
[Twitter](https://twitter.com/GeefyGeorge/status/1161668331457392641?s=20)
