### ISSUE TITLE
MP Talk @ Oracle Groundbrakers tour Guatemala

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#165]
**Conference Name:** Oracle Groundbrakers Tour Guatemala 2019

Conference website and social media links:
https://oraguate.org/

Session Name: Beneficios de MicroProfile para aplicaciones monolíticas.
Date and hour: Monday, August 26th. 2019 (7:30 - 18:00 )

Speaker name: Jorge Cajas
Speaker twitter handle: @cajasmota

Description
Join @cajasmota at @orauggt to discuss and learn how could you take advantage of the @MicroProfileIO API's on your existing applications without refactoring them into microservices - Monday, August 26th 

#OpenSource #OSS

**Comment by rstjames** [comment]
@Motojo It will go out today. Please make sure you spell everything right on the content. You misspelled "Groundbrakers" I caught it :) 
![MicroProfile-OGTour-Guatemala-JorgeCajas](https://user-images.githubusercontent.com/12132146/63575614-c3a46380-c58a-11e9-9c33-8fc706809ded.png)
