### ISSUE TITLE
Request to be added as a WP MicroProfiler Editor

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#166]
If MP blog needs more editors to review other people's blog post submissions, I'm happy to help. :) (I'm an IBMer; IBM address laura_cowen@uk.ibm.com.)

**Comment by aeiras** [comment]
Hola Laura, 

You are most welcome to wpMP Editing fun! 
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/10731224/63034699-9fe86b80-be6e-11e9-97e7-a0f70bca1118.png">

Thank you for choosing to help review and publish content using the blog guidelines. Admin doc adjusted to match this update [here](https://docs.google.com/document/d/1q0Xw4XJcoVq1V5vPWe9KR__WKoGc0e-X5cD3tnBsIKw/edit)
