### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by rieckpil** [microprofile/microprofile-marketing#168]
I would like to contribute to the microprofile.io site with tutorials and examples. Firstname: Philip Lastname: Riecks E-Mail: mail@philipriecks.de

Most of my content is published on https://rieckpil.de

**Comment by aeiras** [comment]
Hola Phillip, 
Your content contributor access sent. Thank you for accepting 🥋👌🏼💛feedback! 

 It is nice to virtually meet you via twitter MP blog today. 
https://twitter.com/rieckpil/status/1162702781289041926?s=21
