### ISSUE TITLE
MP Talk @ Code One 2019

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#170]
**Conference Name:** 
Oracle CodeOne 2019

**Conference website and social media links:**
https://www.oracle.com/code-one/
@OracleCodeOne

**Talk name:**
Take advantage of MicroProfile benefits on your monolithic application.

**Talk Link:**
https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV1151

**Speaker Names:**
Victor Orozco, CTO, Nabenik (@tuxtor)
Jorge Cajas, CTO, inin.global (@cajasmota)

**Tweet Message:**
Come to learn with @tuxtor and @cajasmota how to take advantage of Eclipse Microprofile benefits on your monolithic applications without refactoring them to microservices. 
Thursday, September 19, 11:15 AM

**Comment by rstjames** [comment]
@Motojo scheduled for 2 days to go out on twitter
