### ISSUE TITLE
New MP Blog crosspost

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#171]
Hi,

I created the following draft and it's ready for review: https://microprofile.io/wp-admin/post.php?post=6372&action=edit

**Comment by aeiras** [comment]
@cesarhernandezgt, 

Your crossposting is now published. I you tweet using the @MP handle mention, we will re-tweet via the handle the blog. :) thanks for sharing MP knowledge!

https://microprofile.io/blog/
