### ISSUE TITLE
MP Workshop @ Oracle Groundbrakers tour Guatemala

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#172]
Conference Name: Oracle Groundbrakers Tour Guatemala 2019

Conference website and social media links:
https://oraguate.org/

Session Name: Laboratorio: Java microservices with MicroProfile for the busy developer
Date and hour: Monday, August 26th. 2019 

Speaker name: Cesar Hernandez
Speaker twitter handle: @cesarHgt
Speaker name: Victor Orozco
Speaker twitter handle: @tuxtor

Description
Join @cesarHgt and @tuxtor at @orauggt to learn how to create microservices using the latest @MicroProfileIO API's in @Java architectures - Monday, August 26th

#OpenSource #OSS #ShareIsCaring #JEspanol

**Comment by rstjames** [comment]
@cesarhernandezgt it is scheduled to go out today. Please be careful on spelling in the ticket you misspelled "Groundbreakers"
![MicroProfile-OGTour-Guatemala-Cesar](https://user-images.githubusercontent.com/12132146/63576641-e6d01280-c58c-11e9-8e1a-c23f3ceb03ba.png)
