### ISSUE TITLE
[OC1 Hackergarten session] Hacking MicroProfile

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#173]
- [ ] Title: Hacking MicroProfile

- [ ] Event link: https://community.oracle.com/docs/DOC-1032619

- [ ] When: 9/18 at 2:30pm-4pm PDT

- [ ] location: Moscone South (inside of the Groundbreakers booth in the Exhibition Area)

- [ ] logos: groundbrakers & MP

- [ ] MicroProfilers:  Emily Jiang, Cesar Hernandez Mendoza, Ondro Mihályi, Phillip Kruger, Amelia Eiras

- [ ] Media description:

Becoming a #MicroProfileContributor Is Easy.  Join, participate, secure your #MPshirt @OracleCodeOne  💛@MicroProfileIO #Hackergarten with #MicroProfilers: @CesarHgt, @emilyfhjiang, @OndroMih, @phillipkruger & @ameliaeiras.  [link] #OpenSource #BreakNewGround #CommunityFIRST

**Comment by cesarhernandezgt** [comment]
I suggest, if space is available, to also add the hashtag:  #BreakNewGround since this is the one used by the event.

**Comment by aeiras** [comment]
Excellent feedback Cesar! 💛

**Comment by aeiras** [comment]
Added Groundbreakers logo to the design requirements Cesar.
