### ISSUE TITLE
MP Talk by Cesar, Otavio and Rafael @ Code One 2019

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#181]
**Conference Name**:
Oracle CodeOne 2019

Conference website and social media links:
https://www.oracle.com/code-one/
@OracleCodeOne

**Talk name:**
Keeping Brazil’s Medical Industry Safe with MicroProfile [DEV4113]

**Talk Link**:
https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV4113

**Speaker Names**:
Cesar Hernandez Mendoza, Senior Software Enginner, Tomitribe (@CesarHgt)
Otavio Santana, Senior Software Engineer, Platform.sh/Soujava (@otaviojava)
Rafael Guimaraes, Analyst, GBR Systems (@GuimaraesSv)

Tweet Message:
Come and learn how MicroProfile played a critical role in that enabled the cloud migration in the Brazilian medical industry. Wednesday, Sep 18, 17:00 | Moscone South - Room 310/311 @OracleCodeOne @MicroProfileIO @graalvm @Groundbreakers @Java_Champions #BreakNewGround

logos: groundbrakers, Java Champions & MP

**Comment by rstjames** [comment]
@cesarhernandezgt all set up for two tweets.
