### ISSUE TITLE
[MP- errors with Media push]Twitter Informed/Deleted 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#187]
asked why a microprofiler was not added to push after deletion.

_human error_

![IMG_4221](https://user-images.githubusercontent.com/10731224/64194620-78b10880-ce34-11e9-80e7-a67fd6cb8b96.PNG)

**Comment by cealsair** [comment]
OCO session catalog listed only one speaker. Found out of second speaker via Twitter conversation. Social card was immediately fixed and later posts now show both speakers.
