### ISSUE TITLE
[MP Social Media Inventory/INFRA] Who/what's/how ~ current status under each media tool?  

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#188]
Folder [below ](https://drive.google.com/drive/folders/18YNojWQHb9bQoJv7PkeLnFLqSPakFhex)contains 3 folders:

1. Twitter Management: updated

2. Facebook Management: empty **Needs attention**  

3. LinkedIn Management: empty **Needs attention** 

**AND** 2 documents:

- Social Media _[Standards](https://docs.google.com/document/d/1O-p8HJxs13WEZs8Sl2NNrLuh4ofRngV_EKMDJJYa91g/edit)_ with Twitter as an example

- [Inventory Contributors Detail](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=0)

**Comment by aeiras** [comment]
Hola @cealsair, 

Can you please help update the Inventory of your media access on the link above? Thanks

**Comment by rstjames** [comment]
@aeiras @cealsair Updated what I know

**Comment by aeiras** [comment]
Thank you Ryan for tackling this ticket during the Mktg calls.
