### ISSUE TITLE
[Blog] Publish post on 12 factor apps by Emily

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#189]
https://microprofile.io/wp-admin/post.php?post=6373&action=edit

Based on what @aeiras said on a separate post, I think I'm okay to just publish this myself as I'm an editor and Emily is the author of the post which is already published/hosted elsewhere. So I'm going to give it a go (as my first publish as an Editor)...

**Comment by lauracowen** [comment]
Published: https://microprofile.io/blog/ (redirects to https://openliberty.io/blog/2019/09/05/12-factor-microprofile-kubernetes.html)

**Comment by aeiras** [comment]
Perfectly accomplished crosspost @lauracowen!

Thank you for not giving up and for,  **if able**, tackling the blog-wiki guidelines to make this section easier to own. :)
