### ISSUE TITLE
Alberto (Latin Armada) to see if MP blogs in Spanish can be written

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#19]
Latin American & Spanish JUGs are 1 entity that operates and collaborates in the distrubution of their knowledge. As such, they want to bring Spanish content to MP.  :)

**Comment by lasalazarr** [comment]
I already contact several JUG Leaders from Latin America and Spain; we are starting work on the content.

**Comment by aeiras** [comment]
sounds wonderful  @lasalazarr!  :) I will close this ticket, any future content must use its own issue created and owned by the writer. Super fun!  #thankYOU!
