### ISSUE TITLE
MicroProfile Swag for MicroProfile Presentation

### ISSUE THREAD

**Issue by mpredli01** [microprofile/microprofile-marketing#190]
As you may already know, I am presenting a MicroProfile talk at my Java Users Group this coming Tuesday, September 10.  As per Emily Jiang's suggestion, I attended the MicroProfile marketing call this past Monday and I asked about the possibility of getting MicroProfile swag to distribute at my JUG.

It was decided that the swag could be sent to my house via a US-based MicroProfile contributor.  Is there a chance that you could send me about 50 MicroProfile stickers and such?  I would indeed appreciate it!

Best regards,

Mike.

**Comment by aeiras** [comment]
Mike @mpredli01, 

Thank you for rocking via each MP action getting coverage for your MP session next week, you are amazing and I personally felt happy to attend your request b/c saying THANK YOU via actions is better! :)

Your MP swag will arrive to your home by this Saturday or **latest Monday.**

The package inventory contains: 

*stickers*: 
- 50 MicroProfile

- 50 Jakarta EE 

- 50 combination by Tomitribe:  TomEE, MicroProfile and Jakarta  

**shirts**

- 5 MicroProfile

- 4 combination by Tomitribe:  TomEE, MicroProfile and Jakarta 

Disclosure: It is up to you to allocate the shirts, you have rocked being a Java enthusiast and Java EE Contributor via many mediums. It is great. Biasly, I will recommend given that swag-shirt is limited and sponsored by Tomitribe to keep in mind  that to own it today, it is not enough to show up to the session.  Before session starts, you could state that swag is available and will be given to the deserving participants, or similar. example: who asks the most valuable/crude/maybe thought provoking questions that are likely to improve the ecosystem, etc.
