### ISSUE TITLE
MP Talks by Emily

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#191]
Conference Name:
Oracle CodeOne 2019

Conference website and social media links:
https://www.oracle.com/code-one/
@OracleCodeOne

Talk name:
Configuration

Talk Link:
https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=%22Emily%20Jiang%22

Speaker Names:
Emily Jiang, Liberty Microservice Architect and Advocate

Tweet Message:
Join @Java_Champions @IBMDeveloper  @OracleCodeOne Featured Speaker @emilyfhjiang 
to learn #MicroProfile #Config at 
Wednesday, September 18, 11:30 AM - 12:15 PM | Moscone South - Room 306
https://twitter.com/OracleDevs/status/1165279207590649861
logos: JavaChampions & MP & IBM

**Comment by rstjames** [comment]
@Emily-Jiang can you please check the "session title" and put the correct one that you want to promote? + double check all info. After this is updated I will push this for you

**Comment by Emily-Jiang** [comment]
@rstjames done. By the way, I'm going to create another issue for my Thursday talk as I split this ticket to focus on individual talks instead of combined ones.
