### ISSUE TITLE
[CodeOne session]From zero to MicroProfile hero

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#192]
From Zero to MicroProfile Hero: Let’s Dive into a Microservices World [TUT3894]
We laugh at people who tell us Java is slow. The dark days of EJB2 are over. This tutorial shows you how to develop enterprise applications with just a few lines of code that can even run on a Raspberry Pi. MicroProfile optimizes Enterprise Java for a microservices architecture and delivers application portability across multiple runtimes. You can use a subset of Jakarta EE to develop MicroProfile applications, using JAX-RS, CDI, and JSON-P, and extend it with Config, JWT, Fault Tolerance, Health Check, Metrics, OpeanAPI, and OpenTracing. With live-coding examples, this presentation shows you how to get hands-on with MicroProfile and rediscover the pleasure of developing enterprise applications.

SPEAKERS

Jean-Louis Monteiro, Director of Engineering, TOMITRIBE

Roberto Cortez, Principal Architect, Talkdesk

Code One Tracks: Java Ecosystem, Emerging Tech, Java Server-Side
Session Type: Tutorial Session
Code One Star Speaker: Yes
Tuesday, September 17, 08:45 AM - 10:45 AM | Moscone South - Room 308

**Comment by rstjames** [comment]
![CodeOne-MicroProfile-TUT3894](https://user-images.githubusercontent.com/12132146/64869675-1a5d0480-d642-11e9-8e4a-7a98df6b8bc0.png)
