### ISSUE TITLE
[CodeOne session]Implementing Microservice Security via JWT and MicroProfile

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#193]
Implementing Microservice Security via JWT and MicroProfile [DEV4354]
Building from the ground up, this session deep-dives into implementing an OAuth 2.0 JWT architecture built on MicroProfile. It starts with a short view of a complete OAuth 2.0 JWT architecture, discussing what makes them both secure and scalable. Then a journey into MicroProfile JWT begins, detailing a bare-minimum starter project that has a simple REST service and Arquillian tests challenging security. It explores putting business data in JWTs, encrypted claims, CDI @Injection, and using Bean Validation to replace @RolesAllowed usage. Finally, it all gets tied together with a Pet Store–like AngularJS app that performs client-side login and refresh. All code is in Github. You’ll leave ready to bootstrap your next truly secure full-stack project.

SPEAKERS

Jean-Louis Monteiro, Director of Engineering, TOMITRIBE

David Blevins, Founder, Tomitribe

Code One Tracks: Java Server-Side, Modern Web
Session Type: Developer Session
Code One Star Speaker: Yes
Tuesday, September 17, 05:00 PM - 05:45 PM | Moscone South - Room 303

**Comment by rstjames** [comment]
Join @dblevins & @JLouisMonteiro @OracleCodeOne. September 17, 5:00-5:45 PM. They will leverage @MicroProfileIO #JWT to secure a #microservices based application from the @angular JS frontend to the backend business layer. 

![CodeOne-MicroProfile-Dev4354](https://user-images.githubusercontent.com/12132146/64868275-46c35180-d63f-11e9-9256-e4ca96214676.png)
