### ISSUE TITLE
[Blog] Review crosspost on introduction to MP

### ISSUE THREAD

**Issue by madsop** [microprofile/microprofile-marketing#196]
Submitted for review in Wordpress: https://microprofile.io/wp-admin/post.php?post=6377&action=edit

Feedback much appreciated!

**Comment by aeiras** [comment]
Congrats on publishing your very 1st MP blog @madsop!

two adjustments: 
1- title was expanded b/c what you had was **too general**-- always do your best to be specific and avoid generalizations if at all possible

2- your publication is a crosspost, when that is the case the link needs to be placed in 2 places. See pic below. My hope is that next iteration will be easier. Please help make better the blog guidelines. Given that that part wasn't clear, you could help next author get it right :) 

- [ crosslink needs to be added to 2 paces] <img width="754" alt="image" src="https://user-images.githubusercontent.com/10731224/64913796-a67f3280-d6fb-11e9-9975-5f7193ed10bc.png">

**Comment by madsop** [comment]
Thanks, @aeiras! I think the pull request from @lauracowen at https://github.com/microprofile/wpsite/pull/7 clarifies what I've noticed as well.
