### ISSUE TITLE
Pragmatic Microservices talk by Ondro at CodeOne 2019

### ISSUE THREAD

**Issue by OndroMih** [microprofile/microprofile-marketing#197]
Conference: Oracle Code One 2019

Conference website and social media links:
https://www.oracle.com/code-one/
@OracleCodeOne

Talk name: Pragmatic Microservices in Kubernetes with MicroProfile
Talk time: Tuesday, September 17, 08:45 AM
Talk Link: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=TUT2500
Speakers: Ondro Mihalyi, @OndroMih, Payara Senior Engineer
Tweet: Join @OndroMih at a tutorial about turning a monolith to #Microservices running in #Kubernetes with @MicroProfile @OracleCodeOne: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=TUT2500 #Payara #opensource #BreakNewGround

Picture of the speaker: https://blog.payara.fish/hubfs/Ondrej-1.jpg

**Comment by OndroMih** [comment]
Pictures of speakers:

* Ondro: https://blog.payara.fish/hubfs/Ondrej-1.jpg
* Fabio: https://blog.payara.fish/hubfs/Fabio.jpg

**Comment by aeiras** [comment]
@OndroMih, 

you need to submit each session by 1 ticket. re-do  by copy paste. hug you super soon, tonight!

**Comment by OndroMih** [comment]
OK, I'll do, @aeiras, thanks!

**Comment by OndroMih** [comment]
I kept only one session here and moved other sessions to #198, #199 and #200

**Comment by rstjames** [comment]
![CodeOne-MicroProfile-Ondro-Mihalyi](https://user-images.githubusercontent.com/12132146/64919132-8c029300-d7a7-11e9-93d3-5080f972c699.png)
