### ISSUE TITLE
Securing Microservices talk by Fabio and Ondro at Code One 2019

### ISSUE THREAD

**Issue by OndroMih** [microprofile/microprofile-marketing#198]
Conference: Oracle Code One 2019

Conference website and social media links:
https://www.oracle.com/code-one/
@OracleCodeOne

Talk name: Securing Microservices in Less Than 40 Minutes with Auth0 and MicroProfile
Talk time: Thursday, September 19, 01:15 PM
Talk Link: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV3440
Speakers: Fabio Turizo, @fabturizo, Payara Senior Engineer; Ondro Mihalyi, @OndroMih Payara Senior Engineer
Tweet: Join @fabturizo and @OndroMih to learn how fast & simple it is to secure your #Microservices using @microprofile and third-party #OAuth services @OracleCodeOne: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV3440 #Payara #opensource

Pictures of speakers:

* Fabio: https://blog.payara.fish/hubfs/Fabio.jpg
* Ondro: https://blog.payara.fish/hubfs/Ondrej-1.jpg

**Comment by rstjames** [comment]
@OndroMih It will go out Wed. 

![MicroProfile-CodeOne-DEV3440](https://user-images.githubusercontent.com/12132146/64952682-3a2e3b80-d881-11e9-9268-920f6c3d977b.png)
