### ISSUE TITLE
Reactive Features of MicroProfile talk by Ondro at Code One 2019

### ISSUE THREAD

**Issue by OndroMih** [microprofile/microprofile-marketing#199]
Conference: Oracle Code One 2019

Conference website and social media links:
https://www.oracle.com/code-one/
@OracleCodeOne

Talk name: Reactive Features of MicroProfile You Need to Learn
Talk time: Thursday, September 19, 12:15 PM
Talk Link: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV2491
Speakers: Ondro Mihalyi, @OndroMih, Payara Senior Engineer
Tweet: Join @OndroMih to learn about new @MicroProfile #reactive APIs and why it's important to learn them even if you haven't heard about #MicroProfile @OracleCodeOne: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV2491 #Payara #opensource

Pictures of the speaker: https://blog.payara.fish/hubfs/Ondrej-1.jpg

**Comment by rstjames** [comment]
It is scheduled to go out on Tuesday
![MicroProfile-CodeOne-DEV2491](https://user-images.githubusercontent.com/12132146/64951929-4addb200-d87f-11e9-9066-074f3c13844f.png)
