### ISSUE TITLE
Update 15 page e-Book sponsored by RH

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#2]
[MP Forum thread](https://groups.google.com/forum/#!topic/microprofile/nHoXvN6IOew)

**Comment by cealsair** [comment]
Hi Amelia,

We need to loop in the Eclipse Foundation for this. I'd suggest Paul White.

Thanks,
Cesar

**Comment by aeiras** [comment]
@cealsair thanks for the follow-up. There are two things:

- are you ok to own that task since RH was the one to sponsor the document and worked directly with the EF team?

- unrelated. You are a MP committer, as such your comments need to be shown as a Member of the MP committer in the 24 MP repos.  It seems that something is missing from your paper work with the EF. I recommend you follow up with the foundation. Cheers
