### ISSUE TITLE
Building Elastic and Cloud-ready apps talk by Ondro at Code One 2019

### ISSUE THREAD

**Issue by OndroMih** [microprofile/microprofile-marketing#200]
Conference: Oracle Code One 2019

Conference website and social media links:
https://www.oracle.com/code-one/
@OracleCodeOne

Talk name: 5 Recipes for Building Elastic and Cloud-ready apps
Talk time: Thursday, September 19, 10:00 AM
Talk Link: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV3465
Speakers: Ondro Mihalyi, @OndroMih, Payara Senior Engineer
Tweet: Join @OndroMih to learn 5 simple recipes to design and evolve flexible apps easily with @MicroProfile and other widespread #cloudnative APIs @OracleCodeOne: https://events.rainfocus.com/widget/oracle/oow19/catalogcodeone19?search=DEV3465 #Payara #opensource

Pictures of the speaker: https://blog.payara.fish/hubfs/Ondrej-1.jpg

**Comment by rstjames** [comment]
@OndroMih it will go out on Wed
![MicroProfile-CodeOne-DEV3465](https://user-images.githubusercontent.com/12132146/64950989-0b15cb00-d87d-11e9-80d5-f22730dc8be5.png)

**Comment by rstjames** [comment]
@OndroMih please make sure in future Media push you check your tweet message for correct @ You put in all your tickets " @microprofile" the correct one it "@MicroProfileIO"
