### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor.

### ISSUE THREAD

**Issue by codecr** [microprofile/microprofile-marketing#202]
Gerardo Arroyo,  gerardo@flecharoja.com

**Comment by aeiras** [comment]
Thank you for choosing to become the 50th wordpress MP content contributor @codecr! 

Bienvenido Gerardo :)

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/10731224/65451091-59821700-ddf3-11e9-83a5-03d1a215ce62.png">
