### ISSUE TITLE
Interview Martin Stefanko for blog

### ISSUE THREAD

**Issue by rdebusscher** [microprofile/microprofile-marketing#204]
I'll create a Google doc with the questions shortly ....

**Comment by aeiras** [comment]
amazing @rdebusscher! :)

**Comment by rdebusscher** [comment]
Interview questions here https://docs.google.com/document/d/1DDuxS-82xi45xMwzxUc-BHXJ8NMUMIfejEC9VldZ_j4/edit?usp=sharing

**Comment by aeiras** [comment]
Hey you two, 
Next Monday, David S interview will be published, without rush, do you know if yours will be ready for Nov fun? :)

**Comment by xstefank** [comment]
@aeiras it's stuck on my time limitations now. Rudy already gave me the questions I just need to find a while to fill the answers. November timeframe should be doable :)

**Comment by rdebusscher** [comment]
@aeiras Interview is ready, see Google doc https://docs.google.com/document/d/1DDuxS-82xi45xMwzxUc-BHXJ8NMUMIfejEC9VldZ_j4/edit?usp=sharing

**Comment by aeiras** [comment]
Received MicroProfilers @rdebusscher & @xstefank. 
I have added it to next week's Mktg call agenda, my hope is that a new wordpress editor will choose to own the final review.  Either way- besides scaling that task knowledge, you two can expect to receive a follow up by me on Tuesday :) So fun to get it out the week of Dec 16th, thank YOU both for #sharing!

**Comment by aeiras** [comment]
Hola @xstefank & @rdebusscher :)

Just got done reviewing the blog, smiling. 
I have suggested a few things and added comments for your consumption. Please take it as such, choose what to use & protect the wonderful tone nicely owned while navigating the sharing. 

Do pull me back in after you have completed the review and added the blog that you see as final version in Wordpress.  Once the draft is in wordpress, i will once again review content for extra care .
Ideally, it would be amazing if this interview closes 2019 #sharingIScaring project via on boarding. :) Thank you both for being beautiful with actions that show your care!

**Comment by aeiras** [comment]
@xstefank using my email via comments, you are most welcomed to ask anything you see fit directly via the doc if there is anything unclear from my suggestions.

**Comment by aeiras** [comment]
@xstefank, 

Saw latest updates, it reads fantastic. :) having the shorter Bio is +1 after pic. 

Please pull me back to enable publishing and media fun after @rdebusscher places the blog into wordpress. :)

**Comment by xstefank** [comment]
The document is then completed from my side.

**Comment by aeiras** [comment]
@rdebusscher, you need to become a wordpress MP contributor. for that please submit your email and i will provide you with access to import the blog. :) all within this ticket! 

Thanks for the follow up Martin, almost done 👍 100

**Comment by rdebusscher** [comment]
@aeiras my email for wordpress : rdebusscher@gmail.com

**Comment by aeiras** [comment]
@rdebusscher you are now a MP Content Contributor, yeay! 

 Now you can add content/video/tutorials related to MP and follow up, make better, the content contributors' guidelines as you populate content in MP :) 

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/10731224/71282950-da2db200-2313-11ea-9ba8-a67909690911.png">

**Comment by aeiras** [comment]
Back from nice Holidays, any progress @rdebusscher ? :)

**Comment by rdebusscher** [comment]
Hi Amelia,

I have created the post in WP and have submitted it for review some time
ago already.

**Comment by aeiras** [comment]
@rdebusscher, 

Gotcha. For future content contribution when using wordpress MP blog, you must notify via git as wordpress doesn't send notification on content. As usual, you are most welcomed to make the blog guidelines better by this iteration and clarify that exact part either in both, blog contribution & MP<>MP on boarding interview wikis. :) 

@xstefank & you have been fantastic navigating this fun side of MP during the Holidays, kudos. 
**Last step**, please copy/paste the word document of the blog into the [MP><Interviews Folder](https://drive.google.com/drive/u/0/folders/1xjzdU_U-nXNpg9jlweo6MPXcmhrfhlrc). That is the last ask. 

We will publish the blog, tweet and notify you and the forum! :)

**Comment by xstefank** [comment]
Hi @aeiras, does the shared document need to follow the same formatting? The document is copied here https://docs.google.com/document/d/1K0HQGuAqqWD74OHRImvB0_jOaIsb6Hsg6qefr1WOSro/edit?folder=1xjzdU_U-nXNpg9jlweo6MPXcmhrfhlrc#

**Comment by aeiras** [comment]
Hola Martin, 

thanks for moving interview there. I overlooked the "private" document when both of you pulled us in for editor's review. Now, everything is perfect! thanks :) 

<img width="852" alt="image" src="https://user-images.githubusercontent.com/10731224/72094584-93f0c080-32cb-11ea-89fb-d7e6c559dc4f.png">

**Comment by aeiras** [comment]
@rstjames, 

Thank you for publishing the interview your AM Monday!

For the first 2 weeks we have solely focus on WG discussions. With 3rd week in, let’s re-set to core basics & fun sharing!

**Comment by rstjames** [comment]
@aeiras  it is published and a tweet is going out today at 3:30 CET

@aeiras  not sure what you mean 
"For the first 2 weeks we have solely focus on WG discussions. With 3rd week in, let’s re-set to core basics & fun sharing!"

**Comment by aeiras** [comment]
I meant, MP ecosystem was focused on the discussion of the working group. 💪🏼 
Now, that we have stablished schedule, other activities are back to normal.

**Comment by aeiras** [comment]
design adjustments, publication push and media push via @rstjames  [Tweet HERE](https://twitter.com/MicroProfileIO/status/1219265826957791240?s=20)  Thank you Ryan! 

Thank YOU @xstefank  and @rdebusscher for prioritizing sharing! :) 

Rudy-- it is up to you to own the interviewee next step. Finding your interviewer, who can own the chain of sharing is up to you. You could add the item to a Community hangout and ask via that channel, as done before :) of just ping anyone who you know could be the it. Cheers!

**Comment by aeiras** [comment]
@rdebusscher, 

Your MP wordpress pic is not yet available, no rush yet it is nice for MP Wordpress to add a pic. None can update your MP wordpress profile but you. Cheers! :) 

<img width="140" alt="image" src="https://user-images.githubusercontent.com/10731224/72759855-c7650200-3b8b-11ea-97a3-20ae5b3833c1.png">

**Comment by rdebusscher** [comment]
I did set my picture when I first logged on into WordPress

It is still there, there must be something else wrong.

[image: Screenshot 2020-01-21 at 07.53.33.png]

**Comment by rstjames** [comment]
@rdebusscher @aeiras All looks fine.  I see Rudy's image on the MP site.
