### ISSUE TITLE
[Website Documentation] via Repo wiki ~ MKTG repo?

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#205]
Currently MP.io has 2 parts that are blurry to the community

- [need human ] wordpress and content pushes

- [ automatic] feed by git activity

**Comment by rstjames** [comment]
@aeiras Need more info what you want.

**Comment by rstjames** [comment]
Note for Ryan. Search for past documentation you did.

**Comment by aeiras** [comment]
[wiki](https://github.com/eclipse/microprofile-marketing/wiki/MicroProfile-Website-is-Updated-via-Git-Activity-&-Marketing)

@rstjames adding the link where the data needs to be documented. Thanks for located past documentation and place it in the wiki.

**Comment by aeiras** [comment]
@rstjames i think this ticket got forgotten. can you look at it  please? 

Wiki is still empty.

**Comment by rstjames** [comment]
@aeiras not sure what you want here? Did we have a call about the details on this task? If so I do not remember and the initial  comments on Oct 1, 2019 do not say enough to complete the task.

**Comment by aeiras** [comment]
@rstjames thanks for enabling to clarify this ticket. 

MP website is not fully OSS. 
one part is updated directly via Git, REPO activity yet not all. As the project adds/creates more Repos, those need to be added to website. Example: Projects, Contributors tabs

Other parts use for instance wordpress plug-ins by choice. Those parts are:
Blog
The microprofile starter is similar to Join the Discussion, direct links to action :) 

We need to document WHY and HOW the Website is being run. The wiki is exactly the space to compile this data.

**Comment by rstjames** [comment]
All is updated in the doc.
