### ISSUE TITLE
Mention Packt MicroProfile book on homepage

### ISSUE THREAD

**Issue by pilhuhn** [microprofile/microprofile-marketing#206]
Mention the Packt book on MicroProfile https://www.packtpub.com/web-development/hands-on-enterprise-java-microservices-with-eclipse-microprofile in the resources section of MicroProfile.io (likewise for other books on MP)

**Comment by aeiras** [comment]
perfect ticket @pilhuhn! :)

**Comment by rstjames** [comment]
Hello @pilhuhn. Thank you for making this ticket. After discussing this topic with @aeiras, I voiced my opinion that it would probably be best to promote your "Packt book" with a blog post. I feel it would not be scalable if everyone who released a book to be featured on the home page. Especially that this is not a community push/ non profit publication. 

Please let me know what you think about putting out a blog about your "Packt book" and we can promote in on MP social media.

**Comment by phillip-kruger** [comment]
Hi @aeiras  - I see I am assigned. Not sure what I need to do ?

**Comment by aeiras** [comment]
Hey @phillip-kruger, i added you by mistake, no excuses that the project is RH produced.  Now fixed.  :) 

@pilhuhn -- fixing the previews pull mistake. Hola first. 
 we recommend a short to the point copy/paste of the abstract of the book in a blog format, adding in MP wordpress as a blog with the link to the book. 
That blog then can be pushed via the MP media, say every 2 weeks, as the white paper is pushed today.  

As it is, as explained during the MP community hangout and this thread, it is not scalable to add to resource tab b/c it requires human intervention. The resources tab in the website is the only part that is not automatic, therefore, any item that is added must be sure not to be later debt. Get it? 

@cealsair forgot to pulled you in this thread on today's mktg call, please see above. I see you are also a collaborartor in the book.

**Comment by aeiras** [comment]
hey writers, 

is there a blog on this book via MP website? been too long, cannot find it. 
thanks for the follow up, ideally, this book can be added to the 2020 constant media push, say 1 per month twitter push to remind interested readers about it. 
Same initiate is being taken with e books, currently 2 already added to the blog that are hopefully to be approved by the authors as a constant running via MP media! 

-- cheers

**Comment by aeiras** [comment]
Oct 2019 to now, it seems that a blog for publish book is not in the cards. 
Will close ticket, if the authors choose at a later time to write a blog, kudos :)
