### ISSUE TITLE
MP talk at GeeCon - A different flavor of the distributed transaction

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#208]
Conference Name:
GeeCon Prague 2019

Conference website and social media links:
https://2019.geecon.cz
https://twitter.com/GeeCON

Talk name:
A different flavor of the distributed transaction

Talk Link:
https://2019.geecon.cz/speakers/?id=580

Date and time: Oct 18, 10:10 - 11:00, Room 4

Speaker Names:
Martin Štefanko (or Stefanko :)), a software engineer at Red Hat

Tweet Message:
either retweet please https://twitter.com/GeeCON/status/1181114171917778944

or something generic will be fine.

**Comment by rstjames** [comment]
@xstefank 
Dobrý den,
All good to go.  I will schedule it on social media to go out a couple times. 
![MP-GeeCon-MartinStefanko](https://user-images.githubusercontent.com/12132146/66575106-ab59c980-eb75-11e9-896a-1a4b990f4caf.png)

Tweet:
Join Martin Štefanko @xstefank @GeeCON where he will present "A different flavor of the distributed transaction” Oct 18, 10:10 - 11:00, Room 4, Prague Czech Republic

@MicroProfileIO #opensource #OSS #MicroProfile

**Comment by xstefank** [comment]
@rstjames Thanks a lot!
