### ISSUE TITLE
[Blog] Review blog post

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#211]
Link: https://microprofile.io/wp-admin/post.php?post=6404&action=edit

I wasn't able to find "Page Header Settings" in Link mode as described in https://github.com/microprofile/wpsite.

**Comment by aeiras** [comment]
Martin, you are crossposting content so it is different that adding original content, only in the site. 

if your blog is done, I will publish it and you can see whats what. If needed, we can adjust blog guidelines to match what you have seen via actions, etc. Let me know by pulling me in this ticket.

**Comment by xstefank** [comment]
@aeiras I was following cross-posting session :) but these "Page Header Settings" wasn't on the WP page. Nothing critical from my side. I can update the doc to remove this point if needed.

My blog is done but if there are any comments I can still adjust it. It's hosted on my site.

**Comment by aeiras** [comment]
Martin, 

If the page header is not there for crossposting option anymore, please send a PR against the wiki to help update the guidelines to what currently is :) 

Your blog is published and it reads great from what you chose to add to start the blog to the examples. From my side your first MP blog rocks in value! Now, if you tweet it via your handle, MP tweet can re-tweet you, just add the MP twitter handle to broaden the sharing. Please use this feedback for future iterations.  :) Again, you rock!
