### ISSUE TITLE
Reactive Features of MicroProfile talk by Ondro at GeeCon Prague 2019

### ISSUE THREAD

**Issue by OndroMih** [microprofile/microprofile-marketing#212]
Conference website and social media links:

* https://2019.geecon.cz/
* https://twitter.com/geecon

Talk name: Reactive Features of MicroProfile You Need to Learn
Talk time: Friday, October 19, 1:50 PM
Talk room: Room 6
Talk Link: https://2019.geecon.cz/speakers/?id=569
Speakers: Ondro Mihalyi, @OndroMih, Payara Senior Engineer
Tweet: Join @OndroMih to learn about new @microprofile #reactive APIs @GeeCon and why it's important to learn them even if you haven't heard about #MicroProfile. Friday at 1:50pm room 6: https://2019.geecon.cz/speakers/?id=569 #Payara #opensource #geecon

Picture of the speaker: https://blog.payara.fish/hubfs/Ondrej-1.jpg

**Comment by rstjames** [comment]
@OndroMih All scheduled. Please be carful with your tweet message. You has the MP twitter handle wrong. I adjusted it.

**Comment by aeiras** [comment]
@rstjames the GeeCon template designs with the pic of the city rock. Can you please drop the templates on the social media folder and while at it keep up adding templates as created by different events in different countries. It seems to me, that such a cute templates can be used in the future :)  Thanks for the follow up!
