### ISSUE TITLE
[Blog] Review blog post for tutorials on each MP spec

### ISSUE THREAD

**Issue by rieckpil** [microprofile/microprofile-marketing#213]
Hi,

I've submitted a new blog post for the microprofile.io WP page: https://microprofile.io/wp-admin/post.php?post=6408

This includes links to tutorials for each MP spec on my homepage to help newcomers or seasoned Java EE developers to start with MicroProfile.

Kind regards,
Phil

**Comment by rieckpil** [comment]
some WP admins here who can review the post?

**Comment by aeiras** [comment]
@rieckpil Philip, 

Your tutorial set of MP API start- how is published and it is a strong 1 house blog tutorial. 

Could you **consider** submitting/making it a part of the [How to become a MicroProfile](https://microprofile.io/contributors/)? If yes,  just click the call to action yellow bottom.  Should you have questions about  it reach out. No pressure & really happy to review your latest blog, thanks for the 2nd "i need help" .

**Comment by rieckpil** [comment]
Hi @aeiras,

thanks for reviewing and publishing the post :+1: 

Yes, I would like to also make it part of the How to become a MicroProfile. When I click on your link I get redirected to the contributor's page of MP https://microprofile.io/contributors/ and the yellow action button sends me to the GitHub page: https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc and where should I now exactly also submit it? I'm confused :laughing:

**Comment by aeiras** [comment]
fun follow up @rieckpil :) thanks for caring enough to enable clarification, I appreciate it lots! :) 

Correct, submitting the PR against the .adoc is needed should you want to help a bit more.  
My recommendation is to add the link of the tutorial blog as a **subset** of: Contribute your MicroProfile content blog/tutorial/video post.

Lets use ### the same wording as placed in the _published blog:_ ~
"Q4-2019 tutorials & video/code examples make it easy for YOU, a newcomer, to navigate MicroProfile's 12 APIs."  or similar-- lets be exact, less is more. :) 


For your reference, this is the git where the .adoc became the result of C2A in the Website! :) https://github.com/eclipse/microprofile-marketing/issues/12

Lastly, pull me in via this issue once you have submitted the PR to avoid delays with review and publishing. :) You have my attention!

**Comment by rieckpil** [comment]
Thanks for clarification @aeiras. I've created a PR: https://github.com/eclipse/microprofile/pull/139

Thank you very much,
Phil
