### ISSUE TITLE
Publishing the updated MP data sheet on https://microprofile.io/resources/

### ISSUE THREAD

**Issue by shabnammayel** [microprofile/microprofile-marketing#215]
Hi, can you please add the updated MP data sheet on https://microprofile.io/resources/

Below is the Pdf link to the updated data sheet:
[MP-dataSheet-Oct-15-2019 .pdf](https://github.com/eclipse/microprofile-marketing/files/3730762/MP-dataSheet-Oct-15-2019.pdf)
and here is the link to the folder that includes the updated file in Pdf and .ai
https://drive.google.com/drive/folders/1wljw5u5Okt0oVycRkYaQmsyuyt63kHUY
Thanks

**Comment by rstjames** [comment]
@aeiras I do not see a section to update for the MP datasheet. Do you mean add a new section to the resource page with the data sheet?

**Comment by rstjames** [comment]
@shabnammayel @aeiras I added a CTA for the data sheet on the Resource page.
