### ISSUE TITLE
MP at JFuture

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#216]
Name of the speakers: Mads Opheim and Rustam Mehmandarov
Name of the session: IoT powered by MicroProfile - microservices in practice

Links
https://twitter.com/madsopheim
https://twitter.com/rmehmandarov

https://github.com/mehmandarov/microprofile-iot

https://https://jfuture.dev/

Location
JFuture, Minsk, Belarus, November 16

Description:
We are going to show you what happens when the management lets enterprise Java developers and architects decide how we can control the IoT devices in our new office. While it’s easy to figure out why MicroProfile is cool, it’s harder to see how to get in into your project.

By the end of this talk, you will be introduced into the patterns and software in the enterprise world of Java explaining how to build a build a secure, stable, modular, and integrated system on an example of a completely over-engineered IoT solution to control the lights and plant’s well-being in the new office.

Fear not if your system is more complex than controlling light bulbs and plants! This talk will show you how easily you can design a good production-ready Java full-stack system based on the Enterprise stack with MicroProfile combined with good continuous deployment infrastructure patterns.

There be code, demos, and (buzzword) dragons.

**Comment by mehmandarov** [comment]
@madsop ☝️

**Comment by rstjames** [comment]
@mehmandarov  PLease provide a tweet message for this session. After I will create an image and schedule it to go out on MP handle

**Comment by madsop** [comment]
Hi, Ryan! Rustam won't be able to attend JFuture, so I'll give the talk solo. Here's my suggested tweet:

Добры дзень! Join @MadsOpheim at @jfuturedev for a session on MicroProfile - what is it, why is it useful and how do you use it on your project? He’ll showcase it on an overengineered IoT problem, and show parallels to how you’d do it on real enterprise applications.

**Comment by rstjames** [comment]
@madsop Ok made the adjustment and scheduled 2 tweets to go out. 

![MicrProfile-JFuture-2019](https://user-images.githubusercontent.com/12132146/68024687-1ac16580-fcab-11e9-8e11-9bf36e511ad9.png)
