### ISSUE TITLE
MP at J-Santa

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#217]
Name of the speakers: Mads Opheim and Rustam Mehmandarov
Name of the session: IoT powered by MicroProfile - microservices in practice

Links
https://twitter.com/madsopheim
https://twitter.com/rmehmandarov

https://github.com/mehmandarov/microprofile-iot

https://j-santa.pl/home/

Location
J-Santa, Lublin, Poland, November 30

Description:
We are going to show you what happens when the management lets enterprise Java developers and architects decide how we can control the IoT devices in our new office. While it’s easy to figure out why MicroProfile is cool, it’s harder to see how to get in into your project.

By the end of this talk, you will be introduced into the patterns and software in the enterprise world of Java explaining how to build a build a secure, stable, modular, and integrated system on an example of a completely over-engineered IoT solution to control the lights and plant’s well-being in the new office.

Fear not if your system is more complex than controlling light bulbs and plants! This talk will show you how easily you can design a good production-ready Java full-stack system based on the Enterprise stack with MicroProfile combined with good continuous deployment infrastructure patterns.

There be code, demos, and (buzzword) dragons.

**Comment by mehmandarov** [comment]
@madsop ☝️

**Comment by rstjames** [comment]
@mehmandarov please provide your tweet message.

**Comment by rstjames** [comment]
@mehmandarov looking like this: (please provide tweet message about your session) 
![MicrProfile-J-Santa-2019](https://user-images.githubusercontent.com/12132146/67471064-12d04880-f64f-11e9-81af-8b289949e320.png)

**Comment by mehmandarov** [comment]
@rstjames: How about this Tweet: "Join @rmehmandarov and @madsop for their talk about @MicroProfileIO and #cloudnative #Java applications at J-Santa.pl on November 30th!"

**Comment by rstjames** [comment]
@mehmandarov scheduled it to go out twice.
