### ISSUE TITLE
[Blog] New blog post – endpoints

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#218]
Hi,

I've submitted a new blog post for the microprofile.io WP page: https://microprofile.io/wp-admin/post.php?post=6423. The post is about handling endpoints in MP.

Best regards,
Rustam

**Comment by aeiras** [comment]
@mehmandarov Rustam, published and i must said, you added the coolest blog header for this blog! 
Awesome! :) If you tweet, enable MP to re-tweet you by using @ microprofile handle 👍
