### ISSUE TITLE
MP talk at EclipseCon Europe

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#219]
Conference Name:
EclipseCon Europe 2019

Conference website and social media links:
https://www.eclipsecon.org/europe2019
@EclipseCon

Talk name:
Creating a cloud-native microservice – which programming mode should we use?

Talk Link:
https://www.eclipsecon.org/europe2019/sessions/creating-cloud-native-microservice-%E2%80%93-which-programming-mode-should-i-use

Speaker Names:
Emily Jiang, Liberty Microservice Architect and Advocate, IBM

Tweet Message:
Join @Java_Champions @IBMDeveloper @EclipseCon Speaker @emilyfhjiang to learn the similarity and differences between #MicroProfile and #SpringBoot 
Time: 23 Oct 2019 - 12:00 to 23 Oct 2019 - 12:35
Room: Theater Stage

logos: JavaChampions & MP & IBM

**Comment by Emily-Jiang** [comment]
@aeiras @rstjames please can you tweet before 22nd Oct!

**Comment by kenfinnigan** [comment]
@Emily-Jiang I'm not sure this is possible as I believe the process requires at least a couple of weeks before a conference to create the cards

**Comment by rstjames** [comment]
@Emily-Jiang  Sorry did not receive a notification for some reason. But as stated before 2 week notice for these tickets is needed. Next time assign this ticket to me... that would help.
