### ISSUE TITLE
Create & schedule weekly tweets about Becoming a Blog/video Contributor

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#22]
Minimum requirements:

- add link to blog guidelines 

- create a template for blog design as the banner of tweet

- recommended hashtags: 
 #writethetalk, #sharingIScaring #OpenSource #Community 

- I recommend 1 tweet for week, Wednesdays as a recurring tweet for the rext of 2019, ending on Dec 25th, 2019.

**Comment by aeiras** [comment]
@rsjames should you need help with the description of this tweet, happy to provide back up. :)

**Comment by aeiras** [comment]
brainstorming description: 

@MicroProfileIO💛 Contributors prioritize sharing what they learn with MP! #MicroProfilers feed of video/tutorials/written valuable content to the #MPblog is amazing💪🏽! If you are not a #MPcontent contributor, join the fun https://bit.ly/2OiPWkD. #OSS #community #sharingIScaring

**Comment by aeiras** [comment]
@rstjames where are we with this?

**Comment by rstjames** [comment]
@aeiras Changed the tweet a bit. I feel it reads a lot easier. Visual is bellow. 
Are you a #MPContributors? Have you shared what you have learn with @MicroProfileIO 💛? Share your MP video/tutorials/written valuable content to the #MPblog 💪🏽! If you are not a #MPcontent contributor, join the fun https://bit.ly/2OiPWkD #OSS #community #sharingIScaring

![MicroProfile-Contributors-Share](https://user-images.githubusercontent.com/12132146/55879649-67264600-5b9f-11e9-88f1-4333e8805bc5.png)

**Comment by aeiras** [comment]
you are correct @rstjames, it reads better. Let’s correct grammar in both: the design and description:

#MPContributor is singular.
... have you shared what you are learning  with @MP gold heart?

**Comment by rstjames** [comment]
@aeiras found a couple other grammatical errors and fixed them. 

Are you a #MPContributor ? Have you shared what you have learned with @MicroProfileIO 💛? Share your MP videos/tutorials/written content to the #MPblog 💪🏽! If you are not a #MPcontent contributor, join the fun https://bit.ly/2OiPWkD 

#OSS #community #sharingIScaring #opensource 


![MicroProfile-Contributor-share](https://user-images.githubusercontent.com/12132146/55944194-5e3d7f00-5c48-11e9-8236-aba639218545.png)

**Comment by rstjames** [comment]
All scheduled on twitter

**Comment by aeiras** [comment]
just fantastic Ryan, you rock!
