### ISSUE TITLE
[Schedule a constant media push] Communities organizing events with focus on MP

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#220]
using original[ Help organizing "MicroConferences" about MicroProfile](https://github.com/eclipse/microprofile-marketing/issues/126) lets schedule a 6 months weekly run reminder with a cool design about Community DOERS. :) 

Requirements on the media push:

- To welcome commutes to add the MP events to the sheet: 

[JUGs/Communities Promoting Java/MP releated technologies](https://docs.google.com/spreadsheets/d/1ThPhMwRsfLob1n0up0sUCzOEdfJUGVZVmakEyYcS5bU/edit?pli=1#gid=0)

- Description to be added next week:

**Comment by rstjames** [comment]
@aeiras Ok we should talk about this more.

**Comment by rstjames** [comment]
@aeiras create a description/ tweet.

**Comment by aeiras** [comment]
not needed as Social media speakers' reminder covers this.
