### ISSUE TITLE
Update website landing page with MicroProfile 3.2 release icon

### ISSUE THREAD

**Issue by cealsair** [microprofile/microprofile-marketing#222]
MP 3.2 just went out. Announcement is out. MP.io landing page needs to be updated. Ryan, per your request, here's the ticket.

Thank you,
Cesar

**Comment by rstjames** [comment]
@cealsair I also need the new links for all CTA on the website. And what are we saying about this release. I will look at the blog but... why is there no communication before releasing this new version? We should all be aligned when a new release is going out the websites is updated at the same time. We discussed that it would happen sometime this week last night and now I just heard its out...

**Comment by rstjames** [comment]
@cealsair I was surprised and i guess you were too :) 
I will get it updated tomorrow morning
