### ISSUE TITLE
MP Talk at TDC Porto Alegre 2019

### ISSUE THREAD

**Issue by tuxtor** [microprofile/microprofile-marketing#223]
Conference Name: The Developers Conference Porto Alegre 2019

Conference website and social media links:

- https://thedevconf.com/tdc/2019/portoalegre
- @TheDevConf

Talks Links
https://thedevconf.com/tdc/2019/portoalegre/trilha-java

Session Name: Take advantage of MicroProfile benefits in your monolithic applications 
Date and hour: Wednesday, November 27th. 2019 (12:10 - 13:00)

Speaker name: Víctor Orozco
Speaker twitter handle: @tuxtor

Description
Join @tuxtor at @TheDevConf to discuss and learn how could you take advantage @MicroProfileIO APIs and patterns in your existing monolithic applications - Wednesday, November 27th More info: https://thedevconf.com/tdc/2019/portoalegre/trilha-java
#OpenSource #OSS

**Comment by rstjames** [comment]
@tuxtor scheduled to go out week before and day before the session 
![MicroProfile-DevConPorto-Victor](https://user-images.githubusercontent.com/12132146/68864261-22442e00-06f1-11ea-9d38-9e07c02cd1ac.png)
