### ISSUE TITLE
[Community call 2020] media push

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#229]
It will be kept as it is, lets keep today's media structure, with a refresh on the design side of things. 
same wording, same reminders. 

Also, lets find a way to include the How to Contribute link to the msg: https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc

Ryan
[see ](https://drive.google.com/drive/folders/1_iIXdbuajMOT0ssSJ9xYJAcoCqmDluwr)or use the same one, it is up to you. :) Using your feedback, i have been taking screen shots of the MP hangouts I attend, those pics are twitted on the spot and also added to MP Mktg>Photos folder in the drive. 

Thanks @rstjames

**Comment by rstjames** [comment]
set for the year!
