### ISSUE TITLE
Add Resource Tab & sub-organize via tabs

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#23]
organize the content under Sub-tabs to be consumed will less words:

- e-books

- white papers

- case studies

- Conference/JUGs MP abstracts available for download

- MP presentation template (at least 2 templates)

- Video sessions recorded from past MP presentations added under Conference sub-tab

**Comment by rstjames** [comment]
@aeiras They do not have their own pages to take them to in a sub menu.
These pages would need to be created to do this.

**Comment by aeiras** [comment]
Lets add that as a new feature for Resources directly in the [skelleton doc](https://docs.google.com/document/d/1Ga7Z1aVgq4EcE19mSg5Ig9zugg3xqlXOkZnqsheX61o/edit). 
we won't work in adjutments on MP.io yet. Closing ticket. :) thanks for this follow up Ryan.

**Comment by aeiras** [comment]
@rstjames lets re-open this ticket and further updates, drop them here :) 

One thing is that Resources page is a space for:

- Coders/MicroProfilers

- Users/Clients 

In some way this page must accomodate the two groups that at times are not the same people.

**Comment by aeiras** [comment]
@rstjames we re-opened this ticket b/c it matters to get tab improved. Using this ticket, please share the screen shots you have thus far on options. :) show and tell via this channel might be the best form to enable quick feedback by anyone. thanks!

**Comment by aeiras** [comment]
On next Community call, lets tackle the resources tab with an update @rstjames, thanks!

**Comment by rstjames** [comment]
@aeiras I can add the sub menu but most of these pages do not have their own page. I can link the menu item to a targeted section on each page if this helps.

**Comment by rstjames** [comment]
@aeiras added a sub menu that links to each section on the page. Should we close this ticket? 
<img width="1171" alt="Screen Shot 2019-11-04 at 10 41 03 AM" src="https://user-images.githubusercontent.com/12132146/68111571-bc38f900-feef-11e9-96e2-4f8dbf7c8d06.png">

**Comment by aeiras** [comment]
@rstjames, 

It looks great! **Yes**  lets close this ticket. Can you own sending the git issue link to the MP forum as a written update on website tab betterment? thank YOU :)

**Comment by aeiras** [comment]
@rstjames, 

Lets also add a sub tab link to the [MP_Marketing gDrive](https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8):

**Comment by rstjames** [comment]
@aeiras  I will try to finish up the MP design recourse page this week and I can add this to the sub sections. That page will have all google drive recourse.

**Comment by aeiras** [comment]
your dedication and speed rock Ryan! thank YOU :)

**Comment by aeiras** [comment]
Nicely updated, thanks Ryan! @rstjames
