### ISSUE TITLE
[Submit your MP content] media push for 2020

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#232]
[example 2019](https://twitter.com/MicroProfileIO/status/1202226801033900032?s=20)

media description requires adjustments, the rest follows the other ticket's feedback:

**Media description:**

_#MicroProfileContributors have you shared what you have learned with 
@MicroProfileIO💛 yet?  Submit your #MicroProfile videos/tutorials/blogs/sessions to the #MicroProfileBlog by using the guidelines found here:  https://bit.ly/2OiPWkD 

#MPcollaboration #OpenSource_

**Comment by rstjames** [comment]
![MicroProfile-Content-Submit](https://user-images.githubusercontent.com/12132146/75451264-82916f80-5970-11ea-8fe7-ba983b4051bb.png)
all set on twitter for the year
