### ISSUE TITLE
MP Talk at JavaLand 2020

### ISSUE THREAD

**Issue by javahippie** [microprofile/microprofile-marketing#233]
Conference Name: JavaLand 2020

Conference website and social media links:

https://www.javaland.eu/
@JavaLandConf
Talks Links
https://programm.javaland.eu/2020/#/scheduledEvent/590520

Session Name: MicroProfile Implementations - which one suits me? [GERMAN TALK]
Date and hour: Tuesday, March 17th. 2020 (12:00- 12:40)

Speaker name: Tim Zöller
Speaker twitter handle: @javahippie

Description
Join @javahippie at @JavaLandConf 2020 in Brühl for a deep dive into the most common MicroProfile runtimes like @thorntail_io, @Payara_Fish, @ApacheTomEE, @OpenLibertyIO, @kumuluz and @helidon_project. https://programm.javaland.eu/2020/#/scheduledEvent/590520  (Language of the talk is German)

**Comment by rstjames** [comment]
@javahippie I scheduled the tweet to go out twice before your session .
![MicroProfile-JavaLand-Tim Zöller-2020](https://user-images.githubusercontent.com/12132146/73944133-572bdf80-48f2-11ea-823b-d34ce83830b8.png)
