### ISSUE TITLE
[MP Working Group Proposals] Awareness via Media Push weekly

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#234]
@rstjames thank you in advance for helping us prioritize the media push of this task. Lets tackle logistics via this ticket and get the very first push out this Friday, Dec 13th.

**requirements:**

- design uses the Community pics from [the drive](https://drive.google.com/drive/folders/1_iIXdbuajMOT0ssSJ9xYJAcoCqmDluwr) with MP branding

- forum thread[ public link](https://groups.google.com/forum/#!topic/microprofile/zwFhZec8MGA)

- Proposals via  PRhttps://github.com/eclipse/microprofile-sandbox/tree/master/proposals/working-group

- schedule: every Tuesday/ 1 per week from Dec 17th to Feb 25th, last tweet reminder. 

**Media description message**

I will write it by Thursday. First I need consume the proposals. :) Lets do this!

**Comment by rstjames** [comment]
@aeiras Here is an image for it. I updated the images and took people from other calls and made one big image with everyone I could find. 

![MicroProfile-CommunityCall-2020](https://user-images.githubusercontent.com/12132146/70796034-8bc36500-1da1-11ea-8cf2-3f1bbf725318.png)

Tweet: (from before) 
@aeiras what changes would you like? 

Join the @MicroProfileIO #Community calls 💛 https://bit.ly/2DR3nDp bi-monthly-Tuesdays 11am PDT. #Contributing increases your knowledge. Be a valuable💪🏽 #MPContributor by adding the topics that matter most to YOU to the agenda http://bit.ly/2HXiOh0 #process #transparency #oss

**Comment by aeiras** [comment]
@rstjames 

**Design wording:**

- Join the (white)
MicroProfile Proposals Discussions (yellow)
Participate via the PRs & the Forum thread happening through Feb. 28th (white)

**Design**

- lets add the MP coffee cup :)

**Comment by aeiras** [comment]
@rstjames 

**Design wording:**

- Join the (white)
MicroProfile Proposals Discussions (yellow)
Participate via the PRs & the Forum thread though Feb. 28th (white)

**Design**

- lets add the MP coffee cup :)

**Comment by aeiras** [comment]
**media description** schedule today or saturday and pushed every Tuesday until Feb 25th

The @MicroProfileIO Community needs to define a #WorkingGroup that satisfies the @@EclipseFdn IP Grant & Flow requirements AND the EF Specification Process. The outline proposals welcome your PRs and comments HERE (link here). Thread forum HERE (link here)

**lets make sure that both links are public view and require no long-in to see**
-[ proposal link](https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/working-group)

- [Forum thread link ](https://groups.google.com/forum/#!topic/microprofile/zwFhZec8MGA)

**Comment by aeiras** [comment]
If there is any space, #CommunityFIRST **or** #OSS

**Comment by aeiras** [comment]
Ryan, 

Lets schedule it for Tuesdays and Saturdays each week until the end of Feb. :) Thank YOU!

**Comment by rstjames** [comment]
Final Tweet: 
The @MicroProfileIO Community needs to define a #WorkingGroup that satisfies the @EclipseFdn IP Grant, Flow requirements AND the EF Specification Process. The outline proposals welcome your PRs & comments HERE http://bit.ly/2rxiZdf Thread forum HERE http://bit.ly/38D4Iwg
#OSS 

![MicroProfile-WorkingGroupProposals](https://user-images.githubusercontent.com/12132146/70820621-681c1100-1dd9-11ea-9fdc-7be3a48b988b.png)

**Comment by aeiras** [comment]
Pretty fantastic Ryan, clearly I biasly adore the coffee cup with MP logo. :) 
Thanks for the prompt work on this!
