### ISSUE TITLE
[MP Blog] Announcing Eclipse MicroProfile Course Bundle

### ISSUE THREAD

**Issue by rieckpil** [microprofile/microprofile-marketing#236]
Hi,

I've just submitted a new post for microprofile.io: https://microprofile.io/wp-admin/post.php?post=6475 which contains a link to my Eclipse MicroProfile Course Bundle for newcomers.

PS: Thanks again @aeiras for the reminder.

Kind regards,
Phil

**Comment by aeiras** [comment]
Your ebook is now a part of the blog series of 2019 Phil. :)

**Comment by aeiras** [comment]
Hey @rieckpil, 

Would you consider participating in a Tech Talk to help us navigate through out your book?
https://www.eclipse.org/lists/jakarta.ee-community/msg01493.html Please check out the link I have added here.  If yes, do own it via the forum itself and follow up the MP session media coverage. :) 

No pressure, yet I recommend this step for many reasons. Abrazos,

**Comment by rieckpil** [comment]
Hi @aeiras,

I am not sure how to fill 30-40 minutes to help others to navigate through a 70 page PDF :D

**Comment by aeiras** [comment]
My recommendation then is for you to choose 2 technical charters to dive into code! 👌🏼💪🏼🥋

A book, yours - is similar to training, as such you can choose any chapter & dive into at will! 

I hope this helps to consider the importance of a code dive session based on the book by focus Phil! 🔓

**Comment by rieckpil** [comment]
thanks for raising this idea @aeiras but I don't see that much value for the audience going into technical detail for some chapters of the book. I have a more valuable topic for such a session in my mind (Jakarta EE black box/integration test with MicroShed Testing), but would need some preparation time, which I currently don't have

**Comment by aeiras** [comment]
your follow up rocks Phil :) own sharing as you see fit, when you see fits. :) 
Should you need anything, you know the public forums where to reach out. Cheers

**Comment by aeiras** [comment]
> Hi,
> 
> I've just submitted a new post for microprofile.io: https://microprofile.io/wp-admin/post.php?post=6475 which contains a link to my Eclipse MicroProfile Course Bundle for newcomers.
> 
> PS: Thanks again @aeiras for the reminder.
> 
> Kind regards,
> Phil

Hola Philip, 

Back to formally get your wonderful ebook scheduled in MP media to properly thank you for dedicating such a time to share what you have learned. :) 

@rstjames the ebook blog link is HERE: https://microprofile.io/2019/12/30/announcing-the-eclipse-microprofile-course-bundle/
 it re-directs to Philip's ebook directly, yet to push it via MP media, the above's link needs to be used for the bi-monthly media push. running it through July or August Ok to welcome potential updates on content. Not a requirement Philip, just remember to send a new git issue if there is an update to current ebook bundle and done. :) no tasks, no pressure. 

Ryan, @rstjames-- lets use the similar description format as with Hayri's ebook push. Lets ask MicroProfiler @rieckpil to approve that draft before it goes live. :)

**Comment by aeiras** [comment]
**blog description as follows to help with draft write up:**
All you need to know about each Eclipse MicroProfile specification in one-course Bundle. The first edition is available for FREE.

» includes: E-Book, Video Course and a cheat sheet for all major application servers and up-to-date with the latest Eclipse MicroProfile release 3.2

» add missing parts (e.g. Open API support, JWT Auth, Resiliency, etc.) to existing Enterprise Java applications.

**Comment by rieckpil** [comment]
Hey Amelia,

thanks for getting back and your initiative to push newcomers to the bundle. I really appreciate this 👍 

My action item is to file a new git issue here once a new version is available? I'm planning to update the content to MP 3.3 once OpenLiberty supports it.

I would adjust the draft a little bit to the following:

All you need to know about each Eclipse MicroProfile specification in a single course bundle.

» This includes an E-Book, a 2h video course and a cheat sheet for all major application servers. The content is up-to-date with the latest Eclipse MicroProfile release _(3.X/4.X to be replaced)_

» add missing parts (e.g. Open API support, JWT Auth, Resiliency, etc.) to your Enterprise Java applications to make them cloud-ready or use it standalone.

for the rest you have my approval @aeiras & @rstjames

**Comment by rstjames** [comment]
@rieckpil Do you think its best for us to wait to push this on MP media until after MP 3.3 and you have updated everything?

**Comment by rstjames** [comment]
@rieckpil I will push this version for a 1-2 month until you have and updated version.

**Comment by aeiras** [comment]
> @rieckpil I will push this version for a 1-2 month until you have and updated version.
@rstjames how about media push is run for Q2 (April-May-June) to not push adjustments as done with Cicek's ebook?

Phil- it is fantastic to have the blog and see latest update before media push. Correct on future content update. Submitting a new git issue with new blog link is the process that keeps us sharing! :) cheers from home! be safe.

**Comment by rstjames** [comment]
**Tweet message: @rieckpil @aeiras** 
Looking for a good read? @rieckpil put together a comprehensive MicroProfile Course Bundle to start learning Eclipse MicroProfile. The Bundle contains an E-Book, a video course & a cheat sheet to kickstart your MicroProfile success. https://bit.ly/2UJAb9V

#opensource #oss #MicroProfileeBOOK

![MicroProfile-Ebook-Philip Riecks](https://user-images.githubusercontent.com/12132146/77782390-70a8f800-7014-11ea-8f02-8eba0f6178f0.png)

**Comment by rieckpil** [comment]
that looks awesome, thanks for your effort 👍

**Comment by rieckpil** [comment]
> Phil- it is fantastic to have the blog and see latest update before media push. Correct on future content update. Submitting a new git issue with new blog link is the process that keeps us sharing! :) cheers from home! be safe.

Most probably the link to the course will never change on my site and I'll rather update the page/book itself. 

Or do you mean I should submit a new blog post on microprofile.io (like https://microprofile.io/2019/12/) once I update the content to inform everyone that MP 3.3 is supported?

**Comment by aeiras** [comment]
thanks Ryan. 
@rieckpil Phil-- the idea is that content lives as it is used and is updated. as such, I recommend you submit a new blog with that link as done with first version so that the media push can contain exact description on what's new. Only that seems efficient and effective. Bring the reader to your website from MP blog is preferred as it tracks changes and versions. Lets always assume the reader know nothing. With that in mind, send back your follow up & lets schedule your awesome bundle. :)

**Comment by aeiras** [comment]
> **Tweet message: @rieckpil @aeiras**
> Looking for a good read? @rieckpil put together a comprehensive MicroProfile Course Bundle to start learning Eclipse MicroProfile. The Bundle contains an E-Book, a video course & a cheat sheet to kickstart your MicroProfile success. https://bit.ly/2UJAb9V
> 
> #opensource #oss #MicroProfileeBOOK
> 
> ![MicroProfile-Ebook-Philip Riecks](https://user-images.githubusercontent.com/12132146/77782390-70a8f800-7014-11ea-8f02-8eba0f6178f0.png)
**revise tweet:**  Phil please double check and adjust:

#MicroservicesEnthusiasts, Philip Riecks @rieckpil has put together a comprehensive free bundle that contains: e-Book, a 2hr video course & a cheat sheet to kickstart your #MicroProfile learning with focus on MP.3.2 release. https://bit.ly/2UJAb9V

#opensource #MicroProfileeBOOK

**Comment by aeiras** [comment]
@rstjames the card design is great, so is the content. :)

**Comment by rstjames** [comment]
Tweaked tweet 
#MicroservicesEnthusiasts, Philip Riecks @rieckpil has put together a comprehensive free Course Bundle containing: e-Book, 2hr video course & cheat sheet to kickstart your #MicroProfile success with focus on MP 3.2 release. https://bit.ly/2UJAb9V

#opensource #MicroProfileeBOOK

**Comment by aeiras** [comment]
so much fun you two. 

@rstjames does this media push runs for Q2 **only**?  using Cicek's ebook push reference, there is a need to revisit both ebook's media pushes for  continuity after their last tweet. 
Thanks for the follow up,
