### ISSUE TITLE
Blog Post, Announcing the Building an API Backend with MicroProfile Ebook

### ISSUE THREAD

**Issue by cicekhayri** [microprofile/microprofile-marketing#237]
Hi,

I have submitted a new blog post for announcing the **Building an API Backend with MicroProfile Ebook**
Here is the link [https://microprofile.io/wp-admin/post.php?post=6481&action=edit](https://microprofile.io/wp-admin/post.php?post=6481&action=edit)

Best regards,
Hayri

**Comment by aeiras** [comment]
Hola @cicekhayri :)

Blog is published, see small adjustments. 
Please tweet so MP can re-tweet you.

Hayri,  congratulations on closing the content of your very first MicroProfile e-Book. You are amazing. if you have the bandwidth, you could send the blog to the MPforum with your tweet as a close up. Design for e-book will take a bit of time for the PDF format and there is no reason for you to wait to push it formally. Yeah

**Comment by aeiras** [comment]
hey beautiful MicroProfiler Hayri, 

Would you consider participating in a Tech Talk to help us navigate through out your book? 
https://www.eclipse.org/lists/jakarta.ee-community/msg01493.html  Please check out the link I have added here, if yes, own it via the forum itself and follow up the MP session media coverage. 

No pressure, yet I recommend this step for many reasons. Abrazos,
