### ISSUE TITLE
Touraine Talk 2020 Talk

### ISSUE THREAD

**Issue by jefrajames** [microprofile/microprofile-marketing#240]
Name of the speaker; Jean-François JAMES
Name of the session; Java server-side: 20 years old and still innovative!
twitter or/& git account, if available; Twitter @jefrajames
Link of the event or short session abstract; 
- https://touraine.tech/talk/SYJIDy5JPhQuABdiT7Gv
- The objective of this talk to illustrate concretely how innovative the Java server-side ecosystem remains despite its 20 years,
- It is an opportunity to (re) discover the MicroProfile programming model and to run it on modern platforms.

Date/ time/location; 31 January 2020 10H10am, Tours (France)
Tweet message: https://twitter.com/jefrajames/status/1219209970329247746

**Comment by rstjames** [comment]
@jefrajames 
Tweet message:
During this talk @tourainetech @jefrajames is going to illustrate how the Java server-side ecosystem remains active despite its age and can thrive in the cloud with modern platforms such as @MicroProfileIO @OpenLibertyIO @openj9 @Payara_Fish @ApacheTomEE @kumuluz @QuarkusIO 

![MicroProfile-Session-Jean-FrancoisJames](https://user-images.githubusercontent.com/12132146/72736182-8c6bca00-3b9d-11ea-8632-5cab34bf5c12.png)


Scheduled to go out 21st and 28th
