### ISSUE TITLE
[YouTube adding MP mktg Hangouts] 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#241]
@cealsair and @rstjames, 

Now that Youtube infra and follow up scaling has been nicely completed, is it possible to start also adding the Marketing hangouts to the channel? 

Cesar currently on the call, you are the only one with access to import videos with the other few listed. The reason I asked for Ryan to be included is to help with such a tasks when you are not in attendance. Further, ideally- other in addition to Ryan from the call who attends most often might want to part-take on such task.

Will add this ticket to the next Hangout agenda for further simple discussion.

**Comment by rstjames** [comment]
Sounds good. More than happy to help with youtube tasks when needed.
