### ISSUE TITLE
[DevNexus 2020] MP Talk from Emily

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#243]
Name of the speaker: Emily Jiang
Name of the session: Reactive Microservice in Action 
twitter or/& git account, if available: emilyfhjiang 
link of the event or short session abstract: https://devnexus.com/presentations/5461/

Date/ time/location: Thursday, 20th Feb 2020/10:20/Unobtanium - 313
Tweet message: Join @emilyfhjiang @devnexus 2020 on Thursday, February 20th to learn about Reactive Microservices from zero to hero from an imperative perspective with a live demo 🚀@devnexus @MicroProfileIO  @IBMDeveloper @javachampion

**Comment by rstjames** [comment]
@Emily-Jiang you are good to go. Set to go out this week and the day before your session 
![MicroProfile-Devnexus-Emily-Jiang](https://user-images.githubusercontent.com/12132146/74321116-0e58a880-4d82-11ea-814c-5b47a54b8ecb.png)
