### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by abani-github** [microprofile/microprofile-marketing#249]
Abani Behera
abani.abani@gmail.com

**Comment by aeiras** [comment]
Hola Abani, welcome to contributing MP content! 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/10731224/76879725-e2728c00-6833-11ea-8e50-952581d8ed33.png">

**Comment by aeiras** [comment]
Hola @abani-github, 

Doing an inventory on MP Content draft blogs, I see your blog is still under draft, do you require further assistant with code review? or whatever? 

Let us know how we can help you publish your very first MP blog, always happy to help MicroProfilers!

**Comment by jclingan** [comment]
Closed due to no reply. Can be re-opened later.

**Comment by abani-github** [comment]
Hi Amelia,

Although I started drafting the blog post, I had to go on my paternity
leave. I will resume my blog once I am back (next week).
Thanks
Abani
