### ISSUE TITLE
Promote 2020 Jakarta EE Developer Survey on MP handles 

### ISSUE THREAD

**Issue by shabnammayel** [microprofile/microprofile-marketing#252]
The 2020 Jakarta EE Developer Survey will be open from Monday 6 April to 30 April. 

Please use this social kit to promote on MicroProfile handles: https://docs.google.com/document/d/19zggGv_ytr-B_7TaFCj0-_LW4VXGScqNp8PXk-8FHJA/edit

Here is the collector link for MP socials: https://www.surveymonkey.com/r/YC5955J

Thanks

**Comment by aeiras** [comment]
Is there a medium design that the JAKARTA project is using for the survey? Thanks @shabnammayel

**Comment by shabnammayel** [comment]
I am not sure what do you mean by medium design that The Jakarta EE using for the survey? we have created the social kit with social cards for community members to help and promote the survey on their socials. thanks

**Comment by aeiras** [comment]
Good Monday @shabnammayel, 

Today Tanja delivered the media kit,  https://docs.google.com/document/d/19zggGv_ytr-B_7TaFCj0-_LW4VXGScqNp8PXk-8FHJA/edit

I have provided feedback directly via the forum. The designs are not usable. Thanks for the follow up, yes- media kit is what I was asking. :)

**Comment by aeiras** [comment]
@rstjames assigning this ticket to you given **the time**. Please watch this ticket as it awaits the delivery (actual file added to this ticket) by @shabnammayel, with the fixed media design. 
Up to you to find the less busy day (not wknd) to schedule this tweet, 1 per week with last one on April 30th. :) 

**media description as follows:** 

_Are you a @java developer, architect, manager or c-level #ossDOER? Your input via ~8 minutes investment is needed today! 2020 #JakartaDeveloperSurvey https://bit.ly/3e1Hm62 welcomes YOU to provide feedback through 4/30/20 at 11:59pm PDT. #opensourceVOICES #communityFIRST_

**Comment by aeiras** [comment]
add a blue heart if there is a space before the @java! :) always HUGE +1!

**Comment by shabnammayel** [comment]
We have already updated the document with the new social cards in the document https://docs.google.com/document/d/19zggGv_ytr-B_7TaFCj0-_LW4VXGScqNp8PXk-8FHJA/edit
uploading them here too:
![2 (1)](https://user-images.githubusercontent.com/51449073/78938960-36624080-7a81-11ea-8efe-15a60d9dae38.png)
![6](https://user-images.githubusercontent.com/51449073/78939003-4e39c480-7a81-11ea-898d-882f43dedb8c.png)
![4](https://user-images.githubusercontent.com/51449073/78939014-53970f00-7a81-11ea-86f2-4db71bb03e48.png)

We've also created these variations
![JakartaEEDevSurvey2020v2](https://user-images.githubusercontent.com/51449073/78939055-69a4cf80-7a81-11ea-97ff-bb0fbc95d63b.png)
![JakartaEEDevSurvey2020 (v2)](https://user-images.githubusercontent.com/51449073/78939105-850fda80-7a81-11ea-887d-c1fe3502aebe.png)

Thanks

**Comment by aeiras** [comment]
excellent @shabnammayel, thanks for the follow up. :)

@rstjames, using the above description please lets use the version below for a single media push to be scheduled until April 30th. 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/10731224/78943693-335f5400-7a71-11ea-89ad-0c5bc08a107a.png">

**Comment by aeiras** [comment]
> @rstjames assigning this ticket to you given **the time**. Please watch this ticket as it awaits the delivery (actual file added to this ticket) by @shabnammayel, with the fixed media design.
> Up to you to find the less busy day (not wknd) to schedule this tweet, 1 per week with last one on April 30th. :)
> 
> **media description as follows:**
> 
> _Are you a @java developer, architect, manager or c-level #ossDOER? Your input via ~8 minutes investment is needed today! 2020 #JakartaDeveloperSurvey https://bit.ly/3e1Hm62 welcomes YOU to provide feedback through 4/30/20 at 11:59pm PDT. #opensourceVOICES #communityFIRST_

@rstjames

**Comment by rstjames** [comment]
**adjusted tweet. (just simplified)** 
Are you a @java developer, architect, manager or c-level #ossDOER? Make your voice heard and take the 2020 #JakartaDeveloperSurvey: https://bit.ly/3e1Hm62 YOU can provide feedback till 4/30/20  

#opensourceVOICES #oss #opensource #communityFIRST

**Comment by aeiras** [comment]
@rstjames it reads ok, +1 to simplification! :)
