### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by marcoantoniobferreira** [microprofile/microprofile-marketing#253]
Marco Ferreira
marcoantoniobferreira@gmail.com

**Comment by aeiras** [comment]
Hola Marco, 

Welcome to MP content sharing! :)

<img width="999" alt="image" src="https://user-images.githubusercontent.com/10731224/78597180-e4f84e00-7801-11ea-9af5-f476aa433760.png">

**Comment by marcoantoniobferreira** [comment]
Thanks Amelia!
