### ISSUE TITLE
[MP Starter media push] 2020 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#254]
@cealsair i hope i am assuming correctly and you are behind this valuable reminder of Starter. if not, lets use this ticket to see what's what. 

Using 4/6 MP media push (below):

- reminder set for the rest 2020 via MP twitter? 

- what about using a design for media push? 

- current description reads great. :) Thanks for the follow up! 

Adding @rstjames in case there is the need of a design 

https://twitter.com/microprofileio/status/1247144734029680641?s=21

**Comment by rstjames** [comment]
@aeiras @cealsair 

Are you a developer looking to get started quickly with MicroProfile? Check out the MicroProfile Starter to easily create your first #MicroProfile app! https://start.microprofile.io

#java #microservices #config #faulttolerance #health #metrics #security #openapi #restclient #opentracing #opensource #oss

![MicroProfile-MPstarter-push](https://user-images.githubusercontent.com/12132146/78909089-4844e300-7a83-11ea-8bb0-6409cda38da3.png)

**Comment by rstjames** [comment]
@cealsair take a look at this ticket please.

**Comment by rstjames** [comment]
Scheduled twice a month for the year.
