### ISSUE TITLE
MP Talk by Marco

### ISSUE THREAD

**Issue by marcoantoniobferreira** [microprofile/microprofile-marketing#255]
Name of the speaker; Marco Ferreira
Name of the session; Eclipse MicroProfile, um caminho para construção de microsserviços com Java(Eclipse MicroProfile, a way to build microsservices with Java)

twitter or/& git account, if available; @marcoferreira44
link of the event or short session abstract;

RSVP here: https://www.meetup.com/pt-BR/SouJava/events/269798316/

Date/ time/location; 7th April
Speaker must provide "Tweet message"

Join @marcoferreira44
#MicroProfileTalk on April 7, to hear what she says about “Eclipse MicroProfile, um caminho para construção de microsserviços com Java(Eclipse MicroProfile, a way to build microsservices with Java)” Talk in portuguese, on @SouJava channel! RSVP here: https://www.meetup.com/pt-BR/SouJava/events/269798316/

**Comment by rstjames** [comment]
updated the tweet:
#MicroProfileTalk on April 7, Join  @marcoferreira44 on “Eclipse MicroProfile, um caminho para construção de microsserviços com Java (Eclipse #MicroProfile, a way to build microsservices with Java)” The talk is in portuguese, on @soujava channel! RSVP: https://bit.ly/2JKfl56

![MicroProfile-SouJava-Marco](https://user-images.githubusercontent.com/12132146/78705894-781eaa00-790e-11ea-9889-e2bac6aa6b91.png)

**Comment by aeiras** [comment]
you are amazing @rstjames !

@marcoantoniobferreira please remember on next MP talk submission to use the suggested 2 weeks in advance to allow MP media push to not be rushed. :) This time, you provided everything without need for  a follow up which is most helpful. Thank you for being a wonderful #ossDOER, your contributions and time spent matter!

**Comment by marcoantoniobferreira** [comment]
Yes @aeiras! I'm sorry, i forgot to do this before. @rstjames thank you so much and sorry too =(

**Comment by rstjames** [comment]
@marcoantoniobferreira no problem. Glad we were able to get it out for you. Hope your session went well!
