### ISSUE TITLE
[MP Working Group Media push] Adjustments: Working Group Standalone Proposal

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#256]
Currently [THIS tweet is outdated based on 4/7 Community hangout with extra steps](https://twitter.com/microprofileio/status/1242921196615864320?s=21)and needs changing before next tweet is out. 

Design description needs **adjusting to**

Join the MicroProfile Working Group Discussion
The Standalone Proposal welcomes your feedback until June 1st, 2020.

**media description**:

_The @MicroProfileIO Community needs to define a #WorkingGroup that satisfies the @EclipseFdn IP Grant, Flow requirements AND the EF Specification Process. Resolution: The Standalone Proposal v0.1 welcomes your participation HERE[XXX] Thread forum HERE[xxx]
#OSS _

2 **links** to add to description: 
- Forum [Thread](https://groups.google.com/forum/#!topic/microprofile/G5WZvF0wZuY)

- Document Public view welcomes Community comments [HERE](https://docs.google.com/document/d/1cCMN298rUAX45Nq-ZJv755WZe8yVjyAo1Gz_wN8r7wc/edit)

**Comment by rstjames** [comment]
OLD message: (notes for me)
The @MicroProfileIO Community needs to define a #WorkingGroup that satisfies the @EclipseFdn IP Grant, Flow requirements AND the EF Specification Process. The outline proposals welcome your PRs & comments HERE http://bit.ly/2rxiZdf Thread forum HERE http://bit.ly/38D4Iwg
#Oss

**Comment by rstjames** [comment]
@aeiras 
1. I deleted all working group tweets reminders
2. I edited the tweet to fit the correct character Limits. Please review it and let me know if there is any changes.
3. After the image and tweet is approved I will reschedule. 

**New Tweet:**
The @MicroProfileIO Community needs to define a #WorkingGroup that satisfies the @EclipseFdn IP Grant, Flow requirements & the EF Specification Process. The Standalone Proposal v0.1 welcomes your participation: https://bit.ly/39QsC6U Thread forum: https://bit.ly/34ppsWr
#OSS 

![MicroProfile-WorkingGroup-June1](https://user-images.githubusercontent.com/12132146/78779115-aea30600-799c-11ea-9588-988c697ca66a.png)

**Comment by aeiras** [comment]
Approved! 
It looks great @rstjames, thanks for the prompt adjustment. lets run it until June 1st. :)
