### ISSUE TITLE
[MP.io banner] add a reminder of the MP<>MP interview initiative 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#258]
https://github.com/eclipse/microprofile-marketing/wiki/SHARING:-Onboarding-into-MicroProfile-Interview

**Comment by rstjames** [comment]
Not sure what you want for this. FYI We do not have much more room to on the MP site to put more reminders.

**Comment by aeiras** [comment]
@rstjames, 

The reminder of the activity that welcomes anyone to share its onboarding into MP is going out twice a month for the rest of 2020. :)  thanks for that!   

I was wondering if we could add something about Onboarding interviews call to action in the Contributors tab.  It seems like the best way to get to know the MicroProfilers.   Can you think of ways to add wiki button link on that space?

**Comment by rstjames** [comment]
@aeiras are we sure we want to do another"reminder" our SM is full of these every week. I will make if we think this should be pushed. 
I will need a tweet/ messaging.

**Comment by aeiras** [comment]
Thanks for allowing me to clarify Ryan. @rstjames 

No, not via media but actually my brainstorming is on the website under the Contributors space tab.    However, if it is not a requirement but something nice that that space is missing. 
Each pic of a MicroProfiler brings the viewer to GH account for that individual. 
GH history is great but the MP<>MP interviews are beyond awesome and much more candid. 

Ideally, if you could find a way to add the Call to action there, we could actually start within the doc adding new interviews b/c it just takes a PR to add that blog link. :) get it?

**Comment by rstjames** [comment]
@aeiras I added into the Contributors menu (dropdown) please take a look and let me know if this is what you were thinking?

**Comment by aeiras** [comment]
@rstjames, 

I don't see it. I am looking and referring to this page on the website:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/10731224/82930093-a9dce600-9f39-11ea-9990-73de81aca917.png">
It should be a nice banner like we have on the main page for Duke Award, clickable.

**Comment by rstjames** [comment]
@aeiras not sure why you can not see it. Maybe clear your cache. 
<img width="1234" alt="Screen Shot 2020-05-27 at 8 09 56 AM" src="https://user-images.githubusercontent.com/12132146/82984092-b91f6a80-9ff1-11ea-89c6-78d65224b45d.png">

**Comment by aeiras** [comment]
@rstjames 

The banner is hidden and only when i place my mouse on search for it, it shows but it is not clickable or effective. see here, i managed to save it after much fight with the hidden banner. 



<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10731224/83056702-b4b37b80-a00a-11ea-909a-c9d6432d6dd9.png">

**Comment by rstjames** [comment]
@aeiras 
updated : 
<img width="1248" alt="Screen Shot 2020-05-27 at 8 19 09 PM" src="https://user-images.githubusercontent.com/12132146/83057577-65e00300-a057-11ea-9d4f-fd00fbd37e0a.png">

**Comment by aeiras** [comment]
@rstjames,

Now it looks perfect as those who participate on future interviews can submit PRs to update the wiki and lists his/her interview blog into the guidelines. :) Thank you for the prompt fix!
