### ISSUE TITLE
[MicroProfilers On-Boarding interview] media reminder 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#260]
given the wiki steps are ready for comsupltion, we can now move this fun activity to a regular Call 2 Action for Microprofile. 

Thinking - brainstorming crudely that pushing activity reminder via twitter twice per month for the rest of 2020 is ideal. 

**Minimal Requirements:**

- use the interview media design + extra awesomeness

- guidelines: https://github.com/eclipse/microprofile-marketing/wiki/SHARING:-Onboarding-into-MicroProfile-Interview

- goal: enhance more sharing stories of MP Contributors via blog sharing

Media **description** using blog template INTRO or similar
The #MicroProfile Community cares about its members and does its best to keep the hurdles of getting involved as low as possible. #MicroProfilersInterview series provide a valuable input in optimizing the welcoming process with hopes to inspires YOU, a user/contributor to join. LINK of guidelines (shorter version, draft 0.1.)

**Comment by rstjames** [comment]
@aeiras visual ok?

![MicroProfile-Interview-reminder](https://user-images.githubusercontent.com/12132146/81087508-1ac04d80-8efa-11ea-9975-3d55e176ae51.png)

Shortened to fit. 
The #MicroProfile Community cares about its members & does its best to keep the process simple to get involved. #MicroProfilersInterview series provide valuable input in optimizing the welcoming process with hopes to inspires YOU, a user/contributor to join. LINK of guidelines

**Comment by aeiras** [comment]
Let’s fix “shares” to share. 
Let’s schedule it to 1 to max per month, it looks great! 💛💪🏼

**Comment by rstjames** [comment]
Scheduled to go out once a month for 2020
Tweet:
The #MicroProfile Community cares about its members & does its best to keep the process simple to get started. #MicroProfilersInterview series provide valuable input in optimizing the welcoming process with hopes to inspires YOU, a user/contributor to join https://bit.ly/35DzgNq

![MicroProfile-Interview-reminder](https://user-images.githubusercontent.com/12132146/81181116-40a62a80-8fac-11ea-9823-e8b1c83e9de2.png)
