### ISSUE TITLE
Jakarta Tech Talk

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#263]
Conference Name:
Jakarta Tech Talk

Date: April 29th. 11 AM ET.

Conference website:
https://t.co/QPKblv3Rel?amp=1

Talk name:
Keeping Brazil’s Medical Industry Safe with MicroProfile and JakartaEE

Speaker Names:
Cesar Hernandez Mendoza, Senior Software Engineer, Tomitribe (@CesarHgt)
Rafael Guimaraes, Analyst, GBR Systems (@GuimaraesSv)

Tweet Message:
Come and learn how modern cloud-native Java played a critical role and enabled cloud migration in the Brazilian medical industry. April 29th. @MicroProfileIO @JakartaEE
@Java_Champions @Groundbreakers 

logos: groundbrakers, Java Champions & MP & JakartaEE

**Comment by rstjames** [comment]
@cesarhernandezgt sorry got to these late.

**Comment by rstjames** [comment]
Join @CesarHgt & @GuimaraesSv to learn how modern cloud-native Java played a critical role and enabled cloud migration in the Brazilian medical industry. April 29th, 11 AM ET. https://t.co/QPKblv3Rel?amp=1

@MicroProfileIO @jakartaee
@Java_Champions @groundbreakers
