### ISSUE TITLE
Create Membership Prospectus

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#264]
Relates to eclipse/microprofile#176. Extol the virtues of MicroProfile to prospective member. Examples: [GEMOC](http://gemoc.org/members.html), [IoT](https://iot.eclipse.org/membership/), [Jakarta EE](https://jakarta.ee/documents/membership/jakarta-ee-membership-prospectus.pdf), [Edge Native](https://edgenative.eclipse.org/about/faq/). There seems to be quite a bit of variance on how to convey membership value.

**Comment by aeiras** [comment]
As stated on the last MP Community hangout last week April 28th, I will be attending May MP Marketing hangouts on Monday 10am PDT to attend with the group the WG 3 tasks that need to be worked in parallel with the WG Charter. :)

**Comment by jclingan** [comment]
Initial [draft prospectus](https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit?ts=5eb046ec#slide=id.g6edf059ff0_56_0).

**Comment by aeiras** [comment]
@jclingan I just got done reviewing the latest version of the Prospectus John! 

Thanks for pointing out its current informal use. 

There is no "suggestive move" in the document so I

- use "purple" to add stuff

- comments with "delete" to cut stuff or help with re-write

- attention to page 7.  In no form will MP put forward a budget that will grant the EF Team access to brand the activities for MP. deleted. Currently there are only 3 benefit listed on this page with latest changes. 

Cheers,

**Comment by aeiras** [comment]
@rstjames, 

can you please prioritize (this week) the branding of the Prospectus yet leave it under google doc. 
Submit any issues if you find problems with this request on this ticket. 

This WG ticket is a MP priority. Thank you!

**Comment by rstjames** [comment]
@aeiras I am not sure what you are asking for. "the branding of the Prospectus yet leave it under google doc" ? 

I looked over the slide deck. It seems to be still in progress. 
- What is the goal of the final version? (print pdf, presentation?)

**Comment by aeiras** [comment]
Hey @rstjames, welcome back! :)

Can you see if you can improve the visual of the document as it is?

I learned on Monday, that John & a few other MicroProfilers have been using the Prospectus to invite potential Partners to join the MPWG.  That means that the document is active now, as it is. 

A few of us, Debbie, John, David & I, revised the document after the Mktg call on Monday. I noticed some visual discrepancies on the design. 

- Right upper logo for type to the right on each page

- front page is off- maybe a new pic would also help

-etc

If we are able to use the White Paper detail in a smaller scale on this document, it will improve it. 

Thanks for the follow up

**Comment by rstjames** [comment]
@aeiras to be honest. It is in google slides and not in Indesign or powerpoint so styling is limited. 
I tried to clean up the text (font, colors, size) but there is a lot of content squeezed onto one slide that doesn't allow consistency. Not a problem if everyone is ok with this but I wont be able to do much. Also tried to tweak the top title section and bottom bar but can not figure out how to edit it... 

One suggestions is to get Ian Robinson, IBM to shorten his quote a little bit so the length lines up with the other quotes. 

I see there is editing continuing as I work on the slide. I think its best if everyone wants to clean it up I do it at the end of editing and then we can discuss things in detail. 

Please let me know what everyones thoughts are on this.

**Comment by aeiras** [comment]
@rstjames, 

Thank you for the fantastic follow up providing the status of the document. 
Please add ticket to the next Mktg hangout call. 
Let’s discuss it there. Thanks 🙏 Ryan!

**Comment by aeiras** [comment]
@jclingan, 

good progress, I have given it another review and added comments for most of the feedback with a few additions. 
The bad thing about google slides is that it doesn't allow for "suggestive mode" which is bothersome. Still, thank you for leading the document.

**Comment by rstjames** [comment]
@aeiras what should this change to ? Copyright © 2020, Eclipse Foundation, Inc. | Made Available under the Eclipse Distribution License 1.0 (EDL-1.0) | v2020-5

**Comment by aeiras** [comment]
Ryan, 

The update is completed on the 1st and last page. 

John, I add version 12/2020 as an update that the document will undertake after today's discussion. 
Can you please add the 2 links of the websites on each of the footers? I was not able to adjust that section on the current document, and it seems protected. 

Let's do this,

**Comment by aeiras** [comment]
@rstjames, 

Do you need anything else from us about Quotes page before you tackle improvements on this document? 
If not, please help close this ticket. Thanks

**Comment by aeiras** [comment]
John, 

You and I have completed the Prospectus. 
I will close this issue and create a new one that allows @rstjames to create a formal document. :)
