### ISSUE TITLE
Create membership flyer

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#265]
Relates to eclipse/microprofile#177. 1-pager for industry events. Example: [Jakarta EE](https://jakarta.ee/documents/membership/jakarta-ee-membership-flyer.pdf)

**Comment by aeiras** [comment]
As stated on the last MP Community hangout last week April 28th, I will be attending May MP Marketing hangouts on Monday 10am PDT to attend with the group the WG 3 tasks that need to be worked in parallel with the WG Charter. :)

**Comment by aeiras** [comment]
@jclingan, 

Do you need the flyer? I though the MP Prospectus that will get Ryan's improvement suffices. 
If not, can you close this ticket?  

Traditional clean up of repo, end of the year! Thanks

**Comment by jclingan** [comment]
Thx for the house cleaning, Amelia :-) Closing!
