### ISSUE TITLE
[Youtube Media push] scheduled for 2020

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#267]
using this[ link ](https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w?view_as=subscriber)
Lets push via MP media channels the call to action to check out the video recordings from past & present MP hangouts. 

**Recommended Scheduled:**  twice per month

Msg should be something with core goals: Onboarding new contributors who are currently looking for a healthy OSS project: 

1. wondering about MP & its friendly welcoming community
2. listen to the video/voice conversations 100 % discussed via MP youtube channel since its creation
3. 100% of MP decisions are made in its bi-monthly hangouts, all found HERE.

**Comment by rstjames** [comment]
@aeiras ( wanted to included a woman on this one but is it too much with the nails? )

Did you miss the @MicroProfileIO Live bi-monthly hangouts, where 100% of MP decisions are made? Don't worry you can catch up on all hangouts here on the #MicroProfile Youtube Channel > https://bit.ly/2zbWXQy
#opensourece #oss #MPcollaboration 

![MicroProfile-Youtube-channel](https://user-images.githubusercontent.com/12132146/81078383-74227f80-8eee-11ea-975f-c79c21f2bd78.png)

**Comment by rstjames** [comment]
with youtube logo
![MicroProfile-Youtube-channel](https://user-images.githubusercontent.com/12132146/81078326-61a84600-8eee-11ea-999b-804f07d4cc63.png)

**Comment by rstjames** [comment]
can do two...
![MicroProfile-youtube-channel-2](https://user-images.githubusercontent.com/12132146/81083611-16ddfc80-8ef5-11ea-9ea0-69ee4981371b.png)

**Comment by aeiras** [comment]
Love it Ryan! 

Can the two designs be scheduled once per month? 💛
Ideally we run them when no other stuff is going out. Wknds work 🔓🔍

**Comment by rstjames** [comment]
@aeiras all set for 2020
