### ISSUE TITLE
[MPWG-design task] MicroProfile Compatible Logo

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#268]
Use the Mktg drive under designs to create all drafts. :) 

[gDrive](https://drive.google.com/drive/u/0/folders/1kawjoICH8vuNILCSlPGb_6Sd9oSMTQke)

**Comment by rstjames** [comment]
@aeiras @jclingan @dblevins  

I started to work on the member and compatible badges for MP. After our marketing call yesterday the majority of people want to see a badge that is simple. So based off this I came up with first version. ( I put both here so you can see them next to each other) 

![Compatible](https://user-images.githubusercontent.com/12132146/81732060-2d093100-9490-11ea-968c-b0f33422bc5c.png)

**Comment by aeiras** [comment]
@rstjames

Such a quick turnaround, I like the **simplicity** and colors true to MP in both designs :) wow!

**Comment by aeiras** [comment]
https://github.com/microprofile/microprofile-wg/issues/38

@rstjames can you drop the draft logo in the drive please? Thank you. 
This task has been moved to the MPWG repo

**Comment by kwsutter** [comment]
Simple.  I like it.  Personally, I would remove the "M" shadow.  Just have the standard "M" logo with the circle text.  Thanks!

**Comment by aeiras** [comment]
@kwsutter, can you please copy/paste your feedback on the new ticket? [Trademark] Compatible Logo microprofile/microprofile-wg#38 https://github.com/microprofile/microprofile-wg/issues/38

Gracias!
