### ISSUE TITLE
[MPWG- design task] MicroProfile Member Banner

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#269]
use the mktg drive design for drafts

[gDrive](https://drive.google.com/drive/u/0/folders/1bWw-Ytwht4xCzmr618FOAYYwKkjGHEvZ)

**Comment by rstjames** [comment]
@aeiras @jclingan @dblevins 

I started to work on the member and compatible badges for MP. After our marketing call yesterday the majority of people want to see a badge that is simple. So based off this I came up with first version. ( I put both here so you can see them next to each other) 


![Member](https://user-images.githubusercontent.com/12132146/81731989-12cf5300-9490-11ea-8c2b-c51771565cbf.png)

**Comment by aeiras** [comment]
@rstjames looks awesome. 
Given that there are 2 tickets, can you delete the screen shot that is not associated with the task on this ticket and the other?

**Comment by aeiras** [comment]
@rstjames please drop the draft design in the folder. 

The ticket has been move to the MPWG repo. https://github.com/microprofile/microprofile-wg/issues/39
