### ISSUE TITLE
[MPWG Corporate Quotes for Prospectus doc]  IBM

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#271]
[Prospectus](https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit?ts=5eb046ec#slide=id.g77280c392b_2_0) **page 4**

**Comment by jclingan** [comment]
Done.  Thx.
