### ISSUE TITLE
[Blog] - MP 4.0 and Working Group

### ISSUE THREAD

**Issue by radcortez** [microprofile/microprofile-marketing#273]
Here is a link for the blog about MP 4.0 delay and the Working Group work:

https://docs.google.com/document/d/1Kpk2mGT_m39goJNJLNV7N0lD2kyO6_DJebyI-tizjuI/edit

**Comment by radcortez** [comment]
@jclingan @aeiras

**Comment by aeiras** [comment]
> @jclingan @aeiras

Thanks @radcortez! 
Please make sure you gain access to contribute on the MP blog by following the guidelines [HERE](https://github.com/microprofile/wpsite)
**Need**

1. the blog must be original content hosted under MP and not crosspost content :) Thanks Roberto!

**Comment by aeiras** [comment]
@rstjames- allow you to pull you in on this task and thanks in advance. 

We need the design used for the MP releases to be adjusted to add DELAY on the message card. 
Ideally that card is used on the blog's header housed under the WP site and also in the MP twitter message. Can you get the design ready by Tuesday next week? 

Thinking that the blog ought to be pushed on Tuesdays AM (each week)  until July 31st. 
The description for that tweet to come later after Blog copy/edit is completed. :)

**Comment by aeiras** [comment]
@radcortez, 
Really good draft, i used "suggestive mode" and added via comments your email to pull you back in. 

Like that it is 1 page. After you go in, i believe we can make it shorter. :) thanks for rocking it. 
Best thing on the blog is the soft tone.

**Comment by aeiras** [comment]
@radcortez, 

Latest draft looks even better :) After you see latest adjustments it is a go to publishing next Tuesday. 

Next step is for you to become a content contributor on MP wordpress, for that please provide your preferred email. Remember to add a short bio to your blog profile along side a picture. 
Let's use this ticket for that on-baording. 

Thanks for rocking draft!

**Comment by aeiras** [comment]
> @rstjames- allow you to pull you in on this task and thanks in advance.
> 
> We need the design used for the MP releases to be adjusted to add DELAY on the message card.
> Ideally that card is used on the blog's header housed under the WP site and also in the MP twitter message. Can you get the design ready by Tuesday next week?
> 
> Thinking that the blog ought to be pushed on Tuesdays AM (each week) until July 31st.
> The description for that tweet to come later after Blog copy/edit is completed. :)

Ryan, 

If Tuesdays is already to crowded to add the blog update, let us know what other day could be better. Thanks

**Comment by rstjames** [comment]
@aeiras making sure I  understand what you want for this ticket. This is for a blog post. Needed: top image and new blog post on SM? 

If so I need a tweet message. Maybe best to fill in "blog" template ticket. 

Monday is a holiday Tuesday seems busy, so I can send this out on Wednesday.

**Comment by rstjames** [comment]
@radcortez hey bud can you please write a tweet message for this blog post?

**Comment by aeiras** [comment]
> @radcortez hey bud can you please write a tweet message for this blog post?

@rstjames, 
*Media description*
#MicroProfileRelease 4.0 will be delayed from Q2 (June 2020) to Q3 (tentatively August 2020) due to #MPWG requirement. #MicroProfilers (_insert yellow heart if there is space_)working on the APIs should keep July 31st as the last day to submit contributions that could be a part of the MP 4.0 release. [blog link here]

Can you show us the media design?

**Comment by rstjames** [comment]
@aeiras 
Thoughts? 

![MicroProfile-4 0Delay](https://user-images.githubusercontent.com/12132146/82807777-bce3ad80-9e88-11ea-946b-426c924843bf.png)

**Comment by radcortez** [comment]
Please use my email radcortez at yahoo.

Will you send me an invite to join the site?

**Comment by rstjames** [comment]
@radcortez not sure what you mean...

**Comment by radcortez** [comment]
> 
> Next step is for you to become a content contributor on MP wordpress, for that please provide your preferred email. Remember to add a short bio to your blog profile along side a picture.
> Let's use this ticket for that on-baording.
> 

About this from @aeiras

**Comment by rstjames** [comment]
@radcortez added you as a contributor. You should get an email with all info.

**Comment by aeiras** [comment]
> @aeiras
> Thoughts?
> 
> ![MicroProfile-4 0Delay](https://user-images.githubusercontent.com/12132146/82807777-bce3ad80-9e88-11ea-946b-426c924843bf.png)

Design is great @rstjames, lets **adjust the wording** as follows and thank you! :)

1.  Changes: the yellow wording on the left of the card from MicroProfile 4.0 Release will be delayed to MicroProfile 4.0 Release Announcement
2.  add 1 word:  ... due to * the*Microprofile Working Group requirement.

**Comment by rstjames** [comment]
@aeiras adjusted the tweet. Reads a bit easier. Let me know if you are ok with it.

#MicroProfileRelease 4.0 will be delayed from Q2 (June 2020) to Q3 (tentatively August 2020) due to #MPWG requirement. #MicroProfilers 💛July 31st is the last day to submit contributions that could be a part of the MP 4.0 release. [blog link here]

![MicroProfile-4 0-Announcement](https://user-images.githubusercontent.com/12132146/82984374-5aa6bc00-9ff2-11ea-970a-ff71e229130b.png)

**Comment by aeiras** [comment]
Looks perfect Ryan! 💛

**Comment by rstjames** [comment]
@aeiras @radcortez I am not seeing the blog post in MP blog drafts. When this is ready to go I will set up the top image, publish it and send it out on SM .

**Comment by radcortez** [comment]
Not there yet. Waiting for the final approval.

**Comment by aeiras** [comment]
@radcortez, 

@jclingan is on vacation, though he is such a formidable MicroProfiler and always generous with his time, lets not add him as a bottle neck on the blog. 

The blog is a go- I approve it as its editor! 

The blog ought to start circulating *latest*  by this Friday,  to provide a full 2 months warning, with the weekly media push reminders, to MicroProfilers working on #MPcodereleases. 

Abrazos, and thanks for the follow-up via ticket! :)

**Comment by radcortez** [comment]
I've added it to WP and is now waiting review there.

**Comment by aeiras** [comment]
@radcortez, 

Thank YOU for owning this blog task beautifully MicroProfiler! 👍
I re-added missing links on final Wordpress review & added the blog header.
The blog is published today helping us close the MP May ecosystem most important update before the expected June regular release cadence. 

@rstjames, 
 
Thank you for helping us close this ticket with media scheduling 1 per week running tentability until July 31st.  
I noticed while adding the header media design to wp that for the blog design, we ought to remove all the wording below the MicroProfile TM left side of the card. The book on the right suffices. We want the blog title to be a stand alone in that card for the blog header. Can you update the card and update the header pic while pushing media data? 

Last note, should I release be not possible on August, we will adjust the blog to keep it running with new dates, fluid. FYI Robert :) that's easy! 

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/10731224/83297021-a39f7180-a1a6-11ea-8322-7926c9323d16.png">

**Comment by rstjames** [comment]
Updated the top image of the blog post to this .  Easier to read the title. 

![MP-4 0Delay](https://user-images.githubusercontent.com/12132146/83392921-35e98480-a3f6-11ea-9887-d460de29cf84.jpg)

**Comment by rstjames** [comment]
Scheduled on Twitter till Aug.
