### ISSUE TITLE
MP Talk @ JUG Nicaragua

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#274]
**Conference Name:** 
JUG Nicaragua Meetup (online)

**Conference website and social media links:**
https://www.facebook.com/events/239488467150701/
@jugnicaragua

**Talk name:**
Fallando con estilo: MicroProfile Fault Tolerances & Metrics.

**Talk Link:**
https://us02web.zoom.us/webinar/register/5315896572212/WN_7CvHFfhyTSCHcfUatXrFew

**Speaker Names:**
Jorge Cajas, Developer, MangoChango (@cajasmota)

**Tweet Message:**
@cajasmota nos compartirá como monitorear nuestra aplicación y reaccionar correctamente a errores con las API de MicroProfile Fault Tolerance & Metrics para no afectar la experiencia del usuario final.

Miércoles 20 de mayo, 7PM GMT-6
Registrate en: https://bit.ly/2zIIuvS

**Comment by rstjames** [comment]
@cajasmota Can you please adjust your tweet. You can not start a tweet with @ and my spanish is not good enough to fix this. 

![MicroProfile-JUG Nicaragua Meetup](https://user-images.githubusercontent.com/12132146/82193273-783e9c00-98f5-11ea-8433-41b3736d13ea.png)

**Comment by aeiras** [comment]
> @cajasmota Can you please adjust your tweet. You can not start a tweet with @ and my spanish is not good enough to fix this.
> 
> ![MicroProfile-JUG Nicaragua Meetup](https://user-images.githubusercontent.com/12132146/82193273-783e9c00-98f5-11ea-8433-41b3736d13ea.png)

@rstjames- given the timing and that I am Latina born, allow me to help @cajasmota :) 

**Tweet:** 
Join @jugnicaragua session de #LatinArmada @cajasmota acerca de cómo monitorear aplicaciones y reaccionar correctamente a errores con las API de #MicroProfileFaultTolerance & Metrics. @EventosJEspanol #ossDOER 

Miércoles 20 de Mayo, 7PM GMT-6
Registrate: https://bit.ly/2zIIuvS

**Comment by rstjames** [comment]
@cajasmota all good to go. It will go out today and day of the season.

**Comment by cajasmota** [comment]
Thank you very much everyone, I will take in consideration for future tweets that the text can't start with an @

**Comment by rstjames** [comment]
@cajasmota Thanks for creating a ticket for your session. Happy to help! Best of luck with your session.
