### ISSUE TITLE
[Blog] Keeping Brazil’s Medical Industry Safe with MicroProfile & JakartaEE – Jakarta Tech Talks

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#275]
I created the draft for a cross post for a blog entry about: Keeping Brazil’s Medical Industry Safe with MicroProfile & JakartaEE – Jakarta Tech Talks

https://microprofile.io/wp-admin/post.php?post=6544&action=edit

Please proceed with the review and publication process.

**Comment by aeiras** [comment]
Cesar, 

Your blog is now live! :)
