### ISSUE TITLE
[Website NOT responding] lets check it out

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#276]
@rstjames, 

Today the MP website is not responding. This has been happening throughout the day. 

can you help us check what's going on? 

Not only if the wordpress access not working but regular visit to website are off. thanks

**Comment by rstjames** [comment]
@aeiras the entire website? 
And what do you mean  "regular visit to website are off"?

I checked out the site and everything is working. The project page has some issues but I have brought this up many times and seems nobody want/ or can fix it. Is anyone maintaining this part of the website? 

If the website is down during the day it could be cloudflar or just the hosting. But from the WP side all looks ok.

**Comment by aeiras** [comment]
@rstjames, 

Today the website and wordpress is responsible, so you are likely right and it is the  hosting vendor having bugs. Thanks for the follow up. 

About Project page, that needs the community attention but will have to wait until WG is set. :) 

closing ticket, thanks for prompt turnaround,
