### ISSUE TITLE
Create release marketing bullet item on MicroProfile release page

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#277]
Add bullet (and link) to MicroProfile release page to create marketing github issue on impending release. Two week lead time.

**Comment by aeiras** [comment]
linked to https://github.com/eclipse/microprofile-marketing/issues/251 lets add this page to the technical side update :)

**Comment by jclingan** [comment]
Done. https://wiki.eclipse.org/MicroProfile/SpecRelease/Release#Pre-Release_Review_Steps

**Comment by aeiras** [comment]
wonderful @jclingan! :)
