### ISSUE TITLE
[MP TALK] - Barranquilla JUG Cesar Hernandez

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#278]
Conference Name:
Barranquilla JUG Colombia monthly session

Conference website and social media links:
https://www.facebook.com/barranquillajug/
http://jugbaq.org/

Talk name:
Diseño de MicroServicios con MicroProfile y TomEE

Talk Link:
https://www.youtube.com/watch?v=-cva97fD8w4

Speaker Names:
Cesar Hernandez Mendoza, Senior Software Enginner, Tomitribe (@CesarHgt)

Tweet Message:
Barranquilla JUG invites you to learn how to develop microservices with @Java, @MicroProfileIO, and @ApacheTomEE  in Spanish. Friday, Jun 12, 15:00 GTM-5 @Java_Champions @groundbreakers https://www.youtube.com/watch?v=-cva97fD8w4

logos: groundbrakers, Java Champions & MP

**Comment by aeiras** [comment]
@cesarhernandezgt 

Ideally under logo design the JUG logo is included. 
Recommendation under the description tweet, it is easier for those who are admin for Community twitter accounts to notice media the mentions their community when the @(JUG) is added instead the full name or #. 
 cheers

**Comment by cesarhernandezgt** [comment]
@aeiras , Thank you for the review.


![14656314_115845162217003_8174827930381965717_n](https://user-images.githubusercontent.com/1454523/84098660-11c50f00-a9c5-11ea-958c-924bb42cde20.jpg)
![14570351_115845045550348_3085655611413761379_n](https://user-images.githubusercontent.com/1454523/84098661-12f63c00-a9c5-11ea-89b7-323ff49af217.jpg)

Twitter account is not available.

**Comment by rstjames** [comment]
@cesarhernandezgt  I will send it out today and day before.  
![MicroProfile-Cesar Hernandez-BarranquillaJUG](https://user-images.githubusercontent.com/12132146/84158785-8d2dcb80-aa6c-11ea-93ee-c91f37eb14ab.png)
