### ISSUE TITLE
[MP TALK] - j4k.io - Edwin Derks

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#279]
Conference Name:
j4k.io

Conference website and social media links:
https://www.j4k.io/
https://twitter.com/j4kio

Talk name:
Optimize your applications to the max with Jakarta EE and MicroProfile

Talk Link:
None or TBD

Speaker Names:
Edwin Derks (@edwinderks)

Tweet Message:
Learn how to optimize your @JakartaEE and @MicroProfileIO applications to the max (and why you should) from my talk at @j4kio

**Comment by rstjames** [comment]
Set to go out the week before and the day before. 

Adjusted tweet:
Don't miss @edwinderks talk at @j4kio Sept 2-3. He will cover how to optimize your @JakartaEE & @MicroProfileIO applications to the max (and why you should) https://www.j4k.io/ 

![MicroProfile-j4k-EdwinDerks](https://user-images.githubusercontent.com/12132146/85267509-a6c01180-b475-11ea-9269-fca429a8678a.png)
