### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by thomassuedbroecker** [microprofile/microprofile-marketing#280]
Following the Guide: https://github.com/microprofile/wpsite
Contributor: Thomas Suedbroecker
Email: I will send to the issue owner.
(https://twitter.com/ameliaeiras/status/1272600865375793152?s=20)

**Comment by aeiras** [comment]
Thomas, 

ThankYOU for choosing to help add the content to MP content space 💛. 

Using this ticket, please provide the author email & name. We will help publish the blog one the content is added by the author to Wordpress. 

In the future, if you are interested in helping curate content for MP & you are comfortable with the Written  guidelines you are most welcomed to become a Wordpress Editor. An editor is someone who help publish content for MP on behalf of other authors. 💪🏼

**Comment by aeiras** [comment]
Thomas, 

ThankYOU for choosing to help add the content to MP content space 💛. 

Using this ticket, please provide the author email & name. We will help publish the blog one the content is added by the author to Wordpress. 

In the future, if you are interested in helping curate content for MP & you are comfortable with the Written  guidelines you are most welcomed to become a Wordpress Editor. An editor is someone who help publish content for MP on behalf of other authors. 💪🏼

**Comment by aeiras** [comment]
@thomassuedbroecker, 

Your contributor access was sent this AM. Welcomed to MP WordPress!
