### ISSUE TITLE
[MP Talk] Oracle Groundbreakers Yatra - Rafael Benevides

### ISSUE THREAD

**Issue by rafabene** [microprofile/microprofile-marketing#281]
Conference Name:
Oracle GroundBreakers Yatra

Conference website and social media links:
https://ogyatra.in/
https://twitter.com/OGYatra

Talk name:
MicroProfile APIs with Helidon

Talk Link:
None or TBD

Scheduled Date: 14th July 2020
Scheduled Time:  18:00 to 19:00 IST (Indian Standard Time) UTC +5:30

Speaker Names:
Rafael Benevides (@rafabene)

Tweet Message:
Watch @rafabene presenting @MicroProfileIO 3.3 APIs using @helidon_project implementation on 14th July 2020. More info at @OGYatra and https://ogyatra.in/

**Comment by rstjames** [comment]
All set to go out the week before and day before on twitter.
![MicroProfile-OracleGroundBreakersYatra-RafaelBenevides](https://user-images.githubusercontent.com/12132146/85269580-5e562300-b478-11ea-881d-21c60ceb8494.png)
