### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by jamesfalkner** [microprofile/microprofile-marketing#282]
I'd like to blog on the MicroProfile site, so this is my request. 

Name: James Falkner
Email: schtool@gmail.com

**Comment by aeiras** [comment]
Hola @jamesfalkner, 

Thankyou for choosing to become a MicroProfiler Content contributor via wordpress. #sharingIScaring! 

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/10731224/85455244-916ce500-b552-11ea-8bcd-e00fa35b2be4.png">
