### ISSUE TITLE
[Towards MicroProfile 4.0] Blog update

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#283]
@rstjames, 

Let's adjust the future media pushes related to blog on MP 4.0: https://twitter.com/MicroProfileIO/status/1267484566731796481?s=20 

Can this be completed before next week's media reminder? Thanks

**Design:**

- (design wording) MicroProfile 4.0 Release is delayed due to the MicroProfile Working Group requirement. 

**Media description:** 

#MicroProfileRelease 4.0 is delayed due to the @MicroProfileIO Working Group Requirement. 

#MicroProfilers💛 working on the APIs should continue their work towards Milestone 1. Read more HERE: https://bit.ly/36NV21n 

#OpenSource #OSS

**Comment by rstjames** [comment]
@aeiras 
all set till end of July. 
![MicroProfile-Release-delayed](https://user-images.githubusercontent.com/12132146/86478563-b3cce280-bd4a-11ea-95d1-ddcfa949a71d.png)

**Comment by aeiras** [comment]
perfect Ryan, thank you!
