### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor.

### ISSUE THREAD

**Issue by javatalks** [microprofile/microprofile-marketing#284]
First name: Arturo
Last name: Parra
email: parra.arturo@gmail.com

I just started a YouTube channel where I'll be talking about MicroProfile, among other Java technologies:

https://www.youtube.com/channel/UCyRhzV7gHfl_eTXnJe5qSjw

**Comment by aeiras** [comment]
Hola Arturo, 

Thank you for becoming the 63 MP wordpress content contributor! 
Your access was sent. :) 
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/10731224/86620142-b27cff00-bf70-11ea-9aa1-b25bce559464.png">
