### ISSUE TITLE
Dev-focused website phase 1: Update microprofile.io homepage to be more developer focused

### ISSUE THREAD

**Issue by aguibert** [microprofile/microprofile-marketing#285]
Part of issue #101 

Update the microprofile homepage to have more technical information about what microprofile is. 

1. Component tower: The main thing we had in mind was to show the "component tower" which is included on almost every MP platform presentation where it has each spec as a rectangle. Each rectangle should be clickable and take the user to an appropriate landing page to learn information about the respective spec. Here we can leverage existing resources, such as the spec PDF for MP Config: https://download.eclipse.org/microprofile/microprofile-config-1.4/microprofile-config-spec.html

Open to other ideas too, but this is all I had at the moment and would make the homepage a useful "hub" for learning about the various MP components

**Comment by aguibert** [comment]
@rstjames 

Here are the current cards on the homepage (in order):

- Title card
- Sponsor card
- Whitepaper card 
- Latest release card 
- Business value card 
- Starter card 
- Evolution of Java card
- Mission statement
- Recent blog posts

I propose that we use the following cards (in order) for the mockup:

- Title card (include brief mission statment here)
- Component tower card
- Starter / code sample card
- Company sponsor card
- Recent blog posts

For the starter/sample code card, we can use the following code:

```java
@Path("/hello")
@RequestScoped
public class HelloService {

    @Inject
    @ConfigProperty(name = "greeting", defaultValue = "Welcome to MicroProfile")
    private String greeting;

    @GET
    @Path("{name}")
    public String sayHello(@PathParam("name") String name) {
        return greeting + " " + name + ", lets get started!";
    }
}
```

**Comment by rstjames** [comment]
Update:
![screencapture-microprofile-io-2020-08-03-16_48_46](https://user-images.githubusercontent.com/12132146/89195614-49a59880-d5a9-11ea-9e25-c6ef9bfc7fc0.png)

**Comment by aguibert** [comment]
That looks great @rstjames! I really like the different colors on the component tower to indicate which ones are new/updated.

For the code sample, I see that some of the code overflows beyond the code block, is that intended?

CC @Emily-Jiang for feedback too

**Comment by rstjames** [comment]
@aguibert 
Code section: it is a slider to compare two separate images of code. Just only had the one image from you. An idea... 

The Component tower: will needed to be coded/ made. I was wondering if it needs to be this style or can we change it a bit. Can talk about it on the call today.

**Comment by aguibert** [comment]
@rstjames where is the calendar invite located at? I don't have anything on my calendar for today and should add it

**Comment by rstjames** [comment]
@aguibert its the bi weekly mp marketing call Not sure how to add you on the calendar ... here is the:

link to the call 
https://eclipse.zoom.us/j/4616298762 

Description:Agenda+Minutes:
https://docs.google.com/document/d/1Mc7VoePJFl4K-yoreLw-dri66mEkj0Ue0PLXwgF53fo/edit?usp=sharing

it is at 7pm cet

**Comment by aeiras** [comment]
> @rstjames where is the calendar invite located at? I don't have anything on my calendar for today and should add it

Andy @aguibert, 

MP Calendar for integration into yours: https://calendar.google.com/calendar/embed?src=gbnbc373ga40n0tvbl88nkc3r4%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by aeiras** [comment]
> Update:
> ![screencapture-microprofile-io-2020-08-03-16_48_46](https://user-images.githubusercontent.com/12132146/89195614-49a59880-d5a9-11ea-9e25-c6ef9bfc7fc0.png)

Really good start-draft Ryan!

**Reminder* for @rstjames**, please lets drop _Eclipse_ from any branding that associates its name with MicroProfile on this and any future mock-ups and adjustments for the website.

**Comment by aguibert** [comment]
@rstjames here is what I had in mind for the categorization:

<img width="1232" alt="Screen Shot 2020-08-03 at 1 17 01 PM" src="https://user-images.githubusercontent.com/5427967/89214070-bca01680-d58b-11ea-9b79-95b3f9a8b2d1.png">

A couple notes:
 - The basic idea is to show _some_ sort of categorization. I don't have strong opinions on what categories we choose, as long as we keep the number of categories small/meaningful (i.e. no more than 4 categories)
 - I also don't have strong opinions on on which specs go in which categories
 - I removed the "More information" button, since each box will be clickable and provide the "more information" for that specific spec
 - I made the component tower the full width of the screen, this assumes we can still make the SEO work well

**Comment by TetianaFTV** [comment]
Here is one more option how to place those clickable buttons with the text in the desktop mode (I used the screenshots from the current page, so don't pay attention to the texts).

While hovering, the button can be circled with yellow and the text in the middle will be changing. 
In the mobile version, there can be kept just the rows with buttons without extra text.

![microprofile](https://jelastic.com/blog/wp-content/uploads/2020/08/microprofile.png)

If categorization is required, they can be marked in this way (of course with normal colours picked)

![microprofile](https://jelastic.com/blog/wp-content/uploads/2020/08/microprofile-copy.png)

**Comment by aeiras** [comment]
Welcome to this space @TetianaFTV! :) 

The images you sent need to be copy/paste from zero to make it here. 
I have one of them from you, attached to this message. I think the way you re-order the APIs with the data in the center being filled out with the clicks is fantastic. 

@rstjames can you use Tetiana's mock up for adjustments when dealing with adding wording. 
![WordPress-for-Users-02(UPDATE)- (1)](https://user-images.githubusercontent.com/10731224/89230899-0a6f4b80-d599-11ea-9870-cae26083d80d.png)

**Comment by rstjames** [comment]
Page updates: 
Can view the page here: https://microprofile.io/edit-home/
The page was simplified. Removing some information and changing/ adding other to give it a more dev focus. 
-MicroProfile Starter card was adjusted
using the a slider graphic showing starter UI to code
![Screen Shot 2020-08-04 at 5 43 56 PM](https://user-images.githubusercontent.com/12132146/89314575-1a129100-d67a-11ea-9055-d71fcf446947.png)


**Can see two options for the "component tower"** 

1. (2nd card) this is a more "UI/ app style" it has room for a small description. If we need more room for the description I think this can be solved. Also can easily respond to Mobile. 
<img width="1259" alt="Screen Shot 2020-08-04 at 5 01 29 PM" src="https://user-images.githubusercontent.com/12132146/89309864-44f9e680-d674-11ea-9684-383275f85170.png">

2. standard component tower: Rollover for each box linked to webpage. Can view it on the bottom of the webpage link https://microprofile.io/edit-home/
<img width="1175" alt="Screen Shot 2020-08-04 at 5 05 16 PM" src="https://user-images.githubusercontent.com/12132146/89310206-afab2200-d674-11ea-9bbe-7dd0c2eed2e2.png">

**Comment by donbourne** [comment]
Hi, just a thought on my first impression on seeing the Foundation / Operations / Cloud groupings -- The term Operations makes me think those specs might be intended for operators/SREs, which is partly true, but misses that they are largely for application developers to make use of to make things observable for the benefit of ops.  I'm wondering if that group should be renamed to "Observability"?

**Comment by TetianaFTV** [comment]
Considering the way to add more code samples in the block with Starter, we can add buttons that will switch between the options. Also, I think the code part should go first and only then the screen, as the code attracts developers more. And if we need to have some short explanation for the code, we can add the commented out line at the beginning of the code sample. 

Something of this kind:
![microprofile starter](https://user-images.githubusercontent.com/38689227/89334977-ab443080-d697-11ea-9c1c-7ea7cde6038d.png)

**Comment by aguibert** [comment]
+1 for putting the code block first. All of the interesting bits of code are in the left-half of the code snippet, so only showing the right-half on initial page load hides most of the actual code.

As for the component tower, I am assuming these are image now, but assume the real thing will be proper web elements. In either case, we don't want to make the current design/layout too tied to the number of components we have at the moment, since a few more may be added in the future.

**Comment by rstjames** [comment]
@aeiras i like mockups that you suggested from @TetianaFTV but I suggest a longer discussion on this. I feel this is not scalable and will be difficult for mobile. But I think we can figure out something that will work .

**Comment by aeiras** [comment]
During today's Mktg hangout, it was decided that more feedback is needed from the broader community to move forward. 

I take the task to submit this ticket to the general forum and add that link to the MP Community call minutes as the only topic to be discussed under the Marketing space.

**Comment by aeiras** [comment]
@rstjames, 

Applying what was decided on today's MP Community call, to start implemented some changes:

1. lets dive into clearing all the items that ought to be removed from the main page

2. drop the Eclipse from the MicroProfile name

3.  do not rush on the block- APIs yet, lets dive into clean up first. 

Pulling Andrii for this project is ok! :) Thank you both for using this ticket to provide insight on improvements.

**Comment by aeiras** [comment]
@rstjames, 

While we work on the clean-up of the MP landing page, please adjust the ORGs logo alphabetically to MPWG members: IBM, RH, Jelastic, Atlanta JUG & Tomitribe.   The MPWG public date is Oct 1st, 2020. Therefore there is no need to wait for that adjustment. 

Thank you for bringing the page revised adjustments to next week's community call.

**Comment by rstjames** [comment]
@aeiras Bit confused: should I remove all other logos ? And only have IBM, RH, Jelastic, Atlanta JUG & Tomitribe?

**Comment by aeiras** [comment]
Lets discuss on today's mktg call. MP is hoping to be a formalized working group on Oct 1st, 2020. As such, we need the updating on Members list to match what currently is.  Related to this for future work are likely 2 logos that are needed to be scalable and representative of the MPWG Charter. 

- https://github.com/eclipse/microprofile-marketing/issues/315

- https://github.com/eclipse/microprofile-marketing/issues/314

**Comment by aeiras** [comment]
As discussed on this AM MP Marketing hangout, the Logos located in the MP landing page will be updated formally on Sept 30th, to be compliant with the MPWG first day of Oct 1st. 

@rstjames

**Comment by aeiras** [comment]
During today's MP Community hangout, the show and tell of new MP landing page happen! :) 
This ticket can be closed by any of you who actively pushed the adjustments, yeayy!

@rstjames 
One thing that I noticed on the page at the bottom of the page that requires adjustments:

**Insert:**
Copyright © [Eclipse Foundation](https://www.eclipse.org), Inc. 
2020 MicroProfile is an open source project under the [Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0.html).

**delete:**
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/10731224/91901673-7060f880-ec55-11ea-8635-fda838a22867.png">

**Comment by aeiras** [comment]
Nicely completed. Closing this ticket :)
