### ISSUE TITLE
Dev-focused website phase 2: Create new template for each MP component

### ISSUE THREAD

**Issue by aguibert** [microprofile/microprofile-marketing#286]
Part of issue #101 

Each MP component should have at least one page that contains the following information:
- What the spec does and what sort of problems it solves
- What some of the common use cases are (with code examples)
- Links to relevant resources, such as off-site guides (e.g. OpenLiberty and Quarkus have some guides that do a good job of explaining MP spec concepts)
- Link to the github spec project

At the marketing/website level we should just define the template, meaning things like:
- what sections to have (such as the list above)
- how the sections should be displayed (font size, colors/themes, etc)
- what source files each spec needs to provide, such as: (overview.adoc, code_samples.adoc, resources.adoc)

Then, each spec repo would be responsible for providing the technical content that would fit into and render in the template. So for example the MP Config community would write/maintain the `overview.adoc` file and when they merge PR changes to that file it will automatically update on the website

**Comment by aeiras** [comment]
Moved to the MPWG repo as part of yesterday discussion on work that needs to be completed as part of the 2021 planning approved. 

https://github.com/microprofile/microprofile-wg/issues/40
