### ISSUE TITLE
Dev-focused website phase 3: Socialize template from phase 2 and allow components to start updating to the new template format

### ISSUE THREAD

**Issue by aguibert** [microprofile/microprofile-marketing#287]
For issue #101 

Here we will take the template we create in issue #286 and try to socialize/promote it within the MP community and possibly assist each component with adopting the new model. For starters, we should work directly with one of the components (e.g. MP Config) to utilize the new template, and once we do that, the rest of the components can follow that first component as an example

**Comment by aeiras** [comment]
moved to https://github.com/microprofile/microprofile-wg/issues/41
