### ISSUE TITLE
[MPWG adjustments]  With the WG, the name changes to MicroProfile

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#289]
adjustments:

MicroProfile is officially the new name of the Project under the Working group. We need to adjust: 

- the MicroProfile website across to standardized formal name

- the Repo space, APIs  & documentation to trace naming 

- the google forums 
1) General google forum adjusted on 7/13/20 by Amelia
2) Marketing google forum adjusted on 7/13/20 by Amelia
3) Marketing drive- workINprogress started on 7/13/20 by Amelia

- MP Mktg -- update all the design cards templates, re-adjust anything that is set up automatically to match formal name. @rstjames this will take considerable amount of care.  :) 

- social media tools need adjustment as well. -
1) Twitter completed by Amelia on 7/13/20

- update via the forum on changes that will be in compliance to MPWG :)

**Comment by kwsutter** [comment]
Just a gentle reminder that we can't start making these type of changes until after the Executive Director officially accepts our WG proposal.  So, even though we have finalized our Draft Charter and that's a great first step, we have to wait a bit before we can start to make these changes.  Thanks.

**Comment by aeiras** [comment]
Yes @kwsutter, there are many steps ahead that are exciting that will lead MP to release 4.0, *finally*. When compared to all else, details such as this are not as important. 👍 but now they are traced here for visualization. :) Thanks for candid reminder!

**Comment by aeiras** [comment]
work in progress, a few MicroProfilers are working on the git changes and wiki. :)
