### ISSUE TITLE
Correct InfoQ article about MP Starter

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#29]
#usualsuspects Matt, 

Welcome to Microprofile! :) 

correcting required:

1.  Remove the Eclipse Team launches Starter
 TO

-  MicroProfilers launch MP Starter or similar. 

use link threads located in the forum :) if possible
[Article](https://twitter.com/InfoQ/status/1098274559843803137)

**Comment by mraible** [comment]
Fixed, but I don't have permission to close this issue.

**Comment by aeiras** [comment]
@mraible your actions show that we need to fix the documentation in the Starter Project directly Matt. 

Daniel is correct in the tweet with lack of tracing that must be placed in the project. 

Just great. thank you for #walkingthetalk and becoming a MicroProfiler!

**Comment by aeiras** [comment]
@rdebusscher we are getting direct feedback on Starter and what we need to improve. :) 

pulling you back in and leaving ticket open while we adjust a few things. justFUN!

**Comment by rdebusscher** [comment]
@aeiras yes, received a few GitHub issues.

Why do we need to keep this ticket open?

**Comment by aeiras** [comment]
Hey @rdebusscher I can close it since Matt helped adjust blog yet as feedback from the exchanges, Daniel explicit points out the total lack of INFO in the README. Can you help with that? should I open a new issue? 
 https://twitter.com/danielbryantuk/status/1098862902205927424

**Comment by rdebusscher** [comment]
@aeiras We should open an issue then at the Starter project to keep it at the right place.

But readme will not contain very much as the repo is just to create the Web Page. The repo code will not be used by developers directly.

But there will be some links on some management stuff like when and how will new MP implementation or version of MP implementation added, etc ...

**Comment by aeiras** [comment]
ticket is created and assigned to you,  apologizes @rdebusscher to just throw it without asking you :) 
closing this ticket. 

Again, thanks awesome @mraible!
