### ISSUE TITLE
[MP<>MP Onboarding wiki link] Needs to be fixed

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#290]
@rstjames, 

There are 2 fixes required with respect to the Onboarding Interviews media post & call2action yellow bottom in the 
Website:

Correct link is:
https://github.com/eclipse/microprofile-marketing/wiki/GUIDELINES:-Onboarding-into-MicroProfile-Interview

1. Under Contributors of MicroProfile "Onboarding Into MicroProfile needs replacement
2. https://twitter.com/MicroProfileIO/status/1280894411593773062?s=20  media push needs to be deleted and re-added with actual wiki. 

Thanks,

**Comment by rstjames** [comment]
@aeiras what happened to the link? When I made it, it was working... 
The link on the website has been updated. I updated the social media for the year.

**Comment by aeiras** [comment]
Thats what I don't know Ryan. 
The link we placed first was perfect but it no longer works. 

I know that the Eclipse Foundation INFRA team has been adjusting stuff in the back end, likely the data was affected as they continue to move onto other add-ons. 

Thanks for the fix. :)
