### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by hbelmiro** [microprofile/microprofile-marketing#296]
First Name: Helber
Last Name: Belmiro
Email: helber.belmiro@gmail.com

**Comment by rstjames** [comment]
Hello @hbelmiro ,
You have been added to the MicroProfile as a contributor. You should receive an email with login details.
Have any more questions let us know.

**Comment by hbelmiro** [comment]
Thank you @rstjames.
