### ISSUE TITLE
Request for reviewing new post

### ISSUE THREAD

**Issue by hbelmiro** [microprofile/microprofile-marketing#297]
Can anyone review my new post please?
https://microprofile.io/wp-admin/post.php?post=6572&action=edit

**Comment by aeiras** [comment]
Hola @Helber @hbelmiro, 

Your crosspost blog is published, I am so glad that I was the one who got to it today!  Thank you for choosing to become a valuable content contributor of MicroProfile! :)  Should you have any other MP blogs, even if they have been published long ago, please do pick and choose and add them to the wordpress space for review! 

**Please note** that I as the editor I chose to adjust two items on your post.  You are most welcomed to adjust the content as you see fits. As the author, you do have the final say! 

1. Title is now a question
2. the blog starts with the 1st paragraph of the conclusion of your article which answers 1 reason why MP is awesome!

**Comment by hbelmiro** [comment]
Thank you @aeiras 😃
