### ISSUE TITLE
Migrate https://github.com/microprofile/wpsite to an article in microprofile.io and then delete old repo

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#30]
This repository https://github.com/microprofile/wpsite contains the process to contribute to the current production microprofile.io blog.

Since the parent repo organization https://github.com/microprofile is been depecrated, my suggestion is to migrate the content Readme file into an WP Engine article which is the current CMS microprofile.io uses. 

Then we can safely delete or archive https://github.com/microprofile/wpsite.

**Comment by aeiras** [comment]
@eclipsewebmaster & @waynebeaton,

Hola EF team, can you please help us understand how MP Repo works? 
It seems that anyone can create tickets yet they cannot assign tickets to themselves or to Projects. 

For instance, Cesar is a contributor of MP, he cannot assign nor adjust his own ticket. 
I am a committer, i can create, adjust, close and move ticket progress. 

What are we missing in the INFRA? How do we fasciliate collaboration and owneship of the issues effectively? 
Thanks,

**Comment by aeiras** [comment]
@dblevins this ticket is closed.
