### ISSUE TITLE
[MP TALK] - JUG Mérida - Víctor Orozco

### ISSUE THREAD

**Issue by tuxtor** [microprofile/microprofile-marketing#300]
Conference Name:
JUG Mérida Meetup
https://twitter.com/JugMerida

Talk name:
Evaluating Java security with OWASP Top 10, Jakarta Security and MicroProfile JWT

Talk Link:
https://www.eventbrite.com/e/evaluando-la-seguridad-de-aplicaciones-java-backend-con-el-top-10-de-owasp-tickets-115451583795

Scheduled Date: 7th aug 2020
Scheduled Time: 18:00 to 19:00 (GMT-6)

Speaker Names:
Víctor Orozco (@tuxtor)

Tweet Message:
Meetup is in spanish, hence I'm attaching two versions, en-US and es-MX. Please use the best for MicroProfile.

(Es-MX) No te pierdas la presentación de @tuxtor quien nos mostrara como evaluar la seguridad de aplicaciones Java con @owasp Top 10, @JakartaEE y @MicroProfileIO junto a @JugMerida 

(En-US) Do not miss @tuxtor demonstration about security evaluation for Java applications with @owasp Top 10, @JakartaEE and @MicroProfileIO with @JugMerida

**Comment by rstjames** [comment]
@tuxtor 
![MicroProfile-Víctor Orozco-JUGMérida](https://user-images.githubusercontent.com/12132146/89197586-3d6f0a80-d5ac-11ea-91b2-1938cac621ed.png)

I will schedule it to go out a couple days before and the day before if you are ok with the visual

**Comment by tuxtor** [comment]
Visual Is ok. Please go ahead and thanks for your support

**Comment by rstjames** [comment]
Ok.  no problem.
