### ISSUE TITLE
Usage of Oracle Trademarked Assets on the New Microprofile website

### ISSUE THREAD

**Issue by vincentmayers** [microprofile/microprofile-marketing#302]
I am going to reach out to Tiki Dare Assistant General Counsel for Oracle (whom I know from my time there) to either confirm that we are able to use or solicit approval to use Oracle trademarked assets on the new Microprofile website. MP feels we do not have an issue with the Dukes Choice Award graphic but we will most certainly have one with the Java logo

**Comment by aeiras** [comment]
you are fantastic Vince! :)

**Comment by edbratt** [comment]
If you like, I can facilitate this with you. I've started a discussion internally as well. Some changes are likely going to be required and, yes, there will be some guidelines. The logo on jakarta.ee is probably the correct "badge" to be used, but let's confirm that before any changes are made.

**Comment by vincentmayers** [comment]
Thanks Ed that would be great. I worked closely with Tiki Dare in the past and reached out to her after our call today. I didn’t k ow about the MP public marketing list or would have copied that. Perhaps you can ping her as well? 


Cheers
Vincent 

@vincentmayers

**Comment by vincentmayers** [comment]
> If you like, I can facilitate this with you. I've started a discussion internally as well. Some changes are likely going to be required and, yes, there will be some guidelines. The logo on jakarta.ee is probably the correct "badge" to be used, but let's confirm that before any changes are made.

Hi Ed, can you reach out internally to Tiki Dare re this? She has not replied to my message as of yet

Many thanks
Vincent

**Comment by aeiras** [comment]
@vincentmayers hey MicroProfiler, 

Any update on this?

**Comment by vincentmayers** [comment]
despite reminders, no sorry

Cheers
Vincent

@vincentmayers

**Comment by aeiras** [comment]
thanks for the follow up Vince. 
Tomorrow, the new page is going live today and it won't change that card with Duke until it is requested 👍

**Comment by edbratt** [comment]
Dear Microprofile Project Team,

Congratulations again on being a 2019 Duke's Choice Award recipient.

To acknowledge receiving this award, you're welcome to use the following Duke's Choice Award logo on your website, https://microprofile.io by adhering to the following usage parameters:

1. The logo may not be altered in any way (e.g. color, design, layout style, etc).
2. The logo may not be included or embedded in any released product material such as "about" pages, "splash" screens, or download pages.
3. No claims of Oracle endorsement may be placed with the logo or in-reference to the award elsewhere.

- [x] Please check this box indicating agreement if you're able to adhere to these parameters and I'll attach a clean version of the Duke's Choice logo for your use.
![Sample-Dukes-Choice](https://user-images.githubusercontent.com/12281454/91892971-57057f80-ec48-11ea-87ce-9e77fdc4224a.jpg)

**Comment by aeiras** [comment]
Hola Ed, 

Thank you for the follow-up! 

The logo will be updated once you provide the file!  :)

**Comment by edbratt** [comment]
Here you go. Thanks!
![duke award original-1](https://user-images.githubusercontent.com/12281454/97220905-7375f200-1789-11eb-8e5a-3565942db8c8.png)

**Comment by aeiras** [comment]
Thank you, Ed. We appreciate your help. 

Vince-- thank you for paying close attention to stuff! :) 

Ryan, 

The Dukes' logo contains 4 parts within it on the website. 
We need to drop the 4 section ( from top to bottom). 
The **removal** of the Java word & the coffee cup needs to happen.

**Comment by aeiras** [comment]
On this week mtkg call, we discussed the adjustments! 

@rstjames is on it and ticket will be closed as soon as the adjustment is completed this week. Thanks Ryan and Vince and Ed!

**Comment by rstjames** [comment]
Done :)
