### ISSUE TITLE
[Course Bundle containing: e-Book] media push error

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#305]
@rstjames,

Can you please look at what is scheduled via buffer for Phillip's ebook? 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/10731224/89465685-5fd96300-d727-11ea-9a5a-12af2166ad38.png">

Above tweet uses the old version of Phillip's ebook. Now deleted from twitter. Thank YOU!

**Comment by rstjames** [comment]
@aeiras This old one must have snuck by... But I looked and none of the update tweets for philips course is on the tweetdeck anymore... I am 99% sure I scheduled it for the year... So looks like I need to add it back onto the schedule. I will look for the correct/ updated tweet and image.

**Comment by aeiras** [comment]
ok @rstjames, 

There is a problem with the management of the tweets. 

I will send an [email to the mktg forum](https://groups.google.com/forum/#!topic/microprofile-marketing/O6RgEsk3nyk) to ask if anyone has touched the scheduling. There are only 4 MicroProfilers who push content under the MP twitter account. You, Debbie, Cesar S. and I. 

Thank you for letting us know of the grave issue. lets fix it. :)

**Comment by aeiras** [comment]
@rstjames, 

I went ahead and requested a new MP twitter password to protect the account. 
I am 100% sure that Philip's 3.3 update book was set for the rest of 2020. Likely human error, so I hope. 

As usual, please remember that the only reason to use the password is to adjust the design of the Twitter account. 

The Admin access for design proposes have been sent to you via email. Thank you for bringing the issue promptly. 
Thanks for bringing back the e-book to the MP media twice per month and the off weeks where Cicek's ebook is not ongoing. 

Can you also check that media push for the e-book of Cicek?
How about the WhitePaper by Lars?

**Comment by aeiras** [comment]
I have contacted Philip directly via the ticket as well.  https://github.com/eclipse/microprofile-marketing/issues/259

**Comment by rieckpil** [comment]
thank you both for the outstanding effort on this :rocket: 

The Tweet is converting really good an I can see 5 - 10 new book requests per Tweet. 

Some rough timeline for the future of it:
- Once MicroProfile 4.0 is released I'm working on the adjustments and will also add chapters with full application examples (using MP standalone and also with Jakarta EE)
- The plan is to then publish it on Leanpup and charge a small fee for it

**Comment by aeiras** [comment]
@rieckpil Phil, 

Thank you for the insight providing a direct feedback loop on the tracing on the current pushes of your e-book. Congratulations and thank YOU for caring enough to share. Thats the best payment for anyone volunteering on the branding side of things in MP :) 

About the 2 items you mention, kudos-- 

1.  you need to follow the same steps you did before with the update blog, etc as you nicely owned with @rstjames  via that ticket. 

2.  +1 to charging a "coffee/tea/etc admin fee".  Though it is up to you to choose the $amount, please pay close attention to the opportunity costs, even with small fees by introducing it in the 3rd iteration of your e-book.  
Research shows based on what we see that MP workshops start at $10 USD for 2 to 5hrs. 
When I say "coffee - thank YOU coverage" I unfairly pushed/project to you a 5$ USD as suggested based on the pricing of current MP paid workshops. 
There are many things you cannot assume when changing the FREE to small fee. It is easily doable and to be fair, I see it as a positive but only if it matches your desire to not only gain new subscribers but also protect those who already consume versos 1 & 2 of your e-book. You have 2 audiences and you ought to protect both with any changes. 

Have fun and thanks for the follow up, I will add it as a direct update to the next MP mktg hangout. :)

**Comment by rieckpil** [comment]
thanks for your thoughts on this 🙇

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/308 fixed. 👍 Thanks Ryan!
