### ISSUE TITLE
Reschedule MP whitepaper Tweets

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#307]
Scheduled for the rest of the year after it disappeared on the scheduled tweet deck. 

Have you read the #MicroProfile Technical White Paper yet? Lars Röwekamp @mobileLarson explains why NOW is the best time for developers & users to adopt the #MicroProfileAPIs when developing #microservices. Read more https://bit.ly/2PHFNzl

#MPWhitePaper #opensource #OSS 
![MicroProfile-Whitepaper-twitter](https://user-images.githubusercontent.com/12132146/89901658-b215fa80-dbe5-11ea-8341-1b7528c004c3.jpeg)

**Comment by aeiras** [comment]
Thank you Ryan!!!

fixing issues with "surprise" deletions on media pushed https://github.com/eclipse/microprofile-marketing/issues/305
