### ISSUE TITLE
ReSchedule Philip Riecks Free course bundle (ebook)

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#308]
The tweet has been rescheduled for the year after it disappeared off tweetdeck. 

#MicroservicesEnthusiasts, Philip Riecks @rieckpil UPDATED the comprehensive & free Course Bundle (E-Book, Video Course, Cheat Sheet) to kickstart your #MicroProfile success using the latest @MicroProfileIO version 3.3. https://bit.ly/3bq6e5I

#opensource #MicroProfileeBOOK 

![MicroProfile-ebook3 3](https://user-images.githubusercontent.com/12132146/89901737-d1ad2300-dbe5-11ea-9b32-fea5e4bf1069.png)

**Comment by aeiras** [comment]
You are amazing @rstjames! thank YOU :) 

@rieckpil  your e-book is back in rotation for the rest of 2020. 
B/c we don't know when MP.4.0 will happen, aiming at early Q4... but it is contingent on MPWG stage 5, active group the schedule goes for the entire 2020 for now.
