### ISSUE TITLE
Reschedule MP4.0 delay announcement 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#309]
#MicroProfileRelease 4.0 is delayed due to the @MicroProfileIO Working Group Requirement. #MicroProfilers 💛 working on the APIs should continue their work towards Milestone 1. Read more HERE: https://bit.ly/36NV21n

#OpenSource #OSS 

![MicroProfile-4 0release-delay](https://user-images.githubusercontent.com/12132146/89901943-1df86300-dbe6-11ea-90b5-dac6243267a5.jpeg)

**Comment by rstjames** [comment]
All set

**Comment by aeiras** [comment]
Thank YOU @rstjames!

So, the pushed was also deleted?

**Comment by aeiras** [comment]
fixing issues with "surprise" deletions on media pushed https://github.com/eclipse/microprofile-marketing/issues/305
