### ISSUE TITLE
Delete https://github.com/microprofile/microprofile-blog

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#31]
If if all the post contained in this repository were already migrated into WP engine (current microprofile.io CMS), then the repo https://github.com/microprofile/microprofile-blog can be safely deleted or archived.

It's important to highlight that https://github.com/microprofile/microprofile-blog is not part of the observed repositories the micoprofile.io contributors page via this repository: https://github.com/microprofile/microprofile-blog

**Comment by aeiras** [comment]
@rstjames you were directly involved in the transfered of the old MP blog to WordPress. 

What is your take on this?

**Comment by rstjames** [comment]
@aeiras @cesarhernandezgt When I transfered the MP blog from the old backend to WP I did this manually. So I am not sure if there is any value with keeping the old repository.

**Comment by cesarhernandezgt** [comment]
Thanks, @rstjames for the reply.
@aeiras , https://github.com/microprofile/microprofile-blog is safe for deleting or archiving. 
https://github.blog/2017-11-08-archiving-repositories/

**Comment by aeiras** [comment]
Thank you @rstjames & @cesarhernandezgt for triple checking this. :) 

I don't have the permissions to delete or archive it. adding a few microprofilers to complete task and close this ticket. Thanks!

**Comment by cesarhernandezgt** [comment]
@aeiras  I don't have those permissions either (delete and archive) over the repository.

**Comment by aeiras** [comment]
@dblevins can you delete the repo?

**Comment by aeiras** [comment]
@dblevins this ticket is closed.
