### ISSUE TITLE
[ MP Presentation ] Building Robust Applications with the MicroProfile APIs: A Live Coding Event

### ISSUE THREAD

**Issue by mpredli01** [microprofile/microprofile-marketing#310]
I will be presenting "**_Building Robust Applications with the MicroProfile APIs: A Live Coding Event_**" at the [ACGNJ Java Users Group](https://javasig.org) meeting as detailed below:

Tuesday, September 8, 2020
6:30pm
via Amazon Chime

**Abstract:**

The MicroProfile initiative, introduced in mid-2016, is a collaboration of Java community members representing IBM, Red Hat, Tomitribe and Payara, among others.

The initial three MicroProfile APIs: Contexts and Dependency Injection (CDI); Java API for JSON Processing (JSON-P); and Java API for RESTful Web Services (JAX-RS), have been considered a minimal set of APIs for building microservices-based applications. Since its debut, MicroProfile has grown to a total of 12 core APIs along with four standalone APIs for handling reactive streams.

This presentation will provide a brief introduction and overview of MicroProfile followed by a live coding session to demonstrate individual MicroProfile APIs.

All the best,

Mike.

**Comment by rstjames** [comment]
Hi Mike @mpredli01 
Please provide a **tweet message** and I will make the visual and schedule it to go out on twitter. 

Thanks,
Ryan

**Comment by rstjames** [comment]
@mpredli01 please see my last message.

**Comment by mpredli01** [comment]
> Hi Mike @mpredli01
> Please provide a **tweet message** and I will make the visual and schedule it to go out on twitter.
> 
> Thanks,
> Ryan

Hi Ryan:

My apologies for the delayed response.  Here's the tweet:

@mpredli, co-facilitator of @javasig, will present "Building Robust Applications with the MicroProfile APIs: A Live Coding Event" on September 8, 2020 at 6:30pm. Please visit https://javasig.org for all the details! @microprofileio #shareMPKnowledge

Best regards,

Mike.

**Comment by rstjames** [comment]
@mpredli01 all good to go
