### ISSUE TITLE
Tweet MicroProfile 4.0M1 release

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#311]
For the purpose of reviewing the staged twitter MicroProfile 4.0M1 release graphic and text, the link will be https://github.com/eclipse/microprofile/releases/tag/4.0M1

**Comment by jclingan** [comment]
M1 release is now available.  Feel free to  tweet - https://github.com/eclipse/microprofile/releases/tag/4.0-M1

**Comment by aeiras** [comment]
just fantastic @jclingan :) 

**twitter description** for @rstjames 
#MicroProfileAnnouncement: 💛@MicroProfileIO 4.0-Milestone 1 Release is now available!  This is the first #MicroProfileRelease based on @JakartaEE 8.  

Check-out what is new:  https://github.com/eclipse/microprofile/releases/tag/4.0-M1

#OpenSourceFUN #ByCommunityForCommunity 

**tweet schedule** work week day
Twice per month, same day/time/description/design until October 4th.

**Comment by rstjames** [comment]
sent out and scheduled. 
![MicroProfile-4 0-milestone-1 release](https://user-images.githubusercontent.com/12132146/90531411-54018e00-e176-11ea-9925-29139b20ebf8.png)

**Comment by aeiras** [comment]
the design card looks simple fantastic @rstjames!

@jclingan as stated on yesterday call, you are on fire with timing on the release. 

as decided on yesterday Mktg call, there won't be any adjustments on the website related to the release. 
such action will enable minor releases from MP APIs to occur and be covered via MP twitter media without extra debt or complications.
