### ISSUE TITLE
[grammar fix] MP Onboarding interview media push

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#318]
Hola @rstjames, 

Lets correct the tweet message inserted in the message for future pushes:
_Location:_ with hopes to **inspires** you
**to**
with hopes to **inspire** you

https://twitter.com/MicroProfileIO/status/1301208013118660608?s=20

Thank you,

**Comment by rstjames** [comment]
@aeiras  All set for the year

The #MicroProfile Community cares about its members & does its best to keep the process simple to get started. #MicroProfilersInterview series provide valuable input in optimizing the welcoming process with hopes to inspire YOU, a user/contributor to join https://github.com/eclipse/microprofile-marketing/wiki/GUIDELINES:-Onboarding-into-MicroProfile-Interview

**Comment by aeiras** [comment]
Thank you amazing Ryan! 🥋
