### ISSUE TITLE
Do we have MicroProfile fonts available?

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#319]
There is an issue on https://github.com/jakartaee/collateral/issues/1 opened by @BaptisteMeynier asking for Microprofile fonts. Is this available somewhere? 
cc: @rstjames

**Comment by rstjames** [comment]
@cesarhernandezgt I just put this up on the MP site. You can share this link with him. https://microprofile.io/resources/branding/

**Comment by cesarhernandezgt** [comment]
Thank you @rstjames I'll close this ticket since now I found the URL.
