### ISSUE TITLE
Add links to the 2nd card of microprofile.io

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#320]
In the current microprofile.io, the 2nd card lists a few blocks. Each block should be clickable and point to the corresponding specs/pdf/javadoc.

For MicroProfile Config 1.4, it should be https://github.com/eclipse/microprofile-config/releases/tag/1.4
We can do the similar thing for other specifications.

The next stage is to invest the github pages.
@rstjames

**Comment by rstjames** [comment]
@Emily-Jiang yes to make them all clickable we will need all page links. Not sure how to get each "team" to make them... but once we have them I can start to make it all clickable

**Comment by Emily-Jiang** [comment]
@rstjames I think for now we can link to the above relase tag to start with. Then we can look at the github pages. Let me supply you with all of the links.
Config: https://github.com/eclipse/microprofile-config/releases/tag/1.4
Fault Tolerance: https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/2.1
Open Tracing: https://github.com/eclipse/microprofile-opentracing/releases/tag/1.3
JWT: https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.1
Rest Client: https://github.com/eclipse/microprofile-rest-client/releases/tag/1.4.0
Heath: https://github.com/eclipse/microprofile-health/releases/tag/2.2
Metrics: https://github.com/eclipse/microprofile-metrics/releases/tag/2.3
Open API: https://github.com/eclipse/microprofile-open-api/releases/tag/mp-openapi-1.1

**Comment by Emily-Jiang** [comment]
As a prototype, I create a [webpage](https://emily-jiang.github.io/microprofile-config/) for MP Config. I'll show this at the next MP call to get some feedback.

**Comment by rstjames** [comment]
@Emily-Jiang I made a rough of the page you sent. https://microprofile.io/microprofile-config/ 
It still could used some work but the base is there. I hope to be on the call today there is a chance I can not make it.

**Comment by rstjames** [comment]
Tower update: @Emily-Jiang 
Please check links and after I will make it live on the home page. 
https://microprofile.io/tower/

**Comment by Emily-Jiang** [comment]
@rstjames the links look good. Thanks for getting it done!
