### ISSUE TITLE
Branding resource page improvements

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#322]
In this ticket, everyone can put their suggestions on what resources should be added  MP community branding page. https://microprofile.io/resources/branding/. 

**Hope to add soon:**
- presentation templates
- scalable social media images. (for people that do not have Adobe) 
- branding manual

**Comment by aeiras** [comment]
@rstjames, 

This new click on Resources is a betterment related to the other https://github.com/eclipse/microprofile-marketing/issues/288. Just wonderful to move forward :) Thank you for bringing fun to the new features.

**Comment by aeiras** [comment]
@rstjames, 

Where do we have the MP presentation slides?

**Comment by aeiras** [comment]
Inventory of Resources Page :) 

Lets remove MP Starter and replace it on that spot with Branding. 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/10731224/93520672-b23f9f00-f8e3-11ea-91a4-c92f8dff7c0c.png">
