### ISSUE TITLE
[Swag] Ship MP t-shirt to Emerson

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#323]
@aeiras as you have indicated during Today's MicroProfile Live Hangout Meeting, I'm creating this issue :)

Thanks

**Comment by aeiras** [comment]
Hola @emecas, 

I will personally make sure your shirt request is shipped to you next month. :) You & your MicroProfile contributions rock! 

Thank you for choosing to show up and add value, cannot wait for you to take that pic on and out of the MP community hangout and share it via public media. :)

**Comment by aeiras** [comment]
@emecas, 
California opens on June 15th, your MP swag is close to getting to you! :)

**Comment by majidmostafavi** [comment]
Hola @aeiras 
I'm so excited for creating T-Issue  ;)))

**Comment by aeiras** [comment]
> Hola @aeiras
> I'm so excited for creating T-Issue ;)))

@majidmostafavi you need to create a new git issue that tracks your MP swag. : )
This ticket belongs to MicroProfiler Emerson, only!

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

Emerson, you have waited for the longest time to get your MP swag. As soon as you get it, let us know so that we can close this very old ticket. :)

**Comment by emecas** [comment]
Thanks, I got it :)

**Comment by aeiras** [comment]
so amazing! 

So, looking forward to seeing you wear your mpSwag, Emerson! : ) Abrazos

You waited so long due to pandemic, gracias!
