### ISSUE TITLE
[MPWG Website Tile Description] For the Eclipse Working Groups Explore Page

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#326]
Task sent by Sharon on 9/16 deadline 9/17 via MPWG [forum request](https://www.eclipse.org/lists/microprofile-wg/msg00003.html)

MP - Tile [Draft](https://docs.google.com/document/d/1CEq0EyU0b0DsgKGSVLkeyo2D1GNcPwVRuMOQuRL-Prs/edit)

**Comment by aeiras** [comment]
I submitted review via "suggestive mode" directly in the document.

**Comment by aeiras** [comment]
The draft was reviewed by David, Kevin, Emily and Amelia. :)

**Comment by jclingan** [comment]
Sorry, I am late to the party. Crazy week. We are adding cloud-native to our tagline?

**Comment by aeiras** [comment]
Hola John, 

No, we are not. did you check the draft?

**Comment by jclingan** [comment]
Yep, it says "... MicroProfile is an open forum that optimizes Enterprise Java for a cloud-native microservice architecture ..."

**Comment by aeiras** [comment]
@jclingan, 

Clearly we missed that: 
I have been on 24/7 JCP call day so no bandwith to see this ticket. Can you remove it please & add yourself as reviewer in this ticket?  - thank you 🙏 

The description won’t go live until Monday & even after it is public we can edit stuff.

**Comment by emecas** [comment]
Although this task is just attempting to provide a description for explore page and original due date has already passed, this is an interesting discussion topic around why or why not MP could be considered as "cloud-native", eventually  here or somewhere else.

Why don't see this concept as a growth opportunity in order to identify and produce specifications on that direction?

Keeping focus at the right level with agnosticism, MicroProfile-Cloudify, MicroProfile-Integration, MicroProfile-Delivery, and MicroProfile-Infrastructure, could be nowadays specs screaming to initiate.

**Comment by jclingan** [comment]
@emecas I don't necessarily disagree with it, but we have had the current tagline for 4 years and have not discussed changing it. Things also get a bit interesting if both Jakarta EE and MicroProfile position themselves as cloud native. Maybe they both are, but how the two projects go about it is very different. My thoughts are:

1. Let's discuss it, perhaps even for MP 4.0
2. Disuss it in the context of broader MicroProfile and Jakarta EE WG positioning
3. Leave tile without "cloud native" until we nail it down

**Comment by jclingan** [comment]
Whups, I've removed it from tile description. Not sure if it is too late.

**Comment by aeiras** [comment]
+1 @jclingan!  It is not too late. We can request the adjustments if it already went through. Great catch on that. Too short of a notice to work on stuff makes for oversights with less brains.  Thank you for adding yourself to the review. 

@emecas- Hola, 
The topic could be discuss later as John mentions. -- Lets leave this ticket closed for now and base it solely on the task.

**Comment by aeiras** [comment]
+1 @jclingan!  It is not too late. We can request the adjustments if it already went through. Great catch on that. Too short of a notice to work on stuff makes for oversights with less brains.  Thank you for adding yourself to the review. 

@emecas- Hola, 
The topic could be discuss later as John mentions. -- Lets leave this ticket closed for now and base it solely on the task.

**Comment by aeiras** [comment]
+1 @jclingan!  It is not too late. We can request the adjustments if it already went through. Great catch on that. Too short of a notice to work on stuff makes for oversights with less brains.  Thank you for adding yourself to the review. 

@emecas- Hola, 
The topic could be discuss later as John mentions. -- Lets leave this ticket closed for now and base it solely on the task.

**Comment by aeiras** [comment]
+1 @jclingan!  It is not too late. We can request the adjustments if it already went through. Great catch on that. Too short of a notice to work on stuff makes for oversights with less brains.  Thank you for adding yourself to the review. 

@emecas- Hola, 
The topic could be discuss later as John mentions. -- Lets leave this ticket closed for now and base it solely on the task.

**Comment by aeiras** [comment]
+1 @jclingan!  It is not too late. We can request the adjustments if it already went through. Great catch on that. Too short of a notice to work on stuff makes for oversights with less brains.  Thank you for adding yourself to the review. 

@emecas- Hola, 
The topic could be discuss later as John mentions. -- Lets leave this ticket closed for now and base it solely on the task.
