### ISSUE TITLE
[MPWG Membership- Legal ] Atlanta JUG

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#328]
Deadline by Oct 12th

**Comment by vincentmayers** [comment]
Today we received countersigned agreements from The Eclipse Foundation so are happy to announce that Atlanta Java Users Group, Inc. is now a solutions member of the EF. This is awesome news for our community as we now have an opportunity via the MicroProfile Working Group to help the evolution of this superb project. 

Vincent Mayers
Treasurer/Board Member Atlanta Java Users Group (AJUG)

**Comment by aeiras** [comment]
Completed as of 10/5/20!~ yeayy :)
