### ISSUE TITLE
Require help to help fix article on MP 2.2. release by Erik

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#33]
[article](https://twitter.com/andre_sept/status/1099047237672411139)

I sent a [tweet](https://twitter.com/ameliaeiras/status/1099069380187455488) to infoQ

If anyone knows the bloger Erik with twitter @costlow, do reach out. :) thanks

**Comment by erikcostlow** [comment]
Hi, yes I wrote that. I can look at changing it, but it's called "Eclipse MicroProfile," the site's "see the code" goes into Eclipse.org through the Eclipse foundation, and the maven groupId is org.eclipse. This combined with people I have talked to, indicate that it either was Eclipse or the community is ok with using that general moniker for simplicity.
What is a better term here that would be have been apparent from the materials?

**Comment by aeiras** [comment]
@erikcostlow it is nice to virtually meet you Erik! 
Thank you for taking the time to follow up via issue and for considering the MicroProfile Project worthy to compose and share via your infoQ blog. 

Your actions via that blog are of great value to MicroProfilers as they help the project be documented better to avoid confusions such as the one you state above. 

**The EF Team**  doesn't do any develpment for the projects they house under the umbrella. The EF team job is to provide a neutral ground where individuals and different organizations (JUGs, Vendors, etc) can collaborate. Just as the Apache Software Foundation provides that neutral ground that includes the INFRA to enable OSS to thrive. 

Each time, a blog comes with the Foundation ONLY name it cuts the work actually done by the contrubutors of the project. 

Thank you for adjusting the blog. Currently, we are adding feedback issues to the MP Marketing Repo on how to make the microprofile website clearer. Should you want to help, please help the write-up. What else you and individuals like you could benefit that can be added to site?

**Comment by aeiras** [comment]
@erikcostlow I adjusted the MP. 2.2 release[ first sentence](https://microprofile.io/2019/02/12/eclipse-microprofile-2-2-is-now-available/) to the announcement using your feedback. _Thank you_! 

- The MicroProfile Community would like to announce the release of Eclipse MicroProfile 2.2.

**Comment by erikcostlow** [comment]
I'm fine with whatever term you think is clear and appropriate. I looked up how Apache did it with Kafka, and they just used the term "Apache." https://globenewswire.com/news-release/2017/11/01/1172058/0/en/The-Apache-Software-Foundation-Announces-Apache-Kafka-v1-0-0.html
The term "community" seems too broad, as users are also part of the community. The question in this context is, who can officially state what is in X.Y release?
Looking at how Apache did it, the headline could say "Eclipse ..." and then the article (which is not a blog) would say something about volunteers or whatever term you choose. That would delineate between the Eclipse Foundation, and the broader group using the term Eclipse. Using that term, I can try to re-word the first sentence to avoid the word "foundation" which seems to be the point of confusion here.

**Comment by aeiras** [comment]
@erikcostlow adjusted the blog to: Contributors-- really good feedback Erik, thankYOU!

- The MicroProfile Contributors would like to announce the release of Eclipse MicroProfile 2.2.

**Comment by aeiras** [comment]
is it ok for us to close this ticket or do you prefer to confirm the blog adjustments via comments to close the issue?  Let me know if there is anything else we could improve and lets do this! :) 
@erikcostlow

**Comment by erikcostlow** [comment]
I'm fine with that; I'll see if I can make the change.
It will be helpful if the same term is used for other projects as well, like if the Eclipse Collections team uses the same convention. Similar to how the foundation provides infrastructure, they could also provide this branding.

**Comment by aeiras** [comment]
I agree with you @erikcostlow--  the simple stardarization on names is SUPER important yet not effectively prioritized as such stuff is left unchecked many times.  Self-Police goes into effect as shown with our exchanges. 💯 #sharingIScaring i call that.

Today, in the MP project [we are chatting](https://groups.google.com/forum/#!topic/microprofile/-o0Mqv4I2IY) about how to make it easier for new Contributors to help without waisting time trying to figure out how to get started. It goes beyond the Repo. Check conversation if you are interested and participate if you want!
