### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by rzgry** [microprofile/microprofile-marketing#332]
Name: Ryan Zegray
Email: ryan.zegray@ibm.com

Hoping to post a blog post on the newly published vscode-microprofile extension 😄 
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-microprofile

**Comment by aeiras** [comment]
Hola Ryan @rzgry, 

Your MP-wordpress contributor access should be in your inbox! 
Thank you for choosing to share content via the MP blog, you are MicroProfiler 66 participating on the #SharingISCaring!
