### ISSUE TITLE
MicroProfile Prospectus Member Quote - Jelastic

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#335]
Looking for each Working Group corporate member to provide a quote. See [prospectus](https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit#slide=id.g77280c392b_2_0).

**Comment by TetianaFTV** [comment]
"The growing demand in microservice architecture and containers led to the increasing necessity in MicroProfile. This initiative helps to develop and run Java applications in an easily, scalable and resilient way using dynamic cloud environments. MicroProfile framework will bring a deeper interoperability across cloud platforms and the emergence of portabile vendor agnostic solutions." 
-- Ruslan Synytsky, Jelastic

(already added to the deck)

**Comment by aeiras** [comment]
Thank you @TetianaFTV! :) 

@jclingan i will close this ticket.
