### ISSUE TITLE
MicroProfile Prospectus Member Quote - Atlanta JUG

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#336]
Looking for each Working Group corporate member to provide a quote. See [prospectus](https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit#slide=id.g77280c392b_2_0).

**Comment by aeiras** [comment]
“MicroProfile is the epitome of an open source project. Its lead by an extremely passionate group of individuals that value open communication and community. The manner in which open discussions inform the direction of the project should be a standard that all OSS efforts, whether they are stewarded by a foundation or not, should hope to live up to.”
-- Vincent Mayers, AJUG

**Comment by aeiras** [comment]
Thank you ATL JUG Team! :) 

@jclingan i will close this ticket.
