### ISSUE TITLE
[Wbsite- Main page]  MP Releases

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#337]
Kevin provided on the MP community call a fantastic contribution on adding the previews release link to the card shared below. 
 

- Updated

- No change from MicroProfile 3.2 Release [LINKED] example to use for current page and future updates. :) 

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/10731224/94484686-b09e9280-0191-11eb-986e-b0354b27458d.png">

**Comment by rstjames** [comment]
All updated. @aeiras
