### ISSUE TITLE
[MP website] Footer section  require fixes

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#338]
**Update to:** 
- 2020 MicroProfile is an[ Eclipse Foundation](https://www.eclipse.org) project running under the Apache License, Version 2.0

**Remove:** 

- the blue section that adds Eclipse information. 

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/10731224/94485119-49cda900-0192-11eb-925c-2584db5fe498.png">

**Comment by rstjames** [comment]
All updated and good to go. 
@aeiras
