### ISSUE TITLE
Revamp projects pages on microprofile.io

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#340]
On the microprofile.io under all projects, it lists all of the projects and disaply the readme for the relevant project. The readme doc is often static and contains old info. We need to revisit the readme and introduce a template so that all of the readme flles adopt the same format. 

Here is the [draft page](https://microprofile.io/microprofile-config/) for MP config.

**Comment by aeiras** [comment]
@Emily-Jiang did you read the forum thread: https://groups.google.com/forum/?pli=1#!topic/microprofile/7xEB4PO9Zqs yet?

Work in progress!

**Comment by aeiras** [comment]
This ticket is related to automatication using back & front end work (currently being investigated with the help of Summers)

Closing it b.c it doesn't require human adjustments or maintenance as other pages in MP site.
