### ISSUE TITLE
Content not readable on microprofile.io  home page

### ISSUE THREAD

**Issue by rsoika** [microprofile/microprofile-marketing#341]
Sorry but I must again point out that the official [microprofile.io](https://microprofile.io) homepage has very bad layout problems.
I came across the problem when I just wanted to read something about the Metric API myself. There is sill the problem that the .adoc files are not correctly displayed on the home page.
If you as a user didn't  know the Github source you will not be able to learn something useful about the different projects. And I think this is really really bad.  Because you all do so much good work creating a awesome microservice framework but users who want to learn something about all this starting with microprofile.io will be frustrated after a few minutes. 

Just to to point it out once again please compare the following two links which should show the same content:

 - https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/app-programming-model.adoc
 - https://microprofile.io/project/eclipse/microprofile-metrics/spec/src/main/asciidoc/app-programming-model.adoc

This is how the content should look like (and is shown on Github):

------------

![image](https://user-images.githubusercontent.com/1339124/94859382-b9fb5980-0434-11eb-9a81-bb52dca8b0b0.png)

------------

And this is what the user see on microprofile.io

------------

![image](https://user-images.githubusercontent.com/1339124/94859461-d8615500-0434-11eb-9613-53b3e323d559.png)

------------

I have tried to point to this problem several times. All Microprofile Projects are affected. It is not a Problem form the different projects. It is only a Problem form how microprofile.io is rendering the README and .adoc files form the project.

I fear that the problem can only be solved with a very great deal of effort. So I can understand that this can not be solved over night. Therefore, I suggest that we refer directly to the corresponding Github projects from the Microprofile.io project overview. This allows us to avoid unnecessarily frustrating or deterring new users.

One could easily stick to the conspiracy theory that someone here is trying to boycott the project....  ;-)

**Comment by rsoika** [comment]
Also #334  is related to the overall situation of microprofile.io

**Comment by aeiras** [comment]
@rsoika did you read the forum thread: https://groups.google.com/forum/?pli=1#!topic/microprofile/7xEB4PO9Zqs yet?

Work in progress!

**Comment by rsoika** [comment]
Thank you for the link.

**Comment by aeiras** [comment]
Hola @rsoika, 

I will close this ticket based on your follow up. I hope you are able to provide help on the current work being tackled with the website. See you in that thread.

**Comment by rsoika** [comment]
There are still server errors if I click through the projects:

![image](https://user-images.githubusercontent.com/1339124/104780489-2f3f3000-5781-11eb-891a-d64c2c694c7a.png)


I wonder why this is not recognized by someone else.

Just to point it out once again: The website https://microprofile.io/ is not working since more than 6 months 
Maybe that this error is only reproduceable from Europe and did not occur in the states?

Try to click through all projects in short time - There is still a very have server problem as you can see in the screenshot

**Comment by aeiras** [comment]
I deeply appreciate your follow up on the thread Ralph!

The Project page is going to be re-done. See you in the forum:)

**Comment by rsoika** [comment]
One again I would like to point out that the microprofile pages are mostly broken. If you look at this page: https://microprofile.io/project/eclipse/microprofile-config/spec/src/main/asciidoc/configexamples.asciidoc
it looks awful. The asciidoc behind this page fine. See here: https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc

As I mentioned in the past think its a template problem with inline code caused by the web site generator behind that site. 

Can someone reopen the issue?

**Comment by Emily-Jiang** [comment]
Thank you @rsoika for following up with us! We need to fix this pages as soon as possible. I'll put this on the marketing agenda to have this discussed further on 31st Jan. @rsoika [here](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=GMT) is the calendar if you would like to attend the call.

**Comment by rsoika** [comment]
@Emily-Jiang yes, I will join the 'Marketing call'

**Comment by rsoika** [comment]
Hello @aeiras,
in yesterdays marketing call you were not able to hear me. I am sorry about that. So let me explain it:

I ask you all to go on [microprofile.io](https://microprofile.io/) and then click on big technology buttons like "metrics 4.0" or "health". 

![image](https://user-images.githubusercontent.com/1339124/151929350-89429654-6dda-4baf-b3c8-be0a54209ac1.png)

How is such information supposed to help someone decide whether Microprofile is the right technology? @Emily-Jiang has written a whole book about microprofiles. Can't you put a short explanation about the technologies there instead of linking to the Github release pages?

Please - I just want to help to improve the project. @aeiras please put yourself in the position of a project manager read the information about the Microprofile technologies and try to understand it -  It is impossible!

I am not a fan of spring, but if you do not understand what I am talking about, do the same on this page: https://spring.io/

I also suggest to remove the [project section[(https://microprofile.io/projects/) completely. It does not improve the project form a marketing perspective.

**Comment by rsoika** [comment]
Here is my suggestion for the Metrics section

# Metrics 4.0
Metrics 4.0 gives you a great way to monitor your runntime and your application. Microprofile 4.0 is collecting custom metrics and provides them in the common prometheus format. This makes it easy to visualize and monitor any kind of application parameters. Also it allows you to setup a alerting with the help of Grafana in just a view minutes. 

![image](https://user-images.githubusercontent.com/1339124/151933886-0ab77c4b-3e03-4a09-93c9-c26ac683fa71.png)


To add your own metrics within your project you can use the Microprofile MetricRegistry:

```java
@ApplicationScoped
public class MetricService {
	@Inject
	@RegistryType(type = MetricRegistry.Type.APPLICATION)
	MetricRegistry metricRegistry;
	
	public void onExportEvent(exportEvent) {
		// build a counter metric
		Metadata metadata = Metadata.builder().withName("my-metric")
			.withDescription("Invoice Export").withType(MetricType.COUNTER).build();
		List<Tag> tags = new ArrayList<Tag>();
		tags.add(new Tag("method", "export"));
		tags.add(new Tag("mandant", exportEvent.mandantID));
		Counter counter = metricRegistry.counter(metadata,  tags.toArray(new Tag[tags.size()]));
		counter.inc(exportEvent.count);
	}
}
```

**Comment by Emily-Jiang** [comment]
@rsoika let's discuss [here](https://github.com/microprofile/microprofile-site/issues/97).

**Comment by aeiras** [comment]
> Here is my suggestion for the Metrics section
> 
> # Metrics 4.0
> Metrics 4.0 gives you a great way to monitor your runntime and your application. Microprofile 4.0 is collecting custom metrics and provides them in the common prometheus format. This makes it easy to visualize and monitor any kind of application parameters. Also it allows you to setup a alerting with the help of Grafana in just a view minutes.
> 
> ![image](https://user-images.githubusercontent.com/1339124/151933886-0ab77c4b-3e03-4a09-93c9-c26ac683fa71.png)
> 
> To add your own metrics within your project you can use the Microprofile MetricRegistry:
> 
> ```java
> @ApplicationScoped
> public class MetricService {
> 	@Inject
> 	@RegistryType(type = MetricRegistry.Type.APPLICATION)
> 	MetricRegistry metricRegistry;
> 	
> 	public void onExportEvent(exportEvent) {
> 		// build a counter metric
> 		Metadata metadata = Metadata.builder().withName("my-metric")
> 			.withDescription("Invoice Export").withType(MetricType.COUNTER).build();
> 		List<Tag> tags = new ArrayList<Tag>();
> 		tags.add(new Tag("method", "export"));
> 		tags.add(new Tag("mandant", exportEvent.mandantID));
> 		Counter counter = metricRegistry.counter(metadata,  tags.toArray(new Tag[tags.size()]));
> 		counter.inc(exportEvent.count);
> 	}
> }
> ```

Thank you, Emily for transferring the ticket to the WG repo. 

@rsoika, 

I hope you continue joining the Marketing hangouts in the future. 

I think you wish for MP Specs to have more description, based on your wonderful example. If that is the case, please submit PRs directly to each repo with your write-ups. 
That write ought to be found in the Repo for each spec.  

I hope we continue to join us on the new ticket. This one is closing because any adjustments that deal with Specs require front-end and back-end work, not marketing.
