### ISSUE TITLE
[EclipseCon 2020] Community Day MicroProfile Current and Future

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#343]
@emilyfhjiang will be presenting @MicroProfileIO
 #current #future @EclipseCon
 #communityday today at 3:15pm CET. Check out the blog from @Reza_rahman
 on how to register and the whole day programme https://hubs.la/H0xLsNN0! Hope to see you online! #freeevent

**Comment by rstjames** [comment]
Join @emilyfhjiang TODAY @EclipseCon for a great presentation on "#MicroProfile current future" for #CommunityDay at 3:15 CET. Check out the blog from @reza_rahman on how to register & enjoy a free whole day program. hubs.la/H0xLsNN0! Hope to see you online! #opensource
![MicroProfile-eclipsecon-EmilyJiang](https://user-images.githubusercontent.com/12132146/96440457-487b2380-1208-11eb-8d8e-6e01d6aa4d6e.png)
