### ISSUE TITLE
[EclipseCon 2020] Secure Microservices made easy with Eclipse MicroProfile JWT

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#344]
@emilyfhjiang will be presenting @EclipseCon 2020 21st October Wednesday @MicroProfileIO #jwt at 1:30pm-2:00pm CET. Don't miss out this free event! Register now using this link https://www.eclipsecon.org/2020/registration

**Comment by rstjames** [comment]
Join @emilyfhjiang @EclipseCon Wednesday, October 21st at 1:30-2:00 CET for a great session on "MicroProfile #jwt". Don't miss out on this free event! Register now using this link https://www.eclipsecon.org/2020/registration

#opensource #Oss 
![MicroProfile-eclipsecon-EmilyJiang-october21st](https://user-images.githubusercontent.com/12132146/96441295-95132e80-1209-11eb-9b69-6367b1abba38.png)
