### ISSUE TITLE
[Edwin Derks] Submission of Committer Quote

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#346]
**Testimonial:**
Since June 2018, I have been contributing to MicroProfile, increasingly providing input over time. MicroProfile contributing has helped me grow as a software professional, using open-source software and learning the mechanics behind it. Additionally, I love to work with the amazing people behind MicroProfle that mentor me in this project, where we do serious stuff with a casual touch.

**Name:** Edwin Derks
**Title:** Software Architect
**Twitter:** @edwinderks
**Bio/blog:** https://www.cloudnativesolutions.guru/
**Github:** @ederks85
**Photo:** https://nl.gravatar.com/userimage/91524624/c5926bc1cc8c10e0538c6632df0b0d5a.png?size=200

**Comment by aeiras** [comment]
You are fantastic Edwin! :) 

59 words, yeayy! Please see, adjust or approve the small edits below. Your quote will be moved for import to[ Quotes Excel](https://docs.google.com/spreadsheets/d/1nsNCrv9NCRVDm9BDxQELnIZair3d75LJsyEAl9cGAJs/edit#gid=0) once the review is completed!

_Since June 2018, I have been contributing to MicroProfile, increasingly providing input over time. MicroProfile contributing has helped me grow as a software professional, using open-source software and learning the mechanics behind it. Additionally, I love to work with the amazing people behind MicroProfle that mentor me in this project, where we do serious stuff with a casual touch._

**Comment by aeiras** [comment]
Also, which media link do you prefer to be linked to the quote?

- Twitter or

- Bio/blog?

**Comment by ederks85** [comment]
Twitter is preferred. I will have a look at the rest later.

Edwin

**Comment by ederks85** [comment]
@aeiras I have accepted your suggestions, the quote should be final now.

**Comment by aeiras** [comment]
Fantastic Edwin! 

Your MPWG committer quote has been imported to the excel sheet for processing :) https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit#gid=1946347003

**Comment by aeiras** [comment]
Ryan is adding your quote today! :) 

closing this ticket!
