### ISSUE TITLE
[John Clingan] Submission of committer quote

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#348]
Quote:

_I have been participating in the MicroProfile community since day one, and the entire experience has been remarkable, with measurable industry impact. I enjoy the community engagement, whether writing specifications, providing feedback, marketing, learning, sharing, or presenting at various industry conferences and user groups. I highly recommend those interested in MicroProfile to join the community and enjoy the camaraderie._

**Name:** John Clingan
**Title:** Senior Principal Product Manager
**Twitter:** @jclingan
**Bio:** https://www.linkedin.com/in/jclingan/
**Github:** @jclingan
Photo: Attached. 
![John-MicroProfile](https://user-images.githubusercontent.com/73075/97906935-5301e680-1cf9-11eb-9034-ab80236db424.png)

**Comment by aeiras** [comment]
John, 

59 words and beautifully written with no suggested corrections :) 

Added for processing to https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit#gid=1946347003 :)

**Comment by jclingan** [comment]
Grammarly :-)

**Comment by aeiras** [comment]
Ryan is adding your quote today! :) 

closing this ticket!
