### ISSUE TITLE
[MPWG Members Logo required] IBM  

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#350]
Please drop it in the MPWG folder: https://drive.google.com/drive/u/0/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk

**Comment by aeiras** [comment]
@kwsutter & @Emily-Jiang, 

IBM is missing the logo, can you please drop the versions into the folder above? Thanks!

**Comment by Emily-Jiang** [comment]
Thank you @aeiras for chasing up! We will provide the required logos as soon as possible.

**Comment by Emily-Jiang** [comment]
@aeiras IBM logo is already on the microprofile.io website. Why is IBM logo still required?

**Comment by aeiras** [comment]
logos are required for the website and future MPWG swag. :)
