### ISSUE TITLE
[MP Session Slides]  Presenters' support

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#356]
MP has had through out the years a few slides but they have been deleted from the drive. 

New slides need to be created and added under the MP Branding resources [page](https://microprofile.io/resources/branding/)

**Comment by Emily-Jiang** [comment]
@rstjames please create one slide to display all logos from WG members. Ideally, if it is colorful, it will be awesome. Should we make the logos displayed all the time instead of rotating on [this](https://microprofile.io/workinggroup/) page?

**Comment by rstjames** [comment]
@aeiras @Emily-Jiang 
Here is the first draft of the presentation template. I tried to get a lot of different layouts and at the end a bunch of logos,  colors, fonts, and icons for people to be able to copy and paste. Thoughts?

https://docs.google.com/presentation/d/1YNyhYRAhybpSoPAEm__sQ_zNKrUHKQi87G0j5e7GiWc/edit?usp=sharing

**Comment by aeiras** [comment]
@rstjames the link provided brings me nowhere. Can you please update it to enable review?
Gracias Triber!

**Comment by aeiras** [comment]
Ryan, thanks for adding me to the document itself, I was able to access the [document](https://docs.google.com/presentation/d/1YNyhYRAhybpSoPAEm__sQ_zNKrUHKQi87G0j5e7GiWc/edit?ts=60510477#slide=id.g8a4d35d590_0_305) via that invite.

**Comment by aeiras** [comment]
@rstjames, 

Really good draft Ryan. Your work is deeply thoughtful to the MP Speaker with the extra support on pages that will facilitate a fun presentation, just amazing!

**Feedback:**

- Using the work we did for the JakartaONE [Slides](https://github.com/jakartaee/collateral/issues/31) lets add the speaker information to each page, right bottom side.
- The MP logo seems too small and located only on the left bottom side. I think switching between Upper right and lower left  could improve its visibly.  Also increasing the logo size is recommended.  
- There is an issue with the MPWG Members logo. The size of some logos is too large or too small, it doesn't match. 

Great start.

**Comment by rstjames** [comment]
new link: changes location.
https://docs.google.com/presentation/d/1YNyhYRAhybpSoPAEm__sQ_zNKrUHKQi87G0j5e7GiWc/edit?usp=sharing

**Comment by aeiras** [comment]
Ryan, 

We need to update the TM to R, Registered mark across all MP, including the slides. 
I will submit a ticket b/c that task will take time. :)

**Comment by Emily-Jiang** [comment]
The template looks great with just one minor comment: is it possible to make the WG logos colorful?

**Comment by aeiras** [comment]
on the first page, can we add the full tag line of the MP trademark as posted in the landing page of [MP.io. ](https://microprofile.io) 
Either: 

- MicroProfile 
Optimizing Enterprise Java or

<img width="362" alt="image" src="https://user-images.githubusercontent.com/10731224/111546725-5a201300-8735-11eb-8b80-ee75e900c7b2.png">

- MicroProfile Optimizing Enterprise Java for a Microservices Architecture. 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/10731224/111546753-6310e480-8735-11eb-9bab-237cfecb898e.png">

**Comment by rstjames** [comment]
@Emily-Jiang the link for all logos is on that same page.

**Comment by rstjames** [comment]
@aeiras "on the first page, can we add the full tag line of the MP trademark as posted in the landing page of MP.io."

This will be changed every time the presenter's session title. So no point to put a tagline.

**Comment by rstjames** [comment]
The presentation has been updated and tweaked. Have some concerns about putting the working group member's logos in the presentation because I do not want the overhead of updating the presentation every time we get a new member. I would like to remove this section. And if people want the logos they can go the drive or copy-paste it off the website.

**Comment by aeiras** [comment]
@rstjames I have to agree with you on the Members page. It is not scalable nor worthy of up keep b/c it will likely cause issues and delays later. 

If there a way for you to help place in the resources page drive the downloaded Member's logo in black and white instead?
What could we do to help speakers get the logos in the right size and color format?

If you have recommendations, please share. Thanks for the feedback. Looking forward to checking the revised slides a bit later.

**Comment by Emily-Jiang** [comment]
As for the logos, I think black white version is problematic as it is not visible on a white background. Can we have a colour version as well as the black white version, if possible?

**Comment by rstjames** [comment]
@Emily-Jiang @aeiras I collected all WG member's logos in color + white and added them to their folders on the [drive](https://drive.google.com/drive/u/1/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk). Plus added a link on slide 28

**Comment by aeiras** [comment]
Ryan, the updates to the slides have improved it, good stuff! 

I have added the show and tell item for you to show it on Monday. 

It

**Comment by aeiras** [comment]
@rstjames, is there anything missing on this task? Ticket is still open. :)

**Comment by rstjames** [comment]
Nope. closing it @aeiras  :)
