### ISSUE TITLE
[jLove session] Secure microservices made easy with MicroProfile JWT

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#358]
Join @emilyfhjiang #JavaChampion @IBMDeveloper  @jloveconf Friday, 4th Dec at 17:45-18:30 CET for a great session on @MicroProfileIO  #jwt #microservices. Don't miss out on this free event! 
Register here https://www.eventbrite.com/e/jlove-conference-for-java-developers-tickets-124363473497 for this Free conference 4-5 December! #java #free

**Comment by rstjames** [comment]
![MicroProfile-jwt-microservices-emilyJiang](https://user-images.githubusercontent.com/12132146/100370136-2003f780-3006-11eb-9e6e-84525c6f9b04.png)

all good to go
