### ISSUE TITLE
[JakartaOne Livestream] MicroProfile Current and Future

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#359]
Join @emilyfhjiang #JavaChampion @IBMDeveloper  @JakartaOneConf Tuesday, 8th Dec at 7 am PT / 10 am ET / 16:00 CET for a great session on @MicroProfileIO  #current #future #MP4.0. Register here https://www.crowdcast.io/e/jakartaonelivestream_dec8/register for this #free conference 8 Dec!

**Comment by rstjames** [comment]
![MicroProfile-future4 0-jakartaone-EmilyJiang](https://user-images.githubusercontent.com/12132146/100370101-11b5db80-3006-11eb-8d78-fd2aaf6edc26.png)
all set to go.
