### ISSUE TITLE
New Blog Post - MicroProfile Health Check 

### ISSUE THREAD

**Issue by cicekhayri** [microprofile/microprofile-marketing#36]
Hi everyone, I added a new blog post on microprofile.io could you please review

**Comment by Anurag870** [comment]
@cicekhayri Could you please post link to the blog as well.

**Comment by cicekhayri** [comment]
Sorry, here is the link https://microprofile.io/wp-admin/post.php?post=6152&action=edit

**Comment by aeiras** [comment]
@cicekhayri pubished!!! :)

**Comment by cicekhayri** [comment]
Thanks @aeiras :)
