### ISSUE TITLE
[JakartaOne Livestream] What We Learned from Porting PiggyMetrics from Spring Boot to MicroProfile

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#360]
Join @emilyfhjiang @edburns  #JavaChampion @JakartaOneConf Tuesday, 8th Dec at 12 am PT / 3 pm ET / 21:00 CET for a great session "What We Learned from Porting PiggyMetrics from Spring Boot to MicroProfile" Register here https://www.crowdcast.io/e/jakartaonelivestream_dec8/register

**Comment by rstjames** [comment]
![MicroProfile-jakartaone-emilyjiang](https://user-images.githubusercontent.com/12132146/100370196-37db7b80-3006-11eb-82b5-24631feca5a3.png)
good to go

**Comment by Emily-Jiang** [comment]
@rstjames can you also mention Edward Burns from Microsoft as this is a joint talk.

**Comment by rstjames** [comment]
@Emily-Jiang good catch. Updated it :) 
![MicroProfile- What We Learned from Porting PiggyMetrics from Spring Boot to MicroProfile-jakartaone](https://user-images.githubusercontent.com/12132146/100611501-b63f6280-3311-11eb-87c3-e0ffa7e5da9b.png)

**Comment by Emily-Jiang** [comment]
Thank you @rstjames ! This is awesome!
