### ISSUE TITLE
Emily Jiang - committer quote

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#361]
I have been working in the MicroProfile community from the beginning, working on MicroProfile Config and then Fault Tolerance, and other specrifications. I thoroughly enjoyed the interaction with other contributors from different companies and individuals. The experience of helping others and being helped was amazing! I enjoy the technical discussions, project management, presenting at various conferences. It is a great fun! I hope you can join us and make MicroProfile a big success in Cloud Native space. Emily Jiang - MPWG Committee

**Comment by aeiras** [comment]
Nice Emily, 

I was glad to review your quote today, it made me smile!  Now, the word count was 77 which surpasses the 60 recommended.  Please see below a 2nd draft, disregard whatever you see not fitting to your thoughts. 

On your name, it seems to be more powerful is you sign it:  Emily Jiang - MPWG Committer 
The Prospectus uses company and labels, individuals quotes aim at welcoming without bodies, ideally, you speak on YOU- Emily the MicroProfile contributor who became a committer through awesome work. The most powerful signature is that! 

See below and if you adjust or approve, then, I will move it to the excel sheet. Also, please add your pic into this ticket. We need your preferred pic! 
_I have been working with the MicroProfile Community from the beginning. Contributing to MicroProfile Config, Fault Tolerance, and later on other specifications, I have thoroughly enjoyed interacting with independent contributors and different companies. The experience of helping others and being helped on technical discussions, project management, and presenting at various conferences is amazing. I hope you can join us in making MicroProfile a big success in Cloud Native space!_

**Comment by aeiras** [comment]
word count 69

**Comment by Emily-Jiang** [comment]
Thank you @aeiras for the updated version! It looks awesome! I updated only slightly.

_I have been working with the MicroProfile Community from the beginning. Contributing to MicroProfile Config, Fault Tolerance, and later on other specifications, I have thoroughly enjoyed interacting with independent contributors and different companies. The experience of helping others and getting help from others on technical discussions, project management, and presenting at various conferences is amazing. Please join us in making MicroProfile a big success in Cloud Native space!_

Here is my [avatar](https://github.com/account).

**Comment by aeiras** [comment]
Nice work Emily, Ryan is adding your quote today! :) 

closing this ticket!
