### ISSUE TITLE
[MP branding page adding ] from Resources tab item: Mktg drive link

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#362]
How about removing the MP Marketing drive link from the Resources and adding in the Branding page as its own card?

Simplify and keep together stuff. :) 

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/10731224/101862585-853c0a80-3b27-11eb-9a54-3acb61ae692b.png">

**Comment by rstjames** [comment]
@aeiras Makes sense. I made the changes and added new cards to the resource page and branding page

**Comment by aeiras** [comment]
Wonderful 💪🏼
