### ISSUE TITLE
[MPWG Page]  Footer needs to be added to comply with the Foundation Trademark rules

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#367]
Copy/paste from MPWG forum exchange with Sharon- EMO on request as follows:

_We request the MicroProfile.io website be updated as soon as possible to reuse the standard Eclipse website footer.  We are attaching the HTML code to assist you with this effort._ 

-- Note: the HTML cannot be attached to this file, so it has been drop under the MP-Mktg drive:
[HTML file](https://drive.google.com/drive/u/0/folders/16_bZXJ1zHQDnLBHyg4kAn4T3PJL1vFP5)

**Comment by Dexmaster** [comment]
Added via default menu functionality:
![image](https://user-images.githubusercontent.com/6061000/102631400-57be1500-4156-11eb-9c61-97b05e0f7c5a.png)

Is already live on https://microprofile.io/

**Comment by Dexmaster** [comment]
@rstjames / @aeiras please review and close this issue if no changes are needed.

**Comment by rstjames** [comment]
All good. thanks @Dexmaster

**Comment by aeiras** [comment]
Andrii and Ryan, 
You two are amazing and could rule the world of beautiful UX things :) 

-- @rstjames, how about **adjusting** the:
© 2020 MicroProfile is an Eclipse Foundation project running under the Apache License, Version 2.0

**To**

© 2020 the MicroProfile website is powered by MicroProfilers. 

Or similar message, 

Thank you 



Let's adjust the

**Comment by aeiras** [comment]
Andrii, 

© 2020 MicroProfile runs under Apache License, Version 2.0. This website is powered by MicroProfilers.
