### ISSUE TITLE
[Website] call to action: Submit your MP quote - Contributor's page

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#368]
Given the MPWG page, we need a call to action in the Contributors [page](https://microprofile.io/contributors/) & lets add it also into the Quotes section and any other place that is efficient.

The call to action links to [Quote Submision](https://docs.google.com/document/d/1jPdcdlY0WzZ053RjC5q1DiFfVy0UJv4wVzdAFqcPT1Y/edit#)

**Comment by rstjames** [comment]
![Screen Shot 2020-12-18 at 11 52 24 AM](https://user-images.githubusercontent.com/12132146/102606749-8670c700-4127-11eb-9259-00fd80b51270.png)
all set
