### ISSUE TITLE
[MPWG website Page] Add under Knowledge

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#369]
[MPWG- External [MPWG- External](https://drive.google.com/drive/folders/0AOuIrb7SMIlZUk9PVA) 
hosted by the Eclipse Foundation

**Comment by rstjames** [comment]
@aeiras  I added the link but not sure if the text makes sense... Also, I do not have access to the link...

**Comment by aeiras** [comment]
Thanks for adding it, Ryan. 
We have formally requested the EF EMO to make public the MPWG folder kept under the foundation's infra. 
Access will be available sometime in the future. The links should be set now. We only just figured out the "privacy issue" that is not compliant with the MPWG Charter.
