### ISSUE TITLE
[MPWG Page] Add under the Legal section the EF Membership Agreement

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#373]
[Eclipse Foundation Membership Agreement](https://www.eclipse.org/org/documents/eclipse_membership_agreement.pdf)

**Comment by aeiras** [comment]
@rstjames, 

This agreement is missing from legal :) 
Let's add it after the ECA agreement. 

thanks you for adding it!

**Comment by rstjames** [comment]
done
