### ISSUE TITLE
[MPWG tab] Add INFRA access inventory 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#378]
Under the  Knowledge section lets add:
[MicroProfile Admin Access](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=2015643674)

**Write up can be:** 
The listed MicroProfilers are responsible for protecting the MicroProfile infra across its ecosystem.

**Comment by rstjames** [comment]
Added
