### ISSUE TITLE
[jChampion Conference] Easy Peasy Cloud-Native Microservice Development with MicroProfile

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#379]
Join @emilyfhjiang #JavaChampion @IBMDeveloper @JChampionsConf Wednesday, 13th Jan 4:00PM GMT for a great session on @MicroProfileIO "Easy Peasy Cloud-Native Microservice Development with MicroProfile". Don't miss out on this free event!
Register here https://jchampionsconf.com/ for this Free conference 13th, 14th, 18th, 19th Jan! #java #free! 
http://jchampionsconf.com

**Comment by aeiras** [comment]
Hey @Emily-Jiang, 

With the Holiday and returning, this ticket was missed. 
My recommendation when found in a similar situation is to assign a MicroProfiler to the ticket for extra eyes. :) Will close it now.
