### ISSUE TITLE
Update MicroProfile data sheet

### ISSUE THREAD

**Issue by cealsair** [microprofile/microprofile-marketing#38]
Please update data sheet to account for latest 2.2 release. Replace old listing of past releases as follows:
===========
"What does the Eclipse MicroProfile specification consist of?

The current specification consists of a set of application
programming interfaces (APIs) that allows developers to
write and implement microservices in the Java language
using enterprise-grade constructs. Below is a summary
of the APIs  - a full set of all APIs are available at https://microprofile.io:
o MicroProfile 2.2
Open Tracing 1.3, Open API 1.1, Rest Client 1.2, Config 1.3, Fault Tolerance 2.o, Metrics 1,1, JWT Propagation 1.1, Health Check 1.0, plus (edited) 
CDI 2.0, JSON-P 1.1, JAX-RS 2.1, JSON-B 1.0 (Java EE APIs)

Future focus areas for MicroProfile: Long Running Actions,
Reactive Streams, Reactive Events, Data Access, Event Data
=======

Also please add one more link on the right side of data sheet for:
https://github.com/eclipse/microprofile/releases/tag/2.2
=======

Thanks,
Cesar

**Comment by rstjames** [comment]
All updated have been done. 
Can find the files here:
https://drive.google.com/open?id=1KcLMyNXK2HE2fUVli7j8wTugUv0pIpd-

**Comment by cealsair** [comment]
Thank you Ryan for doing this. Closing now.
