### ISSUE TITLE
Typo on API matrix from MP 4.0 blog post

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#381]
Hello everyone.

On the MicrpProfile 4.0 release [Blog post](https://microprofile.io/2020/12/23/microprofile-4-0-is-now-available/)  there is an image with the API included, changed, updated, as always. but this time the JWT Authentication API has a type and says "JET Authetntication"

![image](https://user-images.githubusercontent.com/5105329/104052734-bf90da00-51af-11eb-9be7-39d602626659.png)

This image with typo has been already copied to another posts like [this post on infoQ](https://www.infoq.com/news/2020/12/whats-new-in-microprofile-4/)

Is there a way to replace the image with the typo fixed?

Thanks!

**Comment by aeiras** [comment]
Jorge, 

Great eye, we will fix it next week. Eres divino! :)

**Comment by Emily-Jiang** [comment]
@cajasmota thanks for reporting this! I have fixed it. I've sent an email to Mike, the author of the infoQ blog for him to update the post accordingly.

**Comment by cajasmota** [comment]
Awesome as always @Emily-Jiang !!

Thank you very much!,
I'm going to close this issue. :)
