### ISSUE TITLE
[MPWG Website] Submit your Quote link update to wiki link

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#382]
[Submit Your MP Quote](https://github.com/eclipse/microprofile-marketing/wiki/Quote-Submissions-Guidelines:-MicroProfiler-Testimonials)

The pilot to launch quote submissions was successful with +6 submissions. Wiki link above replaces the word document. 
Thank you for updating the Contributor Call to Action bottom.

**Comment by rstjames** [comment]
updated
