### ISSUE TITLE
MP Branding Page- website update

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#383]
Ryan, 

I have adjusted the name of the folder to MicroProfile Drive https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8

 the section written about the drive needs to drop the word Marketing:  https://microprofile.io/resources/branding/

thanks for being prompt with adjustments

**Comment by rstjames** [comment]
Updated
