### ISSUE TITLE
[MPWG Steering Meetings] Design card for social media

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#384]
Needed.

- Public 
- Recorded Zoom call
- Welcomes everyone
- Open Community, Open Processes
- By Community for Community is true Open-Source

**Comment by secondsun** [comment]
@aeiras What is the best resource to pull logos and our color scheme from?

**Comment by aeiras** [comment]
Hey Summers, 

go to MP Resources page under Branding click https://microprofile.io/resources/branding/

Submit stuff that is missing from that space. There are other tickets with items still being worked on. :)

**Comment by aeiras** [comment]
design inspiration from the Charter

<img width="920" alt="image" src="https://user-images.githubusercontent.com/10731224/109068571-e8f4bf00-76a4-11eb-908b-ead7020f143d.png">

**Comment by rstjames** [comment]
all done
![MicroProfile-Steering-Committee-Call-Oct13](https://user-images.githubusercontent.com/12132146/109685182-4b582e80-7b81-11eb-8427-241cf5173011.png)
![MicroProfile-Steering-Committee-Call-july13](https://user-images.githubusercontent.com/12132146/109685197-501ce280-7b81-11eb-87b6-4588b4a30bc5.png)
![MicroProfile-Steering-Committee-Call-April13](https://user-images.githubusercontent.com/12132146/109685201-50b57900-7b81-11eb-8834-9354acebe8ab.png)
