### ISSUE TITLE
[MPWG Steering Meetings] Scheduled and pushed via twitter

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#385]
Push twice before the meeting: Thursday before and Monday 
- [Agenda minutes](Minutes:https://docs.google.com/document/d/16v3jVkcDzVz9BVU5aGEzPVbK-a8BIx7S1gbqToVUaLs/edit)

- [zoom access]( https://eclipse.zoom.us/j/949859967)

**Time:**

- 11am-12pm PDT

**Schedule:**

1. January 12th 
2. April 13th
3. July 13th
4. Oct 12th

**Comment by aeiras** [comment]
instead of zoom access, let's just add the public calendar access link that will contact theÑ
Zoom, agenda & date, and time.

**Comment by aeiras** [comment]
**Twitter description**
_Join & contribute to the @MicroProfileIO Steering Committee call on 00/00 11 am-12 pm PDT [calendar link], where the  #MPCharter [link] is the baseline for all the decisions. #OpenSource_

#ByCommunityForCommunity 
with 2 links:

- https://www.eclipse.org/org/workinggroups/microprofile-charter.php
- https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles

**Comment by rstjames** [comment]
All set up on tweet deck. 
![MicroProfile-Steering-Committee-Call-Oct13](https://user-images.githubusercontent.com/12132146/109685055-2a8fd900-7b81-11eb-95db-5442de7f8f2c.png)
![MicroProfile-Steering-Committee-Call-july13](https://user-images.githubusercontent.com/12132146/109685078-2ebbf680-7b81-11eb-85b7-d8c2002d5e56.png)
![MicroProfile-Steering-Committee-Call-April13](https://user-images.githubusercontent.com/12132146/109685083-2f548d00-7b81-11eb-893b-554909b381b4.png)

**Comment by aeiras** [comment]
You are fantastic @rstjames! 

Can you please either update row 2 [inventory media schedule ](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0) rows: I, J, K & FB? If you cannot, send the data via this ticket and I could help. 
Ideally, everyonetime a card gets scheduled, the update is tracked via the inventory. Ideally, this is done by anyone who closes the tickets. 

https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

**Comment by rstjames** [comment]
@aeiras I think this is too much overhead to do every time things are sent out...  What will we use all this data for? And who has time to do something with it? Microprofile is a community project and I think we should keep the overhead down as much as possible.

**Comment by aeiras** [comment]
@rstjames, 

What do you think of the data you found in the MP <> MP onabording interview documents for the 4 MicroProfilers who are now linked to [the consecutive media push for 2021](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)? 

Stating the day and how many times a message goes out per month or quarter matters. We can adjust what we choose to track. 
Every single time a process is piloted, we will learn by actions.  
The goal is for the actions to be the example of how stuff was done so that new MicroProfilers can be enabled improve what currently is & rock it without hand-holding. 

Thanks for allowing this follow up,
