### ISSUE TITLE
[MPWG Members Logo required] Payara = Add to MPWG website page 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#386]
https://drive.google.com/drive/u/0/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk

**Comment by rdebusscher** [comment]
Are there any requirements on the logo (transparent background, colors to avoid,  ...) as Payara has several variations depending on the context?

**Comment by aeiras** [comment]
Rudy, 

Drop all the logos you feel are ok into the folder. 
MP swag will use it, digital design will use it. Diversity is very important. 

A mktg members wiki onboarding is being written to help with such a questions-- thanks for the follow up!

**Comment by rdebusscher** [comment]
The logo that I received from Marketing is uploaded in the Drive.

**Comment by rstjames** [comment]
added :)
