### ISSUE TITLE
[MPWG Members Logo required] Oracle = Add to MPWG website page 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#387]
https://drive.google.com/drive/u/0/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk

**Comment by edbratt** [comment]
[Oracle_cmyk_03_91_86_12.zip](https://github.com/eclipse/microprofile-marketing/files/5868538/Oracle_cmyk_03_91_86_12.zip)

SVG with the Oracle corporate logo

**Comment by aeiras** [comment]
Great Ed!

**Comment by rstjames** [comment]
ADDED
