### ISSUE TITLE
[MPWG Prospectus] Design 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#389]
@rstjames, 

Can you make the Prospectus look better? Especially the quotes section needs to use more pages and be aligned differently. 
The colors also need to pay with each other. 

Adjust everything, except content. We are not attached to what currently is. Design is up to creativity to make sure that the consumption of the document is welcoming & soothing. 

Thank you Triber, 

https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit?ts=5eb046ec#slide=id.g6edf059ff0_56_0

**Comment by rstjames** [comment]
@aeiras I cleaned the presentation up. fonts, spacing, and colors. Plus the quotes section. 
Let me know if you want me to push it further. A bit time-consuming doing it in google slides but I can think about other improvements if you want.

**Comment by aeiras** [comment]
Wow, Ryan, it looks already much better! 
Yes, let's invest time improving it  @rstjames.  The Prospectus is the business card of the MPWG, so if there is a way to improve it, always side on that. Thank you! :)

@jclingan, 

Can you please transfer the Prospectus document to the MPWG folder under [Prospectus](https://drive.google.com/drive/folders/1rkkGdOSjDiG68h_y6hNgXjbBpoyZ7i9E)? 
The document cannot & must not be moved to the MP External - EF drive.  It needs to be housed where the marketing contributors have access to it. Thank you, John!

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/426  related ticket to add the Payara's quote to the Prospectus.

**Comment by aeiras** [comment]
@rstjames the latest improvements to the Prospectus look  great. 
I will close this ticket for now. When the document needs to be adjusted, we will open a new ticket under the MPWG repo
