### ISSUE TITLE
[MP Product Plan] Distribute Community Voices Document

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#394]
Distribute the MP Product Plan - Community Voices document via Twitter

Text:
@MicroProfileIO is shaped by the community. Therefore, we would like to hear your voice on what you would like to see happening or included in the evolution of this platform and product. Please add your input to this document (https://bit.ly/391ZXyC) until February 9th, 2021.

**Comment by xstefank** [comment]
@aeiras who can push this tweet? The sooner we will get this out the better :).

**Comment by Emily-Jiang** [comment]
@ederks85 can you tidy up the doc first by removing the questions after the dotted line? @rstjames will you be able to tweet about this?

**Comment by aeiras** [comment]
Fantastic write-up Edwin!

The tweet is live and pinned into the profile https://twitter.com/MicroProfileIO/status/1352366726298497027?s=20  

Really adore our chosen unity MicroProfilers. :) Thank you for being just amazing!
