### ISSUE TITLE
[Eclipse LSP4MP - Language Server for MicroProfile] The wiki description needs updating. 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#395]
Emily, 

You are listed as a mentor and committer of LSP4MP. Can you drop the Eclipse from the name under the project's wiki? https://projects.eclipse.org/projects/technology.lsp4mp

Thank you for being awesome, 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/10731224/105568515-c27ee500-5cee-11eb-88b5-d891c3cc3e5f.png">

**Comment by Emily-Jiang** [comment]
Fixed! Thanks for pointing it out! Check out the new page https://projects.eclipse.org/projects/technology.lsp4mp

**Comment by aeiras** [comment]
Our community is great. That was pointed out to me as well 🤗🥰 abrazos Emily! 💛
