### ISSUE TITLE
Obtain a dedicated MicroProfile Zoom account

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#397]

**Comment by aeiras** [comment]
March 2nd MP forum email sent by Amelia to bring awareness that the MPWG zoom access will provide coverage to all groups who currently are listed under the MP calendar. https://groups.google.com/g/microprofile/c/HXV6iEMI9Mw

**Comment by aeiras** [comment]
@jclingan, 

Do you have an status on the zoom account yet?

**Comment by aeiras** [comment]
the Access to diverse admins starts this week for the mktg and community hangouts :)
