### ISSUE TITLE
 [MP Product Plan] Distribute Community Voices Document Spanish Version

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#398]
In order to achieve a better and wider dissemination of the "2021 MicroProfile Program Plan Community Voices" in our community, I have prepared the Spanish version of Community Voices (twit and document) 

# Tweet Text:
link: https://twitter.com/MicroProfileIO/status/1352366726298497027?s=20

@MicroProfileIO está formado por su comunidad. Contribuye contándonos lo que te gustaría que suceda o se incluya en la evolución de la plataforma y el producto.

Agregando tus comentarios al documento, versión original: (bit.ly/391ZXyC) o la versión en español: (https://docs.google.com/document/d/1R8RGKRad_VocSWWCmEyZesP0QTW1-tofmo4IO-MfcvM/edit?usp=sharing), tienes hasta el 9 de febrero de 2021

_Note: Related to_  #394

# Document Text
Base Document: https://docs.google.com/document/d/1fC3UFXBqrlxDIURJ3ZIUOeGdZELfo1yPOOjyTR5uNkY/edit#heading=h.4lyopu2gbqrg
Spanish Version: https://docs.google.com/document/d/1R8RGKRad_VocSWWCmEyZesP0QTW1-tofmo4IO-MfcvM/edit?usp=sharing

## Plan del Programa MicroProfile 2021 - Voces de la Comunidad

La creación de este documento se debatió en el MicroProfile Live Hangout del 5 de enero, basado en el éxito del documento Jakarta EE Community Voices. Este documento permite la retroalimentación de la comunidad sobre el Plan del programa MicroProfile 2021. El resultado de este documento será una presentación de diapositivas de un plan de alto nivel. 

Este documento está intencionalmente en estilo entrevista y puede ser utilizado por cualquier persona en artículos o publicaciones. El formato de cada respuesta debe ser en forma de "nombre: cita" para que pueda ser citado y acreditado correctamente. Si ve que alguien ya ha expresado una idea similar, le recomendamos que la repita con sus propias palabras, ya que ayuda a mostrar prevalencia y una mayor voluntad de la comunidad. 

La FECHA LÍMITE para recibir comentarios es el 9 de febrero de 2021. 

Todas las contribuciones a este documento están bajo la licencia pública de Eclipse v2 https://www.eclipse.org/legal/epl-2.0/ Objetivos prioritarios:

**Comment by aeiras** [comment]
Emerson, your actions are wonderful. 


Request: Can you move the document to the MP Community drive?  Currently the document is not Public Edit, we cannot push it as it is.  Cheers 

**Adjusted the tweet:** 
@MicroProfileIO está formado por su comunidad. Cuéntanos lo que te gustaría que suceda o se incluya en la evolución de la plataforma y el producto.
Agregando tus comentarios hasta el 2/9, versión original: (bit.ly/391ZXyC) o la versión en español: (bit.ly/2MOSKsM)

**Comment by aeiras** [comment]
@emecas,

The MP tweet is live and pinned in the profile. :) 
How do you feel about owning the update directly via the MP Community forum, adding the git issue and the tweet to that short message?  
Stay safe and wonderful!  

https://twitter.com/MicroProfileIO/status/1356708251358781442?s=20

**Comment by emecas** [comment]
> How do you feel about owning the update directly via the MP Community forum, adding the git issue and the tweet to that short message? 

@aeiras 
I can do it, but I'm not 100% sure if you meant this same git issue, I guess you do, please confirm and I'll take care of it

**Comment by aeiras** [comment]
It means you use the link of this git issue to show how stuff got done after you nicely translated the document. 
Without this issue, there wouldn't be a tweet :) Process & communication that works

**Comment by emecas** [comment]
Done!!
https://groups.google.com/g/microprofile/c/76ovzalPksg/m/KKgInNkQAAAJ

**Comment by aeiras** [comment]
Emerson, your actions have inspired me to start the write-up **tonight** on needed MP documentation. Thank you!

**Comment by emecas** [comment]
Great :), What is that documentation work in pending about? Is there something I can help on ? Somewhere a [draft] plan?

**Comment by aeiras** [comment]
Your help could be wonderful Emerson. Do help!

I actually included in yesterday msg via bcc since you are always candid and when possible able to help. https://groups.google.com/g/microprofile-marketing/c/Wzxn2hDUHDQ (Feb 3rd update)

Check the Responsabilities document created this week, the part on tasks lists to diverse activities. Other brains need to check what could be improve across the documentation. PRs are the it! 

I have volunteered to write the documentation for:

-  Mktg onboarding wiki (MPwG repo housed) which already started by populating other docs. I will use Community MPWG public edit drive, if you feel like, you could contribute to that before it is moved to the repo. 
- Committers onboarding wiki (MPWG housed) which already started with the diverse documentation we have all over. Also will use the public edit drive to do that work before moving it to git to welcome PRs. 

+ more

**Comment by emecas** [comment]
Thanks, @aeiras  meanwhile I have added #399 to keep working on this line

**Comment by aeiras** [comment]
just beautiful Emerson. Please add items to tomorrow's agenda. 
There are 3 topics tmw and tmw closes the loop to gather feedback before diving into the content :) you Rock!
