### ISSUE TITLE
[MP Product Plan]  2021 MicroProfile Program Plan Slide Deck -  Spanish Version

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#399]
Make available: **_2021 MicroProfile Program Plan Slide Deck_**:

https://docs.google.com/presentation/d/1-mu4dIsfAzLlE81splWBKwsGeRLJhzEWrXgsQ_i0JZQ/edit#slide=id.gb4cf2bb036_0_0

WIP here:
https://docs.google.com/presentation/d/15VlF895lpclxdvv1HlRD3hNxi0R2YexQ3MguqB4arH0/edit#slide=id.p

**Comment by emecas** [comment]
A First Draft:
https://docs.google.com/presentation/d/1-OrSEgEeU39OIxmlXZd1suMQEKJRmjbUzqIO2OyZC2g/edit?usp=sharing

**Comment by aeiras** [comment]
@emecas, 

Just beautiful. 
Emerson, can you please add in the notes of page 2, first thing, Translated by Emerson? 
It is view only so I cannot help with review nor adding such suggestions.

**Comment by emecas** [comment]
@aeiras, I thought it was accessible, I've update permissions and moved it to the Community folder, so you can review / edit. thx

**Comment by aeiras** [comment]
It works Emerson. 
I added you and will provide extra eyes after the program has been approved. :) 
So fun!

**Comment by aeiras** [comment]
Hola @emecas, 

We ought to finalize the Spanish translation so that it can be added to the MPWG page in the website. 
How much time do you think MicroProfilers need to collaborate on the review?  2 weeks from next Monday? 
Whats your preference?

**Comment by emecas** [comment]
@aeiras, I have a question, is [this](https://docs.google.com/presentation/d/1-mu4dIsfAzLlE81splWBKwsGeRLJhzEWrXgsQ_i0JZQ/edit#slide=id.gb4cf2bb036_0_0) the final version of the document?

I'm asking because my impression based on the last 2 meetings has been that it could get some changes, but it is also true that the strategic goals are described in a high level to keep them intact,  anyways, I will give another round to the [first translation  draft](https://docs.google.com/presentation/d/1-OrSEgEeU39OIxmlXZd1suMQEKJRmjbUzqIO2OyZC2g/edit?usp=sharing) before our next meeting. And Yes, I think  2 weeks after that are more than enough for reviewing it

**Comment by aeiras** [comment]
Dias Emerson, 

Yes, that is the voted and approved final version that we need to use to also finalize your wonderful document.

**Comment by emecas** [comment]
> 
> 
> Dias Emerson,
> 
> Yes, that is the voted and approved final version that we need to use to also finalize your wonderful document.

Done @aeiras , I finished final adjustments for the [Spanish translation](https://docs.google.com/presentation/d/1-OrSEgEeU39OIxmlXZd1suMQEKJRmjbUzqIO2OyZC2g/edit#slide=id.gbe60ace8dc_0_0) for the 2021 MicroProfile Program Plan Slide Deck, How do you think we should handle/invite to the review?

**Comment by aeiras** [comment]
Hola Emerson, 

If I were you, I would send a new thread to the MP general forum with 1 to max 2 sentences that include the link of this ticket and the slides' link. It includes the March 29th welcome feedback deadline and makes it a call to action to all Spanish-speaking MicroProfilers in the forum. I would write that short message and the title of the email in Spanish, not 1 word in English. 

However, you can and ought to always do whatever you feel/think you can own (your contributor signature is yours to bear) to help close the amazing contribution you are making possible. 
You are likely to inspire other MicroProfilers to translate the slides as well. Let's see.

**Comment by aeiras** [comment]
Oh and I will help you with the review. You have 1 helper already :) But I won't re-start until you choose how to push the close up.

**Comment by emecas** [comment]
> 
> 
> Oh and I will help you with the review. You have 1 helper already :) But I won't re-start until you choose how to push the close up.

Thank you @aeiras for the suggestion, here is the new thread: https://groups.google.com/g/microprofile/c/hCBSh-CdDnI

**Comment by aeiras** [comment]
So wonderful. I have scheduled to work on it this week, Emerson. Thanks for making it possible.

**Comment by cesarhernandezgt** [comment]
Hi @emecas 
I did the first review of the current status of the slides and applied a couple of updates.
I left a couple of comments too.

**Comment by emecas** [comment]
> 
> 
> Hi @emecas
> I did the first review of the current status of the slides and applied a couple of updates.
> I left a couple of comments too.

Thank you @cesarhernandezgt , I just noticed the document where you added comments is not the latest one, be sure using this one: https://docs.google.com/presentation/d/1-OrSEgEeU39OIxmlXZd1suMQEKJRmjbUzqIO2OyZC2g/edit#slide=id.gbe60ace8dc_0_69

**Comment by cesarhernandezgt** [comment]
Thanks for the new references @emecas, I just move my feedback to the new document. Since Google slides don't have "suggestion" mode like Docs has, the only way to see my changes is by selecting the history of the slides.

**Comment by aeiras** [comment]
@emecas, 

I have fun re-reading the slides. Like @cesarhernandezgt stated, there is no way to "suggest edit" on google slides, so I modify a few words. The current draft has greatly improved. You are just wow! 

With this task, you have helped us improved the original slides in a few sections like Duke's logo, bookmarks with trademark, tracking on approval of the original document, etc. 

Thank you for being so fun on lowering the bar so that the Latin Armada can join and contribute to MP. :)

**Comment by mehmandarov** [comment]
I am getting "You need access" message now, is this intentional, @emecas?

**Comment by emecas** [comment]
> 
> 
> I am getting "You need access" message now, is this intentional, @emecas?

@mehmandarov  No intentional at all, Thank you for letting me know,  it seems it is a problem with the permissions, meanwhile may you try this link: https://docs.google.com/presentation/d/e/2PACX-1vQA322Lkoxs10BUCWfNFituhpSUoMCb2adBw-fk1cz13_dFqDLvw49_RvYpDVtvLq_4qQqWDyxj01Jl/pub?start=false&loop=false&delayms=3000

This is another format: https://drive.google.com/file/d/1_zLvW57P6sKMknI5fHFj0lyPD4qRoIwT/view

**Comment by mehmandarov** [comment]
Thank you! These links work!

**Comment by emecas** [comment]
Final folder: https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C 
PDF: https://drive.google.com/file/d/1ENJIhBRnrJMQuBiSY1mNw-iX1EY_9PNj/view?usp=sharing
