### ISSUE TITLE
[DevNexus 2021] MicroProfile for Dummies

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#401]
Join @emilyfhjiang #JavaChampion @IBMDeveloper @devnexus  Wednesday, 17th Feb at 11:25-11:55 EST for a great session on #easypeasy @MicroProfileIO with a live demo! Don't miss out on this free event!
Register here https://devnexus.com/  #java #free

**Comment by rstjames** [comment]
sent out.

**Comment by Emily-Jiang** [comment]
Thank you @rstjames! Very much appreciated!
