### ISSUE TITLE
[Trademarks] MicroProfile Brand HandBook Slides

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#404]
[Slides](https://docs.google.com/document/d/1v7Chteluh4KrzLjFTCPLwvGccUpeKpcnQYzPiEjJQBU/edit)

**Comment by rstjames** [comment]
I'll deal with this. Think it's better when it's a downloadable pdf or a page on the website.

**Comment by aeiras** [comment]
I thought so too. 
First, we need to get the Trademark guidelines written to be approved by the Steering committee. 
The conversation needs to happen to show them what we have. 
If you have the bandwidth to use the document to create the book, even though we lack the actual trademark logos, that would be great Ryan. 
You have helped compiled the MP colors, fonts, etc already in the website. 

See the MP Folder that contains the example we worked on when creating the Jakarta EE handbook. 

[MP Trademarks](https://drive.google.com/drive/u/0/folders/1wbn8mUPTjQMpHYuzh1swwPCBnuS7rg3o)  Links included into the document.
