### ISSUE TITLE
[Quotes Template- design] Use when sharing the Word in the Street about MP

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#406]

**Comment by aeiras** [comment]
Whats the word count to push current quotes via twitter? @rstjames

**Comment by rstjames** [comment]
@aeiras what do you mean?  Twitter character limits are 280... We need to have a message Twitter template that starts the tweet and ends it with a link.

**Comment by rstjames** [comment]
![microprofile-quote-2021](https://user-images.githubusercontent.com/12132146/112835399-832b9680-9099-11eb-80ac-46835ebb6ec1.png)

**Comment by aeiras** [comment]
Ryan, 
can you please provide the customized link of the working group page, short link here? 

I need the exact link to complete the export of the current quotes — exact length. Thank you!

**Comment by rstjames** [comment]
Please test it: @aeiras 

http://bit.ly/mp-wg

**Comment by aeiras** [comment]
- 

- #TheWordOnTheStreet: "We've seen a successful & rapid pace of innovation and look forward to this continuing, with priorities established by a community & multiple open implementations and integrations providing developer choice." - @ian__robinson #IBM

http://bit.ly/mp-wg

- #TheWordOnTheStreet: "Through rapid, incremental evolution of specifications, #MicroProfile matches the pace of microservice evolution while enabling developer productivity and investment protection through common APIs..." - @nmcl @RedHat 

http://bit.ly/mp-wg

#OpenSource

- #TheWordOnTheStreet: The💛@MicroProfileIO "initiative helps develop and run #Java applications in an easy, scalable, and resilient way using dynamic cloud environments."- @siruslan @Jelastic 

http://bit.ly/mp-wg

#ByCommunityForCommunity #OpenSource

- #TheWordOnTheStreet: "The manner in which open discussions inform the direction of @MicroProfileIO  should be a standard that all #OSS efforts, whether they are stewarded by a foundation or not, should hope to live up to.”- @vincentmayers @atlantajug 

http://bit.ly/mp-wg

- #TheWordOnTheStreet about💛@MicroProfileIO: "The experience of helping others and getting help from others on technical discussions, project management, and presenting at various conferences is amazing." -@emilyfhjiang #IBM

Read more: http://bit.ly/mp-wg

- #TheWordOnTheStreet about💛@MicroProfileIO: "I value #MicroProfile open-collaboration, community building while having fun with the great people working on it." - @brunobat_ 

Read more http://bit.ly/mp-wg

#ByCommunityForCommunity #OpenSource

- #TheWordOnTheStreet about💛@MicroProfileIO: "I enjoy the community engagement, whether writing specifications, providing feedback, marketing, learning, sharing, or presenting at various industry conferences and user groups." - @jclingan @RedHat 

Read more http://bit.ly/mp-wg

- #TheWordOnTheStreet: "#MicroProfile is the critically needed compliment to initiatives like @JakartaEE, allowing innovation to be pursued quickly at the edge in a first-to-market fashion..." - @dblevins @tomitribe 

Learn more: http://bit.ly/mp-wg

#ByCommunityForCommunity

- #TheWordOnTheStreet about💛@MicroProfileIO: "MicroProfile contributing has helped me grow as a software professional, using open-source software and learning the mechanics behind it." -@edwinderks 

Learn more: http://bit.ly/mp-wg

#ByCommunityForCommunity #OpenSource

- #TheWordOnTheStreet: "We believe in the benefits of multi-vendor open standards and are keen to support the experimental and innovative approach in the creation of new open standards for microservice API development." -@l33tj4v4 @Payara_Fish 

Learn more: http://bit.ly/mp-wg

- #TheWordOnTheStreet about💛@MicroProfileIO: "I like the community-driven, effective, and enjoyable approach of creating cloud-native APIs invented by the MicroProfile Community."  -@m0mus #Oracle

Learn more: http://bit.ly/mp-wg

#ByCommunityForCommunity #OpenSource

- - #TheWordOnTheStreet about💛@MicroProfileIO: "Earning #MicroProfile authority depends on the contributor. MP’s flat structure welcomes anyone’s participation, no titles, no egos." - @ameliaeiras @tomitribe 

Learn more: http://bit.ly/mp-wg

#ByCommunityForCommunity #OpenSource

**Comment by aeiras** [comment]
@rstjames, 

The link works great. Thanks! 

Every dot is a quote with hashtags & the MPWG link. 

**How about we schedule current quotes and future quotes until the end of Dec 31st, 2022. 2 years.?** 
It is important to broadcast why we do what we do while bringing attention to the MPWG page.  

If we can push each quote 1 per month, (12 messages) that could be great. 
However, every quote needs to get the same number of coverage. We could have multiple quotes go in the same day as well if you consider that viable. I haven't checked twitter deck yet. 

There are 12 quotes total (12 days max per month on quotes for 2yrs). If the MP current media schedule is too heavy, then let's add 2 quotes per day. This media activity needs to scale and welcome other quotes rotation to be integrated.

Brainstorm as you see fit so that the activity is sustainable with what currently is and please pull us in via this ticket or the mktg call if there are issues. Thanks Triber!   

-

**Comment by rstjames** [comment]
@aeiras I think one year is enough. in 2022 can change up the design or maybe someone leaves then we need to find it and take it down.

**Comment by rstjames** [comment]
@aeiras I read you message again. 
"There are 12 quotes total (12 days max per month on quotes for 2yrs). If the MP current media schedule is too heavy, then let's add 2 quotes per day. This media activity needs to scale and welcome other quotes rotation to be integrated."

How often are you wanting to post this?  12 posts a month? I think that is way too much... And will take hours to do...

**Comment by Emily-Jiang** [comment]
@aeiras @rstjames I think 1 per week might make sense.

**Comment by aeiras** [comment]
something like that could work. 
12 quotes, currently... more expected. :) 

that means that your quote @Emily-Jiang, under the current number, will be tweeted every ~12 weeks.
Ryan, would that work? WDYT. 
The most important thing we could push in Media is highlighting the #ossDOERs doing the work. We want many to share why they invest their time in MP. NO other tweet is as important IMO. 

@rstjames, 
As you mention, it takes a lot of time, care, and work to do these tasks. That's why I said 2years in the other ticket, lol : )I swear! 
For now, let's complete it with your help. Let's document what you think is a healthy MP media space for pushing stuff, so that, others with TwitterDeck access can keep that in mind while also onboarding into help on such tasks.

**Comment by aeiras** [comment]
ohh and Ryan, you ought to submit your quote too. :) it is a voluntary action but coming from you who helped created everything there is in MP creative side is amazing!

**Comment by rstjames** [comment]
I really think if the number of quotes will continue to grow. This task is not scalable and we should think of a different way to promote these quotes.

**Comment by aeiras** [comment]
@rstjames, 

Thank you for always keeping rule #1 when collaborating in MicroProfile activities. If it a task is not scalable, we must think harder about the task and discover new solutions. 

I will add this ticket and task to the MP Mktg agenda for discussion on the next call. Thank you, Ryan!

**Comment by aeiras** [comment]
@rstjames lets close this ticket and please create a new ticket on how to make that 1 link of quotes to share via media instead.

**Comment by rstjames** [comment]
@aeiras dont we still want to put this out reminding people to take a look at what people have to say about MP ? 
if so I just need a tweet and I will post it with the visual above and link 
https://microprofile.io/workinggroup/#testimonials

http://bit.ly/mp-testimonials

**Comment by aeiras** [comment]
Wow, did you find a shortcut to push the quotes, @rstjames? 

This ticket was closed and this open which you just closed. https://github.com/eclipse/microprofile-marketing/issues/517

Yes, let's push it for 2021.  Use the spreadsheet to see times, etc. 
You are AMAZING, Ryan!

**Comment by aeiras** [comment]
ticket is open as the other ticket is now closed. 
let me know what else you  need, Ryan!

**Comment by rstjames** [comment]
@aeiras I wrote above if we want to schedule a tweet going out with a standard visual and it links the quote section on the website we can. But not sure what we want to say in the tweet.

**Comment by aeiras** [comment]
@rstjames, 

I missed this call out, apologies Ryan. Here it goes and thanks you!
Please lets schedule the tweet with the quote link you created to be published in the weekends, twice per month. 

Tweet

#AboutMicroProfileVoices check out the diverse community quotes that tell YOU, a potential Adopter & Contributor, why investing your time and resources into the advancement of the @MicroProfileIO technology is a worthy endeavor in the #OpenSource Ecosystem.
