### ISSUE TITLE
[Quotes- Individual Highlight] Media push- Submit your Quote

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#407]
**Twitter message**

_#WordOnTheStreet: Submit your @MicroProfileIO quote and share why you invest your time and resources developing/using the #MicroProfileTechnology._ #OpenSource

[Quote Submissions Guideline](https://github.com/eclipse/microprofile-marketing/wiki/Quote-Submissions-Guidelines:-MicroProfiler-Testimonials)

#ByCommunityForCommunity  #SharingIsCaring

**Comment by rstjames** [comment]
@aeiras 
![microprofile-submit-quote-2021](https://user-images.githubusercontent.com/12132146/112835985-4b711e80-909a-11eb-8c58-2d6027de9a2d.png)

**Comment by rstjames** [comment]
option 2

![microprofile-submit-quote-2021-2](https://user-images.githubusercontent.com/12132146/112848388-5337bf80-90a8-11eb-923b-589ef918dd45.png)

**Comment by aeiras** [comment]
Option 2 rocks, Ryan! 
How about we schedule it for 2yrs?

**Comment by rstjames** [comment]
#WordOnTheStreet: Submit your #MicroProfile quote & share why you invest your time & resources developing/using the #MicroProfileTechnology. http://bit.ly/submit-quote

#ByCommunityForCommunity #SharingIsCaring  #OpenSource #Oss

**Comment by rstjames** [comment]
all set for the year
