### ISSUE TITLE
[MPWG Prospectus Media Push]  Join MP msg

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#408]
**Twitter message**
_#OpenSourceSupporters looking for a healthy & welcoming ecosystem where to invest your time and resources, checkout the @MicroProfileIO Working Group Prospectus that answers why you should consider joining the #MicroProfileCommunity.  _

[MPWG Prospectus ](https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit#slide=id.g6edf059ff0_56_0)

**design template words**

- Contributors
- Users
- Committers
- Guests
- Organizations

**Comment by rstjames** [comment]
@aeiras 
what does this mean? 

design template words
Contributors
Users
Committers
Guests
Organizations

**Comment by aeiras** [comment]
@rstjames,

It means that the design image lists the diverse groups of people who are welcomed to join the project. 

tell me, when I want to add anything to the image, how should I call that action? :) I am used to calling it Design requirements but via this tickets, I don't. What would you like to see?  Thank you!

**Comment by rstjames** [comment]
@aeiras like this? 




![microprofile-prospectus-2021](https://user-images.githubusercontent.com/12132146/110492481-8531b380-80f2-11eb-8f99-55d7531ab660.png)

**Comment by aeiras** [comment]
Really cool, Ryan! 

I can see that the word Organizations is larger. Can you increase the font in other words as well? 
It looks simple, clean & to the point. You rock!

**Comment by rstjames** [comment]
they are all the same size.

**Comment by rstjames** [comment]
But they all were not the correct font. 
![microprofile-prospectus-call-2021](https://user-images.githubusercontent.com/12132146/110603915-cf18a900-8187-11eb-87ad-55f5ba9024ee.png)

**Comment by rstjames** [comment]
#OpenSourceSupporters looking for a healthy & welcoming ecosystem where to invest your time & resources, check out the #MicroProfile Working Group Prospectus that answers why you should consider joining the #MicroProfileCommunity.
http://bit.ly/mp-prospectus
#opensource #oss

all set to go out twice a month for 2021
