### ISSUE TITLE
[MPWG Charter]  Media Push

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#409]
**Twitter description**

@MicroProfileIO Working Group Charter states that it is the #MicroProfileCommunity, who owns the responsibility to collaborate on & release #OpenSource specifications, promote, evangelize & market #MicroProfile. Learn more:
[Charter](https://www.eclipse.org/org/workinggroups/microprofile-charter.php)

**Design**

let's use the Charter to create template
<img width="861" alt="image" src="https://user-images.githubusercontent.com/10731224/109065549-9c0ee980-76a0-11eb-82e9-1b82ab3a9568.png">

**Comment by aeiras** [comment]
@rstjames, 

My take on this card is that the design needs to have the words in bold as core to the MPWG Charter. 
Let's add 1 extra bold highlight to the design: **ByCommunityForCommunity**

**Comment by aeiras** [comment]
It is similar to the community media push card with the 7 pillars written on the "not safe zone". 
if we could add the actual screen shot of the pillars as shown above that would be even better. 
can you please create something we could look at @rstjames? 
I cannot explain nor draw it, apologies and thank you!

**Comment by rstjames** [comment]
MicroProfile Working Group Charter states that it is the #MicroProfileCommunity, who owns the responsibility to collaborate on & release #OpenSource specifications, promote, evangelize & market #MicroProfile. Learn more: https://bit.ly/3bUh8lN
![microprofile-charter](https://user-images.githubusercontent.com/12132146/110817324-7a128b00-828c-11eb-8e87-41c1f2c6fa1d.png)

**Comment by rstjames** [comment]
All set to go out once a month for 2021

**Comment by aeiras** [comment]
Amazing speed & work, Ryan!
