### ISSUE TITLE
Help fix Gerry Noij's first MP blog

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#41]
Gerry, 

Welcomed to MicroProfile repo! :) 
This is your very own issue, thank you for considering the project and the Contributors worthy of your attention! 

[Blog via Gerry's twitter](https://twitter.com/Sasquatsch66/status/1106175038758309888)

**Comment by Misano9699** [comment]
I have updated my blog to make a clearer distinction between the MicroProfile Platform specification and component specifications. 

[Introduction to Eclipse MicroProfile](https://craftsmen.nl/introduction-to-eclipse-microprofile/)

**Comment by aeiras** [comment]
@Silfen66 fastest turnaround, amazing Gerry! :) 

Are you interested in crossposting that very valuable blog to the MP blog? If yes:

[Blog guidelines](https://microprofile.io/blog/)

Looking forward to formally welcoming you as the newest MP WordPress contributor!!!!

**Comment by kwsutter** [comment]
@Silfen66, Reading through your blog post...  Have a few comments...

- I think you went overboard with your use of "platform" and "specification".  For me, it doesn't read as smoothly as it did before...  For example,

_The Eclipse MicroProfile Platform specification is an open-source community specification for optimizing Enterprise Java for a microservices architecture._

Should read more like this (which I think you pretty much had before)...

_The Eclipse MicroProfile Project is an open-source community for optimizing Enterprise Java for a microservices architecture._

And, now that I continue reading, the use of Specification seems to be overkill in several areas.  And, to be honest, the overuse of the word "specification" will be confusing when people start comparing it to the Jakarta EE Specification process.

And, I'm finding that doing a full review of the article via this github issue is quite difficult.  Any chance you have the article in another github repo or something that would easier commenting?  Google doc?  Something?

Thanks,
Kevin

**Comment by aeiras** [comment]
@kwsutter thank YOU for jumping into the blog and seeing the issues I saw last night upon reading the blog. 
A quick fix is to drop the current blog to word into the MP drive. 

https://docs.google.com/document/d/1V_9s7lXmCErgUOAo3sGqsZaxU9dydJmx4YjfLQ2zOf4/edit  

If Gerry imports blog into MP drive to enable adjustments, you could help with the review easily. That is how we work on content review. The word document is public and anyone has access to edit. 

For me, blog has great potential yet specification is too heavy and condusing. thank you for prioritizing this.

**Comment by Misano9699** [comment]
I have updated the document posted by @aeiras with the contents of the blog. I appreciate the help with making it better. 

I never expected this blog to be picked up by the MicroProfile community and the amount of retweets and likes are way beyond what I expected. Thank you!

**Comment by aeiras** [comment]
@Silfen66 you walkTHEtalk and writethetalk!  Aach MicroProfiler walks it with you, no glamour nor BS. Now you are a MicroProfiler contributor, simply by showing up and owning your weight/voice!  JustFUN Gerry :) 

I see the word doc populated, it is wonderful! I will add a few MicroProfilers  from yesterday's call with the hopes some can take a bit of time to review the blog before crosposting it into Wordpress MP blog. 

Thank you owning it Gerry!

**Comment by mblevins65** [comment]
@Silfen66 Gerry, I have reviewed your blog and found it perfect to read.  Congrats!

**Comment by aeiras** [comment]
Thanks Peggy for the edit review of Gerry’s blog. 

Blog needs the adjustment in the technical sense too- work in progress 💪🏼⭐️

**Comment by aeiras** [comment]
MicroProfilers, 

@Silfen66 have added via the word link his blog. we just need to adjust the wording btw components and specification accross the blog. Code looks good. :)

https://docs.google.com/document/d/1V_9s7lXmCErgUOAo3sGqsZaxU9dydJmx4YjfLQ2zOf4/edit

Today, I took the liberty to add @kwsutter and @jclingan directly to the minutes. I am mindful that we are 24/7 busy yet the comment adding you is to trigger attention to latest update. :) detest taking others' time for granted. fyi and cheers

**Comment by aeiras** [comment]
hey Gerry, i see this issue still open, did you get enough feedback? @@Silfen66

**Comment by Misano9699** [comment]
Hi Amelia (@aeiras), 

I didn't get any more feedback. So the blog is still the same as in the google doc. 

PS I changed my github account. It is now @Misano9699  :)

**Comment by aeiras** [comment]
Thats great then, the grammar was excellent! 

Thanks for the follow up Gerry. :) Is it ok for us to close ticket?

**Comment by Misano9699** [comment]
Yes, that's ok!
