### ISSUE TITLE
[Marketing Call discussions] Schedule Media Push

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#410]
**Twitter Description**
#MicroservicesEnthusiasts: As a communicator & #OSSContributor, are you a grounded, sharp, versatile learner, open to change & experiment, individual? If yes, join the @MicroProfileIO marketing activities. You could help simplify messages, create & maintain processes that scale.

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

**Design focus= people matter**

- #ByCommunityFor Community
- Video, talk, write, git issues, email, etc imagines that put ideas and creativity focus. 

**Design**

@rstjames the template integrate Join in many different languages? 
Thinking global outreach, no matter where you are, you can contribute a design message.

**Comment by aeiras** [comment]
Hola @debbiehoffman & @TetianaFTV, 

Can you please review and adjust as you see fit the tweet description of the marketing call to action? 
Thanks a bunch for your eyes!

 Further feedback is valuable. 

 Next call is March 15th, it needs to be ready hopefully by the end of this week.

**Comment by rstjames** [comment]
@aeiras thoughts?
![microprofile-marketing-call-2021](https://user-images.githubusercontent.com/12132146/110472358-8dcbbf00-80dd-11eb-82e5-eaa21bd166cd.png)

**Comment by rstjames** [comment]
like this? I changed the "word" in all the languages to "participate". 
![microprofile-marketing-call-2021](https://user-images.githubusercontent.com/12132146/110482198-b0170a00-80e8-11eb-8dfa-52cacf757712.png)
@aeiras

**Comment by aeiras** [comment]
Just perfect & fun, @rstjames! 
Thank you for bringing to life such cool stuff :)

**Comment by aeiras** [comment]
and I really love the hands-on design imagine, spot on Ryan!

**Comment by rstjames** [comment]
@aeiras Can we simplify your tweet message? 
 _#MicroservicesEnthusiasts: As a communicator & #OSSContributor, are you a grounded, sharp, versatile learner, open to change & experiment, individual? If yes, join the @MicroProfileIO marketing activities. You could help simplify messages, create & maintain processes that scale._
 
 **Maybe something like:** 
Join Today's #MicroProfileMarketingCall & participation in marketing activities. We need grounded #OSSContributor like yourself to help simplify messages, create & maintain processes that scale, & brainstorm on new ideas that will help shine a light on MicroProfile around the world. https://bit.ly/calendar-zoom-minutes

Join Today's #MicroProfileMarketingCall & help shine a light on MicroProfile around the world. We need grounded #OSSContributor like yourself to help simplify messages, create & maintain processes that scale, & brainstorm on new ideas. 
 https://bit.ly/calendar-zoom-minutes

**Comment by aeiras** [comment]
Ryan, 

this version is fantastic, really good write up. I added plural for OSSContributors.   

 _Join Today's #MicroProfileMarketingCall & help shine a light on MicroProfile around the world. We need grounded #OSSContributors like yourself to help simplify messages, create & maintain processes that scale, & brainstorm on new ideas._
https://bit.ly/calendar-zoom-minutes

**Comment by rstjames** [comment]
All set to go out 2 hours before each call for 2021
