### ISSUE TITLE
[Technical Discussions-Media Push] Long Running Actions  (LRA)

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#411]
when: weekly
Day: Monday
Time: 2 am PDT (change to EU time)

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

**Twitter description**
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
Today, I submitted a comment via the agenda minutes calling out the active MicroProfilers to work via this issue https://docs.google.com/document/d/1HBPiXpsXcQp9T8JeoT-IDs-EblZX1SxuTV5qjUPzwrM/edit?pli=1#

things needed here from other MP call https://github.com/eclipse/microprofile-marketing/issues/412#issuecomment-806167114

**Comment by aeiras** [comment]
Hola @starksm64, 

I saw a LRA event show up in the calendar, so that will help closed this ticket. Thank you!

Ryan, @rstjames, 

Please help us schedule for the rest of the 2021 the API calls as follows and thank you!

**When:**
Every Monday
11am-12pm CEST 

**Twitter:**
Join today's #MicroProfileLongRunningActions discussion & contribute to the LRA's technical direction. #MicroProfilers' participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.
 
https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

**Comment by rstjames** [comment]
all set for the year
![microprofile-MicroProfileLongRunningActions-Call](https://user-images.githubusercontent.com/12132146/128001367-789eb7a1-d690-4592-841f-a6bf631ef6f7.png)

**Comment by aeiras** [comment]
Just beautiful Ryan, thank you!
