### ISSUE TITLE
[Technical Discussions-Media Push] Starter

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#412]
when: weekly
Day: Monday
Time: 6 am PDT (change to EU time)

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

Twitter description
Answers: Why should I join and contribute to this project?

**Comment by rstjames** [comment]
![Uploading MicroProfile-Starter-Call.png…]()

**Comment by rstjames** [comment]
![microprofile-starter-call](https://user-images.githubusercontent.com/12132146/112345938-c961ae00-8cc5-11eb-820e-60bff84daccb.png)

**Comment by aeiras** [comment]
@rdebusscher & @Emily-Jiang, 
**Needed:**

- [ ] I have checked the Starter minutes and it seems that you two are the best equipped to write the twitter description call2action to join the Starter weekly discussions. 

- [ ] You are most welcomed to provide feedback on the card design @rstjames has nicely updated.


- [x] Can you also transfer the Minutes to the [MP Community Minutes Drive ?](https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLZUhOMEFTRWx2TDQ) 

- [x] Zoom admins to continue the calls. We need 2 dedicated Zoom Admins that can record the calls to the Cloud. Who should those 2 people be? 

The media push will be sent on the day of the call, a few hours before the call. :) 
Thanks! 

Examples of media push:

- [Community call tweet](https://twitter.com/MicroProfileIO/status/1371875660034019332?s=20)
- [Mktg call Tweet](https://twitter.com/MicroProfileIO/status/1371491377826107392?s=20)

**Comment by rstjames** [comment]
@Emily-Jiang do you know who should update this ticket with a tweet?

**Comment by Emily-Jiang** [comment]
@rstjames the meeting is 3pm CET. I don't think the call is worthy to be recorded and sometimes it is very short as well. I have moved the minutes to the shared drive though.

**Comment by Emily-Jiang** [comment]
The admin will be me and Rudy. Have these calls been added to the Zoom account? What ID do we need and also the host code as well?

**Comment by aeiras** [comment]
@rstjames thanks for catching us up on this task. 

@Emily-Jiang, 

even is the call is 5 minutes, it ought to:

- use the MPWG Zoom
- ought to be recorded, if longer than 10mins :) 
- minutes under the Community drive.

The Zoom code is the same as the call used for the technical call. Please share it with @rdebusscher, via private means!  :) 

@jclingan, 

Can you please help set up the Starter Call in the internal Zoom? Thank you! 

**Media push**
Based on your feedback Emily, I don't think the media push is valuable. Do create a new ticket in the future if you & other Starter MicroProfilers think such a call out to attend the calls can add value to the project. 

Let's do this,

**Comment by Emily-Jiang** [comment]
It seems the zoom link mentioned in the MP calendar was not set up correctly. @jclingan can you take a look?

**Comment by rstjames** [comment]
@Emily-Jiang @aeiras should this be scheduled or is there still an issue?

**Comment by aeiras** [comment]
It seems that this was fixed. Emily. 

Ryan, this won't need media as it is mostly about enabling developer to implement the MP technology, support tool and not an API> Thanks!
