### ISSUE TITLE
[Technical Discussions-Media Push] Fault Tolerance

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#413]
when: weekly
Day: Tuesday
Time: 6 am PDT (change to EU time)

[Calendar ](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

Twitter description
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
I have checked the minutes, @Emily-Jiang seems to be a constant on calls that took place. https://docs.google.com/document/d/12Tm_JP2Ws8W1fU5IIhhIbNHbrEIf27wgTbTIv80JoXY/edit?pli=1
Request is same as Starter git ticket https://github.com/eclipse/microprofile-marketing/issues/412#issuecomment-806167114

**Comment by Emily-Jiang** [comment]
Please check the MicroProfile calendar. No future calls are sheduled and we are doing async communications. I believe it is true for many spec meetings.

**Comment by Emily-Jiang** [comment]
I suggest you can close this issue.

**Comment by aeiras** [comment]
Really good update Emily. Thank you. 
Many calls are still listed so we will have to wait to see if there is a response or delete the events all together in April. :)
