### ISSUE TITLE
[Technical Discussions-Media Push] Metrics

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#414]
when: bi-monthly
Day: Tuesday
Time: 6 am PDT (change to EU time)

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

Twitter description
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
I submitted a comment via the agenda today to request the MicroProfilers help unblock this task. 
https://docs.google.com/document/d/1HJOg-NOVpcE5X7qhELnyBa_A7OaVTwbOPCsAOp6F1Zc/edit?pli=1#
needed: https://github.com/eclipse/microprofile-marketing/issues/412#issuecomment-806167114

**Comment by aeiras** [comment]
@Emily-Jiang, 

Are you involved in Metrics' work? If yes, thank you in advance for looking at the calendar call duplication.

I don't want to delete stuff from the external calendar if the internal is also duplicated. 
Can you please help us see why the duplication has started?
<img width="860" alt="image" src="https://user-images.githubusercontent.com/10731224/127388528-ec53ae7f-e130-48ce-84c3-95898b13a7a4.png">

**Comment by aeiras** [comment]
@rstjames,

Lets us move ahead and also schedule this API in the mpMedia. Thank you, Triber!

**When:**

Every Tuesday
3-4pm CEST

**Twitter:**

Join today's #MicroProfileMetrics discussion & contribute to the API's technical direction. #MicroProfilers' participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

**Comment by Emily-Jiang** [comment]
@aeiras @rstjames I don't go to their meetings. I've left a message on their gitter [chat room](https://gitter.im/eclipse/microprofile-metrics) for them to confirm.

**Comment by rstjames** [comment]
@aeiras is this ticket for "Technical call" of "#MicroProfileMetrics APIs discussion"? I don't see the info needed for the technical call reminder but see it for APIs.

**Comment by aeiras** [comment]
Hey Ryan, 

The media push is for MP metrics call. 
I am choosing to use the same description slightly change for the other APIs that are active. Call to action is the same for all, help the API move forward. : )

The information for the tweet is on my July 28th comment.

**Comment by rstjames** [comment]
all set for the year. 
![Uploading microprofile-metrics-call.png…]()

**Comment by aeiras** [comment]
Thank you, Ryan!

Please keep in mind to add the issues closed under the mktg "completed tasks" section, always!
