### ISSUE TITLE
[Technical Discussions-Media Push] GraphQL

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#415]
when: bi-monthly
Day: Wednesdays
Time: 7:30 am PDT (change to EU time)

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

Twitter description
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
Connected via comments via call agenda https://docs.google.com/document/d/1gb3jirFGrJwDZSbrtnFPVTNjPNe3Y0dUYfm-HkU1c3U/edit?pli=1#

Needed: https://github.com/eclipse/microprofile-marketing/issues/412#issuecomment-806167114

**Comment by andymc12** [comment]
Hi @aeiras - thanks for making @phillip-kruger and I aware of this thread - and thanks for promoting the MP GraphQL meeting - we'd definitely like to see more community involvement.  What can we do to help?  Are you looking for more information on the project to help market it? Thanks again!

**Comment by aeiras** [comment]
It is fun and my pleasure Andy @andymc12 & Phillip @@phillip-kruger !  :) 

Correct in all your assumptions. In Q4 2019,  I did an inventory on APIs calls, reading the agenda minutes,  and I noticed that we are starving for new contributors in the technical side of the fence.  Sadly MPWG creation didn't allow us to work on pushing fun and innovation and media. All in the past. 👍 
2021 with MPWG behind us enable us to re-focus. Thank you in advance for providing below information in this ticket, asking questions and helping with other similar tickets about the Specs, should you be involved. 

Check my comment: https://github.com/eclipse/microprofile-marketing/issues/420#issuecomment-807889940
Also, check Starter tissue. 

copy/paste for you:

-  move the current agenda minutes to the MP Minutes drive [the folder](https://drive.google.com/drive/folders/0B8_67yGf9LkLZUhOMEFTRWx2TDQ) will be added to the MPWG page as part of the documentation on how to reach MicroProfilers.

-  Via the MPWG, we only just secured a dedicated paid Zoom account, so every call needs at least 2 Admins from each API, it can be more if the group deems it so. Can you get that information so we can provide you with admin access so that Admin can record to the Cloud and all the videos get added to the MP youtube? Admins won't have to do a thing, just record and done.

-   can you provide a written twitter description of the dynamics of the call? It will be pushed the day of the call, a few hours before as a "hey, you too can contribute" social media push. For example:

Community Call- [Twitter](https://twitter.com/MicroProfileIO/status/1371875660034019332?s=20)
Marketing call- [twitter](https://twitter.com/MicroProfileIO/status/1371491377826107392?s=20)

-   lastly, consider submitting an MP quote, you and all those around you who make MP amazing. go to "Submit your quote" [call to action](https://microprofile.io/contributors/)

Abrazos,

**Comment by aeiras** [comment]
Ticket and zoom & media guidelines added to the API minutes call.

**Comment by aeiras** [comment]
closed via https://github.com/eclipse/microprofile-marketing/issues/590
