### ISSUE TITLE
[Technical Discussions-Media Push] OpenTracing	

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#416]
when: bi-monthly 
Day: Wednesday
Time: 8 am PDT 

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)
Twitter description
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
left a msg, 2021 minutes not updated. Not sure call is active. https://docs.google.com/document/d/1TbeKThAd9Df6IS0S6lz_YsTmxpFqWRmCL2HjbrAyLPQ/edit?pli=1
Tasks: https://github.com/eclipse/microprofile-marketing/issues/412#issuecomment-806167114

**Comment by kenfinnigan** [comment]
Right now I don't believe the calls are happening.

@aeiras do you have permission to remove the calendar entry? Thanks

**Comment by aeiras** [comment]
Hola beautiful Ken! 
Tracing has been removed from calendar. If anything changes, please open a new ticket so that we can provide the Zoom Admin access to 2 MicroProfilers and help with media etc push :) Thank you!

**Comment by aeiras** [comment]
@TetianaFTV there is no minutes to place close tickets. Ideally, the minutes are place within 24hrs of the mktg call to allow tracking & self-adding of tasks. 
Like that you can take a breather as well. FYI on this ticket.

**Comment by TetianaFTV** [comment]
Considering that we didn't have summary on Community call I wanted last minutes to stay there one extra day for review.
Fresh copy is already here https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit?ts=605e2b4a#heading=h.9u8jnv48mhk9
