### ISSUE TITLE
Promote architecture call on 2019-03-26

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#42]
Can someone with access please tweet about upcoming architecture call so it can get a little more visibility please? All details are in the MicroProfile calendar. Thanks!

**Comment by aeiras** [comment]
@rsjames can we prioritize this to go out this week and 1 day before the call. The very first call for this project is next week. Thanks!

**Comment by aeiras** [comment]
@xstefank Martin, thanks for prompt issue submission to enable internal prioritizing! :)

**Comment by aeiras** [comment]
minimum requirements for the scheduled tweet that will be constant:

- call takes place the 4th Tuesday in 2019

- 11am PDT

- Minutes doc: https://docs.google.com/document/d/1uAKRymdAL5Wj1KADzrYKZzSnAFsq74lBfj8lxKQnI6I/edit?usp=sharing

- video call:  https://bluejeans.com/3958254622

**Comment by rstjames** [comment]
![MicroProfile-Architecture-Call-2](https://user-images.githubusercontent.com/12132146/54771186-07262a80-4c05-11e9-810b-8dcfeeeb62ac.png)
![MicroProfile-Architecture-Call-1](https://user-images.githubusercontent.com/12132146/54771187-07262a80-4c05-11e9-9681-5d3b17555758.png)

**Comment by aeiras** [comment]
@rsjames designs approved, excellent and simple :) perfect! 

description of the tweet, please schedule it twice a month, Thrusday before the call and Monday. Lets schedule it for 2019 covering all months up until Nov 2019!  Thanks

#Join #contribute to the @MicroProfileIO 💛architecture call that happens the 4th Tuesday of each month https://bluejeans.com/3958254622. # Proactively help open & close PRs during each meeting, it is a #funprocess. Add what matters to you to the agenda via minutes https://bit.ly/2UMWIBx

**Comment by kenfinnigan** [comment]
Is there something I need to do for this, or it's more an FYI?

**Comment by aeiras** [comment]
@xstefank @kenfinnigan tweets are set for the rest of 2019 starting today. 

Note that I love emojis, bias, the call must survive with 1 heart 💯

**Comment by aeiras** [comment]
@kenfinnigan you can review the description and kill it adjust it before it goes live :) this is a fluid process yet we cannot wait for proactive feedback! own it!

**Comment by kenfinnigan** [comment]
I think it's fine. Hard to have anything more specific for something that covers a wide range of topics

**Comment by aeiras** [comment]
yes, i notice that too :) thanks for 3rd eyes man! 

@rstjames execute, lets do this/

**Comment by rstjames** [comment]
**Final Tweet:** 
Join & #contribute to the @MicroProfileIO 💛architecture call that happens the 4th Tuesday of each month https://bit.ly/2JE74Cm #Proactively help open & close PRs during each meeting. Add what matters to you to the agenda via minutes https://bit.ly/2UMWIBx 
See you there! #OSS

**Comment by aeiras** [comment]
looks good. Ryan, lets make it automatic for  twice a month up until the end of Nov 2019? 
Please confirm that is possible via buffer, issues-- shoot :) thanks!

lets close this ticket today.

**Comment by rstjames** [comment]
https://twitter.com/MicroProfileIO/status/1108784492955750401

**Comment by aeiras** [comment]
Thank you @xstefank for creating the ticket and being explicit during the Community call about this call. :) 

closing issue.

**Comment by xstefank** [comment]
@aeiras @rstjames thank you! I wasn't expecting it to have such an impact :) Well done!

**Comment by aeiras** [comment]
@xstefank by now you should know that we, you included, do not BS or waist time when enough beef is added to make something better. This is part of the fun and it wouldn't be possible without you owning it first! :) keep healthy and thanks!
