### ISSUE TITLE
[Technical Discussions-Media Push] Context Propagation

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#420]
when: bi-monthly
Day: Fridays
Time: 6:30-7am  PDT (change to EU time)

[Calendar](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

Twitter description
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
Left a comment in the agenda: https://docs.google.com/document/d/1WWyBjtGxZAwIKHvM6wjjY8nQ_x9Cc7WnvMosGuwodG4/edit?pli=1

Tasks: https://github.com/eclipse/microprofile-marketing/issues/412#issuecomment-806167114

**Comment by njr-11** [comment]
@aeiras I'm unsure of what is being asked for here.  I can see on the calendar that the monthly call for MP Context Propagation (previously MP Concurrency) has run out of repeats as of next month and needs to be rescheduled -- thanks for making me aware of that, even if it wasn't the intent of this issue!  I also see that you've added a comment to the meeting minutes.  Is there a new process for meetings and meeting minutes and where/how they are recorded?  Or is the request something else entirely?  I apologize if I'm just unaware of these things because I haven't been attending the wider MicroProfile meetings lately.  Do you have a link to any documentation on what needs to be done differently?

**Comment by aeiras** [comment]
Hola Nathan, @njr-11,

Thank you for coming to this repo. I appreciate your prompt reply. :) 

Actually, It was also the intent to make you notice the calendar. The calendar event was still set with old name and it went weekly. I took the liberty to delete it once I read the minutes and I knew you were active in the project. I assigned you to the ticket especially because of it. (smily face insert)

Here is what we need from Context Propagation MicroProfilers:

- [x] move the current agenda minutes to the [MP Minutes drive ](https://drive.google.com/drive/folders/0B8_67yGf9LkLZUhOMEFTRWx2TDQ)  the folder will be added to the MPWG [page](https://microprofile.io/workinggroup/) as part of documentation on how to reach MicroProfilers. 
- [x] Via the MPWG, we only just secured a dedicated paid Zoom account, so every call needs at least 2 Admins from each API, it can be more if the group deems it so.  Can you get that information so we can provide you with admin access so that Admin can record to the Cloud and all the videos get added to the MP youtube?  Admins won't have to do a thing, just record and done. 
- [ ] can you provide a written twitter description of the dynamics of the call?  It will be pushed the day of the call, a few hours before as a "hey, you too can contribute" social media push.  For example:

[Community Call- Twitter](https://twitter.com/MicroProfileIO/status/1371875660034019332?s=20)
[Marketing call- twitter](https://twitter.com/MicroProfileIO/status/1371491377826107392?s=20)

- [ ] lastly, consider submitting an MP quote, you and all those around you who make MP amazing. go to "Submit your quote" [call to action](https://microprofile.io/contributors/)

Hugs and thanks for enabling this follow up,

**Comment by njr-11** [comment]
Thanks for the clarification. I've moved the meeting minutes over to the new MicroProfile drive location under the Context Propagation folder,
https://docs.google.com/document/d/1Iy_k-Yaq3AnfWaZ97z2CjOf4LLt71UnaVw8NAbyeVDs/edit?usp=sharing

That's great to hear we have a Zoom account again so we can stop using our separate company-specific web conferences.  @FroMage and @manovotn and @nmittles would you all agree to be admins as well as myself?  I'll also ask on the gitter chat if anyone else is interested, both to be admins as well as for the other items (submitting MP quote) that Ameila posted in the prior comment.

**Comment by aeiras** [comment]
You are amazin Nathan! @njr-11 

While you are an example of doing fun things to broadcast the Project with the other MicroProfilers, can you help write the tweet for the call?  Use the Calendar spacial link in that tweet: **https://bit.ly/calendar-zoom-minutes**

Example: 
_Join Today's #MicroProfileCommunityCall & let your actions show a commitment to the evolution & sustainability of #MicroProfile. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem._

_https://bit.ly/calendar-zoom-minutes_

 **Next call** is not yet scheduled yet coming up middle of April, correct? 

**Zoom**- today we discussed the access redistribution in the community call. Conversation not completed just yet, but we have the zoom. :) 

**quotes**

**Check this out:**  Short versions given that Twitter has only 280 characters and we have a link to add to the media push.  You and others ought to follow the quote guidelines :) 

- https://github.com/eclipse/microprofile-marketing/issues/406#issuecomment-809831513
- listed and rotating every 15 seconds in the [MPWG page ](https://microprofile.io/workinggroup/)
- this page and media needs all #ossDOERs to share some light on contributing in MP, it is simply fun and inspiring. 

Abrazos and thanks for pushing forward,

**Comment by njr-11** [comment]
I'm hoping to get agreement on the Zoom admins at our next meeting, which means for April we will still be using the employer-provided webex that we've used for the past several months, and then hopefully switch over to the MicroProfile Zoom for May.

**Comment by aeiras** [comment]
Sounds wonderful, Nathan. 
2 Zoom dedicated Admins is perfect.

What about the status on submitting:

-  the 2021 tweet for May & future calls? an example that went out today that is scheduled for[ steering calls 2021](https://twitter.com/MicroProfileIO/status/1379829318679937040?s=20)  
- quotes from every MicroProfiler, whose actions inspire collaborating in Context Propagation?
- + more. 

Remember, any MicroProfiler can submit business tickets via this Repo to requests things that could improve the project communicating better with the world.  
Let the system we have in place help the project get new contributors. Just submit new git issues with project updates worthy of attention or issues that must be tackled and need more visibility so that media can push such stuff.

Abrazos,

**Comment by njr-11** [comment]
>     * Via the MPWG, we only just secured a dedicated paid Zoom account, so every call needs at least 2 Admins from each API, it can be more if the group deems it so.  Can you get that information so we can provide you with admin access so that Admin can record to the Cloud and all the videos get added to the MP youtube?  Admins won't have to do a thing, just record and done.

@aeiras on the call today, Stéphane Épardaud @FroMage agreed to be an admin for the MicroProfile Context Propagation spec, with myself being the other admin.  Could you get us added?  Thanks!

**Comment by aeiras** [comment]
Are you ok to send your email via this ticket? Or private to aeiras@tomitribe.com? Up to you, preference! 

With @jclingan's help, we will get the you two enabled to co-lead future calls using the code. Thank you, in advance, John. 

Though, we need to simply document Zoom admin access, access will allow Admins to: 

1. be able to delegate co-lead in the call if 1 of you is missing. 
2.  Record the meeting to the Cloud
3. so that a MP youtube admin can import the recording to youtube. 

Cheers,

**Comment by njr-11** [comment]
Admin emails have been provided separately (by email). Thanks!

**Comment by aeiras** [comment]
Received and sent! 

I will close this ticket, the expectation is for both of you to gain access to zoom, latest next week. 
If you don't. Please re-open the ticket or use the private email to request an update on why the delay. 

Nathan, 

A Context Propagation Youtube playlist will be added to the MP youtube channel to hold the recordings moving forward.  That is assuming, either you or @FroMage always record the call to the Cloud.  Any issues with it? 
Your feedback is preferred. We cannot push you to record the calls, yet I personally recommend the recordings. If you cannot own it for the world to see 5years from now, then, it is truly not OSS> :)

**Comment by aeiras** [comment]
Hey Nathan @njr-11 and Stéphane @FroMage 

The very 1st media push for the technical meeting went out today. That team chose to use the already set message for the Community call MP media push.   
You could choose to use the same working as well. 
Did you two gain access to the Zoom account yet? This is a follow-up! 

https://twitter.com/MicroProfileIO/status/1384522242080448527?s=20

**Comment by aeiras** [comment]
This morning, John and I met with @@njr-11 to test his new zoom admin access. 
Thank you Nathan the patience through the infra testing.

**Comment by aeiras** [comment]
@rstjames, thank you in advance for helping us push this API media call! 

**When**
2nd Thursday, 1 a month. Starting June 2021. 

**Time:**
6:30- 7:30 AM PDT- let's convert to Easter time instead of PDT

**Twitter:** 
_Join today's #ContextPropagationCall to discuss & contribute to the API's technical direction. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource API. 

Join: https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS_

**Comment by njr-11** [comment]
Suggestions for additional clarification to the Zoom Admin doc based on this morning's conversation have been added to
https://docs.google.com/document/d/1xTBnhJ2SjDmLjM6OTyRVjSnjb6r5s8_opGjSyZnD5vA/edit

**Comment by aeiras** [comment]
Your wonderful suggestions have been accepted into the document. Thank YOU, @njr-11! 💯 
 
As a follow-up, should MicroProfilers wish to connect next Thursday, the event has been created and is public in the calendar [John did it before returning to his PTO :) ].  Please, do not stress about the event. If there is no need for that special call, please follow up via this ticket with a "delete" request.   I will delete the call from the public calendar, OK. Just let me know early next week!

Nathan, thank you for caring enough to improve the documentation!

**Comment by njr-11** [comment]
> As a follow-up, should MicroProfilers wish to connect next Thursday, the event has been created and is public in the calendar [John did it before returning to his PTO :) ]. Please, do not stress about the event. If there is no need for that special call, please follow up via this ticket with a "delete" request. I will delete the call from the public calendar, OK. Just let me know early next week!

Yes please go ahead and delete the extra MP Context Propagation meeting entry that is on the calendar for this Thursday, May 27.  When I checked with the community, there wasn't anyone wanting to have the meeting then.  Our upcoming June meeting will be close enough.  Thanks!

**Comment by aeiras** [comment]
Deleted. Thank you, Nathan!

**Comment by aeiras** [comment]
> @rstjames, thank you in advance for helping us push this API media call!
> 
> **When**
> 2nd Thursday, 1 a month. Starting June 2021.
> 
> **Time:**
> 6:30- 7:30 AM PDT- let's convert to Easter time instead of PDT
> 
> **Twitter:**
> _Join today's #ContextPropagationCall to discuss & contribute to the API's technical direction. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource API.
> 
> Join: https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS_

@rstjames can you help us scheduled this please?

**Comment by rstjames** [comment]
scheduled for the year. 
![MicroProfile-Context-Propagation-Call](https://user-images.githubusercontent.com/12132146/121356553-3e419d00-c931-11eb-8728-60bc2c997e1a.png)

**Comment by aeiras** [comment]
Thank you, beautiful Ryan! 

@njr-11 🤗

the API is all set up. 
thank you for helping us pilot everything about zoom, Google drive, documentation …

when you & the context propagation MicroProfilers wish to submit your quotes, just read the guidelines. Your quotes are welcomed at anytime 💛

**Comment by jclingan** [comment]
Zoom meeting schedule fixed. It had 6:30 "PM" instead of "AM".
