### ISSUE TITLE
Twitter poll 1- Jakarta EE 9 Alignment Questionnaire

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#421]
MicroProfile community values your opinion towards Jakarta EE 9 alignment to guide our release plan. Please participate and retweet! Thanks

Question 1 : Do you think MicroProfile should align with Jakarta EE 9 and drop the support for Jakarta EE 8?
Choice 1: No, wait for Jakarta EE10
Choice 2: No, support both
Choice 3: Yes, do it asap

**Comment by Emily-Jiang** [comment]
Can you keep this poll running for 4 days?

**Comment by aeiras** [comment]
[Survey document](https://docs.google.com/document/d/1ucMSPUMG0Urpd64FtT9Z65BMnnaxlIR18p5Rf8ggs5Q/edit?ts=60363af3) for reference to keep the information within the ticket. 

Go live:  8am PDT on Feb. 26th until March 1st. 4 days.

**Comment by aeiras** [comment]
[Feb 26th tweet](https://twitter.com/MicroProfileIO/status/1365327469838934021?s=20) responses will close this ticket on March 2nd.

@Emily-Jiang I think it is wonderful for you to update the survey google thread with this ticket and the tweet to inform the Community. You rock!:)

**Comment by Emily-Jiang** [comment]
Thank you @aeiras ! Can you please tweet the other 2 polls out asap #422 #423 ?

**Comment by aeiras** [comment]
The Q1 poll is closed. Results are https://drive.google.com/drive/folders/1LtiInEuIwt4BVmhPqHgLds8ETSa50Dtl

@Emily-Jiang, 

 Two requests:

1. Can you please move the survey document to MP Drive> Surveys> 2021 > Releases? 
2. Are you able to update the document with the results as listed in the drive above? 

Let me know if you cannot and I will do my best to get it done before today's community call :) Thanks!

**Comment by Emily-Jiang** [comment]
@aeiras I don't have access to the dirve. I don't see it is visible in the external drive for MP either.

**Comment by aeiras** [comment]
Now you do Emily. Please confirm! 
The community folder is the only public-edit for all contributors with a Gmail account. 
The other folders' access is based on the individual MicroProfiler's chosen collaboration.

**Comment by Emily-Jiang** [comment]
No. I still can't. I have put two docs [here](https://drive.google.com/drive/folders/1XABVbjypqRvH8-8NIKsUVPBMOCdZL4nv) instead. Feel free to rearrange the folders.

**Comment by Emily-Jiang** [comment]
oh, please use my gmail account: emijiang6@googlemail.com

**Comment by aeiras** [comment]
I figured out the issue. 
When the MPWG was created, you gained access to the MPWG folder under the drive, 1 file. 
It seems that IBM email restricts it. I checked Kevin and he uses his personal email. I have sent you the full access via your gmail account. I know this time you will have full access based on findings. This exchange will help document wiki. :) Thanks Emily!

**Comment by Emily-Jiang** [comment]
Thank you @aeiras ! done now.
