### ISSUE TITLE
Twitter poll 2- Jakarta EE 9 Alignment Questionnaire

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#422]
MicroProfile community values your opinion towards Jakarta EE 9 alignment to guide our release plan. Please participate and retweet! Thanks

Question 2: Would you like to use Jakarta EE 9 (jakarta.*) together with a MicroProfile release? 
Option 1: Yes, asap in 2021
Option 2: Yes, in 2022 or later
Option 3: No, wait for Jakarta EE10
Option 4: No, not use Jakarta EE

**Comment by Emily-Jiang** [comment]
Please tweet on Friday morning and leave this open for 4 days

**Comment by aeiras** [comment]
[Survey document](https://docs.google.com/document/d/1ucMSPUMG0Urpd64FtT9Z65BMnnaxlIR18p5Rf8ggs5Q/edit?ts=60363af3) for reference to keep the information within the ticket.

**Comment by aeiras** [comment]
Go live: 8am PDT on March 2nd until  March 5th. 4 days.

**Comment by Emily-Jiang** [comment]
@aeiras can you tweet this poll as well asap?

**Comment by aeiras** [comment]
It is not a good idea to submit the 3 questions at once.  

The idea is to allow for the questions to arrive at different times, each one closing before submitting the new question. There is no need to rush for feedback. 
 
I wrote in the survey document the schedule that is expected.  Happy for us to discuss it on the Tuesday call.

**Comment by Emily-Jiang** [comment]
not really. If we don't send out all questions, we won't be able to gather feedback and we can't get the full picture. We won't be able to make any decisions next week. I'll twitter from my own handle instead. From last Tuesday's call, IIRC, David suggested to twitter the questions all together and all were agreed.

**Comment by dblevins** [comment]
@Emily-Jiang we should tweet from the MicroProfile handle so people see it as official.

On all together or fanned out, I like fanned out as you can only get so many retweets at once.  But either is fine.

**Comment by Emily-Jiang** [comment]
@dblevins I agree that tweeting out from MicroProfile handler sounds more official. I think tweeting out with a couple of hours sparation is fine. Since the questions are not sequenced, we don't need to wait for the previous poll comes back.

**Comment by dblevins** [comment]
Can we add this question?

"Do you hope to start migration from the javax to jakarta namespace in the next year?
 - Yes
 - No
 - Unsure
"

Reason I'd like to see that question is because the first "Do you think MicroProfile should align...." question is asking users what *we* should do.  I'd really like to know what *they* will do.

If you ask users, "do you want everything now" questions, you'll always get a yes.  That doesn't mean they'll be as aggressive with their own plans.  We should ask them their plans.

**Comment by Emily-Jiang** [comment]
@dblevins good suggestion. I have added your question to the google doc and also created a github [issue](https://github.com/eclipse/microprofile-marketing/issues/428).

**Comment by Emily-Jiang** [comment]
At today's live hangout, we decided not to push this any more.
