### ISSUE TITLE
Tweeter Poll 3- Jakarta EE 9 Alignment Questionnaire

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#423]
MicroProfile community values your opinion towards Jakarta EE 9 alignment to guide our release plan. Please participate and retweet! Thanks

Q3: Do you want the same MicroProfile release 4.x works with either Jakarta EE 8 or Jakarta EE 9 since they only differ in namespace?
Choice 1: Yes
Choice 2: No

**Comment by aeiras** [comment]
@Emily-Jiang, 

You are awesome. 
Can you please add the survey document to each ticket. 
I will need to review the if X, Y. 
Tmw might to be too fast as I cannot get to it right now. FYI.

**Comment by Emily-Jiang** [comment]
We will need to tweet it on Friday so that we can get results on Tuesday. I am not sure what you want to know.

**Comment by Emily-Jiang** [comment]
We don't need a survey doc as when you tweet, the link won't show. Besides, it is too long already. I will consolidate the results.

**Comment by aeiras** [comment]
Ok, thats a great idea. I will make sure to review question 1 today Emily. I gotcha. :) Thanks for the follow up. 
Please assign all the tickets to me. We need same time & same amount of days for the 3 questions.

**Comment by Emily-Jiang** [comment]
If you could tweet this at the end of your day, it will be awesome as well. Otherwise, please do so as early as you could tweet tomorrow morning.

**Comment by aeiras** [comment]
[Survey Document](https://docs.google.com/document/d/1ucMSPUMG0Urpd64FtT9Z65BMnnaxlIR18p5Rf8ggs5Q/edit?ts=60363af3)

**Comment by Emily-Jiang** [comment]
@aeiras I have assigned the 3 tickets to you. Please feel free to add your awesome collection of emojis

**Comment by aeiras** [comment]
Go live: 8am PDT on March 6th until March 9th. 4 days.

**Comment by Emily-Jiang** [comment]
@aeiras can you tweet this poll as well asap?

**Comment by Emily-Jiang** [comment]
> Go live: 8am PDT on March 6th until March 9th. 4 days.

I disagree with the schedule. It is unnecessary.

**Comment by Emily-Jiang** [comment]
At today's live hangout, we decided not to push this any more.
