### ISSUE TITLE
[ Website Images] Need to be in the MP Drive

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#424]
@rstjames, 

Can you please drop all images found on the website in the Website> Designs [folder](https://drive.google.com/drive/folders/1CcxFgAqub7qPrqbHCUURY5afQV1HU-RQ) please?

A while ago, Kevin asked for a few images to do a presentation, but I couldn't find the files in the drive. Thank you!

**Comment by rstjames** [comment]
@aeiras all images?  I am not sure we can do this. We bought these pictures for website use. I don't believe "anyone" can use them for what they want. If anyone wants certain images off the website they can right-click and save them and use them at their own risk.

**Comment by aeiras** [comment]
Ryan, 

Please add whatever you have available into the folder.  
We started building the website in June 15th, 2016 - June 26th, super quick. 
There was no drive nor INFRA during the build time.  It is normal to not have all the data after all these years. 

Thank you,
