### ISSUE TITLE
[Content Contribution] Document: Desarrollo de Microservicios  [spanish review]

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#425]
As a follow up from my conversation with @xtecuan , [this](https://drive.google.com/file/d/1sdz0Pj_fvQIwDfj07bKN4D4K3B5rO6Gt/view) is the draft version of the paper "Desarrollo de microservicios con MicroProfile".

@xtecuan 
In the [MicroProfile community Drive](https://drive.google.com/drive/folders/1kRrOzf0G7PtG8VJXKODgDpVNOUKSUxnR), you can allocate the paper in a google doc format, this will facilitate the feedback interaction with the MicroProfile Spanish community over the content of your awesome paper.

So far the feedback provided during our call:
* The name of the project is: MicroProfile
* Accuracy in the creation date can be updated, I found the following official announcement from mid-2016: https://www.tomitribe.com/blog/microprofile/
* The project was not created by Eclipse Foundation, it was created by the Java community, Open Source communities and vendors. In the previous bullet, you can find an article with references to the founding members.

**Comment by xtecuan** [comment]
@cesarhernandezgt  [This](https://drive.google.com/drive/folders/1ILl8FbOPKfi0wkMHj4DN9V65eNGFv35t?usp=sharing) is the link of the Word document I tried to add it to the community drive but I think I don't have permission

**Comment by aeiras** [comment]
Hola Tadeo @xtecuan, como estas?

First, thank you for choosing to share ([Twitter message](https://twitter.com/xtecuan/status/1364848067074273284?s=20)) a document about the MicroProfile technology. It is the very first one I see in Spanish. 

Using the MP drive, under e-books, I have created a [folder ](https://drive.google.com/drive/folders/11jkjYWI509ySXWVIwgCrE-m_mWpT798T)for your work to enable collaboration. Thank you for choosing to accept feedback via your reply to this git issue. You actions are wonderful. 

Please let us know via this ticket as soon as the word document is ready for public review. It is your job to state the rules of engagements. In the past, MicroProfilers have contributed to creating the white paper & ebooks using the drive & public edit access where all changes are via "suggested mode". I recommend you state that in the document to make sure that you can see the recommended changes & accept them, specially if there are in code. 
When we helped with the ebook that was heavy in code, we use git to run the tests, etc. It is your job to welcome as much feedback as you think it necessary. 

For reference: 

- the MicroProfile Content Contributions' listed under the Blog section in the website [guidelines ](https://github.com/microprofile/wpsite)
- ebook, white papers, etc [guidelines](https://github.com/eclipse/microprofile-marketing/wiki/Pro-Bono:-OSS-Content-Creation-Steps-for-White-Paper,-Case-Study,-e-Book...) for contributors


Stay wonderful and safe,  ask questions!

**Comment by xtecuan** [comment]
I just dropped in the document in the folder, I'm ready to begin the corrections!

**Comment by aeiras** [comment]
First, @cesarhernandezgt you rock at introducing Tadeo to the review process, thank you! 

Hola @xtecuan, 
Thank you for adding the word document into the MP community drive. 
To onboard you onto how review works, please note that:

- as the author, you ought to not assume that the reader knows anything about the technology.  I see how the document starts, it is tracing history, which is great. Kudos on that!  
-  the document was converted into gdocs directly in the drive. [28 word document- MP](https://docs.google.com/document/d/1xsnQcj590_hJAb4LnNk-2OybquhcaG_h/edit)  

- [MP trivia facts](https://docs.google.com/spreadsheets/d/1M0d7U3Yk-Vu3-TdC7zKnQ4qRVODSpD1ih2E4jvNbjoc/edit#gid=0) could help you write the 1st page.  I specially initiated the document to help you with factual-historic documentation that is relevant to your document. Thank you for enabling the creation of the new document. 

-  I used s_uggested mode_ to show you a few changes, it is you the one who will approve or decline or follow up the suggestions (example) Please use my email aeiras@tomitribe.com to pull me in via comments when you must. I won't be the only MicroProfiler who might help with the editor's side yet that's how we contribute, fluid and simple. 

- added page numbers
- added Reviewers into the intro of the document. Anytime a review happens, credit is given directly in the document. Usually, any media that contributor prefers is used as a link as you see my preference is Twitter. 
- a webpage links are crucial, note how the MP website is inserted. I recommend you do that for all relevant projects, companies, etc. After all, your document will live-online as such links ought to be prioritized. 
- this is a good start, let's do this! 

It would be amazing if you could join this month the MP business call on Monday 10 am-11 am PDT. Please check the MP [calendar,](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles) the next zoom call is March 15th. Its access is public and in that & all MP calls welcome questions about anything relevant to contributing to MicroProfile. 

Editing takes awhile, I look forward to getting to know you via this collaboration along with many other MicroProfilers. 

PS: Me fascina tu pais. Aun extraño mucho su gente cariñosa y muy linda. Que viva el Salvador! :)

**Comment by xtecuan** [comment]
Thanks, This weekend I going to begging to check the things in the document

**Comment by aeiras** [comment]
No hay apuro Tadeo, toma tu tiempo. 

Aquí estamos para colaborar contigo!

**Comment by aeiras** [comment]
Hola @xtecuan Tadeo, 

Como estas?  Mira si puedes acerca este lunes a chatear con algunos MicroProfilers sobre este ticket durante la llamada de marking, eres bienvenido. Encuentra el acceso en el calendario de MP que lo encuentras el el website under Resources.

**Comment by xtecuan** [comment]
Sí está bien me conecto entonces el Lunes

**Comment by aeiras** [comment]
Que chevere, Tadeo. Gracias!
Entonces, yo añado este ticket a la agenda del Lunes y así tu tienes unos minutos para decirnos quien eres y hablar sobre el papel. Nos vemos pronto!

**Comment by aeiras** [comment]
Como estas Tadeo, @xtecuan 

For the time being, I will close this ticket and welcome you to re-open it or connect it with a new ticket once you wish help on the document you wrote about MP. 

Stay safe,
