### ISSUE TITLE
[MPWG Prospectus Quote Addition] Payara

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#426]
[Payara's quote](https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit#gid=0)

@rstjames, 
Can you add it to the document? 
This addition with latest adjustments you have made make me wonder if we could improve the way the Quotes are presented in the MPWG page by allowing a quote link to be possible. Like that, that link could be a part of the Prospectus Quote's section and help scale the document.   It is not going to be scalable when we get 20 Organization quotes, so we need to think ahead and find a way that shows all of them in the document with 1 links.  Website link sounds great but it is not focus... "later wish". 

Also, we are awaiting for Oracle and Garden State quotes to be submitted whenever the partners wish to submit. 

Thanks Ryan,

**Comment by rstjames** [comment]
done
