### ISSUE TITLE
[Past consecutive media designs]  needed in the MP Drive

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#427]
Ryan, 

Can you please drop under the media space > [2020 and past designs](https://drive.google.com/drive/folders/1zuDs1XbRvoXXuuLBp_ZC4k7_q93I4CWm) the designs used? 

We want to show what has been used, either allow for new designers to improve that work or create new ones while we work on 2021 media consecutive pushes. 

If you could get this completed by the time Monday's Mktg call meets, that would be amazing to enable the discussion and include others in the work. Thanks!

**Comment by rstjames** [comment]
I will organize these files this week making it easier for other people to use and edit them.
