### ISSUE TITLE
MP talk by Emily [MP twitter push]

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#43]
Hey you two, please add the value "core" reasons for attending this call to enable a proper description of the session. Specially since it is under the Jakarta tech calls. 

Current description is not correct. lets fix it. Thanks!

**Comment by aeiras** [comment]
@rsjames this is the data needed for a successful tweet. Lets schefule it for this Thursday and next Monday. Thanks! 👍 

[Session Information](https://secure.meetup.com/register/?ctx=ref)

When Thu Mar 28
12:00 PM ‐ 1:00 PM Eastern Time 
JOIN THE WEBINAR HERE:
https://www.youtube.com/watch?v=sbgCPdt9TJs

Start of tweet:  #JakartaTechTalks
Emily is going to bring attendees up to speed with  MicroProfile 2.2.  and what components changed from previews release. She will also focus on the MicroProfile Starter, how to use it and its value. 

End tweet: #sharingIScaring #community @OSS

**Comment by Emily-Jiang** [comment]
Why the description is incorrect? Can you be more specific on which bit is incorrect @aeiras ? The reason for attending is to learn the latest update of MicroProfile and future specs. I am not sure what you want me to do.

**Comment by aeiras** [comment]
@Emily-Jiang the description is correct. I am refering at the tweet that went about your session that is misleading and reason for this ticket :) that will help use the MP tweet to clarify. 

I wrote the description above based on what Kevin explained on the call yesterday and the abstract on session. :) get it!

**Comment by aeiras** [comment]
@rsjames will deal with ticket, he needs the information i post it b/c he didn't have it this AM. He works from Prague so I am helping you and Kevin by providing him with that data :)

**Comment by rstjames** [comment]
Tweet: 
#JakartaTechTalks @emilyfhjiang will bring you up to speed with #microprofile 2.2 & what components changed from previews release. She will also focus on the @MicroProfileIO Starter, how to use it & its value.
WEBINAR https://bit.ly/2HOa2C5
#sharingIScaring #community @oss
 
![JakartaTechTalks-EmilyJiang](https://user-images.githubusercontent.com/12132146/54717013-7a716300-4b57-11e9-8e43-d87325bedbb1.png)

**Comment by aeiras** [comment]
@rstjames  approved! thank you for sending the tweets :) closing ticket!

**Comment by Emily-Jiang** [comment]
ah, awesome! Thanks @aeiras @rstjames !
