### ISSUE TITLE
[General: Mktg-Call Steward] co-host for June/July

### ISSUE THREAD

**Issue by nehasardana09** [microprofile/microprofile-marketing#430]
hi @aeiras, I want to be help with co-hosting as discussed in Marketing call. I can do in June or July. :)

**Comment by aeiras** [comment]
@nsardana-bny, 

So wonderful, thank you for choosing to help. 
Currently there is no other MicroProfiler added to the months. Note you said June or July. I added you to both, you can adjust the sheet now because you are an editor. 

https://docs.google.com/spreadsheets/d/1gb2D8wPoXIrvmndMt0fP4jDYC61YuvBwVEFqVskywU8/edit#gid=0

Neha, 
Please keep in mind the feedback given to Rustam in https://github.com/eclipse/microprofile-marketing/issues/429

I cannot speak for Rustam but maybe after march, he might choose to help mentoring the next Steward. Either way, we have your back! We will figure stuff together as we show up and learn. Abrazos,

**Comment by mehmandarov** [comment]
I might be able to help in July if you want.

**Comment by aeiras** [comment]
help as you see fit Rustan, no limits and no pressure. please add yourselves to stuff and skip if anything changes. MP is fluid b/c we care about time investment. :) Abrazos to both of you!

**Comment by aeiras** [comment]
Neha, Rustan, and you will lead for 1 month :) 

Rustan started an onboarding document, https://github.com/eclipse/microprofile-marketing/issues/429#issuecomment-788219888. You are most welcomed to help write-up (using "suggestive mode") before the document converts to a PR for wiki review. It is contributors like you who are the best-suited individuals to help with documentation on how. :)

**Comment by nehasardana09** [comment]
Thanks Amelia and Rustam for your help! 

I will refer to the onboarding document and let you know if I have any questions. :)

**Comment by aeiras** [comment]
you ought to contribute to the onboarding document instead of using it as a reference Neha. 
Again, only those with fresh eyes are best equipped to document new processes. :) Cheers

**Comment by nehasardana09** [comment]
Will do, Amelia! Thanks!

**Comment by aeiras** [comment]
Hola @nsardana-bny, 

To help Tetiana with your onboarding, I have run an inventory of the many git issues that we had. Many have been tackled this week and others were in stand-by. Please see the closed tickets for reference, all closed today. 
https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit# 

Check the responsibilities' sheet for further reference of the work ahead. Improve the Steward onboarding document as you do stuff. Struggling alone is a flat no and to be avoided is your choice. struggling and pulling others via private means must be strategic and not abused. Remember what is MP winning with private vacunm. :)

Super excited to see you rock next month,

**Comment by aeiras** [comment]
@nsardana-bny, 

So much fun seeing you lead your very first MP call. :) 
I haven't seen the latest version of the Steward's onboarding documentation, yet I wonder if in there we have put the add the following call agenda within 24hrs of the previews call?

Why it matters that the agenda is always ready to take on tickets and changes? 
The MP work is fluid. ASAP after completing the Monday call, tickets continue to open and close. Without the agenda ready to take in those activities, you are left with YOU having to do all the updates, and even figure out what tickets were closed, etc. That hustle is not sustainable and not recommended. 

It is your job as the monthly steward to make sure that a MicroProfiler is moving the tickets from open to close and updating the agenda. If someone is not doing that. Call it out on the ticket. avoid doing that work yourself. 

That's it.  It is Thursday, there are many tickets activities. without agenda, it is likely you will have to help with that upkeep. recommendation, added asap to the minutes agenda, copy / paste from Monday works great. 
If you can place it below next Monday call, I will move those minutes asap after the MPWG call. Thank you!

**Comment by nehasardana09** [comment]
Hi @aeiras, I was going to update the agenda right after the call but I was going to update it after next Monday's call. I will update it by tomorrow. Sorry for my delayed response. I was in a conference and presenting at a JUG today. I will make sure the information is updated for the Steward's onboard documentation as well.  Thank you!

**Comment by nehasardana09** [comment]
@aeiras I have added the agenda in the document. Will continue to work on it. Please let me know if this is okay.

**Comment by aeiras** [comment]
Wonderful, Neha! 
always do your best to avoid stuff falling only under your lap. Distributing the responsibility is core to an scalable & maintainable oss contributing, if at all possible, prioritize it! 🥋

💓

**Comment by nehasardana09** [comment]
It wasn't hard. I will keep that in mind next time. Thank you for the reminder!! I am also learning from it :)

**Comment by cesarhernandezgt** [comment]
Hi @nsardana-bny and @mehmandarov, I was checking the July Monthly Mktg-Call Stewards file.
Both of you appear as the one leading the Microprofile calls for the rest of July.
Can you please provide me access to the [Onboarding](https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit#heading=h.f48u5qcg1twv) document so I can check how I can also help on some of the back-end task during the July calls you will lead?

**Comment by nehasardana09** [comment]
Thanks @cesarhernandezgt for volunteering. If you share your email address, I can give you access to the document. I have added @aeiras to the document. You can share your email with Amelia so she can assign you. Whatever suits you. If you have any questions or doubts, you can always reach out to me. I will be on vacation from July 2 - July 11 so I won't be able to host the calls but I can help you onboard. We are all here to help. Thanks for showing up and considering to volunteer. We take your time very seriously. We appreciate your time. 
Thanks.

**Comment by nehasardana09** [comment]
@cesarhernandezgt the document is open now. I have enabled public access. Feel free to go through it and ask any questions you may have. Cheers!

**Comment by cesarhernandezgt** [comment]
Thank you @Naramsim.
I reviewed the documents and I think that at this point if either you or Rustam are not present in a call during July, I can help as co-host performing task described in the document for the `During your call category`:

> Role: During your call
Assign someone as a co-host so that they can admit people on the zoom meeting without you as you will be talking for the call.
>Make sure to record the call on cloud (Zoom has option)

After my first call helping I'll identify more areas I'll be able to help.

**Comment by aeiras** [comment]
@cesarhernandezgt  & @nsardana-bny
https://docs.google.com/spreadsheets/d/1gb2D8wPoXIrvmndMt0fP4jDYC61YuvBwVEFqVskywU8/edit#gid=0 is updated to add Cesar as a supportive co-host!

**Comment by ghost** [comment]
Hi all,
 I have made some suggested edits to the Mktg-Call Steward document to make it easier to follow when you are trying to be the steward for the first time, or wondering how to onboard a new call Steward. I also merged some of the details from the Zoom Admin Doc along with the screen shots. (I do not believe we still need Zoom Admin Doc but maybe it has another purpose beyond Marketing call stewards). https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit#

**Comment by aeiras** [comment]
It has other users, MP has +8 API & those groups have zoom stewards that will use the document. 

The plan is to converted into a wiki under the MPWG Repo documentation.
