### ISSUE TITLE
MP Trademark work

### ISSUE THREAD

**Issue by manish2aug** [microprofile/microprofile-marketing#431]
Hi,

I want to contribute to the trademark work, please guide

**Comment by aeiras** [comment]
Thank you, @manish2aug, for allowing us to move the Trademark's folder to the Community folder to enable your contributions to the project. 
Edit is public so that contributors like you can help draft the document using the resources provided within the document from the past work. 

https://drive.google.com/drive/folders/1wbn8mUPTjQMpHYuzh1swwPCBnuS7rg3o

**Comment by manish2aug** [comment]
Thanks, @aeiras, I will go through the ones for Jakarta EE and would make similar copies for MP though I am not sure about the following, 

1. Brand usage handbook is a pdf, not sure about the content, can you please guide me to something to find out about the chosen logo, and typography etc which is required for the content.
2. The second document (trademark guideline) is hosted on the internet, can I create an MS\Google doc and attached it to this issue for review

Sorry, just confused a little bit never involved in such type of activities before, would appreciate your guidance here, thanks

**Comment by aeiras** [comment]
Hola Manish, 

1. Forget about brand handbook, that is only possible once the trademark guideline is approved and finalized. 

2. Fantastic request on number 2. [Example - Word  Trademark Document- Jakarta EE Trademark](https://drive.google.com/drive/folders/1wbn8mUPTjQMpHYuzh1swwPCBnuS7rg3o) has been converted from online PDF to word. 

You have nothing to apologize for. Thank you for choosing to do & asking questions on the spot. You are not alone, many others are right there beside you, ready to help.!

**Comment by manish2aug** [comment]
Thanks, Amelia, 
Have added a drafted version ([here](https://docs.google.com/document/d/1dturdVLQvx-UV6TbD9wr0pgFReBXhDH0/edit)), 
Can you please confirm if it will have the same eligibility requirements & required information for inclusion in the official list of Compatible Software Products or this information would be different and relevant information can be found somewhere

**Comment by aeiras** [comment]
Wow, Manish, you are amazing! 
Thank you for stepping in. How wonderful! 

I added comments in the document and quickly review the write-it, excellent draft. Kudos! 
Things are still coming together with compatible implementations & TCK. Discussions are ongoing in the general forums. 

Your time and effort have provided enough to move the community to tackle the stuff we haven't decided yet. 

Can you please @manish2aug become a member of the [MP general =1,200 Members ](https://groups.google.com/g/microprofile)or you could start small and send a message update to the [Marketing forum + 26 members ](https://groups.google.com/g/microprofile-marketing) and provide an update from your point of view as the leading contributor using this git issue? Doing so will help trigger notice on progress on such important MPWG task to other MicroProfilers who can help.

**Comment by manish2aug** [comment]
Thanks, Amelia! 
Posted the msg.

**Comment by ghost** [comment]
I made a find/replace edit throughout the doc from Microprofile to MicroProfile as I believe the capital P is part of the trademark.

**Comment by aeiras** [comment]
Awesome @debbiehoffman!

**Comment by manish2aug** [comment]
Hi @aeiras, I am not sure about the review or approval process. As there is no more suggestion on this can we mark this as closed?

**Comment by aeiras** [comment]
Hey Manish, @manish2aug

This ticket can be closed as the 1st face of the trademark write up is completed. 
Now, we move into group review before we start the technical API inserts that will need to be included. 
While at it, we will also work in the creation of the trademark logos that are missing, the tickets were openned in 2020. 

The trademark and all the work will end up for Steering Committee vote once all pieces are completed. Thats why the Trademark's handbook comes at the very end. :) 

You are welcomed to close the ticket today or wait until Monday, show and tell update.  Your call!

**Comment by aeiras** [comment]
oh and you can and ought/must vote on the MPWG mailing list when that vote goes out. MPWG steering ballots and votes are public and welcomes contributors' feedback and votes. You leading the effort must own it beautifully on that vote!

**Comment by manish2aug** [comment]
Closing the issue as the planned work is done
