### ISSUE TITLE
[eBook- Riecks] 2021 media schedule

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#436]
@rstjames, 

Using 2020 wording,  let's schedule Phil's book twice a month. Adjusting the design a bit could be great for a quick re-fresh. Thank you!

https://github.com/eclipse/microprofile-marketing/issues/236
twitter: https://twitter.com/MicroProfileIO/status/1323301341528264714?s=20

**Comment by rstjames** [comment]
@aeiras let's do this when he makes a new ticket updating what he wrote. He was promoted all 2020 and some.

**Comment by rstjames** [comment]
@rieckpil your image has been updated and scheduled for the next three months. Let us know when you have an update for the ebook. All the best!

**Comment by rieckpil** [comment]
Thanks a lot for your efforts @rstjames and @aeiras to push the bundle :)

Unfortunately, I can't give a concrete timeline when I find time to update the existing content as I'm currently busy with other content :(

**Comment by aeiras** [comment]
Thank you Ryan for being awesome pulling @rieckpil to the update ticket! :) 

Philip, 
You don't have to feel stressed or pushed to update your ebook. It is up to you, always, when you might do it. 

The reason, we scheduled it for 3 months is b/c hopefully in June we have the new MP release welcoming update. 
By informing you, we properly thank you and appreciate your awesomeness and also hopefully enable you to inform the project via **a new git ticket** if your book ought to continue to be pushed as  it is without changes from June to Dec or similar. It is you who decides how we push it.  Thanks for allowing this follow up. 

Your feedback is the most important on the social push, it is your work! :)  

Stay awesome,
