### ISSUE TITLE
[David Salter onboarding into MicroProfile] media push 2021

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#438]
**Twitter description:** 
_#MicroProfileInterview: @GeefyGeorge shares his experience onboarding into @MicroProfileIO. http://bit.ly/2oCOtgy

 "Everyone is welcomed at whatever level they can help, whether its code, documentation, blogs, or other support - everyone is welcomed." - David Salter_

**Git ticket** with the design which is still perfect here. https://github.com/eclipse/microprofile-marketing/issues/182

**original tweet for refernce:** https://twitter.com/MicroProfileIO/status/1189917656117325824?s=20

**Blog** updated due to MicroProfile reverting to its original name. 

**Schedule**
1 per month > there are 4 onboarding interviews @rstjames, lets push 1 per week. :)

**Comment by rstjames** [comment]
Scheduled to go out once a month (3rd week) for 2021
