### ISSUE TITLE
[Martin Stefanko onboarding into MicroProfile] 2021 media push

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#439]
**Twitter description:** 
#MicroProfileInterview: @xstefank shares his experience onboarding into @MicroProfileIO!  http://bit.ly/2G33DAO

"Participating in discussions and decisions was really easy. Many of my ideas are already integrated into several MicroProfile specifications" - Martin Stefanko
**Git ticket** with the design which is still perfect https://github.com/eclipse/microprofile-marketing/issues/204

**original tweet for reference:** https://twitter.com/MicroProfileIO/status/1219265826957791240?s=20

**Blog** updated due to MicroProfile reverting to its original name. 

**Schedule**
1 per month > there are 4 onboarding interviews @rstjames, lets push 1 per week. :)

**Comment by rstjames** [comment]
set to go out once a month (last week of the month) for 2021
