### ISSUE TITLE
Add a 2nd click under BLOG header for Speaking on MP waters

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#44]
brainstorming... 

enable the MicroProfiler speaking on MP via events to submit via git issues about those events.
Minimum requirements to be provided on issue:

- name of the session

- name of the speaker 

- twitter or git account

- link of the event 

- date and time

-Speaker must provide the aproximate description of her/his session on issue.

- 2 weeks notice requirement (when possible) 

@rsjames how much time will it take for us to create a 2nd bottom if it doesn't affect current blog guidelines?

If easy to adop, we can create a _NEW_ project under this space to populate those tickets with exact requriements under description as part of how to submit ticket.

what else am i not considering when brainstorming?

I do not want to repeat same message like [I did today](https://twitter.com/ameliaeiras/status/1108451072555638784), yet fun-- it gets bothersome. :) 
-- quote tweet: 
<img width="583" alt="image" src="https://user-images.githubusercontent.com/10731224/54718460-cdc3c100-4b17-11e9-9e59-9eef274f483e.png">

**Comment by rstjames** [comment]
@aeiras let me check I understand this right. 
- You want to add a "Call to Action" button to get people to make an issue for a session they have coming up

- This button would lead them to a github page that will tell them the requirements

We can do this in a few min.  Just need to know what we want to say and have the github link to connect to the button. Are you sure the blog is the best spot? We should have a conference page itself ( future )

**Comment by aeiras** [comment]
@rstjames lets drop the "I" from this and future exchanges first 👍 

- correct-- MP project benefits from having its Contributors feed via issues the events that related to MP, globally. 

- correct-- just as we did with blog guidelines and what we use internally in Tomitribe for events' submmisions, MP will benefit from a process that enables direct feed onto MP activities. 

---
@rstjames using what works based on actions, please draft the bare minimum that anyone must share when adding an event activity. Stated above, i brainstormed with 
Minimum requirements to be provided on issue:

name of the session

name of the speaker

twitter or git account

link of the event

date and time

-Speaker must provide the aproximate description of her/his session on issue.

-- No- the blog space is not the best space yet we don't have the time to adjust or start adjusting MP website today. For now, i recommend we use what we have if it doesn't adjust the excellent traction we have with incoming content via Blog click.

**Comment by aeiras** [comment]
@rstjames can we prioritize (gievn that you stated it will take not much time to complete) this issue to add this feature before the end of this work week please?

There are many MicroProfilers attending events, the sooner we get something to enable them to submit issues with MPevent details the better MP is about attendance if in person or virtual .

**Comment by aeiras** [comment]
MicroProfile MicroProfile Sessions_Social Media Coverage is the new Project within the Mktg Repo created to substain this effort. 

Closing ticket as part of MP website.
