### ISSUE TITLE
[Alex Lewis onboarding into MicroProfile] media push 2021

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#440]
**Twitter description:**

#MicroProfileInterview: @seekingbinary shares his experience onboarding into @MicroProfileIO! https://bit.ly/2ZVAuiV

"If you have an idea or a suggestion, don’t keep it to yourself. If for some reason, it doesn’t go anywhere, the experience is still worth it." - Alex Lewis 

**original Twitter :** https://twitter.com/MicroProfileIO/status/1144245946743607296?s=20
**git issue** https://github.com/eclipse/microprofile-marketing/issues/93

**Blog** updated due to MicroProfile reverting to its original name.

Schedule
1 per month > there are 4 onboarding interviews @rstjames, lets push 1 per week. :)

**Comment by rstjames** [comment]
All set for the year
![Microprofile-onboarding-Interview-alex_lewis](https://user-images.githubusercontent.com/12132146/109826094-c0d40580-7c3a-11eb-8f20-b22cdc1f499f.png)
