### ISSUE TITLE
[Edwin Derks onboarding into MicroProfile] media push 2021

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#441]
**Twitter description:**

#MicroProfileInterview: @edwinderks shares his experience onboarding into @MicroProfileIO! http://bit.ly/2Z2ePZz

"Edwin finds the #MicroProfileCommunity to be very friendly, helpful, and accepting – it doesn’t matter that he’s not part of a big vendor." - Edwin Derks

**original Twitter :** https://twitter.com/MicroProfileIO/status/1161665029365743622?s=20
**git issue:** https://github.com/eclipse/microprofile-marketing/issues/161

Blog updated due to MicroProfile reverting to its original name.

Schedule
1 per month > there are 4 onboarding interviews @rstjames, lets push 1 per week. :)

**Comment by rstjames** [comment]
@aeiras in the past the interview had two people. Who is the 2nd person on this? or will we just have one person from now on?

**Comment by rstjames** [comment]
set for the year.

**Comment by aeiras** [comment]
@rstjames, 

The tweet needs to be fixed. **I finds the M... 
** Please see **above**. 

"Edwin finds the #MicroProfileCommunity to be very friendly, helpful, and accepting – it doesn’t matter that he’s not part of a big vendor." - Edwin Derks

It needs to stay as such b/c it is a direct quote from Edwin while being interviewed by David. He speaks as an interviewee and the quote reflects that. 
In relation to current and future MP<>MP interview media pushes, let's do our best to avoid the adjustment of the content, ask questions as needed.  

Thanks Ryan, 

<img width="589" alt="image" src="https://user-images.githubusercontent.com/10731224/121391078-d6745d80-c902-11eb-9775-69e9a9584e17.png">
Tweet https://twitter.com/MicroProfileIO/status/1401900501764120577?s=20

**Comment by rstjames** [comment]
Updated
