### ISSUE TITLE
[Red Hat Sponsored e-Book] produced by the Foundation - 2021 Website Status

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#443]
@rstjames, 

Please help remove the listed [ebook](https://microprofile.io/resources/#e-book) under the resources page. Thank you! 

@jclingan, 

Quick tracing for you.  
The ebook was paid by Red Hat, yet it was never reviewed nor welcomed MicroProfilers' feedback before its publication.  It is not housed under the MP Content drive. The EF contains the ebook in case you want to do anything with it. 

Much of the content is no longer applicable. As we are going through MP [content inventory ](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0) This ticket is the status update.  

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/10731224/109864556-d4ba4000-7c17-11eb-9e06-1e0feb9906b9.png">

**Comment by rstjames** [comment]
removed
