### ISSUE TITLE
Contributor- documentation and Video with old name- request to fix content

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#444]
https://github.com/GiuseppeScaramuzzino/quarkus-microprofile-restclient/issues/1

**Comment by gscaramuzzino** [comment]
Hello @aeiras ,
the issue has been fixed

**Comment by aeiras** [comment]
Hola, how awesome to see you in this space @GiuseppeScaramuzzino!

You are wonderful, thank you for the prompt turnaround!
  
If you are able, no rush, let's push your MP content broader. 

Please check out the MP Blog guidelines  (improve the steps by submitting PRs, if anything is off) Click "Become an MP Author" https://microprofile.io/blog/

**Comment by gscaramuzzino** [comment]
Hello,
I have created a new issue to become MP Contributor thanks to you

**Comment by aeiras** [comment]
Thank you for becoming the 69 wordpress contributor of MP content Guiseppe! 
Just wonderful! :)
