### ISSUE TITLE
[Community Call discussions] Schedule Media Push 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#445]
**Twitter Description**
#MicroProfileCommunityCalls: Show-up and let your actions show a commitment to the evolution and sustainability of @MicroProfileIO. #MicroProfilers' participation ensures continued growth and development of a well-governed, vendor-neutral #OpenSource ecosystem.

**Calendar**
[Zoom access & agenda minutes](https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles)

**Design focus**  

- #ByCommunityForCommunity
- using the 2020 design card works great, it needs to integrate the Charter's focus goals: _Limited Processes, Experiment and Innovate, No Backwards Compatibility Guarantee, Implementation First, Encourage Brand Adoption, Openness, Low Barrier to Entry._

**Comment by rstjames** [comment]
@aeiras 
Updated the tweet so it would work for twitter. And a new picture below.
 
Not sure what you meant here... _"using the 2020 design card works great, it needs to integrate the Charter's focus goals: **Limited Processes, Experiment and Innovate, No Backwards Compatibility Guarantee, Implementation First, Encourage Brand Adoption, Openness, Low Barrier to Entry**."_

**Tweet:**
#MicroProfileCommunityCalls: Show-up & let your actions show a commitment to the evolution & sustainability of MicroProfile. #MicroProfilers' participation ensures the growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. Join: bit.ly/calendar-zoom-minutes

![microprofile-community-call-2021](https://user-images.githubusercontent.com/12132146/110115802-e554ec80-7db6-11eb-9b30-f74982341ed2.png)

**Comment by aeiras** [comment]
@rstjames, 

Via this comment, I cannot attach or paste the mockup I created to show you what I mean. I will send a mktg email with the ticket in a bit. Thanks for enabling the follow up! you are amazing.

**Comment by rstjames** [comment]
I get the idea... I think it will make everything too busy and this new text will not be in the "safe zone" it probably will be cut off a lot. Up to you... @aeiras and if you want it I think the wording could be more simple. Not the clearest " No Backwards Compatibility Guarantee" 
<img width="1036" alt="Screen Shot 2021-03-08 at 12 59 31 PM" src="https://user-images.githubusercontent.com/12132146/110318799-41fe1480-800e-11eb-9dd1-98dde6699d93.png">

**Comment by aeiras** [comment]
Wow, Ryan, the added words look great with the M. 
MicroProfile has 7 pillars that maintain it. With this design, we want to educate about them! :) I really like how you place them. Thank you!

@rstjames, you are right about too much wording, **Let's adjust to** given that the message no longer applies to Community calls being the decision-making for MP under the WG. 

_Participate in Today's MicroProfile Community Call_

Next call is on March 16th, a day after the mktg call.  Can you help it be set up your 8am or 9am Prague time on the 16th and onwards, just 1 reminder? 

About the Marketing call ticket, do you think it can have the same set of pillars-wording but maybe a different picture in the background as well? That one is needed on March 15th.

**Comment by rstjames** [comment]
@aeiras
I was referring to all the text around the edges is too much. Especially "No Backwards Compatibility Guarantee" but if you want it, ok. But it is not in the "safe zone" 
Is this what you had in mind? 

![microprofile-community-call-2021](https://user-images.githubusercontent.com/12132146/110467308-2579df00-80d7-11eb-9aed-5a6b989b63c4.png)

**Comment by aeiras** [comment]
Yes, @rstjames! 

You are amazing. Thank you for bringing such a clean & simple design. 
I understand about the "safe zone," and that is ok, Ryan. Let's schedule it starting on March 16th. 

By the way, today we have a 1 -off schedule-community call. Would you like to push it via media so that when we take the pic, it can be shared again? I can push it without issue. Do let me know.

**Comment by rstjames** [comment]
@aeiras I can send it out in a few min if that helps. after that I will schedule them for the year.

**Comment by aeiras** [comment]
Amazing Ryan! 

Thank you for always helping so much in MP. You are incredible!

**Comment by rstjames** [comment]
Adjusted tweet:
Join Today's #MicroProfileCommunityCall & let your actions show a commitment to the evolution & sustainability of #MicroProfile. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. bit.ly/mp-cal

**Comment by aeiras** [comment]
wonderful!

**Comment by aeiras** [comment]
@rstjames, there seems to be an issue with the Mp tweet access to the calendar. 
You must get that link to be public and not log-in.

 https://calendar.google.com/calendar/embed?src=gbnbc373ga40n0tvbl88nkc3r4%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by rstjames** [comment]
Join Today's #MicroProfileCommunityCall & let your actions show a commitment to the evolution & sustainability of #MicroProfile. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem.
https://bit.ly/calendar-zoom-minutes

**Comment by rstjames** [comment]
all set for the year to go out couple hours before each call.
