### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor.

### ISSUE THREAD

**Issue by gscaramuzzino** [microprofile/microprofile-marketing#446]
Hello,
I would like to become MP Contributor:

Firstname: **Giuseppe**
Lastname: **Scaramuzzino**
Email: **giuse.scara@gmail.com**

Resources ready to be share:

**MicroProfile Rest Client with Quarkus**
YouTube video: https://youtu.be/8d8GSRZzdsA
GitHub Repository: https://github.com/GiuseppeScaramuzzino/quarkus-microprofile-restclient

**MicroProfile OpenAPI with Quarkus**
YouTube video: https://youtu.be/H1Hf9NHQjSc

**RESTful Web Service with Quarkus** 
YouTube video: https://youtu.be/spWnqkbFgH4

Thank you

**Comment by aeiras** [comment]
Happy Friday, Giuseppe, 

Your MP WordPress contributor access has been sent.   You are welcomed to start sharing MP content aim at teaching others, helping others adopt, learn, use...  the technology.  

 Thank you for choosing to share your current MP content.

**Comment by aeiras** [comment]
By the way, should you encounter any issues with Wordpress, do feel free to re-open this ticket ok. !:)
