### ISSUE TITLE
[Social Media- Twitter Poll] Do you hope to start migration from the javax to jakarta namespace in the next year? #448

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#449]
[[September 2021 MP Twitter Poll] Do you hope to start migration from the javax to jakarta namespace in the next year? #448](https://github.com/eclipse/microprofile-marketing/issues/448)

**Comment by nehasardana09** [comment]
#448 and #449 have the same description. Does it make sense to close one of them or is there any purpose of keeping them both open?

@aeiras @TetianaFTV

**Comment by aeiras** [comment]
@nsardana-bny, 

Than you for the push to get me to bring the Feedback Strategy for discussion to the group on how to use the MP media  to understand MP users, adopters and contributors. 

I will close the 2 tickets and open 1 to enable the creation of the crude skeleton on it. : ) Both tickets are now closed. They are too specific and have served the purpose to remind me of stuff. with your help, yeayy!

**Comment by aeiras** [comment]
Here [[Social Media Monitoring- Gathering Feedback] Continue Yearly Strategy Loop #515](https://github.com/eclipse/microprofile-marketing/issues/515)
