### ISSUE TITLE
Request for microprofile.io post review - MP Rest Client

### ISSUE THREAD

**Issue by gscaramuzzino** [microprofile/microprofile-marketing#452]
Video Tutorial:: Microprofile RestClient with Quarkus

In this video, I am going to explain how to use Microprofile Rest Client to call external APIs in a simple way.

https://microprofile.io/wp-admin/post.php?post=6773&action=edit

**Comment by aeiras** [comment]
Hola Giuseppe, 

MicroProfiler @mehmandarov will review and process your content! :) Stay awesome!

**Comment by gscaramuzzino** [comment]
Thank you so much

**Comment by gscaramuzzino** [comment]
Hello, 
do you have any news about the review of my post?

Thank you so much

**Comment by aeiras** [comment]
Hola @GiuseppeScaramuzzino 

We are still onboarding Rustam, so your blog is delayed. However, I will take over your review and publish it today if all is good. Thank you for your understanding!

**Comment by aeiras** [comment]
Your blog is published Giuseppe! 

Feedback:

- It is MicroProfile, please adjust the intro slide that has the Eclipse in the name on future videos.  The next contribution containing the same slide won't be accepted. 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/10731224/112357233-8f27ea80-8c8c-11eb-8ad7-dbf8af52e425.png">

- please note the modifications in the description of the blog as follows:

- [ ] I added the API repo landing page issues to bring the reader there and maybe push for awareness on the work that needs to be done. Always ask, what's the value of the content of your blogs? Call to action is great, if at all possible. 
- [ ]  I removed the "I". Your tutorial is about some else choosing to check out MP and potentially learn. Always make it about that person. 
- [ ] There is no time for your video in the description. Why is that? Your contribution blog can be improved if you add the exact minutes time you are asking the viewer to commit/invest. Time is the most valuable resource, treat it as such. 
- [ ] You can choose to be a 365 MP contributor who welcomes feedback and interaction via twitter on your videos. For example if you were to add a final line where you state, I am @GiuseppeScaramuzzino and you can find me in Twitter [Handle] to provide feedback or discuss anything about this video... [use your words] that would make you so welcoming and reachable.  Do consider improving how reachable you want to be in your blog, that is if you want to be reachable. 

MP contributor profile is still incomplete: 
Please add your photo, next content won't be published without your profile. :) 
<img width="859" alt="image" src="https://user-images.githubusercontent.com/10731224/112357577-e6c65600-8c8c-11eb-8518-dbc04cfd30ba.png">


Ok, that's it! 

Submit away your MP content and please reach out via this ticket or future ticket with questions or whatever.

**Comment by gscaramuzzino** [comment]
Hello Amelia, 
thank you so much. I really appreciate your actions and advice.
I will follow them in my next article!

Thank you for bringing me in as MP Author!

**Comment by aeiras** [comment]
Your sharing technical MP knowledge opens windows that your options convert into diverse open doors. You are choosing to the walkthrough. A signature, yours to protect and adjust to match your chosen growth.  

When we choose to show up, (this week, you showed up to the public CN4J discussion, yeayy) & you use the processes and tools in place to be a part of a 365 feedback loop, any project & community is better off with contributors like you —also, much more fun to be a part of it because of the flat dynamics. 
You and your contributions are as important as someone that was there on day 0. Why? Because should you desire it, by helping, your influence will increase and you will likely help someone who is in your shoes today.  
This I believe is the best reward for sharing time and collaborating to add value in Open Source. 

Stay safe and rock it!

**Comment by aeiras** [comment]
Your [tweet](https://twitter.com/GiuseScara/status/1375178237077303299?s=20) is most kind, thank you!

**Comment by mehmandarov** [comment]
Sorry for the review taking so long, @GiuseppeScaramuzzino and thanks to @aeiras for reviewing it! 

Great job, Giuseppe! I will do my best to be faster next time. Please publish another video soon, so we can test this! :-)
