### ISSUE TITLE
[MP Product Plan] 2021 MicroProfile Program Plan Slide Deck - Russian Version

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#453]
Make available: 2021 MicroProfile Program Plan Slide Deck in Russian:

Original Program Plan document:
https://docs.google.com/presentation/d/1-mu4dIsfAzLlE81splWBKwsGeRLJhzEWrXgsQ_i0JZQ/edit

WIP here:
https://docs.google.com/presentation/d/1JnbIYsxyNtKcJ3kvkBg9cDpT41b2xy9F5Ag4NmZUvJM/edit

**Comment by aeiras** [comment]
This ticket is fantastic Rustam. 
Now Mitia is still not watching nor collaborating on this space. In order for you to handover his words from Monday's discussion, Mitia needs to be able to join. Recommendation, share the onboarding document you are helping draft with Mitia in the To of that email and MP Mktg forum in the cc'd. :)
