### ISSUE TITLE
[Content Contribution] MicroProfile 5-year anniversary Blog

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#454]
MicroProfile is going to be 5 years old soon. We should use this opportunity to properly promote MicroProfile. The focus is on some well-known influencial individuals and companies that use MicroProfile to solve real-time scenario.

**Comment by aeiras** [comment]
I will contribute, thanks for taking the lead Emily! 
 
The [Announcement](https://drive.google.com/drive/u/0/folders/1EUEsKegOlN22u5u6CpPwmglEkJs_oc0f) folder has been created to enable collaboration awesome @Emily-Jiang

**Comment by manish2aug** [comment]
Hi @Emily-Jiang,

Here are the details about the blog and a production system built with MicroProfile

[Part 1](https://live-with-microprofile.blogspot.com/2021/03/do-you-really-need-sledgehammer-to.html)
[Part 2](https://live-with-microprofile.blogspot.com/2021/03/do-you-really-need-sledgehammer-to_25.html)
[Github](https://github.com/manish2aug/minor-consent)

**Comment by aeiras** [comment]
@manish2aug you have been added as a blog contributor! :)

**Comment by aeiras** [comment]
@manish2aug, 

I have reviewed Part 1.  The blog is pretty fantastic. 
There are a few areas that could use improvements. 

1. Can you fix the section where you introduce MicroProfile in the blog?  Trivia MP document, row 9 could be helpful.  The Tomitribe's blog, linked in the row,  will give you the exact names of the 5 co-Members and also provide you with technical data about what went down back then. There are 3 blogs within row 9 that can improve that section. 
https://docs.google.com/spreadsheets/d/1M0d7U3Yk-Vu3-TdC7zKnQ4qRVODSpD1ih2E4jvNbjoc/edit#gid=0

We can provide a copy/editor for you to collaborate with on the blogs Manish. 
 f so, you can start by dropping the word version of Part 1 blog under [Blogs](https://drive.google.com/drive/folders/1yonVuzmgpH_Mr3WgoqQEYywoJJjOmKBD) & check out how easy it is to work with our copy/editor via google "suggestive more". 

I won't review part 2 until I hear from you. 
Based on what I see, the blog once adjusted could be crossposted into  [MP Blog](https://microprofile.io/blog/), making you a MP Content contributor as well.

**Comment by manish2aug** [comment]
Thank you so much Amelia!

Will check and update.

Thanks
Manish

**Comment by manish2aug** [comment]
Hi @Amelia Eiras ***@***.***>

I have updated the section as suggested and copied the word version in the
shared drive.
Appreciated your time for reviewing, please let me know if something else
also requires a relook.

Thanks
Manish

**Comment by manish2aug** [comment]
Sorry, I mistakenly unassigned myself :(

**Comment by Emily-Jiang** [comment]
@manish2aug I have readded you. I have created [this](https://docs.google.com/document/d/1F2giJt3RCdOoN6wW_Vg-XrSjeLQPnc7INts9yyNRb44/edit?usp=sharing) google doc for us to collaborate. Please feel free to contribute.

**Comment by manish2aug** [comment]
Thanks, Emily!

**Comment by aeiras** [comment]
@manish2aug, 

Thank you for adding the part 1 blog to the word version to enable the copy/editor review.  You can expect the review to start next week : )

 https://docs.google.com/document/d/1Fx_TLmPt55wqCU7bpSzCPU_39rGQ31D8/edit

**Comment by mblevins65** [comment]
@manish2aug @aeiras 
Hello, I'm here to help with the editing.  If you have questions please feel free to contact me at blevins.peggy.65@gmail.com

**Comment by aeiras** [comment]
> Thank you so much Amelia! Will check and update. Thanks Manish
> […](#)

Hola @manish2aug, 

Peggy is ready copy/edit. 
My recommendation is to start a new git ticket so that all exchanges are focused on current Part 1. Just link that ticket this main ticket and done. :)

**Comment by aeiras** [comment]
> @manish2aug @aeiras
> Hello, I'm here to help with the editing. If you have questions please feel free to contact me at [blevins.peggy.65@gmail.com](mailto:blevins.peggy.65@gmail.com)

thank you, Peggy, mblevins65!

@manish2aug, 
Peggy cannot start the editing until the document is added to the Blog Folder [HERE](https://drive.google.com/drive/u/0/folders/1yonVuzmgpH_Mr3WgoqQEYywoJJjOmKBD ) Thanks for unblocking!

**Comment by manish2aug** [comment]
Thanks, @aeiras @mblevins65 
I copied the document to the [blog](https://drive.google.com/drive/u/0/folders/1yonVuzmgpH_Mr3WgoqQEYywoJJjOmKBD) folder, a separate git [475](https://github.com/eclipse/microprofile-marketing/issues/475)  is created

[Part 1](https://docs.google.com/document/d/1xB1EdFxcLxMp2owdr6w1kBcSBSa8-xzua5nhwnnRN80/edit?usp=sharing)

**Comment by aeiras** [comment]
Linked to call to action Community quotes https://github.com/eclipse/microprofile-marketing/issues/500

**Comment by aeiras** [comment]
@Emily-Jiang as promised the blog crude outline is created to help us start the write up
https://docs.google.com/document/d/1u1WQo7tsh484AyOZMvVzPfdYPbgj5RtA4f15Zs94yok/edit#heading=h.bovrgfkmfan1

Ideally, we populate a good first draft in the next 2 weeks, how about eta June 7th?  ( next Marketing call) so on that day's call, we can bring attention to include feedback and more eyes into the write up.

**Comment by aeiras** [comment]
I have added more things to the blog today. I will get back to it later this week. 

I think it is closer to publishing. We can get it out next week Thursday. It will need 3rd & more eyes before publishing once this week's work is completed. :)

**Comment by Emily-Jiang** [comment]
@aeiras I have accepted your update. Please can you all double check to see whether it is read well so that we can add this to our blogs?

**Comment by caitmm43** [comment]
@Emily-Jiang Ticket clean-up time :) Can this one be closed?  Please confirm if yes or no.  Thank you!!

**Comment by aeiras** [comment]
Caitlin, 

I say, we ought to skip the blog on MP 5 years b/c the blog lacks heart. In a sense that for the last 2 years MP has not been able to create new technologies for diverse reasons. 
I believe that 2022 with MP focusing back to innovation will make way for a great MP 6 year blog in June. 

@@Emily-Jiang, you and I are the authors of the blog. What is your take on it? 

+ 1 to close ticket and leave the draft as it is under the drive for later look when writing MP 6 year.

**Comment by Emily-Jiang** [comment]
I am ok with not publishing it but keeping it in the draft so that we can keep on working it.

**Comment by aeiras** [comment]
Thank you, Emily for the follow up. We are in an agreement to not remove the MP 5 blog and use it for Mp. 6 if applicable. :)
