### ISSUE TITLE
[MPWG Page] Email Forums - Update

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#457]
While onboarding monthly MP Stewards, I discovered that the mailing lists need descriptions to be effective. 

- MP community forum: Welcome to the MicroProfile Community discussion! If you want to optimize Enterprise Java for a microservices architecture, then you're in the right place.
- MP marketing forum: Welcome to the MicroProfile Marketing discussion! If you want to broadcast the MicroProfile technology around the world by simplifying messages, creating & maintaining processes that scale & brainstorm new ideas, then you're in the right place.
- MP Working Group forum: Welcome to the Eclipse MPWG formal discussion!  If you want to learn and participate in how the MicroProfile Steering Committee handles the working group processes such as ballots, vote, releases... then you're in the right place. 
- Cloud-Native For Java Alliance, CN4J Alliance [forum](https://accounts.eclipse.org/mailing-list/cn4j-alliance): Welcome to the MicroProfile and Jakarta EE discussion!  If you are interested in technical & not-technical CN4J goal discussions, then you're in the right place.

**Comment by mehmandarov** [comment]
Great idea! Love it! Also, we should probably post the list of available forums on the website somewhere?

**Comment by aeiras** [comment]
The mailing lists are located in the MPWG page under  [Email Forums](https://microprofile.io/workinggroup/). 

Check the page, you can help improve it if you see things that could be clearer, submit a ticket. 

For example, this ticket exists to improve a section of the page. It is possible based to onboarding interactions with a few of you :) So you see, fluid and fun!

**Comment by rstjames** [comment]
All updated
