### ISSUE TITLE
[infra] Rights to assign issues

### ISSUE THREAD

**Issue by mehmandarov** [microprofile/microprofile-marketing#458]
I don't have rights to assign issues to myself or others on this repo. Is it possible to get it? Thanks. :)

**Comment by aeiras** [comment]
Rustam, 

Maybe you can help us pilot the feature created + 1year ago by the EF infra team to allow GitHub to have that capability. 

I will dust the blog. Can you add it to next mktg call agenda, please? 

Currently, only committers at the EF can assign tickets. Contributors can assign tickets themselves only if they create tickets or they comment in a ticket already created. That we fixed, it took 8 month, yet MP got overtaken by the creation of the MPWG in 2020 and never implemented the amazing feature we fought for. Stay awesome and thanks for bringing it up again. Just great!

**Comment by aeiras** [comment]
Rustam, 

Today, you should have received Triage access (check your email) to the MPWG repo. With it you can assign tickets, etc

**Comment by mehmandarov** [comment]
I did! Thank you!

**Comment by mehmandarov** [comment]
Should we close this, or we need to handle a way of doing this for microprofile-marketing repo as well before closing?

**Comment by aeiras** [comment]
Closing it is ok. 
We can dust the fix bug that adds the feature to the EF repos at a later time.
