### ISSUE TITLE
[MP Website] Remove Feb 2020 DataSheet

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#459]
[MP-dataSheet-Feb-18-2020.pdf](https://github.com/eclipse/microprofile-marketing/files/6160200/MP-dataSheet-Feb-18-2020.pdf)
The information no longer applies. Please remove it. [Feb 2020 datasheet](https://microprofile.io/resources/#data-sheet)

@rstjames,  I cannot find the datasheet in the MP drive under the [Content folder ](https://drive.google.com/drive/u/0/folders/1kRrOzf0G7PtG8VJXKODgDpVNOUKSUxnR), which tells me that it wasn't you the one to import into the website. If my assumption is incorrect, please import the PDF into the Content Drive & make a copy under the Community folder. MicroProfilers could own the update work on the 2021 datasheet. Thanks!

**Comment by rstjames** [comment]
I did not make this datasheet. I removed it from the website.
