### ISSUE TITLE
 New Blog Post (Spanish) - MicroProfile, el éxito de microservicios depende de la cultura de tu Empresa

### ISSUE THREAD

**Issue by gdiazs** [microprofile/microprofile-marketing#46]
Hi , I wrote this post : https://microprofile.io/wp-admin/post.php?post=6164
Please, your comments and suggestions.

By The way, I completely forgot to upload a Page Header Image, sorry I read the documentation, but I forgot it. Can somebody reject the post? to edit the post.

**Comment by aeiras** [comment]
Hola Guillermo, @gdiazs! :)

You mean, you need us to delete post? You have full access to delete and adjust blog, there is no need to delete. Please confirm and welcomed to adding your very first MP blog!

**Comment by gdiazs** [comment]
No, I wrote the post but I thougt that after I sent to review I wouldn't be able to change it, but I have added the image succesfully so I think everything is okay.

**Comment by cealsair** [comment]
Reviewed. I will publish it momentarily. Thank you Guillermo for your contribution! I hope you continue providing the MicroProfile community with more insightful posts.

**Comment by aeiras** [comment]
Super chevere Guillermo @gdiazs! 

Closing ticket with @cealsair's as editor and reviewer of post. 
Just wonderful MicroProfilers' collaboration. :)
