### ISSUE TITLE
MP Trademark - Update across the website

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#462]
This week, the EMO confirmed that the MP trademark was filed for MP.  

The Trademark needs to become R in the website and all future swag, all documentation, etc.

**Comment by rstjames** [comment]
updated. Too small to really see what its adjusted.

**Comment by rstjames** [comment]
Also all logos have been updated on the drive

**Comment by aeiras** [comment]
wow, you were able to remember the t-shirts & stickers etc too? @rstjames soooo sooo amazing. Thank you!

**Comment by rstjames** [comment]
@aeiras  Stickers are updated.

**Comment by aeiras** [comment]
awesome!
