### ISSUE TITLE
[CN4J Alliance Meeting] Media schedule

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#463]
@rstjames, 

This just came in today. Thank you in advance for seeing if you can help. 

This week, amazing Tetiana worked on the pilot slides. See the latest version.  If there is no time to create something from zero, we could use something similar to the [1st page ](https://docs.google.com/presentation/d/1wYBNqUHwADvipTC9fW5ugGMbDf_3_JH9skBtyPcI-IE/edit#slide=id.gc994ce748f_0_1)
<img width="565" alt="image" src="https://user-images.githubusercontent.com/10731224/111723976-a8aadb80-8821-11eb-96ac-78c1e1cbaa5b.png">

**design Information:**
- projects logos, MP is missing from above design
- Tuesday, March 23rd
- Time: 9:30am-10:30am PDT
- Where: MP calendar zoom access + agenda (I included the link in the description below :) 

**Twitter message:**
_The 1st public Cloud-Native For #Java Alliance call is happening today between the💙@JakartaEE  and💛@MicroProfileIO communities. #OpenSourceFUN

The communities will collaborate in the pilot communication proposal explaining the 2 projects' synergy. Join: https://bit.ly/calendar-zoom-minutes_

**Schedule**

- once, your AM or at least 5hrs before 9:30 am PDT

**Comment by rstjames** [comment]
Tweet: 
The 1st public Cloud-Native For #Java Alliance call is happening today between the💙 @jakartaee and💛@MicroProfileIO communities. The communities will collaborate in the pilot communication proposal explaining the 2 projects' synergy. Join: https://bit.ly/calendar-zoom-minutes
 #opensource 
![microprofile-jakarta_alliance_call-2021](https://user-images.githubusercontent.com/12132146/111983171-1e58c500-8b0a-11eb-88f5-d490ad29037d.png)

**Comment by rstjames** [comment]
Put one out today and one tomorrow before the call.

**Comment by aeiras** [comment]
It looks great Ryan 💪🏼 Thank you!
