### ISSUE TITLE
[Dzone article fix]  Contributor via Twitter outreach 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#464]
- [Twitter post](https://twitter.com/otaviojava/status/1372204879737946115?s=20)
- [follow-up](https://twitter.com/ameliaeiras/status/1372207797375430660?s=20) by me
- Otavio's [response](https://twitter.com/otaviojava/status/1372551167855767556?s=20)

@otaviojava as stated via twitter, when you write MP focus only on documents that are technical in nature you could choose to crosspost them to MP as content. Keep in mind that rejections will occur if the blogs are not MP technical. :) Abrazos,

**Comment by otaviojava** [comment]
Thank you @aeiras 
My fixes got approved:
https://dzone.com/articles/jnosql-1-0-0-b3

**Comment by aeiras** [comment]
That’s wonderful Otavio! 
let’s retweet you 💛

**Comment by aeiras** [comment]
Done ⭐️ Your prompt actions are amazing Otavio! 

Now, can you help us? 
you are a DevRel, an author, speaker & you connect with many in our community & help broadcast their knowledge. Can you keep an eye on content that contains the wrong MP branding name & just like I did, (in your own way) help correct stuff? 

Ideally, every time you do, you could submit a git ticket 🎫, etc so that others could help you if necessary. 

Think about it & notice how you felt & what you did to get stuff corrected. Educating takes many of us to care & act! 🤗🧸💪🏼

**Comment by otaviojava** [comment]
Yeap, thank you, I'll :)
