### ISSUE TITLE
[Documentation] MP Facts/Trivia Documentation

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#468]
We need to update the MP Questions and Answers space in the [website FAQ](https://microprofile.io/resources/#faq)

[Trivia/Facts about MicroProfile](https://docs.google.com/spreadsheets/d/1M0d7U3Yk-Vu3-TdC7zKnQ4qRVODSpD1ih2E4jvNbjoc/edit#gid=0) needs to be pushed forward & proactively be populated. 

@TetianaFTV, 

the document was introduced a few weeks ago. It needs more eyes and care to be pushed forward!  :)  
happy to help yet I cannot lead the write up of the work, it needs to be pushed via the calls and invite new comers to ask questions via the document that old MicroProfilers can help answer.

**Comment by aeiras** [comment]
updated with https://groups.google.com/g/microprofile-marketing/c/6YNubGBqlCU

**Comment by aeiras** [comment]
@debbiehoffman, 

The mpFacts sheet continues to gather information. 
How do you feel about leading the update on Q&A https://microprofile.io/resources/#faq card?  

if this is something you could help with, that would be truly valuable via a new git issue, where could help us tackle it with you. 

Since the launch of MP on June 27th, 2016, this section has **never** been updated. 
The creation of Trivia document aims at helping us update the Wiki & the Q&A.
As anything updated in the site, a skeleton document is needed to curate what goes in. This needs to spill in the mpWiki  + more.

**Comment by ghost** [comment]
@aeiras  I took a look at the trivia doc. There are a few things in there that would help in updating the Q&A section. I could convert the trivia doc into a Q&A and see if anyone has anything to add before it is published.
Do we want to close this task & start a new one for the creation of Q&A or just move this one out of 'ballpark tasks' and in progress?

**Comment by aeiras** [comment]
Días Debbie, 

this ticket is in ballpark as a constant to remind us that we ought to continue improving knowledge sharing. 

Any improvements will need a new git ticket 🎟 
For example, one coming from you with curating the content, first. 
Once that is done ✔️ same ticket can be used to maybe pull Ryan to help with export if you prefer to delegate that part. Etc! 💛

**Comment by aeiras** [comment]
With the update on MP FAQs the Fact document will be added to the Website and proactively adjusted. https://github.com/eclipse/microprofile-marketing/issues/565

Thank you, Debbie!
