### ISSUE TITLE
[Documentation] Mktg Call Monthly Stewards Onboarding

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#469]
@mehmandarov, 

You are currently writing the o[nboarding document](https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit) to help Monthly Stewards share the workload. Such a task needs to be tracked via a git issue. 

All MP tasks must be tracked via git issues. Choose the relevant Repo :)

**Comment by mehmandarov** [comment]
Good point! You mean an issue in addition to this, or we can use this one? I have just pinged folks on the mailing list to have a look and suggest improvements.

**Comment by TetianaFTV** [comment]
I think the current task can be used for this purpose, just need to set @mehmandarov as assignee.

**Comment by edbratt** [comment]
I'd recommend the following be added to the Steward's onboarding document:
After the call
Review call minutes and finalize the content.
(Optional) Create a named revision of the document (Marketing Committee Minutes - YYYY-MM-DD)
Create a ticket to the YouTube administration team to upload the Zoom recording (for example, see issue #561)
(What, if anything is done to the Meeting Minutes?)

**Comment by ghost** [comment]
Hi @edbratt 
 I updated the onboarding doc with your suggestions. 

I've also gone through and accepted all the changes and updates I made to this document last month because no one has commented or put any more feedback here after several weeks and a couple mentions of the doc, so I felt it was time to move it forward.

@mehmandarov can you turn the onboarding document into a Wiki? I believe that is the next step and looks like from history of comments you were planning to do that.

**Comment by aeiras** [comment]
Hola @debbiehoffman, 

Two choices to close this fun ticket:
 
1) @mehmandarov,  who has Triage access to the MPWG repo, sends a PR, and you approve it with your Write access. 
Or 
2) you create the page without PR in the repo and done. 
--- 

I have sent you a private email to follow up on your Write access to the MPWG repo. That is where the document needs to land. 

https://github.com/microprofile/microprofile-wg/wiki

As soon as you access your write access, you can create the document from work completed on that draft and done. No PRs needed. 

 Ideally, we meet the documentation that is only awaiting its export, latest next week. 

Thank you so much for bringing this collaborative task to a close. You rock!

**Comment by aeiras** [comment]
@@nsardana-bny, 

This is the document mentioned on Monday that needs export into MPWG wiki :) Thank you for finalizing your review on the write up. :)

**Comment by caitmm43** [comment]
@aeiras @mehmandarov @TetianaFTV @nsardana-bny @debbiehoffman 

Hello all, 

Since this ticket has been consolidated into #586 and is also being worked on in ticket #632, can it be closed?  Please add your comments here and update the minutes accordingly.  Thank you!  :)
