### ISSUE TITLE
MP Session coverage help- template

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#47]
**Are you giving a MicroProfile Session soon? Do you want MP coverage to promote it?** 
Create a new issue with the required information & we will help promote your session. 

**Minimum requirements to be provided on issue:**
1. name of the session
2. name of the speaker
3. twitter & git account
4. link of the event
5. date and time
6. Speaker must provide the description of her/his session on issue.
7. Two weeks notice requirement (when possible)

**Comment by rstjames** [comment]
@aeiras we need this as a project I guess... But I am unable to create them now. To be able to create the CTA on the blog I will need a link to a Project with this content.

**Comment by rstjames** [comment]
@aeiras Blog would have an banner on the right side bar. Thoughts? 
![MP-coverage-banner](https://user-images.githubusercontent.com/12132146/55167984-43f8a100-5172-11e9-859d-809c1f07fad2.png)

**Comment by aeiras** [comment]
@rstjames [Repo project](https://github.com/eclipse/microprofile-marketing/projects/5) has been created.  

Ryan, the design is simple and it looks great. 

NOW, lets adjust the content of it to or similar:

Are you a MicroProfile Speaker?
Your dedication to THAT session needs MP media coverage! 
Submit an MP Marketing issue

**Comment by rstjames** [comment]
@aeiras banner has been added to the blog sidebar and linked to MP github projects.
![MP-session-media](https://user-images.githubusercontent.com/12132146/55229970-ba52dd00-521e-11e9-9e33-e5356d2b313d.png)

**Comment by aeiras** [comment]
@rstjames this ticket is re-openned due to the possitioning of the call for action on filing an issue in the blog below right part of the tab. 

That doesn't work as it is not noticiable. I have asked JL to check that page and he doesn't even see it, confirming the lack of value of the possion. 

Lets move call for action to the main tab click under the Resources tab. Thanks.

**Comment by aeiras** [comment]
@rstjames the link to the click bottom needs to be to Project 5 dedicated to the guidelines of the task:  https://github.com/eclipse/microprofile-marketing/projects/5
