### ISSUE TITLE
[ Garden State JUG ] Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by mpredli01** [microprofile/microprofile-marketing#470]
The Garden State JUG would like to submit a blog post about joining the MicroProfile Working Group.  I will serve as contact to add the blog post.  My email is mike@redlich.net.

Thanks!

**Comment by TetianaFTV** [comment]
Hello @mpredli01

I've added you as a contributor to MicroProfile blog (you should receive the email with credentials). 
Now you can upload a blog post. Please make sure to add SEO details, the featured image would be also great.

When it is ready, please send the link to this git issue, so we can review and publish it.

Thanks!

**Comment by mehmandarov** [comment]
I believe this task can be now closed, but I don't have permissions to do so. Pinging @aeiras. Can you help please closing this issue until we get the issue with permissions sorted?

**Comment by TetianaFTV** [comment]
The only point - @mpredli01 please edit the title of the issue to include [Garden State JUG], so it's easier to track the tasks based on their titles. And then feel free to close it.

**Comment by mpredli01** [comment]
Hi @TetianaFTV:

Sorry for my slow response in getting the blog post published.  I will try to get it published this week.  The title of the blog post will be: "**GSJUG and MicroProfile: Perfect Together!**"

All the best,

Mike.

**Comment by TetianaFTV** [comment]
No problem, Mike. Just ping here when it is uploaded.
Also, please prepare tweet text beforehand, so we can share the article after publication.

**Comment by mpredli01** [comment]
Hi @TetianaFTV:

I uploaded the blog post on the WordPress site yesterday afternoon.

All the best,

Mike.

**Comment by aeiras** [comment]
Mike, @mpredli01,
I am so very excited about GSJUG onboarding blog that I did the first review just now. 
Created a new cathegory, MPWG Onboarding Members under MP Community. :) 

**Request for GSJUG:**

- new ticket, provide a Members quote to be added to Prospectus and MPWG page. Thank you! 

Tetiana has  the ownership on the final review & publishing!

**Comment by TetianaFTV** [comment]
Hi @mpredli01

SEO meta tags should be added (below the content part there are fields for that).
Also, please upload featured image (in the right part of post editor)

**Comment by TetianaFTV** [comment]
Congrats, the article is published (I've added SEO)
https://microprofile.io/2021/04/27/gsjug-and-microprofile-perfect-together/

@mpredli01 please tweet the article and add the link to the tweet post here, so we can re-share from MP account

**Comment by mpredli01** [comment]
That's awesome, @TetianaFTV!  Thanks for the opportunity to post this!  I just tweeted about it and you can find it [here](https://twitter.com/mpredli/status/1388163882624106503).

Have a great weekend!

**Comment by aeiras** [comment]
Mike 🤗 before you go off to a peaceful weekend, can you please share the blog & tweets via the MP community forum? 
None but the GSJUG can do that ☀️

**Comment by aeiras** [comment]
@mpredli01, 

Using the MP media, we would like to push the blog as well. Can you help improve the message below or create a new message, please? :) 

**Tweet:** uses your words to introduce the blog. It answers why the JUG joined the MPWG :) 

#MicroProfileMemberOnboarding: Under the new MPWG Charter, @MicroProfileIO continues to be an #OpenSource project with #OpenCommunications.   @GardenStateJUG members have the ability to help steer the direction of MicroProfile. 

Read more: https://microprofile.io/2021/04/27/gsjug-and-microprofile-perfect-together/

**Comment by aeiras** [comment]
Thank you Mike for the review, i saw your tweet which I count as +1 from you. 

@rstjames can we create a unique design (template works too that allows for changes)  that welcomes GSJUG as a MPWG member  and use the tweet above as the body content with the highlight of the onboarding blog? Let me know what else you need. This goes into the decision that we will push Members joining with a template that can include fun stuff about the member like logo, etc! ETA this week. :)  Thanks

**Comment by rstjames** [comment]
@aeiras the tweet seems off if this is to promote @GardenStateJUG becoming a member. Thoughts on the rewrote below. 

Tweet:
#MicroProfile is proud to announce that the @GardenStateJUG has become the newest MicroProfile Working Group Member (MPWG). We are excited to have the Garden State Java User Groups help steer the direction of MicroProfile.
Read more: https://microprofile.io/2021/04/27/gsjug-and-microprofile-perfect-together/

#opensource #oss

**Comment by rstjames** [comment]
This would be the template. So all that would need to be added is the new member's logo

![working-group-new_member](https://user-images.githubusercontent.com/12132146/118001519-1ae1fd00-b347-11eb-9ebe-bf1544f9b82e.png)

**Comment by aeiras** [comment]
@rstjames, 

Your tweet reads fantastic, it is scalable for the guidelines on this iterable task, +1 instead of using quotes from the onboarding blog. 
Design looks great. 
Please help us tweet it and close this ticket with the tweet link. :) 

--- Ryan, 

Under designs can you please create a new folder with the design template and the example of the design with GSJUG. You rock! 
I will write the quick wiki on task and provide links, etc. 

We need to also submit a tweet for iJUG & Fujitsu this week. 2 git issues coming!

**Comment by rstjames** [comment]
tweet template would be:

#MicroProfile is proud to announce that the _______________________ has become the newest MicroProfile Working Group Member (MPWG). We are excited to have the ________________________ help steer the direction of MicroProfile.
Read more: LINK

#OpenSource #OSS


I will send out the tweet in a few min with the visual. @aeiras
