### ISSUE TITLE
[MPWG- Marketing Calls for Q2] add to the calendar

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#471]
We discussed this but no ticket yet. Here you go, John. Thank you! 

Calls might be deleted, as per need by the monthly Stewards and those working on MPWG tasks.

**Comment by aeiras** [comment]
Today, John created the Q2 potential calls in the zoom integration. 
I went ahead and added them to the MP calendar for every other week when the Mktg meeting is not happening. 

The idea is to have a secure space to use **if/when**  for example Trademark work needs live-discussion. 
The pilot was the Budget call on April 5th, I believe that that time was valuable and effective to progress in the task at hand. 

Any MicroProfile involved in the MPWG activities can make use of the 1hr. Agenda is required the Thursday before the call to the Marketing forum & / or Community forum (as applicable based on the topic)

Currently, only John & I have access to the be co-hosts of those calls.

**Comment by mehmandarov** [comment]
Great! Thanks! If I understand the purpose of this correctly, we will need to use that already next week to move today's meeting to the 19th instead. Looping in @TetianaFTV as the call host (and myself as her co-host).

**Comment by aeiras** [comment]
Correct, Rustam. 

I have adjusted the calendar event from MPWG call to a regular marketing call. There is no extra steps to take, as the same call's processes apply.

**Comment by aeiras** [comment]
oh and now, at least for Q2, the calls can be used for any relevant topic MicroProfilers deemed as a priority.
