### ISSUE TITLE
[MP Website] Add Program Plan Presentation

### ISSUE THREAD

**Issue by TetianaFTV** [microprofile/microprofile-marketing#473]
Hi, 

We need to add program plan presentations in all available languages to the website.

Currently we have a block with MP release presentation
https://microprofile.io/resources/#presentation

I think this block can be adjusted to include both presentation types.
The text on the page can be changed in the following way:

--
**MicroProfile Presentation**
These presentations cover the when, where, what, how and why of the MicroProfile initiative. Following the links you will find all the required information within the files that can be reviewed, downloaded and shared!
- [MicroProfile Overview Presentation](https://docs.google.com/presentation/d/1tILNRRjr6jxIM77m6zQ4JQQdXpqkGIg0pQHcL9J3pog/edit)
- [MicroProfile Program Plan Presentation](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C)

**[Get The Presentations](https://drive.google.com/drive/folders/1yN_HhFmB9CfZR-t6OIhMVjyZs8BY_7qY)**

--

[MicroProfile Overview Presentation](https://docs.google.com/presentation/d/1tILNRRjr6jxIM77m6zQ4JQQdXpqkGIg0pQHcL9J3pog/edit) should be updated (as far as I understand there is [appropriate task](https://github.com/eclipse/microprofile-marketing/issues/460) for that) and uploaded as Google Slides to [this folder](https://drive.google.com/drive/folders/1U599utXHUt1CrmnyJSwdiOtxbnjacEGx).

I've already uploaded MicroProfile Program Plan Presentations in PDF format to [the required folder](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C). Anyway, if there are going to be any edits we can re-upload them later.

Let me know what you think on the offered steps and text changes.

**Comment by aeiras** [comment]
+1 Tetiana on bringing the data together.

The git ticket on the presentation you see comes from 4.0 Release. We need
to fix what current is with respect to that presentation to include the
past releases as well. Every presentation carries all the past releases,
like that we never have to worry about updating the link of the
presentation... etc.

Glad to see it in the minutes, lets discuss. :)

Amelia Eiras
twitter.com/ameliaeiras
Tribe: http://tomitribe.com      https://tribestream.io
OSS:  http://microprofile.io     https://jakarta.ee

**Comment by aeiras** [comment]
oh wow, i used email to reply and it sent the entire thing. weird.

**Comment by TetianaFTV** [comment]
Then the MicroProfile Overview Presentation can be linked to the folder 
https://drive.google.com/drive/folders/1U599utXHUt1CrmnyJSwdiOtxbnjacEGx
Here later we can upload other release presentations if any appear this year.

**Comment by TetianaFTV** [comment]
@rstjames 
as discussed on the MP marketing call yesterday, here are some edits that can be already done on the site to include the links to presentations:

1) https://microprofile.io/
- in the second block under the specs add the button [**MicroProfile 4.0 Presentation**](https://drive.google.com/drive/folders/1Med3ls-MuwWA372PkgFPdEMLIDIjAeMT)
- in The Mission block add button [**Program Plan**](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C) with link 
 
2) https://microprofile.io/workinggroup/
in **Program Plan & Budget** tab change the link to https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C 
 
3) https://microprofile.io/resources/#presentation
in MicroProfile Presentation block change the text and delete the button (there will be two links instead) in the following way:

These presentations cover the when, where, what, how and why of the MicroProfile initiative. Following the links you will find all the required information within the files that can be reviewed, downloaded and shared!
- [MicroProfile Latest Release Presentation](https://drive.google.com/drive/folders/1Med3ls-MuwWA372PkgFPdEMLIDIjAeMT)
- [MicroProfile Program Plan Presentation](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C)

Also, I think this MicroProfile Presentation block should be moved up instead of Eclipse MicroProfile White Paper 2019 (as it is already outdated). And below (where currently presentation is placed) there can be added a new block with the link to C2A cards that people can use for social media posts (I left appropriate comment in [the related ticket](https://github.com/eclipse/microprofile-marketing/issues/366)).

**Comment by rstjames** [comment]
All updated.

**Comment by TetianaFTV** [comment]
@rstjames looks great but it seems one edit is missed
the link on [Working Group page](https://microprofile.io/workinggroup/) here should be https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C
![image](https://user-images.githubusercontent.com/38689227/116404933-6668b700-a82f-11eb-8bf1-02eaec4ab031.png)

**Comment by rstjames** [comment]
@TetianaFTV  fixed

**Comment by Emily-Jiang** [comment]
As for the program plan link, I think it links to 2021 files. What will happen when we enter 2022. I think it is better off to link to a folder which contains the up to date program plan and then move the past program plans to archived folder or something similar. @rstjames @TetianaFTV thoughts?

**Comment by aeiras** [comment]
+1 Emily. Anything that is scalable and requires no human attention should be always preferred.

**Comment by rstjames** [comment]
Also agree with this @Emily-Jiang . This should be the standard for any linked files on the site. That was we do not need to update all links each year.

**Comment by TetianaFTV** [comment]
No objections to that. I renamed the folder with [Program Plan presentations](https://drive.google.com/drive/folders/1hj-o5s2-LXBpuw0h_xKkJVQ-iz265K6C) (deleted the year) and added extra folder [Archived](https://drive.google.com/drive/folders/1WVLezUqlirMpvqxsGEjyxdwXMnmbUhE9) to move outdated presentations there when we have new one next year. The link remains the same, so there is no need to change it at the site.

In order to use the same scheme with unchangeable link for release presentations, I've create a separate folder and placed there a copy of 4.0 release. So now we need to paste this link everywhere where we have a release presentation mention
https://drive.google.com/drive/folders/1zqIzegskeYUCualDek3Wq4Sle9qW-_eY
In future, we'll be just moving these presentations to Archived folder also and uploading there the latest one without need to change anything on the site. Is it ok for everyone?

**Comment by aeiras** [comment]
+1! :)

**Comment by Emily-Jiang** [comment]
Thank you @aeiras @TetianaFTV @rstjames ! Great team work!

**Comment by rstjames** [comment]
updated the links on the home page and resources page. I couldn't find where else it needed to be replaced. If anyone finds a link I missed please let me know.

**Comment by TetianaFTV** [comment]
seems all fine. thanks, Ryan!
