### ISSUE TITLE
[MP Blog] Microprofile, a knight or just another pawn

### ISSUE THREAD

**Issue by manish2aug** [microprofile/microprofile-marketing#475]
**[Review required]**

This issue refers to the work that needs to be done for an article to be published on the MP blog. 

This article sheds light on the requirement, problem statement, a bit of history\background about the MicroProfile, and getting the development environment ready for the required service

This article also touches on the aspect that was discussed at the meeting held on 15th March about sharing some systems which are live in production and making use of MicroProfile, as part of #454 

[Part 1](https://docs.google.com/document/d/1xB1EdFxcLxMp2owdr6w1kBcSBSa8-xzua5nhwnnRN80/edit?usp=sharing)

**Comment by aeiras** [comment]
you are wonderful Manish! 

@mblevins65 thank you for your copy/edit help!

**Comment by mblevins65** [comment]
@manish2aug @aeiras it took me a bit of time, but I have edited Part One.  It's ready for you to review.

**Comment by manish2aug** [comment]
Thank you so much @mblevins65 for your time, efforts and suggestions! 
Have accepted the suggestions and updated the document.

**Comment by manish2aug** [comment]
Hi @aeiras, can you please guide here, what should be the next step now for this ticket? Should I add the second article in document form and should open a new ticket?

**Comment by TetianaFTV** [comment]
Hi Manish,

Are these two articles meant to be published on MicroProfile blog in the near time? 

I've just added you as a contributor to the MP blog, you should receive access details to your email (the one mentioned in the article document).

Now you can upload the materials there and save as draft articles. Please don't forget to add SEO meta description.

Also, prepare tweet texts to promote these articles. You can add them to this ticket.

When the content is going to be approved by the community, we will publish the article and share it via Twitter.

P.S. 
- Please edit the git issue title to mention the topic of the article, e.g. **[MP Blog] Microprofile, a knight or just another pawn.** This makes task tracking easier without even opening each of them 
- There is no description at the beginning of the ticket, so it's difficult to get the point of the task, so would be nice if you can edit it by adding short explanation (sample: The article called "Bla bla" is planned to be published on MP site. The topic is covered in Part 1 and Part 2. Review is required.)

**Comment by manish2aug** [comment]
Thanks, @TetianaFTV, updated the issue as suggested!

This is actually one big article revolving around the motivation of using MicroProfile for one production live system but based on the length of the article I had to split it into two articles. 

I have also copied the second [article](https://docs.google.com/document/d/1jXhLy4yx-P2yGQqwPbZnsWE6tVDs7n-bGAhXiWApWp8/edit?usp=sharing) to the blog folder and it is also ready for review

Thanks for the access, I will add the first part there as a draft copy.

**Comment by aeiras** [comment]
@manish2aug, 

Tetiana is 100 correct on the blog (s) being valuable as a crosspost in MP blog website. She rocks to enable you to add the 1st blog as well. @TetianaFTV you rock!

Now, 
2nd article needs to follow suit like this ticket and be worked on its own ticket to enable copy/edit review @manish2aug. 

At the end the 2 articles will be used in the MP 5yrs anniversary blog yet that's not the only value for them as Tetina nicely pointed out. 

Brainstorming here:
@TetianaFTV though it would be great for Manish to provide a written tweet for his blog for MP to push forward, that is not an scable action that we can own. 
Better is to have Manish publish his blog via his twitter account, each part and add the @MP handle to that tweet to enable the handle to re-tweet. 
**Why?**
There are only a few Admins who volunteer to help with MP push.  When I help, I re-tweet technical valuable content if the author uses the @ MP handle, only. 
We cannot own publishing MP Content with a single tweet bc we want and look forward to more content being added to MP blog and there won't be enough of us helping to help push that content, formally. We don't want that. re-tweets are great for that matter. 

Happy for us to discuss more on next Mktg call if there is the need.

**Comment by manish2aug** [comment]
Thanks, @aeiras , a separate issue (#482 ) created focused on the second half of the article

**Comment by aeiras** [comment]
> Thank you so much @mblevins65, for your time, efforts and suggestions!
> Have accepted the suggestions and updated the document.

@manish2aug I have added a few recommendations to Part 1 now that @mblevins65 has nicely completed the review. :) 

Mainly there are connection issues btw the 2 parts that need to be fixed.

**Comment by manish2aug** [comment]
Post is uploaded and saved as a draft article on MP Blog

**Comment by aeiras** [comment]
@manish2aug, 

Congratulations on your very 1st MP Wordpress content. You did it!  Your blog is now published. 
[MicroProfile, a knight or just another pawn [Part 1 of 2]](https://microprofile.io/2021/04/19/microprofile-a-knight-or-just-another-pawn-part-1-of-2/)

**Page Header Imagine** is missing. 
Please log-in and add the internal blog picture as a "set featured image"?  See below, All blogs need a feature pic, otherwise the presentation of the blog looks bare and not welcoming. 

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/10731224/115296132-6968f680-a10f-11eb-8b58-e63af54a0b1e.png">

Once you do, you could tweet using@ MP handle and answer why anyone should care to read the blog. Stay awesome!

**Comment by manish2aug** [comment]
Thanks, @aeiras!
It seems the post is not editable for me anymore as I do not see the link for "Edit", maybe because it's already published or maybe because of edit rights, can someone please assist

**Comment by aeiras** [comment]
Updated Manish! 
I believe you will be able to provide valuable feedback on the new "Publishing documentation" and maybe you can even help improve the current [Guidelines ](https://github.com/microprofile/wpsite)  Just submit PRs to the wiki & allow review.

**Comment by manish2aug** [comment]
Thanks, @aeiras! Sure will definitely check

**Comment by aeiras** [comment]
Manish, 

Almost missed your [ blog tweet](https://twitter.com/manish2aug/status/1384253872764383236?s=20). Now retweeted via MP handle. That's why adding the tweet in the ticket is necessary! 

As you heard today, we will formalize the write up of the "internal" Publication HOW Guideline,  as part of the last portion of the current Content guidelines (new wiki). 

I will help you close this ticket by adding your tweet here. :) 

@TetianaFTV if there is anything a miss, please let us know.
