### ISSUE TITLE
[MP Youtube PlayLists Creation] Diverse Lists

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#476]
@jclingan can you help us create Youtube playlists covering the below meetings?

1. Context Propagation
2. Jason Web Tokens, JWT
3. OpenAPI
4. OpenTracing
5. GraphQL
6. Metrics
7. Starter  
8. Long Running Actions, LRA
9. Architecture 
10. Marketing 
11. Cloud Native For Java, CN4J 
12. MPWG Steering Committee

**Comment by Emily-Jiang** [comment]
I suggest before creating youtube playlist we need to talk with the spec teams for them to opt in first. By the way, I think OpenTracing, LRA don't have calls. Not sure whether there is calls on JWT. At the moment, I think there is value to publish the following playlists

1. Marketing
2. Normal hangout
3. Technical
4. CN4J
5. Steering committee

I would put the others on hold for now. By the way, you have got GraphQL and Metrics mushed together:o.

**Comment by aeiras** [comment]
mushing fixed. :) thanks Emily!
So for the Architecture call, technical is not sufficient in my view,  you and Roberto are the current Zoom admins, correct? @radcortez @Emily-Jiang 
Infra MP has been updated based on[my assumption](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1206744069) Zoom tab. Thanks for the follow up! 

While obtaining the 2 admins on the API's, I am directly asking those MicroProfilers if they plan to record the calls. 
My recommendation is to record all calls yet we cannot enforce that. 

with @jclingan -- we chatted about autosetting recording on all calls, yet there is always a few minutes of informal chatter, so we have placed the trust **to record to the Cloud to the Admins**.

**Comment by Emily-Jiang** [comment]
> So for the Architecture call, technical is not sufficient in my view, you and Roberto are the current Zoom admins, correct? @radcortez @Emily-Jiang
> Infra MP has been updated based on[my assumption](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1206744069) Zoom tab. Thanks for the follow up!

Yes. We will take turns to chair the calls. By the way, I updated the spreadsheet by referring it to Technical calls, which is the new name we adopted this time.
I also put me and Rudy as the admins for Starter calls.

> While obtaining the 2 admins on the API's, I am directly asking those MicroProfilers if they plan to record the calls.
My recommendation is to record all calls yet we cannot enforce that.

+1

**Comment by aeiras** [comment]
That's pretty wonderful, Emily!

**Comment by jclingan** [comment]
> I suggest before creating youtube playlist we need to talk with the spec teams for them to opt in first. By the way, I think OpenTracing, LRA don't have calls. Not sure whether there is calls on JWT. At the moment, I think there is value to publish the following playlists
> 
> 1. Marketing
> 2. Normal hangout
> 3. Technical
> 4. CN4J
> 5. Steering committee
> 
> I would put the others on hold for now. By the way, you have got GraphQL and Metrics mushed together:o.

[I've already created playlists for these.](https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w/playlists)

**Comment by aeiras** [comment]
You are so fantastic @jclingan! You even added a few 2021 recordings to the lists, just wow!

Based on git issues, there are currently 8 calls happening not including the occasional CN4J & Steering calls: 

**Create Playlist API group**

-  Context Propagation (Completed happening- pilot zoom APIs)  
- Starter    @Emily-Jiang can you help with Admin access on this one so that the zoom link is updated. Thanks. 
- JWT 

**Work in progress- not sure?** 
- GraphQL (work in progress)
- Metrics

**Not happening/Deleted from Calendar**

- OpenAPI (completed- not happening)
- OpenTracing (completed- not happening)
- Fault Tolerance - completed- Terminated 

By the end of the month, given that there are tickets for each of the calls that help us gather intel, I will delete the calls that are not using the Zoom Admin account & use the community minutes space so complete clean-up.

**Comment by Emily-Jiang** [comment]
>     * Starter    @Emily-Jiang can you help with Admin access on this one so that the zoom link is updated. Thanks.
>
@aeiras what do you mean on the above? I think @jclingan needs to create the repeating call on zoom first and then share the host code with us and then the google calendar can be updated with the new link. Right?


> 
>     * OpenTracing (completed- not happening)
I am going to put a team together to start the call next week. See [this](https://groups.google.com/g/microprofile/c/KrK47t_Dm0k) conversation. When starting this call, we will create on zoom and google calendar using the new MP zoom account.

> By the end of the month, given that there are tickets for each of the calls that help us gather intel, I will delete the calls that are not using the Zoom Admin account & use the community minutes space so complete clean-up.

I think it is best to send an email to google group so that the spec groups is aware of this and will take appropriate actions.

**Comment by aeiras** [comment]
Hola Emily, 

The code can be provided before the call is added to the calendar. You are correct, currently, only Kevin and John can update the internal Zoom schedule that mirrors the MP calendar. 

I will submit a new git ticket where I suggest you get added as a 3rd INFRA Zoom Admin so that you could help with the creation and maintenance of API's zoom access/etc.  You said yesterday that you wouldn't mind helping upload the API recordings to the Youtube playlists & (that includes tweeting them as well). 
Please correct me if I understood wrong. :) 

Correct about the 3rd follow up on calendar update. I have sent 2 to the community month this year. The next one should state that all calls not using the Zoom access are deleted to help clean up INFRA. There are issue tickets for those calls still open and for the one you mention, lets create a new ticket. 

MicroProfilers can communicate simply via git issues to get this done. I would love for you to own that communication, Emily! Why? b/c you attend many technical calls.

**Comment by Emily-Jiang** [comment]
@aeiras sure, I can help with the zoom admin tasks etc.
@jclingan can you create a playlist for MicroProfile OpenTelemetry and then upload this first recording there? I have temporarily placed today's recording into our google [drive](https://drive.google.com/file/d/1fcebUmnCSk72OH6cpUw3jzg0Dq8QFoiC/view?usp=sharing). Please remove it once you have published it to the youtube playlist.

**Comment by jclingan** [comment]
Will do.

**Comment by aeiras** [comment]
As usual, @Emily-Jiang thank YOU for choosing to make @jclingan scalable with INFRA stuff. You are fantastic!

https://github.com/eclipse/microprofile-marketing/issues/497  This ticket will track your INFRA access increase. Remember to adjust the INFRA document and place it in this ticket as you complete the 2 access- steps. 

In the future, when John is off, you could cover. When you are off, John can do stuff. 
Especially now that we are adding the APIs to the mix, we need someone like you to own, for example, the cloud recording exports to the Youtube mailing lists. We need to add the API's events to the calendar internally, tweet the recordings, etc.

@jclingan, clearly, you are amazing!

**Comment by aeiras** [comment]
Thank you everyone involved!
You have enabled the youtube playlist 2021 monthly tweets to go out with latest clean up! 
https://github.com/eclipse/microprofile-marketing/issues/502
