### ISSUE TITLE
[Technical Discussion] Technical calls

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#477]
when: bi-weekly
Day: Tuesday
Time: 11am PDT

Calendar

Twitter description
Answers: Why should I join and contribute to this project?

**Comment by aeiras** [comment]
Yes, Emily👍 
The description needs to follow suit with current tweets on joining the Community, Mktg, Steering & CN4J calls.

**Comment by Emily-Jiang** [comment]
Join Today's #MicroProfileTechnicalCall to discuss technical issues and contribute to technical goals #MicroProfile. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. 
https://t.co/GOU4zQzjRo?amp=1

**Comment by aeiras** [comment]
great usage of the message @Emily-Jiang +1. 

The adjustment is to use the MP Calendar link instead. 

_Join Today's #MicroProfileTechnicalCall to discuss technical issues and contribute to @MicroProfileIO's technical goals. #MicroProfilers' participation ensures continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. https://bit.ly/calendar-zoom-minutes_

**Comment by aeiras** [comment]
Hola @TetianaFTV,

I couldn't assign you to the ticket, so adding you via comments in case you want to help schedule this call. 
That means that the design needs to be created as well. 

I have assigned @rstjames as well in case you want to skip it.

**Comment by TetianaFTV** [comment]
hi, we've made such card based on the previous designs, so feel free to use it for sharing if it works ok

![MicroProfile-Technical-Discussion](https://user-images.githubusercontent.com/38689227/114722239-ed9b3280-9d39-11eb-9598-5fc37327707b.png)

**Comment by aeiras** [comment]
Dias Tetiana, 

It looks awesome. 

Do you know how to schedule recurring tweets via MP? 
Example[ Prospectus ](https://twitter.com/MicroProfileIO/status/1382269145492824065?s=20)

The technical call needs to be scheduled for the day of the meeting (~5hrs before the start) on  April 20th and every 2 weeks from there for the rest of 2021 :) 

MP media currently uses Buffer, yet Ryan is bringing us some other options that sadly he was not able to show this week.  

Ryan could write how stuff is done, if needed, as part of media documentation for media Admins. Debbie also is aware of the consecutive scheduling

HUgs

**Comment by aeiras** [comment]
oh, this is also part of the [Consecutive Yearly Media Messages](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)

As the mktg email stated, the items in bold have not been tackled yet.

**Comment by TetianaFTV** [comment]
@rstjames or @debbiehoffman, can you please cover Twitter scheduling of the mentioned post about Tech Call?

**Comment by rstjames** [comment]
Ill take care of it

**Comment by rstjames** [comment]
set for the year.

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1384522242080448527?s=20
