### ISSUE TITLE
Schedule a recurring Tweet on Submit your MP Session for 2019

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#48]
The MP Contributors now [can submit issues](https://microprofile.io/resources/) to get their MP sessions, workshops, and all their knowledge transfer via virtual or in-person forms,  globally. 

The reminder of that needs to be set as a tweet every week. 
My recommendation is to set it for Tuesday 9am PDT, starting next Tuesday April 2nd to end of 2019. :)

**Comment by aeiras** [comment]
@rstjames  amazing turnaround on CFA submit your session via the resources page. 
To finalize the CFA, a schedule tweet will keep a weekly reminder blast. 
Q&A, if any-- welcomed!

**Comment by rstjames** [comment]
@aeiras 
Tweet message: 
Are you a MicroProfile Speaker? Your session needs MP media coverage!  Submit an github issue  http://bit.ly/2IhxsQa (with required information)  & we will do our best to push your session to the @MicroProfile.IO #Community. 

OR 
Are you giving a session on MicroProfile? Your session needs MP media coverage!  Submit an github issue  http://bit.ly/2IhxsQa (with required information)  & we will do our best to push your session to the @MicroProfile.IO #Community. 

![MicroProfile-Media-Coverage](https://user-images.githubusercontent.com/12132146/55557146-7f9ee800-56e9-11e9-8da0-b0c14d6237a7.png)

**Comment by aeiras** [comment]
@rstjames design is perfect! 

description draft is ok, lets improve it to: 

Are you giving a session on 💛 #MicroProfile? If YES, your talk needs effective #MPmedia 🌎🌍🌏coverage! Simply submit an github issue http://bit.ly/2IhxsQa (with the required information). Help push your session to the @MicroProfile.IO #Community. #opensource #sharingIScaring

**Comment by rstjames** [comment]
@aeiras all scheduled.

**Comment by aeiras** [comment]
Wonderful—ThankYOU Ryan!
