### ISSUE TITLE
[MP Site] Add iJUG and Fujitsu Logos to Member Page

### ISSUE THREAD

**Issue by TetianaFTV** [microprofile/microprofile-marketing#481]
@rstjames please add logo of iJUG and Fujitsu to https://microprofile.io/workinggroup/ when they provide them based on these tasks:
- iJUG https://github.com/eclipse/microprofile-marketing/issues/479
- Fujitsu https://github.com/eclipse/microprofile-marketing/issues/480

In addition, please add the following full list with MP members the block Knowledge
https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=0

It can go as the first point "[MicroProfile Steering Committee Representatives](https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=0)"

**Comment by rstjames** [comment]
add them to the website
