### ISSUE TITLE
[ Eclipse Tweet on MP using old name]  Fixed required

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#485]
Hola @TanjaObradovic, 

In advance, thank you for correcting this tweet about using the MicroProfile name without the Eclipse insert.  MicroProfile and its  [Trademark name](https://twitter.com/EclipseFdn/status/1382406741808275459?s=20)

Please advise the entire Marketing team of MP proper name.

**Comment by TanjaObradovic** [comment]
@aeiras it is done now! thanks for pointing out!

**Comment by aeiras** [comment]
You are wonderful, Tanja. Thank you for quickly helping fix issue. We appreciate it.
