### ISSUE TITLE
[CN4J Meeting April 20th] Media push - Needed

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#486]
**When:**
April 20th, 9:30-10:30am PDT

Same  **design** as [CN4JTweet](https://twitter.com/MicroProfileIO/status/1374367832109031425?s=20)

**Description:**
Join and contribute to the 3rd public #CN4J communications' discussion happening today between the @jakartaee and #MicroProfile communities.  The 2 communities aim at efficiently explaining the strong synergy that exists between the 2 projects  https://bit.ly/calendar-zoom-minutes
#OpenSource

**Comment by rstjames** [comment]
scheduled to go out tomorrow before the call.
