### ISSUE TITLE
[CN4J 4 call media push] May 4th @9:30 PDT

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#488]
Same as past media design/time/card

 **Twitter description**

Join & contribute to the 4th public & recorded @jakartaee and @MicroProfileIO Steering Committees call that aims at efficiently explaining, writing-up, the powerful collaboration the 2 Working Groups enjoy @EclipseFdn
 Access https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

Thank you, Ryan!

**Comment by rstjames** [comment]
Going out on the 3rd to give some people time to see it.

**Comment by aeiras** [comment]
Thats wonderful, Ryan! thank you.
