### ISSUE TITLE
[Media Push] Compatible logo Submissions C2A

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#489]
@rstjames, 
Can you please help push tomorrow the call2action via MP media?

**Design**

- Submit Your MicroProfile Compatible Logo Design
- Deadline April 30th at 6pm PDT. 
- #ByCommunityForCommunity

**Twitter**
#MicroProfileEnthusiasts: Submit your #MPCompatibilityLogo design. Doing so will help the continued prioritizing of @MicroProfileIO's community imput & the #MPCommitment shapping its development on a well-governed #opensource ecosystem. 

Participate: https://docs.google.com/document/d/1pcEducp-lEC0o0I3hRRzt3Kc-uC-hN3zQ-Yj1MqSuiE/edit#heading=h.4fm2913fu0o9 

** call to action media pushes**

- tmw
- last day
- the C2A is going to be pinned into Twitter until the 30th

Ryan, 

Can you share the adjusted tweet with proper google link so that I can review the tweet once more? Thank you!

**Comment by rstjames** [comment]
Set to go out 26th and 30th. 
![microprofile-compatible-logo-subit](https://user-images.githubusercontent.com/12132146/116099921-bcf9b800-a6ac-11eb-9d4d-48ca8705e757.png)

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1386689021041156096?s=20

**Comment by aeiras** [comment]
excellent @rstjames, thank you!
I added the twitter link here, moving forward if we have the link, can you add it to the ticket as well?

**Comment by rstjames** [comment]
@aeiras I do not understand your last comment.

**Comment by aeiras** [comment]
@rstjames, 

Let's re-open this issue and use it to add 3 more weekly reminders + 1 on the last day of the Call to Action. If anything is a miss, new ticket is also ok!

**Comment by rstjames** [comment]
scheduled to go out 3 more times this week

**Comment by aeiras** [comment]
Excellent Ryan!
