### ISSUE TITLE
MP JWT at ITKonekt

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#49]
Conference Name: ITKonekt

Conference website and social media links: https://itkonekt.com/en/it-conference-zagreb/

Title: Stateless Microservice Security via JWT, TomEE and MicroProfile
Date and hour: Sunday, April 14th. 2019

Speaker name: Jean-Louis Monteiro
Speaker twitter handle: @JLouisMonteiro

**Comment by rstjames** [comment]
Join Jean-Louis @JLouisMonteiro For a great session on Stateless Microservice Security via #JWT, #TomEE & #MicroProfile @ITkonekt - Sunday, April 14th More info: http://bit.ly/2UaPHhm
#sharingIScaring #community #OpenSource #OSS 

![MicroProfile-ITKonekt-JeanLouis](https://user-images.githubusercontent.com/12132146/55339212-8b4c9d80-54a2-11e9-94b4-b8625f8792c8.png)

**Comment by rstjames** [comment]
Two tweets were scheduled  for 9th and 13th

**Comment by jeanouii** [comment]
Ok @rstjames 
I cannot move the ticket to Done but I can close the ticket from here.
