### ISSUE TITLE
[MPWG Page] Fujitsu logo is too large

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#490]
Lets keep in mind to adjust the logos so all of them look the same in size and not 1 takes over visual. 

@rstjames Thanks for fixing issue. 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/10731224/116478925-b6e21380-a833-11eb-8727-dcf8b1240aa8.png">

**Comment by rstjames** [comment]
fixed
