### ISSUE TITLE
MP font mistake ( updated font files) 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#491]
I made a mistake with the MP font on the website and designs. Not sure how it got changed but I relaxed we are using the wrong font. I already updated the branding page, the files online (google drive) and next I will update the branding manual and all social media files on Google drive.  Attached is the correct font, which can be found on GD and MP branding page. 
[dosis font.zip](https://github.com/eclipse/microprofile-marketing/files/6404941/dosis.font.zip)

**Comment by rstjames** [comment]
@TetianaFTV can you please update the files you created. Sorry for this mix-up but want to correct it before it's too late.

**Comment by aeiras** [comment]
That’s the beauty of working on the trademark task. It gives us the opportunity to audit everything. 

Thank you for tackling findings head strong, Ryan! 👌🏼

**Comment by TetianaFTV** [comment]
@rstjames fonts on [the cards](https://drive.google.com/drive/folders/1R0ogSBMaipLG10cQk5fGj1ppAZmtrR0F) are updated

**Comment by rstjames** [comment]
@TetianaFTV looks good. Thank you for the changes. 
I updated the website card image already.
