### ISSUE TITLE
[Documentation] Zoom Admin for MPWG Assigned Admins

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#492]
I'll work on a document for securing the Zoom calls, assigning host and co-hosts, etc.

**Comment by aeiras** [comment]
You are amazing, Debbie!
 
We can test those guidelines with the Context Propagation Team.   I will send the 2 Admins the code today. They have not scheduled the call yet, so perfect timing. 

 https://github.com/eclipse/microprofile-marketing/issues/420

**Comment by ghost** [comment]
First draft of documentation - 
https://docs.google.com/document/d/1xTBnhJ2SjDmLjM6OTyRVjSnjb6r5s8_opGjSyZnD5vA/edit?usp=sharing

**Comment by jclingan** [comment]
Document updated with images.

**Comment by nehasardana09** [comment]
Are we expecting any review comments on this? Looks good to me. Let me know if this to okay to close.
@aeiras @jclingan

**Comment by aeiras** [comment]
Neha, 
Thanks for pulling back in. There are a few updates I need to add to the document now that John has inserted the images. 
You and Debbie can expect completion latest by next Monday. On that day, you can help Debbie submit the PR under the MPWG pages  https://github.com/microprofile/microprofile-wg/wiki.

**Comment by nehasardana09** [comment]
Thanks @aeiras for the updates.

**Comment by aeiras** [comment]
Hola @debbiehoffman, 

I have added a few things in the document. John did a fantastic job with the screen shots. :)
Can you please [review ](https://docs.google.com/document/d/1xTBnhJ2SjDmLjM6OTyRVjSnjb6r5s8_opGjSyZnD5vA/edit#heading=h.4hav8m8ws6jw)and pull me in if there are any questions on latest additions? Thank you!

With John, we navigated onboarding Context Propagation and learned quite a bit by doing. 

If you cannot look into this, do delegate the review to Neha. :) Neha volunteered to help you with the PR submission so the 2 of you are a team! 

Thank you both,

**Comment by ghost** [comment]
@aeiras  Hi! Can you please update this with the info about the PR as discussed in marketing call today? Thank you!

**Comment by aeiras** [comment]
Hola Debbie, 

Under https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc  "Create or fix an issue..." 
you find the [do a pull request  ](https://github.com/eclipse/microprofile/blob/master/how-to-pr.adoc)

Have fun!

**Comment by ghost** [comment]
Hi @aeiras ! Talked with @nsardana-bny today and we agree that the Zoom doc really should be merged with the Mkt- Call Steward Doc (https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit#) as several things mentioned in the original Zoom doc aren't actually steps that we need to do anymore.

We also talked about doing the pull request, and I need to reach out to Cesar H because Neha said we can't actually change the Wiki directly using the instructions provided (she tried with something else previously). So will try and set up a call w/ him for that but in the meantime will work on merging some of the details from the Zoom Admin doc into the Mkt Call Steward document to make being this "Steward" less confusing and easy for anyone to follow.

**Comment by aeiras** [comment]
Sounds fantastic to simplify the documentation, Debbie & Neha!

I think @cesarhernandezgt is going to be glad to be pulled, via the git ticket he created, to unblocking any PR work. 
 https://github.com/microprofile/microprofile-wg/issues/92

**Comment by ghost** [comment]
I added the Wiki page for this but none of the screenshots are showing. I tried using the image thing in the toolbar at the top of the wiki edit screen but it asks for a URL. So I put the images in imgur to grab links for them. They don't seem to work. Can someone fix this?  https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Zoom-Admin

**Comment by aeiras** [comment]
beautiful, Debbie! 

@jclingan when contributing the screen shoots also volunteered to help with the import of those imagines to the page :) 
John, can you please help here? Lets close this ticket : )

**Comment by aeiras** [comment]
@jclingan, 

Can you please help Debbie with the images in the wiki https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Zoom-Admin?   You volunteered to help her with that step, therefore, thank you, John. 

Let's aim at closing this ticket before Nov is done.

**Comment by aeiras** [comment]
completed, you are wonderful, Debbie. 
Thank you @jclingan for the extra care importing the images!
