### ISSUE TITLE
[New Member Media Push] Interessenverbund der Java User Groups e.V.  ( iJUG )

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#493]
**Tweet:**
#MicroProfile is proud to announce that @iJUGeV has become the newest MicroProfile Working Group Member (MPWG) as of March 2021. We are excited to have the Interessenverbund der Java User Groups e.V. (iJUG) help steer the direction of @MicroProfileIO.

#ByCommunityForCommunity 

**Design**
The one created for Garden State announcement works. 

**Blog**
not available

**Comment by rstjames** [comment]
![microprofile-wg-new_member-iJUGeV](https://user-images.githubusercontent.com/12132146/118110252-7f05cf00-b3e2-11eb-9dcd-b52688d59add.png)

**Comment by rstjames** [comment]
Going out tomorrow
