### ISSUE TITLE
[New Member Media Push] Fujitsu Global

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#494]
**tweet**
#MicroProfile is proud to announce that @Fujitsu_Global has become the newest MicroProfile Working Group Member (MPWG) as of March 2021. We are excited to have Fujitsu Global help steer the direction of @MicroProfileIO.

#ByCommunityForCommunity #OpenSource

**design**
The one used for Garden state

**Blog**
not available

**Comment by rstjames** [comment]
![microprofile-working-group-new_member-fujitsu](https://user-images.githubusercontent.com/12132146/118110933-5205ec00-b3e3-11eb-96ca-8499963e8a04.png)

**Comment by aeiras** [comment]
@rstjames,

I love the template. It fits wonderful with the message! 

 There is another, now closed that deals with Fujitsu's logo [ticket ](https://github.com/eclipse/microprofile-marketing/issues/490) that still needs care.  Can you look into it again?  check the page in all your devices to notice it please. : ) gracias!

**Comment by rstjames** [comment]
strange... the change was made and remember seeing it on the page... anyways its fixed again @aeiras

**Comment by aeiras** [comment]
thank you, Ryan!

**Comment by rstjames** [comment]
going out today.
