### ISSUE TITLE
[New Member Media Push] Oracle Corporation 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#495]
**Tweet:**
#MicroProfile is proud to announce that Oracle has become a MicroProfile Working Group Member (MPWG) as of January 2021. We are excited to have the Oracle Corporation help steer the direction of @MicroProfileIO.

#ByCommunityForCommunity #OpenSource

**Design**
same as for Garden State

**Blog **
Not corrected so cannot be shared. @edbratt FYI on [blog annoucement](https://dmitrykornilov.net/2021/01/08/oracle-joins-microprofile-working-group/) with [Mktg forum feedback ](https://groups.google.com/g/microprofile-marketing/c/ksxbKT32qJE)

@rstjames lets wait to see if blog gets fixed. This message can be schedule for next Monday to allow for time to review blog. Thanks!

**Comment by rstjames** [comment]
![microprofile-working-group-new_member-oracle](https://user-images.githubusercontent.com/12132146/118113282-613a6900-b3e6-11eb-87e6-6e0dd4323a9f.png)

**Comment by aeiras** [comment]
I am not sure if the blog will be ready for media push. 
@rstjames, please let's push this message late next week to allow a full week to pass. Thank you!

**Comment by rstjames** [comment]
posted

**Comment by aeiras** [comment]
Pretty wonderful, thank you, Ryan! 

we have completed the media onboarding with the 4 Members via MP media. 
https://twitter.com/MicroProfileIO/status/1395368952075853825?s=20
