### ISSUE TITLE
[INFRA- Zoom Admin Access] Add Emily 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#497]
@Emily-Jiang thank you for helping us make @jclingan scalable!

John, 
Two requests for you, thank you! 

1. Can you please add Emily as an MP Super Zoom admin?
2. Can you please add Emily as an MP Youtube Admin?

The request comes from Mktg discussions and git issue: https://github.com/eclipse/microprofile-marketing/issues/476#issuecomment-816272758 

Let's do this,

**Comment by jclingan** [comment]
Done.

**Comment by aeiras** [comment]
fantastic, snuggly John. 
Emily will be included in the current documentation as the person to be added to API's calendar updates and more. So happy!
