### ISSUE TITLE
MP OpenTelemetry Media push for 2021

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#498]
**When:**
Monday, every week

**Time:**
6:30am- 7am PDT- lets change it to EU time. 

**Twitter**
_Join today's #OpenTelemetryCall to discuss & contribute to the API's technical direction. #MicroProfilers' participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API. 

Join: https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS_

Thanks @rstjames!

**Comment by rstjames** [comment]
@aeiras 
![OpenTelemetry-Call](https://user-images.githubusercontent.com/12132146/119139138-f7077100-ba42-11eb-98f5-445647f44aef.png)

**Comment by aeiras** [comment]
Let’s fix the name in the card, Ryan.

**Comment by rstjames** [comment]
![microprofile-opentelemetry-call](https://user-images.githubusercontent.com/12132146/119367148-f45e8300-bcb1-11eb-9664-b83f29ba940f.png)

**Comment by aeiras** [comment]
perfect, Ryan! 

Thank you,

**Comment by rstjames** [comment]
set for the year.

**Comment by aeiras** [comment]
Thank you, Ryan! 

--- for tracing on this ticket. 
[MP Community Thread on new space](https://groups.google.com/g/microprofile/c/KrK47t_Dm0k) is a wonderful MP communication statement of how strong & beautiful the ecosystem is with feedback and the engagement reaching + 1200 subscribers.
