### ISSUE TITLE
[MP Infra Social Media Account] Created to link HootSuite- Connecting All MP Media

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#499]
As part of the 2021 Project plan, MP social media will use a portion of the budget to scale its social media and purchase HootSuite subscription to link all MP outlets and enable easier media scheduling that is not painful to own. 

The new email group contains the MicroProfilers helping with MP twitter media today, 5/21/21, with ownership status:
@rstjames 
@TetianaFTV
@aeiras 

INFRA inventory sheet >Tab [Mktg_Media ](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=2108923563) created

**Comment by aeiras** [comment]
@rstjames the hootsuite account is now active. Please play with it and set it up. Ideally you can bring status to next Monday's call.  https://www.hootsuite.com

tetiana and I have access for support and INFRA. 
We need ideally documentation on stuff that we ought to know that has nothing to do with access but usage as well. 
Using the marketing wiki is the personal location for that document as you navigate the set up on the account. 

Thank you,

**Comment by aeiras** [comment]
@rstjames & @@TetianaFTV, please use this ticket if there are any issues with the email with your access you received last Friday.

**Comment by rstjames** [comment]
@aeiras @TetianaFTV 
I can not find an email with login information. Who set up the account and set the password and email?

**Comment by aeiras** [comment]
Ryan, I have forwarded you the private email.
