### ISSUE TITLE
Jakarta EE talk (also covering MicroProfile extensively) at JEEConf 2019

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#50]
Conference Name: JEEConf

Conference website and social media links:
- https://jeeconf.com
- @jeeconf

Talks Links
https://jeeconf.com/program/jakarta-ee-a-weapon-of-mass-development/

Session Name: Jakarta EE: A Weapon of Mass Development
Date and hour: Friday, April 26th. 2019 (16:20 – 17:05)

Speaker name: Edwin Derks
Speaker twitter handle: @edwinderks

Description
Join @edwinderks at @jeeconf to learn how to tap into the power of @JakartaEE and @MicroProfileIO from development to production - Friday, April 26th More info: https://bit.ly/2FVDJ1x
#OpenSource #OSS

**Comment by aeiras** [comment]
@ederks85 hola Ed! :)

You missed 1 step, the description for the tweet. Thanks for the follow up.

**Comment by ederks85** [comment]
@aeiras I have found the template and updated the details accordingly. Can you confirm if it is complete please?

**Comment by rstjames** [comment]
Hi @ederks85 Below you can see how the social media image will look. 
Please confirm all info is correct. Thanks

![MicroProfile-JEEConf-EdwinDerks](https://user-images.githubusercontent.com/12132146/55403567-631e7680-5556-11e9-8244-a71425fc9161.png)

**Comment by ederks85** [comment]
@rstjames looks good, but the time is not correct, it must be 16:20 – 17:05. I seem to have taken the wrong time from the schedule, my apologies for that.

**Comment by rstjames** [comment]
@ederks85 good catch thanks 
![MicroProfile-JEEConf-EdwinDerks](https://user-images.githubusercontent.com/12132146/55423501-50b83300-557e-11e9-81a1-d87f26e79489.png)

**Comment by ederks85** [comment]
Awesome, thanks 👍

**Comment by rstjames** [comment]
@ederks85 All scheduled to be tweeted out before you session 22nd and 25th

**Comment by ederks85** [comment]
perfect!

**Comment by rstjames** [comment]
@ederks85 please close this issue
