### ISSUE TITLE
[2021 Media Call 2 Action Messages] Content Contribution 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#501]
2020 [tweets](https://twitter.com/MicroProfileIO/status/1341037962637656065?s=20)

**Twitter description:** 
#MicroProfileContributors: have you shared what you have learned with @MicroProfileIO💛yet? 

Submit your #MicroProfile videos/tutorials/blogs/ebooks to the website blog by using the guidelines found here: https://bit.ly/2OiPWkD

#SharingIsCaring #ByCommunityForCommunity #OSS

**Tracking sheet** tells how many times, suggestion is maybe to schedule the media on either Saturday or Sunday instead of the work week. @rstjames  WDYT. This message is very important, if we can push it every week once that would be great b/c sharing knowledege must always come first. 

https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0
line 13

**Comment by rstjames** [comment]
going out every other Sunday for the year
