### ISSUE TITLE
[2021 Media Call 2 Action Messages] Watch Youtube recordings

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#502]
[2020 tweets](https://twitter.com/MicroProfileIO/status/1317126403570151424?s=20)

**Tweet**
#MicroProfileEnthusiasts: Do you want to meet some of the #MicroProfilers behind the many project's activities? 

Watch or listen to them via the #MicroProfileYoutube Playlists: https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w/playlists  **[shortern link needed]** :) 

#CommunityAlwaysComesFirst #ossTransparency #OpenSource 

**Tracing sheet**
line 11
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

--- Thank you, Ryan!

**Comment by rstjames** [comment]
set to go out once a month

**Comment by aeiras** [comment]
@rstjames if anyting you push is not tracked with frequency in the sheet, please adjust it there to show the final count :)
