### ISSUE TITLE
[2021 Media Call 2 Action Messages]  DevRel Media Highlights on MP Activities

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#503]
2020 [tweets](https://twitter.com/MicroProfileIO/status/1338857092640198668?s=20)

**Twitter**
#MicroProfileDevRel: MicroProfile provides you with branding resources that allow your autonomy. If you wish for @MicroProfileIO to highlight your #MicroProfileSpeaking & misc activities via its media channels, check: https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support  **(shortern URL needed)**

#ByCommunityForCommunity #SharingIsCaring #OSS 

**Tracing sheet**
line 14
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

--- Thank you, Ryan!
The tweet might need a 3rd read as I don't have the short URL yet.

**Comment by rstjames** [comment]
Not sure what this tweet is for? We already put tweets out of getting coverage if you a MP speaker... I said it before and I'll say it again :) We have TOO MANY reminders. Let's try to keep be pickier about what we schedule out.

**Comment by rstjames** [comment]
I did a mix of the old tweet and the new. Clearer message now. Set to go out every 3 weeks 

Are you giving a session on #MicroProfile? If YES, your talk needs effective #MPmedia 🌎 coverage! Get MicroProfile to highlight your #MicroProfileSpeaking & misc activities via its media channels, check out: https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support

#opensource #sharingIScaring #Oss

**Comment by aeiras** [comment]
I like your version better. It uses part of last year's message + adds more clarity. Kudos!
