### ISSUE TITLE
[Website Improvements] Update the  Submit Sessions/Activity button

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#504]
While working on the 2021 leftover media pushes, I noticed that improvements as follows are needed, further discussion is also welcomed:

1. Change the current link to the Call 2 Action under Blog's C2A to the new wiki
- [Submit A git Issue - Are you a MicroProfileSpeaker](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)

2. Add the same button to the Branding Resources Page 

What else can we improve with respect to the call to action and its call out to the Branding Page?
Tweet git issue submitted.

**Comment by rstjames** [comment]
updated

**Comment by aeiras** [comment]
beautifully place @rstjames 💯

**Comment by aeiras** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/10731224/119885542-d2017b00-bee6-11eb-9bf1-e55f05577de6.png">

**Comment by aeiras** [comment]
@rstjames 
the git issue (shown below) link needs to also be updated. Please do not remove it. It is ok, efficient in this case for it to repeat twice within the page. 
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/10731224/119885860-33c1e500-bee7-11eb-84f1-54ac5209b69c.png">

**Comment by rstjames** [comment]
updated
