### ISSUE TITLE
[2021 Media Call 2 Action Messages] Sharing Your MicroProfile Experience

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#505]
2020 [tweet](https://twitter.com/MicroProfileIO/status/1334175745728344065?s=20)

**Tweet**
#MicroProfilersInterviewSeries provides valuable input & insight into the @MicroProfileIO ecosystem.  Should you, a #MicroProfiler, wish to share your experience contributing to #MicroProfile, do join the #SharingIsCaring activity: https://github.com/eclipse/microprofile-marketing/wiki/Sharing:--The-Onboarding-Into-MicroProfile-Interview-Series  **[need short URL]**

#ByCommunityForCommunity  #OpenSource

**Tracing sheet**
line 15
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

--- Thank you, Ryan!
The tweet might need a 3rd read as I don't have the short URL yet.**

**Comment by rstjames** [comment]
@aeiras not 100% sure what you want to be done here. 

What is?: "Tracing sheet line 15
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0"

**Comment by rstjames** [comment]
set to go out twice a month for the year

**Comment by aeiras** [comment]
Nice, Ryan. 
I added the sheet b/c it tracks the expected frequency. :) Thank you!
