### ISSUE TITLE
[MPWG site-Tab] Knowledge tab additions and update

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#506]
Under [MPWG tab](https://microprofile.io/workinggroup/)
section Knowledge lets add in first position the Steering Committee Members - to be added when the external drive is back to working.

**Comment by aeiras** [comment]
external drive access is back: link to the document https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=0

**Comment by rstjames** [comment]
@aeiras I do not understand what you want done here

**Comment by aeiras** [comment]
@rstjames, 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/10731224/119886222-931ff500-bee7-11eb-95b0-070d7b09a263.png">

The first item in the list needs to be:

1. The Steering Committee Assigned [Members ](https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=0) are the MPWG Stewards who ensure that the MPWG [Charter ](https://www.eclipse.org/org/workinggroups/microprofile-charter.php) 7 pilars: Limited processes, Experiment and innovate, No backwards compatibility guarantee,Implementation first, Encourage brand adoption, Openness, & Low barrier to entry are protected. 
2. The Steering Comittee  Discussion [Minutes](https://drive.google.com/drive/folders/1FKOKGwHnS-eHujVKs5BL6U3xCqyoS7P8) provides the history of all the committee discussions that has happened, since October 1st 2020, that are approved by the members. 
3. The MicroProfile Lifecycle [Status](https://docs.google.com/presentation/d/1FnuC4cJqkXfqIJ-8ZajENiVK9YNBfk1zlWI4CAKp8Kk/edit#slide=id.g86c371225a_1_6) shows the trajectory of the project becoming a member of the Eclipse Foundation Working Group [Projects](https://www.eclipse.org/org/workinggroups/explore.php). 
4. The Infractucture Admins [Inventory](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=2015643674) lists and shows the MicroProfile core believe By Community For Community!  The sheet contains individual volunteers accross the ecosystem, who are trusted to uphold the keys to MicroProfile infra.  MicroProfile is 100 percent run by its community. No Eclipse hires nor Eclipse purchased services. 
4. The New Members Onboarding [Wiki](https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--Members-Onboarding) lowers the bar to entry for new MPWG Members. 
5. The MPWG [Repository](https://github.com/microprofile/microprofile-wg/issues) tracks the work set-up either by the yearly Project Plan or Releases, etc. 

Ryan, please help update the entire knowledge page with above. Just like we did for the Social & Email forums. 

Thank you, triber!

**Comment by rstjames** [comment]
updated

**Comment by aeiras** [comment]
It looks great, Ryan! You rock : )
