### ISSUE TITLE
[INFRA- Social Media Admins] Update for Linkedin

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#509]
@rstjames connected to the [[MP Social Media] Create Hootsuite Account #487](https://github.com/eclipse/microprofile-marketing/issues/487) with your admin access, please help update the account as follows:

**Remove**

- Angela Warner
- Jane Matteis

**Update**

the account name, logos, etc. 

**Remember**
Your Admin account allows you to link IN to Hootsuite, there has never been a log-in into the MP account. 

**Follow-ups**

- I will add this ticket to the next mp Mktg call to enable the discussion about updating the admin access to trusted MicroProfilers within 2021 work: 

1. Payara's admin access needs adjusting (aka @debbiehoffman)
2. Jelastic @TetianaFTV wants access 

The MP Infra inventory sheet will be updated after that conversation. 

![image](https://user-images.githubusercontent.com/10731224/119902254-d4ba9b00-befb-11eb-9d11-80b935a922a9.png)

**Comment by rstjames** [comment]
Upated
