### ISSUE TITLE
MP at Devoxx France 2019

### ISSUE THREAD

**Issue by lilian-benoit** [microprofile/microprofile-marketing#51]
Conference Name: Devoxx France

Conference website and social media links:
    https://www.devoxx.fr/
    @DevoxxFR

Talks Links 
    https://cfp.devoxx.fr/2019/talk/LGU-0798/Creer_facilement_des_microservices__(ou_cloud_native_java)_avec_Eclipse_MicroProfile

Title: Créer facilement des microservices (ou cloud native java) avec Eclipse MicroProfile
Date and hour: Wednesday, April 17th. 2019 (13:30 – 16:30)

Speaker name: Lilian BENOIT
Speaker twitter handle: @Lilian_Benoit

**Comment by jeanouii** [comment]
Bonjour Lilian,

Is the tweet advertising the talk supposed to be French or English?

Jean-Louis

**Comment by lilian-benoit** [comment]
Bonjour Jean-Louis,

My talk is in French for French developers. It would better interested if possible that tweet to be in French.

Regards,
Lilian.

**Comment by rstjames** [comment]
Hi @lilian-benoit 
It is always best if the speaker writes his tweet and will will adjust it for MP. 
Can you please write a tweet saying what you would like to say about your talk and we will do the rest. 
Thank you

![MicroProfile-DevoxxFr-LilianBenoit](https://user-images.githubusercontent.com/12132146/55406424-63ba0b80-555c-11e9-9cee-e499f8620fbc.png)

**Comment by lilian-benoit** [comment]
I think to a tweet as

> Venez rejoindre @Lilian_Benoit afin de découvrir Eclipse MicroProfile et ses fonctionnalités #config #health #openapi #metrics #restclient #jwt. Tout ce que vous avez besoin pour réaliser vos microservices

**Comment by rstjames** [comment]
All scheduled.

**Comment by aeiras** [comment]
just wonderful form MicroProfilers! :)

**Comment by lilian-benoit** [comment]
Thanks @rstjames

**Comment by rstjames** [comment]
@lilian-benoit can you close the issue? 
Thanks!
