### ISSUE TITLE
[INFRA- Social Media Admins] Facebook Update and Clean up

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#510]
https://www.facebook.com/microprofile.io/?ref=pages_you_manage

@rstjames I have confirmed today that you have always had Admin access to the MP facebook page. 
Please check your 2021 FB page settings first. Given that up until now, MP media didn't have the budget to link all media accounts to 1 Vendor, it is only normal that you never accepted the MP invite. 

How: Under your FB Pages invites find MP and accept. 

**Work to be done by you:**

- update the page as you see fit 
- connect to hootsuit (you wont have a password for FB b/c FB is the same as linkedin, it uses your personal FB account to enable collaboration)

**Completed tasks **
- I have removed the Message feature, none can send MP Facebook messages
- MP will post media messages on different languages, I have enabled that feature
- updated the email to the Community forum email
- update address to Global
- updated Page Info
- general stuff

**Follow up** 

- I will add this ticket to the Mktg agenda for discussion.  FB access Admins need to be increased to include at least another volunteer outside the Tomitribe team. 
- Cesar S from Red Hat was removed today
- 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/10731224/119904466-4b0ccc80-beff-11eb-982d-b8c0259e7280.png">

**Comment by rstjames** [comment]
@aeiras to connect it to facebook I need the original login info. (email and password) so far it wont connect with my linked private account.

**Comment by rstjames** [comment]
@aeiras I think because. this the free one-user version I need to log into MP as MP, not as a manager of the account. Do we have the email and password to get into MP facebook?

**Comment by aeiras** [comment]
The MP Facebook was never created with an email. Groups can only be created with "personal accounts" so the log-in is always possible via Admin status. You have the highest access. SO the problem must be your setting. 

If unsure, I could connect you via private email with Cesar S. I am not the best person to know much about Facebook. Do let me know.

**Comment by aeiras** [comment]
@rstjames is this done?

**Comment by rstjames** [comment]
@aeiras I can not connect Hootsuite to facebook. I am not sure why... it only allows me to connect my personal fb account.

**Comment by aeiras** [comment]
@rstjames, 

I have forwarded you the weekly email that comes to the media email forum used for managing Hootsuite. 
It says that FB is not linked anymore.

**Comment by rstjames** [comment]
@aeiras it was never linked because I can not get it to connect through my personal FB. As I stated in the other comments above. I need the email used to create the MP facebook and password. No other idea how to fix this and am not sure why it is acting this way. You can try to connect it through your FB account @aeiras

**Comment by aeiras** [comment]
Ryan, 

I am looking at this to see if I can link it with my account. Stand by. 
Reminder that FB pages are not created with emails, so there is no email that can be provided.

**Comment by aeiras** [comment]
@rstjames, 

On minute 50 of the video, it explains how to link Hootsuite to a Facebook page: https://education.hootsuite.com/pages/add-social-networks

**Comment by rstjames** [comment]
Yes, I tried this (whats in the video). But the options / UI they show in this video are not the same as what I am shown when trying to set it all up. When connecting my Private account, MicroProfile does not show up as a company page I manage or have admin rights to. 

Please try it from your side and see if you are able to connect it @aeiras

**Comment by aeiras** [comment]
MP Facebook is now connected to Hootsuite. 
The "allow" selective access in Hootsuite to connect to is easy to miss as step 2 in the video. The thing is, once you log in, you must select with much care what you wish to provide access. Either personal account access, Groups, or Pages. It is there yet easy to miss.  

Please can you play with the integration on Monday and confirm that there are no further issues? Thank you, Ryan! 
Hootsuite can now push all MP content activity to Facebook. I left no restrictions on the access.

**Comment by rstjames** [comment]
Thank you @aeiras 

Microprofile did not show up on groups or pages on my personal account and couldn't figure out why.

**Comment by aeiras** [comment]
The pages need to be in your favorites or similar stuff to be seen. poor UX. 

Please close this ticket once you are sure that Hootsuite is a go. 
Ideally, could you send the update to the mp mktg forum with ALL Set bells :) ? thank you! 
This set up took awhile, glad it is hopefully done and we can start tracking and sharing the monthly stats with the creation of a ticket and add to the drive space as well. All part of the onboarding tool.

**Comment by aeiras** [comment]
Completed.
