### ISSUE TITLE
[Website MPWG Tab] Add Prospectus: Catálogo de Membresía del Grupo de Trabajo de MicroProfile

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#511]
@rstjames, 

Today, the Spanish translation of the Prospectus was completed. Now we make it scalable. Thank you helping figure out how best to add the document into the MPWG page. 
 
**My recommendation** 

- to add a new yellow- buttom called "Aprende más" side by side the "Learn More" button  bringing the viewer to the  Spanish Prospects [Version](https://docs.google.com/presentation/d/1B1uRPNAox5iSL2pOsaI_1ogmjR9MBcmUDb79u-fyHzA/edit#slide=id.g6edf059ff0_56_0)

see below: 

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/10731224/119910228-890fed80-bf0b-11eb-9293-c97fdf3a3ffa.png">

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/511

**Comment by aeiras** [comment]
https://github.com/microprofile/microprofile-wg/issues/73

**Comment by rstjames** [comment]
updated

**Comment by aeiras** [comment]
i love it, @emecas, look what you have made possible! :)
