### ISSUE TITLE
[Social Media] Catálogo de Membresía del Grupo de Trabajo de MicroProfile

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#512]
Ok @rstjames, 

1 more media that follows suit with [[MPWG Prospectus Media Push] Join MP msg
](https://github.com/eclipse/microprofile-marketing/issues/511)

**the design needs replace** 
- Check out... with >  Chequee el Catálogo de Membresía del Grupo de Trabajo de MicroProfile 
- Contributors >  Contribuyentes
- Users > Usuarios 
- Committers doesn't have a Spanish translation, it stays
- Guests >  Invitados
- Organizations> Organicaciones
- Community > Comunidad

**Media tweet**

#ParticipantesCódidoAbierto que buscan un ecosistema saludable y acogedor en donde invertir su tiempo y recursos echen un vistazo a el Catálogo de Membresía del Grupo de Trabajo que responde por qué debería considerar unirse a la #ComunidadMicroProfile 

**short customized Link** -  [[Catálogo](https://docs.google.com/presentation/d/1B1uRPNAox5iSL2pOsaI_1ogmjR9MBcmUDb79u-fyHzA/edit#slide=id.g6edf059ff0_56_0)   @rstjames you created this short link for the Prospectus http://bit.ly/mp-prospectus. Now, let's replace the prospectus with catalogo and proper link. 

**Timing of the tweet**, this tweet can be scheduled on the same day the English version is going out, that could be awesome. 

Gracias Ryan,

**Comment by aeiras** [comment]
https://github.com/microprofile/microprofile-wg/issues/73

**Comment by aeiras** [comment]
@rstjames,

This tweet is assigned to you. It is the same as the Prospectus message already going out. 
Same format but all needs to be in Spanish. See above the translations to help you with the creation of the card. 

Pull me in if you have questions.

**Comment by rstjames** [comment]
http://bit.ly/mp-catalogo 

scheduled to go out each month. 
![spanish-Catalogo-2021](https://user-images.githubusercontent.com/12132146/122752414-3965dd00-d291-11eb-8d6a-867a6d786b70.png)
