### ISSUE TITLE
[Vote - 2021 Eclipse Community Awards] Social media push

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#513]
@rstjames, 

Can you please prioritize the scheduling Call to Action to remind MicroProfilers to vote for 3 #ossDOERs? this week, thank you! 

- Deadline June 28th
- LInk: https://www.surveymonkey.com/survey-taken/?sm=sHMMIP5I4oCiSk5pX6o8nLhAfXdLKe3omyuSzRH0gGRD9dgsFER6Ghp_2Fs5NVYTxFLItfm2wtvDc9viNgW_2BRPBstINeDGA_2BSvjVZ0WYPQ9Kw_3D   (make it a short link, if we could choose mp_Champions that would be great)
- Time: 1 per week, + last day = 5 media pushes

**Design requirements**:

- 2021 Eclipse Commity Awards Need YOUR Vote on MicroProfile Champions
- photos of the 3 MicroProfilers: [Emerson](https://twitter.com/emecas), [Tetiana](https://twitter.com/tetiana_ftv) & Ryan (awesome you) 
- Deadline June 28
- #ByCommunityForCommunity
- using same format as the card design created for the Charter: add Top Committer, Top Contributor, Top Newcomer Evangelist

**Twitter:**
#MicroProfileCommunity, the 2021 @EclipseFdn Community Awards awaits your vote for @emecas (Top Newcomer Evangelist) @tetiana_ftv (Top New Contributor) & @s8ntjames (Top Committer). 

Vote for 3 #MicroProfileChampions [Link with mp_Champions]

**Comment by rstjames** [comment]
all set to go out once a week and once the last day. 
![eclipse-community-awards](https://user-images.githubusercontent.com/12132146/120692809-8e8bab80-c4a8-11eb-9d7b-405624f412de.png)

#MicroProfileCommunity, the 2021 @EclipseFdn Community Awards awaits your vote for @emecas (Top Newcomer Evangelist) @tetiana_ftv (Top New Contributor) & @s8ntjames (Top Committer). Vote for 3 #MicroProfileContributors! https://www.surveymonkey.com/r/eclipse-awards-2021

#opensource #Oss
