### ISSUE TITLE
[Website] Addition to Branding Page- Action Contributor Cards

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#514]
from this ticket https://github.com/eclipse/microprofile-marketing/issues/366

Link https://drive.google.com/drive/u/0/folders/1R0ogSBMaipLG10cQk5fGj1ppAZmtrR0F

@rstjames let's add the link to the cards to the Branding page. Thank you! 

Tetiana, i have restricted the editing access from the public. View access only now that cards have been finalized.

**Comment by TetianaFTV** [comment]
@aeiras cards are already added to Resources and highlighted separately in menu
https://microprofile.io/resources/#achievement-cards

so i don't think we need to duplicate them in Branding, especially considering that in Branding we place templates that can be adjusted by those who download them (e.g. presentation template) and the cards can be used only as is, so they belong to Resources more (like overview presentation, etc)

**Comment by aeiras** [comment]
Hey, 
How about we discuss this with others on Monday call, Tetiana?

I believe that the cards need to be located in 2 sections on the website:

- Resources **and**
- Branding /Marketing page-  This page supports speakers as the ossDOERs in the project. It integrates all resources provided to them into 1 section, especially when dealing with their projecting and communicating about MP that is simple and effortless. It has nothing to do with limiting adjustments to the cards or similar. 

I personally find it valuable to have the cards on the branding page. 

However, when pushing them via social MP media, we must use the Resources page. That is b/c we are already pushing the Branding page via media for the rest of the year. 

Ideally, the MP website is highlighted via MP media communications strategically.

**Comment by rstjames** [comment]
I agree with @TetianaFTV I don't think we need to duplicate them.

**Comment by aeiras** [comment]
lets move forward using the 2 of your feedback.  
Adjustments will be triggered to potentially add the cards also to the Branding page using the community feedback. Eyes from others not aware of the site navigating it is key. 💯
