### ISSUE TITLE
[MP Blog] RSS, Subscribe Button and Automatic Email Notification

### ISSUE THREAD

**Issue by TetianaFTV** [microprofile/microprofile-marketing#516]
Need to consider adding on MP blog:
- subscribe button
- automatic email notification about new article published

@aeiras @rstjames

**Comment by TetianaFTV** [comment]
If we are not going to have any mailing system in the near time, then we can consider using some WordPress plugin like this https://wordpress.org/plugins/newsletter/

**Comment by aeiras** [comment]
+1, Tetiana. 
Thats what I thought we agreed to activate yesterday? Didn't we?

**Comment by aeiras** [comment]
we ought to revisit this topic in 2022. 
For now closing the git issue as it has been 6 months and we chose to skip actions.
