### ISSUE TITLE
[Website] Creating a single link for Quotes rotation

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#517]
Linked to https://github.com/eclipse/microprofile-marketing/issues/406

@rstjames, 
Thanks for helping us figure out, without rushing, what it will take to create a single quote link that allows:

- media pushes 
- website effortless maintainance
- etc

**Comment by rstjames** [comment]
https://microprofile.io/workinggroup/#testimonials

http://bit.ly/mp-testimonials

**Comment by aeiras** [comment]
AMAZING, Ryan, 

https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0
ideally, up to you, we could push the messages in the wknds, and like that maybe push it twice per month. Yet I don't have a view of the social so up to you. : )
 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/10731224/121253465-fd2c8880-c85d-11eb-80b6-978458daeb51.png">
