### ISSUE TITLE
MicroProfile Recording Link - June 7, 2021

### ISSUE THREAD

**Issue by nehasardana09** [microprofile/microprofile-marketing#518]
Hi @jclingan,
I don't have access to the upload video of the MicroProfile Marketing meeting for June 7, 2021. Can you please share the link so that I can update the agenda.

Thanks
Neha

**Comment by nehasardana09** [comment]
@aeiras I am not able to assign the ticket to John. Do I need access to the repository for that? Or you can do it :) Thanks :)

**Comment by aeiras** [comment]
Yes, that's the sad part of the current Repo that restricts access. MP can use a new feature we worked on in 2019 to make trusted contributors be able to assign tickets, etc. Rustam mentioned the same thing. We need to use that feature we moved forward (it took 8 months working with the wonderful infra Team to achieve from a 5yrs old bug). Can you create a ticket and pull me in via comments and add it to INFRA or General topic for us to fix current issues. We have the means. We need to adjust stuff within the repos. All without affecting Commit status. :) 

The recording is published. It needs to be added to the agenda. John rocks, of course!  https://twitter.com/jclingan/status/1402298423320006659?s=20

**Comment by nehasardana09** [comment]
Thanks! I have updated the document with the link.
