### ISSUE TITLE
[Swag] Ship MP t-shirt to Luis.

### ISSUE THREAD

**Issue by LuisGalazM** [microprofile/microprofile-marketing#519]
Hi,
I would like to wear a MicroProfile t-shirt to generate some brand awareness in Sweden. If is possible ship some stickers too .
Es un agrado el poder participar en la comunidad MicroProfile.
Saludos!

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

If you would like the international tracker, please let us know. Next week, we can share it internally with you. :)

**Comment by LuisGalazM** [comment]
Que Chevere!,

yes, share the international tracker please.

muchas gracias :-)

**Comment by aeiras** [comment]
Tracking sent!

**Comment by aeiras** [comment]
Hey @LuisGalazM, 

Your mpswag was re-sent today. Let's see if this time, it passes aduanas.!

**Comment by LuisGalazM** [comment]
Hola @aeiras! 
The mpswag arrived today. 
Muchas Gracias :-D !

**Comment by aeiras** [comment]
Thats so wonderful, Luis!!! Yeayy to 2nd try on package :)

By the way, the 1st package has arrived as of Sunday back to us. 
We cannot wait to see you wearing your MP swag, if you are comfortable about it, share the pic via twitter and highlight the mP handle to enable re-tweet fun. 

Closing this ticket. Gracias por ser tan chevere en MP!
