### ISSUE TITLE
[MicroProfile SWAG] MP Swag T-Shirt to Neha

### ISSUE THREAD

**Issue by nehasardana09** [microprofile/microprofile-marketing#520]
Hi @aeiras,

I want to wear MicroProfile T-Shirt for our marketing calls and other places as well. Submitting the request for the same. I have sent the details to you.

Thank you! 
Neha

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

Please let us know when you get it so that this ticket can be closed :)

**Comment by nehasardana09** [comment]
I got my wonderful TShirt. Thank you :)
