### ISSUE TITLE
[Swag] Ship MP t-shirt to Manish

### ISSUE THREAD

**Issue by manish2aug** [microprofile/microprofile-marketing#522]
Adding this issue for requesting the t-shirt

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

If you would like the international tracker, please let us know. Next week, we can share it internally with you. :)

**Comment by aeiras** [comment]
Hola @manish2aug, 

Did you get your swag?

**Comment by aeiras** [comment]
Hey @@manish2aug, 

Did you get the package yet?

**Comment by manish2aug** [comment]
Hi Amelia,

No, I didn't receive it.

Thanks
Manish

**Comment by aeiras** [comment]
Hola manish2aug, 

 if you didn't get it (been almost 5 months and 2 tries) you won't get it. 
Let's see what 2022 brings, Manish!


Closing ticket.
