### ISSUE TITLE
[Swag] Ship MP t-shirt to Jelastic

### ISSUE THREAD

**Issue by TetianaFTV** [microprofile/microprofile-marketing#524]
We'd be glad to wear MicroProfile t-shirts on the community calls :)
Looking forward to get them.

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

If you would like the international tracker, please let us know. Next week, we can share it internally with you. :)

**Comment by aeiras** [comment]
Hey @TetianaFTV, 

Your swag package was returned due to "unattended" reciber. :) 
Maybe we try again in Nov? Let me know! besitos

**Comment by TetianaFTV** [comment]
Yeah, I was out of country for a long time, so couldn't receive it. 
In the near time no long travels are planned, so let's try again. Thanks!

**Comment by aeiras** [comment]
Hey @TetianaFTV, 

Did you get the new package yet?

**Comment by TetianaFTV** [comment]
Not yet.

**Comment by aeiras** [comment]
uhhh, if you didn't get the 2nd try package (been over 1 month) you won't get it. 
Let's see what 2022 brings, Tetiana!

Closing ticket.
