### ISSUE TITLE
[YouTube Import] MPWG Trademark & Compatibility Call with the EF- EMO

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#525]
Thank you, @jclingan for helping with import! 

Please add the agenda [link ](https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit#) as the description of the video

**Compatibility Program Discussion**
[Paul- EF EMO] presents the process by which the MP community works with the EF trademark team to get things accomplished.
Paul presented for the full hour the content in the spreadsheet  MicroProfile Trademark & Compatibility Program Components
The EMO will use the MPWG forum to communicate with the MPWG on tasks they depend on and require feedback from the MPWG
MPWG will continue to use Git Issues under the WG repo for Compatibility matters
MPWG will continue to use the mpwg forum to communicate with the EMO on the progress of the tasks required for a MPcompatibility project. 

The Compatibility spreadsheet Q&A used the full hour.

**Comment by jclingan** [comment]
Uploaded it to youtube last night.
