### ISSUE TITLE
Do we create a Slack Channel for MicroProfile?

### ISSUE THREAD

**Issue by nehasardana09** [microprofile/microprofile-marketing#527]
Hi,

Like most of the open source projects have a way to communicate faster amongst ourselves and also to enable the community to be more involved. I want to propose a slack channel or something similar.

Thanks,
Neha 

cc: @aeiras

**Comment by aeiras** [comment]
MP has a slack group https://microprofile.io/workinggroup/ 
anyone can go to Media section and join. 

-- I won't part-take on that extra layer of communication debt as stated when the conversation (2020) of the slack happened, Neha! 

You must always own what you think you can. ;)

**Comment by nehasardana09** [comment]
We all agreed on the marketing call that we prefer reaching out through either GitHub ticket or MP Google groups. Hence closing this ticket. Thanks
