### ISSUE TITLE
[Website] Add MPSP link to Working Group page

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#528]
The [MicroProfile Working Group page](https://microprofile.io/workinggroup/) should include a link to the [MicroProfile Specification Process](https://raw.githubusercontent.com/microprofile/microprofile-wg/main/mpsp.adoc). This link is already rendered. Maybe add a "MicroProfile Specification Process" bubble button? Kinda large, though, and makes it  4 buttons across the top. Open to ideas.

**Comment by aeiras** [comment]
Thank you for creating the git, John. 
We need to add it to the new spreadsheet, i will do that a bit later today. 

Next week, we will talk about the Spec page and compatible page, etc. We need to discuss the outline to bring it to life in a manner that is scalable and can be effortless to own. :)

**Comment by rstjames** [comment]
@jclingan the link you provided is a "raw git" should the page look like notes page or a git page? 
Let me know and after I can update the link.

**Comment by rstjames** [comment]
@jclingan PING

**Comment by aeiras** [comment]
Ryan, I see your addition to the landing page call to action under the MPWG page. 

I think we need to improve its visual yet the location seems great.

**Comment by jclingan** [comment]
Yeah, it is a raw Asciidoc. Forgot that I had an Asciidoc browser extension that auto-renders .adoc files, lol

**Comment by rstjames** [comment]
@jclingan is there a next step to improve this or should we close it?

**Comment by aeiras** [comment]
jumping on this nice ticket to provide you feedback on the usage of the MPSP document. 

For MP 4.1 blog, we have 2 options on sharing the MPSP document, website as it is and word. 
We used the Word. 
The current website version is not aligned with MP formating nor view. Ideally, the page follows the MP space, font, etc. 

@rstjames, 
Can you see if this can be done?  What are the pros and cons?
We must create a Products page, Specs page, Compatible etc. The MPSP page is just the beginning of that work. 

Thanks you two,

**Comment by rstjames** [comment]
@jclingan @aeiras the pages has been created and link has been update https://microprofile.io/microprofile-specification-process/

**Comment by aeiras** [comment]
Ryan, 

Good improvement. 

Now, we need to brainstorm about how can we pull together the new Specifications tab with the new Compatible tab into ONE page that is fluid, elegant & clear. Gear up!

**Comment by aeiras** [comment]
@rstjames, 
Please help us update the link page on the first item under the Release Guideline tab located in the MPWG page. Thank you! 

https://microprofile.io/workinggroup/

**Comment by rstjames** [comment]
@aeiras updated

**Comment by aeiras** [comment]
thank you, Ryan!
 You truly make all the ideas & data come to life in the MP website. So amazing. Thank you!
