### ISSUE TITLE
MicroProfile talk (plus Java EE) at Es-Conference 2019

### ISSUE THREAD

**Issue by tuxtor** [microprofile/microprofile-marketing#53]
Conference Name: Es-Conference Mexico 2019

Conference website and social media links:

 - http://www.javaup.org.mx/
 - @JavaUp

Talks Links
http://www.javaup.org.mx/session/microprofile-for-the-busy-developer/

Session Name: MicroProfile for the busy developer
Date and hour: Friday, April 26th. 2019 (9:30 am - 10:30 am)

Speaker name: Víctor Orozco
Speaker twitter handle: @tuxtor

Description
Join @tuxtor at @JavaUp to discuss and learn how could you take advantage of your current EE knowledge to create/deploy cloud native applications with @MicroProfileIO - Friday, April 26th More info: http://www.javaup.org.mx/session/microprofile-for-the-busy-developer/
#OpenSource #OSS

**Comment by rstjames** [comment]
Hi Victor @tuxtor 
Are you ok with this visual? 

![MicroProfile-session-Victor-Orozco](https://user-images.githubusercontent.com/12132146/56124720-8ba36900-5f77-11e9-9fa7-1405c54abff5.png)

**Comment by rstjames** [comment]
@tuxtor scheduled to go out on the 19th and the 25th before your session

**Comment by tuxtor** [comment]
Hi @rstjames visual and information are perfect!. I'm closing the issue since everything is ok and scheduled.
