### ISSUE TITLE
Tweet MicroProfile 4.1-RC1 release

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#530]
For the purpose of reviewing the staged Twitter MicroProfile 4.1-RC1 release graphic and text, the link will be:

https://github.com/eclipse/microprofile/releases/tag/4.1-RC1

Twitter description for @rstjames
#MicroProfileAnnouncement: 💛@MicroProfileIO 4.1-RC1 Release is now available! This release contains an update to Health and relaxes compatibility constraints.

Check it out here: https://github.com/eclipse/microprofile/releases/tag/4.1-RC1

#OpenSourceFUN #ByCommunityForCommunity

**Comment by rstjames** [comment]
![microprofile-release-announcement](https://user-images.githubusercontent.com/12132146/122222657-bfa9aa00-ceb2-11eb-98a3-3a8824e1bfbf.png)

**Comment by rstjames** [comment]
went out today

**Comment by aeiras** [comment]
Yeay, it is exciting to see the needle finally move, Edwin. :) 

Ryan and Edwin, 
It is so nice to see the usage of the Announcements section under Projects https://github.com/eclipse/microprofile-marketing/projects. :)

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1405147650903642115?s=20 
Lets pin-in the push to twitter as important msg. :)
