### ISSUE TITLE
 [Swag] T-Issue is extremely exciting - for Majid!

### ISSUE THREAD

**Issue by majidmostafavi** [microprofile/microprofile-marketing#531]
Hola @aeiras
I'm so excited for creating T-Issue ;)))

**Comment by aeiras** [comment]
Your mpSwag was sent yesterday!

If you would like the international tracker, please let us know. Next week, we can share it internally with you. :)

**Comment by aeiras** [comment]
Hola @majidmostafavi, 

Your MP swag, was re-sent today. Should arrive within 10 to 30 days. :)

**Comment by aeiras** [comment]
https://twitter.com/majidmostafavi/status/1448004166119530496?s=20
