### ISSUE TITLE
[Website fix] Contributors tab broken link on C2A

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#532]
under the https://microprofile.io/contributors/  tab, the Onboarding Into MP button is linked to the wrong [page](https://github.com/eclipse/microprofile-marketing/wiki/GUIDELINES:-Onboarding-into-MicroProfile-Interview). 

Let's fix it to be https://github.com/eclipse/microprofile-marketing/wiki/Sharing:--The-Onboarding-Into-MicroProfile-Interview-Series

**Comment by rstjames** [comment]
updated
