### ISSUE TITLE
[Social Media] CN4J meeting call-  push awareness 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#533]
@rstjames, 

Thank you in advance!!! 
Can you please once again help us push the next CN4J call?  
1 push, only. 

Tuesday June 29th, 9:30- 10:30AM PDT 

(using same design as May tweet) https://twitter.com/MicroProfileIO/status/1389240833623437315?s=20

**description** 

#OpenSource: Join & contribute to the 5th public & recorded @JakartaEE and @MicroProfileIO steering committee discussion that aims at explaining via a written message the powerful collaboration the two Working Groups enjoy
Access https://bit.ly/calendar-zoom-minutes…
#ByCommunityForCommunity

**Comment by rstjames** [comment]
done
