### ISSUE TITLE
[Tweet] MicroProfile 4.1 Release is underway with Compatible Implementation

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#537]
@rstjames please tweet about MicroProfile 4.1.
Tweet message:

MicroProfile 4.1 release is under way with the compatible implementation @OpenLibertyIO 21.0.0.8-beta. If you would like to try out MicroProfile 4.1, check out this following blog to get started. https://openliberty.io/blog/2021/07/12/logging-format-21008-beta.html

**Comment by aeiras** [comment]
Wonderful Emily!

https://twitter.com/MicroProfileIO/status/1415042668762066944?s=20
