### ISSUE TITLE
OSS session on MicroProfile

### ISSUE THREAD

**Issue by nehasardana09** [microprofile/microprofile-marketing#538]
Hi, 
I am giving a 30 min session on OSS at Hack4Inclusion at https://www.h4i.tech/#schedule
Day 2 , July 15, 2021 at 7pm IST (India time). I plan to include my contributions to MP as a steward and other activities. I also contribute to JCP - Java in Education program, Eclipse Collections. Here is my bio:

Bio: 

Neha Sardana is a Software Developer/Architect for Java based applications for over a decade.
She is currently Vice President at Bank of New York Mellon and  JUG (Java User Group) Leader for Garden State JUG(New Jersey, USA). She is a contributor to Eclipse Collections framework and MicroProfile as part of OSS contributions. 
She is also an active volunteer at the JCP - Java In Education program. She works as a coordinator for NYJavaSig's JavaHOW workshops.
Neha has worked in financial services for almost 8 years in both Europe and the US.
She is a technologist and an OSS enthusiast and loves to talk and blog about all things open source.

Twitter handle: @nehasardana09

**Comment by aeiras** [comment]
hola @nsardana-bny, 

I interjected this ticket b/c it missed the tweet. with @rstjames we got it sort out given the short time to get tweet out. 

@rstjames can you please share the tweet here once it is out? Thank you for pushing it given such a short notice. !

**Comment by aeiras** [comment]
Neha, 

In the future always refer to  https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support also found in the website under Resources or submit a session. :)

**Comment by nehasardana09** [comment]
Thanks @aeiras for the wonderful tweet! I will keep that in mind for future events.

**Comment by rstjames** [comment]
Attend @nehasardana09 at @hack4inclusion session July 15, 2021, at 7 pm IST (India time) to understand why you should contribute to #OpenSource and where to begin with #MicroProfile, @EclipseCollect & @jcp_org #JavaInEducation projects.
https://www.h4i.tech/#schedule
#Oss 
![microprofile-hack_for_inclusion-neha_sardana](https://user-images.githubusercontent.com/12132146/125661024-3b67ca44-6150-4167-b8ed-17b6763a8a22.png)


https://twitter.com/MicroProfileIO/status/1415342336733847557

**Comment by nehasardana09** [comment]
you are so amazing @rstjames !!
