### ISSUE TITLE
MP support Giuseppe talk's on Quarkus Insight

### ISSUE THREAD

**Issue by gscaramuzzino** [microprofile/microprofile-marketing#539]
Hello,
I got the invitation to the Quarkus Insight, the official YouTube Channel of Quarkus, and I'm going to spread the voice about MicroProfile specifications. Here the plan:
- brief description about the MP specs 
- demo to how easily implement a MP project with Quarkus. 

Speaker: 
Giuseppe Scaramuzzino

Title of the session:
Quarkus projects using MicroProfile specs with Giuseppe

Personal Twitter or/& git account.:
https://twitter.com/GiuseScara
https://github.com/GiuseppeScaramuzzino

Short session abstract:
Description: "Join us as Giuseppe Scaramuzzino comes by to discuss his youtube channel, tutorials and building Quarkus projects using MicroProfile specifications"

Date/time/location or access of the session:
August 9th, 3:00pm CEST
https://www.youtube.com/c/Quarkusio

**Comment by aeiras** [comment]
Pretty fantastic Guiseppe!

**Comment by rstjames** [comment]
It is set to go out a couple of days before and the day of. @GiuseppeScaramuzzino 

Tweet:
Don't miss @GiuseScara at #Quarkus Insight (youtube) where he discusses his youtube channel, tutorials & building @QuarkusIO projects using #MicroProfile specifications. August 9th, 3:00pm CEST > https://www.youtube.com/c/Quarkusio

#opensource #oss 

![microprofile-quarkus-giuseppe_scaramuzzino](https://user-images.githubusercontent.com/12132146/127499012-0c4cdf6f-9412-4956-bf61-cd1d6004acc3.png)

**Comment by gscaramuzzino** [comment]
Beautiful!!!!! Thank you so much!!!!
