### ISSUE TITLE
 Brian Benz: Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#54]
- [Twitter exchange and feedback to Microprofiler](https://twitter.com/bbenz/status/1113226899386449921)

**Comment by aeiras** [comment]
@cesarhernandezgt thanks for owning follow up! :) 
<img width="907" alt="image" src="https://user-images.githubusercontent.com/10731224/55754224-fb0ddb80-5a00-11e9-9698-113a1867175c.png">

**Comment by bbenz** [comment]
Closes #54 - Thanks!  I'll post the redirect URL next
