### ISSUE TITLE
[General: Mktg-Call Steward] August

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#540]
Hi @nsardana-bny 
 I'm on the list to host MP marketing calls for August and was hoping you'd have a bit of time to quickly go over any details I might be missing to do so as you were just hosting in July. Thanks!

**Comment by nehasardana09** [comment]
Hi Debbie, 
Sure. I can go over the document with you and be your co-host for the next meeting. 
Before that please refer to this document https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit?usp=sharing
and let me know if anything is not clear in this. You can always setup a zoom call and discuss if you need any explanation. Happy to help.

**Comment by ghost** [comment]
@nsardana-bny 
Do you have 30 minutes or so on Tues or Wednesday this week, 11:30am Eastern? Or let me know better times for you. Thanks!

**Comment by nehasardana09** [comment]
Hi @debbiehoffman , wed sounds good. Talk to you soon!

**Comment by ghost** [comment]
Thanks @nsardana-bny  do we need a separate Zoom invite or would we just use the MP Zoom? Not sure if it's used at other times for any of the other calls.

If separate, just let me know where to send the invite. Thanks!

**Comment by aeiras** [comment]
Hey you two, 
I recommend you use an external medium of communication for that follow up. 
we have never used the zoom for such a conversations.

**Comment by ghost** [comment]
ok @nsardana-bny  if you email me at debbie.hoffman@payara.fish I can send an invite (or you can send me one there). Not sure how to contact you outside of here. Thanks!

**Comment by nehasardana09** [comment]
Hi @debbiehoffman you can send me an invite on neha.sardana97@gmail.com

**Comment by cesarhernandezgt** [comment]
Hi @debbiehoffman @nsardana-bny 
During July I offer help to Neha for the background duties. I'm happy to help during August too. 
I just sent you both an email in case I can still catch up with the handover zoom session.

**Comment by debbiehoffman** [comment]
Onboarding completed. (Thanks @nsardana-bny and @cesarhernandezgt ). Closing this issue as there is no reason to keep it open.

**Comment by ghost** [comment]
Updated the Mktg-call steward onboarding & responsibilities document for review: https://docs.google.com/document/d/1ayqaFoXGeTZdneL6U9oekaZP3LPe7PapTlg7jh7eD3M/edit

**Comment by ghost** [comment]
@aeiras  (and anyone interested!) you've asked that I provide a retrospective on Leading August work as the call steward.  I found it overall to be easier than I was anticipating, but I personally feel there is a lot of repetition with our github issues (several times I felt like I would open an issue/ticket, click several links from within an issue to get to another issue and google doc with more related info, some info was in Wiki's...  and try to piece it all together) and as I've said on a couple of our marketing calls - I think we could do with fewer issues. (Still do the work, but contain the information and tasks a little more). I think in general there is 'information overload'.  Ed's suggestion to make more of the checklist style issues may help - where we are placing multiple issues in a single issue for tracking purposes but that still requires someone to add them to the appropriate template/overview issue in the checklist for it to work.

I edited the onboarding document for call stewards and I think that will help a lot as new people come in to run the meetings. As a google doc, I like that it can be edited regularly and I think turning it into a Wiki might make that process a bit more challenging (more tech hurdles to get over just to make a small edit) - but as long as we have the basic steps here I think everyone will comfortably step in and take the reigns! 

I'm going to go ahead and close this issue with this comment, now.

**Comment by aeiras** [comment]
@debbiehoffman, 

Did you provided the oral retrospective in the mktg calls yet? 
If you haven't, lets do that next Monday :) 

With you on creating 1 Master ticket to own multiple tickets that are part of a ONE task. Ed has volunteered to do that clean up. Let's ask him on Monday as well.
