### ISSUE TITLE
[Content creation - Youtube Import ] Mktg video recording 7/19

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#541]
Thank you, @Emily-Jiang or @jclingan for helping with export to youtube!

**Comment by Emily-Jiang** [comment]
I could not upload the recording to youtube as the login does not approve my device:(
his device isn’t recognized. For your security, Google wants to make sure it’s really you. Learn more
@jclingan I think it might have to send a code to the mobile number associate with the microprofileio email.

**Comment by aeiras** [comment]
@Emily-Jiang, 

You need to be added as an admin to the MP Youtube channel. You are not yet based on the [INFRA spreadsheet inventory](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1113152235)

4 MicroProfilers have access. 
@jclingan can you please add Emily to the tool?
Emily, once you gain access, please update the INFRA sheet. Thank you everyone,
