### ISSUE TITLE
[MPWG Release] Tweet MicroProfile 4.1 release

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#542]
For the purpose of reviewing the staged Twitter MicroProfile 4.1 release graphic and text, the link will be:

https://github.com/eclipse/microprofile/releases/tag/4.1

Twitter description for @rstjames
#MicroProfileAnnouncement: 💛@MicroProfileIO 4.1 Release is now available! This release contains an update to Health and relaxes compatibility constraints.

Check it out here: https://github.com/eclipse/microprofile/releases/tag/4.1

#OpenSourceFUN #ByCommunityForCommunity

**Comment by aeiras** [comment]
@ederks85 

Is there a plan to write a release blog for the release? 
Usually all releases contain that link instead of Github. 

Check the template under the wiki https://github.com/eclipse/microprofile-marketing/wiki/How-to-Process-MicroProfile-Releases

having only 1 spec changed, it shouldn't be complicated to do the write up using the template.

**Comment by ederks85** [comment]
No we haven't talked about it, but sure, I can write up something. I will try to get it done this week.

**Comment by aeiras** [comment]
Excellent! 

Edwin ideally you & Emily check the current documentation & together by doing, we update it before adding it to the formal wiki. 
the last time we update it was December 2020 before we actually use the formalized new process. 

Actions lead to the current truth of the steps. 

💛

**Comment by Emily-Jiang** [comment]
I have updated the slide deck for MP 4.1 [here](https://docs.google.com/presentation/d/1iBKpx7pAV4PRfJVPuJSN07PiqsBqji0bRgEEr5opuLM/edit#slide=id.gb262a5e73a_0_14)

**Comment by aeiras** [comment]
Hey you two, 

The slide deck requires its own git ticket to trigger the update in 2 sections of the website:

1. main page
2. Resources page under Presentation

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/10731224/127201684-8ae28ce8-8ad4-4df0-9b0c-fede850ffcae.png">

@Emily-Jiang while going through this, can you help improve the documentation in the wiki?  

We want to make sure that the follow up is effortless and that anyone, a new trainee under an MP release, is ok to follow up marketing steps. 

Cheers,

**Comment by rstjames** [comment]
@ederks85 has this gone out already or do you still need something from me?

**Comment by ederks85** [comment]
@rstjames it has not gone out yet. We are still working on the content in #546, #547 and #548. After these have been closed, the tweet can go out.

@aeiras @Emily-Jiang please add your input if I'm missing anything
