### ISSUE TITLE
[Documentation ] Update marketing and release documentation

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#543]
As discussed during the July 20th 2021 Mp hangout:
- Update [MP release guidelines](https://wiki.eclipse.org/MicroProfile/SpecRelease/Release) with marketing details
- Move marketing guidelines to 1 specific document

**Comment by aeiras** [comment]
Gracias, Edwin!

There are layers of marketing listed [How to Process MicroProfile Releases](https://github.com/eclipse/microprofile-marketing/wiki/How-to-Process-MicroProfile-Releases)

Items:

- write a release blog using the templates listed in the wiki
- update the website, cards and all
- push stuff via MP media, MP uses Hootsuite so it goes to 3 channels in 2021 (this needs updating)
- update to forums, last step. 

Throughout the years we have written the content. 
Now, we can add it to the formal release MPWG wiki by parts. 

-- I will convert the word document into a wiki that will welcome PRs and improvements as we iterate. 

Stuff got adjusted on MP 3.1 while many onboarded into helping with that release while most of us were out on vacation for the XMas holidays, so stuff needs revision as well. 

-- Prioritizing it now.

**Comment by Emily-Jiang** [comment]
I have updated the spec release [process](https://wiki.eclipse.org/MicroProfile/SpecRelease/Release#Major_or_Minor_Final_Releases) to cater for final platform release.

**Comment by aeiras** [comment]
Edwin and Emily, 

14, 15 & 16 steps ought to be consolidated into 1 step under marketing documentation. 

Simplication is the point of the current work. :) 

Other git tickets are helpful to improve what currently is.

**Comment by aeiras** [comment]
We have successfully linked the Technical guidelines to the Marketing guidelines. 
Closing this ticket. :) Thanks Edwin and Emily.
