### ISSUE TITLE
Zoom code and meeting set up

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#544]
Hi @jclingan
 I'm up next for the MP marketing call stewart and as per the Zoom Admin doc, requesting help here to schedule meeting to the Zoom-internal calendar AND the MicroProfile Google calendar. I'll also need the Zoom code.

**Comment by aeiras** [comment]
Días Debbie, 

I sent you along the few other Stewards, the access code via email months ago. 

There is no need for you to have zoom Inter at access, you don’t need it. I don’t have it myself. 

I will forward that email you later today. 

Debbie, please connect with Neha to get on boarded. 

☀️🤗

**Comment by aeiras** [comment]
Access to the external calendar sadly follows the EF Infra restrictions & is only editable by MP Committers. FYI Debbie! 

Do ask away & pull me in & others as you are doing now to unblock you. 💪🏼 You will rock August! 💕

**Comment by ghost** [comment]
Ahh.. ok then I have already found things in the doc for Zoom admin that
need editing, because I just followed the steps that said to ask John for
help scheduling the meeting and to get the zoom code. It's not clear when
or who would need to do that as it seems it's just a step everyone does to
use Zoom for MP meetings.  I have reached out to Neha.

**Comment by aeiras** [comment]
Totally 😎 cool Debbie! 

That part was written months ago, before q2 started when John & I set up the zoom. 

It needs changing to “onboarding Steward” instead of John. That’s why you onboarding is crucial to current documentation & you chatting with Neha! 🤗
