### ISSUE TITLE
[Documentation]  Marketing Release Updates

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#545]
I have updated the 2 documents (google doc and wiki) below to enable MicroProfilers review:

1. [MPWG Marketing Releases Guidelines- dDrive](https://docs.google.com/document/d/1L3ek2RNvFnzydhuLYJCVEQTumKdMGTO3-xCH73KHjNY/edit#heading=h.lpcvu88vf4zy)
2. [Marketing Release Process, wiki](https://github.com/eclipse/microprofile-marketing/wiki/Marketing-Release-Process)

@ederks85 & @Emily-Jiang, 

as you are undergoing the process, you are most welcomed to submit PRs against the wiki and use Suggested mode in the document. I will send this ticket to the mktg forum and also add it to next Monday priority item in the agenda

**Comment by aeiras** [comment]
the wiki has been updated using the reviewed word document. https://github.com/eclipse/microprofile-marketing/wiki/Marketing-Release-Process

Now only awaiting the 1 issue template to hold all the tasks into 1. https://github.com/eclipse/microprofile-marketing/issues/551

**Comment by aeiras** [comment]
I provided some feedback awhile back. 
Where are we on this task? :) thank you to everyone involved!

**Comment by ghost** [comment]
This task should be completed as it was for updating the marketing release process - and that one is done. There are already tasks for creating the 1 issue template to hold all release tasks together.

**Comment by aeiras** [comment]
Debbie, 

We need to create a template git issue that will be used for all future marketing work on Technical releases. Example are the 2 templates created under the MPWG repo. 
 https://github.com/microprofile/microprofile-wg/issues/new/choose

MP marketing repo doesn't have that yet. You created the steps, they just need to be templated for ongoing help. that exact link to the template will be added to the documentation under the marketing wiki release. It is the item that is missing.

**Comment by aeiras** [comment]
Hola @debbiehoffman 

The documentation is now complete. The release checklist you created is now linked to the HOW guidelines. 
Now, you can close this ticket with the git page under the MPWG repo. :) Please let me know if you encounter any issues. thank you for rocking on making the processes better!

**Comment by ghost** [comment]
I am unable to close this ticket - just have an option to comment.

**Comment by aeiras** [comment]
@debbiehoffman, 
You have MP Triage access to repo. You can close tickets, assigned tickets to microProfilers, projects, labels, etc.

**Comment by aeiras** [comment]
Debbie, I updated the git issue template in the documentation. https://github.com/eclipse/microprofile-marketing/wiki/Marketing-Release-Process

Should you see anything a miss, let's fix it. Thank you so much for bringing such clean aspect to the process!
