### ISSUE TITLE
[MPWG Release] Design Card for Social Media, Blog announcement and Website 

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#546]
At the moment, microprofile.io still mentions MP 4.0. This needs to be updated to point to MP 4.1.

- [x] On the top card, update MicroProfile 4.0 to 4.1 
- [x] On the top card, More Information points to https://github.com/eclipse/microprofile/releases/tag/4.1
- [x] On the 2nd card, Update MicroProfile 4.0 to 4.1. Health 3.0 will be updated to Health 3.1 while the others are unchanged.
- [x] Move the MicroProfile 4.1 presentation from this [location](https://docs.google.com/presentation/d/1iBKpx7pAV4PRfJVPuJSN07PiqsBqji0bRgEEr5opuLM/edit#slide=id.g24c0b02670_0_0)  to the [latest Release Prsentation](https://drive.google.com/drive/folders/1zqIzegskeYUCualDek3Wq4Sle9qW-_eY)  and then move MP 4.0 deck to the archive dir or 2020 release folder

**Comment by ederks85** [comment]
I have updated slide 7 (MicroProfile 4.1 Released!) in the presentation to include the lifted compatibility requirement for CCR. Can you please verify if this text is correct?

**Comment by Emily-Jiang** [comment]
Thank you @ederks85 ! Looks good!

**Comment by Emily-Jiang** [comment]
This one depends on #547 #548

**Comment by rstjames** [comment]
@Emily-Jiang @ederks85 @aeiras  

Should these updates be done now? or are we waiting for something?

**Comment by ederks85** [comment]
The updates mentioned in this issue can be done now.

Additionally:
#547 requires a change in the Duke logo used in the presentation
#548 has been reviewed. You only need to accept the suggestions

**Comment by edbratt** [comment]
MP Presentation has been relocated (checkbox 4 in the issue summary). [Here is the 4.1 presentation](https://drive.google.com/drive/folders/1zqIzegskeYUCualDek3Wq4Sle9qW-_eY)

**Comment by rstjames** [comment]
@Emily-Jiang @aeiras @edbratt @ederks85 
 
 What we are missing to get this released today:

- [ ] 1. update block image "3.1 health"  -  DONE  (Not sure we can add "Jakarta Annotation" today- also it will make a odd structure the blocks )
- [X ] 2. Update drive with 4.1 pres (in latest pres folder) (Ryan)
- [ X] 3. 4.1 Short descriptions for home page (Ryan)
- [ X] 4. Tweet message image (Ryan)
- [ X] 5. Blog on WP (Ryan)

Tweet:
#MicroProfileAnnouncement: 💛@MicroProfileIO 4.1 Release is now available! This release contains an update to Health and relaxes compatibility constraints.

Check it out here: https://github.com/eclipse/microprofile/releases/tag/4.1

#OpenSourceFUN #ByCommunityForCommunity

**Comment by rstjames** [comment]
![Microprofile-4 1_release](https://user-images.githubusercontent.com/12132146/128356439-af7fec28-fee1-4627-aed2-62a083fcbcb6.png)

**Comment by rstjames** [comment]
All that is left is moving the 4.1 presentation to the correct "latest version folder" on the drive and move the 4.0 presentation to the old version folder.

**Comment by ghost** [comment]
It appears the 4.1 presentation is in the[ latest version folder here](https://drive.google.com/drive/folders/1VheJD9sJBiwfXSH1Lbc-eQtVuz4BFM6d?usp=sharing) and it appears the 4.0 presentation is in the [2020 Releases folder here](https://drive.google.com/drive/folders/1WeFgN1SDzf6Z_9fN9308DACBxr1Ukwgz?usp=sharing)

It appears the Tweet with the designed social card about the announcement has been[ published here](https://twitter.com/MicroProfileIO/status/1423317267882905600?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1423317267882905600%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2FMicroProfileIO2Fstatus2F1423317267882905600widget%3DTweet): 

And that the Microprofile.io homepage has been updated and the[ blog announcement published](https://microprofile.io/2021/08/05/microprofile-4-1-is-now-available/).

**Comment by aeiras** [comment]
Debbie, 

Good call out Debbie. There is an ongoing discussion where I explained to Emily that we won't be moving Releases content to the EF infra drive. 
The work was completed and stays under the MP Community drive that will continue to provide and welcomed contributors from all walks in our ecosystem and not those from the Steering Cmtee only. 
This is nothing new on the process, https://drive.google.com/drive/u/0/folders/1pyUT50_taXQe-8qKAzBZcwJDb5s6TedR.  I will delete the other content to avoid duplications. Thanks for reminder. 

-- 

The only thing missing is the finalizing of the word document review to inserted into the wiki. This ticket and others related to tasks done can be closed. I will go to it now and help on that as well. Ñ)
