### ISSUE TITLE
[MPWG Releases]  Release Presentation Update - MP # 4.1

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#547]
The Presentation is [here](https://docs.google.com/presentation/d/1iBKpx7pAV4PRfJVPuJSN07PiqsBqji0bRgEEr5opuLM/edit#slide=id.ga6bdad56ea_1_37)

**Comment by Emily-Jiang** [comment]
Please review. If no more comments, please import it to the Website, 2 sections: Landing page & Resources  page

**Comment by aeiras** [comment]
@Emily-Jiang, 

On the first page, the Duke logo needs to drop the Java portion and be exactly as it is in the website. 
We are not allowed to use the old logo anymore. 

Thanks for updating it.
