### ISSUE TITLE
[MPWG Releases] Announcement Blog - MP 4.1 Release 

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#548]
The blog is [here](https://docs.google.com/document/d/1cWZASF0krdnuuOdwFJoFR69w6NurPqbsafwsvqie0DE/edit#)

**Comment by aeiras** [comment]
Emily, 

I am happy to be the final reviewer and publisher. 
Who else reviewed the blog?

**Comment by aeiras** [comment]
> The blog is [here](https://docs.google.com/document/d/1cWZASF0krdnuuOdwFJoFR69w6NurPqbsafwsvqie0DE/edit#)

@Emily-Jiang, 

The document is not in the drive under Releases nor Community folder, I cannot help with the review. 
I am off tmw and Friday. 
Another Triber will have to help with the final review.

**Comment by Emily-Jiang** [comment]
@aeiras the blog is in the [MP drive](https://drive.google.com/drive/u/0/folders/1pyUT50_taXQe-8qKAzBZcwJDb5s6TedR) , based on the instruction you posted. Not sure why the link does not show up the drive location.

**Comment by aeiras** [comment]
@Emily-Jiang, 

Now I see it and it allows me to help with review :) thank you!

**Comment by ederks85** [comment]
I have also revied the blog and left a few comments. Looks good though :)

**Comment by aeiras** [comment]
Edwin and Emily, 

I feel happy with the latest version yet I provided additional recommended improvements. 
If need it, please remember to pull me back into the review via this ticket. 

Always fun to work on stuff with the 2 of you! :)

**Comment by Emily-Jiang** [comment]
@aeiras thanks for the great comments! I have accepted them and added one more sentence to make it more explicit. Please take a final look to see whether you have more comments. I think we are good to go tomorrow. @rstjames we can work on the webpage tomorrow. Once you have made the changes, please get in touch so that I can view them.

**Comment by aeiras** [comment]
Emily, 

It reads even better!   done with review and I approved your improvements. 

Now, let's enable Ryan to rock it. :) Have fun with him on the last steps. 

Afterward, please review & help improve the guidelines word document. I plan to insert it into the wiki next Monday. Other MicroProfilers are working on simplification as well.
