### ISSUE TITLE
DevRoxx 2019: MP has the option to sponsor DevoxxUK Community Party? 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#55]
[About the Conference, Speakers' list](https://devoxxuk19.confinabox.com/talks/conf)

[MP workshop](https://devoxxuk19.confinabox.com/talk/TTC-5728/From_Zero_to_Microprofile_Hero_-_Let’s_dive_into_a_Microservices_World)

[About DevRoxx, current Partners](https://twitter.com/search?f=tweets&vertical=default&q=devroxx&src=typd) 

1.  Every sponsor gets a tasty beer with your choice on the branding. The Community sends many names that the sponsors choose from. Just Fun. 
Estimated +600 attendees 

[Beer Naming Competition started 4/10/19](https://twitter.com/DevoxxUK/status/1115932999768510464)

- [Clever Cloud](https://www.clever-cloud.com)

- [Voxxed](https://twitter.com/voxxed?lang=en)

- [Tomitribe](http://www.tomitribe.com)

- [4th Partner]  Available

**Comment by aeiras** [comment]
added a few of you. Will send an email to MP Community in a bit to share ticket! :)

**Comment by smillidge** [comment]
We have no presence at Devoxx UK

**Comment by aeiras** [comment]
Thanks for the prompt follow up @smillidge :)

**Comment by aeiras** [comment]
taking the liberty to add you Brian.   @bbenz

**Comment by bbenz** [comment]
Microsoft won't be able to help on this one.  I'm looking into swag/funds for future events.

**Comment by cealsair** [comment]
In the process of finding out if Red Hat would be interested in participating.

**Comment by cealsair** [comment]
How much would it be per sponsor?

**Comment by aeiras** [comment]
Hola @cealsair, the total cost is 3000 Pounds divided by interested sponsors. 

Tomitribe is a full sponsor of 1 slot, so that amount should be divided by other (s) interested MicroProfile Partners. Thanks for the follow up!

**Comment by cealsair** [comment]
Hi Amelia,

Red Hat is interested in being a sponsor of the Community Party. Could you put me in touch with the conference contact so that we can issue payment?

Thanks,
Cesar

**Comment by aeiras** [comment]
That is wonderful Cesar. I will send email internally to you and DevoxxUK team. Closing issue 👍
