### ISSUE TITLE
MicroProfile Recording Link - August 2, 2021

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#550]
Hi @jclingan,
I recorded the August 2nd meeting to the cloud, but don't think I have access to upload it to Youtube. ( Call Stewards list of responsibilities says it's in this folder, but I didn't see it there. https://drive.google.com/drive/u/0/folders/1e4Tm-zrmmc9b-8H8BW7DfXRlG6uzNqmy)  Can you upload the recording please?

Thanks, 
Debbie

**Comment by nehasardana09** [comment]
Since @jclingan is on vacation, we can ask @Emily-Jiang since she has admin access too.

**Comment by ghost** [comment]
Hi @Emily-Jiang  and @jclingan  just following up on the recording for August 2nd meeting.

**Comment by Emily-Jiang** [comment]
@debbiehoffman @jclingan has uploaded a few days ago. it is [here](https://www.youtube.com/watch?v=xXwZl8e9kWU)
