### ISSUE TITLE
[Website - MPWG Page] CN4J Messaging import

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#552]
[Jakarta and MicroProfile Positioning ](https://drive.google.com/drive/folders/1YTXkiwCC8In5G356c008xspszaStswRs)

Needs to be added under MPWG [page ](https://microprofile.io/workinggroup/)
@rstjames I am assigning it to you to get this improvement set. Thank you!

**Where:**
Under the Knowledge tab
after MPWG Repository

- The MPWG and Jakarta EE communities created & voted on a [Positioning Message ](https://docs.google.com/presentation/d/1wVaGJssQKPDSRcgRSE52mmm2Lb55THyUc_dGj7F5SAg/edit#slide=id.gbcfab764b6_0_221) that explains the powerful collaboration that exists between the two communities. Learn more about the shared Implementations, Members, API collaboration, and the differences between the 2 projects.

**Comment by rstjames** [comment]
Updated
