### ISSUE TITLE
[General- Calendar & Zoom] Issues with the Zoom access to the MP marketing calls

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#554]
Today, August 2nd mpMarketing call encountered issues with the following "old" access restriction:

- Waiting for the host to start this meeting
<img width="887" alt="image" src="https://user-images.githubusercontent.com/10731224/127936292-92df0265-3da3-4c48-a1fa-61dfcd9d0f2d.png">

- the Zoom access ID was changed from previews number https://eclipse.zoom.us/j/97431685452 to August 
https://eclipse.zoom.us/j/99971055231

- location mapping was added to the calendar, causing the link to no longer work and creating work for attendees. 

We need to know why changes were made without a git ticket and communication to the Mktg forum (as the bare minimum)
We also need to delete the current meeting ID, internally in Zoom.  (only John, Emily, and Kevin can do that) Current access contains not scalable and desirable call access.

Though 10mins of frustrated MicroProfilers were it this AM, with Debbie as the August Steward we owned a valuable 50 mins call. Thanks to Emily for using your new Zoom Admin access to temporarily correct today's access.

**Comment by aeiras** [comment]
I have fixed August 16th and onward mpCalendar by deleting the Zoom mapping access link and adjusting the description documentation. 

Please do not delete this external event. It contains the entire MP community. 
When changes are needed, we do them directly in this event and we avoid sending notifications to the **listed guests** on the changes done on the event. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/10731224/127937359-5f7fe1f4-1f98-4613-a3bb-e4db9617e0f3.png">

**Comment by aeiras** [comment]
Emily and John, 

Have you located the issue with latest change on the general mp mktg calls?

We need the situation fixed before Monday call. Thank you for looking into issue.

**Comment by Emily-Jiang** [comment]
I checked the calendar and zoom set up. They look ok to me. Maybe @jclingan has fixed it. Let's try it out today to see whether the same problem still occurs.

**Comment by aeiras** [comment]
Ok, we will know in 30mins. 
If there is a recurring issue, we will delete all traces of future Mktg meetings and create a new event. :) thanks Emily! 
No need to waste for time on this.

**Comment by jclingan** [comment]
I think the problem was that the meeting was scheduled for 12AM central time (instead of 12PM, LOL). Regardless, I created a new meeting as we discussed and updated the calendar entry. Closing issue.
