### ISSUE TITLE
Community voting process for MP Compatible logo

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#556]
Here we should decide what/ who/when we would like to send out the logo options for voting. 

Suggestions:
- survey monkey
- Rating scale voting

How many days?

**Comment by rstjames** [comment]
I will make an SM image for promoting the vote

**Comment by aeiras** [comment]
Ryan, 

Thank you for creating the git issue and starting the investigation into the best vendor to use for Scale Voting that allows to choose by preference multiple logos in Ranking. 

https://docs.google.com/document/d/1K-in78vt6z4VCMIFidiPy-Ir53PwRCU3Nt8eIqy7su0/edit#

I have drafted the Tracker How to, which was missing. 

As discussed on this week's community call, next Monday will be used for tackling your findings and coming together to decide on final stuff.  The agenda will be sent in a bit to the forums. 

-  only MP general forum subscribers can vote (email associated with her/his subscription to mailing list required item)  -- This was decided weeks ago.  (checking will be done internally, likely by a few volunteers)

-  voting can only start after the Steering cmtee has voted on moving ahead with 1 logo Trademark, potentially ~8/16 or later that week. 

- time: max 14 days. to be discussed. 

- transparency on results during Tracker's time collecting feedback:  recommendation private (to be discussed)

- results to be shared with stats & all that Survey Monkey provides from the activity (free or paid? - please provide recommendation on what is needed based on requirements)

- push Tracker via the forums and also social media + 1 with reminders

**Comment by rstjames** [comment]
I have looked into a couple only voting products. But I think sinse we used in in the past survey monkey is our best choice. 
- to do **rate scaled** voting we will need an ADVANTAGE account  44.50 USD a month
- ADVANTAGE is the cheapest plan. https://www.surveymonkey.com/pricing/individual/?ut_source=pricing-teams-details

Does anyone else have a platform they would suggest for voting?

Once we get this setup, I can add all logo images and create the poll.

Here is how the logos will be presented on the poll.
![Microprofile-campatibility-logo-options5](https://user-images.githubusercontent.com/12132146/128734455-c717d575-cf82-4d8b-b3df-f2cb735d2775.jpg)
![Microprofile-campatibility-logo-options4](https://user-images.githubusercontent.com/12132146/128734463-0dbabc37-8a7e-4441-987d-3c212b7d061c.jpg)
![Microprofile-campatibility-logo-options3](https://user-images.githubusercontent.com/12132146/128734467-0fda0ae1-0ead-4977-854f-ec997cf09b52.jpg)
![Microprofile-campatibility-logo-options2](https://user-images.githubusercontent.com/12132146/128734472-6979566e-c1dd-4c03-92f7-f02143bea850.jpg)
![Microprofile-campatibility-logo-options1](https://user-images.githubusercontent.com/12132146/128734479-6e96ea64-5e8e-4502-bbf3-e26cc7e66cc5.jpg)

**Comment by aeiras** [comment]
voting tools from Q1 2021.

**Comment by aeiras** [comment]
https://docs.google.com/document/d/1OIZxjrS2dr_gjP5PjLVegYUCG1kkW_BP5du_0l8O4to/edit#heading=h.y4w93ve1fr4s

**Comment by rstjames** [comment]
Survey money can restrict who can vote by setting a password. But this means we will need to email everyone that is allowed to vote and provided them with the email. https://help.surveymonkey.com/articles/en_US/kb/Can-I-block-or-restrict-access-to-my-survey

**Issues I see with password restrictions**
- People missing the email with the password. 
- Promoting on social media and people not knowing where to get a password

**Comment by rstjames** [comment]
We can send the poll with the email list we have:  https://help.surveymonkey.com/articles/en_US/kb/Email-Invitation-Collector

**Comment by aeiras** [comment]
https://docs.google.com/document/d/1J4HweWHU_UKtFHDp2nkf0bcl4YjF-JSv/edit#

@rstjames previews research on trackers now in the Community folder. Please help update it. You are welcomed to add the Resolution of Choice: Survey Money at the begging of the document as well, if you want to. 

Thank you,

**Comment by aeiras** [comment]
Ryan on send email, i just saw that it lets you choose a focum or google group, this is great. 
Can you test it with a marketing forum on a play test? or do we need to tackle the account first? 

If so, all the testing will have to wait but I am SO HAPPY we can add the committer & mp forum.

**Comment by SharonCorbett** [comment]
Please remember as communicated during the Community Call on August 17th, a request for a SurveyMonkey account or otherwise must be requested in advance via the Eclipse Foundation.

**Comment by aeiras** [comment]
Happy Monday Sharon, 

Today during the mktg call, we discussed SurveyMonkey logistics and you can expect our follow up in the next coming days. Thank you for collaborating via git issues. We appreciate that form.

**Comment by aeiras** [comment]
We need to close this issue given that we have dropped the compatible program and MP moves to a simplify logo format. 

We could still use some form of the logos submitted with modifications as stated on this issue https://github.com/microprofile/microprofile-wg/issues/107
