### ISSUE TITLE
[Documentation - Trackers Process]  Conducting Surveys and Polls

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#557]
https://docs.google.com/document/d/1K-in78vt6z4VCMIFidiPy-Ir53PwRCU3Nt8eIqy7su0/edit#

welcomes Suggestive mode feedback and improvements

**Comment by ghost** [comment]
Made some suggestions for readability.

**Comment by aeiras** [comment]
@debbiehoffman, 

Wonderful feedback Debbie, 100% accepted!

**Comment by aeiras** [comment]
wonderful feedback Edwin! @ederks85

**Comment by aeiras** [comment]
Thank you to all of you, the wiki has been created. The word document has been moved to Survey's folder under Archive. 

https://docs.google.com/document/d/1K-in78vt6z4VCMIFidiPy-Ir53PwRCU3Nt8eIqy7su0/edit#

**Comment by aeiras** [comment]
https://github.com/microprofile/microprofile-wg/wiki/Why,-When-and-How-to-Conduct-Surveys
