### ISSUE TITLE
MP LRA calls are not happening periodically anymore

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#559]
I noticed this tweet yesterday - https://twitter.com/MicroProfileIO/status/1424626707781365762 which is promoting MP LRA call on Monday which is not happening for quite some time so I don't want people from the community joining when there will be no one from the spec group. I asked in out [gitter channel](https://gitter.im/eclipse/microprofile-lra) and no one objected to deleting both this tweet and call info from the MP calendar. 

Can you take down this tweet, please?

@jclingan can you remove this call from the calendar, please?

**Comment by aeiras** [comment]
Martin, 

Thank you for the update. 
I have deleted the external event sequence. 

@jclingan or @Emily-Jiang will help with internal zoom deletion. 

@rstjames will help with media deletion. I tried but we moved mpMedia from buffer to Hootsuite and I don't know where the schedule happen. :) 

Thanks to everyone,

**Comment by Emily-Jiang** [comment]
I checked the meetings on zoom. This meetings were not there, so we are good.

**Comment by aeiras** [comment]
Great Emily. Thanks for checking that!

Lets wait for Ryan to delete the 2021 events. :)

**Comment by rstjames** [comment]
@aeiras social media posts have been deleted.

**Comment by aeiras** [comment]
Thank you, Ryan!

**Comment by xstefank** [comment]
Thanks!
