### ISSUE TITLE
Linked Article submitted for review

### ISSUE THREAD

**Issue by bbenz** [microprofile/microprofile-marketing#56]
https://microprofile.io/?p=6190&preview=true

**Comment by aeiras** [comment]
@bbenz the link to your Dzone blog is incomple. https://dzone.com/articles/how-to-use-recent-microprofile-and-jdk-features-to    [missing ]
Please adjust it. 

The rest is great. I have published the post since I can correct blog in the next 3hrs if you are not able to get to it. :)

**Comment by aeiras** [comment]
disregard, you are Mexico bound, i just fixed it-- but only this time around :) 

Thank you for being awesome with knowledge transfer Brian. Closing issue!
