### ISSUE TITLE
[Youtube Settings Update] Play most recently added video in playlist

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#560]
Hello Youtube Admins @jclingan, @Emily-Jiang, and @rstjames

Is it possible to change hte view settings on the marketing meetings playlist (https://www.youtube.com/playlist?list=PLJPCiPRVVzBa1ncUXIgsUDbFx631GykHT) so that it is set to play the most recently added video?

**Comment by jclingan** [comment]
I’ve updated. I updated setting to add most-recent first. I’ve also sorted all the playlists to be more-recent first. It works under the MP account and my personal account, but hoping others can load the playlist and see what it looks like.

**Comment by ghost** [comment]
Yes, it loaded our most recent one first and looks like they're all sorted recent-first.

**Comment by jclingan** [comment]
Hurray! I thought that was a personal setting (only applied to the person doing the sorting).  I am closing this issue.
