### ISSUE TITLE
Please upload Zoom Recording of Marketing Meeting August 16 to Youtube

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#561]
Hello John @jclingan and Emily @Emily-Jiang  - could someone please upload the recording to Youtube.

**Comment by jclingan** [comment]
Done and [tweeted](https://twitter.com/jclingan/status/1427422837002825747).

**Comment by aeiras** [comment]
John, 

you reply with the tweet in this git issue allowed for the fastest MP re-tweet b/c it arrived via email. No need for me to be on the look out tmw or later. Thank you!  

Can you always do that? if yes, super super appreciated!  :)

**Comment by jclingan** [comment]
Sure, NP
