### ISSUE TITLE
[General]  Delegation task - August 30th Coverage

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#562]
@debbiehoffman, 

Please use this ticket for anything you might need me to handle on your behalf on the August 30th call! :)

**Comment by ghost** [comment]
Thanks @aeiras 
 I went ahead and added the info to the agenda using the new table format for the August 30th call so it's ready for people to update and add between now and the meeting. I'm good to keep an eye on things to try and keep it updated as well - just can't attend on the 30th. Thanks!

**Comment by aeiras** [comment]
Thank you, Debbie, for clarifying your expectations. I appreciate it! 

You can delegate stuff as you see fit before the call to me. 
Family always comes first. 

Thankfully, most MP tasks are not time-sensitive for the unblock/regular calls. :)

**Comment by ghost** [comment]
Hi again, Amelia!
 I think I've updated the Agenda with any relevant issues and updates for the Monday Aug 30 meeting. I sent out the notice of the agenda and meeting to the MP google group.

My update on anything currently assigned to me in the agenda is that it will happen in September as I just couldn't get to it this month and am off next week. Let me know how it goes using the table format for the meeting, hoping it is easier!

**Comment by aeiras** [comment]
Count on such update, Debbie! 

With you next week. Take care of yours and see you upon your return.

**Comment by aeiras** [comment]
@debbiehoffman, 

We used the new minutes format, it worked great. 

Given your written call to action on Sept and Nov. Stewards, Ed will lead the Sept work and Tetiana Novemember. Expect those follow ups directly by the MicroProfilers. 

Many tickets are being tackled and will be completed this week. 
I will create right now the agenda minutes & update stuff based on today's discussion. 
There is no MPWG mktg call happening next Monday based on today's follow up tasks. :) 

When you return, with calm you can provide your retrospective on Leading August work + more. 

Stay safe,

**Comment by aeiras** [comment]
oh and tomorrow, the marketing update during the community call will be about the current status of the MPWG Compatible spreadsheet items. https://docs.google.com/spreadsheets/d/1Qy_lawEXWUMYPlUVi7aziu0LELrZIhbRr6J6H8YsHc4/edit#gid=0
