### ISSUE TITLE
Tweet for Edwin on becoming a Java Champion

### ISSUE THREAD

**Issue by dblevins** [microprofile/microprofile-marketing#564]
How about something like this:

> 
> Congratulations to MicroProfile committer and Committer Rep @edwinderks on being elected into the @Java_Champions!
> 
> When you get involved with Open Source, good things can happen!
> 
> Learn about Edwin's journey getting involved with MicroProfile https://microprofile.io/2019/08/14/onboarding-interview-edwin-derks-into-microprofile/

**Comment by aeiras** [comment]
@rstjames, 

Can you please help us prioritize this tweet with a very cool design card for Edwin?
 BY your AM tomorrow!

We don't have yet a Congratulations template for MicroProfiler Java Champions. Lets create one! :) 

Thank you,

**Comment by ghost** [comment]
+1 for tweet

**Comment by rstjames** [comment]
Thoughts on the image? 
Not sure about the wreath but it kinda goes with the old duke java champion logo
![microprofiel-java_champion-edwin-derks](https://user-images.githubusercontent.com/12132146/129915647-ef3d6037-fce5-4fe3-8d20-1916319d4150.png)

**Comment by aeiras** [comment]
Ryan, 

can we please insert into the imagine the duke & java champions logo? 
 Please look at the left lower corner of this tweet for reference.  Thank you! 🥋
 
 https://twitter.com/java_champions/status/1427380962392870946?s=21

**Comment by aeiras** [comment]
Oh & I like the wreath, it is cute ☺️

**Comment by ghost** [comment]
Ryan, 
 it looks good! Congratulations is with a "t" not a 'd'  :)

**Comment by mpredli01** [comment]
Looks awesome!

A big +1 from me!

**Comment by rstjames** [comment]
Updated: 
![microprofiel-java_champion-edwin-derks-1](https://user-images.githubusercontent.com/12132146/129944373-0bc722e9-4c66-4e47-a948-2573e1ae7774.png)

**Comment by aeiras** [comment]
It is perfect, Ryan!! you nailed it :) thank you!

Can you add the template to the drive for future usage also?
Please, submit the tweet on David's community forum msg as a yeay celebration.

**Comment by aeiras** [comment]
https://twitter.com/microprofileio/status/1428048970312454155?s=21
