### ISSUE TITLE
[Infra- SurveyMonkey]   Logistics 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#568]
Yearly paid tool with reference to  https://github.com/eclipse/microprofile-marketing/issues/556 to be used at MPWG discression as set in the Trackers Guidelines below. 

https://docs.google.com/document/d/1K-in78vt6z4VCMIFidiPy-Ir53PwRCU3Nt8eIqy7su0/edit#  

The above **Tracker's Guideline** linked to https://github.com/eclipse/microprofile-marketing/issues/557 needs to be converted into a Wiki as soon as the review is completed. 
Only then, we can make use of setting SurveyMonkey. 

**MPWG Infra Admins Inventory** https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1069147464  contains the SurveyMonkey tab that will list the Admins and the email associated with such access, etc. 

**Infra email**

1 email provides access to the application. (will check if that is possible) We did this with Hootsuite. 
Suggested email : surveys-microprofile@google.com
If 1 email is possible, then Admins onboarding is easier and not costly. 

**Suggestions as follows and for discussion** 
<Required Admins>  2 MicroProfilers

Ryan (Tomitribe) 
Edwin (Committer Representative)

**Suggested Admins for transparency & operational process**
Tetiana (Jelastic)
Debbie (Payara)
John (Red Hat)
Emily (IBM)
Ed (Oracle)
Neha (GardenJUG)
Amelia (Tomitribe)

Opting out is welcomed for those listed above.  

**Pros to owning the Survey account**
MP can design the surveys as it see fits for each activity or create templates to enable such diverse out reach
MP can control 100% all aspects of the tool and provide as much insight to its community as it wishes without intermidiaries. 

**No cons** 

**EF as part of the MPWG could help set surveymonkey**
The EF could help set up the account. At this time I am not sure how much access and power we will have to own the guidelines above if the EF sets up the account.  

The Trackers Guidelines states the wish to keep our costs down when working on such dynamics. It is aligned with the MPWG Charter on Transparency and Community ownership. 
 Does enabling the EF to set up the SurveyMoney for MPWG means that they must mediate all activities for those activities to happen?
if so, that defeats the purpose of the Survey's value, the  account ought to be set up independently and request the reimbursement as we have done with Hootsuite and other infra tools. 

----

**Comment by TetianaFTV** [comment]
On today's MicroProfile Marketing Call (Aug 30), it has been decided to ask Eclipse Foundation to provide us with a SurveyMonkey account.

The community requires:
- 1 admin account to make and manage the needed configurations and polls (e.g. survey-admin-microprofile@)
- 1 view account to track the results (e.g. survey-view-microprofile@)

The access to the admin account will be initially provided to Ryan (Tomitribe) and Edwin (Committer Representative).
The access to the view account will be provided to all community members.

We need to get approval from Eclipse Foundation that such accounts can be created or if we need to consider other options.

Also, for each account type we'll need to create emails with joint access (e.g. survey-admin-microprofile@ and survey-view-microprofile@).

**Comment by aeiras** [comment]
@TetianaFTV, 

The cost $$$ is missing with the request. 
The rest looks great. 

Thank you for quickly drafting this follow up, Tetiana! :)

**Comment by aeiras** [comment]
Thank you, Tetiana for sending the ticket with extra content to the WG forum for EF conversation. https://www.eclipse.org/lists/microprofile-wg/msg00942.html

Added that thread to the ticket : )

**Comment by chrisguindon** [comment]
Hi Folks,

I was asked by @SharonCorbett to look and this ticket and make a recommendation on behalf of the Eclipse Foundation. 

First of all, based on the requirements listed on https://github.com/eclipse/microprofile-marketing/issues/568#issuecomment-908569952, the personal plans won't work for us.

Survey monkey has 3 business plans:
https://www.surveymonkey.com/pricing/teams/details/?ut_ctatext=See%20all%20features&ut_source=mp&ut_source2=take-a-tour&ut_source3=sm-button

1. Team advantage 27$ / user / month
2. Team premier 75$  / user / month
3. Enterprise ??  / user / month

Key differences between Premier and Advantage:

- 10,000 responses per year vs 15,000 responses per year
- Unique to Premier plans
  - **Survey builder:** Click map data visualization, Multilingual surveys, Advanced survey logic, Block randomization
  - **Customization & Branding:** Remove SurveyMonkey footer, Survey completion redirect, and White label surveys.
  - **Analysis & Reporting:** Word clouds: Combine or hide words, Sentiment analysis, Crosstabs
  - Direct API access
  
Unless we have a hard requirement for any of these features, my recommendation would be to start with the team advantage 27$ / user / month plan.

The Team plans start at a minimum of 3 full-access users. The good news is that I was going to mention that we will need to make sure that webmaster@eclipse.org is the owner of the account and must have access.

If we have a hard requirement to restrict access to the "1 view account to track the results (e.g. survey-view-microprofile@)" user, we will need to add contributors' seats.

We can add contributor seats to that in bundles of two. Contributor seats for Team Advantage are priced at $15/user/month ($180/user/year) sold in bundles of 2 ($360.00/2 seats).

The total cost of 3 full-access users and 2 contributor seats on Team Advantage is $1,260.00 USD per year. If we wanted the Team Advantage plan for 3 full-access users, the total would come to $900.00 USD.

With this said, I now have a question for the group. Are we planing to store Personally Identifiable Information (PII) on SurveyMonkey from users filling up the form?

If so, the group must adhere to the  Eclipse Foundation Hosted Services Privacy and Acceptable Usage Policy: 
https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

**Comment by aeiras** [comment]
Hola Chris, 

Thank you so much for such a great follow up, we appreciate it. 

On Monday, we have a discussion and this ticket will be our priority. 
In the mean time, 2 questions for you: 
1) what would intel if we did store PII? 

2) Yes, to you having Master access to the MPWG SurveyMoney, we understand it. :) 
Are you able to create the 2 email accounts ( 1 private & 1 public) as requested above and add them as 2 contributor's seats? 
That would make for 3 full access-users, your access and our access. 

@rstjames, 
In your original research, you chose individual Advantage as an individual plan but that doesn't work. 
Can you check once again that Team Advantage still provides us with rate-scale voting? Please have this information ready via by next Monday discussion. Thank you for submitting your findings in this ticket.

**Comment by chrisguindon** [comment]
> Hola Chris,

Hola @aeiras :)

> 1. what would intel if we did store PII?

I would recommend starting with the creation of a Data Protection Impact Assessment (DPIA) document which should describe what kinds of PII data you will be collecting and for what purposes.

Also, users with full access will need to subscribe to eclipse.org-gdpr@eclipse.org, and respond within 30 days to requests to delete accounts or make user data available to the specific user in question. The IP address of a client request is considered PII.

All of this is included in our policy: https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

> 2. Yes, to you having Master access to the MPWG SurveyMoney, we understand it. :)
>    Are you able to create the 2 email accounts ( 1 private & 1 public) as requested above and add them as 2 contributor's seats?
>    That would make for 3 full access-users, your access and our access.

Before I answer this question, I would like to better understand the reasoning for creating these accounts. Why is this preferred over using the email address of the person with full access?

**Comment by aeiras** [comment]
About the accounts:

Thus far, we identify 2 MicroProfilers who will need Admin access to create and administer surveys on behalf of MPWG. Ryan on the marketing side and Edwin on the Committer side.  (Edwin is yearly chosen to represent the committers of the WG) not permanent, so getting a private Admin group account to adjust and add more MicroProfilers as it becomes relevant for them to use Survey monkey is important to us. 

The public mailing list (2nd seat) (Not to subscribed but actually to use to log-in with the password cannot adjust stuff in Survey Monkey allows for anyone to check on MP survey results and stats (history tracing) directly in the account. In MP we thrive to protect history and be as transparent as possible for anyone who wishes to have that data. No questions asked, full access. 

We wish to design the MPWG SurveyMonkey account to our style (MicroProfilers work not the EF) and have it be an account that scales and can be adjusted by the Admins in the account. 

I hope this helps, Chris.  
On Monday 10am PDT to have a call about this, I know you wear many hats, should you wish to attend and Q&A on the recorded call, do join.   https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles

**Comment by chrisguindon** [comment]
Based on your comment. It does appear that we will need to pick the option with extra 2 contributors' seats.  I also agree with you when you say "MP we thrive to protect history and be as transparent as possible for anyone who wishes to have that data. No questions asked, full access.".

In that spirit, I believe that the WG must share the data with the group when it's requested but I don't think it means that anyone one the group should be allowed to log in. 

My concern with the shared accounts is that we lose the accountability of who did what. 

Is it correct for me to assume that we only plan on sharing anonymized data? I could see some privacy concerns if the email addresses of people are being shared across members of a WG. However, I am less concerned if the aggregated/anonymised results are shared with members.

I do see the value in using SurveyMonkey but the privacy rights of our users must be a priority. This can be done, but does require some extra effort in communicating and documenting how the tool is being used.

**Comment by Emily-Jiang** [comment]
I am wondering whether we need to have 3 admin access. I suggest we ask for input from microprofile googlegroup to see whether anyone is interested in log onto the surveymonkey to see the raw data. If not, we can have just 2 admin access and save around $300 per year.

**Comment by jclingan** [comment]
I'm ok with paying the extra ~$300 for a year to give additional access instead of screen snapshots. We have the budget this year. If it turns out that there isn't enough value there, then we can use screen snapshots next year.

**Comment by chrisguindon** [comment]
> I am wondering whether we need to have 3 admin access. I suggest we ask for input from microprofile googlegroup to see whether anyone is interested in log onto the surveymonkey to see the raw data. If not, we can have just 2 admin access and save around $300 per year.

The team plans start at 3 admin (full-access) user minimum. 2 is not an option : https://www.surveymonkey.com/pricing/teams/?ut_source=pricing-indv-details&ut_source3=megamenu

![Screenshot 2021-09-22 090905](https://user-images.githubusercontent.com/893942/134349413-c51bd067-171b-4705-a2b6-f0348d1e83c7.png)


It's the contributors' seats that we can decide to add or not.

**Comment by aeiras** [comment]
Hola Chris, 

During our discussion yesterday, we chatted about your recommendation + everything else discussed in our exchanges.
We need the 3 seats (yours, Admins & transparency). The feedback you see is that received during the call that always makes it to the ticket for tracing & reference. Apologies to confuse you. 

We will have the research completed by this Friday on things we were not sure about. 
Currently Ryan is checking if Team advantage offers ranking voting. If it does, we have a go. 

We will also draft the Data Protection Impact Assessment (DPIA) document which will describe what kinds of PII data MP plans to collect and for what purposes. (ETA next week) - 

1) do you need DPIA before setting the account? Gracias Chris!

**Comment by chrisguindon** [comment]
Sounds good! Also to add to this, @eclipsewebmaster will probably be the team responsible for setting up the account. 

Regarding the Data Protection Impact Assessment (DPIA), We want this done before we publish the first survey that will hold PII.  If the survey does not hold any PII, the DPIA is not required.

I think the best place for this document to live is on Bugzilla, under the Hosted Services Privacy and Acceptable Usage Policy component. The group can use the bug to publish the DPIA and update the issue each time a change is made to the document.

**Comment by rstjames** [comment]
Hello everyone, 
@aeiras @chrisguindon 

I wrote survey monkey to make sure what plan would work and they wrote back this: 

**All of our paid plans include questions for ranking or rating in your survey so in that regard any level plan would be a great fit. Advantage would be our most popular plan. :)

As for your request for multiple admins -- If multiple people need to work together in survey and access the same survey a Team plan would be a great fit but you can only have 1 primary admin, everyone else is a full user.
A team is made up of multiple SurveyMonkey accounts. Every person in the team gets their own username and password so they can control who can access surveys in their account with fine grain permissions. All accounts in the team are managed and paid for by the Primary Admin. This is the account that makes the upgrade, so if your account makes the upgrade this will become the Primary Admin. Each team starts with 3 users in total and you can add more users if you want to. 

With a team you can share surveys with people in or outside of your team and control the level of access (or permissions) people have to each section of the survey. As long as you own the survey you can share it with anyone in the team. Your surveys and data will remain intact - the only thing that changes is the added team functionality. The primary admin will be able to share the surveys from their account with everyone in the team.

Check out our guide for some more information regarding the Team Plans: https://help.surveymonkey.com/articles/en_US/kb/Teams 

For more information on the different team plans and pricing you can go to our Teams Plans & Pricing page.

If you have any other questions, I'd be more than happy to help.**

I think with this info we can move forward picking the correct plan. Are we ok with 1 admin and 2 users?

**Comment by chrisguindon** [comment]
> I think with this info we can move forward picking the correct plan. Are we ok with 1 admin and 2 users?

Thanks @rajivnathan,

+1 Advantage is what I was proposing. The admin should be @eclipsewebmaster since they need to manage the billing

**Comment by SharonCorbett** [comment]
@eclipsewebmaster:

Can you please proceed to set up the account for the MicroProfile Working Group.  

The Data Protection Impact Assessment (DPIA) can be created in parallel.

Thanks, 
Sharon

**Comment by eclipsewebmaster** [comment]
Ok I've created the primary account, and a couple of sub-accounts(one for creating surveys, and one with 'read only' access) for the team to use.

Can the WG team work with Sharon to determine who should have access initially(and to what) and then let me know(via email preferably) and I'll send out the details.

-M.

**Comment by aeiras** [comment]
Thank you, Sharon & Chris. 

Admin access to 
Ryan and Edwin. I will send you a private email Chris with them in the CC'd (private emails sharing)

**Comment by ederks85** [comment]
Hi Amelia, Chris,

I have received the credentials for SM, but I'm unable to log in since they seem to be incorrect.

**Comment by aeiras** [comment]
Hola @eclipsewebmaster, 

Can you please help us find the issues @ederks85 mentions? 
Gracias Edwin for the follow up! :)

**Comment by rstjames** [comment]
Hi @aeiras , @chrisguindon ,

I have received also the credentials for SM, but I'm unable to log in too. 

R

**Comment by chrisguindon** [comment]
> Hi @aeiras , @chrisguindon ,
> 
> I have received also the credentials for SM, but I'm unable to log in too.
> 
> R

@eclipsewebmaster can you help please?

**Comment by eclipsewebmaster** [comment]
Is this still a problem?  Edwin emailed me a few days ago saying he'd managed to login(after some confusion on my part about what SM was actually expecting in terms of login credentials).  

The bigger issue is going to be SMs limiting the number of people('devices') accessing an account in order to drive more license purchases(I suspect).  Right now they do that verification by sending an email to the registered address for an account.  For the initial setup I"m willing to forward those codes to Edwin and Ryan, but if the WG ends up with more people that want access that isn't going to scale.

**Comment by aeiras** [comment]
Hi team, 

for the time being, there won’t be the need to add any more Admins to the account. Please do send via private means (either use current private thread) or a new one, your call to share the codes.  When sending, please make it explicit to Edwin & Ryan that only 1 machine ought to be used. 

Thank you 🙏

**Comment by ederks85** [comment]
FYI I was able to login after having received the verification code

**Comment by aeiras** [comment]
That is wonderful Edwin. how about you, @rstjames?

**Comment by aeiras** [comment]
Hola @chrisguindon and @eclipsewebmaster

What is the public email & password that will give access to anyone who wishes to gain access to past Surveys results? 

https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1069147464

The MP Infra access spreadsheet is updated yet missing that information. Thank you so much, Team!

**Comment by chrisguindon** [comment]
Hi @aeiras,

I am not involved with account creations. I can't really help you with these types of requests!

**Comment by aeiras** [comment]
Hey Chris, 

on August 30th, Tetiana wrote 2 request:
 2) 1 view account to track the results (e.g. survey-view-microprofile@)

Can you provide that? 
It is part of what we wish to have with MP SurveyMonkey. 

Thank you for the follow up and enabling us to understand the current set up,

**Comment by SharonCorbett** [comment]
@eclipsewebmaster needs to provide assistance.  Not Chris.

Webmaster:  Can you help?

Thanks,
Sharon

**Comment by eclipsewebmaster** [comment]
So I need to reiterate that 'our'(MPWG) use of SurveyMonkey doesn't really fit with how SurveyMonkey expects to be used.

I'm not willing to publish these credentials publicly(for reasons I hope are obvious), but I've sent the details to @aeiras(and updated the email alias), who can then share them as needed with interested MPWG parties.  Webmaster can act as a backstop if needed.

**Comment by caitmm43** [comment]
Determined to close this ticket during 11/22 Mktg Call
