### ISSUE TITLE
Create documentation for contributor 'triage user' setup

### ISSUE THREAD

**Issue by edbratt** [microprofile/microprofile-marketing#569]
Please create a doc. that describes 'Contributor' configuration and setup to enable GitHub 'Triage' user access for project repositories.

**Comment by edbratt** [comment]
Draft doc. is created and available for review in Google Doc ['Drafts' folder](https://drive.google.com/drive/u/0/folders/13qmKV0inSuxX3uhzpD_mbLKtmgmHI2e4). Direct link is [here](https://docs.google.com/document/d/1EV0CKYfIAes-nosft-NYXsPtz0VkPRNssuibYspEYYY/edit#).

**Comment by aeiras** [comment]
Ed, 

Great draft. Super fun stuff! 

I inserted data from Chris exchanges, + links. 
Adjusted a few things and expanded more data. No screen shots added, your amount of detail suffices. :) 

Please look at it, I use "suggested mode". 
Via this ticket, you can pull me back in if further review is needed. 

Home of the document once review is finalized: https://github.com/microprofile/microprofile-wg/wiki

You have write access to the MPWG repo.  You can create the page, in my view there no need for a PR(your call)
 
The page will also need to be linked to the "Become a MicroProfiler" documentation located in the website under Contributors tab call to action https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING.adoc . 

Suggested location for the new Page ought to be after "Become a Member of the MP google group and participate in the discussion..."

A PR is needed to update the CONTRIBUTING.adoc, which means a new git issue to trigger prompt review and merge. : )

**Comment by edbratt** [comment]
Please see https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-%E2%80%9CTriage%E2%80%9D-access

**Comment by aeiras** [comment]
Wow, @edbratt-- it looks wonderful! 

Thank you so much for being awesome at piloting this feature. 
Tmw, we can distribute it to the Community forum alongside the tickets & in parallel add the MicroProfilers listed in the spreadsheet. 

I really appreciate your time and support on this, so exciting!
