### ISSUE TITLE
Add MP YouTube to website under Resources Tab 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#57]
[MP youtube](https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w)

**Comment by rstjames** [comment]
@aeiras do you mean on the resource page or a sub dropdown top menu?
Sadly its only meeting videos. Would be more interesting if it was a lot of conference sessions...

**Comment by aeiras** [comment]
Ryan, this is going to be part of the product page linking the minute videos from the +8 projects directly there. Lets add it as a new feature on the [MP.io skelleton_document](https://docs.google.com/document/d/1Ga7Z1aVgq4EcE19mSg5Ig9zugg3xqlXOkZnqsheX61o/edit). 

We won't start work on MP.io just yet.
