### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by tuxtor** [microprofile/microprofile-marketing#570]
First and Last name: Víctor Orozco
Preferred email: vorozco [ at ] nabenik [ dot ] com

Motivation:

This semester I've been preparing  a series of videos covering all MP APIs **in spanish** using many  MicroProfile implementations. These videos are available at the following playlist:

https://www.youtube.com/watch?v=-AUmo75Jdh4&list=PL4fXIf4GRmkX_WJOssmyTEjh4NcdLmfre&ab_channel=V%C3%ADctorOrozco

I would like to share this contend in a cross playlist on Youtube and/or blog post in MicroProfile site, hence according to this 
https://github.com/microprofile/wpsite I'm requesting to become a WP contributre to create a draft.

**Comment by aeiras** [comment]
Hola Victor, 

Your WP access is sent. Welcome to MP WordPress contributing! :) 
You can do both, introduce the videos via a blog (either crossposted or original content) & add each video under MP Community Playlist (using a single git ticket for each video) to enable its import. 

Thank you for rocking and lowering the bar to use & adopt the MP technology in Espanish. Amazing work and focus, Victor!

**Comment by tuxtor** [comment]
Thank you @aeiras, I confirm my access and I've worked in a blog post that I'm submitting in another issue. In the meantime I'm closing this bug.
