### ISSUE TITLE
Post review request Videotutoriales: Recorriendo MicroProfile en español

### ISSUE THREAD

**Issue by tuxtor** [microprofile/microprofile-marketing#573]
I've submitted a post **in spanish** available on preview at

https://microprofile.io/?p=6888&preview=true

This post consolidates a videotutorial series that I've elaborated demonstrating all MicroProfile APIs with diverse implementations.

**Comment by aeiras** [comment]
Qué impresionante eres Victor¡ :) 13 videos de MP!

Ok, I have reviewed the blog and it is a fantastic document. We could publish it, do check the adjustments I made as follows:

1)  Added the 13 number to quantify the videos. Being explicit is important as you as the author ask and depend on readers to consume the content. 

2) You need to update your MPwordpress bio with picture and short profile. As it is, we cannot publish your content without such information. 

3) Added your name and linked it to your "bio" website where you can be socially traced. 


I have a few recommendations for you as follows:

1. How about introducing yourself before you introduce MicroProfile?  Can you answer Why did you choose to invest your time on creating MP videos?

I think you are the most important thing in the blog, your care shows. Allowing a window for those who have yet to know you via this very blog is important.  You are simple and that works great.

2. Submit via this ticket a twitter description of your blog, please. 
Your blog will be scheduled (twice per month)  to be pushed by MP Hootsuite media, reaching FB, Twitter & Lknd audiences.      
Your blog will be proactively pushed in all MP channels as other e-books, tutorials, etc. (years)  :) 

 After we are done with the publication of your blog, we can tackle the video import as well. Today, I updated our community about your contributions during the community call.  I think MP is better b/c of MicroProfilers like you. Such a formadible #ossDOER and #usualsuspects. Abrazos, Victor!

**Comment by tuxtor** [comment]
Hi @aeiras thank you for the feedback:

1. As suggested I've added a foreword explaining the videos motivation and introducing myself
2. I've updated my bio, urls and picture in wordpress
3. Twitter description (in spanish as the videos)

¿Estas iniciando una aplicación con microservicios y Java? ¿Sabes que es MicroProfile? En estos videotutoriales exploramos el camino Cloud Native con Java y MicroProfile a través de sus diversas implementaciones

**Comment by aeiras** [comment]
Victor, 

Thank you for being amazing!  Your post is now live, yeayy! 

https://microprofile.io/2021/09/01/videotutoriales-recorriendo-microprofile-en-espanol/  

On its final review, I added the Youtube playlist of the MP videos as well under 13 videos & editor's note to link this git issue to the blog. Your work is done on blog stuff.  Thank you!  

MP consecutive yearly media messages [spreadsheet](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0) now includes your video blog. 

Now, you decided to embed the videos into the blog so they can be watched in the blog directly without leaving the space and also watch it in Youtube. 
@tuxtor how about submitting a new git issue with the " Contributing to MP youtube Community playlist" and add 1 video link in the description.  We have never before imported into Youtube a community video. 
 If you are up for it to pilot it with us, @jclingan and others will try figuring out whats what. :)  

I think crossposting it to your youtube works great. If MP could also add them as its content, your video could have 2 houses.   the bad thing about 2 houses is that you won't be able to track the metrics and stats as easily. 
Your choice, Victor.  


**Now social media push fun:**
@rstjames, 

Can you please help us schedule by Friday via MP hootsuite's Victor's video blog as follows? 
Thank you in advance for your insight on things we might not see while tackling the scaling of the video blog.  

-  **Twitter description**
_¿Estas iniciando una aplicación con microservicios y #Java? ¿Sabes que es MicroProfile? En estos videotutoriales @tuxtor te ayuda a explorar el camino #CloudNative con Java y MicroProfile a través de sus diversas implementaciones. #OpenSource_  [blog/video link]

@rstjames lets create a short link that says "Recorriendo MicroProfile en Español" or similar 

**design card**

- if we can use what Victor has provided as a cute duke under the pandemic that would be very cute as it is part of the blog's time. 
- with MP branding as usual
- + Victor's picture
- video image of Video contribution is core, if VideoTutoriales is added in the card that is even better. 

**Media push Schedule**

- twice per month, wknd and work day. Please choose the 2 days and lets keep them as constant. 
- this 1st blog push goes until June 30th, 2022.  

Thanks Ryan from bringing stuff here so Victor is involved into providing the follow up feedback as you see it fit.

**Comment by aeiras** [comment]
> Hi @aeiras thank you for the feedback:
> 
> 1. As suggested I've added a foreword explaining the videos motivation and introducing myself
> 2. I've updated my bio, urls and picture in wordpress
> 3. Twitter description (in spanish as the videos)
> 
> ¿Estas iniciando una aplicación con microservicios y Java? ¿Sabes que es MicroProfile? En estos videotutoriales exploramos el camino Cloud Native con Java y MicroProfile a través de sus diversas implementaciones

@tuxtor how do you feel about sharing your very first and super important mp wordpress publication via the [MP community forum, Victor? ](https://groups.google.com/g/microprofile)
None is most equipped that you to announce such a huge and important undertaking and contribution to MicroProfile outreach than YOU. 👍

**Comment by rstjames** [comment]
All set and scheduled for the year. @tuxtor 

![microprofile-videotutoriales-recorriendo_microprofile en_espanol](https://user-images.githubusercontent.com/12132146/132529239-d825cead-b00d-4768-8c6e-344de626aeeb.png)

**Comment by aeiras** [comment]
Ryan, 

The card is so cute and suddle with the 2 little companions of Victor :) Love it!  Thank you,
