### ISSUE TITLE
Please upload MicroProfile Marketing Team recording from 2021-09-13

### ISSUE THREAD

**Issue by edbratt** [microprofile/microprofile-marketing#576]
The recording for the Marketing Team meeting, held earlier today should be in the Zoom cloud storage location. Please upload to YouTube and notify the WG members via the usual tools that this recording is available for playback.
Thank you!

**Comment by aeiras** [comment]
https://twitter.com/jclingan/status/1437580688165785600?s=20 
thank you John! :)
