### ISSUE TITLE
[Website] Create a web page to store Compatible Implementations

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#577]
We need to design a webpage to store compatible implementations for MicroProfile releases from MP 4.1 onwards. [Here](https://jakarta.ee/compatibility/) is the Jakarta compatible implementation page for our reference.

**Comment by aeiras** [comment]
MP needs to design a Spec and compatible implementation page. 
First we need to draw from the work we completed on the Jakarta side and drop the stuff we found not valuable from UX feedback. 

We will discuss this task in the next Marketing call. :)

**Comment by aeiras** [comment]
not applicable.

**Comment by Emily-Jiang** [comment]
This is still valid. We still need a page to store the compatible implementations that MP accepts.

**Comment by aeiras** [comment]
Hey Emily, 

The reason why I chose to close this ticket is b/c it is link to the base of https://github.com/microprofile/microprofile-wg/issues/107

MP website will need to create in Q1 2022 an Implementation plage and shape it on Community driven compatibility branding concept. 

The community driven will focus solely on Implementations of MP, all of them. 
It is not about MP accepting compatibility products. 

B/c this ticket centers around regular Trademark Product Compatibility, it is closed. 

Let me know if this follow up is helpful to close this ticket.  and thanks for the wonderful follow up that enables this reply.

**Comment by Emily-Jiang** [comment]
@aeiras when I opened this ticket, I did not treat it part of EF trademark programme. We ought to create a compatibility page no matter whether it is part of trademark programme or not.

**Comment by aeiras** [comment]
Gotcha. Then, the ticket is applicable to Q1 2022 website work, Emily. Thanks for clarifying it. 

Implementations = MPWG Releases page

A draft document needs to be created in January to set the requirements about what that page "must" have, optional "nice" have & + more. 
If you wish to volunteer and start the page requirements (via a public editable google doc and insert it here), that would be great Emily. If you do, please remember to use the Community drive space or website folder for the housing the document. 

Bare minimums:
I see a page within a page with multiple options
--- list all implementations available for MP releases since first release
--- add MP 5. release & implementation (s) 
--- add community compatible logo 
--- add the annoucement blog written on releases (double post within MP website)
etc. 

Brainstorming fun!

**Comment by caitmm43** [comment]
@aeiras @Emily-Jiang 

Hi Emily, Amelia,

Is there any update on this ticket now that we've reached Q1?  What is needed next?  Please add your comments here and update the minutes accordingly.  Thank you! :)

**Comment by Emily-Jiang** [comment]
We need to create this page asap.

**Comment by aeiras** [comment]
@rstjames, 

What is your take on the creation of a landing new Compatible Implementation page that during the short term can be adjusted by humans yet in the long term, we will add PRs?

Today, I have updated the Website document https://docs.google.com/document/d/1Ga7Z1aVgq4EcE19mSg5Ig9zugg3xqlXOkZnqsheX61o/edit#

Please lets use the document to enable brainstorming before new git issues are created to mark the work for the page. 

----
Copy/paste my brainstorming on the crude draft on website logistics 
New Website Pages
Compatible Implementations - Short term (needs a human, no PRs)
Why a short term solution?
MP 5.0 release is out and there are 2 products that are compatible with MP 5.0. 
 The website Projects page is going to be decommissioned and brought back via PRs. Once that work starts, this page can be added to that dynamic . 

Git issue  [General] Create a webpage to store Compatible Implementations #577
Deadline:  sometime in February

Features by ORDER 
Must to have features
Lists MP releases as a unique page for each release
Adds the Repository to that release
Project products by all organizations ( not only members of the MPWG) get listed
Links of those products are live
Nice to have features 
Each release page has the blog announcement linked to it
Adds organizations blogs about the release as an Announcement news feed that crossposts those releases to the pages. 
Example
The work we have done on the creation of the Jakarta Compatible pages via PRs can be put into a temporary nice page for MP compatible  https://jakarta.ee/compatibility/ page 


@Emily-Jiang as mentioned yesterday, you and anyone else, is most welcomed to help with brainstorming on this task via that document and this ticket.

**Comment by Emily-Jiang** [comment]
We also need to create a compatibility logo to be displayed on this page. I have raised an issue [here](https://github.com/eclipse/microprofile-marketing/issues/646).

**Comment by Emily-Jiang** [comment]
For the first version, we list the releases 4.1, 5.0. When clicking on the release, it will go to another page containing all of the compatible implementation logos.

**Comment by mdagit** [comment]
Speaking as a technical user of these standards and products, I wouldn't consider
https://jakarta.ee/compatibility to be a good reference point -- that looks nice visually but carries little useful information.

As for https://wiki.eclipse.org/MicroProfile/Implementation my complaints about it
would be:
- "Progress" versus "Pending"? Huh? Why have either of these, let alone both?
- All links to a standard should go to a page that lets me actually download the spec **of that version**. It is astonishingly hard to actually find spec documents right now.
- Some visual separator or other indication distinguishing MP standards vs Jakarta standards would be nice
- I have a memory that this page or one like it used to indicate the JDK versions that pass the TCK. That is quite useful.
- If a link label has product and version than that link better go to a page that actually lists that version
- I've got no idea how the eclipse site is managed but i would think that the page could be generated from an underlying table in some format that approved vendor representatives have access to or at least can do PR's against.
- Then the page itself might get interactive so you can find a product by standard and standard version, or you could pick a product and product version and see what standards it has (go in either direction).
- Top of the page can list links to each implementation project's home page (with a small logo), for convenience.
- Would be nice to have a separate page that just itemizes the various standards and for each gives the highlights of what are added in each recent version. Digging through blog articles for this information is ad hoc and frustrating.

**Comment by aeiras** [comment]
Hola Mark, @mdagit 

Thank you for choosing to contribute via this issue. Your feedback is fantastic. 

Can you please insert all your feedback in the working document? https://docs.google.com/document/d/1Ga7Z1aVgq4EcE19mSg5Ig9zugg3xqlXOkZnqsheX61o/edit#
That action will keep the document fluid so that when new tickets for the creation start, they can be discussed and tracked using the document as the source of truth for potential stuff. 

MicroProfilers created the MP website when the project was founded outside any foundation. 
The website continues to be maintained 100% by MicroProfilers, not the EF team. 
MP is a member of the working groups, WG,  of the EF, yet not all WG projects choose to buy the EF website services. 

Therefore, your feedback is most valuable and welcomed. It is wonderful to meet you virtually. Thank you for caring to introduce yourself via your write-up insight. 

PS: the project page will be re-done this year as well, it fits many of your points as well.

**Comment by aeiras** [comment]
Mark, your feedback has been integrated in the outline. A few items made it to MUST. :)

**Comment by Emily-Jiang** [comment]
@rstjames further to our discussion on this week's marketing call, I went to read the above doc created by @aeiras which captures the feedback from @mdagit . In summary, on the top of what we discussed on the call, on the page of 4.1 and 5.0, we should have the following information as well:

- Lists MP releases as a unique page for each release
- Adds the Repository to that release
- Project products by all organizations ( not only members of the MPWG) get listed
- Links to those products are live
- All links to a standard should go to a page that lets me actually download the spec of that version. It is astonishingly hard to actually find spec documents right now.
- indicate the JDK versions that pass the TCK. That is quite useful.
- Then the page itself might get interactive so you can find a product by standard and standard version, or you could pick a product and product version and see what standards it has (go in either direction).

I can work with you to provide feedback on your mock @rstjames.

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/677

**Comment by rstjames** [comment]
Emily and I are outlining the content for this page. Please take a look and leave comments. We can talk about it on the next marketing call https://docs.google.com/document/d/1MVYC6LB6D-1LkHYlJMcK3A2o7n4NFV3BU9-x8D7oYjk/edit#

**Comment by aeiras** [comment]
to enable review, please move the document to the MP website folder before Monday. Thanks Ryan!

Reminder, no document on MP ought to be housed under private drives. 

<img width="904" alt="image" src="https://user-images.githubusercontent.com/10731224/162264341-7be39be5-ebf0-482b-83b9-826cbe5c6aa9.png">

**Comment by aeiras** [comment]
Thank you, @rstjames for the export to the drive. 
Review sent via suggestive mode. 

The document is the very basis of the 4.1 test page. 5.0 is not applicable just yet.

**Comment by aeiras** [comment]
@rstjames, 

The review on past releases outside MPWG is complete. 
The other item is also completed with feedback. :) 

Thank you for a great call today! Looking forward to Friday.

**Comment by aeiras** [comment]
https://docs.google.com/document/d/1MVYC6LB6D-1LkHYlJMcK3A2o7n4NFV3BU9-x8D7oYjk/edit#heading=h.qvd7hg5in1c7

**Comment by rstjames** [comment]
Today @Emily-Jiang  and I met again to review all information that would go on the Compatible Implementations pages. 
All content was added for: 

- Compatible Implementations home page https://microprofile.io/compatible-implementations/
- Compatible Implementations 5.0 https://microprofile.io/compatible-implementations/5-1/
- Compatible Implementations 4,1 https://microprofile.io/compatible-implementations/4-1/

These new pages were added to the top of the MP site menu. 

Next steps: 

-  add "version release translations" 
- "Related content section" on each Compatible Implementations version pages

**Comment by aeiras** [comment]
@rstjames 

![36DCD18B-D894-4E04-ADAC-530E63B6A001](https://user-images.githubusercontent.com/10731224/167936055-7f90c680-61e9-4f76-b5e8-cab4cd91ea42.png)

small devices needs tackling 💛

**Comment by aeiras** [comment]
@rstjames, 

Language translations can be found under: https://microprofile.io/category/releases/. posts 
It seems we don't have a category for it, and maybe we need something scalable like that to help feed it. 
Ideally, the Announcement Blog goes beside the English bottom.  Let's think of a way to scale it.

**Comment by aeiras** [comment]
@Emily-Jiang, in order to add the implementation blog feed to each Release page, we need the crosposting of those blogs into MP blog. 
Can you help import the IBM blogs for 4.1 & 5 and attribute authoring to the writers via WordPress?  Thank you. 
This part is super important. With your help, we can show how nice it is to have that information on the page and make it easier to emulate. 

Gracias, MicroProfiler.

**Comment by rstjames** [comment]
@aeiras mobile responsive table formating is fixed

**Comment by aeiras** [comment]
> @aeiras mobile responsive table formating is fixed

it looks fantastic @rstjames. Great job with Andrii.:)

**Comment by aeiras** [comment]
Nicely discussed and presented during today's MP Community call. 
Incoming feedback will be received fluid via new git tickets :) 

👍
