### ISSUE TITLE
MicroProfile talk at JAX 2019

### ISSUE THREAD

**Issue by javahippie** [microprofile/microprofile-marketing#58]
Conference Name: JAX 2019

Conference website and social media links:

https://jax.de/
https://twitter.com/jaxcon

Talks Links
https://jax.de/serverside-enterprise-java/eclipse-microprofile-vs-spring-boot-getting-back-in-the-ring/

Session Name: Eclipse MicroProfile vs. Spring Boot: getting back in the Ring!
Date and hour: Thursday, May 9th. 2019 (10:00 am - 11:00 am)

Speaker name: Tim Zöller
Speaker twitter handle: @javahippie

Description
After many years of arguments debating the differences between Spring and JEE, it seemed that the Spring Framework finally came out on top. With the rise of cloud environments and microservices, application servers had nothing to offer against Spring Boot.

In 2016, the Eclipse foundation presented a new contender: MicroProfile. This approach for Cloud-Native Java, based on the proven Java EE technology, was advanced with an ambitious roadmap to catch up on Spring Boot. Time for a closer look: How do both compare? We are exploring similarities and differences in development, configuration, and operations and take a look at how well the MicroProfile project prepared enterprise Java for the cloud.

**Comment by rstjames** [comment]
@javahippie 
Hi Tim,
Can you please provided a tweet message for your session. After I receive this I will create an image( share it in this ticket) and will schedule 2 tweets before your session date.
Thank you
Ryan

**Comment by javahippie** [comment]
Hi Ryan, thank you for your answer!

My proposal (not a native speaker, happy about any corrections):
Visit @javahippie at @jaxcon to discover similarities and differences between @MicroProfileIO and @springboot in development, configuration, and operations. The session will start on May 9th at 10:00 am https://jax.de/serverside-enterprise-java/eclipse-microprofile-vs-spring-boot-getting-back-in-the-ring/

**Comment by rstjames** [comment]
@javahippie All scheduled. 
![MicroProfile-JAX-TimZoller](https://user-images.githubusercontent.com/12132146/56286501-29cf3480-611a-11e9-95c3-0d2cf3da077c.png)

Feel free to close the ticket.

**Comment by javahippie** [comment]
Thank you very much!
