### ISSUE TITLE
[Tweet] Open Liberty 21.0.0.9 being the first compatible implementation for MicroProfile 4.1

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#580]
Congratulations @OpenLibertyIO 🏆 for being the #1 compatible implementation for @MicroProfileIO 4.1. The certification record is here https://github.com/microprofile/microprofile-wg/issues/97

**Comment by aeiras** [comment]
congratulations, Emily and team!

@rstjames, 
lets prioritize this media push (with design about Compatible Implementation) via hoosuite tmw! thank you for your help :)
Do correct me if I am wrong, we created the design a few months ago, correct?  
I don't see it here:

https://drive.google.com/drive/u/0/folders/1OJ3dmoe6vGxmtZbEt7cloLZ7If_zg4Sj

**Comment by Emily-Jiang** [comment]
Thank you @aeiras! @rstjames any progress with it?

**Comment by rstjames** [comment]
We didn't have a compatible template but a new working group template. But we now have the compatible template. I will update it on the drive when this ticket is complete. 

@aeiras @Emily-Jiang 
Here are two versions. Which one do you prefer? 

Tweet:
We are proud to announce the Newest MicroProfile Compatible Implementation for MicroProfile 4.1 @OpenLibertyIO. Check out the certification record here: https://github.com/microprofile/microprofile-wg/issues/97

#Opensource #Oss 

![microprofile-compatible-openliberty](https://user-images.githubusercontent.com/12132146/136073625-3c5174b5-5f85-469f-b554-929c006bde21.png)
![microprofile-compatible_implementation_openliberty](https://user-images.githubusercontent.com/12132146/136073633-47076a30-b55f-4215-aa01-d310a7070e2a.png)

**Comment by rstjames** [comment]
Sent out and will go out next month

**Comment by Emily-Jiang** [comment]
Thank you @rstjames ! Great job!

**Comment by aeiras** [comment]
Ryan, apologies never saw this until now, both designs are great! :)
