### ISSUE TITLE
[Documentation using SurveyMonkey] Data Protection Impact Assessment (DPIA)

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#581]
MPWG will store Personally Identifiable Information, PII, as discussed on the Sept 20th call. 
Goal: the document will describe what kinds of PII data MP will be collecting and for what purposes.

Requirements: 
1) MPWG must adhere to the Eclipse Foundation Hosted Services Privacy and Acceptable Usage Policy:
https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf
2) Admin users with (full access) will need to subscribe to eclipse.org-gdpr@eclipse.org and respond within 30 days to requests to delete accounts or make user data available to the specific user in question.

**Comment by aeiras** [comment]
@rstjames, 

On the 17th we discussed the draft for this document. Can you please deliver the crude draft as you chose to own that task during the call? thanks for any Q&A and for using the Documentations drive under Community drive to enable public access.

**Comment by ederks85** [comment]
How can I subscribe to eclipse.org-gdpr@eclipse.org? It seems not to be listed on https://accounts.eclipse.org/mailing-list. Is there a different way necessary to subscribe?

**Comment by rstjames** [comment]
@aeiras not sure what you are asking me. I don't remember saying I will document anything. Not sure what you want me to document. 

I have all images ready for voting. When we are ready to set up the survey please let me know and I will supply the most updated images of each logo.

**Comment by aeiras** [comment]
Hola @ederks85, 
I imagine that the steps are as follows based on past work.  Once you are fully set up in MP-sm, you will need to send a Bugzilla ticket (reference the working tickets here on that msg)  to the EF Infra for them to let give you access to that admin mailing list. 

@rstjames, Sept 20 MPWG call was ages ago. we should start writing tickets during the call to make sure stuff goes. Please check the minutes or listen to the recordings.  If you check the other ticket about SM, you will know that it is a simple 1 page document that says what is listed in the minutes of the call. 

I can look into its creation next week but would appreciate your help this week on it.

**Comment by rstjames** [comment]
@aeiras not sure I understand what you mean. I am only offering to help out with the images and setting up some structure in SM.

**Comment by aeiras** [comment]
Gotcha, Ryan.  
Thanks for clarifying your intent from that call, today, Ryan. 
I am ok to take over the documenting task and draft the 1-page DPIA to enable its review.  
You focusing on your magic-design work with MP - sm rocks!

**Comment by aeiras** [comment]
closed due to https://github.com/eclipse/microprofile-marketing/issues/593

**Comment by ederks85** [comment]
I need a +1 from MicroProfile PL on https://bugs.eclipse.org/bugs/show_bug.cgi?id=577288 to confirm that MP adheres to the DPIA policy

@aeiras do you know who is the PL (Project Lead?) for MicroProfile?

**Comment by ederks85** [comment]
@aeiras we need to finish the draft of the DPIA (I'll get to my comments there) into a final version

**Comment by aeiras** [comment]
Thank you Edwin @ederks85 for the 2 follow ups, you are amazing. 

First, MP doesn't use Project leads. There is none and that is by choice. 
There is no need for a PL. 
For the DPIA policy only the SurveyMonkey admins will have to comply with the DPIA. In this case 3 accounts equals to WebMaster (EF), you and Ryan. 

Second, I have scheduled to complete the DPIA draft this Monday and bring it back for Websmaster, you and Ryan to review before it is converted to a wiki under the MPWG repo. 

Questions, shoot! 


As it s

**Comment by ederks85** [comment]
@aeiras I have processed my outstanding comments in the DPIA document and edited the texts accordingly. Please let me know if I need to provide and edits

**Comment by aeiras** [comment]
Thank you, Edwin for enabling the wiki export of https://github.com/microprofile/microprofile-wg/wiki/Why,-When-and-How-to-Conduct-Surveys.

Please review and provide via Suggestive Edits feedback in the DPIA draft below:  @chrisguindon (@eclipsewebmaster)  @rstjames & @ederks85 


https://docs.google.com/document/d/11jRvFHLqRKjaek7e_mP_0ZugIeKqPDLL2i7vOl61XXE/edit#heading=h.bt99isvc6o7b 

@edwin and @ @rstjames

Please confirm you have submitted your request to be added to the eclipse.org-gdpr@eclipse.org by submitting a bugzilla issue https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Working%20Groups&component=MicroProfile

Please provide feedback by next Monday Nov. 29th. Doing so will enable the completion of the SurveyMonkey set-up by this month end. Thank you,

**Comment by ederks85** [comment]
@aeiras like this? https://bugs.eclipse.org/bugs/show_bug.cgi?id=577477

Why is this supposed to be mentioned in a bug? Is it part of an EF process?

**Comment by aeiras** [comment]
Correct, Edwin. 
We use the tool process the EF provides for such a request. Currently it is via bugs. 

for anything Security related, we need tracking and tracing to state what we are doing on our end to match the EF policies. 
For example, you subscribed to the mailing list and only you & the EF know will know when. When you post it via a bug, it is public view and it shows compliance within the WG. Extra steps but it relates to our care. 

Please let me know if this answers the why? happy to clarify further.

**Comment by chrisguindon** [comment]
I commented on https://bugs.eclipse.org/bugs/show_bug.cgi?id=577477

I think we can leverage the existing bug for tracking/tracing purposes related to MicroProfile adoption of our Hosted Services Privacy and Acceptable Usage Policy: https://bugs.eclipse.org/bugs/show_bug.cgi?id=577288

**Comment by aeiras** [comment]
+1 Chris. 
I forgot we had the other bug :) thank you for the simplification.

**Comment by ederks85** [comment]
Thanks @chrisguindon that makes more sense

**Comment by aeiras** [comment]
completed https://github.com/microprofile/microprofile-wg/wiki/MPWG-SurveyMoney-Data-Protection-Impact-Assessment-(DPIA)
