### ISSUE TITLE
[Ops] Implementing the 2021 MicroProfile Program Plan marketing initiatives

### ISSUE THREAD

**Issue by paulbuck** [microprofile/microprofile-marketing#582]
EMO and MP Marketing Team to prioritise and plan to leverage the remaining budget to implement 2021 MicroProfile Program Plan marketing initiatives.

**Comment by aeiras** [comment]
Hola Paul, 

The MP budget can take a surplus to 2022, correct? 

We are working under the assumption that a not-for-profit like the EF always does as it needs to carry over money to start the year & plan for emergencies, etc.  

Same goes for any project under the EF. Healthy and strong financial cadence.

**Comment by caitmm43** [comment]
Cross-posting @croundy 's reply in ticket #619: 
> "the 2021 budget will be fully allocated and will not carry over into the new year."

@aeiras Is any additional info or confirmation needed to resolve this ticket?

**Comment by caitmm43** [comment]
[https://www.eclipse.org/lists/microprofile-wg/msg01362.html](https://www.eclipse.org/lists/microprofile-wg/msg01362.html)
