### ISSUE TITLE
Collect the books, video and blogs related to MicroProfile

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#583]
We use this ticket to collect all of the books, videos and blogs related to MicroProfile and then work out how to publicise these properties with some paying SEO etc. Please add any books, blogs and video you value.

**Comment by Emily-Jiang** [comment]
Practical Cloud-Native Java Development with MicroProfile: 
_Develop and deploy scalable, resilient, and reactive cloud-native applications using MicroProfile 4.1_
amazon link [here](http://ibm.biz/MicroProfileBook)

**Comment by aeiras** [comment]
Thank you, beautiful Emily. 
For many years, MP social media has been used to highlight consecutive MicroProfile content. 
Those works are tracked:
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

Under the MPWG, we are considering adding a budget to the social media push of content to increase the bandwidth of those already in the schedule + new or missing works. 
This also includes "paid" works that include MP books we purchase, paid workshops, etc. 

Submitting via new git tickets that content is a call to action ongoing for years and a constant in mp social media https://twitter.com/MicroProfileIO/status/1439597695337893905?s=20

Super fun stuff!

**Comment by aeiras** [comment]
> Practical Cloud-Native Java Development with MicroProfile: _Develop and deploy scalable, resilient, and reactive cloud-native applications using MicroProfile 4.1_ amazon link [here](http://ibm.biz/MicroProfileBook)

So excited about your book, Emily, @Emily-Jiang 
How about you create a new ticket and follow the standards of publications? There is no need to wait until budget is allocated to social media content. It can be added under Yearly content schedule. 
Recommendation:

- create a short blog in MP to introduce your book and yourself
- add the why you care as Victor' did https://microprofile.io/2021/09/01/videotutoriales-recorriendo-microprofile-en-espanol/ under "Porque estos tutoriales" "Why these videos" section. If you use translate, you could see that that section is the most important in the sharing, as it focus on you and why you contribute with the creation of the book. 
**Or**

- write a tweet description of your book to enable that review & link of your amazon and done. :) 

Up to you, questions, shot via that new git ticket!

**Comment by caitmm43** [comment]
Hello @Emily-Jiang and @aeiras, I'm doing some ticket cleanup.  It seems there is no outstanding action to be taken.  If there is, please assign the relevant tasks and individuals.  Otherwise, please confirm that this ticket can be closed.  Thank you! : )

**Comment by aeiras** [comment]
correct @caitmm43 - thank you for the care on tracking inventory! :) Your Steward actions rock! 

https://twitter.com/MicroProfileIO (before Q3 Hootsuite purchase)
Hootsuite is pushing content submitted via tickets + monthly reminders about it. :)
