### ISSUE TITLE
[CONSOLIDATED] Survey Monkey voting process on MP Compatible Logo

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#585]
Here are the tasks related to using survey monkey to vote on MP Compatible Logo.

- [x] https://github.com/eclipse/microprofile-marketing/issues/581
- [x] https://github.com/eclipse/microprofile-marketing/issues/568
- [x] https://github.com/eclipse/microprofile-marketing/issues/557
- [x] https://github.com/eclipse/microprofile-marketing/issues/556
- [x] https://github.com/eclipse/microprofile-marketing/issues/591
- [x] https://github.com/eclipse/microprofile-marketing/issues/593

**Comment by aeiras** [comment]
You are amazing 💪🏼🥋🌟

**Comment by aeiras** [comment]
hola @ederks85, 
When you get the time, can you look/review Trackers 557 ticket? 
 I will convert the document to a wiki next week, ideally you could provide 'suggestive feedback' directly in the document or do so via PR at a later time. It is important that you get to the document before this month ends. 
The MP-sm account will be active and hopefully ready for your use in Nov, yet you cannot use it without agreeing to the Operational Process. For Q&A please use that ticket! 

Cheers

**Comment by ederks85** [comment]
@aeiras I have suggested my thoughts in the document

**Comment by aeiras** [comment]
Excellent follow up, Edwin. Wiki has been exported which leads to the completion of the DPIA draft awaiting Admins feedback. Gracias!

**Comment by aeiras** [comment]
completed with https://github.com/microprofile/microprofile-wg/wiki/MPWG-SurveyMoney-Data-Protection-Impact-Assessment-(DPIA)
