### ISSUE TITLE
[CONSOLIDATED] Website Updates Needed

### ISSUE THREAD

**Issue by ghost** [microprofile/microprofile-marketing#587]
- [ ] https://github.com/eclipse/microprofile-marketing/issues/565 -FAQ section of website hasn’t been updated in years. Debbie created a draft here. Please review, comment, edit.
- [ ] https://github.com/eclipse/microprofile-marketing/issues/577 -design a webpage to store compatible implementations for MicroProfile releases from MP 4.1 onwards
- [ ] https://github.com/eclipse/microprofile-marketing/issues/529 - duplicate of 577?

**Comment by aeiras** [comment]
correct, ticket 577 is a duplicate of 529.

**Comment by aeiras** [comment]
Only 1 ticket reminds, and it will be worked independently . 
Update FAQs for Microprofile.io and Wiki #565 
Again Debbie the grouping of the tasks is amazing with the checklist. You are incredible!
