### ISSUE TITLE
[GraphQL] Please setup Zoom call / calendar for MP GraphQL

### ISSUE THREAD

**Issue by andymc12** [microprofile/microprofile-marketing#590]
Opening this issue per instructions at https://docs.google.com/document/d/1xTBnhJ2SjDmLjM6OTyRVjSnjb6r5s8_opGjSyZnD5vA/edit#

The MP GraphQL project meets the first Wednesday of every month at 9:30am US Central Time. Currently we use BlueJeans (or Webex as a backup), but we would like to start using Zoom for consistency with other projects.

@Emily-Jiang can you set up the calendar and provide @phillip-kruger and me with hosting abilities?f

Thanks!

**Comment by aeiras** [comment]
Hola @andymc12, 

Thank you for being awesome at this follow up! 
Pull me in on Oct 22nd, via this ticket, if you are still missing the Zoom Admin code. Emily should get the 2 of you the code via private email before then. :)  

Call 2 Action review:
Can you please review & approve, cut, adjust the media message that will be scheduled for the rest of 2021 below? Gracias 

_Join today's #MicroProfileGraphQLCall to discuss the technical issues & contribute to the project goals. 
#MicroProfilers' participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. 
https://bit.ly/calendar-zoom-minutes

#Community4OSS_

--- 
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0  is updated and old ticket is 415 is closed. 

@rstjames please help us update the monthly social media pushes for GrapgQL. Start date November. Thank you!

**Comment by Emily-Jiang** [comment]
@andymc12 I have created the monthly meetings for you and updated the entries on MP calendar. Please check to see whether it is correct. I'll tell you the host code through a private channel and then you share the code with @phillip-kruger.

**Comment by aeiras** [comment]
@rstjames, 

Do you have the bandwith to help schedule the API call? See my follow up on Oct 13th. 

Join today's #MicroProfileGraphQLCall to discuss the technical issues & contribute to the project goals.
#MicroProfilers' participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource ecosystem.
https://bit.ly/calendar-zoom-minutes

#Community4OSS_

**Comment by andymc12** [comment]
Hi @aeiras - sorry, I missed the second part of your post on Oct 13.  The Call 2 Action post looks good to me.  I verified that the calendar is correct (next meeting is on November 3 at 7:30am US Pacific Time), and Emily sent me the admin code for the Zoom call.  I think I'm all set, but if I run into any trouble at our next meeting I'll let you know.  Thanks so much!

**Comment by aeiras** [comment]
Hey snuggly you, 

Thank you for reviewing the baseline of the tweet!! Whoever you and the group desires to change it, just submit a new git issue with the word description and the MicroProfilers behind the scheduling will handle it. 

Ryan will help us close this ticket now that you have closed the missing parts! yeay!

**Comment by rstjames** [comment]
I scheduled the social reminder for the next two calls ( the rest of 2021 ) 
![microprofile-graphql-call](https://user-images.githubusercontent.com/12132146/139463376-c7710a17-5991-4826-8430-e0acceeb0807.png)
)

**Comment by andymc12** [comment]
Thanks Ryan!
