### ISSUE TITLE
[Social Media Push] Book release "Practicial Cloud-Native Java Development with MicroProfile"

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#592]
Very thrilled to announce a new book @MicroProfileIO  authored by our very own committers @emilyfhjiang @AndrewMcCright @nottycode @david_yk_chan and our consumer @jwalcorn! Get this book to learn #CloudNative #dev @MicroProfileIO @OpenLibertyIO ibm.biz/MicroProfileBook @PacktPub 

@rstjames can you do your usual awesome design for the tweet?

**Comment by aeiras** [comment]
Hola Emily, 
Way awesome congrats to everyone involved. 

Thank you for **reviewing** the re-write of the tweet below:
Our Community is thrilled to announce a new @MicroProfileIO book authored by our very own committers @emilyfhjiang @AndrewMcCright @NottyCode @david_yk_chan and their consumer @jwalcorn! 

Get this book to learn #CloudNative with @OpenLibertyIO: ibm.biz/MicroProfileBook @packtpub #OSS

**More work**
We also need to create a new tweet that is a **constant** in media rotation for at least 6 months. Can you draft something that lists the creators & contains the name of the book + anything core that defines the book effectively. 

Ideally, we push the book either 1 or twice per month (ryan will help with that part and recommend)  and check the value of the push and adjust.  I added the reference and tracking below.  
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

Once you do, this ticket will be re-assigned for processing¡ Cheers

**Comment by aeiras** [comment]
Oh and Emily, avoid tweet usage only. MP social media uses Hootsuite and it pushes content via that platform to 2 outlets, including Twitter :) 

1. Twitter
2. Facebook
3. LinkedIn
I adjusted the name of your ticket.

**Comment by Emily-Jiang** [comment]
Awesome, thank you @aeiras

**Comment by Emily-Jiang** [comment]
@aeiras 

> More work
> We also need to create a new tweet that is a constant in media rotation for at least 6 months. Can you draft something that lists the creators & contains the name of the book + anything core that defines the book effectively.

How about this: (can't add anything else because it has reached to the maximum characters)
Our Community is thrilled to announce a new book Practical Cloud-Native Java Application Developent with MicroProfile by our very own committers @emilyfhjiang @AndrewMcCright @NottyCode @david_yk_chan and MP consumer @jwalcorn!
Get this book ibm.biz/MicroProfileBook @packtpub #OSS

**Comment by aeiras** [comment]
so fast, love it! 

the continue messaging cannot be " introducing the book"

Example: 
Practical Cloud-Native #Java Application Development with #MicroProfile, a book by #IBMers @emilyfhjiang @AndrewMcCright @NottyCode @david_yk_chan & consumer @jwalcorn, builds cloud-native applications using @OpenLibertyIO @Docker @IstioMesh @kubernetesio! ibm.biz/MicroProfileBook

Goal, 
be noticed by any of the @ technologies that are listed in the tweet. 
increase followers by authors @
increase sales by awareness. etc

**Comment by rstjames** [comment]
![microprofile-Practical-Cloud-Native_book](https://user-images.githubusercontent.com/12132146/139689809-aafce087-dd33-4dbc-a101-4ceda428989e.png)

scheduled to go out once a month on all channels.

**Comment by aeiras** [comment]
Gracias, Ryan @ rstjames!
Thats a beautiful card. :) 

Can you please confirm that the message that is getting pushed monthly is and thank you:
Practical Cloud-Native #Java Application Development with #MicroProfile, a book by #IBMers @emilyfhjiang @AndrewMcCright @NottyCode @david_yk_chan & consumer @jwalcorn, builds cloud-native applications using @OpenLibertyIO @docker @IstioMesh @kubernetesio! ibm.biz/MicroProfileBook

Ryan, 
It is easy to miss given the exchanges with Emily. 
We also need a one off media push that highlights introducing the book with focus on its authors. The tweet is above, copy paste for you:

Our Community is thrilled to announce a new book Practical Cloud-Native Java Application Developent with MicroProfile by our very own committers @emilyfhjiang @AndrewMcCright @NottyCode @david_yk_chan and MP consumer @jwalcorn!
Get this book ibm.biz/MicroProfileBook @packtpub #OSS

Can that design image have the twitter pictures of the 5 authors? 

Reopening issue.

**Comment by rstjames** [comment]
<img width="422" alt="Screen Shot 2021-11-01 at 8 14 58 PM" src="https://user-images.githubusercontent.com/12132146/139728069-dd46f6b2-e1e2-4dc0-afd0-658a4ec2b720.png">
@aeiras

**Comment by rstjames** [comment]
Ok missed that there should be an initial post. 
It will go out tomorrow. 

Tweet:
Our Community is thrilled to announce a new book "Practical Cloud-Native Java Application Development with MicroProfile" by our very own committers @emilyfhjiang @AndrewMcCright @nottycode @david_yk_chan & MP consumer @jwalcorn!
Get this book ibm.biz/MicroProfileBook 

@PacktPub 
![microprofile-book-promo-1](https://user-images.githubusercontent.com/12132146/139730499-f4bd509e-62e5-4c3d-9df4-65365a2886ee.png)

**Comment by aeiras** [comment]
Ryan, super easy to miss, given the good exchanges. 
Thank you so much for confirming the regular consecutive tweet. That looks awesome and is already added under the constant inventory spreadsheet. :)

Tmw's tweet looks great to me. Yet only the authors could provide you with valuable feedback and critic!
