### ISSUE TITLE
[Swag 2021 Update]  MP Members Shirt Design to match the Charter & MPWG

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#594]
archiving of the current t-shirt needs to come into effect https://drive.google.com/drive/folders/0B7PK4ZIk1mjAT3hTWjJMM2lGYU0?resourcekey=0-6HJOanvfrcZB2uhDjjhf0A

**Front design**

- the same

back design recommended additions:

- Contributor
- Committer
- Guest

In addition can we consider adding below the Members also:

- Users
- IDEs
- Porting Tools
- Cloud Providers
- Testing Tools
- Monitoring Tools
- Frameworks 

What else is missing from making the MP technology awesome!

**Comment by rstjames** [comment]
@aeiras 
I think hoodies and shirts should be as simple and scalable as possible.

I suggest **NOT** having:

- Contributor
- Committer
- Guest
- Members 
      - not sure how you would add "Users, IDEs, Porting Tools, Cloud Providers, Testing Tools, Monitoring Tools, 
         Frameworks. It would be a mess.

Because these are always changing it will make a lot of the swag seem outdated. Not a "vintage" or "old school"

Logo on front and maybe tagline on back... something that talks about the community.

**Comment by aeiras** [comment]
@rstjames, 

Thank you for your follow-up.  About Members, you are right, it is hard to list EVERYONE. 

Can you create a mock up with current ORGs & add Contributor to the design?

Using this issue to enable feedback is always appreciated. If you can have an updated version of current shirt ready by next Monday call that would be amazing. Thank you,

**Comment by rstjames** [comment]
@aeiras 
- Please place a list of what exact logos need to be on it. After we may need to request official vector logos from the companies. 
- Front "should be the same design and t-shirt" does this hoody have a zipper?  If so it can not be the same design as the front of the shirts.

**Comment by rstjames** [comment]
Hi everyone.  @aeiras @Emily-Jiang and whoever else may be interested. 

Here are two options for the back of the shirts. The two differences are the bottom center logo. 
**Committers/or Contributors** Which one do you prefer? 

<img width="556" alt="Screen Shot 2021-11-11 at 12 56 22 PM" src="https://user-images.githubusercontent.com/12132146/141294302-e0c6d685-a0cf-455a-98d9-440bd1325dba.png">

<img width="558" alt="Screen Shot 2021-11-11 at 12 53 38 PM" src="https://user-images.githubusercontent.com/12132146/141294294-5ba657a1-6754-490a-bafc-59990cbf4ea8.png">

**Comment by ederks85** [comment]
Well, I like the "Contributers" version since we have contributions from both Committers and non-Committers

**Comment by aeiras** [comment]
I love 💜 Contributors choice! It is inclusive 💪🏼

Ryan, I also like the design of the font watermarks for both contributors & Committers. if there is a way to bring that to the website, that would be awesome. Beyond swag fun 🙏

**Comment by cesarhernandezgt** [comment]
+1 on having Contributors on both the Tshirt design and website, social media, etc..

**Comment by Emily-Jiang** [comment]
+1 on Contributors version. For the colour, can we have different colours such as dark, grey, etc?

**Comment by aeiras** [comment]
Hey Emily, 

The MP t-shirt is a 2 color print shirt by choice, simplicity. White and yellow. Exactly what the current t-shirt you wear is.

**Comment by Emily-Jiang** [comment]
> Hey Emily,
> 
> The MP t-shirt is a 2 color print shirt by choice, simplicity. White and yellow. Exactly what the current t-shirt you wear is.

@aeiras do you mean the logo color white and yellow. I think my current MP t-shirt is always kind of blue.

**Comment by aeiras** [comment]
Hey Emily, 

- [2021 - Shirt, pre MPWG mock up](https://drive.google.com/drive/u/0/folders/1LXgXYIYPSmUteMd0fA7lr9ZP9WE0U259) we will deprecate only the back design by updating the Members. 

- since day 1 of MP, the design, cut, and color continues to be the same:   “midnight-navy”   color [Style N6210
Next Level Unisex CVC Crewneck T-Shirt](https://www.threadsy.com/next-level-unisex-cvc-crewneck-t-shirt-n6210?msclkid=408cbbc7326713a0fd0eda499682aeae&utm_source=bing&utm_medium=cpc&utm_campaign=s_sea_b_nextlevel__nextlevel_multi_all_c-us_m_rev_bi_en_txt_dr_&utm_term=next%20level%20apparel%206210&utm_content=nextlevel_6210__multi_txt_nextlevel__)  

- [Hoody 2017 mock up](https://drive.google.com/drive/u/0/folders/1AmdyY5NE_2kzksO-x0Vw1aWmEWj29fBo)
- [Next Level style 9601, midnight navy/gray - French Terry Zip Hoody](https://www.shirtspace.com/next-level/sweatshirts/6577-next-level-9601-adult-french-terry-full-zip-hooded-sweatshirt?variant_id=232267&msclkid=649d5f1654101755d1953e98f2ee558d&utm_source=bing&utm_medium=cpc&utm_campaign=Shopping%20-%20Manufacturer&utm_term=4579672090795107&utm_content=next%20level)

For both designs, only the back will be updated with new members logos. All else ought to stay the same. 

I hope this is helpful!

**Comment by rstjames** [comment]
<img width="759" alt="mp-Back-shirt-2021" src="https://user-images.githubusercontent.com/12132146/143035631-f0c96f4f-4ca2-411e-bb79-5e37a61257f4.png">

**Comment by Emily-Jiang** [comment]
Looks good @rstjames !

**Comment by Emily-Jiang** [comment]
> Hey Emily,
> 
>     * [2021 - Shirt, pre MPWG mock up](https://drive.google.com/drive/u/0/folders/1LXgXYIYPSmUteMd0fA7lr9ZP9WE0U259) we will deprecate only the back design by updating the Members.
> 
>     * since day 1 of MP, the design, cut, and color continues to be the same:   “midnight-navy”   color [Style N6210
>       Next Level Unisex CVC Crewneck T-Shirt](https://www.threadsy.com/next-level-unisex-cvc-crewneck-t-shirt-n6210?msclkid=408cbbc7326713a0fd0eda499682aeae&utm_source=bing&utm_medium=cpc&utm_campaign=s_sea_b_nextlevel__nextlevel_multi_all_c-us_m_rev_bi_en_txt_dr_&utm_term=next%20level%20apparel%206210&utm_content=nextlevel_6210__multi_txt_nextlevel__)
> 
>     * [Hoody 2017 mock up](https://drive.google.com/drive/u/0/folders/1AmdyY5NE_2kzksO-x0Vw1aWmEWj29fBo)
> 
>     * [Next Level style 9601, midnight navy/gray - French Terry Zip Hoody](https://www.shirtspace.com/next-level/sweatshirts/6577-next-level-9601-adult-french-terry-full-zip-hooded-sweatshirt?variant_id=232267&msclkid=649d5f1654101755d1953e98f2ee558d&utm_source=bing&utm_medium=cpc&utm_campaign=Shopping%20-%20Manufacturer&utm_term=4579672090795107&utm_content=next%20level)
> 
> 
> For both designs, only the back will be updated with new members logos. All else ought to stay the same.
> 
Maybe we should revisit next year to see wheter we make some updates for the styles. Do we want to stay with the zip style? What about the non-zip style hoody? What about different colors?
> I hope this is helpful!

**Comment by aeiras** [comment]
+1 Emily on adding a lighter version of the apparel. 
Always improving stuff yet keeping it simpler and making it even more simple. 

About added wearable piece, maybe we can finally include a light loose sweater (ligh t grey) . Example like the one I was wearing today
![Image from iOS](https://user-images.githubusercontent.com/10731224/143112727-1dcbacec-ef41-47b0-9bf0-709807b5b4bd.jpg)
. 
MP has 4 colors as listed here: https://microprofile.io/resources/branding/#color-fonts

**Comment by Emily-Jiang** [comment]
@aeiras great idea with the lighter comfy sweater! I love the color as well, so 2 +1 from me.

**Comment by aeiras** [comment]
Thank you, @rstjames for the good work on the updating of the t-shirt!
[MP-shirt-Back-2021.pdf](https://github.com/eclipse/microprofile-marketing/files/7678285/MP-shirt-Back-2021.pdf)
[MP-shirt-Front-2021.pdf](https://github.com/eclipse/microprofile-marketing/files/7678286/MP-shirt-Front-2021.pdf)

**Comment by SharonCorbett** [comment]
Please note this matter is not yet closed.  

Cross Reference https://github.com/eclipse/microprofile-marketing/issues/633

Perhaps you can help @rstjames 

Thanks,
Sharon

cc @paulbuck
