### ISSUE TITLE
[Swag 2021 Update]  Regular t-shirt 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#595]
[hoody print data](https://drive.google.com/drive/folders/0B7PK4ZIk1mjAbjM3WjBPMUZTams?resourcekey=0-6dEV-Pk4kTqoOQN6-0wgUg)

linked to this design: https://github.com/eclipse/microprofile-marketing/issues/594

**Comment by aeiras** [comment]
Hey @rstjames, 

For reference I will attached the 2017 design mock up of the hoody in this ticket. you can find the original files in the drive.  What we are looking for is updating the members logo as described in the t-shirt ticket to match the MPWG Charter membership.  No change in the front design is needed. It has been a long time since we created this design, so hopefully this helps you bring something to us via this ticket by Friday. Thanks! 
![2019- MP Hoodie_Front_mockup](https://user-images.githubusercontent.com/10731224/141024485-7417f641-9e2e-428b-9fa4-c992dcfdcb88.jpg)



![2017- MP Hoodie_Black_Mockup](https://user-images.githubusercontent.com/10731224/141024494-4edca915-ff37-4f2e-948c-696abe22f053.jpg)

**Comment by rstjames** [comment]
Update new back image to match the design of the shirt on the drive. https://drive.google.com/drive/folders/0B7PK4ZIk1mjARnJnVUxtNi1nRlE?resourcekey=0-Jefu4sy1-fdIlG6Y3pWLtw

**Comment by aeiras** [comment]
Thank you, Ryan. 

Can you please create the t-shirt mock ups for the back of the t-shirt and the hoody ? 
https://drive.google.com/drive/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg

I went ahead and deprecated the old back versions on both items. Please use the old versions for measure. Avoid starting from zero. The actual mock ups work great as they are. 

Questions, shoot. Can you get this to the marketing mailing list by AM your Wednesday?

**Comment by rstjames** [comment]
@aeiras Both have been added to the correct google drive folders 
![mp-Back-hoodie-2021](https://user-images.githubusercontent.com/12132146/142941038-9e357ffb-f00f-43f6-8656-6d3ddec9d3c5.jpg)

<img width="599" alt="MP-_back_mockup" src="https://user-images.githubusercontent.com/12132146/142941069-3fc70e40-5e42-478a-8237-8d0598bcea87.png">

**Comment by aeiras** [comment]
Thanks Ryan for the super fast turnaround. 

Can you create a 2nd draft on the 2 mocks as follows and thank YOU! 

1. Shirt, 

- Re- add the yellow M and the twitter MP address on the top of the shirt (old version)
![Image from iOS](https://user-images.githubusercontent.com/10731224/142943663-cdfff2e5-3dc4-40e2-8a04-b2d2a6016fb7.jpg)

- Place By the Community, For the Community in the bottom of the shirt. 
- Instead of White letters, use yellow letters. 

2. Hoodie
![Image from iOS (1)](https://user-images.githubusercontent.com/10731224/142943988-e27fbd52-142d-4a92-ad2d-bd3464833879.jpg)

- Re- add the yellow MP on the lower right bottom 

- same feedback as the shirt.

**Comment by rstjames** [comment]
![Back-hoodie](https://user-images.githubusercontent.com/12132146/143034935-485800d2-6a8a-4e83-b044-34b30e489828.jpg)
updated on the drive

**Comment by aeiras** [comment]
@rstjames, 

Can you please this ticket to the marketing forum so that others who wish to provide feedback, can do it?

Thank you for the on time delivery before the holidays. you ROCK!

**Comment by myfear** [comment]
@rstjames @aeiras apologies for the late reply. Europe was sleeping. Please update the Red Hat Logo according to latest brand standards (https://www.redhat.com/en/about/brand/standards/logo). Reverse Pantone EPS attached. LMK if you need anything else. 
[Logo-RedHat-A-White-Pantone.eps.zip](https://github.com/eclipse/microprofile-marketing/files/7593005/Logo-RedHat-A-White-Pantone.eps.zip)

**Comment by aeiras** [comment]
Hola @myfear, 

Your timing is perfect. Thank you so much for helping with the review. You are wonderful. 

@@rstjames, thank you for your help on this. 
To dos:
1) update the swag
2) delete the old RH logo version under the RH logos drive folder and drop new zip under  as well. 
3) update the logo under the MPWG Members banner page. 

If anything else is missing, Markus, do let us know. Abrazos,

**Comment by rstjames** [comment]
@myfear @aeiras The RedHat logo has been updated and google drive has been updated with a new shirt mockup, .ai and pdf files
<img width="584" alt="microprofile-shirt-mockup-2021" src="https://user-images.githubusercontent.com/12132146/145235777-97083383-c7d8-44f1-af68-01b00a1f1b68.png">
<img width="608" alt="Screen Shot 2021-11-19 at 2 30 15 PM" src="https://user-images.githubusercontent.com/12132146/145235795-c9c902f6-b338-4a00-8401-1778cd7c9c82.png">

**Comment by myfear** [comment]
This looks great! Thank you, Ryan!

M

**Comment by aeiras** [comment]
beautiful work, Ryan. 
 
you are wonderful!

**Comment by aeiras** [comment]
@caitmm43, 

During yesterday's Mktg call, we discussed the EF's feedback. 
4 of us decided **for now drop** the Contributors' wording from the t-shirt until the MPWG decides to formally integrate a new logo for Committers and Contributors under its formal register marks. 

Today during the Community call, the plan was to discuss the requested adjustment  but Retrospective became a priority.
As you remember, you sent to 1,200 MicroProfilers the update email with the final design version.  Any changes that modify that design ought to follow Community call awareness to enable extra eyes on the WHY change it before the formal write up follow up.  

That means that @rstjames won't change the design until after Feb 1st Community call, if all others agree with the 4 of us on yesterday call.

**Comment by aeiras** [comment]
@rstjames, 

Pulling you back in to the 2021 design. 
We must remove the Contributors from the t-shirt, sadly. 

Can you please help us with the adjustment and update the hoody in the drive and all the files? 
ETA, end of this week. 

The EF won't allow the Vendor to print the current t-shirt until the adjustments have been completed. Thank you!

**Comment by rstjames** [comment]
All files have been updated on the google drive. 
https://drive.google.com/drive/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg&usp=sharing

**Comment by rstjames** [comment]
<img width="528" alt="microprofile-hoodie-back" src="https://user-images.githubusercontent.com/12132146/152525627-0066d3ba-2a66-4340-85d6-eb321f4d933d.png">
<img width="646" alt="Screen Shot 2022-02-04 at 12 54 32 PM" src="https://user-images.githubusercontent.com/12132146/152525656-d507bca2-9fbe-47e7-8256-b93a394322bb.png">

**Comment by aeiras** [comment]
Thanks Ryan for the time on this. 
Payara & Jelastic need to be in the shirt. Let’s insert them once again. This print if with the 2021 budget. 

Let’s place the designs you just provided in the 2022 folder. As the design is perfect for use of 2022 budget & membership.

**Comment by rstjames** [comment]
ALl updated on the drive. I left 2022 designs and made a 2021 folder with the latest requested updates

**Comment by caitmm43** [comment]
@rstjames - I'm getting back into the loop after stepping back from MP for 2 weeks.  It looks like there is some action pending in #633.  Previously, I was managing communication with Deluxe & community updates on the design.

With @aeiras away, could you catch me up to speed?  If the design is ready to print, I will update the community via google groups and confirm with Deluxe.  Let me know whether these are the appropriate next steps, or if other action is needed.

**Comment by paulbuck** [comment]
@rstjames any update on the revisions for the artwork for the shirts? I think we would all like to get er done!

**Comment by rstjames** [comment]
@paulbuck @caitmm43 I updated this ticket 13 days ago. Has something changed since the last updates?

**Comment by paulbuck** [comment]
@rstjames I see that now, apologies, ball appears to be in our court. Thanks for the speedy response.

**Comment by rstjames** [comment]
@paulbuck no problem please let me know if there is any adjustment needed or questions.

**Comment by caitmm43** [comment]
@rstjames Let's discuss this during the marketing call today to ensure things are moving forward as they should be.

**Comment by caitmm43** [comment]
#633:
> @shanda-eclipse We discussed this during our call today and confirmed that we are ready to print this order using the updated 2021 designs. Do you need any additional info from us in order to finalize this order with the printer?
