### ISSUE TITLE
[Swag 2021 Update] Implementations Shirt 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#596]
![image](https://user-images.githubusercontent.com/10731224/137405865-1bf2a061-87b0-42e7-bd13-4f2af5819b89.png)

Needs to integrate the Compatible logo into the design

Do we wish to print also a hoody of it?

**Comment by rstjames** [comment]
Think this is too much to have on a hoody. People want to represent it but don't want to walk around with 30 logos on it.

**Comment by aeiras** [comment]
@rstjames, 

I count 12 logos, where does your 30 logos comes from?

Can you please draft a t-shirt with the 12 logos as listed in the chart above?

**Comment by rstjames** [comment]
@aeiras How many shirts are we doing? I am getting confused. So far we have 3 separate tickets for shirts and hoodies.

**Comment by rstjames** [comment]
So we are having shirts only with these 12 logos on the image above? Not the logos on the past shirts? example no Tomirtirbe,  IBM... Let's hop on a call and go over the shirt and hoody to clear it all up.

**Comment by aeiras** [comment]
during the 11/08 mktg call, it was decided to keep MP wearable shirt to 1 design.
https://docs.google.com/document/d/1fQWUiCInhJni8WhGt2k5WKqb8K6BuhzzWTzqynvX3_U/edit#heading=h.un65ig1dgyws
