### ISSUE TITLE
[Swag - Vendor & EF]  Request the trusted MP Swag Vendor to be welcomed to the EF Suppliers

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#598]
https://docs.google.com/document/d/1f3pGnaySMlwGhi9-RsgjQPV2qzE_1lZ7Sf87-19YfSU/edit

https://deluxescreenprinting.net

Deluxe Team is formidable in every way. Tomitribe has tried many Vendors before we found it and never looked back. 

Deluxe has printed 90% of all MicroProfile tshirts wore globally. 

Vendor is:

- 100% on time with deadlines, no excuses. 
- errors in printing shirts, hoodies, etc are below 1%. For example with 300 shirts and maybe on rare times just 1 returning bad
- Women owned, minority, located in CA. 
- Vendor has printed 1000s of MP shirts. 
- Discounts available after 250 count as listed in the website 

-- 
This ticket needs to be submitted to Sharon or Paul via the MPWG forum to enable the request to start the onboarding process.

**Comment by aeiras** [comment]
request submitted https://www.eclipse.org/lists/microprofile-wg/msg00988.html

**Comment by HailleySeed** [comment]
Hi @aeiras. We are looking to place the order for the Microprofile Committers. I would just like to confrim the quantity of t-shirts, hoodies and stickers you would like to have.

As well for shipping, are they being sent out individually or will they all be shipped to 1 location with someone else being in charge or distributing them?

Can you please also confirm your budget for this?  

Thanks in advance,
Hailley Seed

**Comment by aeiras** [comment]
Good morning Hailley, @HailleySeed!

Thank you so much for agreeing to add Deluxe to the EF Swag vendors, we appreciate it. 

Our community is in the process of updating the wearable swag designs and figuring out how much to order (which includes many JUGs that will take care of the swag distribution).   https://github.com/eclipse/microprofile-marketing/issues/597

We will pull you in as soon as we have those 2 tasks completed.

**Comment by croundy** [comment]
@HailleySeed  Please work with @aeiras and team to identify the quantities, sizes, etc. with the target total of $5000. thanks!

**Comment by aeiras** [comment]
@croundy, 

Can you please confirm that the USA vendor has been added as a Vendor? 
If yes, we will close this ticket and open a new one once we are done completing the design of the apparel. Thank you and @HailleySeed.

**Comment by croundy** [comment]
> @croundy,
> 
> Can you please confirm that the USA vendor has been added as a Vendor? If yes, we will close this ticket and open a new one once we are done completing the design of the apparel. Thank you and @HailleySeed.

Deluxe has been added to the list of suppliers for this and future EF swag projects. Once design and quantities/sizes/etc have been determined @HailleySeed will work with them and other vendors for pricing/delivery.

**Comment by aeiras** [comment]
Thank you so much Clark. 

We will close this ticket and once ready, we will pull Hailley in. 

https://github.com/eclipse/microprofile-marketing/wiki/Eclipse-Foundation-Team-GitHub-IDs 

This exists to enable MicroProfilers to collaborate with your team.
