### ISSUE TITLE
MicroProfile and Istio talk at JAX 2019

### ISSUE THREAD

**Issue by nheidloff** [microprofile/microprofile-marketing#60]
Speakers:
1) Niklas Heidloff https://twitter.com/nheidloff
2) Harald Uebele https://twitter.com/harald_u

Session (German):
Wie entwickle ich meine ersten Cloud-nativen Applikationen mit Java?

Für Cloud-native Anwendungen liefern Kubernetes und Istio out of the box eine Vielzahl von Schlüsselfunktionen, die generisch für Microservices verwendet werden können, egal in welcher Sprache sie implementiert sind und ohne Änderungen an der Anwendungslogik. Einige Funktionen können jedoch nicht von Orchestrierungs-Frameworks und Service Meshes abgedeckt werden, sie müssen in der Geschäftslogik der Mikroservices gehandhabt werden, z. B. anwendungsspezifische Fail-over-Funktionalität, Metriken und fein abgestufte Autorisierungen.

In dieser Session zeigen wir anhand eines konkreten Beispiels, wie man Microservices mit Java EE und Eclipse MicroProfile erstellt und wie man sie auf Kubernetes und Istio ausrollt und betreibt. MicroProfile verfügt selbst über einige komfortable Funktionen, die man typischerweise bei der Entwicklung von Mikroservices benötigt, z. B. für die Aufrufe von REST APIs und die Implementierungen dieser, einschließlich ihrer Dokumentation. Wir benutzen für die Session unser Codebeispiel cloud-native-starter, das wir auf Github als Open Source veröffentlicht haben, zusammen mit Skripten zum schnellen Deployment auf Minikube und Anleitungen.

Session (English):
How to develop your first cloud-native Applications with Java

For cloud native-applications, Kubernetes and Istio provide out-of-the-box a variety of key functionality that works generically for microservices, regardless of the language they are implemented in and without changes to the application logic. However, some functionality can not be covered by orchestration frameworks and service meshes. Instead it must be handled in the business logic of the microservices, for example application-specific failover functionality, metrics, and fine-grained authorizations.

In this session, we'll use a concrete example to show how to create microservices with JavaEE and Eclipse MicroProfile and how to roll out and run them on Kubernetes and Istio. MicroProfile itself has some convenient features that are typically needed for the development of microservices, such as: calls to REST APIs and implementation of REST APIs, including their documentation. For this session, we use our example code "cloud-native-starter", which we have released on GitHub as open source, along with scripts for fast deployments to Minikube and lots of instructions and information.

Session: https://jax.de/serverside-enterprise-java/wie-entwickle-ich-meine-ersten-cloud-nativen-applikationen-mit-java/
Tuesday 5/7/19
10:00 - 11:00 AM (German time)

@jaxcon

We'll demo this example: https://github.com/nheidloff/cloud-native-starter

**Comment by rstjames** [comment]
@nheidloff can you please write a tweet for your session and then I will create and image and prmote it on the MP twitter handle.

**Comment by nheidloff** [comment]
Hi @rstjames, how about this?

Attend the session from @nheidloff at @jaxcon to learn how to write your first cloud-native app with #Java and #MicroProfile on #Kubernetes and #Istio https://jax.de/serverside-enterprise-java/wie-entwickle-ich-meine-ersten-cloud-nativen-applikationen-mit-java/

Thanks a lot
Niklas

**Comment by rstjames** [comment]
@nheidloff  ok I scheduled the tweets to go out the week before and the day before. 
![MicroProfile-JAX-Heidloff](https://user-images.githubusercontent.com/12132146/56893575-69cfd900-6a83-11e9-929b-a687a76e2a83.png)
