### ISSUE TITLE
[Social Media push - Consecutive] Jakarta EE & MicroProfile Messaging Position 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#600]
**Timeline**

1 per month
work week day
throughout June 30th, 2022 
Oversee the push to see where it is next year and adjust as needed, either before or by then...

**Media message**
 #MicroProfile and @JakartaEE created & voted on a Positioning Message that explains the powerful collaboration between the two Working Groups. 

Learn more about their differences as well as their shared Implementations, Members, API collaboration & more.  https://docs.google.com/presentation/d/1wVaGJssQKPDSRcgRSE52mmm2Lb55THyUc_dGj7F5SAg/edit#slide=id.gbcfab764b6_0_221
#OpenSourceFUN #OSS

---- 
Ryan, 
Pulling you back into this project. thank you!  -- Please await for the review to trigger the adding of the event in MP social media, eta end of next week. 
Can you please modify/rename the document link to be Positioning Message? 

**Tracking**

[Consecutive Yearly Media Messages](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)

**Comment by ghost** [comment]
Don't forget this one we did in September but I don't think it was reviewed by anyone- 
 I think it's related to this same thing but in a different format: https://docs.google.com/document/d/1_xeUs1Y1SKNiei6iOZga8iLfgFtmg0-eMH0WfRESVIg/edit?usp=sharing

**Comment by aeiras** [comment]
@debbiehoffman, 

The work is great yet none knew about it b/c no ticket. 
The push can have 2 different messages. 

Thank you so much for bringing it to the ticket. Let's work on the review with the other MicroProfilers and choose the 2 messages that can be shared twice a month. :)

**Comment by ghost** [comment]
No worries -  it started as a google forum message and that's how I continued it. And we talked about it on a few marketing calls so we did know about it, but there is just too much noise and too many tickets for similar items. Will add #600 to agenda for next week next to the original forum message and combine them :)

**Comment by rstjames** [comment]
@aeiras am i needed on this?

**Comment by aeiras** [comment]
Not yet @rstjames. A review and approval of the 2 messages is still needed. Thank you for asking!

**Comment by caitmm43** [comment]
@aeiras Hey Amelia, Is there any update on this ticket?  Please add your comments here and update the minutes accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
This task is on me to complete the review created by Debbie. ETA end of January as I need to add my writing to Debbies' document before I bring it back to the group review on a future call.

**Comment by aeiras** [comment]
https://docs.google.com/document/d/1_xeUs1Y1SKNiei6iOZga8iLfgFtmg0-eMH0WfRESVIg/edit

Some edits are integrated and we could discuss this item on next call @caitmm43. Not as a priority, it is a regular item. :) 
Thank you for pushing the reminders out.

**Comment by aeiras** [comment]
It has been 1 year, and there has been no traction on getting this on MP media. 

Closing it for now.
