### ISSUE TITLE
[MPWG documentation]  2022 Marketing Plan - in detail 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#601]
Direct export from the MPWG 2022 Project plan to enable the creation of a more detailed document as feedback provided from the MP project plan call stated the need of such improvement! https://docs.google.com/presentation/d/1jX1YfeOEN_k60voVj9CVGwT7yXvlF8NA/edit#slide=id.p11

![image](https://user-images.githubusercontent.com/10731224/137957361-20feb706-540d-499e-8407-5018fc284fd0.png)
![image](https://user-images.githubusercontent.com/10731224/137957389-6d7d77d6-99e5-4a93-a689-84b9bb4d0a4b.png)

**Comment by caitmm43** [comment]
@aeiras What next steps should be taken on this ticket?  Should we look for volunteers to own any aspects of this in the next meeting?

**Comment by aeiras** [comment]
Slide 2 - Branding and Compatibiity is no longer applicable to MP. 

We can close the ticket as many items are being tackled. 

--- 1 thing I would like to submit as a call to action for Neha and Neha you can say, "no bandwidth" for 2021 or similar. 

@nsardana-bny, Neha, 
It could be great if you choose to become the Steward on the Marketing documentation. There is no need to wait for a call. Either we use a new ticket or the mailing list to discuss. 

I wrote the MPWG Onboarding members currently link to the MPWG page https://microprofile.io/workinggroup/
https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--Members-Onboarding

Ideally, other members help with the parts within. 
For example,  Committer Rep Onboarding wiki thread https://groups.google.com/g/microprofile-marketing/c/YePKMccVhhc

The Marketing wiki follows the same form. It ought to be inserted into the main Onboarding document. All the specific wiki's will make the document cleaner, shorter and much more consumable at one try. 

Now,  the marketing draft (gathers all the current stuff (documented) under Marketing into 1 document) ought to be drafted under Community documentation and reviewed before being exported as a standalone wiki under MPWG repo and linked to the Main document of onboarding new members. 

- openly brainstorming. Thank you for facilitating the exchange, amazing!
