### ISSUE TITLE
[Social Media Push] broadcast to get community voice on MP technical goals

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#602]
Please push this community voice via social media push

We need your input to help us define MicroProfile 2022 Techincal Goals. Please add your thoughts to this [googledoc](https://docs.google.com/document/d/1kYUKaf0-G75sGkDlcI7ccN-YVADg8476q1fVIr1P2jk/edit?usp=sharing). The deadline is 26th October. Thank you for your contribution!

**Comment by Emily-Jiang** [comment]
@aeiras @rstjames please feel free to polish the tweet text. Please push it out on Thursday.

**Comment by aeiras** [comment]
Emily, did you move it to the correct folder?
See my msg to the forums on the importance of it. once you do, we can push it twice to get more momentum. :) Let's do this!

**Comment by Emily-Jiang** [comment]
I have recreated the file under the folder you asked and updated the link in this ticket.

**Comment by aeiras** [comment]
Fantastico, Emily!

@rstjames, 
can you please first thing on your Monday create and schedule 2 messages about communicating that the 2022 Program plan is in the works and the Technical goals welcome MicroProfilers' feedback. 
Drive to be used https://drive.google.com/drive/u/0/folders/1do4bZlfCcXqcPvhs3PquglX74eFUK-Ic alone side with MP calendar link. 

Monday and Tuesday suffice for C2A. Thank you, Ryan!

Emily wrote a short media description that you could use as well:

_We need your input to help us define MicroProfile 2022 Technical Goals. Please add your thoughts to this googledoc. The deadline is 26th October. Thank you for your contribution!_
Google drive link
Calendar link

**Comment by rstjames** [comment]
went out today and going out tomorrow
![microprofile-technical_goals](https://user-images.githubusercontent.com/12132146/138742414-e5dd8884-1fa3-4950-a439-96c4224986ce.jpg)
.

**Comment by aeiras** [comment]
beautiful!
