### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by ankurkumarz** [microprofile/microprofile-marketing#603]
First Name: Ankur
Last Name: Kumar
Email: ankurkumar78@gmail.com

I have been writing blog posts on Microservices and cloud native and would like to extend it to cover Microprofile use-cases. Please add me as an author to publish.

**Comment by ghost** [comment]
Hi Ankur,
 I went ahead and added you to microprofile.io as a contributor. You should have received an email with the password to log in and submit blog posts.

Welcome :)
