### ISSUE TITLE
[MPWG Page] New Members Onboarding Document - click link 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#604]
@rstjames, 

Can you please help add Members Onboarding as a yellow click button?
we added it under Knowledge section but it is too hidden and not efficient. It is ok to have it more pronounced. :) Gracias! 

![image](https://user-images.githubusercontent.com/10731224/140436178-a4e64f00-280f-47c6-bee7-5e67d98d30c3.png)

[Members Onboarding](https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--Members-Onboarding)

**Comment by rstjames** [comment]
@aeiras Think there are already too many buttons and we can not fit another. We should reformate the top card if we want to keep adding things. I think this can grow into a problem every time we think there is something important and we should put it on the top. The point of the tabs is to be organized and people to look for them.

**Comment by aeiras** [comment]
Can you think of a way to add this to the main yellow area? 
There are only a few items that are a MUST on "easy to find". 
This page could benefit for tabs that bring the viewer to its single page in the future. 

I think something similar to the Branding tab could work.

**Comment by rstjames** [comment]
@aeiras page has been updated. Not the most scalable but works for now. 
https://microprofile.io/workinggroup/

**Comment by aeiras** [comment]
It looks great, Ryan! gracias
