### ISSUE TITLE
[Website]  Add google Drive to the Resources Page

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#606]
Given latests " where is the drive questions" : ), the drive needs to be more visible than only in the Branding page. 

Ryan, can you please add it to the Resources Tab? 

Community Google Drive https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8?resourcekey=0-vOqlGHzf3OkGgD1DMMsq0g

Thank you,

**Comment by rstjames** [comment]
updated

**Comment by aeiras** [comment]
Thank you!
