### ISSUE TITLE
[website - MPWG Page] Legal Agreement addition: Working Group Sponsorship Agreement

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#611]
Under Agreements, we need to add:

1) Working Group Sponsorship Agreement as the last item. 

*remove* 
- MPWG Trademarks – WIP later

https://www.eclipse.org/org/workinggroups/sponsorship/working-group-sponsorship-agreement.pdf

**Comment by rstjames** [comment]
done

**Comment by SharonCorbett** [comment]
Please reopen...

In order for the Working Group to hold a Sponsorship Program, the Steering Committee must agree to update the Charter accordingly followed by Executive Director Approval.  The Eclipse Foundation then adds the Sponsorship Agreement to explore.php for the related WG. 

Please raise the charter update request to the next Steering Committee agenda.  

Thanks for understanding there is a governance framework in place that must be followed.

Sharon

cc @paulbuck
