### ISSUE TITLE
[Website Addition ] Brand Manual needs to be added

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#612]
@rstjames,

This ticket https://github.com/microprofile/microprofile-wg/issues/45 is completed with version 5 as final for the time being. 

Let's close it by you helping us add the Branding manual to the Resources page https://microprofile.io/resources/branding/

as a new card that is under the clickable yellow items that are listed. 

Thank you!

**Comment by rstjames** [comment]
The site has been updated
[MicroProfile-Brand_Manual_Guide.pdf](https://github.com/eclipse/microprofile-marketing/files/7570443/MicroProfile-Brand_Manual_Guide.pdf)
.
