### ISSUE TITLE
[Website MPWG Page] Add to Email Forums Committer Tools

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#615]
Let's add under https://microprofile.io/workinggroup/
Email forums section at the beginning of the list the 
https://projects.eclipse.org/projects/technology.microprofile

The text is as follows:
Welcome to the MicroProfile Committer Tools site. If you want to Nominate a Committer, discuss IP logs, communicate with the PMC or Dev list, etc, then you're in the right place.

**Comment by rstjames** [comment]
added

**Comment by aeiras** [comment]
@rstjames, 

I don't see the update yet. 
The last item listed under emails continues to be: 
Eclipse Foundation Team GitHub IDs- Contact Information

**Comment by caitmm43** [comment]
@rstjames @aeiras 

Hey Ryan, Amelia,

This ticket was closed and reopened.  Has it been resolved?  Please add your comments here or close it, and update the minutes accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
> added

@rstjames I don't find the addition. Can you please show me with a screen shot its location?
Thanks.

**Comment by aeiras** [comment]
Here is what I see
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/10731224/150031630-f2078ba2-d1bf-4aed-8488-cfa7b80fad7c.png">

**Comment by rstjames** [comment]
is this correct
<img width="675" alt="Screen Shot 2022-01-26 at 11 06 33 AM" src="https://user-images.githubusercontent.com/12132146/151143763-683ebab8-77e6-4ea3-aaf5-e8fa39a0edda.png">

**Comment by aeiras** [comment]
Yes, Ryan. 
Thank you, it is perfect!
