### ISSUE TITLE
[Website= MPWG Page] Add Linkedin to Social section

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#616]
Ryan, 

Thank you for helping with the continuous improvement on the page. 

Under Social spot, let's add Linkedin. 
Wording: MicroProfile Linkedin

https://www.linkedin.com/company/microprofileio/?challengeId=AQEiG_nADMcb8QAAAX1J1N1S0Wv8KW584W-lT1AWkfm9jx_DIx2vbSAf9IVN-3o3jnZdavgvmOOL5D952mkjaDrjzMwVGb4-NQ&submissionId=2209db3f-d4ff-b916-02e5-65662beb027b

**Comment by rstjames** [comment]
added
