### ISSUE TITLE
Please promote JakartaOne Livestream 2021

### ISSUE THREAD

**Issue by TanjaObradovic** [microprofile/microprofile-marketing#617]
Hello MP community!

Can you please help us promote JakartaOne Livestream 2021?

Please feel free to use this social kit document for this

https://docs.google.com/document/d/1AP1O_UWvlCMY6Fk4CIiNRBcZvr4krj8L7GkUFaGqGbM/edit#

Thanks!

**Comment by aeiras** [comment]
@rstjames can you please prioritize this ticket and push JakartaONE english?
-- 

https://twitter.com/JakartaOneConf/status/1463130212670050307?s=20

Designs cards are provided by link via Tanja's submission. Thanks, Tanja! 

**Design**
Count down card accentuates the Jakarta Trademark logos and colors. Let's use that card
 
![image](https://user-images.githubusercontent.com/10731224/143144649-e942df32-307c-4ffa-999e-7ce9aef7ceca.png)

**Twitter description**
Calling all #Java Developers and @java Communities to join @JakartaOneConf on December 7th.  Watch live, from the comforts of your home, the 4 #MicroProfile sessions & learn more about #CloudNative technologies @JakartaEE @Java_EE content. 

Register here: https://bit.ly/3qhRKz9

**schedule countdown**  4 media pushes

- November 24th
- Nov. 28
- Dec 1st
- Dec 5th

Gracias,

**Comment by HailleySeed** [comment]
Hi @aeiras ! We would also appreciate if you could help us promote the following social on twitter:

Description:
Win a prize at #JakartaOne Livestream by making a pizza to celebrate #JakartaEE! Get creative with the toppings to resemble the #Jakarta logo, take a picture & tag @JakartaEE & @JakartaOneConf on twitter by 18:00 CET on December 7th to enter. https://www.crowdcast.io/e/jakartaone-livestream-2


Social Card:

![JakartaOne The largest Jakarta EE event of 2021 (1)](https://user-images.githubusercontent.com/85507137/143273356-e4228ece-fc0a-47af-ad16-9f6f8272786b.png)

Thank you!!

**Comment by rstjames** [comment]
@aeiras @HailleySeed @TanjaObradovic 

I scheduled the event posts to go out on the selected dates and also pushed the pizza post to go out before the event.
