### ISSUE TITLE
[INFRA] EF Team Git IDs - Contact 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#618]
I released today that a EF git IDs wiki is necessary to enable MPWG to collaborate via git issues without wondering around for those IDs. 

https://github.com/eclipse/microprofile-marketing/wiki/Eclipse-Foundation-Team-GitHub-IDs

**Comment by aeiras** [comment]
@rstjames, thank you for your help on this!

Can you please add the wiki to the MPWG page https://microprofile.io/workinggroup/  under Email Forums?

**Position:**
Below the CN4J forum

**Description**
[Eclipse Foundation Team GitHub IDs- Contact Information](https://github.com/eclipse/microprofile-marketing/wiki/Eclipse-Foundation-Team-GitHub-IDs)
If you need to collaborate with the Eclipse Foundation Team on any specific task associated with the project such as Ops, Marketing, or Infrastructure, find the individual's gitID & submit your ticket request via the  [MPWG git issues](https://github.com/microprofile/microprofile-wg/issues) & the [MicroProfile Marketing](https://github.com/eclipse/microprofile-marketing/issues).

**Comment by rstjames** [comment]
Updated
