### ISSUE TITLE
[Ops] MicroProfile.io SEO 

### ISSUE THREAD

**Issue by croundy** [microprofile/microprofile-marketing#620]
We are working with an agency to define and create an SEO strategy for MicroProfile.io. Elements of this plan include: 

- **Site Audit and Keyword Search**
     Analyze current state of the site to determine what is needed to gain search visibility

- **Focus on Optimization of Core Pages**
     Initial effort to focus on microprofile.io (8 main pages + 22 project pages)

- **Develop Plan and Recommendations for 2022 Implementation**
    Page structure
    Meta tags and keywords
    Content strategy

To make this program a success, we need your input on the document linked below. This is the same document that has been sent to the email list on 2 separate occasions: 

https://docs.google.com/document/d/1QqVQXz07XSVBku8BjOggzBwizyxK9qMzDNvRpNoK-cQ/edit

**Comment by Dexmaster** [comment]
There are 23 projects and 6 main pages as far as I know, I'm curious who has done research for this strategy.
 
I can answer right away that the back-end for projects list and each project individual pages is broken even now (caching broken in back-end) and good SEO is not possible without proper projects tool and front rebuilding.
 
So I would say right away SEO research is needed only after MP will re-do the Project's page with sub-pages in 2022 as stated in the approved program plan.

**Comment by croundy** [comment]
@Dexmaster you may be right on the breakdown of the number of pages. This is based on a cursory review of the site by the agency. At any rate, the project is scoped out as some 28-30 pages. While there is always work to be done and improvements to made, this project is meant to help with the SEO strategy (not implementation) so as site pages get fixed and/or updated, the expectation would be that the learnings and strategy will be applicable in helping to drive messaging, content, etc. as those updates get made. Also, this process will take some time and will flow well into 2022. The critical piece here is for the WG to work with us in helping derive the most value.

**Comment by Dexmaster** [comment]
@croundy but "Page structure" will change and will need another SEO research for 23 projects with project list page, so will it be done only for 5 pages out of 30? or 80% of research will just be thrown out? as content and structure for 80% will change...

**Comment by Dexmaster** [comment]
Ok, I might have said thrown out too fast, probably some parts could be reused even for those pages, but they could change drastically in structure 100% in content probably and I still believe SEO research reasonably should be done only after project pages fixing is finished.

**Comment by croundy** [comment]
Page structure refers to recommendations only, which I would expect to be helpful as those pages go through re-work. This research should be viewed as a living document that becomes a strategic roadmap to guide content and website strategy. The WG will own it and can/should iterate as things change. As you know, SEO is about continual improvement....the key is to have a better understanding of where we might best focus our efforts to gain an advantage and then build on that. And that's what this is all about.

**Comment by Dexmaster** [comment]
But recommendations will be irrelevant if content rework will change structure completely, recommendations will be related to current broken content, wouldn't it be better to do it after they will get re-built. Implementing those recommendations and other SEO website changes are unrelated to projects pages rebuild as far as I know, doesn't it increase scope of other task too much? I'm just saying review and research will be mostly irrelevant after rebuild, creating a roadmap to guide previous content and website strategy is great but I feel these tasks are in wrong order.

**Comment by croundy** [comment]
We can slow walk this to make sure WG benefit is optimized and coordinated with website updates, but only part of this project is about structure. A lot of it is about content strategy and other drivers of SEO. Websites are constantly changing, as they should. If we are waiting for the perfect time, it will never happen. This project is currently in play, so now is a good time to get ducks in a row for any already planned website changes.

**Comment by Dexmaster** [comment]
I'm just saying resulting three parts all will change for those pages:

Page structure - recommendations on old page structure which will change
Meta tags and keywords - recommendations based on old content and will need to be re-done for new content
Content strategy - maybe can be used, but still might need to be re-done

Those are mostly all that drives the SEO (there is also links, link/network building etc), but the things you can do right away are those three and all of those are useful only if they are relevant to content. (and provide proper SEO research: keywords, descriptions and other changes needed for each page) And if you feel you just need generic one you can open google and get generic best practices for website SEO for free :)

**Comment by caitmm43** [comment]
@croundy @aeiras @Dexmaster 

Hello all, is there any update on this ticket?  Please add your comments here and update the minutes accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
During the Sept 13th Community call, Paul (EF) stated that the 2021 MPWG budget was spent.  
Closing this ticket.
