### ISSUE TITLE
[General 2022 bare to minimum ]  Call to Actions

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#621]
Reminders submitted to the mktg forum on Nov. 29th. 

1. [[Call to Action] 2022 Monthly Mktg-Call Stewards - Schedule needs MicroProfilers
3 vi](https://groups.google.com/g/microprofile-marketing/c/qTzHgM2IjPo)

2. [https://github.com/eclipse/microprofile-marketing/watchers - Become ONE!
1 v](https://groups.google.com/g/microprofile-marketing/c/OgIdi8aAt3g)

**Comment by caitmm43** [comment]
@aeiras Is there any update needed on this ticket?  If it is no longer in progress, please close and update the minutes accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
@caitmm43, 

This ticket is kept open until all months are covered by at least 1 Steward. 
It is the year of each monthly Steward to talk about this ticket, during each Mktg call.  The ticket is usually added under Priority tasks as a show and tell of the Responsibilities and the latest volunteers' schedule sheet. Constant awareness is placed on this ticket task.

Questions, shoot!

**Comment by aeiras** [comment]
Let's close it and keep it as a priority 1 in the mktg agenda instead.
