### ISSUE TITLE
[General] 2021 Program Plan Retrospective --- Recommendation on how

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#622]
On last week's community call, it was discussed that MicroProfilers should own a retrospective on the work completed this year. 

[Yearly Program Retrospectives](https://docs.google.com/spreadsheets/d/1E3Z2OwWByU9ozh6ojFGu-kBObwl4ak4j0FiPUV6H4HM/edit#gid=0) is a spreadsheet located under the Minutes folder.  It provides public edit access for all MicroProfilers who are actively contributing to MP and wish to provide feedback :)

**Comment by caitmm43** [comment]
Hello @ederks85, @radcortez, and @Emily-Jiang, 

I am adding you to this ticket in reference to @aeiras's message via the MP Marketing Group:
[https://groups.google.com/g/microprofile-marketing/c/5vtaeWzqA6Q/m/NM3TrvA3BgAJ](https://groups.google.com/g/microprofile-marketing/c/5vtaeWzqA6Q/m/NM3TrvA3BgAJ)

**Comment by caitmm43** [comment]
@aeiras, @Emily-Jiang, @radcortez, @ederks85

Hello all, are there any updates to this ticket?  Please add your comments here and a status summary to the minutes.  Thank you! :)

**Comment by aeiras** [comment]
Today, during the MP community call MicroProfilers chose to adopt the written spreadsheet as the formalized way to move forward on yearly retrospectives. 

A new folder has been created under MP Community drive called **Retrospectives** 
The document has been moved from Minutes folder to Retrospective as it takes shape. 

@rstjames, thank you in advance for tackling this task! 

Please add the link to MPWG as a new subject category under the https://microprofile.io/workinggroup/?
**location- Position:**

- Below Program Plan & Budget and above Email Forums

**Wording description**

MicroProfilers routinely, via calls & in writing throughout the year and ONE of completed yearly, via the [Yearly Plan Retrospective](https://docs.google.com/spreadsheets/d/1E3Z2OwWByU9ozh6ojFGu-kBObwl4ak4j0FiPUV6H4HM/edit#gid=0) & its video recording during 1st Community Call of the new year, confront honestly and with candor a zoom-out Yearly Retrospective on the tasks completed, the good and the bad.  

1. The lessons learned are acknowledged
2. The good outcomes are acknowledged   
2. The Improvements are set forth based on the gaps found on the actions performed

**Comment by aeiras** [comment]
completed on January 18th call using the spreadsheet retrospective!
