### ISSUE TITLE
[Website- MPWG tab]  Insert Committer as a Member

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#623]
https://microprofile.io/workinggroup/

Lets use the design word "Committer" created under the wearable swag on https://github.com/eclipse/microprofile-marketing/issues/594#issuecomment-966245069  

The Charter recognizes all MP committers as formal members of the MPWG.  We must add the Committer into the listed members with a logo. 

doing so means that the MP 5 slides under members need to insert the Committers as well. 

@ederks85 if anything is missing, please insert here. Thank you!

**Comment by aeiras** [comment]
![image](https://user-images.githubusercontent.com/10731224/144314100-f73f0435-05d3-46d0-9fc7-26fb51b341d8.png)

Suggested logo

**Comment by aeiras** [comment]
@@ederks85 see the design :) forgot to add it. too fast.

**Comment by rstjames** [comment]
@aeiras I am working on this but on the shirts we put contributors. Which one is correct? Contributor or committer?
also the MP home page logos seem out of date. Lightbend is still there and microsoft. Should these be updated if so which logos?

**Comment by aeiras** [comment]
@rstjames, 
Thank you for working on this task. 

Let's add Committers - make it plural as MP has 51 committers today.  
The website has Contributors as a standalone page which is fantastic. The Logos shown on the MPWG page should be compliant with the MP Charter that lists three memberships: ORGs, Committers & Guests. MP has no Guest members yet. 

I hope this is helpful,

**Comment by rstjames** [comment]
@aeiras I was referring to https://microprofile.io/ page logos are out of date. 
![Screen Shot 2021-12-15 at 11 43 04 AM](https://user-images.githubusercontent.com/12132146/146172164-f9f1dd91-b1ec-4984-9cea-5df043eb6d74.png)

Committers have been added to the WG page

**Comment by aeiras** [comment]
The addition of Committers to both the MP 5.0 release slides and the MPWG page looks wonderful, Ryan. Thank you. 

I see what you mean. 
Can you please create a new ticket and added as a discussion to have in January about those logos? please

We chatted about them in January last year. The majority wished for them to stay as they are. Pre- MPWG stuff. 
Let's see how everyone feels in the new year. :) Thank you for tackling it and leading that discussion next January!

**Comment by caitmm43** [comment]
@rstjames love the slide effect--if that was you, nice touch!

It sounds like the original issue has been addressed the issue of outdated logos on the [https://microprofile.io/](https://microprofile.io/) will be tacked in a new ticket  #637.  Closing this issue.
