### ISSUE TITLE
[2021 Swag Order]  Request Quote to Vendor for $5,000

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#625]
To be drafted and discussed on Monday, Dec 6th during the Marketing call:  [Proposal](https://docs.google.com/spreadsheets/d/1iOTTar3nFXI_yraCmZu4KVBduRPSgD7BDeN1fKZizWk/edit#gid=1242876094)

---

Linked to 

- [ ] https://github.com/eclipse/microprofile-marketing/issues/595 updating the t-shirt & zip-up hoody using Red Hat logo preference for MP wearables. And final members review. 
- [x] https://github.com/eclipse/microprofile-marketing/issues/594
final approved versions and mock ups [Apparel Designs](https://drive.google.com/drive/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg)

**Comment by caitmm43** [comment]
@aeiras Here is a link to the quote from Deluxe Screen Printing: [https://deluxe.deluxescreenprinting.net/Dsp/BusinessTools/Invoice?ID=23173607&Email=a277f6a5](https://deluxe.deluxescreenprinting.net/Dsp/BusinessTools/Invoice?ID=23173607&Email=a277f6a5)

**Comment by caitmm43** [comment]
PDF Copy: [12_7_2021_Deluxe MPWG - 380 Shirts_Invoice23173607.pdf](https://github.com/eclipse/microprofile-marketing/files/7681421/12_7_2021_Deluxe.MPWG.-.380.Shirts_Invoice23173607.pdf)

Google Drive File Location: Added to the Swag folder under Orders-Quotes > Quote Proposals- by Vendor > 2021 > [12:7:2021_Deluxe MPWG - 380 Shirts_Invoice23173607.pdf](https://drive.google.com/file/d/1l_J_pNKqUPGGMZPcNHwEHgxKvMm9W6ey/view?usp=sharing)

![Screen Shot 2021-12-08 at 7 57 09 PM](https://user-images.githubusercontent.com/25733252/145315112-718b14a1-9b45-45c1-ac14-03168aafb3a6.png)
