### ISSUE TITLE
[Release MP 5.0] MicroProfile 5.0 Release Blog Post / Announcement - Spanish Version

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#626]
This issues is oriented to track the process to provide a Spanish version of MicroProfile 5.0 Release Blog Post / Announcement from the English version available here: https://drive.google.com/drive/folders/1XqoNB9kEL9dpKxjHq71a4CfmBx1vjt3Z

_Note: Base on the results from #607 and #619,_

**Comment by emecas** [comment]
A first draft of the Spanish translation is available here: https://docs.google.com/document/d/1v_QxO10cPAROETuA1d9PHbV43ZOFYXcNGmQpKKm_PAE/edit#

CC: @aeiras 

@LuisGalazM te gustaria darle una review?

**Comment by LuisGalazM** [comment]
@emecas por supuesto 👍

**Comment by LuisGalazM** [comment]
@aeiras @emecas me pueden dar acceso para comentar en el documento?
Saludos!

**Comment by emecas** [comment]
> @aeiras @emecas me pueden dar acceso para comentar en el documento?
> Saludos!

Listo @LuisGalazM, actualizado el acceso para comentar, intenta de nuevo por favor! Thx

**Comment by caitmm43** [comment]
@aeiras will handle review & next steps

**Comment by aeiras** [comment]
Emerson, 
Thank you for caring so much to lower the language barrier for the Spanish only speaking Java community with  your current work translating MP 5 content. Tus acciones son divinas! :) 

Fantastic first draft. I added initial comments and feedback for you and @LuisGalazM to tackle the blog. Hola Luis 👍 

**Recommendation** 
Emerson, 

You have Edit access to the [MP Release folder.](https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLX096QUdxcTdueWs?resourcekey=0-zCVjDPtS441ppquRx4Xkpg) 
Can you please move into the [MP 5.0 folder ](https://drive.google.com/drive/u/0/folders/1XqoNB9kEL9dpKxjHq71a4CfmBx1vjt3Z
the 2 spanish documents? 
We need the documents there formally. Better to transfer right now while working on the drafts. 
Also, the plan is to push the spanish version 1 per month, English version 1 per month. 2 release reminders per month. We will draft the repeating tweet after the Announcement goes out.  ETA next week.

**Comment by aeiras** [comment]
@emecas, 

When you import the blog, the author is you. I will go to the document for final review now that we have the blog post it : )

**Comment by aeiras** [comment]
Great job @LuisGalazM translating the original tweet to Spanish. We will use that for consecutive media messages as soon as the Spanish blog and slides are completed. 
You and Emerson are amazing! 


https://twitter.com/LuisGalazM/status/1468263883051782148?s=20

**Comment by emecas** [comment]
@aeiras 

Which of the 3 following options for linking pages of available language versions do you think looks better? 

![image](https://user-images.githubusercontent.com/849502/145474940-eea7d71c-ecd9-4064-8405-d2f43bbd44a3.png)



Even GitHub does not render them exactly like expected, the result is good enough and generated documentation will follow the correct AsciiDoc outcome. This is how the 3 options are presented in the website:

![image](https://user-images.githubusercontent.com/849502/145475077-bbc14076-35b3-45a4-ac52-0140defdc76e.png)

**Comment by aeiras** [comment]
Hey snuggly you, @emecas 

From UX side option 1 seems great.  No borders and it can spill into many more languages easily. :) 
Option 3 is too messy in positioning. 
Option 2 is acceptable. 

Which is one is your preferred version?

It is irrelevant what I like. Lets focus on the reader's experience, always :)

**Comment by emecas** [comment]
> Hey snuggly you, @emecas
> 
> From UX side option 1 seems great. No borders and it can spill into many more languages easily. :) Option 3 is too messy in positioning. Option 2 is acceptable.
> 
> Which is one is your preferred version?
> 
> It is irrelevant what I like. Lets focus on the reader's experience, always :)

I have adjusted option 1 and created a PR, removing the title, it is a AsciiDoc `sidebar`, but  I could not find a way to remove the borders.

**Comment by aeiras** [comment]
Super fun to improve things with you, Emerson. 
YOU care and it shows. https://github.com/eclipse/microprofile/pull/238 is merged. :) 
https://github.com/eclipse/microprofile/pull/238/commits/b5b65a33ed6f5b41c598afeff61d81b57e88b5e8

You are amazing!

**Comment by caitmm43** [comment]
@emecas, it sounds like this task might be complete.  If so, please close this ticket and update the minutes accordingly.  Thanks!  :)

**Comment by aeiras** [comment]
not yet in social media. Awaiting to hear from Emerson that all items are completed to close the 2 tickets relevant to the translation. Thanks, Caitlin.

**Comment by caitmm43** [comment]
Sounds good, thanks for the update! :)

**Comment by emecas** [comment]
> not yet in social media. Awaiting to hear from Emerson that all items are completed to close the 2 tickets relevant to the translation. Thanks, Caitlin.

@aeiras  @caitmm43 

I just closed #627 , looking for the other one in pending

**Comment by emecas** [comment]
> > not yet in social media. Awaiting to hear from Emerson that all items are completed to close the 2 tickets relevant to the translation. Thanks, Caitlin.
> 
> @aeiras @caitmm43
> 
> I just closed #627 , looking for the other one in pending

It seems the other ticket in pending is this itself

Document translation [1]  and blog post draft with SEO analysis passed [2] are completed as well.

[1] https://docs.google.com/document/d/1v_QxO10cPAROETuA1d9PHbV43ZOFYXcNGmQpKKm_PAE/edit#
[2] https://microprofile.io/?p=6948&preview=true

**Comment by aeiras** [comment]
Emerson, 

The blog is published. Congratulations, MicroProfiler!!!
https://microprofile.io/2022/02/01/lanzamiento-de-microprofile-5-0-con-dependencias-jakarta-ee-9-1-actualizadas/

It needs the Spanish card design as the header of the blog as seen in the English version. 

@rstjames can you please help us create and add as the header of the Spanish blog the design card for MP 5.0? 
To do so, using the spanish title is OK for the wording of the card. Thanks, RSJ! 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10731224/152063806-c738c028-10e7-4789-91b2-358dff89f1a9.png">

I will create a new ticket to bring in the English and Spanish blogs so we can start their media schedule until the end of May. Stand by. :)

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1509188718527229958?s=20&t=GTWeolD5qYTTkhmuScG7Aw
