### ISSUE TITLE
[Release MP 5.0] MicroProfile 5.0 Release Slides - Spanish Version

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#627]
This issues is oriented to track the process to provide a Spanish version of MicroProfile 5.0 Release Slides from the English version available here: https://drive.google.com/drive/folders/1XqoNB9kEL9dpKxjHq71a4CfmBx1vjt3Z

Note: Base on the results from #607 and #619

**Comment by emecas** [comment]
CC @aeiras  A first draft of the translation is available here : https://docs.google.com/presentation/d/11-eNwPBNidxgBU8WauRrAyXmIZu8dOXNRb0BVCAJm7I/edit?usp=sharing

@LuisGalazM

**Comment by aeiras** [comment]
@emecas, 

Edwin has completed adding the watermark on 1st and last page of the presentation with extra changes completed with Tetiana and soon Ryan. 

https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.g3c8b0fa004_3_0

Please update the document with latest version. 
Do pull me in if you encounter issues. For design help please pull Tetiana and Ryan via this ticket or the document. :)

**Comment by rstjames** [comment]
@emecas the mp5 presentation has been updated please take a look 
https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.p

**Comment by aeiras** [comment]
It looks fantastic, Ryan. Thank you!

**Comment by emecas** [comment]
> @emecas the mp5 presentation has been updated please take a look https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.p

Thanks @rstjames & @aeiras  , I've updated Spanish version as well accordingly

**Comment by caitmm43** [comment]
@emecas Hey Emerson, it sounds like this task might be complete.  Way to go!  If so, please close this ticket and update the minutes accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
Caitlin and @emecas, 

Emerson, we are missing you "it is completed" ready for media push for Q1. 
Given the holidays, everyone went away so I am not sure you completed the work yet. 
As soon as you do let us know so we can schedule the media and documents to go live. 
Luis already translated the media translation from the English version so that is completed.

**Comment by emecas** [comment]
@caitmm43 @aeiras  the Spanish presentation is completed and located in the correspondent folder:

link: https://docs.google.com/presentation/d/11-eNwPBNidxgBU8WauRrAyXmIZu8dOXNRb0BVCAJm7I/edit?usp=sharing

Thanks !!!

**Comment by aeiras** [comment]
@emecas,

Fantastic to hear the completion of both documents. 

I will create a new ticket to bring the English and the Spanish blogs to be published via MP media from now until end of May. 

Thank you for rocking it, Emerson, you are wonderful. 
I will close the 2 tickets while linking them to the new media git issue that will be assigned to Ryan.
