### ISSUE TITLE
[Content creation - Youtube Import ] Mktg video recording Dec 6th

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#628]
@Emily-Jiang or @jclingan, are either of you the right person to do the youtube upload for today's meeting?  If not, could you recommend and tag the correct individual(s)?  Thank you!!

**Comment by Emily-Jiang** [comment]
@caitmm43 the video has been uploaded by @jclingan I think. It is [here](https://www.youtube.com/watch?v=OZ-nCLmJ2BU)

**Comment by caitmm43** [comment]
@Emily-Jiang  Thank you! :)
