### ISSUE TITLE
[Swag- T-shirt ] Final Review welcomed on MPWG 2021 Tshirt  by the end of 12/7 (PDT) 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#629]
Back of the t-shirt is being adjusted to match MPWG Members in 2021. It requires final review to make sure Member logos are up to date. 

- [Back shirt MockUp](https://drive.google.com/drive/u/0/folders/1LXgXYIYPSmUteMd0fA7lr9ZP9WE0U259)

![image](https://user-images.githubusercontent.com/10731224/144913077-cd3a648b-fc30-4c53-a28c-b6efbb27513a.png)

Red Hat feedback via [@myfear comment ](https://github.com/eclipse/microprofile-marketing/issues/595#issuecomment-977550346) will be applied tomorrow.  Thank you, Markus! 

----

[Print Data - Shirt folder](https://drive.google.com/drive/u/0/folders/0B7PK4ZIk1mjAT3hTWjJMM2lGYU0?resourcekey=0-6HJOanvfrcZB2uhDjjhf0A   - 

- [Front & Back MockUps](https://drive.google.com/drive/u/0/folders/1LXgXYIYPSmUteMd0fA7lr9ZP9WE0U259)

--- 
**Discussed on 12/6/ Marketing call** that MP **does not wish** to print the zip-hoodie on 2021 budget because we don't know the actual sizes of the Committers. The plan is to print MP hoodies in 2022 with 2022 swag budget by itemized exact order on sizes based on Committer's sizing request.

**Comment by mpredli01** [comment]
The shirt looks awesome!  Many thanks to the marketing committee for creating it!

**Comment by aeiras** [comment]
> The shirt looks awesome! Many thanks to the marketing committee for creating it!

thank you for your prompt review, you rock, Mike! :) 

By the way, there is no marketing committee to power MP collaboration.  MPWG has only 1 committee by choice, Steering which suffices.

**Comment by aeiras** [comment]
T-shirt has been adjusted with feedback provided https://github.com/eclipse/microprofile-marketing/issues/595#issuecomment-988916338

**Comment by aeiras** [comment]
Deluxe printer provided yesterday with additional feedback on submitted designs that require simplification to enable clear printing without losing the style.
![Screen Shot 2021-12-08 at 12 43 17 PM](https://user-images.githubusercontent.com/10731224/145407181-73d483c5-aab8-492a-85cb-e5d81fa4b0bd.png)


With @rstjames & @caitmm43, we are working internally with the Deluxe Art team to create the 2021 t-shirt.  

**Changes as follows:**

1. All trademarks and registered marks have been removed from the shirt, front and back.

Ryan will update on other changes.

**Comment by rstjames** [comment]
@mpredli01 because of the printing limitations we will need to adjust the Garden state user group logo. I wanted to check if you are ok with this? We are on a sharp deadline to get this done.
<img width="693" alt="Screen Shot 2021-12-09 at 12 26 13 PM" src="https://user-images.githubusercontent.com/12132146/145415029-a2da7e04-10dd-4dfc-9ed1-c1f3837041fc.png">
<img width="596" alt="Screen Shot 2021-12-09 at 3 29 10 PM" src="https://user-images.githubusercontent.com/12132146/145415042-a9dc2847-245b-4980-9c3e-a9d227df849b.png">

**Comment by mpredli01** [comment]
Hi Ryan and Amelia:

Yes, we are OK with this change for the T-shirts.

Mike.

**Comment by aeiras** [comment]
Thank YOU, Mike 💛 for your prompt feedback! 
given the deadline, we appreciate it!

**Comment by rstjames** [comment]
@mpredli01 thank you.

**Comment by aeiras** [comment]
![N L 6210 MICROPROFILE FRONT](https://user-images.githubusercontent.com/10731224/145500202-0161a0cb-9b3f-48b3-817d-0192685ca464.jpg)


![N L 6210 MICROPROFILE BACK](https://user-images.githubusercontent.com/10731224/145500220-112d495c-f98a-4249-b9e6-c191eb49ae7f.jpg)

**Comment by rstjames** [comment]
Files are updated. You can find them all here:  https://drive.google.com/drive/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg

**Comment by aeiras** [comment]
Special thank you to you @rstjames for utilizing MicroProfilers feedback on this MPWG 2021 shirt. 
Thank you for working internally with the Deluxe Art Team to simplify a great print. :)
