### ISSUE TITLE
Access to MP marketing repository

### ISSUE THREAD

**Issue by nehasardana09** [microprofile/microprofile-marketing#630]
Hi @aeiras, I dont seem to have access to this repository. Can you give me the access?

**Comment by aeiras** [comment]
hola Neha, 

I have re-sent your write access right now. Please look for that email and accept it. 
:) 
![image](https://user-images.githubusercontent.com/10731224/144933294-a531e809-bd98-4b95-ba66-1d8ebea94a0e.png)

**Comment by aeiras** [comment]
I think invite is valid for only a few days, FYI why it didn't work last time. Let's do this!

**Comment by nehasardana09** [comment]
I got the access to the wg repository.

Just to confirm, I still don't have access to edit the wiki here https://github.com/eclipse/microprofile-marketing/wiki but it may be because this is on Eclipse repository. It also reminds me that I had received an invite to add Eclipse as my organization. I don't know if that's the same thing but it didn't give me access to edit the wiki page.

**Comment by nehasardana09** [comment]
Thanks for giving me access @aeiras !!

**Comment by aeiras** [comment]
Neha, 

This repo is part of the formal MP repositories under the 1 Platform. Only Committers have write access as per EF INFRA. 

The MPWG repo you have write access is outside the EF INFRA. It is not limited by committer access. Its goal is to allow anyone active in the community to do stuff, such improving the documentation etc that is needed under the Working Group. 

The Steward Onboarding wiki belongs under the MPWG, not just marketing repo. :) 

I hope this is helpful. 
Oh, and there is no need for you to submit a PR with the Stewards Onboarding document. The review has been done so beautifully. Just added and then send it to the marketing forum closing that git issue :)

**Comment by aeiras** [comment]
Neha, 

This repo is part of the formal MP repositories under the 1 Platform. Only Committers have write access as per EF INFRA. 

The MPWG repo you have write access is outside the EF INFRA. It is not limited by committer access. Its goal is to allow anyone active in the community to do stuff, such improving the documentation etc that is needed under the Working Group. 

The Steward Onboarding wiki belongs under the MPWG, not just marketing repo. :) 

I hope this is helpful. 
Oh, and there is no need for you to submit a PR with the Stewards Onboarding document. The review has been done so beautifully. Just added and then send it to the marketing forum closing that git issue :)

**Comment by nehasardana09** [comment]
Thanks for confirming. Will do it accordingly. Thanks for help @aeiras!!

**Comment by caitmm43** [comment]
It sounds like all is resolved :)  @nsardana-bny, can this ticket be closed?

**Comment by nehasardana09** [comment]
I got the access. Yes we can close it.
