### ISSUE TITLE
Error in Legend of MicroProfile 5.0 API Diagram

### ISSUE THREAD

**Issue by mpredli01** [microprofile/microprofile-marketing#634]
In the most recent [blog post](https://microprofile.io/2021/12/07/microprofile-5-0-release/) announcing MicroProfile 5.0, the legend at the bottom of the diagram incorrectly states "_No change from last release (MicroProfile 5.0)_."  This should obviously have MicroProfile 4.1 as the last release.

**Comment by TetianaFTV** [comment]
Thanks for noticing.
I've changed the image in the article and also edited this in [release presentation](https://docs.google.com/presentation/d/1PfXEOJzy8v2kGRudvknPox5elRasewv3MBeV0P4Rk6M/edit#slide=id.ga6bdad56ea_0_7)

**Comment by aeiras** [comment]
Hey @mpredli01, 

End of the year and vacations almost here for all of us, yeayy. 
I am wondering if you will be able to write an InfoQ MP.5? 
If you do, (no pressure) my recommendation is for you to get direct quotes from Emerson, Edwin and Emily that were the 3 technical Stewards.  
If you do push it this decemeber, remember to  submit a ticket with the blog link and MP media will push it (easy if you do it this week) most of us will be out after the 17th. Crossposting that blog to the MP blog highly recommended. 

Questions, shoot and thanks to you and Tetiana for being fantastic!

**Comment by mpredli01** [comment]
Thanks @TetianaFTV for addressing this so fast!

Hola @aeiras ... I have MP 5.0 on our news JIRA, and it will most likely be me who writes it, but I'm not sure I can get it done before 12/17.  I did, however, mention MP 5.0 in the weekly roundup that went live this morning.

**Comment by aeiras** [comment]
YOU are amazing, Mike! 

Please do not rush with that blog. 
Do your thing and protect your Holiday time. Once you get it out, submit a ticket and crosspost it. MP 5 announcement blog is being written in Spanish by Emerson, the plan is to push English and Spanish versions for Q1 2022, up until next MP release.   With that, we have time to add valuable noise around the release. Glad you and infoQ are part of it. 

--- this ticket can be closed if you are ok with Tetiana's fixes, Mike! 

Abrazos,

**Comment by mpredli01** [comment]
Hola @aeiras and @TetianaFTV:

Yes, this ticket can be closed.  Thanks again for the fast response!

Mike.
