### ISSUE TITLE
[General: Mktg-Call Steward] Caitlin & Amelia - January 2022 Co-Stewards 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#635]
MicroProfilers are welcomed to use this ticket to communicate with us on anything MP in all January that doesn't belong to its own git ticket. 
MicroProfilers' proactive feedback on Steward work is always welcomed & appreciated. Proactive feedback is preferred as well! :) 

Caitlin and I will use this ticket to communicate on January MP stuff as well!

**Comment by aeiras** [comment]
@caitmm43, 
Thanks to you, the MP calendar for mktg has been updated with 2022 minutes link. Ideally, once you and Neha are done converting the Stewards' onboarding into the wiki, that document can be integrated into the calendar as well. :) Thank you for being amazing at populating Jan 17th 2022 agenda + more. So fun! 

![image](https://user-images.githubusercontent.com/10731224/145902827-2d3f7112-24ff-4918-ad9e-b1c8b4ebcead.png)

**Comment by aeiras** [comment]
@@caitmm43,

Thank you for being such a fantastic Steward and reviving all open tickets promptly. 

I have commented in all relevant items.

**Comment by aeiras** [comment]
Caitlin, 

I had a wonderful time onboarding you into MP. Thanks for the opportunity. See you rocking it and enabling others to do what you have learned in the past 2 months!

**Comment by caitmm43** [comment]
I did too, thank you for the invitation to join this amazing group and for being amazing throughout onboarding!
