### ISSUE TITLE
[Website Main page]  Suggestions with MP 5.0 Release and Onwards

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#636]
@TetianaFTV & @rstjames, 

Brainstorming via this ticket and including you two as the ones to update the website on anything Releases. 

![image](https://user-images.githubusercontent.com/10731224/146064999-b2e1a73c-cdb9-4f4a-8301-3adba214b770.png)

**Issues**

1. The card lost the mention and link to the past release. Can we bring it back ?

**Suggested Additions:**

1. Thanks to @emecas, the MP 5.0 Spanish presentation is almost ready for import to the website. We ought to add it here.  once is ready. StandBy. Emerson, please pull via the other ticket the action. :) 
2.  The blog (english and Spanish) could be added here too. Double the sharing seems smart and allows for lazy browsing where the card provides everything on MP 5.0. What do you think Ryan and Tetiana? Spanish version will be published as soon as the presentation is completed and will be pushed via media, the same amounts as the english versions up until end of Feb 2022 when next release is planned. 

Thanks for brainstorming with me on this. 👍

**Comment by TetianaFTV** [comment]
> The card lost the mention and link to the past release. Can we bring it back ?

added

> Thanks to @emecas, the MP 5.0 Spanish presentation is almost ready for import to the website. We ought to add it here. once is ready. StandBy. Emerson, please pull via the other ticket the action. :)

the link to folder with both English and Spanish version of presentation and blog article is already placed at the website here https://microprofile.io/resources/#presentation

at home page (same as previous time) we have a direct link to English presentation only, 
so basically we don't need to make any changes at the site when Spanish content is ready, just spread it via social media

**Comment by aeiras** [comment]
Tetiana, 

Thank you for promptly adding 4.1 :) 
The remainder of the Resources tab under presentation was needed. thank you, completely forgot that we have chosen to spread the releases across the website. 
I think with the new Implementation page that deals directly with compatibility this will be fixed. :) 

What about the announcement blog under the card on main pain?  Valuable?

**Comment by TetianaFTV** [comment]
> What about the announcement blog under the card on main pain? Valuable?

not sure I understand what you mean by this

**Comment by aeiras** [comment]
@TetianaFTV, 

please disregard. Via this  https://github.com/eclipse/microprofile/issues/239#issuecomment-993944867
we have updated:
-  landing MP. 5 description to include the announcement blog link. 
- release guidelines steps wiki
- release gudiliens git issue check list. 

I think it is enough :) 
Thank you for the follow up. I will close ticket.
