### ISSUE TITLE
[website] Update MP.com home page logos

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#637]
I believe the logos on the MP.com need to be updated. Please can we discuss what logos need to be added and taken away
![Screen Shot 2021-12-15 at 11 43 04 AM](https://user-images.githubusercontent.com/12132146/146238860-877e4cfc-3492-40d8-ab00-e03a1f32fb41.png)

**Comment by caitmm43** [comment]
@rstjames Is this still in progress?  If so, what is needed next?  Please add your comments here and update the minutes with a summary.  Thank you!  :)

**Comment by aeiras** [comment]
+ 1 to remove the launch logos, @rstjames. 

Let's add this ticket to this Monday's call under priority topics. Thank you for bringing it to our attention.

**Comment by rstjames** [comment]
@aeiras any update on this?

**Comment by cesarhernandezgt** [comment]
During today's Community call, the call out about updates on the logos from companies and organizations that are no longer working group members was raised. 
Notice that there is a spreadsheet to keep track of this: https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=1486862268

**Comment by rstjames** [comment]
Updated on the home page 
<img width="1362" alt="Screenshot 2022-08-01 at 16 01 21" src="https://user-images.githubusercontent.com/12132146/182165177-f3638d5c-9d4c-4bd0-aedc-57514c5ef31e.png">
