### ISSUE TITLE
Please review New Blog Post - "Build your MicroProfile apps quickly with Boost"

### ISSUE THREAD

**Issue by scottkurz** [microprofile/microprofile-marketing#64]
https://microprofile.io/wp-admin/post.php?post=6197&action=edit

Sorry, first time posting on this blog plus not too familiar with WordPress, and I didn't do anything for steps 5, 6 [here](https://github.com/microprofile/wpsite) for **Feature Image** or **Page Header Image**, though I did link to the YouTube recording of the MP Hangouts demo.

Would be happy to incorporate any suggestions.

Thank you !

**Comment by aeiras** [comment]
@scottkurz formidable turarond on blog introducing via writing Boost!:)

Recomemnded feedback:

- After the Boost Vision, how about adding a 3rd paragrah that introduces HOW the Boost your demo presentation on 4/16 call (leaving that fact for the end of the blog under Learn More is not efficient)
The blog's value is not only to introduce Boost but actually tell us the steps that get to you & team explaining how Boost came to be. 

- Maybe add the fun fact as to how it got its name.   I think that was fun and part of Boost history as it tells about  its creators the. 

Mind you, you & team -- the individuals  that are braiding Boost are AS important AS the code behind Boost. Simply  introducing yourselves  ought to be an  the extension of the Boost blog, 

- Tell us under Learn More the steps your team must own, as stated on the MP call:)

1. You will send an email to the MP forum creating a healthy google thread 2) a Repo sandbox will be created, after that forum msg arrives,  for the code to be moved to the MP repo to welcome the Contributors to participate in the prototype. 
3... etc... :)

 Boost is not yet part of MP extensions, let’s state it  clearly in the blog. 

Looking forward to 2nd draft and wonderful first draft to start with. Impressed!

**Comment by scottkurz** [comment]
Thx Amelia, for the supportive words and the detailed suggestions.    I tried to incorporate each of them, including adding some personality at the end 🎉 

One thing I wasn't sure of was what you meant exactly by: 

> adding a 3rd paragrah that introduces HOW the Boost your demo presentation on 4/16 call (leaving that fact for the end of the blog under Learn More is not efficient)....

I thought maybe you meant to link the demo video inline, which is what I did.

Would be happy to make other suggestions.

Thank you for reviewing !
Scott

**Comment by scottkurz** [comment]
I threw in my quick links to Twitter, GitHub , LinkedIn... if there's a better way to do this to fit in, like putting it on the Eclipse profile, I don't mind changing...just wanted to have something out there.  Thx again.

**Comment by aeiras** [comment]
@scottkurz Boost blog is published, fantastic adjustments! 
[MP twitted ](https://twitter.com/MicroProfileIO/status/1118991293697277952)too :) 
Please push it via your channels 👍 

If you feel like you want to do 2 things extra, not requirement per say yet still nice to add:

- add a Post Header Image by maybe just taking a screen shot of your choosing from the demo. I am lazy, so I would do that if I were you. Easy, effective and exactly the point of the blog. 

- add your pic as the author

own your ticket by closing it! just fun

**Comment by scottkurz** [comment]
Thx @aeiras for the review, the publishing, and the other suggestions (of adding a pic and a Post Header image). 

Sorry to have to ask, but how would I go about doing that? 

Would I click the [duplicate this](https://microprofile.io/wp-admin/admin.php?action=dt_duplicate_post_as_draft&post=6197&nonce=70dfe2355c) link, to create a new draft, and then submit it for review?   (Assuming you have a way to publish over the original).

If it's not too much work for you, I'd give it a try.

Thanks

**Comment by aeiras** [comment]
Happy Monday Scott @scottkurz, 

As the author of the blog, you can adjut it as you see fit without having to duplicate. Once that is done, you can tell us via this issue and we can "refresh" the blog with the updates.
