### ISSUE TITLE
[General] Adding a New Wordpress Admin

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#640]
@nsardana-bny opening a separate ticket for tracing.  I've added your info to the admin list for wordpress.  Please confirm here when you are successfully logged in to close this ticket.  Thank you! :)

**Comment by nehasardana09** [comment]
Thanks @caitmm43! I have got access to MP WP account. It looks like I may not be Admin. Not sure which role is assigned to me but I am in! We can close this ticket. Thanks!

**Comment by aeiras** [comment]
@nsardana-bny & @caitmm43- Happy and healthy 2022! 

Neha, your access needs to be marked as an Admin as you are invited to help with future Contributors' access, reviews, publications + on special occasions when the opportunity presents itself, to add a new trusted Admin for MP WordPress.

**Comment by caitmm43** [comment]
@aeiras @nsardana-bny 

I see.. Neha, I added you as a user but left your role type defined as "contributor."  I have now changed it to "administrator."

**Comment by caitmm43** [comment]
@neha I'm starting a thread to collect info for a Word Press How-To Wiki.  As you get started, please drop any questions or observations into #642.  It can be a temporary home base for learnings & tips, and a place to reach out for more info as we go through it together.  New eyes notice new things :)
