### ISSUE TITLE
MP Publication Correction: Jrebel Blog by Pavel Fol

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#641]
Hey @caitmm43, 

I have completed MP publication corrections many times before with diverse media partners. 
I would love for you to have the opportunity to do it this December. Can you contact Pavel at the JRebel team and request that the article be corrected to drop the Eclipse from the MicroProfile name?

Background for you:

- MP was launched in June 2016 with its name, MicroProfile. 
When the community decided to move to the foundation, MP had to add the Eclipse to the project name. 
-- in 2020, MP was forced to become a working group to deal with its IP gaps. By doing so, it got to drop the Eclipse from its name. The Charter and the project trademarks are MicroProfile. https://www.eclipse.org/org/workinggroups/microprofile-charter.php

The current article violates the project's registered marks, and as such, it must be corrected ASAP. 
 https://www.jrebel.com/blog/eclipse-microprofile?

Questions shoot and thank you for considering this task. If you own it, it needs to have its own git issue. While your communications with Pavel will be private, the ticket stands as public tracing for that work educating a media valuable partner. :)

_Originally posted by @aeiras in https://github.com/eclipse/microprofile-marketing/issues/609#issuecomment-992968366_

**Comment by caitmm43** [comment]
Reached out to Pavel via LinkedIn & Twitter on Dec. 21st, will comment here with updates / resolution.

**Comment by caitmm43** [comment]
Eclipse has been dropped from the Microprofile name in all text.  

@aeiras Is this sufficiently resolved?

See screenshot: 
![Screen Shot 2022-01-07 at 7 47 36 PM](https://user-images.githubusercontent.com/25733252/148624484-8a3744b6-3ad9-4a24-be0a-cfed2e5d6fa5.png)

**Comment by aeiras** [comment]
@caitmm43, 

The article reads great. Fantastic job. 

The author is most welcome to crosspost the blog to MP Wordpress now that the content is correct? Up to you to invite him to do so. 

Super fun, thank YOU for rocking it!

**Comment by caitmm43** [comment]
Sweet.  Invited!   And no prob.
