### ISSUE TITLE
[Documentation] How To Wiki for Word Press

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#642]
@aeiras You mentioned a need for documentation around Word Press Processes.  I want to prioritize helping Neha with the Onboarding Wiki, however I am happy to take that on as a "next" project.  Opening this thread to kick it off and begin collecting info.  

What documentation exists right now?  If you know of any links or community knowledge, please drop it into this thread.  Thank you!

**Comment by caitmm43** [comment]
**Accumulated Knowledge:**
Admin = invited to help with future Contributors' access, reviews, publications + on special occasions when the opportunity presents itself, to add a new trusted Admin for MP WordPress (source: @aeiras)

> This is the quick how to add a new content contributor the the website so that that person can add content (video, sessions, blogs, workshops, etc) for MP review and publication as listed in the website under Blog tab https://microprofile.io/blog/
> 
> 1. log into WP
> 2. on the left hand side, find Users at the button. 
> 3. go to the top of Users and Add New
> 4. https://microprofile.io/wp-admin/user-new.php
> 5. fill out the form below as follows (see pic, below):
> 
> ![image](https://user-images.githubusercontent.com/25733252/148622706-e5d05f6e-d394-44ed-918a-307d9917d278.png)
> 
> - Username is first and last name (2 words) separated by a -  (example: First-Last)
> - website is never entered
> - role is always Contributor, no exceptions. 
> - click Add new users and to close that git ticket you can share a screen shoot of the contributor, example:
> 
> The [Trusted INFRA MicroProfilers](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit?usp=gmail#gid=1028975568) spreadsheet must be adjusted if anyone gets added to any tool. 
> 
> Once an individual accepts Administrator's access, it is the responsibility of the person who adds them to update the above spreadsheet. 
> 
> New admins must be documented in separate tickets for tracing and notifications.
(source: @aeiras)


**Helpful Links:**
https://github.com/microprofile/wpsite

**Comment by caitmm43** [comment]
Note to self / future admins: default role is contributor unless otherwise noted & approved.  If noted and approved, special access is good!  Check first.

**Comment by aeiras** [comment]
Hey @caitmm43, 

Wonderful ticket. 
I think the task requires its own  wiki that we can link to the Become a Contributor wiki. 

MPWG repo ought  to be used for such documentation. 
Caitlin, it is so healthy to see the documentation within the ticket, with pics etc. That shows that this document is a standalone and requires its own space to avoid crowded steps. (thinking of the authors here) 
Simplification works. 

You are truly fantastic!

**Comment by aeiras** [comment]
Caitlin, you are an editor in the MPWG repo and can do as you please with the documentation. +1 the above documentation about the process. :)

**Comment by caitmm43** [comment]
@aeiras Awesome!  Thanks for the access.  I'll continue compiling info here in the meantime :) 

**Note to self / future admins:** [MP.io Word Press Admins Access](https://docs.google.com/document/d/1q0Xw4XJcoVq1V5vPWe9KR__WKoGc0e-X5cD3tnBsIKw/edit?usp=sharing)

**Comment by aeiras** [comment]
This seems completed. : )
