### ISSUE TITLE
[MPWG page update] Update Members

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#643]
2 members left the MPWG effective January 1st, 2022. 

- Payara https://www.eclipse.org/lists/microprofile-wg/msg01334.html
- Jelastic https://www.eclipse.org/lists/microprofile-wg/msg01365.html

Remove:

1) logos
2) corporate quotes
3) contributing quotes by employees of the 2 ORGs stay.

**Comment by aeiras** [comment]
@rstjames can you please prioritize this task by this Friday? Thanks!

**Comment by rstjames** [comment]
@aeiras not sure I understand. 
- remove logos (OK)
- remove Corporate quotes (OK )
- contributing quotes by employees of the 2 ORGs stay. (Do not understand this)

**Comment by rstjames** [comment]
These two stay? 
![Screen Shot 2022-01-13 at 1 41 29 PM](https://user-images.githubusercontent.com/12132146/149332233-58d0e367-6416-4447-a8a6-f045823d95b2.png)
![Screen Shot 2022-01-13 at 1 41 21 PM](https://user-images.githubusercontent.com/12132146/149332240-d2a92ecd-2a8e-4524-906e-41ce92dce3a8.png)


Then where are the Corporate Quotes?

**Comment by aeiras** [comment]
Hey Ryan, 

been a while with quotes therefore easy to forget. 
Corporate logos are those that contain the logo of the company & not the picture of the MicroProfile. 

the 2 quotes above need removal. 

I hope this helps. Thanks 🙏

**Comment by rstjames** [comment]
@aeiras yes this helped. Thank you!
