### ISSUE TITLE
[Social Media] 2022 Consecutive media messages

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#644]
CheckList as follows:

----

MP always uses its media to add weekly and monthly reminders about calls, content, initiatives, etc that are a constant in the year. 

The inventory sheets contain the items that need to be placed back into social media
**Timeline** January 24th through Dec 31st. 

**Inventory sheet** https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0

**content review**  "volunteer needed"  as content can always be improved. 
I cannot own 2022 review as I have written all the media pushes since day zero and I believe we can scale it by using years of tracking on public media. 

 @caitmm43 would you like to check this?  It is a January task. :) 

**Design**  @rstjames 

- for design, first we create a few drafts cards (new git issue) that go through careful review. From that,  we pic 1 design and use it for all media in 2022. We prefer constancy and simplicity that matches the MP colors, fonts, etc as shown in the Brand Manual.  

**The how**

- As seen in the inventory sheet, each item requires 1 ticket. 
- a 2022 tab needs to be created and items from the 2021 tab ought to be copied to the new sheet. 
- lines 3 to 24 are a go. 
- calendar calls need to be placed back starting line 27. The MP calendar needs to be used to start all those calls correctly. 
-  the removal of calls not happening in 2021 needs to be deleted from 2022 media. 
- we check if there are items missing that could be added to the general list. 
- the items are stable. More items can be added as needed or relevant. 
-

**Comment by caitmm43** [comment]
@aeiras What's the time commitment?

My two MP projects at the moment are helping Neha update the onboarding wiki (high priority, in my opinion) and creating/updating the WP wiki.  I need to prioritize a client engagement before taking on anything else.   However if this is more urgent, I can boot the WP wiki to Feb.

**Comment by aeiras** [comment]
@caitmm43, 

Thanks for allowing this follow-up. 
Your commitment should you take to help Ryan with the review is minimal. Ryan and I have been doing the recurring messages for +5years, the work is done. 
The task is a refresh. 

Ryan can create each ticket using the inventory sheet and pull you and me into the ticket if questions arise. 
Usually, the design wording requires review before he schedules it for the year. extra eyes avoid human error. 

Ryan and I usually complete about 3 messages per day, lol :) it takes about 2 weeks (the rest of January) to complete the careful scheduling.   

I hope this clears your valid questions on commitment. You are a supporter of Ryan. He uses 2021 descriptions (if he adjusts them, then he might request review) and is done!  For that review on wording, I would like some else to own it. I wrote all the descriptions so I am biased. :) 

For design help, the general design ought to be created on a single git ticket with many choices that we can tackle before using the 1 design as the it for 2022.  That is not Ryan's sole job but it takes much care and review. Most important item on this project.

**Comment by caitmm43** [comment]
@aeiras Understood, I appreciate you laying it out.  In that case, I'm happy to help.  

@rstjames Feel free to tag me in :)

**Comment by aeiras** [comment]
Great!

Let's start, @@rstjames, can you please use this ticket to Initiave the 2022 design card by provided as usual many versions to allow brainstorming? 

Thanks in advance Ryan for being amazing at the design brainstorming session! :) 
Once 1 design is selected, you can start using the spreadsheet to create new tickets for all the 30 or so media messages. 
We got this!

**Comment by rstjames** [comment]
@caitmm43 @aeiras I am a bit confused. Do you want a couple of suggestions for changing the images for all social media posts? 

These are all the images I have created that need to be connected to reminders throughout the year. I updated the designs a bit last year putting connecting nodes overlay. 

![Screen Shot 2022-01-26 at 10 41 29 AM](https://user-images.githubusercontent.com/12132146/151139672-0f6bc1fe-dc87-421b-ab3d-d76a26c718de.png)

<img width="359" alt="Screen Shot 2022-01-26 at 10 36 35 AM" src="https://user-images.githubusercontent.com/12132146/151139255-a44afff5-2ab8-46b1-b73a-9fef8e25d2cf.png">

What are everyone's thoughts? We are looking for a completely new look? 

If so this could be weeks of work not including all scheduling.

**Comment by rstjames** [comment]
A new idea for the visual

<img width="881" alt="Screen Shot 2022-01-26 at 5 37 51 PM" src="https://user-images.githubusercontent.com/12132146/151206541-513f66da-a328-4573-a6cb-5d032059140a.png">

**Comment by aeiras** [comment]
> @caitmm43 @aeiras I am a bit confused. Do you want a couple of suggestions for changing the images for all social media posts?
> 
> These are all the images I have created that need to be connected to reminders throughout the year. I updated the designs a bit last year, putting connecting nodes overlay.
> 
> ![Screen Shot 2022-01-26 at 10 41 29 AM](https://user-images.githubusercontent.com/12132146/151139672-0f6bc1fe-dc87-421b-ab3d-d76a26c718de.png)
> 
> <img alt="Screen Shot 2022-01-26 at 10 36 35 AM" width="359" src="https://user-images.githubusercontent.com/12132146/151139255-a44afff5-2ab8-46b1-b73a-9fef8e25d2cf.png">
> 
> What are everyone's thoughts? We are looking for a completely new look?
> 
> If so this could be weeks of work not including all schedules.

Hola Ryan, 

Yes, ideally, we always refresh the general image before setting the year on the media schedule. 
I like the card we have about Participation and we should extend it to all calls. We could use the new word "maybe - Contribute in different languages" for such a card.  

> *We are looking for a completely new look?  - RSJ*

The refresh is not focused on changing everything on the recurring card messages. Just the background at the very minimum. 

Once we get the general card to use, either you or I create a git issue for each item and go from there as usual.

**Comment by aeiras** [comment]
> A new idea for the visual
> 
> <img alt="Screen Shot 2022-01-26 at 5 37 51 PM" width="881" src="https://user-images.githubusercontent.com/12132146/151206541-513f66da-a328-4573-a6cb-5d032059140a.png">

Good direction, Ryan.

I like 

1. including MP io to the card
2. including Open Source multiple times 

The background image should change to something similar that says "collaboration." 

Can you create a new design with the same message to keep it comparable yet add:

-  lighter background
- if it is a call, how about adding something that looks like a calendar, for example. 
- 
We need to get one card to be good to tackle all other pieces via its tickets. 

Thank you for always being amazing at this detailed yet necessary task Ryan.

**Comment by rstjames** [comment]
The image is filler. All images will fit the topic and the base elements would stay on each post.

**Comment by rstjames** [comment]
here is a light version. WIth using elements from the logo. 
![MP-SM-branding-v2](https://user-images.githubusercontent.com/12132146/151327796-e13d98d6-bbad-431a-98a3-a9bd1c362b86.png)

**Comment by aeiras** [comment]
I like it @rstjames. Ideas focus design is a pretty sweet card and it marks a slight change in 2021 design. A huge plus on showing the change. 

My only feedback will be to maybe use a picture from MicroProfilers' calls as found in the drive. :) 

Really good 2 choices. 

Please be ready to show and tell next Monday. If anything else comes to your mind with other choices from now to Monday, please also add them to this ticket to prepare for that chat.

**Comment by aeiras** [comment]
Ok, as discussed and agreed on today's call, I will create one ticket for each item found on the [2022 inventory tab](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=31174810). 
Ryan will work via each ticket to request feedback, etc. 

[2022 Design Cards PSD files](https://drive.google.com/drive/u/0/folders/1SnvhAEzjMiUZOr9kWZ5BSt2ZADcd5GA0)
Please Ryan drop all new files to the 2022 folder. :) 

Traditions! Thanks, @rstjames, for helping on this yearly task!

**Comment by aeiras** [comment]
@rstjames update from this week's community call relates to the 2022 consecutive media schedule. 

**For MP calls**

- No calls scheduled after Dec 16th. 

**general messages**

- should be outgoing after Dec 16th for common messages

---

Please acknowledge the 2 points as not being aware of it will create issues with unnecessary media that require deletions and adds media debt and noise.  Thank you!

**Comment by caitmm43** [comment]
@rstjames These images are really nice.  I'll begin reviewing the text for each post in the other tickets and share a thumbs-up or feedback as needed.  Please tag me if other input is needed.

**Comment by caitmm43** [comment]
All done!  Retrospectively, I'm realizing that not all of the links are shortened with bit.ly.  Is that purposeful?
