### ISSUE TITLE
[MPWG Page]  2022 Project Plan and Budget import

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#645]
Hola John, @jclingan,  

First, can you please import the approved budget and program plan into the drive? https://drive.google.com/drive/folders/14Rrk5W3caBexVS3oexRM1bSKAZL8rapA  Thank you!

John, once the 2 documents are there, we will pull in @rstjames to update the links. 

Ryan, thank you for your help on the updating of the yearly documents before we can push them over media. 

Aside from the Program & budget links, we also need to add the budget forecast. 
https://docs.google.com/spreadsheets/d/100jj5LL0VLZIChrDmptFSRuCau5MKyCkW90QSlDEfW0/edit#gid=1728036894

Same as last year. 

Thanks you two,

**Comment by aeiras** [comment]
Notes are written in the forecast budget as the budget needs to be updated to reflect 2022 Membership. FYI on the comments on that document that is fluid for MPWG awareness.

**Comment by caitmm43** [comment]
@jclingan @rstjames @aeiras

Any update on this?  Please add comments here and update the minutes with a summary accordingly.  Thank you!  :)

**Comment by aeiras** [comment]
thank you, @caitmm43!

The program plan was delivered on January 14th back to the MPWG by the EMO after the EF Board of Director approved it.  The budget is still pending before we can complete the exports of the 3 documents.

**Comment by jclingan** [comment]
Done.
