### ISSUE TITLE
[Logo] Create a community-owned compatibility logo

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#646]
Since we have decided not to use EF trademark programme, it means the previous designed compatibility logos need to be redone and rebrand as a community-owned compatibility logo.

**Comment by aeiras** [comment]
@Emily-Jiang lets close this ticket. Scott already started a great issue on this that has the information. 
Please refer to https://github.com/microprofile/microprofile-wg/issues/107. Thanks!
