### ISSUE TITLE
Content not readable on microprofile.io home page

### ISSUE THREAD

**Issue by rsoika** [microprofile/microprofile-marketing#648]
I want to ask to reopen the issue #341 as it is still a problem:

![image](https://user-images.githubusercontent.com/1339124/151580103-b09098c8-014f-4f7c-a877-9d72346813ca.png)

Should look like this:

![image](https://user-images.githubusercontent.com/1339124/151580207-397d82e4-c6f5-4a8e-b128-61452b1c2e1a.png)

Its still a problem with the web site template engine behind.

**Comment by Emily-Jiang** [comment]
I will move this microprofile-site repo and start the collaboration with @cesarhernandezgt and Summers.

**Comment by aeiras** [comment]
Thank you, Emily! 

Looking forward to that discussion on new repo!

**Comment by Emily-Jiang** [comment]
@rsoika a few of us worked together on the issues you created. For the time being, the style issue was fixed. please take a look at the projects site to verify. Please follow microprofile/microprofile-site#97 for more info.

**Comment by rsoika** [comment]
@Emily-Jiang yes great! I have followed the discussion and checked already the pages which are now working great. I think this style issue was really a important fix!

**Comment by rsoika** [comment]
I want to mention one more thing which is now really more marketing than an technical issue: 
On the home page there are these big bubbles pointing to the main features:

![image](https://user-images.githubusercontent.com/1339124/161298977-a4448df4-81f3-4528-8d68-63cda5e22e76.png)

When you click on such a bubble you will be redirected to a Github Release page which shows the source of the spec and how to add a dependency. For example for microprofile-config this is the page:

https://github.com/eclipse/microprofile-config/releases/tag/3.0

Would it be not more useful if the link points to the corresponding project page on the same site:

https://microprofile.io/project/eclipse/microprofile-config

**Comment by Emily-Jiang** [comment]
@rsoika the reason to point to the release page is that the tag contains the corresponding information for that release.. 
https://microprofile.io/project/eclipse/microprofile-config holds the latest info, which might be related to that particular version of the spec.
