### ISSUE TITLE
[Social Media - Consecutive 2022] Steering Committee	Calls

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#649]
**Twitter description**
#MicroProfileSteeringCommittee: Join & contribute to the 📽️call on 00/00 11 am-12 pm PDT https://bit.ly/calendar-zoom-minutes🗓️

The #MicroProfileWGCharter https://www.eclipse.org/org/workinggroups/microprofile-charter.php is the baseline for all the discussions & decisions. 

#ByCommunityForCommunity 💛#OpenSource #OSS

**Time:**

11am-12pm PDT

**Schedule:**

- twice per call (1 week before and the day of the call) 

April 12th
July 12th
Oct 11th

**Picture:**

[MicroProfile hangout pictures](https://drive.google.com/drive/u/0/folders/1Xh9jbDOvNzy8UP9zccYVpr8E175L1jz_)

**General**
@rstjames 

- let's add the border elements (Charter 7 pilars) from the Community call 2021 design to the 2022 steering call as well. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/10731224/151870393-e469a317-cff7-4410-9071-3b19f070c910.png">

- can you create a short link for the Charter to something like: MPWGCharter instead of what currently is listed?**

**Comment by aeiras** [comment]
@Emily-Jiang hey!!! Can you please help create a checklist git issue template for this task using the data above?  I will review and put to use as soon as that is created to simplify the recurring task :) Thank you, lots!

**Comment by caitmm43** [comment]
> Twitter description
>#MicroProfileSteeringCommittee: Join & contribute to the 📽️call on 00/00 11 am-12 pm PDT [https://bit.ly/calendar-zoom-minutes🗓️](https://bit.ly/calendar-zoom-minutes%F0%9F%97%93%EF%B8%8F)
>
>The #MicroProfileWGCharter https://www.eclipse.org/org/workinggroups/microprofile-charter.php is the baseline for all the discussions & decisions.
>
>#ByCommunityForCommunity 💛#OpenSource #OSS

This message looks good!

**Comment by rstjames** [comment]
working on this now

**Comment by rstjames** [comment]
![MicroProfile-technical_call-April-2022](https://user-images.githubusercontent.com/12132146/156350994-a5ff9e27-0ef8-4ae4-9bf4-8020ff5296b4.png)
![MicroProfile-technical_call-july-2022](https://user-images.githubusercontent.com/12132146/156351030-27b697d3-62b9-4d22-b807-72a5628df82d.png)
![MicroProfile-technical_call-oct-2022](https://user-images.githubusercontent.com/12132146/156351038-36b772af-e42a-48ea-9576-926a5ac4e84b.png)

**Comment by rstjames** [comment]
all scheduled
