### ISSUE TITLE
Growing Pains Call Tweet reminder before meetup(recurring until ~June 2019)

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#65]
- zoom link/minutes (same location)   [ **to be scheduled by John**]  Thanks Jon! :) 

- [Forum Thread](https://groups.google.com/forum/#!topic/microprofile/bxKDRVrLXHI)

- Growing Pain's[ draft v.01 ](https://docs.google.com/document/d/1iCKAK4eayhkv6A7x3Gl2XQKwAsIaaEQS08p_JC5NXLo/edit#)public EDIT document 

- constant description, _2 different messages_, 1 week before and a day before --  [later to be simple written :)] I will own the msg (Amelia)

- design by @rstjames

**Comment by rstjames** [comment]
@jclingan @kwsutter @aeiras 

Who would like to provide the 2 different tweet message for this? 
After I have this I will create a visual and schedule it all for the year.

**Comment by aeiras** [comment]
me Ryan :) Just slight changes as we have done for the other recurring tweets. 
This particular tweet won't go for the entire year, only half. :) still thinking on the dates.
