### ISSUE TITLE
[MPWG 2022 Budget] Revisit marketing budget

### ISSUE THREAD

**Issue by caitmm43** [microprofile/microprofile-marketing#650]
@aeiras opening this ticket to follow up on the MP Live Hangout Call.  Some adjustments to the marketing budget were brought up, further discussion needed.

**Comment by aeiras** [comment]
Caitlin, 

Thank you for owning the communications on this topic! :) You rock!!! 

https://docs.google.com/spreadsheets/d/100jj5LL0VLZIChrDmptFSRuCau5MKyCkW90QSlDEfW0/edit#gid=1728036894

The forecast budget is the document that helps with budget review & adjustments throughout the year. 
The PDF attached is the budget approved by the Steering Committee to remind members of what it currently is while checking for changes. 

**forecast Tabs adjusted:**

**Total Budget**

1. row 8 needs to be adjusted to match the 12% fee

 **Marketing** 

1. rows 14 & 15 are adjusted (this needs to be discussed by the marketing MicroProfilers)
2. There is no need for a call or to wait for the next call. Via the marketing & WG forums, we can note it. 

The goal is to get feedback to request the EF to adjust the budget using the forecast document after MicroProfilers feedback. 

The marketing budget & total budget are adjusted with my biased recommendations to enable MicroProfilers to provide feedback on money allocation this week, closing feedback by next Tuesday is OK as a deadline. What do you think? 

[EMO delivered 11_24_21- Draft MSwagProfile Working Group Budget.pdf](httSwag/github.com/eclipse/microprofile-marketing/files/7981699/EMO.delivered.11_24_21-.Draft.MicroProfile.Working.Group.Budget.pdf)

**Comment by caitmm43** [comment]
@aeiras The PDF linked above is "not found."  Could you resend?

**Comment by aeiras** [comment]
Hola [caitmm43](https://github.com/caitmm43),

Please, always check the External drive that contains the formal MPWG documents. Ask the other WG members if you don't find the information. https://drive.google.com/drive/folders/14Rrk5W3caBexVS3oexRM1bSKAZL8rapA

Can you please tackle this task by the end of tomorrow, Wed? Do let me know if you cannot send the emails to both the Mktg and MPWG forums, and I will help. :) Thank you!

FYI: I see that next week, MP has its 1st 2022 Steering Cmtee and budget is a topic for the call. @jclingan sent this msg today :) https://groups.google.com/g/microprofile/c/m4byQ63D_eY

**Comment by caitmm43** [comment]
@aeiras Thank you!  

I took a look at both documents.  To my eyes, the numbers seem to already be updated (including row 8).  I'm not familiar with the various categories of the budget or how they interact, and I'm missing the context to make these updates correctly.  Are you available to walk through it over screen share any time tomorrow?  

I'm happy to help with this and similar tasks in the future, but need to get up to speed first.

**Comment by aeiras** [comment]
I could call you today (10-12pm) PDF frame if that works for you, [caitmm43](https://github.com/caitmm43)

**Comment by caitmm43** [comment]
https://groups.google.com/g/microprofile/c/ZEehmUM2hQ0:
![Screen Shot 2022-03-09 at 7 16 42 PM](https://user-images.githubusercontent.com/25733252/157561646-e5a42d24-cc82-46ec-a127-1791f16a4ef5.png)

[EMO delivered 11_24_21- Draft MicroProfile Working Group Budget.pdf](https://github.com/eclipse/microprofile-marketing/files/8219097/EMO.delivered.11_24_21-.Draft.MicroProfile.Working.Group.Budget.pdf)

**Comment by aeiras** [comment]
@jclingan hola John, 

 Can you please add the forum link on the budget topic that Caitlin sent yesterday to the Steering cmtee minutes? 
Or should I use the forum message for such feedback?  Let me know and thanks!

**Comment by aeiras** [comment]
@jclingan, 

Thank you for checking with the EF on the revised budget as stated earlier this week. 

We need the budget to start the expenditures in 2022. :)

**Comment by edbratt** [comment]
@jclingan  will look into this and provide an update this week

**Comment by aeiras** [comment]
EMO message about request dated 4/27:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/10731224/165599393-57ee562f-42b2-44db-8774-e0ccef4cf534.png">
