### ISSUE TITLE
[Promotion - social media call to action] eBook give away

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#652]
Tweet message:

To reward our @MicroProfileIO followers and believers, we are going to give away 15 ebooks ibm.biz@MicroProfileBook. To win one copy, all you need to do is post a selfie with a poster stating "MicroProfile Rocks!".

@aeiras please add Vincent here as I could not tag him somehow.

**Comment by aeiras** [comment]
@vincentmayers

**Comment by aeiras** [comment]
> Tweet message:
> 
> To reward our @MicroProfileIO followers and believers, we are going to give away 15 ebooks ibm.biz@MicroProfileBook. To win one copy, all you need to do is post a selfie with a poster stating "MicroProfile Rocks!".
> 
> @aeiras please add Vincent here as I could not tag him somehow.

good draft @Emily-Jiang.
@@vincentmayers added

**How about**

To thank🙏our #MicroProfileCommunity, @PacktPub & MicroProfile wish to give away 15 ebook copies of Practical Cloud-Native Java Development with MicroProfile 4.1. 

#FirstComeFirstServed💛All you need to do is tweet a selfie of yourself with a poster stating "MicroProfile Rocks!"

--- 

IMO the msg ought to have:

1.  publisher
2. community
3. name of the book (formally stated)
4. parameters of who limited quantities a must on giveaways

**Comment by aeiras** [comment]
@Emily-Jiang once we are happy with the write-up, we ought to share this issue via the discussion to enable approval by the publisher as well :) 365 simple reviews and integration with the Partner is necessary and vital!

**Comment by Emily-Jiang** [comment]
To thank🙏our #MicroProfileCommunity, @packtpub & MicroProfile wish to give away 15 ebook copies of Practical Cloud-Native Java Development with MicroProfile 4.1 ibm.biz/MicroProfileBook

#FirstComeFirstServed💛All you need to do is tweet a selfie of yourself with a poster stating "MicroProfile Rocks!"

**Comment by Emily-Jiang** [comment]
@tenythomas01 please take a look at the above tweet message to see whether you have any comments.

**Comment by tenythomas01** [comment]
Hi Emily,

Hope you're well.

I'm unable to view any tweets. Please find the image below:

[cid:76e55360-d414-46dd-b83c-5af790c32a11]

Can you please share the screenshot of the tweet?


Kind regards,
Teny Thomas

________________________________

**Comment by aeiras** [comment]
> To thank🙏our #MicroProfileCommunity, @packtpub & MicroProfile wish to give away 15 ebook copies of Practical Cloud-Native Java Development with MicroProfile 4.1 ibm.biz/MicroProfileBook
> 
> #FirstComeFirstServed💛All you need to do is tweet a selfie of yourself with a poster stating "MicroProfile Rocks!"

Hola @[tenythomas01](https://github.com/tenythomas01), 

I hope you are starting 2022 healthy! :) 

Above is a draft message of the potential media social we have in mind.  We want to give you the opportunity to review it and provide feedback before publishing it.  Thank you,

**Comment by tenythomas01** [comment]
Hi Amelia,

Hope you're well.

Many thanks for sharing.

The tweet looks good to me. Please go ahead with the book giveaway promotion.


Kind regards,
Teny Thomas

________________________________

**Comment by aeiras** [comment]
We appreciate your prompt review and approval, Teny. 
A true pleasure to collaborate with you. Thank you for working with Emily to communicate with the MicroProfile community via our preferred mediums, your care shows. 

@Emily-Jiang  will continue to keep you updated on the distribution of the 15 e-books as we start the social promotion.  :) Super fun!

**Comment by aeiras** [comment]
> To thank🙏our #MicroProfileCommunity, @packtpub & MicroProfile wish to give away 15 ebook copies of Practical Cloud-Native Java Development with MicroProfile 4.1 ibm.biz/MicroProfileBook
> 
> #FirstComeFirstServed💛All you need to do is tweet a selfie of yourself with a poster stating "MicroProfile Rocks!"

@rstjames, 

A few requests on this task: 

- [x] **Design  Card Creation**

- create a new card for 2022 MP Promotions? 
-  The card will be used for this and other Call to Action via social media to the MicroProfile Community
- Hashtag: #ByCommunityForCommunity  
- The subject title of card: Call to Action

- [ ] **Media Schedule**

- Promotion goes live on **Feb 8th, your AM** - Prague
- 1 message via Hootsuite

- [ ] **Description**

- should have the emojis you see in this message above. :) 

---
Let us know if you encounter issues.

**Comment by Emily-Jiang** [comment]
@rstjames will you be able to produce a design card for this (pls see the above requirement from @aeiras )

**Comment by rstjames** [comment]
@Emily-Jiang
![MicroProfile-book_give_away-2022](https://user-images.githubusercontent.com/12132146/154698175-e4fad807-2523-432b-b4fa-7d62f258181b.png)

**Comment by rstjames** [comment]
Scheduled on Twitter

**Comment by aeiras** [comment]
Hola MicroProfilers, 

This issue ought not to be closed until:

1.  the 15 books are given away. 

I have reopened the issue.

**Comment by aeiras** [comment]
> @Emily-Jiang
> ![MicroProfile-book_give_away-2022](https://user-images.githubusercontent.com/12132146/154698175-e4fad807-2523-432b-b4fa-7d62f258181b.png)

@rstjames, 

How many more tweets are scheduled on this activity?

If at least 1 more, I have design improvements as follows:

- Insert Packt logo into the design. The partner is nowhere visible, we ought to improve partnerships highlights, always via visual as a standard of how we collaborate. 

Questions, shoot and thanks! 

<img width="192" alt="image" src="https://user-images.githubusercontent.com/10731224/157550809-1d243613-7d51-486b-8020-c62fea79e986.png">

**Comment by rstjames** [comment]
it's is going out for 2 more weeks. We still have more scheduling I will try to update it after the others are done.

**Comment by aeiras** [comment]
Is there anything stopping us from adjusting those scheduled media pushes,? @rstjames

**Comment by rstjames** [comment]
Time and other scheduling to do.

**Comment by rstjames** [comment]
updated on hootsuite
