### ISSUE TITLE
[Social Media]2022 Community Call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#654]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

#MicroProfilers' participation ensures the growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. Show up & let your actions show a commitment to the evolution & sustainability of MicroProfile. 

Join: bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
Feb 15th, 11am-12 am PDT
every 2 weeks
until Dec 16th

**media schedule**
day of the meeting - 6hrs before. 

**Design Card**

add the 7 pilars as last year yet include calendar image, etc as provided on this week's mktg call. 

<img width="807" alt="image" src="https://user-images.githubusercontent.com/10731224/152449384-d069d09f-5dde-4ed1-9e90-3fb4909a5bb8.png">

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> #MicroProfilers' participation ensures the growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. Show up & let your actions show a commitment to the evolution & sustainability of MicroProfile.
> 
> Join: bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

**How about:** 
#MicroProfilers' participation ensures the growth & development of a well-governed, vendor-neutral #OpenSource ecosystem. Join us to contribute to the evolution & sustainability of MicroProfile. 🌐♻️
 
Join: bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Comment by rstjames** [comment]
![MicroProfile-community_call-2022](https://user-images.githubusercontent.com/12132146/155982151-c22a3139-3efd-434c-b9b9-6f333445be97.png)

**Comment by rstjames** [comment]
All scheduled for 2022
