### ISSUE TITLE
[Social Media]2022 - Marketing Call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#655]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
Join Today's #MicroProfileMarketingCall & help shine a light on MicroProfile around the world. We need grounded #OSSContributors to brainstorm on new ideas, help simplify messages, create & maintain processes that scale.
https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
Feb 14th, 10-11 am PDT 
every 2 weeks
Until Dec 16th

**Schedule**
day of the meeting- 6 hrs before

**Design Card**

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> Media Description
> Join Today's #MicroProfileMarketingCall & help shine a light on MicroProfile around the world. We need grounded #OSSContributors to brainstorm on new ideas, help simplify messages, create & maintain processes that scale.
> https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

Great messaging.

**Comment by rstjames** [comment]
![MicroProfile-marketing_call-2022](https://user-images.githubusercontent.com/12132146/153902973-525833a6-1c47-4393-b34e-c4339829744c.png)

**Comment by rstjames** [comment]
All scheduled for the 2020
