### ISSUE TITLE
[Social Media]2022 - OpenTelemetry call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#656]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
Join today's #OpenTelemetryCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API. 

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
Weekly
Mondays
15:00 CET

**Schedule**
day of the call- 6 hrs before

**Design Card**
Minimal requirements

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> Join today's #OpenTelemetryCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.
> 
> https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

Media description sounds good.

**Comment by rstjames** [comment]
![MicroProfile-OpenTelemetry-2022](https://user-images.githubusercontent.com/12132146/153902001-85c15cfa-ff49-4bd9-8ffa-01511aae1700.png)

**Comment by Emily-Jiang** [comment]
@rstjames the project has been renamed to MicroProfile Telemetry due to the trademark issue.

**Comment by rstjames** [comment]
![MicroProfile-Telemetry_call-2022](https://user-images.githubusercontent.com/12132146/153922578-efe35ade-4a65-407d-8cf8-4da5e6b137a7.png)

**Comment by rstjames** [comment]
scheduled for 2022
