### ISSUE TITLE
[Social Media]2022 - Technical Calls

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#657]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

#CommunityOverCode: Join today's #TechnicalCall & contribute to #MicroProfile development. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource project. 

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
Tuesdays
Feb 8th 
11am-12 pm PDT

**Schedule**
day of the call- 6hrs before

**Design Card**
Minimal requirements

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> #CommunityOverCode: Join today's #TechnicalCall & contribute to #MicroProfile development. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource project.
> 
> https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

Media Description is good!

**Comment by rstjames** [comment]
![MicroProfile-technical_call-2022](https://user-images.githubusercontent.com/12132146/153904058-1a0fac2a-2967-48a3-8cc0-4d91dc4166e6.png)

**Comment by rstjames** [comment]
![MicroProfile-technical_call-2022](https://user-images.githubusercontent.com/12132146/156355654-d120d41b-e40e-4f03-adca-3870a6505bf3.png)

**Comment by rstjames** [comment]
scheduled for the year
