### ISSUE TITLE
[Social Media]2022- Metrics call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#658]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
Join today's #MetricsCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
Tuesdays, Feb 8th
Weekly
6:30am- 7am PDT (use EU time)
Stop after Dec 16th

**Schedule**
day of the call - 6hrs before. 

**Design Card**
Minimal requirements

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> Join today's #MetricsCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.
> 
> https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

Media Description is good!

**Comment by rstjames** [comment]
![MicroProfile-metrics_call-2022](https://user-images.githubusercontent.com/12132146/153907803-e75ce10a-ea9f-4375-b04f-72d55ed975cf.png)

**Comment by rstjames** [comment]
done
