### ISSUE TITLE
[Social Media]2022 - GraphQL call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#659]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
Join today's #GraphQLCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
First Wednesday of each month
March 2nd

**Schedule**
day of the call- 6hrs before

**Design Card**
Minimal requirements

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> Join today's #GraphQLCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.
> 
> https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

Media Description sounds good!

**Comment by rstjames** [comment]
![MicroProfile-graphql-_call-2022](https://user-images.githubusercontent.com/12132146/153909432-bbe808df-1eee-4d1c-ace9-c23166baeb6d.png)

**Comment by rstjames** [comment]
all set for 2022
