### ISSUE TITLE
[Social Media]2022 - Context Propagation call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#660]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

Join today's #Context PropagationCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity #OSS

**Time**
2nd Thursday of each month
Feb 10th
6:30am- 7:30am PDT (use EU time)

**Schedule**
day of the call- 6 hrs before

**Design Card**
Minimal requirements

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> Join today's #Context PropagationCall to discuss the API's technical direction. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #OpenSource API.
> 
> https://bit.ly/calendar-zoom-minutes
> 
> #ByCommunityForCommunity #OSS

Sounds good! :)

**Comment by rstjames** [comment]
![MicroProfile-Context_Propagation_call-2022](https://user-images.githubusercontent.com/12132146/153910280-49a8bab2-2938-4998-9176-acd8c2fc5127.png)

**Comment by rstjames** [comment]
All set for the year

**Comment by aeiras** [comment]
you are fantastic, Ryan.
