### ISSUE TITLE
[Social Media]2022- CN4J card design for future calls

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#661]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Design Card**

1. MP logo
2. Jakarta Logo

**Notes**
To help with everything

**Comment by rstjames** [comment]
@aeiras Not sure I understand what to do here

**Comment by aeiras** [comment]
MP has a relationship with Jakarta EE. 
We need a card that enables MP to push via social media future CN4J alliance calls & also push the Messaging document that will be scheduled soon in media for 2022.

**Comment by rstjames** [comment]
ok let me know when this information/ content is ready to make this image

**Comment by aeiras** [comment]
Here you go, @rstjames. 

https://docs.google.com/presentation/d/1wVaGJssQKPDSRcgRSE52mmm2Lb55THyUc_dGj7F5SAg/edit#slide=id.gbcfab764b6_0_221

While at it, lets change the main slide when updating to the new card. Too dark and not welcoming. Thanks!

**Comment by aeiras** [comment]
@rstjames why is this ticket still pending?

**Comment by rstjames** [comment]
@aeiras Not sure what you want to say on the social media card. 

![microprofile-jakarta_collaboration](https://user-images.githubusercontent.com/12132146/178447194-f0899f29-d672-436b-a709-e6f857af8413.png)

And have any of these cards been used by anyone?

**Comment by aeiras** [comment]
Hola Ryan, 

We use them for calls that will re-start soon. 

Can you replace the old version of the card to something maybe lighter? The wording is perfect, it works for all stuff for now. Thank you.
