### ISSUE TITLE
[Social Media]2022 - Quotes- Guidelines Submissions

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#662]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
#WordOnTheStreet: Submit your #MicroProfile testimonial & share why you invest your time & resources developing & using the #MicroProfileTechnology. 

http://bit.ly/submit-quote

#ByCommunityForCommunity #SharingIsCaring #OpenSource 

**Time**
1 workday -week
1 wknd day

**Schedule**
twice per month

**Design Card**

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> #WordOnTheStreet: Submit your #MicroProfile testimonial & share why you invest your time & resources developing & using the #MicroProfileTechnology. 
> 
> http://bit.ly/submit-quote
> 
> #ByCommunityForCommunity #SharingIsCaring #OpenSource


**How about**
#WordOnTheStreet: Submit your #MicroProfile testimonial & share why you invest in developing & using the #MicroProfileTechnology. 

📢  bit.ly/submit-quote

#ByCommunityForCommunity #SharingIsCaring #OpenSource

**Comment by rstjames** [comment]
![MicroProfile-testimonial-2022](https://user-images.githubusercontent.com/12132146/154084428-5a03155a-14b3-4abb-9ae1-0b894263d1b9.png)

**Comment by rstjames** [comment]
all set for 2022
