### ISSUE TITLE
[Social Media]2022 - MP<>MP Interviews Series

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#663]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

The MicroProfile community is always on the lookout for new members to join the family. Read the MicroProfilers' interviews that provide valuable input into contributing to #OpenSource and get inspired to join @MicroProfileIO!

https://microprofile.io/category/community/interviews-onboarding/

#ByCommunityForCommunity #OSS

**Schedule**
twice per month 
workday
wknd day

**Design Card**
similar to last year but adjust to match the 2022 design

**Notes**
@rstjames please create a short link for the interview URL. 
This time we will use the category to push the interviews instead of individual blog push.

**Comment by caitmm43** [comment]
> The MicroProfile community is always on the lookout for new members to join the family. Read the MicroProfilers' interviews that provide valuable input into contributing to #OpenSource and get inspired to join @MicroProfileIO!
> 
> https://microprofile.io/category/community/interviews-onboarding/
> 
> #ByCommunityForCommunity #OSS

**How about:**
The MicroProfile community is always on the lookout for new #OpenSource members. We are colleagues and friends, and come from all professions within the tech industry.  Check out these MicroProfilers' interviews and get inspired to join @MicroProfileIO!

https://microprofile.io/category/community/interviews-onboarding/

#ByCommunityForCommunity #OSS

**Comment by rstjames** [comment]
![MicroProfile-interviews-2022](https://user-images.githubusercontent.com/12132146/154087012-41827da4-e9d3-4d30-bae2-a5ce0e41ff8b.png)

**Comment by rstjames** [comment]
scheduled

**Comment by aeiras** [comment]
all the templates are customized for the action, I think it is a wonderful output in social media, Ryan. You are amazing!
