### ISSUE TITLE
[Content Improvement] Prospectus

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#665]
@rstjames as we worked on the 2022 media, I discovered that the Prospectus needs adjustments. 

Thank you in advance for bringing your magic to it. 

https://docs.google.com/presentation/d/1hNZ5sgmLcB76i2xPmNmWXZ9Wx39Otc0YRoj8W68FsE0/edit#slide=id.gc0e8651d90_1_19

1. **page 3** - remove Jelastic's quote
2. **page 4** remove Payara's quote
3. refresh the document to match the 2022 design

**Comment by rstjames** [comment]
Updated
