### ISSUE TITLE
[Social Media] 2022 - MPWG Charter

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#666]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
The MicroProfile Working Group Charter states that it is the #MicroProfileCommunity, who owns the responsibility to collaborate & release #OpenSource specifications, promote, evangelize & market #MicroProfile. 

Learn more: https://bit.ly/3bUh8lN

#ByCommunityForCommunity #OSS

**Schedule**
twice per month, no weekends

**Design Card**
the 7 pillars ought to be included in the new design :) 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/10731224/152456909-519af534-1b76-4873-93f8-9652bc13082f.png">

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> The MicroProfile Working Group Charter states that it is the #MicroProfileCommunity, who owns the responsibility to collaborate & release #OpenSource specifications, promote, evangelize & market #MicroProfile.
> 
> Learn more: https://bit.ly/3bUh8lN
> 
> #ByCommunityForCommunity #OSS

**How about:**
As a working group, the #MicroProfileCommunity owns the responsibility to collaborate & release #OpenSource specifications, promote, evangelize & market #MicroProfile.  

To learn more, take a look at our Charter: https://bit.ly/3bUh8lN

#ByCommunityForCommunity #OSS #GetInvolved

**Comment by rstjames** [comment]
![MicroProfile-charter-2022](https://user-images.githubusercontent.com/12132146/154096532-1a51903f-4a7d-413a-8dd8-0f16d97a841d.png)

**Comment by rstjames** [comment]
All set for the year
