### ISSUE TITLE
[Social Media] 2022  - YouTube recordings

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#667]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

#WalkingTheTalk: The #MicroProfileYoutube Playlists provide years of transparency, open & recorded #MicroProfilers' live hangouts on Community, Technical, Marketing, Steering Committee & APIs matters. 
 
Catch up here https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w/playlists?view=1&sort=lad&flow=grid

#ByCommunityForCommunity #OpenSource

**Schedule**
Frequency per month
1 workday
1 wknd day

**Design Card**

**Notes**
@rstjames,

- can you please create a short link for the playlists
- note that the grid is on latest playlist added (video) 
- avoid adding the link to Home

**Comment by caitmm43** [comment]
> #WalkingTheTalk: The #MicroProfileYoutube Playlists provide years of transparency, open & recorded #MicroProfilers' live hangouts on Community, Technical, Marketing, Steering Committee & APIs matters.
> 
> Catch up here https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w/playlists?view=1&sort=lad&flow=grid
> 
> #ByCommunityForCommunity #OpenSource

Looks great

**Comment by rstjames** [comment]
![MicroProfile-youtube-2022](https://user-images.githubusercontent.com/12132146/154097558-1785ecd5-1db0-4018-9e66-0d5f45de979c.png)

**Comment by rstjames** [comment]
all set for 2022
