### ISSUE TITLE
[Social Media]2022 - Victor @Tuxtor Spanish Videos

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#668]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
#MicroProfileVideotutoriales: ¿Estas iniciando una aplicación con microservicios y @java? ¿Sabes que es MicroProfile? En estos videotutoriales @tuxtor te ayuda a explorar el camino #CloudNative con #Java y #MicroProfile a través de sus diversas implementaciones. 
https://microprofile.io/2021/09/01/videotutoriales-recorriendo-microprofile-en-espanol/
#OpenSource #SharingIsCaring

**Schedule**
twice per month
workday
wknd day
until Dec 31st. 

**Design Card**

a light touch to 2022 card could be awesome to match 2022 style. 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/10731224/152459187-99861f17-3744-4c89-a68b-d15b78864c92.png">

**Notes**
@rstjames : short blog link needed.

**Comment by rstjames** [comment]
![MicroProfile-Spanish_Videos -2022](https://user-images.githubusercontent.com/12132146/154100037-3c052211-91e7-4774-a6e9-fd7bf91367f7.png)

**Comment by rstjames** [comment]
@aeiras the tweet message is too long and not sure how to shorten it in Spanish. It is 315 / 280

**Comment by aeiras** [comment]
[rstjames](https://github.com/rstjames) can you please provide me with the short link? once you do, I will re-write the message to fit. 

gracias,

**Comment by aeiras** [comment]
> ![MicroProfile-Spanish_Videos -2022](https://user-images.githubusercontent.com/12132146/154100037-3c052211-91e7-4774-a6e9-fd7bf91367f7.png)


I like it, can Victor's face be clearer on the card? less dark so that he is highlited?

**Comment by rstjames** [comment]
@aeiras https://bit.ly/mp-en-espanol

**Comment by aeiras** [comment]
_#MicroProfileVideotutoriales: ¿Sabes que es #MicroProfile? En estos videotutoriales #LatinArmada🥋@tuxtor te ayuda a explorar el camino #CloudNative con #Java y @MicroProfileIO a través de sus diversas implementaciones.
https://bit.ly/mp-en-espanol

#SharingIsCaring and is #OpenSource_

@rstjames here you go!

**Comment by rstjames** [comment]
done
