### ISSUE TITLE
[Social Media]2022 - Content Blog Contribution

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#669]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

#MicroProfileCommunity have you shared what you have learned with @MicroProfileIO💛? 
Sharing your #MicroProfile knowledge via videos/tutorials/blogs/ebooks makes you an incredibly caring 🥋individual. 

The #MPBlog awaits your content: https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=Blog&template=Contributing+Blog+Content.md&title=%5BBlog+Contribution%5D+Name+of+blog

#SharingIsCaring #OSS

**Schedule**
twice a month
workday 
wknd day

**Design Card**

**Notes**
add a short link to the URL that is a git issue that connects the contributor to the guidelines on how to contribute.

**Comment by caitmm43** [comment]
> #MicroProfileCommunity have you shared what you have learned with @MicroProfileIO💛?
> Sharing your #MicroProfile knowledge via videos/tutorials/blogs/ebooks makes you an incredibly caring 🥋individual.
> 
> The #MPBlog awaits your content: https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=Blog&template=Contributing+Blog+Content.md&title=%5BBlog+Contribution%5D+Name+of+blog
> 
> #SharingIsCaring #OSS

How about:
#MicroProfileCommunity 💛  Have you shared what you've learned with @MicroProfileIO?
Sharing your #MicroProfile knowledge via videos/tutorials/blogs/ebooks enables our community to grow!  🌱

The #MPBlog awaits your content: https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=Blog&template=Contributing+Blog+Content.md&title=%5BBlog+Contribution%5D+Name+of+blog

#SharingIsCaring #OSS

**Comment by rstjames** [comment]
![MicroProfile-share_content-2022](https://user-images.githubusercontent.com/12132146/158836851-1e312450-7fd7-49bf-a5cc-4b3f1c580d0c.png)

**Comment by aeiras** [comment]
Really like the tagline in the design and Caitlin green leaf :)

**Comment by rstjames** [comment]
Done for the year
