### ISSUE TITLE
MP at JBCNConf

### ISSUE THREAD

**Issue by madsop** [microprofile/microprofile-marketing#67]
Name of the speakers: Mads Opheim and Rustam Mehmandarov
Name of the session: IoT powered by MicroProfile - microservices in practice

**Links**
https://twitter.com/madsopheim
https://twitter.com/rmehmandarov

https://github.com/mehmandarov/microprofile-iot

https://www.jbcnconf.com/2019/infoTalk.html?id=5c44693a9034ae38180b14b2

**Location**
Barcelona, May 27th-28th

**Description:**
We are going to show you what happens when the management lets enterprise Java developers and architects decide how we can control the IoT devices in our new office. While it’s easy to figure out why Microprofile is cool, it’s harder to see how to get in into your project.

By the end of this talk, you will be introduced into the patterns and software in the enterprise world of Java explaining how to build a build a secure, stable, modular, and integrated system on an example of a completely over-engineered IoT solution to control the lights and plant’s well-being in the new office.

Fear not if your system is more complex than controlling light bulbs and plants! This talk will show you how easily you can design a good production-ready Java full-stack system based on the Enterprise stack with Microprofile combined with good continuous deployment infrastructure patterns.

There be code, demos, and (buzzword) dragons.

**Comment by rstjames** [comment]
Sorry I missed this ticket. @madsop can you please write a tweet for your session and then I will create and image and promote it on the MP twitter handle.
