### ISSUE TITLE
[Social Media]2022 - MicroProfile Activities Highlights

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#670]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
#MicroProfileSpeakers: Are you giving a #MicroProfile session? If YES, your talk needs global media🌎 coverage! 

Enable MicroProfile to support you & highlight your MicroProfile activities here: https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=Sessions&template=MicroProfiler+Activity+Announcement.md&title=%5BSocial+Media%5D+Name+of+Activity%5D

 #ByCommunityForCommunity #SharingIscaring #OSS

**Schedule**
twice per month
workday
wknd day

**Design Card**

**Notes**
short link needed @rstjames

**Comment by caitmm43** [comment]
> #MicroProfileSpeakers: Are you giving a #MicroProfile session? If YES, your talk needs global media🌎 coverage!
> 
> Enable MicroProfile to support you & highlight your MicroProfile activities here: https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=Sessions&template=MicroProfiler+Activity+Announcement.md&title=%5BSocial+Media%5D+Name+of+Activity%5D
> 
> #ByCommunityForCommunity #SharingIscaring #OSS

**How about:**
#MicroProfileSpeakers: Are you giving a #MicroProfile talk? If YES, your talk needs global media coverage! 🌎

Enable MicroProfile to support you by highlighting your activities here: https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=Sessions&template=MicroProfiler+Activity+Announcement.md&title=%5BSocial+Media%5D+Name+of+Activity%5D

#ByCommunityForCommunity #SharingIscaring #OSS

**Comment by rstjames** [comment]
All set for the year

#MicroProfileSpeakers: Are you giving a #MicroProfile talk? If YES, your talk needs global media coverage! 🌎
Enable MicroProfile to support you by highlighting your activities here:
https://bit.ly/MP-media-coverage

#ByCommunityForCommunity #SharingIscaring #OSS
![Uploading MicroProfile-sessions-2022.png…]()

**Comment by aeiras** [comment]
@rstjames please add all closed tickets to the agenda minutes to be noted on next week's call. 
April doesn't have a Steward yet so everyone needs to own the tasks.
