### ISSUE TITLE
[Social Media]2022 - New MPWG Member Announcement Card

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#671]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Design Card**
Create a fun card to welcome new members with

1. the position of the ORG logo should be easy to place on the card

**Notes**
To help with everything

**Comment by rstjames** [comment]
![MicroProfile-New_working_group_member-2022](https://user-images.githubusercontent.com/12132146/158834951-da039b38-c9d9-4b47-a282-67cc6b7a8e6d.png)
 template

**Comment by rstjames** [comment]
or 
![MicroProfile-New_working_group_member-v2-2022](https://user-images.githubusercontent.com/12132146/158835569-feb2ac78-b650-4620-ab8a-bcab4e84676b.png)

**Comment by aeiras** [comment]
I voted via little fingers on design card, @rstjames. 
People's graph is great and applicable.

**Comment by rstjames** [comment]
@aeiras "Little fingers"?

**Comment by aeiras** [comment]
here @rstjames 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/10731224/161829197-2b9fb413-e571-42aa-a3be-67031b29f710.png">
 

2nd design.

**Comment by aeiras** [comment]
@rstjames let's add both cards to the drive and close the ticket. Thank you!

**Comment by rstjames** [comment]
the psd with all announcements in one file has been added to the drive.
