### ISSUE TITLE
[Social Media]2022 - Book Push: "Practical Cloud-Native Java Development with MicroProfile

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#672]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**
#MicroProfileBook: Practical Cloud-Native #Java Application Development
with #MicroProfile, a book by #IBMers @emilyfhjiang
@AndrewMcCright @nottycode @david_yk_chan &
user @iwalcorn builds cloud-native applications using @OpenLibertyl0 @Docker @IstioMesh

ibm.biz/MicroProfileBook 

**Schedule**
twice a month
workday
wknd day
until Dec 31st

**Design Card**

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> #MicroProfileBook: Practical Cloud-Native #Java Application Development
> with #MicroProfile, a book by #BMers @emilyfhjiang
> @AndrewMcCright @NottyCode @david_yk_chan &
> user @iwalcorn builds cloud-native applications using @OpenLibertyl0 https://github.com/docker @IstioMesh
> 
> ibm.biz/MicroProfileBook

Are these links related?  https://github.com/docker @IstioMesh 
They seem random/unnecessary without context, but please lmk if I'm missing something.

**How about:**
🚨 #MicroProfileBook: Practical Cloud-Native #Java Application Development
with #MicroProfile, by #BMers @emilyfhjiang, @AndrewMcCright, @NottyCode, @david_yk_chan, & user @iwalcorn, 
builds cloud-native applications using @OpenLibertyl0.

ibm.biz/MicroProfileBook

**Comment by Emily-Jiang** [comment]
Thank you @caitmm43 ! Your version looks better!

**Comment by caitmm43** [comment]
@Emily-Jiang You're welcome!

**Comment by rstjames** [comment]
![MicroProfile-book-2022](https://user-images.githubusercontent.com/12132146/153896877-c470df84-973b-4cce-9197-f48f3ce2272c.png)

**Comment by Emily-Jiang** [comment]
@rstjames the image looks amazing. Can you tweet about it with the following text
🚨 #MicroProfileBook: Practical Cloud-Native #Java Application Development
with #MicroProfile, by #BMers @emilyfhjiang, @AndrewMcCright, @NottyCode, @david_yk_chan, & user @iwalcorn,
builds cloud-native applications using @OpenLibertyl0.

ibm.biz/MicroProfileBook

**Comment by rstjames** [comment]
@Emily-Jiang  some issues: 
- do you mean #BMers  - "IBMers" 
- @iwalcorn doesn't exist

**Comment by aeiras** [comment]
@Emily-Jiang, 

What is the status of the 15 e-books available? 

This ticket is still open, and I see now follow up on the discussion with the partner. :) 

We could adjust the requirements, etc as needed.

**Comment by rstjames** [comment]
@aeiras this ticket is just for the book push. Not the giveaway.  The last tweet goes out for the giveawat on April 13th and the partner logo was already added to the image

As for this ticket. @Emily-Jiang can you please look at my comment from 23 days ago

- do you mean #BMers - "IBMers"
- @iwalcorn doesn't exist

**Comment by Emily-Jiang** [comment]
> @aeiras this ticket is just for the book push. Not the giveaway. The last tweet goes out for the giveawat on April 13th and the partner logo was already added to the image
> 
> As for this ticket. @Emily-Jiang can you please look at my comment from 23 days ago
> 
>     * do you mean #BMers - "IBMers"
> 
>     * @iwalcorn doesn't exist
Here is the new version:
#MicroProfileBook: Practical Cloud-Native #Java Application Development
with #MicroProfile, by @emilyfhjiang, @AndrewMcCright, @NottyCode, @david_yk_chan & @jwalcorn,
builds cloud-native applications using @OpenLibertyl0.

**Comment by rstjames** [comment]
Done, set for the year. 

@Emily-Jiang please be more careful with the tweet your write. YOu have @OpenLibertyl0 written wrong. Correct is @OpenLibertyIO.  Think you put a zero

**Comment by aeiras** [comment]
awesome Ryan and Emily!
