### ISSUE TITLE
[Social Media ] 2022 - MicroProfile Contributors Media Cards

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#673]
@rstjames, 

There is no deadline for this project. 

https://drive.google.com/drive/u/0/folders/1R0ogSBMaipLG10cQk5fGj1ppAZmtrR0F

Based on the lack of usage, cards ought to be updated. 

-  unique in style for each single card

- extra things that are relevant to each contributor activity

etc

**Comment by rstjames** [comment]
@aeiras Sorry, I think we should close this ticket. A lot of effort went in and nobody used it. I am not willing to put that time in again especially after all the scheduling and design done for SM reminders

**Comment by aeiras** [comment]
The cards are in the website and should stay there until further notice then. 

I do agree that lots of attention is always paid to yearly scheduling. That is a new project that will take away from website improvements and we cannot have that. Thanks Ryan for the input.  +1 to closing ticket for now. @rstjames
