### ISSUE TITLE
[Social Media]2022 - Branding Resources

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#674]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Media Description**

#SharingIsCaring: #MicroProfile supports its global🗺️community with Branding Resources & other materials such as Brand Manual, Logos, Colors & Fonts, Speaker Presentation Template, Social Media Cards & much more. 

https://microprofile.io/resources/branding/

#ByCommunityForCommunity #OpenSourceFun

**Schedule**
every week --- 4 times per month 
weekday
wknd day

**Design Card**

**Notes**
To help with everything

**Comment by caitmm43** [comment]
> #SharingIsCaring: #MicroProfile supports its global🗺️community with Branding Resources & other materials such as Brand Manual, Logos, Colors & Fonts, Speaker Presentation Template, Social Media Cards & much more.
> 
> https://microprofile.io/resources/branding/
> 
> #ByCommunityForCommunity #OpenSourceFun

**How about:**
#SharingIsCaring: #MicroProfile supports its global🗺️community with Branding Resources & other materials such as Brand Manual, Logos, Colors & Fonts, Speaker Presentation Template, Social Media Cards & much more.

Visit https://microprofile.io/resources/branding/ to explore & use these tools 🎨🖌

#ByCommunityForCommunity #OpenSourceFun

**Comment by rstjames** [comment]
![MicroProfile-branding-2022](https://user-images.githubusercontent.com/12132146/153896923-e7b05a64-1ced-4d0b-9fb8-fec63da7c5b2.png)

**Comment by rstjames** [comment]
scheduled for 2022
