### ISSUE TITLE
[Social Media]2022 - MP Technical Releases Card

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#675]
**[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=0)**

**Design Card**

**Notes**
@rstjames  this link to https://github.com/eclipse/microprofile-marketing/issues/651 as we have not yet created the Release version for 2022 Releases and we have to. 

Questions, shoot! 

--- 
Please add all the 2022 final designs to the 2022 folderhttps://drive.google.com/drive/u/0/folders/1SnvhAEzjMiUZOr9kWZ5BSt2ZADcd5GA0

**Comment by rstjames** [comment]
@aeiras what is this ticket for?

**Comment by aeiras** [comment]
great question, for when an API achieves a release after steering cmtee votes.

**Comment by aeiras** [comment]
@rstjames, 
A few cards are needed to:

- highlight an implementation when it catches with an MPWG release - for example New Compatible page is populated with diverse implementers at different times, that's good news and media is needed. 
- highlight API's progress while undergoing changes -- How to make this scalable is the brainstorming... 

I hope this helps,

**Comment by rstjames** [comment]
OK, who will make/ fill in this card or report these scenarios so we promote them? I will make a very basic template. Because depending on the topic the image and text would change.

**Comment by aeiras** [comment]
@rstjames, excellent. thank you. 

anyone who has technical releases of any form from Implementations to APIs can submit a git ticket and we can process such requests. I created a template for that git issue so what is needed is already easy to add. Check the "new ticket" to see all the templates and if you see anything missing from the requests, please let me know.

**Comment by rstjames** [comment]
yes, this sounds good. They fill in the ticket with the template and assign it to me .
