### ISSUE TITLE
[website] Keeping past MP releases graphics on the microprofile.io

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#677]
We have a nice graphical representation of the current release at microprofile.io:

![2022-02-09-1644392627_1674x729](https://user-images.githubusercontent.com/9353101/153144646-5397f072-2d89-41f8-9798-0f85f828d0cd.png)

but only for the current release. I find this a nice reference when pointing people to which specifications have been updated in which release so can we maybe keep these graphics also for the past releases?

**Comment by ederks85** [comment]
+1, good suggestion @xstefank

**Comment by Emily-Jiang** [comment]
We should get this to the certification page per release.

**Comment by aeiras** [comment]
+1 [xstefank](https://github.com/xstefank)

@[Emily-Jiang](https://github.com/Emily-Jiang), are you ok with adding this feature to the document we have in place (@rstjames said he would create a new document just for it :))  for the page?

**Comment by rstjames** [comment]
Where would these graphics go? what pages? Right now you can find them on the implementation pages.

**Comment by rstjames** [comment]
@Emily-Jiang @aeiras  please look at my comment above

**Comment by aeiras** [comment]
> @Emily-Jiang @aeiras please look at my comment above

@rstjames, good question, lets's broaden the brainstorming to this Monday's call.  Many places so I cannot zeroed it.

**Comment by Emily-Jiang** [comment]
@rstjames the graph was already present on the individual implementation page (e.g. 5.9 goes [here](https://microprofile.io/compatible/5-0/))

**Comment by Emily-Jiang** [comment]
@xstefank please take a look at the [implementation](https://microprofile.io/compatible/) website, which lists the graphics for the specific release. 4.0 graphics is listed [here](https://microprofile.io/compatible/4-1/). Please close this issue if you are happy with the design.

**Comment by xstefank** [comment]
Thanks, looks great.
