### ISSUE TITLE
[Website] MicroProfile Site Improvement

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#678]
During the calls for MicroProfile Site Improvement,  we have been able to fix a couple of website issues and also start the analysis for website improvements/optimizations. 

My view on this is the following:

- EC2 site was base on Github Pull-Request workflow since all the pages, sections, etc. produced a plain-text site.
-  EC2 site didn't have a proper way to handle blog posts and managing roles among reviewers and authors.
- SEO issues that we still have to carve out from existing ec2 dependency. https://github.com/eclipse/microprofile-marketing/issues/620#issuecomment-978215226
- Ec2 site is based on Elastic Beanstalk, this service is reaching an EOL within AWS ecosystem: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-support-policy.html
- The migration from ec2 to WPEngine/WordPress was accomplished at 90%, and the only two pages in the current website that still requires the REST endpoint from Ec2 are: Contributors and Projects. 
- Personally, I think this is where our main two objectives can be based on a mid-term improvement, but I wanted to obtain Marketing feedback about the opportunity cost of also moving away from WP enginge/WordPress into another technology stack.

**Comment by aeiras** [comment]
Thank you, Cesar, for the update and written tracing for those meetings.

**Comment by dblevins** [comment]
For historical context, we've never migrated anything from EC2 to WordPress or changed any of the technologies that back the website.  I'm not sure what is being referred to when we say "migration was accomplished at 90%".  What we have now is what we've always had with two notes:

 - In 2017, we did migrate our EC2 usage to a new EC2 account dedicated to only MicroProfile, but that's the only migration that has occurred and was a lift-and-shift with no actual changes to the website introduced.
 - We did add start.microprofile.io at one point, but that wasn't a change as much as adding something that didn't exist.

Here's what we have:

 - https://start.microprofile.io runs in OpenShift https://github.com/eclipse/microprofile-starter
 - https://microprofile.io/projects/* and https://microprofile.io/contributors are Groovy+Markdown and was in place shortly after launch
 - All else on https://microprofile.io/ including the blogs is WordPress and always has been

We definitely want to replace the Groovy+Markdown stuff with github pages so we have a site that is served statically and we are not hit by Github rate-limiting issues, yet things are still git based for specification teams to easily maintain.  We've not had any issues with the WordPress portions -- that seems to be the part of the site that works well and is easy to actively maintain.  We also do not have specification/technical people maintaining that portion of the website.

**Comment by dblevins** [comment]
Great to see us writing stuff down from the meetings, btw.  As things progress, let's update this issue from our Program Plan https://github.com/microprofile/microprofile-wg/issues/65

**Comment by cesarhernandezgt** [comment]
Thank you for the information and clarification about the ec2 and WordPress historical relationship @dblevins. 
We will keep the updated on the https://github.com/microprofile/microprofile-wg/issues/65 as we move forward.
