### ISSUE TITLE
[Video calls] MicroProfile Site Improvement sessions

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#679]
Hi @Emily-Jiang @jclingan ,

Can you please upload the working sessions for the MP website improvements to a playlist `website`?

**Comment by aeiras** [comment]
dias @jclingan, 

Can you please help create a Website Playlist under MP youtube? https://www.youtube.com/channel/UC_Uqc8MYFDoCItFIGheMD_w/playlists
I just checked and it doesn't exist yet. thank you.

**Comment by aeiras** [comment]
@cesarhernandezgt we are not using Youtube anymore... 

I will close this ticket while requesting an update on where the Q3 and Q4 recordings are hosted.
