### ISSUE TITLE
[General] Contributors GitHub “Triage” access for Hoyt Summers Pittman(AJUG)

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#681]
Discussed on today's marketing call, [https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access](https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-%E2%80%9CTriage%E2%80%9D-access) will be granted to MicroProfiler :)

Summers GH ID is https://github.com/secondsun associated with MP project contributions.
Please read the wiki on Triage access and improve it via PRs if you see it necessary as you onboard. :) Thank you!

**Comment by aeiras** [comment]
Thank you, Cesar.

MicroProfiler @[secondsun](https://github.com/secondsun) has been granted MP Triage, which is active now :) 

<img width="169" alt="image" src="https://user-images.githubusercontent.com/10731224/162824197-f670a0f8-6cc6-49c0-9616-28a4abcf7dae.png">

**Comment by cesarhernandezgt** [comment]
Thank you @aeiras .
