### ISSUE TITLE
[Website] Resources add : Java In Education 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#683]
During an MP community call (Nov. 2021), I shared the JCP initiative a few of us started working on under the JCP EC group about enhancing the reach of Java in Education.   This project is today a global effort JUG led and supported by the JCP program.  I stated that once ready to share. The resource links ought to be added under the MP Resources page. 

The plan then was to continue improving the resources of the project by gathering global supporters and cases of use, etc. Today, the project has a good standing, and it continues to improve.

**Task:**

Under Resources:
Add Java In Education https://jcp.org/java-in-education

Once this is in the website, we will share it with the MP Community so that MicroProfilers who are members of JUG communities could either share their histories under the Videos section (Edwin already did) or find ways to become involved in the SharingIsCaring initiave.

**Comment by rstjames** [comment]
Updated @aeiras

**Comment by aeiras** [comment]
It looks great, @rstjames 💯
