### ISSUE TITLE
[Website] Add version to the implementations in the implementations pages on microprofile.io

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#685]
In https://microprofile.io/compatible-implementations/4-1/ and https://microprofile.io/compatible-implementations/5-0/ we should list versions of all implementations in the title as more than one version of the same implementation can be certified for the same MP version. See Payara Enterprise (Web Profile) for instance.

To save time, Quarkus version should be 2.7.2.Final - https://github.com/eclipse/microprofile/issues/247.

**Comment by aeiras** [comment]
+1 on improvement of page Martin.

**Comment by aeiras** [comment]
completed.
