### ISSUE TITLE
[INFRA] Swag email creation

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#686]
microprofile-swag@googlegroups.com has been created. 
Email is private so that the project can collect private information to distribute MP swag. 

**Current Admins/Owners are:**

- @Emily-Jiang, who nicely volunteered to be one of the Admins of new email. :)  Please confirm your access have arrived. Thank you!

- Amelia

**Inventory**
The INFRA spreadsheet has been updated with new Swag Tab.

**Comment by aeiras** [comment]
Thank you, @Emily-Jiang for confirming your access to the new infra swag email.

**Comment by JanWesterkamp-iJUG** [comment]
@aeiras , @Emily-Jiang : Is there a way to order a box of swag without using googlegroups?

Our office need to be contacted that they expect a box and additional payment for it - so they need a tracking code and the exact worth of the box (including shipping) to assign budget.

When I try to convince them to add them to a googlegroups, that will probably not work... :-(

**Comment by aeiras** [comment]
> @aeiras , @Emily-Jiang : Is there a way to order a box of swag without using googlegroups?

Of course, Jan. 
The 2 public Google groups won't be used for discussions on MPWG Swag. That would be noisy and increase communication debt.  + any exchanges need to highly private as it might contain personal information. 

> 
> Our office need to be contacted that they expect a box and additional payment for it - so they need a tracking code and the exact worth of the box (including shipping) to assign budget.

This is something that only the Shipping Vendor can share.  Great point about ensuring we get the international shipping numbers so that the Vendor or we send such information to the receivers. 

> 
> When I try to convince them to add them to a googlegroups, that will probably not work... :-(

Nothing to convince.  I think for each shipment, we could rotate a MicroProfiler to provide such information to iJUG. However, we will learn if that works or if it is not scalable.  Do, try, and re-try! 

Abrazos,

**Comment by JanWesterkamp-iJUG** [comment]
@aeiras Good point regarding personal information - the contact details for our organisation are public: https://www.ijug.eu/en/home/ (in the footer)
While my personal contact details are not and need to be protected - if Google is a good choice to hold that private, even if they say so, I would disagree... ;-)
The EF website contains (or should contain) that official contact information (when logged in) of all the members who would like receive a box - or at least the EF staff should have access to it.
But for the Non-EF-Members there need to be a process to share that information of course.
Yes, let's try!
