### ISSUE TITLE
[Swag] MP Stickers for 2021 t-shirt distribution - Costs

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#687]
Today, during the Marketing call, we discussed adding stickers to the global shipment. 

there are 23 Organizations being considered for the 380 shirt allocation so softly covering +100 each is about 3000 stickers. 

StickerMule:
https://www.stickermule.com/custom-stickers

MP Sticker design- Vertical version:
https://drive.google.com/drive/u/0/folders/1gTnf_Op15AWKHZuqRT6EGcT0ESy_YHHc

<img width="238" alt="image" src="https://user-images.githubusercontent.com/10731224/169889004-23f43fa1-a0cc-4b91-939f-9300dea89b41.png">

**Costs:** will use 2022 marketing budget
3000 stickers <img width="315" alt="image" src="https://user-images.githubusercontent.com/10731224/169887429-5e2f5fed-0731-4f0e-bdbf-25ea7ff49601.png">

5000 stickers 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/10731224/169887631-2436fa29-631d-4a20-b812-c5b32446c435.png">

Recommendation:

the price difference from 3000 to 5000 stickers is $202.14.  I recommend 5000 stickers as we can provide JUGs with 200 stickers instead of 100, which will work better on the distribution front for larger communities.

**Comment by aeiras** [comment]
@rstjames, 

Can you please update the design to drop TM instead add R?

Thank you

**Comment by rstjames** [comment]
@aeiras on the google drive the pdf sticker already has R version files
Updated the "source file"

**Comment by aeiras** [comment]
so fast, thank you, Ryan!!! :)

**Comment by Emily-Jiang** [comment]
Let's do this from 2022 budget.
