### ISSUE TITLE
[Swag 2021] Distribution logistics

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#688]
[2021 -Shirt Swag - Distribution Plan - Global](https://docs.google.com/spreadsheets/d/1y3dT8zpBlgO0eJ4TgYx9zVCfzDXx_4l58KQKkd5vp7I/edit#gid=590237288)

**Comment by aeiras** [comment]
minutes by @edbratt from 5/23 meeting:

Process for swag distribution linked to 2021 swag  
[2021-Shirt Swag- Distribution Plan - Global](https://docs.google.com/spreadsheets/d/1y3dT8zpBlgO0eJ4TgYx9zVCfzDXx_4l58KQKkd5vp7I/edit#gid=0)  spreadsheet allocates the 380 shirts, globally. 
[2021 Spend Proposal Swag for JUGs ](https://docs.google.com/spreadsheets/d/1iOTTar3nFXI_yraCmZu4KVBduRPSgD7BDeN1fKZizWk/edit#gid=1242876094) logic sheet behind the $5,000 order. 
[[INFRA] Swag email creation #686](https://github.com/eclipse/microprofile-marketing/issues/686)  swag email created with Emily and Amelia as Admin owners. More MicroProfilers who wished to help with distribution of MP swag are welcomed. 
[Infra email] Contact organizations via private email to see if they would like to get the MP swag (address, phone numbers etc
[Amelia] Find a Vendor who will tackle the shipments. Swag is in Los Angeles. 
Discussed the shirt allocation. Allocation in spreadsheet is good for estimation. Final allocation is limited by number of shirts. 
Should we make 3K stickers to include as hand-out, especially for distribution to JUGs? Allocate from 2022 budget. No one on the meeting objects.  [[Swag] MP Stickers for 2021 t-shirt distribution - Costs #687](https://github.com/eclipse/microprofile-marketing/issues/687) Budget from 2022 will also be used to cover shipping costs of 2021 shirts. Both these budget requests must be approved by a quorum steering committee meeting. We would propose a Steering Committee resolution to cover shipping costs.
We will work on a draft resolution over e-mail and try to finalize it at the next Marketing meeting – then refer it to the Steering committee for a formal vote

**Comment by aeiras** [comment]
[12_7_2021_Deluxe MPWG - 380 Shirts_Invoice23173607.pdf](https://github.com/eclipse/microprofile-marketing/files/8757572/12_7_2021_Deluxe.MPWG.-.380.Shirts_Invoice23173607.pdf)

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/10731224/169892362-33e9cc91-e901-430b-a525-26ca9b19c262.png">

**Comment by aeiras** [comment]
During the Sept 12 Marketing & Sept 13 Community calls, the 2021 logistics were discussed, and it was decided:

 **UPDATE:** 
1. that as part of the swag pilot "distributing swag," MPWG will [distribute to the 2021 MPWG](https://docs.google.com/spreadsheets/d/1wZzuKyniHy1PEuKm2OAZ9laKquyZ0XiscEZb65BHvoE/edit#gid=1903084404) members the 380 printed shirts that the printing Deluxe Vendor is holding since May 2022.  2. 
2. the EF team will provide its contact person who will be in charge of 1) payment to the BSC shipping Vendor, 2) delivering the MPWG members' information to BSC
3. No JUG communities will be contacted due to the major delay on resolving issues with new swag processes.

**Comment by aeiras** [comment]
@emecas, in order to add you to this ticket, you ought to comment :)

**Comment by emecas** [comment]
> @emecas, in order to add you to this ticket, you ought to comment :)

thanks @aeiras  :)

**Comment by aeiras** [comment]
hey @emecas, 

The "logistics" [spreadsheet ](https://docs.google.com/spreadsheets/d/1TuqvDCtvoMTUM-kkW_qVeGS36Z6pX0ty/edit#gid=365241246) was created to facilitate 
[LogisticDRAFT - Swag Allocation - Steering Committee Members.xlsx](https://github.com/eclipse/microprofile-marketing/files/9579715/LogisticDRAFT.-.Swag.Allocation.-.Steering.Committee.Members.xlsx)
each Member sending their information to the EF foundation. 

Paul today via https://www.eclipse.org/lists/microprofile-wg/msg01595.html delivered the EF point of contact.

**Comment by shanda-eclipse** [comment]
@croundy confirmed that the distribution list provided above is final and I have shared it with the supplier.

**Comment by emecas** [comment]
> @croundy confirmed that the distribution list provided above is final and I have shared it with the supplier.

Thanks @shanda-eclipse  , may you confirm that the final distribution list contains Payara's shipping information?

**Comment by shanda-eclipse** [comment]
> Thanks @shanda-eclipse , may you confirm that the final distribution list contains Payara's shipping information?

Yes. Payara's info was included.

**Comment by aeiras** [comment]
Again, all you @emecas :) Kudos!
