### ISSUE TITLE
Change "https://microprofile.io/compatible-implementations/" link to "https://microprofile.io/compatible/"

### ISSUE THREAD

**Issue by dblevins** [microprofile/microprofile-marketing#689]

**Comment by aeiras** [comment]
good follow up as part of today's MP community call :)

**Comment by rstjames** [comment]
@dblevins @aeiras Would "compatible" be updated in the menu too, instead of "implementations"?

**Comment by aeiras** [comment]
Días, Ryan. 

The change is only in the url. Leaving the tab formally named is desired. Thanks for the follow up question 🥋

**Comment by rstjames** [comment]
done :) added a redirect to the old links, incase someone has sent these links out they can still get to the pages correct pages

**Comment by aeiras** [comment]
Thoughtful and smart, kudos!

**Comment by Emily-Jiang** [comment]
> @dblevins @aeiras Would "compatible" be updated in the menu too, instead of "implementations"?

My apologies for missing this conversation in time! I checked this site again. I think the url says `compatible` while the menu says `implementations`, which is very confusing. Can we make it consistent? Either use `compatible` or `implementations` for both url and menu.
I slightly prefer `implmentations`. What do you think @dblevins ?

**Comment by aeiras** [comment]
I prefer Compatible.

**Comment by aeiras** [comment]
> > @dblevins @aeiras Would "compatible" be updated in the menu too, instead of "implementations"?
> 
> My apologies for missing this conversation in time! I checked this site again. I think the url says `compatible` while the menu says `implementations`, which is very confusing. Can we make it consistent? Either use `compatible` or `implementations` for both url and menu. I slightly prefer `implmentations`. What do you think @dblevins ?

really good catch on lack of naming continuity, Emily!

**Comment by aeiras** [comment]
> I prefer Compatible.

@rstjames I haven't seen feedback on this. 

@dblevins used in the subject of his ticket Compatible. Let's name the tab also Compatible instead of Implementations. Thank you.

**Comment by rstjames** [comment]
Updated menu to Compatible
