### ISSUE TITLE
Create a page on how to get compatible implementation listed

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#690]
We need to list the requirements on how to get compatible implementations listed under `microprofile.io/compatible`

**Comment by Emily-Jiang** [comment]
Below is the draft:
How to Get Listed as a Compatible Implementation

To get your product listed on the Implementations page, please follow these steps:

 
    Certification and listing on microprofile.io Implementations pages requirements
        Follow the [MicroProfile TCK process](https://github.com/microprofile/microprofile-wg/blob/main/tckprocess.adoc) to completely run and satisfy all of the requirements of the applicable TCK test

            Publish the TCK results and maintain the public listing of your TCK results for as long as you continue to claim compatibility.

            Email the TCK results to [tck@eclipse.org](mailto:tck@eclipse.org)
        File a [Certification Request](to be done) for the MicroProfile umbrella release 
        If not certifying against umbrella release, file or an individual certification request against a particular MicroProfile specification such as MicroProfile Config.

**Comment by aeiras** [comment]
@Emily-Jiang really great draft. 

How about we place it under MPWG repo wiki?

Feedback on steps:

1. enumerate each line item
2.  task 4 File a Certification... should have the link of the repo that houses that landing request git.
3. same for 4
4. a marketing ticket is required after triggering the implementation to the compatible page. 
5. I recommend we create a checkmark's https://github.com/eclipse/microprofile-marketing/issues/new/choose to help start the process with action item number 1 that lists all the steps clearly.   Doing so was my first suggestion on Ed's feedback about getting added.    Simplicity works, I go as far as suggest that we created the checkitems via a gitticket list and link it to the compatible page and be done.  The wiki is helpful yet it duplicates and adds extra clicks. 

What do you think?

**Comment by cesarhernandezgt** [comment]
This is great proposal, I'm +1 on added in both compatible/ page and also in the Github Issue template as a note for the [certification request](https://github.com/eclipse/microprofile/labels/certification)?

**Comment by Emily-Jiang** [comment]
Updated the [page](https://wiki.eclipse.org/Implementation_Certification_Process)

**Comment by Emily-Jiang** [comment]
>     5. I recommend we create a checkmark's https://github.com/eclipse/microprofile-marketing/issues/new/choose to help start the process with action item number 1 that lists all the steps clearly.   Doing so was my first suggestion on Ed's feedback about getting added.    Simplicity works, I go as far as suggest that we created the checkitems via a gitticket list and link it to the compatible page and be done.  The wiki is helpful yet it duplicates and adds extra clicks.
> 
> 
Good idea! I have created a template [here](https://github.com/eclipse/microprofile-marketing/pull/713). Please review to see whether you have any comments @aeiras . I think I have addressed all of the comments.

**Comment by aeiras** [comment]
Welcome back @Emily-Jiang :) 

The template was reviewed and approved without changes.

**Comment by aeiras** [comment]
> Updated the [page](https://wiki.eclipse.org/Implementation_Certification_Process)

@Emily-Jiang I adjusted a few things in the page during review, please check changes.  Good draft. 

New Compatible Implementations: This needs to be added as a link to the page. 
I also recommend we link MP.io Compatible page to page. https://microprofile.io/compatible/


WDYT?

**Comment by Emily-Jiang** [comment]
> > Updated the [page](https://wiki.eclipse.org/Implementation_Certification_Process)
> 
> @Emily-Jiang I adjusted a few things in the page during review, please check changes. Good draft.
> 
> New Compatible Implementations: This needs to be added as a link to the page. I also recommend we link MP.io Compatible page to page. https://microprofile.io/compatible/
> 
> WDYT?

Yep, in the compatible page, we need to add a sentence "Follow [this](https://wiki.eclipse.org/Implementation_Certification_Process) instruction to get your implementated listed here". I will create a new issue to track that.

**Comment by Emily-Jiang** [comment]
https://github.com/eclipse/microprofile-marketing/issues/714 created to cover the end to end story.

**Comment by Emily-Jiang** [comment]
I think this issue can be closed.

**Comment by aeiras** [comment]
yes! :)
