### ISSUE TITLE
[Blog Contribution] Learn MicroProfile 5.0 and Jakarta EE 9.1 without installing anything

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#691]
**Content copy/edit review (available & optional)
- [x]  [Learn MicroProfile 5.0 and Jakarta EE 9.1 without installing anything](https://microprofile.io/wp-admin/post.php?post=7003&action=edit) (a post hosted on the Open Liberty blog)
 
 **Social Media Description**
 - [ ]  Learn MicroProfile 5.0 and Jakarta EE 9.1 with the Open Liberty cloud-hosted guides so you don’t need to worry about installing prerequisites on your laptop first.
By Gilbert Kwan (https://github.com/gkwan-ibm)

**Comment by Emily-Jiang** [comment]
I reviewed this blog, which is reference to a blog on openliberty.io. Looks good to me! @aeiras please take a look at it.

**Comment by aeiras** [comment]
Hola @lauracowen, 

The blog is exactly what we were waiting for to activate the desired feature under the new MP Compatible page https://microprofile.io/compatible/.    

- The blog is now published as a crosspost blog, kudos on crossposting work, Laura and Emily's wonderful support. It made the review quite efficient and effortless.  I did adjust a few minor things in the title and the tags.    https://microprofile.io/blog/. 
- The blog helps add the content on the Compatible page as part of the Community content under MP 5.0 Release.  Exactly what we were missing. Yeayyy!!!!   https://microprofile.io/compatible/5-0/ 

Thank you and the IBM team for rocking at sharing MP knowledge. 

--- @rstjames 

Can you please us activate the blog as part of MP 5.0 Community content shown at the end of the page https://microprofile.io/compatible/5-0/ ?

You mentioned that you would find a way to add release content if added to MP blog. Here you have it. Please pull us in if you encounter issues via a new ticket highlighting that feature. Thank you!

**Comment by aeiras** [comment]
> **Content copy/edit review (available & optional)
> 
> * [ ]   [Learn MicroProfile 5.0 and Jakarta EE 9.1 without installing anything](https://microprofile.io/wp-admin/post.php?post=7003&action=edit) (a post hosted on the Open Liberty blog)
> 
> **Social Media Description**
> 
> * [ ]   Learn MicroProfile 5.0 and Jakarta EE 9.1 with the Open Liberty cloud-hosted guides so you don’t need to worry about installing prerequisites on your laptop first.
>   By Gilbert Kwan (https://github.com/gkwan-ibm)

Social media recommendations:

1. when possible, always remember to add the Twitter handles of projects, organizations, people... etc

How about this version, @lauracowen?

_#MicroProfileBlog: #IBMer Gilbert Kwan shares how developers can learn about @MicroProfileIO 5.0 and @JakartaEE 9.1 with the @OpenLibertyIO cloud-hosted guides without installing anything! 

[MP blog Link uses a short link]

#OpenSource #MicroProfileReleases #JakartaEEReleases_

---

The design card can have the photo of the author, git, etc. We don't add that link to the description b/c the only link that matters is the blog link #374

**Comment by lauracowen** [comment]
@aeiras Yes, that tweet text looks great, thanks. I wasn't sure exactly what was needed in the issue, so thanks.

Ah, the "design card" is the image like in the release tweet you've linked to ([with the Christmas art](https://twitter.com/MicroProfileIO/status/1341732854359871490/photo/1)). How do they get created?

**Comment by aeiras** [comment]
> @aeiras Yes, that tweet text looks great, thanks. I wasn't sure exactly what was needed in the issue, so thanks.
> 
Great, thanks, Laura for the review. 

> Ah, the "design card" is the image like in the release tweet you've linked to ([with the Christmas art](https://twitter.com/MicroProfileIO/status/1341732854359871490/photo/1)). How do they get created?

The person that will help with the media publishing creates that card. In this case, MicroProfiler @rstjames will help us. 

Every year, MP creates a master design card to cover the year. That card is usually customized by MicroProfiler @rstjames to match a message task.  https://microprofile.io/resources/branding/ Design templates are located in the MP drive under designs, and anyone in the world that knows how to use Adobe can download and use the designs. 

Hugs

**Comment by rstjames** [comment]
I added all 5.0 content to the bottom of the page. Also added 4.1 content to the 4.1 page. There is one bug to fix but Andrii will tackle it.

**Comment by aeiras** [comment]
amazing adding @rstjames. 

Why is [Guide: Learning MicroProfile 5.0 and Jakarta EE 9.1 Without Installing Anything](https://openliberty.io/blog/2022/04/12/guides-updated-mp5-jakartaee9.html) which is a cross post into the MP blog about 5.0 not shown in the page?

**Comment by aeiras** [comment]
@rstjames when the feature is added, please close this ticket and lets update Laura about it. Thank you!

**Comment by rstjames** [comment]
@aeiras it is added. There is a bug causing categorized blog posts that are "linked" not to show. We need to buy extended support to be able to ask about this issue with the theme creator. Looking into all of it now. 

all other not "linked " blogs that have the 5.0 or 4.0 categorized tag show up.

**Comment by aeiras** [comment]
Let us know what you and Andrii find out about the fix, Ryan. Thank you for the update on this issue.

**Comment by rstjames** [comment]
Fixed @aeiras

**Comment by aeiras** [comment]
@rstjames formidable job getting this done, Ryan. Thank you and Andrii for tackling it. 

Hola @lauracowen [lauracowen](https://github.com/lauracowen)

It took awhile but the release blog you crosspost it is now also listed under the Compatible pages, release 5.0. Please see below. Thank you for your patience.  This ticket is now closed. If your team has a blog on 4.1, you are most welcomed to add it as well. No pressure. :) 
https://microprofile.io/compatible/5-0/

**Comment by lauracowen** [comment]
@aeiras Done one for 4.1 - see #699
