### ISSUE TITLE
[Documentation] MP Wikipedia 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#693]
[MicroProfile Wikipedia Content DRAFT](https://docs.google.com/document/d/1uaygZLm_xJWWuVjSuR7IRTpqNYAwsEuECizDBIfwJ6c/edit#heading=h.8acevozb2c25

from June 2018.

**Comment by aeiras** [comment]
@JanWesterkamp-iJUG & @dblevins I have found the 2018 work draft on this.

**Comment by JanWesterkamp-iJUG** [comment]
@aeiras , thanks - good to know! :-)

**Comment by aeiras** [comment]
> @aeiras , thanks - good to know! :-)

Jan, I added you to the MPWG contributors https://projects.eclipse.org/projects/technology.microprofile. Now, you can Triage git access in all MP repos.

**Comment by aeiras** [comment]
MP wikipedia is a nice to have feature with iJUG as a volunteer. 

This ticket is closed for now until MicroProfiler starts that work. :)
