### ISSUE TITLE
[Website - MPWG page] Replace Become a Member with Membership Prospectus + more

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#695]
@rstjames, 

Thank you for helping adjust the highlighted bottoms of the: https://microprofile.io/workinggroup/

1. Become a Member **changes** to Membership Prospectus
2. Join the Discussion **changes** to Community Forum
3. Members Onboarding changes to "Member Onboarding Process"

**Comment by aeiras** [comment]
@rstjames lets try to close this ticket this week. Thank you! 

Please check all tickets and lets close the ones that are easy to complete. July means a new quarter and we ought to do laundry of tickets. :)

**Comment by rstjames** [comment]
Updated @aeiras

**Comment by aeiras** [comment]
excellent improvements @rstjames :)
