### ISSUE TITLE
[Swag Infra] Add Cesar Hernandez to microprofile-swag@googlegroups.com 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#697]
@[cesarhernandezgt](https://github.com/cesarhernandezgt)

Please confirm you got the access. You are an owner of the mailing list. Also, note that the Admin infra spreadsheet has been updated, and tab Swag has your trusted access. https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=51126614

Thank you for being a beautiful ossDOER!

**Comment by cesarhernandezgt** [comment]
Access was tested successfully.
