### ISSUE TITLE
[MPWG  Request] Onboard a New Vendor - Burbank Shipping Center, BSC

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#698]
MicroProfilers have talked and agreed on the 23 communities who are tentative the recipients of the swag (shirts- purchased & 5000 stickers [still awaiting purchased linked to shipping matters location] ) refer to [[Swag 2021] Distribution logistics #688](https://github.com/eclipse/microprofile-marketing/issues/688)

**Message from the new Vendor after much discussion on their services:**

Thank you and can’t wait to work together
-Monique Petrossian
[Burbank Shipping Center ](https://www.burbankshippingcenter.com)- A Mother/Daughter Operation - All Female owned and managed

1812 W. Burbank Blvd
Burbank CA 91506
(818)846-1400
Monique@BurbankShippingCenter.com

https
[cc.Authorization.Form.pdf](https://github.com/eclipse/microprofile-marketing/files/9105836/cc.Authorization.Form.pdf)
://github.com/eclipse/microprofile-marketing/issues/692#issuecomment-1160863987

---

Related to this ticket:

1.  [[ Swag] Find a Shipping Global Partner #692](https://github.com/eclipse/microprofile-marketing/issues/692), MP wishes to collaborate with Burbank Shipping Center to ship the [380 shirts ](https://github.com/eclipse/microprofile-marketing/issues/633) currently stored at [Deluxe Printing Center](https://github.com/eclipse/microprofile-marketing/issues/598) in Los Angeles. 
#692 contains the information about costs estimates, USPS, only. We are interested in the USPS service delivery as seen on PDF https://drive.google.com/drive/u/0/folders/1sRgUXDmeQPOJBbweBRvUeriIWfYpTuP0, which includes the discounts. 

2. [[Swag] MP Stickers for 2021 t-shirt distribution - Costs #687](https://github.com/eclipse/microprofile-marketing/issues/687)  Microprofilers decided that 5000 stickers will be distributed with the 380 shirts3. 

3. [[Swag 2021] Distribution logistics #688](https://github.com/eclipse/microprofile-marketing/issues/688)4. 

4. [ [SWAG] T-shirt Purchase Request on behalf of the MPWG #633](https://github.com/eclipse/microprofile-marketing/issues/633).  380 shirts were purchased. 
---

** Process of purchasing Shipping from BSC:**

MP submits the order (s) privately to BSC via an excel sheet that contains:

1. names
2. addresses
5. phones
6. sizes & quantity

BSC submits to MP via private excel sheet :

1. the USA and/or international tracking numbers so that MicroProfilers inform the community etc.

----

**Comment by aeiras** [comment]
In addition: microprofile-swag@googlegroups.com has been created as a private mailing list where trusted access is given to thus far [5 MicroProfilers ](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=51126614)who are waiting for the Shipping Vendor to be approved to initiate contact and secured shipping information with the [2021 -Shirt Swag - Distribution Plan - Global Communities](https://docs.google.com/spreadsheets/d/1y3dT8zpBlgO0eJ4TgYx9zVCfzDXx_4l58KQKkd5vp7I/edit#gid=590237288)

**Comment by emecas** [comment]
@aeiras as discussed during our community call, I wish to collaborate with this task, please assign me to own this ticket!!

**Comment by aeiras** [comment]
Your actions are beautiful, Emerson!

Please see the #598 ticket and use it as a reference for the process. 

https://github.com/eclipse/microprofile-marketing/issues/598

**Comment by emecas** [comment]
The request has been submitted to the MicroProfile Working Group: https://www.eclipse.org/lists/microprofile-wg/msg01555.html

**Comment by emecas** [comment]
**Current Status:** 

Based on 2 meetings this week : [Marketing](https://docs.google.com/document/d/18W4NdRqXFUDSVJHdQEUI4-Nx0Vuq_Ms6QiiGwFj-diQ/edit#bookmark=id.us4ke513qd5z) and [Community Call](https://docs.google.com/document/d/1ErBpojIK3JT1WmCWVkxmpifkH9dD57U4Lci-Sy1mh6I/edit?pli=1#bookmark=id.96ci1poivc53) ,  Burbank Shipping Center (BSC) is now an authorized EF Supplier

**Next Steps: [WIP]**

- [ ] Meet with @dalexandrov to get an update on the discussion about next action items
- [ ] Define action items list with scope and outcomes
- [ ] Execution

**Comment by aeiras** [comment]
Amazing work, @emecas!!!

**Comment by aeiras** [comment]
@emecas, 

While we await for the EF team to get back to us as their point of contact to proceed, is it OK for you that via Email, I formally introduce you to the two swag Vendors, Printer Deluxe and Shipping Center?

**Comment by emecas** [comment]
> @emecas,
> 
> While we await for the EF team to get back to us as their point of contact to proceed, is it OK for you that via Email, I formally introduce you to the two swag Vendors, Printer Deluxe and Shipping Center?

Sure @aeiras , It is totally OK,  I sent a initial contact to Monique from `BSC` about 2-3 week ago at 08/26, but I did not get a reply.

**Comment by aeiras** [comment]
Thank you, Emerson. Expect that email today. :)

**Comment by aeiras** [comment]
completed. :) You rock, @emecas!
