### ISSUE TITLE
[Blog Contribution] Check the startup status of your microservices with MicroProfile 4.1 in Open Liberty 21.0.0.9

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#699]
**[MicroProfile.io WordPress](https://github.com/microprofile/wpsite)**

**Content copy/edit review (available & optional)
[Draft post](https://microprofile.io/wp-admin/post.php?post=7021&action=edit) 
 
 **Social Media Description**
Define startup probes to check the startup status of your #microservices before the Liveness probe takes over. Easily configure @KubernetesIO Startup probe with the new REST endpoint. Check out @MicroProfileIO 4.1 in @OpenLibertyIO.

 **Design Card**  (for MicroProfile designer)
(There isn't really an author as it's a release blog post compiled from multiple contributions and I don't know who wrote the relevant part of it now. We could mention Ryan (who edited it) but he isn't the right person for anyone to contact for more info. The @OpenLibertyIO Twitter account is probably best for that kind of blog post as a contact point.)

Notes: I've also tagged this for MP 4.1 so that it can appear on the compatibles page.

**Comment by lauracowen** [comment]
@aeiras

**Comment by cesarhernandezgt** [comment]
Hi @lauracowen,
Thank you for submitting the article. The blog post is now published: https://microprofile.io/2022/08/15/startup-status-of-microservices-microprofile-4-1-open-liberty-21-0-0-9/

cc: @rstjames Social media is the next step, I'm assigning the ticket to you.

**Comment by rstjames** [comment]
@lauracowen ok with the image? 
let me know and I will put it on MP social
![MicroProfile-blog-Checkstartup_status_MP4 1](https://user-images.githubusercontent.com/12132146/186357312-36e18e61-bae4-45b8-93e0-83db1a4f96a3.png)

**Comment by lauracowen** [comment]
That's fine, thank you!
