### ISSUE TITLE
Please review New Blog Post - End-to-End Example App running on Kubernetes and Istio

### ISSUE THREAD

**Issue by nheidloff** [microprofile/microprofile-marketing#70]
Hi, I've written my first blog post for microprofile.io. Could you please review it?

https://microprofile.io/wp-admin/post.php?post=6209&action=edit

Thanks a lot
Niklas

**Comment by aeiras** [comment]
Hola @nheidloff, 

Fantastic first MP blog, reviewed and [published ](https://microprofile.io/2019/04/24/end-to-end-example-app-running-microprofile-on-kubernetes-and-istio/)

Are you ok to add a page header? If yes, go diretly to the blog- no matter if it is already published, we will refresh it if you add the header. 

Page Header ImageThe image should be between 1600px - 2000px wide and have a minimum height of 475px for best results.

Thank you for #writingTHEtalk and sharing MP fun with everyone! Your actions ROCK!
--

**Comment by nheidloff** [comment]
Hi @aeiras, thanks a lot! That was pretty fast.

I didn't do a page header since the title was hard to read. I've created now a new version of an image which is 50% transparent. 

I cannot edit the blog entry (only see view and duplicate). I've uploaded the file niklas-heidloff-architecture-transparent.png to Wordpress. Could you please put it in the blog or give me access?

Thanks !
Niklas

**Comment by aeiras** [comment]
Actually can you add the file in this issue? I cannot see it in wordpress. 
File must follow Wordpress sizing, I won't adjust it :) I will add it for you, Thanks! 👍 
Page Header Image
The image should be between 1600px - 2000px wide and have a minimum height of 475px for best results.

**Comment by nheidloff** [comment]
Hi @aeiras, here it is:

<img width="1000" alt="niklas-heidloff-architecture-transparent" src="https://user-images.githubusercontent.com/1425685/56757244-0c424080-6794-11e9-8fa6-013c27e4f18f.png">

**Comment by nheidloff** [comment]
It should be in Wordpress as well:

<img width="1332" alt="Screen Shot 2019-04-25 at 7 55 21 PM" src="https://user-images.githubusercontent.com/1425685/56757308-3562d100-6794-11e9-91cb-8be7a9abd520.png">

**Comment by aeiras** [comment]
@nheidloff excellent graphic choice, your blog is updated. If you tweet, we can re-tweet via the MP handle :) 

Thanks for #writingTHEtalk, for caring enough to prioritize sharing what you are learning.

**Comment by nheidloff** [comment]
Great, thanks a lot, @aeiras! I tweeted about it here: https://twitter.com/nheidloff/status/1121330917614784514

**Comment by aeiras** [comment]
MP- retweeted-- abrazos!
