### ISSUE TITLE
Need to monitor the compatibility issues and add the approved project to the compatible website

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#702]
The certification requests are [here](https://github.com/eclipse/microprofile/labels/certification) . We need to monitor that and get the request added to the `compatible` page of microprofile.io once they are approved according to the [MicroProfile TCK process](https://github.com/microprofile/microprofile-wg/blob/main/tckprocess.adoc#certification-resolution).

**Comment by cesarhernandezgt** [comment]
Can we add this step to the current Github Issue template?
![image](https://user-images.githubusercontent.com/1454523/184688788-b895c94c-7b68-4b19-bc94-7d83ff0bcd45.png)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/690

**Comment by aeiras** [comment]
The new wiki page has been added to the https://microprofile.io/compatible/ 

Thank you @rstjames for that step and Emily for enabling a draft review! :)
