### ISSUE TITLE
[Swag 2022 budget] MP stickers & Shirts

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#703]
It will be great if you can distribute some MP stickers to the various MP speakers like myself to give out when deliving MP talks or giving out at the Eclipse booth of various conferences. Can we allocate some funding to order more MP stickers from the 2022 budge?

**Comment by aeiras** [comment]
+1

**Comment by cesarhernandezgt** [comment]
+1

**Comment by aeiras** [comment]
T-shirts ought to be added to this activity as well. 

There are about 5 active traveling MicroProfilers who can formally get MP swag to distribute on their MP sessions.

**Comment by dalexandrov** [comment]
Not only stickers but also T-Shirts to most active contributors!

**Comment by aeiras** [comment]
@emecas, please comment on this ticket to add you as the lead for the task :)

**Comment by emecas** [comment]
> @emecas, please comment on this ticket to add you as the lead for the task :)

landing!!!
