### ISSUE TITLE
Improve MP compatible page

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#704]
At the moment, some runtime has different versions listed under the `compatible` page (see [here](https://microprofile.io/compatible/4-1/)). The list will grow longer and longer. In order to make it more manageable, I wonder whether to assign one row per product and that row can list multiple versions.

In this case, `Payara Enterprise` will just occupy one row while multiple versions can be displayed.
Product                 | product versions
Payara Enterprise | 5.37.0, 5.38 
The product version will be a hyper link which points to the tck result.

See https://jakarta.ee/compatibility/certification/9.1/

**Comment by rstjames** [comment]
Here is a rough solution: @Emily-Jiang 
Expandable sections: 
- The companies will be listed and when clicked it will show a table of all the compatibl
<img width="1241" alt="Screenshot 2022-08-25 at 14 04 26" src="https://user-images.githubusercontent.com/12132146/186659824-6526a4d9-eb86-4519-8aad-95487be3f04b.png">
<img width="1245" alt="Screenshot 2022-08-25 at 14 04 32" src="https://user-images.githubusercontent.com/12132146/186659828-0c85ea85-8b99-4d34-bae7-0c2057cfb663.png">
e products for each product.

**Comment by aeiras** [comment]
@rstjames +1 on improvement. How long will it take to update?

**Comment by Emily-Jiang** [comment]
@rstjames even this, some lists are still quite long. Can we take a look at [Jakarta EE compatible page](https://jakarta.ee/compatibility/certification/9.1/) as I think it manages well?

**Comment by cesarhernandezgt** [comment]
+1 for the collapsable approach.

**Comment by dalexandrov** [comment]
+1 collapsable

**Comment by rstjames** [comment]
Updated on implementation. I will bring this over live tomorrow. After we can start to update what new content is needed for each page. 
<img width="1403" alt="Screenshot 2022-09-12 at 19 42 05" src="https://user-images.githubusercontent.com/12132146/189721013-37754b21-60ce-4ef7-8a29-721636afc9d8.png">

**Comment by rstjames** [comment]
<img width="1431" alt="Screenshot 2022-09-12 at 19 45 47" src="https://user-images.githubusercontent.com/12132146/189721501-d57be8de-cb89-42a4-87da-984371f437b5.png">

**Comment by aeiras** [comment]
I really like seeing the logos for the projects that are compatible, @rstjames :)
