### ISSUE TITLE
[Blog Contribution] Develop MicroProfile apps with the new Liberty Tools for Eclipse

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#705]
**Content copy/edit review (available & optional)
[Draft](https://microprofile.io/wp-admin/post.php?post=7030&action=edit) 
 
 **Social Media Description**
Early release of Liberty Tools for Eclipse. A new experience for developing cloud-native Java microservices on @OpenLibertyIO, inc assistance using @MicroProfileIO APIs, editing server config in Maven and Gradle projects, and automatically deploying code changes to your running app. @awisniew90 demos.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

**Comment by cesarhernandezgt** [comment]
Hi @lauracowen,
Thank you for submitting the article. The blog post is now published: https://microprofile.io/2022/08/15/develop-microprofile-apps-liberty-tools-eclipse/
cc: @rstjames Social media is the next step, I'm assigning the ticket to you.

**Comment by rstjames** [comment]
@lauracowen on the SM image: 
Who should be as the author.?
I clicked the link from the artical and it says the author is [Adam Wisniewski](https://github.com/awisniew90)? 

Let me know and I will add whoever's image to the SM card. 

Thanks,
R

**Comment by lauracowen** [comment]
@rstjames hi, yes, it should be Adam. Thanks

**Comment by rstjames** [comment]
![MicroProfile-blog-dev_MP_apps_liberty](https://user-images.githubusercontent.com/12132146/186353347-edc3a306-662a-4eb8-9887-7e49540ff6d2.png)
@lauracowen

**Comment by rstjames** [comment]
I will put it on MP social today

**Comment by lauracowen** [comment]
Looks great, thanks :)

**Comment by rstjames** [comment]
@lauracowen sorry but your tweet is over the characters.  323 / 280 can you please shorten it?

Thanks

**Comment by lauracowen** [comment]
Ah sorry. How's this:

Early release: Liberty Tools for Eclipse. Develop cloud-native Java microservices on @OpenLibertyIO, inc assistance using @MicroProfileIO APIs, edit server config in Maven & Gradle projects, auto deploy code changes to your running app. @awisniew90 demos.

**Comment by rstjames** [comment]
All set to go out.
