### ISSUE TITLE
Create more meetings for MP Metrics group

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#706]
MP Metrics teams needs to create weekly Thursday calls from this week 2:00-3:00 British Summer Time and last for 2 months.
I was no longer able to log into zoom account using microprofile-marketing. I got this error 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/10999780/183952390-6540df12-7f46-4ae1-bf01-9415aee309e0.png">

We need to work out a better strategy for the login issue. In the meanwhile, @jclingan can you schedule the meetings first? Thanks

**Comment by jclingan** [comment]
I did add more meetings, but we still have to get the code (with help from Eclipse Foundation staff) so you can log in.

**Comment by aeiras** [comment]
what is the status of this issue @jclingan ? 
Does MP need to buy its own Zoom account?

**Comment by aeiras** [comment]
This week during the MP mktg call we noticed that Zoom is working ok with access to Admin calls. Closing ticket.
