### ISSUE TITLE
[Infra- Video Recording] Add visibility for the location of the meetings recordings

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#707]
I am unable to find where the recordings of the Tuesday calls are kept at the moment. Can we add some links to the site or tweet the recording link after the meeting, please?

**Comment by aeiras** [comment]
Martin, 

About +1 month ago, MP had an issue with a recording via Youtube. @jclingan is adding the recordings to another tool. If you check the minutes, I think the links are under each minutes.  John could confirm. NO tweets b/c there is no recordings being shared yet... Maybe we are still figuring out if we drop Youtube formally or similar.

**Comment by xstefank** [comment]
Thanks, @aeiras. I'm asking because I can't find the latest one anywhere. So I guess John will link it in the minutes. But I still think a less digging way of finding these links would benefit the community.

**Comment by jclingan** [comment]
I just linked it in the minutes. Sorry, I was a bit late this week!

**Comment by aeiras** [comment]
@jclingan, 

can we add as a topic "general" about recordings and the process that we have chosen to work in as well? 
Martin's points are valid. Like him, a few others do await for recordings to listen to stuff.  You rock! I think whatever you are comfortable supporting, either paid or none paid tool is a go. Do let us know!

**Comment by aeiras** [comment]
@jclingan where are we on this? Do we close the ticket?  
I don't know where the recordings are posted as they don't show up in Twitter. Thank you for your insight.

**Comment by xstefank** [comment]
@jclingan @aeiras just bringing this up again so we can get it resolved. I can find the links now in minutes but we could still put the link to all of them somewhere (top of the minutes or site).

**Comment by aeiras** [comment]
Decided that Ryan will upload the Community, Marketing and Technical recordings to Youtube and that John will create git tickets for each of those recordings.
