### ISSUE TITLE
[DevRel Outreach ] Twitter communities

### ISSUE THREAD

**Issue by majidmostafavi** [microprofile/microprofile-marketing#708]
Some community such as JakartaEE , Quarkus  has the twitter community . I suggest Microprofilers  create Microprofile community in Twitter

**Comment by majidmostafavi** [comment]
MicroProfilers or MicroProfile ?

**Comment by aeiras** [comment]
I think it is MicroProfilers, Majid. 

If others like you, think that creating a twitter community for MP is healthy, then Admins/volunteers will have to create such account and manage it.  That is where you need to sell it.  Alone you won't be able to push this forward. At least 3 people might help with neutral set or similar.   

The [MP Admin Access - Trusted Stewards](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=2015643674) comes into play for all MPWG INFRA. 

I recommend you discuss it again next Monday in the marketing/ and community calls to see if you find supporters for the initiative.

**Comment by msharafifar88** [comment]
MicroProfilers community has been created so we can post on it .

**Comment by majidmostafavi** [comment]
MicroProfilers commynity has been created in Twitter.

**Comment by majidmostafavi** [comment]
URL : 
https://twitter.com/i/communities/1570499885488607232

**Comment by majidmostafavi** [comment]
We need some volunteer for manage MicroProfilers community in twitter

**Comment by aeiras** [comment]
@majidmostafavi Hola, 

As discussed on this week's marketing call, can you please draft a Twitter message that MP twitter can share about the new Twitter community group you created? 
Doing so will bring awareness to anyone in twitter who might wish to learn about MP and to those who already know about MP. 

I am happy to review your social text on that push before MP pushes it via its media channels.

**Comment by aeiras** [comment]
@majidmostafavi, 

Are you ok to close this ticket and open new ones about the active as you see fit? 
The ticket is from Aug, so as the December steward I am checking what is in the pipeline before this year is done.
