### ISSUE TITLE
[Calendar] Metrics changed from Monday to Thursday

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#709]
Hola @Emily-Jiang, 

Can you please help confirm that the Metrics call was formally moved from Tu to Thursday? 
The current media API schedule is set for Tuesdays. The calendar shows Thursdays, and no ticket has been filed to adjust it. You could assign this ticket to other MicroProfilers as you see fit.  Thanks for your help. 

 https://twitter.com/MicroProfileIO/status/1562062527508406275?s=20&t=LaHjmrFh9qXGdMMVnGhfSw

**Comment by Emily-Jiang** [comment]
Not moved. They added a few additional calls on Thursdays in addition to Tuesdays. The Thursday calls only last for a few weeks.

**Comment by aeiras** [comment]
Oh, that is great. No need for schedule then :) Thanks for the prompt reply, @Emily-Jiang!
