### ISSUE TITLE
MicroProfile and JavaEE @ es~conference (Mexico)

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#71]
Sorry for the late submission, I didnt knew about this until today...

Conference Name: Es-Conference Mexico 2019

Conference website and social media links:

http://www.javaup.org.mx/
@Javaup
Talks Links
http://www.javaup.org.mx/session/microprofile-for-the-busy-developer/

Session Name: MicroProfile benefits for monolithic applications
Date and hour: Friday, April 26th. 2019 (16:30 am - 17:30 am)

Speaker name: Jorge Cajas
Speaker twitter handle: @cajasmota

Description
Join @cajasmota at @Javaup to discuss and learn how could you take advantage of the @MicroProfileIO API's on your existing applications without refactoring them into microservices - Friday, April 26th More info: http://www.javaup.org.mx/session/microprofile-y-sus-beneficios-para-aplicaciones-monoliticas/
#OpenSource #OSS

**Comment by aeiras** [comment]
This late -- might not make the cut, i have pushed it to priority yet it might not be possible for the team to own it. FYI, still thanks for submitting, even if late- it is ok to be disciplined with filing issues for everything MP sharing fun via events. :) #LatinArmada

**Comment by rstjames** [comment]
@Motojo Sorry but this snuck by me and I was not able to get it out. 
Please next time its best to give us a bit more time to prepare it. 

Next time :) Thanks
Ryan
