### ISSUE TITLE
August 29th call co-host 

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#710]
Hello

 I'd be happy to help host the call for August 29th.

Based on past co-host participation I've seen, I wonder who will provide me with the Zoom access to be able to:

- Start the zoom call
- Start the recording
- Allow others to join from the waiting room

**Comment by aeiras** [comment]
This Monthly steward ticket is great, @cesarhernandezgt!

@jclingan & @Emily-Jiang are the 2 Zoom admins and can give you that access. It seems that zoom infra settings are problematic...  we will discuss the findings soon and see a resolution to either keep the EF zoom and buy an independent Zoom.

**Comment by aeiras** [comment]
Mitia, @@dalexandrov, 

Your Sept git issue ticket is missing :) Needed to enable other MicroProfilers to collaborate with you this month. 

Please keep in mind the Stewards wiki and submit PRs or adjust documentation as you navigate being the leader of MP in September. 

[Mktg Call Steward Onboarding & Call Steward Responsibilities Work in progress](https://github.com/microprofile/microprofile-wg/wiki/Mktg-Call-Steward-Onboarding-&-Call-Steward-Responsibilities---Work-in-progress)
