### ISSUE TITLE
[Website Improvements] Working Group tabs restructure

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#711]
The page https://microprofile.io/workinggroup/ has been growing in to a point that now individual pages can be created to cover different aspects of the MP WG context.

This topic was briefly discussed on the August 29th Mkt call, so further discussion will need to define this ticket's context and scope.

**Comment by rstjames** [comment]
Think we need more information on this one to move it forward @cesarhernandezgt @aeiras

**Comment by aeiras** [comment]
@rstjames, 

I recommend you create a draft via google drive on what currently exist in the page and suggest how you recommend the content being organized. Like that, we can discuss it via this ticket and in the Mondays' calls before implementing the improvements on the page. 

Ideally, we can tackle that document in 2022 and implement the changes in Q1 of 2023.  Or if you and @cesarhernandezgt have other ideas, do bring them forward.  

Just remember that the last 2022 MP marketing meetings is Dec 5th and most of the work stops on the 16th.

**Comment by rstjames** [comment]
@aeiras Not sure how to create a draft when there this no information on what should be restructured.

**Comment by aeiras** [comment]
Ryan, 

the base is all the información found in the page. 
how would you recommend the información is presented? 
the most important thing is for each section to have its own link.

it doesn’t matter how long the page is, if we can bookmark it as we did witt resources that could work. 

Does this clears the how for the outline?

**Comment by rstjames** [comment]
Ah all need their own link... hmm 

Let me see if I can make anchor links for "tabs" if not... I will think of something

**Comment by Dexmaster** [comment]
Ok I'm starting on this.

So from this, I will replace tab links with readable ones and make so they direct to the correct tab selected (so could be shared)

**Comment by Dexmaster** [comment]
Done on https://microprofile.io/workinggroup/ (added prefix `mptab-` so it's unique tab id, and small js for scrollto after load)

If you click any tab link hash changes, and could be shared as is, example links:
https://microprofile.io/workinggroup/#mptab-knowledge
https://microprofile.io/workinggroup/#mptab-program-plan-budget
https://microprofile.io/workinggroup/#mptab-branding

**Comment by aeiras** [comment]
Thats a fantastic improvement @Dexmaster & @rstjames! 

Can the quotes and the Prospect spaces also have their own links? 
Ideally, the entire page is separated by its own link based on the information group by section.

**Comment by Dexmaster** [comment]
@aeiras done too (just need id added to row, testimonials was already there)

https://microprofile.io/workinggroup/# - top
https://microprofile.io/workinggroup/#testimonials - testimonials
https://microprofile.io/workinggroup/#prospects - prospects
https://microprofile.io/workinggroup/#mptab-members - members
...

**Comment by aeiras** [comment]
Andrii, 

How do I get from the landing page to those links? 
Navigating the page doesn't lead me to those clicks/... what am I missing?

Thank you for working on this ticket!!!

**Comment by Dexmaster** [comment]
Question where you want those links to be? 
I don't know, it's design question to @rstjames 
Tabs you click and URL changes, as for page paragraphs testimonials/prospects info those might need some icon somewhere?...

**Comment by Dexmaster** [comment]
@rstjames / @aeiras Feature is ready for review:
I've implemented a feature that changes the hash on the scroll.
When you add an id to the top-level section row it will be used as a base for links on scrolling. Could be used for any page right now.
preview: https://microprofile.io/workinggroup/

**Comment by aeiras** [comment]
It is great to have your front end skill on the adjustments on the MPWG, Andrii :)  

Now, is there a way you can show a screenshot of the change you mention before implementing it? 
Reversing stuff also work if it doesn't work but if we can avoid doing so, that is always preferable.

**Comment by Dexmaster** [comment]
Sure @aeiras, here is example for the future if anyone wants to set some custom Row ID so it will be used in scrolling:

https://user-images.githubusercontent.com/6061000/205167717-2b789624-4cf0-482a-b0a6-b3eaf3361047.mp4


P.S. Link in question is https://microprofile.io/workinggroup/ and section is testimonials

**Comment by aeiras** [comment]
@Dexmaster let's execute and see it. :) thank you for showing it. Let's iterate, and hopefully more eyes arrive to provide feedback on the quote section. 

As for the Members' logos, we need the section to show all the logos at once, no scrolling anymore. Ryan will create a new ticket. You two have fun on that improvement.

**Comment by rstjames** [comment]
this is done.

**Comment by aeiras** [comment]
Hey @Dexmaster & @rstjames, 

The ticket is re-opened b/c there are 2 sections' links, Quotes, and prospectus 
https://microprofile.io/workinggroup/#testimonials - testimonials
https://microprofile.io/workinggroup/#prospects - prospects.

Which still don't have a house within their space. 

Andrii, thank you for creating the links a month ago.  
Ryan, we need to place them within each section. 

Thank you!

**Comment by Dexmaster** [comment]
@aeiras based on your input:

- added a link icon to the left of those sections' headings (invisible by default)
- icon becomes visible when you hover over the heading

Preview: https://microprofile.io/workinggroup/#testimonials
![image](https://user-images.githubusercontent.com/6061000/207949843-9e247333-ce82-42d8-bb51-d369f06f3433.png)

**Comment by aeiras** [comment]
@Dexmaster, Hey! :)

That works for both sections. Thank you. 

A fix needs to be made to the Prospectus area:  https://microprofile.io/workinggroup/#prospects

Please change #prospects to #prospectus. 

Thank you for helping close this ticket. :) Please pull me in when completed to close it. Yeay!

**Comment by Dexmaster** [comment]
Done.

https://microprofile.io/workinggroup/#prospectus

**Comment by aeiras** [comment]
Andrii, 

You found a beautiful and elegant solution to the 2 spaces. You rock! 
Thank you, Triber! :)
