### ISSUE TITLE
[2022 swag update] Tshirt and Hoodie design update 

### ISSUE THREAD

**Issue by cesarhernandezgt** [microprofile/microprofile-marketing#712]
As a follow-up from [8/29th Marketing call](https://docs.google.com/document/d/18W4NdRqXFUDSVJHdQEUI4-Nx0Vuq_Ms6QiiGwFj-diQ/edit#bookmark=kix.61snxhst0oim), the design for both the T-shirts and the hoodies needs to be updated to match the actual number of members' logos.

**Comment by rstjames** [comment]
which list is correct for this @cesarhernandezgt ?

**Comment by aeiras** [comment]
Hola @emecas, 

Here is the issue on 2022 swag design update. :)

**Comment by aeiras** [comment]
Hey @rstjames, 

Thank you in advance for prioritizing this task. 

**Shirt design**

- same front
- back - 9 members

**Hoody Design**
When the hoody was designed in early 2017, MP was not yet 1year old project.   Its M mark is well known today so I recommend the following:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/10731224/190247116-b4f06d83-4ec2-4b78-a0f3-a46e04dd27c6.png">

**Front design**
- Remove the wording of Micro Profile from the front of the hoody
- leave only the M
- remove Registered Marks from all printing designs

**Back design**
<img width="721" alt="image" src="https://user-images.githubusercontent.com/10731224/190247451-0fd872e5-74e6-4c0f-afa0-bccbc3280b6a.png">

- Add in the upper section of the shirt, MicroProfile. Since we remove it from the front of the hoody to match the t-shirt design of being just the M, we ought to add its formal name in the back. 
-
How possible is it to add Duke in the design, @rstjames ? Could we make it hold all the logos inside of it, or similar?


The hoody has never been re-designed. Since this will be the 2nd time we print it, we ought to improve what it currently is. 

--- 

We need drafts early next week, ETA Sept 20th.

**Comment by aeiras** [comment]
@rstjames  
> which list is correct for this @cesarhernandezgt ?

[2022 MicroProfile Working Group Steering Committee](https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=1486862268)

**Comment by rstjames** [comment]
@aeiras 
New updates on the hoody and shirt. 
Hoodie back: 
Put the full logo because the M is only on the front think its good to have somewhere the full logo
<img width="626" alt="Screenshot 2022-09-15 at 17 45 22" src="https://user-images.githubusercontent.com/12132146/190448670-983a4ea1-6a48-417d-8bef-7e90ab855395.png">

Back shirt:
<img width="742" alt="Screenshot 2022-09-15 at 17 48 24" src="https://user-images.githubusercontent.com/12132146/190449203-15e42396-1866-411f-9b66-af7406c0e373.png">

**Comment by aeiras** [comment]
@rstjames, 
Thank you for the 2022 update. I like the addition of the full MicroProfile name in the back of the hoody. 

**Adjustments**

1. Add the Eclipse foundation logo
2. stabilize the logo sizing. For some reason, it looks off. 
3. Hoody: The M goes on the lower right of the hoody. I think we ought to keep that style. 2 M back-to-back are off. 
4. remove Garden State's red color. The MP prints have only 2 colors, yellow and white. 
5. provide mocks for t-shirts and hoodies. 

You rock!

**Comment by rstjames** [comment]
@aeiras 
1. **(ok was told 9 logos so this will change the layout and sizes of all the logos.)**
2. **(all logos have different formats, makes it hard to make it all "balanced"**
3. **dont understand comment** 
4. **(this is just a screenshot and not colored on the design)**

**Comment by aeiras** [comment]
@rstjames  on 

2.  gotcha.  if someone can do it, that is only you 💯 Ryan!
3:
 
<img width="447" alt="image" src="https://user-images.githubusercontent.com/10731224/190512126-c560b350-7172-4c08-b52c-2d1deacb0946.png">

The M looks amazing on the lower right side of the hoody. Let's keep it there and only add the full Logo as you have done on the top without the M. 


4. cool :)

**Comment by rstjames** [comment]
3. I wound put the logo on top without the M. The point was to have one logo that is "fully" together. I would just leave the top logo out then. It would all before too random. Ill send an update soon

**Comment by rstjames** [comment]
@aeiras 
Hoodie:
![Back hoodie-2022](https://user-images.githubusercontent.com/12132146/190619269-171e8374-66d3-417e-8b64-c0a92c4ae163.png)

![Front hoodie](https://user-images.githubusercontent.com/12132146/190619257-5256c7d9-b98c-4d0f-bd3f-8d957038708c.png)

Shirt
<img width="910" alt="Screenshot 2022-09-16 at 12 55 01" src="https://user-images.githubusercontent.com/12132146/190623810-859844d8-b20d-4254-8e1c-e2070ed184ce.png">
<img width="898" alt="Screenshot 2022-09-16 at 12 55 17" src="https://user-images.githubusercontent.com/12132146/190623816-54ad12f3-8d3e-4554-a078-820c7c02a9ff.png">

**Comment by aeiras** [comment]
@rstjames, 

It looks beautiful. Thank you, RSJ!!!
We will revise it on next call. The mockups are helpful for committers' task :)

**Comment by aeiras** [comment]
> 3\. I wound put the logo on top without the M. The point was to have one logo that is "fully" together. I would just leave the top logo out then. It would all before too random. Ill send an update soon

I understand your feedback. Thanks for explaining, Ryan!

**Comment by vincentmayers** [comment]
great work Ryan

**Comment by aeiras** [comment]
> great work Ryan

Thank you, @vincentmayers for providing feedback, you rock! :)

**Comment by pilhuhn** [comment]
Does that / would that need to say "Eclipse MicroProfile" at some place, like what we need to do for other communication?

**Comment by emecas** [comment]
> Does that / would that need to say "Eclipse MicroProfile" at some place, like what we need to do for other communication?


Thanks @pilhuhn , I am  wondering  what other communications  you are referring to?  

Since this an interesting  and directly related matter to the design being addressed here, do you know (or anybody else)  is there is any agreement or project documentation that could clarify that subject ?

On the other hand , It seems Eclipse Foundation logo is in the back of both, T-shirt and Hoodie.

**Comment by aeiras** [comment]
Hola beautiful @pilhuhn, 

Thank you for joining this task. 

The Eclipse was dropped from MicroProfile on Oct 1st, 2020 when MP become a working group.  A reminder that the project during its transfer to the EF was required to add to its name the Eclipse.  Thankfully, when MP became a WG, the project could revert to its desired name and branding.  

Any Eclipse inserted into MP violates the project's trademarks. If you see it, do help fix it. If you cannot fix it, do submit a git issue via this repo.  

@emecas is correct on its follow-up about the Eclipse Foundation logo being a required part of the design. 

Do let us know if we understood correctly. Always happy to understand and stand together on MP.

**Comment by pilhuhn** [comment]
Thank you @aeiras for the update. I missed the drop of Eclipse, probably was after my really active time on MP. Good to hear.

**Comment by rstjames** [comment]
@aeiras are the latest updates approved? if so I will export all print data to the drive

**Comment by aeiras** [comment]
Yes, @rstjames! Thank you.

**Comment by rstjames** [comment]
@aeiras all updated on the GD

**Comment by aeiras** [comment]
Thank you, Ryan!

**Comment by aeiras** [comment]
We need to re-open this ticket to update design to include Primeton as the newest member of MP. https://github.com/eclipse/microprofile-marketing/issues/742. 

@rstjames --- this ticket is connected to the other onboarding. Thank YOU!

**Comment by aeiras** [comment]
Hola [mingyuehuang99](https://github.com/mingyuehuang99), 

This swag design ticket will request your final approval before the swag is printed. Above, you can see how the process was completed. It is helpful as a reference. Thank you for enabling the formal adding to Primeton. You rock!

**Comment by mingyuehuang99** [comment]
Yes，Primeton is happy for this logo used on MicroProfile swags！：）@aeiras

**Comment by aeiras** [comment]
@rstjames, 

While adjusting the design, please remove the EF logo. Doing so is based on this thread about authorization[ issues](https://www.eclipse.org/lists/microprofile-wg/msg01754.html).

**Comment by aeiras** [comment]
> Yes，Primeton is happy for this logo used on MicroProfile swags！：）@aeiras

So fantastic. Thank YOU for commenting on this ticket as well. Very much appreciated, [mingyuehuang99](https://github.com/mingyuehuang99),

**Comment by mingyuehuang99** [comment]
@aeiras@Emily-Jiang
halo,My company Primeton want to update logo to the new one,both io and swags ,thank you so much!!!:)
!this is the new logo.
[primeton logo](https://user-images.githubusercontent.com/119476657/206375734-552f0d3c-ae43-4489-8edd-c6d31db9303f.jpg)

**Comment by aeiras** [comment]
Gotcha, @mingyuehuang99, 

Your update logo has been placed under Members Logo folder https://drive.google.com/drive/u/0/folders/1egNtUlEajK4mS3NSAgLlTevxy6VLo1Z0 

You have editor access to adjust it as your company sees fit and use git tickets to inform MP.  

@rstjames can you please prioritize this update across? Thank you, Triber!

**Comment by Emily-Jiang** [comment]
Awesome, thank you @aeiras !

**Comment by aeiras** [comment]
Thank you for being such a great support to onboarding Primeton, Emily!

**Comment by aeiras** [comment]
@Emily-Jiang, 

Based on today's detailed community discussion on [Re: [microprofile-wg] 2022 Marketing Proposal](https://www.eclipse.org/lists/microprofile-wg/msg01782.html), it was agreed that we would look at the possibility of skipping the printing of t-shirts. Instead, 2022 expenditure is desired by the Members on two items. 

- Hoodies  (with a few 2XLs added)   
- MP coffee cups  (new item)

If the MP cups are a possible suggestion, we would be happy to provide ASAP the cup design with LARGE M.
If the MP cups are impossible, 100% of the budget for Hoodies is also attractive for Members, as the desired font is shown below.  


[2022MP Hoody approved designs](https://drive.google.com/drive/folders/1EvTnncOqUfrXTnDmj0eX3ziWsyB0wqdx)

- The hoody folder contains the following:

1. [Mockups](https://drive.google.com/drive/folders/1AmdyY5NE_2kzksO-x0Vw1aWmEWj29fBo)
2. [PDF](https://drive.google.com/drive/folders/0B7PK4ZIk1mjAX0pyd3g4SGhtaVU?resourcekey=0-UzRtZndB6JOrpFYJlx8wkA)
3. [Pantone colors](https://drive.google.com/drive/folders/0B7PK4ZIk1mjAYm9Hc0FTT0IwQ1k?resourcekey=0-4NuEOUeyFTa2NC6F4DLBiw)
4. [ai](https://drive.google.com/drive/folders/0B7PK4ZIk1mjARnJnVUxtNi1nRlE?resourcekey=0-Jefu4sy1-fdIlG6Y3pWLtw)

The [2021 hoody design](https://drive.google.com/drive/folders/1Cg8IuVtrJOBBmqtWv-MFHLvdnTyL5gkV) - and past printed hoodies have had the same front [print](https://drive.google.com/drive/folders/1pziV6zvz-Ts-lBJDHG1ry0vuBl4p-eiY) that includes MicroProfile and is while accepted as well. 

--
Happy to clarify anything shared with the links here. :)

**Comment by Emily-Jiang** [comment]
Please see my email on microprofile-wg with this request.

**Comment by rstjames** [comment]
Should this be closed?

**Comment by aeiras** [comment]
Not yet, @rstjames.

**Comment by aeiras** [comment]
https://www.eclipse.org/lists/microprofile-wg/threads.html#01722

**Comment by rstjames** [comment]
@aeiras can we close this?

**Comment by aeiras** [comment]
Yes.
