### ISSUE TITLE
Add instruction on how to add Compatible implementations on the Compatible page

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#714]
In the [compatible page](https://microprofile.io/compatible/), we need to add a sentence "Follow [this](https://wiki.eclipse.org/Implementation_Certification_Process) instruction to get your implementated listed here".

**Comment by rstjames** [comment]
![Screenshot 2022-09-09 at 13 51 23](https://user-images.githubusercontent.com/12132146/189345060-61eb55b3-b947-4621-9789-44329ebb489c.png)
@Emily-Jiang
