### ISSUE TITLE
[Website] Improvements on Members logos on landing page

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#715]
@rstjames, 

Can you please look into the sizing of the logos located https://microprofile.io? Thank you for correcting it. 
I couldn't find the old ticket for this task. :) 

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/10731224/188937860-b0330cf7-81e3-4470-a182-15120d944ce3.png">

**Comment by rstjames** [comment]
![Screenshot 2022-09-09 at 16 22 19](https://user-images.githubusercontent.com/12132146/189372318-1e019d10-dbfc-440b-ac3c-6dafb7ea19f8.png)
@aeiras

**Comment by aeiras** [comment]
It looks great. Thank you, Ryan 💪

**Comment by emecas** [comment]
@aeiras  @rstjames  I have a question for you,  it is a little unrelated topic, but is it there a issue already to follow the design for 2022 swags ?

**Comment by aeiras** [comment]
here you go, Emerson! :) https://github.com/eclipse/microprofile-marketing/issues/712#issuecomment-1241887378
