### ISSUE TITLE
[Compatible Implementations To Be Added to the Compatible page] Launcher 4.0

### ISSUE THREAD

**Issue by tnagao7** [microprofile/microprofile-marketing#716]
**Product Name**
Name: Launcher
 
**Product Version and download URL**
Product Version and URL: [Launcher 4.0](https://github.com/fujitsu/launcher/releases/tag/4.0)
 
**Java runtime used to run the implementation**
Java 11

**Compatibile Implementation Request**
https://github.com/eclipse/microprofile/issues/266

**Notes**
Please add Launcher to the Compatible page without the product logo for now. When the logo is ready, we may ask you to add it later.

The issue template "New Compatible Implementations To be Added" seems to be currently unavailable in [the list of templates](https://github.com/eclipse/microprofile-marketing/issues/new/choose). I created the current issue from the blank one, and that's why the `Compatibility` label is not set.

**Comment by aeiras** [comment]
Hola Takahiro, 

@rstjames, can you please look into this request? Thanks!

**Comment by aeiras** [comment]
@rstjames, 

https://microprofile.io/compatible/5-0/ needs to add Launcher as its newest compatible implementation. Can you please look into adding it this week. ? 

@tnagao7 would you like to write a social media post, 280 characters max "twitter" so that MP can use Hootsuite media to announce your product compatibility with Mp. 5.0?  Using this ticket is perfect for such write up.

**Comment by rstjames** [comment]
@aeiras @tnagao7 
Launcher 4.0 has been added to the 5.0 compatibility page. 
https://microprofile.io/compatible/5-0/

Please let me know if there are any issues

**Comment by Emily-Jiang** [comment]
@rstjames should you mention the product name instead of the company name?

**Comment by tnagao7** [comment]
@rstjames Thank you for updating, but the current logo (the infinity symbol cropped from the FUJITSU logo) cannot be used here. Could you use the normal FUJITSU logo or just remove the logo?

**Comment by Emily-Jiang** [comment]
> @rstjames Thank you for updating, but the current logo (the infinity symbol cropped from the FUJITSU logo) cannot be used here. Could you use the normal FUJITSU logo or just remove the logo?

Since we are listing the product, I think it is better not to list the company logo. For non-opensource project, it is okay to list the company name. I think removing the logo is better, as we are focusing on the product rather than the company behind it.

**Comment by aeiras** [comment]
+1 @Emily-Jiang!

@tnagao7, 
when the project has a logo, please submit it via a new ticket and the page will be updated. 

Thanks @rstjames for normalizing the pages so that it contains only the logo projects and not companies moving forward. : )

**Comment by rstjames** [comment]
@tnagao7 can you point me in the direction of what is the correct logo for  Launcher 4.0? If there is one.

**Comment by tnagao7** [comment]
@rstjames Please proceed with no logo (e.g. blank image).

**Comment by tnagao7** [comment]
I noticed that the compatibility page has already been updated. Thank you!
https://microprofile.io/compatible/5-0/
