### ISSUE TITLE
JS plugin  email from eclipse team (about website issue- but no issue found) 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#719]
Suggesting we have a missing/ issue with WG participants logos on home page. But there is no issue... so not sure why we are getting this email  

--------------------------------------------------------------------------------------------
Email title: [microprofile-wg] Incorrect Working Group participants on website
External

Hey all,

I'm one of the devs that help in managing Eclipse Foundation Working Group sites and APIs. I was recently reached out to by our Membership Lead to let me know that there are missing organizations in the carousel on https://microprofile.io/workinggroup/ and the membership logo section on the homepage https://microprofile.io/#fws_632083d27e92b.

We've recently created an API that allows for lookups of organizations associated with a working group, as well as a JS plugin that loads this data for you. The API in question can be found at the following link, https://membership.eclipse.org/api/organizations?working_group=microprofile. This looks up active members through our database, with an hourly cache rollover. This should keep this data very nicely up to date with less fuss if used.

The JS plugin prints it onto the page in a few formats that are pretty different than what you do, so it may not work well for you. While we added the ability to implement your own template, I'm not aware of how the current lists are managed, or any of the other mechanisms that may impact page load. If you would like to look into this plugin, it is available through our [solstice-assets](https://gitlab.eclipse.org/eclipsefdn/it/webdev/solstice-assets/) project which bundles our JS and minifies + polyfills the code. An example of a site that uses the new JS plugin is the IoT site, which uses it on the homepage and on the members' list/explore page.

If you have any questions, feel free to ask! I'll do what I can to support a switch over to the new API if that route is chosen.

Regards,

Martin Lowe

Software Developer | Eclipse Foundation

[Eclipse Foundation](http://www.eclipse.org/): The Platform for Open Innovation and Collaboration
_______________________________________________
microprofile-wg mailing list
[microprofile-wg@eclipse.org](mailto:microprofile-wg@eclipse.org)
To change your delivery options, retrieve your password, or unsubscribe from this list, visit
https://www.eclipse.org/mailman/listinfo/microprofile-wg

**Comment by cesarhernandezgt** [comment]
@rstjames maybe this API feature can be part of the work tracked here: https://github.com/eclipse/microprofile-marketing/issues/701

**Comment by aeiras** [comment]
Thanks Cesar for connecting this ticket to 701. closing this.
