### ISSUE TITLE
Please review Blog Post - MicroProfile JWT with Keycloak

### ISSUE THREAD

**Issue by cicekhayri** [microprofile/microprofile-marketing#72]
Hi everyone, I added a new blog post on microprofile.io. Could you please review it?

[https://microprofile.io/wp-admin/post.php?post=6215&action=edit](https://microprofile.io/wp-admin/post.php?post=6215&action=edit)

Thanks
/Hayri

**Comment by aeiras** [comment]
@cicekhayri great tutorial, you used code to show each steps, nicely done. Published, please tweet, so MP can re-tweet it :) 

Can you please start adding page headers to future MP content contributions? 
Why? See below, the blog is a crosspost to your website, it looks so bare on the blog header, I know you can take a screen shot of the code and be done with it, do that! 
You are beyond awesome about technical knowledge transfer, YOUR MP signature as such is KUDOS! :)  

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/10731224/56777242-3d674480-6785-11e9-97ea-7ba12b310614.png">

**Comment by cicekhayri** [comment]
Thanks @aeiras, I will add page headers to future blog posts :)
