### ISSUE TITLE
[SWAG infra] Private Committers Spreadsheet created

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#720]
The PRIVATE /CONFIDENTIAL spreadsheet is created and shared with the 5 MicroProfilers listed under Swag Email listed here: https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=51126614

The sheet will incorporate via tabs the year, committer, t-shirt sizing, address, etc. Information needed to send swag as it becomes available.

**Comment by aeiras** [comment]
@emecas & @dalexandrov

**Comment by emecas** [comment]
> @emecas & @dalexandrov

ACK, thx @aeiras

**Comment by aeiras** [comment]
The committers and contributors private spreadsheets are ready for use.   We need to figure out soon what tool to use as stated on https://github.com/eclipse/microprofile-marketing/issues/721

**Comment by aeiras** [comment]
ongoing!
