### ISSUE TITLE
[Social Media] EclipseCon Community Day Promotion

### ISSUE THREAD

**Issue by m-reza-rahman** [microprofile/microprofile-marketing#722]
As discussed in the marketing call, kindly help promote the MicroProfile related content at EclipseCon Community Day. Putting out something along the following lines a few times until October 24th would be very helpful. Registration is going on right now, so boosting registered attendees is the main goal. The main CTA link is this: https://www.eclipsecon.org/2022/jakarta-ee-community-day. I would say now is the right time at least for the first push.

"EclipseCon Community Day is a great place to learn about what is coming in MicroProfile and how you can contribute. Check out the agenda and register now - space is limited! https://www.eclipsecon.org/2022/jakarta-ee-community-day"

**Comment by m-reza-rahman** [comment]
Tagging @rstjames as requested. Looks like I am not a committer and so cannot assign the issue. Should I be a committer, @Emily-Jiang?

**Comment by Emily-Jiang** [comment]
> Tagging @rstjames as requested. Looks like I am not a committer and so cannot assign the issue. Should I be a committer, @Emily-Jiang?

@m-reza-rahman we can add you to the list of contributors so that you can assign/be assigned to the issues, I think. As a WG memember, Microsoft is eligible for a committer. You can email emo and put forward one rep for being a committer of MP.

**Comment by m-reza-rahman** [comment]
Does it have to be only one committer or can both Ed and I be committers?

**Comment by Emily-Jiang** [comment]
Only one committer granted to one WG member.

**Comment by m-reza-rahman** [comment]
Hi @edburns, can you go through the process to become a MicroProfile committer please? Since we can only have one, I think you would be better for this.

**Comment by rstjames** [comment]
@m-reza-rahman I will push this visual if you are ok with it. 
![MicroProfile-eclipsecon-2022](https://user-images.githubusercontent.com/12132146/195104965-ff754d5c-f5fa-4348-9edd-8b19767250a2.png)

**Comment by rstjames** [comment]
It is scheduled to go out Wed 19th and 23rd (day before the conference)
