### ISSUE TITLE
[Compatible Implementations Announcement] WildFly 26.1.2.Final

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#723]
**Organization Name**
 Name: [Red Hat](https://www.redhat.com/en)
 
 **Product Version and download URL**
 URL: [WildFly 26.1.2.Final](https://github.com/wildfly/wildfly/releases/download/26.1.2.Final/wildfly-26.1.2.Final.zip)
 
 **Java runtime used to run the implementation**
  [TCK results](https://github.com/wildfly/certifications/blob/MP4.1/WildFly_26.1.2.Final/microprofile-4.1/microprofile-4.1-full-certification.adoc) - JDK 8, 11, 17

 **Media Description**
 280 chararters includes the organization's name & URL or blog

Not sure what to add here. A short announcement is all right.

 **Design Card**  (for MicroProfile designer)

 **Notes**
 
- Will this also add the implementation to the certification page? - https://microprofile.io/compatible/4-1/

**Comment by rstjames** [comment]
@xstefank to make sure I understand. This is only for 4.1 ?

**Comment by xstefank** [comment]
@rstjames correct, the last javax release.

**Comment by rstjames** [comment]
updated
