### ISSUE TITLE
Welcome Microsoft to MicroProfile community

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#724]
MicroProfile community should create a blog to welcome Microsoft to the community and link to [this](https://azure.microsoft.com/en-us/blog/microsoft-joins-jakarta-ee-and-microprofile-working-groups-at-eclipse-foundation/) blog

See [an example](https://blogs.eclipse.org/post/tanja-obradovic/microsoft-new-member-jakarta-ee-working-group) of this in Jakarta EE.

The blog can then be tweeted.

**Comment by m-reza-rahman** [comment]
This would be great! Thanks @Emily-Jiang!

**Comment by aeiras** [comment]
> MicroProfile community should create a blog to welcome Microsoft to the community and link to [this](https://azure.microsoft.com/en-us/blog/microsoft-joins-jakarta-ee-and-microprofile-working-groups-at-eclipse-foundation/) blog
> 
> See [an example](https://blogs.eclipse.org/post/tanja-obradovic/microsoft-new-member-jakarta-ee-working-group) of this in Jakarta EE.
> 
> The blog can then be tweeted.

hola @Emily-Jiang, 

I have untagged @rstjames from this ticket. 
A reminder to you and all that blogs about new Members joining MP ought to be written by the member. 
The member can follow AJUG and GSJUG's blog https://microprofile.io/category/community/mpwg-onboarding-members/

-- 

**Why?** 
B/c MPWG doesn't have a hired writer nor copy/editor and cannot speak for its members on why joining MP was right for them. 

-- I hope this helps with current member and future advice during onboarding. 

The guidelines for onboarding are [here ](https://microprofile.io/workinggroup/)

**Comment by m-reza-rahman** [comment]
Unfortunately, it would not really be appropriate for me to add anything on behalf of Microsoft on top of Julia's announcement and it would not be appropriate to syndicate Julia's announcement. This can be closed if needed. However, perhaps a suitable solution is to simply tweet Julia's announcement from the official Twitter handle?

**Comment by aeiras** [comment]
https://azure.microsoft.com/en-us/blog/microsoft-joins-jakarta-ee-and-microprofile-working-groups-at-eclipse-foundation/

@rstjames, thank you in advance for helping close this ticket with the below action. 

- MP Social media push of MSFT's formal letter. 

**recommended Text** or similar -  @m-reza-rahman, you are most welcome to improve the message. 

_@Microsoft joins the @JakartaEE and @MicroProfileIO Working Groups. "We believe our experience running @java workloads in the cloud will be valuable to the working groups,..." by Julia Liuson. 

Read more [Link]_

**Comment by m-reza-rahman** [comment]
I think this is perfect. Much appreciated!

**Comment by m-reza-rahman** [comment]
I think this can be closed now, @rstjames?

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1591098778253074432?s=20&t=Fkt9kcCZw3wIEXyQkQLSfg
