### ISSUE TITLE
[Committer & Contributor Swag ] MP Swag Package 2022

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#727]
On Sept 20th, an email to the 53 MP committers was sent to microprofile-dev@eclipse.org

Subject title: [Committers MPSwag] Hoody, T-shirt & Stickers - ThankYouGift!

We have received many positive replies accepting the gift. 
Next step is to submit the order. I recommend we provide a second change with deadline 1 week to remind those who didn't request and wish to wear MP swag to secure the gift.

**Comment by emecas** [comment]
#717  is almost complete

**Comment by aeiras** [comment]
@emecas this is great. I will close this ticket then since it was created to pull you into latest updates and check on 2021 swag updates.  I think you created a ticket for swag 2022 matters. 👍

**Comment by aeiras** [comment]
Re-opened b/c we need to re-send the message to committers to close the message sent on Sept 20th. The delay is on the navigating on shipping the 2021 swag to Members, etc. Now resolved.

**Comment by aeiras** [comment]
I sent an update message to Committers on 12/15 about the current status of swag. 

Copy/paste email message:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/10731224/207985137-d5a2932e-fa2b-42e7-8825-b904e062a366.png">

**Comment by m-reza-rahman** [comment]
This is being sorted. I will close this once the last of the 2022 swag is sent out of the warehouse, hopefully very shortly.

**Comment by aeiras** [comment]
https://docs.google.com/spreadsheets/d/1wZzuKyniHy1PEuKm2OAZ9laKquyZ0XiscEZb65BHvoE/edit#gid=0

**Comment by m-reza-rahman** [comment]
Hi @emecas, is the last of the 2022 swag sent out? If so I would like to close this issue out so we can move on. For any residual problems, we could always open new issues if really needed. This has been hanging around forever.

**Comment by emecas** [comment]
> Hi @emecas, is the last of the 2022 swag sent out? If so I would like to close this issue out so we can move on. For any residual problems, we could always open new issues if really needed. This has been hanging around forever.

Hi Reza , I am not sure if I am could be mixing subjects here, but there are two lines in pending in the shipping spreadsheet, I will update for any clarification / outcome as late for the end of this week , then if any residual problematic situation keep in pending we can open individual issues. thanks for following up!!!

**Comment by m-reza-rahman** [comment]
OK. Can I kindly ask you to close this once you feel the 2022 swag is sorted?

**Comment by Emily-Jiang** [comment]
I confirm that the MP speakers at JavaLand and DevNexus 2023 all got the swags and had them distributed nicely. The qulity of the SWAGs are great. The size small is like medium size.
