### ISSUE TITLE
[Blog Contribution] More MicroProfile 6 and Jakarta EE 10 features make their debut in Open Liberty 22.0.0.12-beta!

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#728]
**[MicroProfile.io WordPress](https://github.com/microprofile/wpsite)**

 **MicroProfiler**
 To new Contributors who need to gain access to the WordPress site, please provide:
- [ ]   Name:
- [ ]   Email:

**Content copy/edit review (available & optional)
- [ ]  [Draft post](https://microprofile.io/wp-admin/post.php?post=7068&action=edit) 
 
 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
 - [ ]  Michal Broz, Liberty Release Architect, on the latest @OpenLibertyIO beta release, inc MicroProfile 6.0 features: MicroProfile JSON Web Token (JWT) 2.1, inc simple JWT validation, and MicroProfile Metrics 5.0, inc user-defined metric registry scopes.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by emecas** [comment]
Landing here!!

**Comment by emecas** [comment]
@aeiras  @lauracowen, I would like to get some context ,  please correct me if I am wrong,  It seems like the body for this blog post is just a link to an external blog.

The preview looks like:
![image](https://user-images.githubusercontent.com/849502/199814891-f203a562-d7b2-48ed-b7c5-ec8f508c64e8.png)

For this particular case the yellow box is a link to:  https://openliberty.io/blog/2022/10/27/](https://openliberty.io/blog/2022/10/27/22.0.0.12-beta.html
![image](https://user-images.githubusercontent.com/849502/199815138-d70f5042-81d8-4599-b65f-aec3ea89db76.png)

Is that correct? 

Thanks

**Comment by lauracowen** [comment]
Yes, that's correct. It's a redirect (option 2 in the instructions) to the original article hosted on openliberty.io

I didn't have a suitable image to go with it but I've just found a code sample and screenshotted that and added it to the article. So I think it shouldn't render with the yellow box when it's published now.

**Comment by emecas** [comment]
Regarding to the text and link, it seems we are all set to post, now I only wondering about the Design Card part and that what you @lauracowen mentioned about the image rendering 

CC @aeiras & @rstjames

**Comment by lauracowen** [comment]
I think the image is now fine - I don't think there's any problem there to worry about.

**Comment by emecas** [comment]
This was/is the list of potential problems and improvements, the main subjects are about key phrase, links and text length, I added a keyphrase, please review and comment:

**Problems and improvements**

- [x]   Keyphrase distribution: Have you evenly distributed your focus keyphrase throughout the whole text? 
- [ ]   Outbound links: No outbound links appear in this page. Add some!
- [ ]   Internal links: No internal links appear in this page, make sure to add some!
- [x]   Keyphrase length: No focus keyphrase was set for this page. Set a keyphrase in order to calculate your SEO score.
- [ ]   Meta description length: No meta description has been specified. Search engines will display copy from the page instead. Make sure to write one!
- [ ]   Text length: The text contains 29 words. This is far below the recommended minimum of 300 words. Add more content.
- [ ]   SEO title width: The SEO title is wider than the viewable limit. Try to make it shorter.
- [ ] 	Image Keyphrase: Images on this page do not have alt attributes that reflect the topic of your text. Add your keyphrase or synonyms to the alt tags of relevant images!

**Comment by lauracowen** [comment]
Hi, this post is being submitted under the ["Case 2" instructions](https://github.com/microprofile/wpsite) which don't mention setting keyphrases etc. The Yoast keyphrase tool (and all the other tools on the Wordpress editor form) won't work because the post is published elsewhere. This Wordpress entry will only provide a link to another URL (aggregator-style) when published.

**Comment by emecas** [comment]
> Hi, this post is being submitted under the ["Case 2" instructions](https://github.com/microprofile/wpsite) which don't mention setting keyphrases etc. The Yoast keyphrase tool (and all the other tools on the Wordpress editor form) won't work because the post is published elsewhere. This Wordpress entry will only provide a link to another URL (aggregator-style) when published.

In that case the previous improvements suggested do not applied.  Thanks for the clarification  and providing the resource to verify.

Approved after checking all  criteria for approving blog posts:

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [x]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
        Screenshot-2022-11-04-at-11.02.08-e1667559834267.png  - 55 KB  - 955 by 396 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by lauracowen** [comment]
Thanks. @emecas Are you able to publish it yourself or does someone else need to do it?

**Comment by emecas** [comment]
> Thanks. @emecas Are you able to publish it yourself or does someone else need to do it?

I was not sure if you were expecting from me to do the final click to publish, I am going to do it right now

**Comment by emecas** [comment]
Status: Published
Permalink: https://microprofile.io/2022/12/07/microprofile-6-liberty-22-0-0-12-beta/

**Comment by aeiras** [comment]
Hola Emerson and Laura, 

On Monday, we had the last marketing meeting on Monday and the contributed blogs were quickly discussed. 
Emerson, are you still ok to review and publish them if they match the crossposting suggested guidelines and content? :) 

Social media is not mandatory, so closing the issues upon publishing the link in the ticket suffices. 
Happy to Q&A with both of you to make sure we tackle the blogs before the 16th.

**Comment by emecas** [comment]
@aeiras thanks for confirming, yes, I will review and publish them

On the other hand, the option for closing this ticket is not available for me!

**Comment by aeiras** [comment]
@lauracowen can close it :) 

Have fun, Emerson.  Thank you for rocking your onboarding into content review and publication on MP Blog Stewardship. 
Laura is also a content reviewer and contributor, so you are in good hands for Q&A.

**Comment by lauracowen** [comment]
Closing now. Thanks @emecas and @aeiras. Let me know if there's anything you need for the others I've submitted. I appreciate there are several (and probably a couple more coming soon), so just say if there are any you think aren't relevant enough (I try to make sure I only submit relevant ones but I wanted to give you the options).

**Comment by aeiras** [comment]
Hola Laura, 

You can contribute as many blogs that share MP content as you and your team create. There are no limits. Today and always, Laura! 

Thank you for caring to share and thanks Emerson for rocking on review and publishing!  ossFUN, I feel inspired by you two :)

**Comment by aeiras** [comment]
Oh and never stress about relevance. Thats why the review is there. There are blogs that have not been accepted, so it is always a possible when we choose to step in and contribute. Cheers.
