### ISSUE TITLE
[Blog Contribution] Liberty InstantOn startup for cloud native Java applications

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#729]
**[MicroProfile.io WordPress](https://github.com/microprofile/wpsite)**

 **MicroProfiler**
 To new Contributors who need to gain access to the WordPress site, please provide:
- [ ]   Name:
- [ ]   Email:

**Content copy/edit review (available & optional)
- [ ]  [Draft](https://microprofile.io/wp-admin/post.php?post=7072&action=edit) 
 
 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
 Tom Watson (GH: tjwatson) & Josh Dettinger (GH: dettmoney) of the Open Liberty development team introduce Liberty InstantOn (beta), a checkpoint/restore solution to fast Java startup in the cloud. Based on Linux CRIU in collab w/ @openj9.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by emecas** [comment]
Landing here!!

**Comment by emecas** [comment]
Approved and published 

Permalink: [https://microprofile.io/2022/12/08/liberty-instanto…ava-applications/](https://microprofile.io/2022/12/08/liberty-instanton-startup-for-cloud-native-java-applications/)

Added tags:  `performance `and `cloud native`

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [x]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
        instantonperf.png - 91 KB - 1993 by 1168 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by lauracowen** [comment]
Thanks, will close the issue.
