### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by cajasmota** [microprofile/microprofile-marketing#73]
Jorge Cajas - jac.mota@gmail.com

**Comment by aeiras** [comment]
Hola Jorge, que chevere verte en este Repo 👍  @Motojo  
You just became the 36 MP WordPress Contributor. Es realmente divino que escojes representar Latin Armada de una manera genial! :) 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/10731224/56764479-9f11b980-6759-11e9-9923-2de11c546e3a.png">

**Comment by cajasmota** [comment]
Gracias Ameilia @aeiras !

Hoy por fin tuve tiempo de escribir algo, espero sea aprobado y vamos a llenar ese blog de contenido en español :smile:  (y tambien en inglés para que el contenido sea útil para todos)

**Comment by aeiras** [comment]
@Motojo Hola desde Tokyo.  
Donde esta el link de tu articulo?  abrazos y que chereve que tomaste tiempo para compartir lo que estas aprendiendo con MP. :)

**Comment by aeiras** [comment]
Reminder, once you submit your blog you must submit a new issue with the link of the blog, always.

**Comment by cajasmota** [comment]
I didn't knew about the issue for every post, sorry for that, I will create the issue rigth now :smile:
