### ISSUE TITLE
[Blog Contribution] A brief history in maker projects of a cloud-native Java runtime

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#730]
**[MicroProfile.io WordPress](https://github.com/microprofile/wpsite)**

 **MicroProfiler**
 To new Contributors who need to gain access to the WordPress site, please provide:
- [ ]   Name:
- [ ]   Email:

**Content copy/edit review (available & optional)
- [ ]  [Draft](https://microprofile.io/wp-admin/post.php?post=7073&action=edit) 
 
 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
 Laura Cowen (GH: lauracowen) tells a brief history of @OpenLibertyIO, the cloud-native Java runtime, through the medium of maker projects, which were mostly built using MicroProfile & @JakartaEE technologies.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog
 
 **Notes**
 To help with everything

**Comment by emecas** [comment]
Landing here!!

**Comment by emecas** [comment]
Approved and published

Permalink: [https://microprofile.io/2022/12/08/history-maker-pr…ive-java-runtime/](https://microprofile.io/2022/12/08/history-maker-projects-of-cloud-native-java-runtime/)

Added tag(s):  ` Raspberry Pi`

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [x]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
        spacerover.jpeg - 254 KB -  1200 by 675 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by lauracowen** [comment]
Thanks. Closing.
