### ISSUE TITLE
[Blog Contribution] Run a MicroProfile application as a serverless function with CloudEvents in IBM Cloud Code Engine

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#731]
**[MicroProfile.io WordPress](https://github.com/microprofile/wpsite)**

 **MicroProfiler**
 To new Contributors who need to gain access to the WordPress site, please provide:
- [ ]   Name:
- [ ]   Email:

**Content copy/edit review (available & optional)
- [ ]  [Draft](https://microprofile.io/wp-admin/post.php?post=7069&action=edit) 
 
 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
Alex Butcher (GH: abutch3r) and @emilyfhjiang demonstrate how to run a MicroProfile app on @OpenLibertyIO as a serverless function on IBM Cloud Code Engine.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by emecas** [comment]
Landing here!!

**Comment by emecas** [comment]
@lauracowen This one is missing the link, also the image looks different to the other 3 , it is OK if that is the purpose, just verifying

**Comment by lauracowen** [comment]
Oops, sorry, I've added the link in now.

In what way does the image look different? I have uploaded a smaller, cropped version of it in case it was just the image dimensions. Could you paste a screenshot here if it still looks odd, pls?

**Comment by emecas** [comment]
Approved and published 

Permalink: https://microprofile.io/2022/12/09/microprofile-serverless-function/

Added tags:  `docker`  `serverless` and `cloud native`

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [x]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
         codeengine2.png - 116 KB - 2942 by 895 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by lauracowen** [comment]
Great, thank you.
