### ISSUE TITLE
[Infra] MP Community drive access - Edit - to Emerson

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#732]
@emecas, 

On Nov 2nd, you have been granted Edit access to help manage and maintain the [MP Community Drive]( https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8) for your continues valuable work and dedication. 

****Infra investory sheet of MicroProfilers**  has been updated. https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1040459762**

Your #OSS actions are truly amazing!

**Comment by emecas** [comment]
Thanks @aeiras , my first contributions to the folder: 2 invoices from Burbank Shipping Center :) 
https://github.com/eclipse/microprofile-marketing/issues/717#issuecomment-1299462410

**Comment by aeiras** [comment]
Smiling, you know how best and most efficiently to close tickets, MicroProfiler, yeayyy!!!!

**Comment by aeiras** [comment]
> Thanks @aeiras , my first contributions to the folder: 2 invoices from Burbank Shipping Center :)
> [#717 (comment)](https://github.com/eclipse/microprofile-marketing/issues/717#issuecomment-1299462410)

remember to add this ticket + actions you have done to the call minutes under Swag. :) or misc section. your call! :)
