### ISSUE TITLE
 [General: Mktg-Call Steward] Emerson - November 2022

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#733]
MicroProfilers are welcomed to use this ticket to communicate with us on anything MP in all November 2022 that doesn't belong to its own git ticket(s).

MicroProfilers' proactive feedback on Steward work is always welcomed & appreciated. Proactive feedback is preferred as well! :)

I will use this ticket to communicate on November MP stuff as well!

**Comment by aeiras** [comment]
Hola Emerson, 

[emecas](https://github.com/emecas)

Today, Mitia covered you. He did great. I have adjusted the Stewards sheet to include his support. 

If you can, would you like to co-lead the last call of 2022 with me? December 5th?
1) sharing the screen, recording the call
2) talking about agenda items
3) etc

No pressure!
