### ISSUE TITLE
[Website] Mention product versions in compatibility pages

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#735]
Hi, in https://microprofile.io/compatible/4-1/ or https://microprofile.io/compatible/5-0/ we should be mentioning the individual product versions not only the names of the products. This is done in https://microprofile.io/compatible/4-1/ if you open Payara tab but it's not done in WildFly, Quarkus, and OpenLiberty. We should standardize this is included every time new implementation is added to the certification site. This information is always available in the announcement issue or CCR.

**Comment by aeiras** [comment]
+ 1 Martin.

**Comment by rstjames** [comment]
@xstefank was this individual product versions information ever given to have on the site before? 

If we want this info for WildFly, Quarkus, and OpenLiberty please provide the information needed to put on the site.

**Comment by xstefank** [comment]
@rstjames this is available in the CCRs, which will require some work to collect. I don't have the bandwidth for it now, but I can help you with it later.

**Comment by rstjames** [comment]
@xstefank ok when you have time, just put all info here and I will update the site.

**Comment by aeiras** [comment]
Hey you two, 

given that Martin is aware of what is needed, I am closing this ticket as each implementation adjustment will need its own ticket, etc.

**Comment by xstefank** [comment]
@aeiras I don't think we need issue for each implementation. We just need to add existing versions to existing certifications.

**Comment by xstefank** [comment]
So here's it:

MicroProfile 4.1

Open Liberty 
Open Liberty 21.0.0.9 -  https://github.com/eclipse/microprofile/issues/246

Quarkus 
Quarkus 2.7.2.Final - https://github.com/eclipse/microprofile/issues/247

Payara 
Payara Server Enterprise 5.37.0 - https://github.com/eclipse/microprofile/issues/249
Payara Server Enterprise (Web Profile) 5.37.0 - https://github.com/eclipse/microprofile/issues/250
Payara Server Community 5.2022.2 - https://github.com/eclipse/microprofile/issues/251
Payara Server Community (Web Profile) 5.2022.2 - https://github.com/eclipse/microprofile/issues/252
Payara Server Enterprise 5.38.0 - https://github.com/eclipse/microprofile/issues/253
Payara Server Enterprise (Web Profile) 5.38.0 - https://github.com/eclipse/microprofile/issues/254
Payara Server Enterprise 5.39.0 - https://github.com/eclipse/microprofile/issues/255
Payara Server Enterprise (Web Profile) 5.39.0 - https://github.com/eclipse/microprofile/issues/256
Payara Server Enterprise 5.40.0 - https://github.com/eclipse/microprofile/issues/261
Payara Server Enterprise (Web Profile) 5.40.0 - https://github.com/eclipse/microprofile/issues/262
Payara Server Enterprise 5.41.0 - https://github.com/eclipse/microprofile/issues/263
Payara Server Enterprise (Web Profile) 5.41.0 - https://github.com/eclipse/microprofile/issues/264
Payara Server Enterprise 5.42.0 - https://github.com/eclipse/microprofile/issues/267
Payara Server Enterprise (Web Profile) 5.42.0 - https://github.com/eclipse/microprofile/issues/268
Payara Server Community 5.2022.3 - https://github.com/eclipse/microprofile/issues/269
Payara Server Community (Web Profile) 5.2022.3 - https://github.com/eclipse/microprofile/issues/270
Payara Server Enterprise (Web Profile) 5.43.0 - https://github.com/eclipse/microprofile/issues/272
Payara Server Enterprise 5.43.0 - https://github.com/eclipse/microprofile/issues/273
Payara Server Enterprise 5.44.0 - https://github.com/eclipse/microprofile/issues/277
Payara Server Enterprise (Web Profile) 5.44.0 - https://github.com/eclipse/microprofile/issues/278
Payara Server Enterprise 5.45.0 - https://github.com/eclipse/microprofile/issues/285
Payara Server Enterprise (Web Profile) 5.45.0 - https://github.com/eclipse/microprofile/issues/286
Payara Server Community 5.2022.4 - https://github.com/eclipse/microprofile/issues/287
Payara Server Community (Web Profile) 5.2022.4 - https://github.com/eclipse/microprofile/issues/288
Payara Server Community 5.2022.5 - https://github.com/eclipse/microprofile/issues/301
Payara Server Community (Web Profile) 5.2022.5 - https://github.com/eclipse/microprofile/issues/302
Payara Server Enterprise 5.46.0 - https://github.com/eclipse/microprofile/issues/303
Payara Server Enterprise (Web Profile) 5.46.0 - https://github.com/eclipse/microprofile/issues/304

WildFly
WildFly 26.1.2.Final - https://github.com/eclipse/microprofile/issues/274

Launcher
Launcher 3.0 - https://github.com/eclipse/microprofile/issues/265


------------------------
MicroProfile 5.0

Open Liberty
22.0.0.1 - https://github.com/eclipse/microprofile/issues/245

Payara
Payara Server Community (Web Profile) 6.2022.1.Alpha2 - https://github.com/eclipse/microprofile/issues/259
Payara Server Community 6.2022.1.Alpha2 - https://github.com/eclipse/microprofile/issues/260
Payara Server Community 6.2022.1 - https://github.com/eclipse/microprofile/issues/289
Payara Server Community (Web Profile) 6.2022.1 - https://github.com/eclipse/microprofile/issues/290
Payara Server Community 6.2022.2 - https://github.com/eclipse/microprofile/issues/305
Payara Server Community (Web Profile) 6.2022.2 - https://github.com/eclipse/microprofile/issues/306

WildFly
WildFly Preview 26.0.0.Final - https://github.com/eclipse/microprofile/issues/284

Launcher
Launcher 4.0 - https://github.com/eclipse/microprofile/issues/266

Helidon
Helidon 3.0 - https://github.com/eclipse/microprofile/issues/291

Apache TomEE
Apache TomEE 9.0.0.RC1 - https://github.com/eclipse/microprofile/issues/283


------------------------
MicroProfile 6.0
Open Liberty 22.0.0.13-beta - https://github.com/eclipse/microprofile/issues/294

I hope I got everything but if not them people will shout.
I'll leave how you want to put this on the site up to you. Here is how it's done in jakarta - https://jakarta.ee/compatibility/certification/10/

**Comment by aeiras** [comment]
wow, you are wonderful @xstefank! 

@rstjames thank you for tackling this ticket.

**Comment by rstjames** [comment]
@aeiras @All these should be put in the compatible table under Open Liberty , Quarkus and Payara?? 

For each "row" I need name of product (is there) , java versions compatible with, link to certification results and download link. 

It would take me two year to find all these links for each item :) 

Thanks you

**Comment by aeiras** [comment]
Gotcha, @rstjames.

@@xstefank the ticket is back to you. Happy wknd, MicroProfiler!

**Comment by xstefank** [comment]
@rstjames `@ALL` doesn't work here, you need to mention me directly ;).

Thanks @aeiras.

Every CCR (link next to the product in my last comment) has first comment in the issue the actual CCR, e.g., https://github.com/eclipse/microprofile/issues/247#issue-1159850689. 

java versions compatible with -  Java runtime used to run the implementation
link to certification results - Public URL of TCK Results Summary
and download link -  Product Name, Version and download URL (if applicable)

That should be everything you need. If it's not provided in the CCR then I can't provide the information and we need to go to the individual team/company that made the CCR.

**Comment by rstjames** [comment]
@xstefank 

I see in each ticket link the link to certification results - Public URL of TCK Results Summary but 

I DO NOT see the java versions. Without this I can not update the pages on MP.

**Comment by xstefank** [comment]
@rstjames It's in the [CCR](https://github.com/eclipse/microprofile/issues/247#issue-1159850689) under Java runtime used to run the implementation.

**Comment by rstjames** [comment]
@xstefank example: https://github.com/eclipse/microprofile/issues/255 where is the java version?

**Comment by rstjames** [comment]
unless this is the version number? ?
Java runtime used to run the implementation:
Zulu JDK Runtime Environment (version 8.0.252)??

**Comment by rstjames** [comment]
@xstefank  @aeiras All should be updated

**Comment by aeiras** [comment]
Thanks @rstjames. 

Hey Martin @xstefank, 

Please review and follow up with closing this ticket or adding further improvements... :)

**Comment by xstefank** [comment]
Thanks @rstjames. I see that Payara only is in the way that I would think we should have everything. Even if there is only one certification per product/version we should still always include the version on the site. So for instance in MP 4.1 https://microprofile.io/compatible/4-1/ for WildFly it should be WildFly 26.1.2.Final. I think that readers might find it still confusing if Payara has versions and anything else doesn't. Thanks anyway, great work so far.

**Comment by Emily-Jiang** [comment]
The process for getting runtime included was documented here. Did the missing versions submit a github issue to have them listed? I think we need to make sure they follow the process. Otherwise, it is not sustainable as a person has to go through the CCR and match the page accordingly. It is the runtime owner's responsibility to have their runtime listed.

**Comment by xstefank** [comment]
@Emily-Jiang everyone followed the process. We just don't have versions stated on the site except Payara that @rstjames already fixed and he will probably fix the rest soon. I hope that from now on, when we add a new product/version to the site it will be included with both Product Name and Product Version.

**Comment by aeiras** [comment]
Hey Martin @xstefank, 

@Emily-Jiang is correct with her feedback.  Allow me to project my thoughts in this particular ticket. 

I think you helping catch up the missing compatible products in the last 2 releases (not counting Mp 6.0)  is deeply kind. 

After this ticket,  you are not expected to repeated covering the tracking as it is not scalable neither for you nor the others, who must own the responsibility as implementors. 

The MPWG Compatible process exists so that the job lands and is held by those behind the work. If steps are missed, we could **all** (who notice) remind those groups to follow the process.   Yet we cannot enforce their follow up actions.   

Most importantly, we ought to not own their lack of action by doing the work ourselves.  

Open Source is truly like a huge puzzle, creating many pieces for all to see.  Each puzzle piece is (most often) taken and moved into place by the responsible parties. It is what makes it fun and sustainable. 

Your contributions are valuable and your care is noticed by all.

**Comment by xstefank** [comment]
Thanks @aeiras. This is also how I understood this. This issue is only about fixing the currently published compatible implementations on the site (incl MP 6.0 ;)).

Every time the CCR is completed, the CCR creator should open an issue similar to [this](https://github.com/eclipse/microprofile-marketing/issues/748) where the CCR should be linked with all relevant information. Maybe consider making it required in the issue template. So from now on, when it gets published on the site, it should be published with the version.

**Comment by aeiras** [comment]
It is a required step in the becoming compatible. Please check the guidelines here https://microprofile.io/compatible/ under Certification Process. If you wish, you could help improve it. :) 

In the other checklist, it should also be there already. I merged PRs about it but it has been too long. Can you check if anything is missing. Thank you!

**Comment by xstefank** [comment]
I fixed what I meant in the above PR.

**Comment by aeiras** [comment]
> I fixed what I meant in the above PR.

Merged. You are amazing, @xstefank :)

**Comment by xstefank** [comment]
@rstjames this issue got a little sidetracked. Just want to ask if you are able to fix remaining certifications as I mentioned in https://github.com/eclipse/microprofile-marketing/issues/735#issuecomment-1401502339.

**Comment by rstjames** [comment]
@xstefank there is a lot going on above. What is the issue?

**Comment by rstjames** [comment]
@xstefank Sorry I do not understand what you are asking for in comment 735.

**Comment by xstefank** [comment]
@rstjames that's ok. So if you open https://microprofile.io/compatible/4-1/ and click-open **Payara** that is what I would like to see everywhere. Each line has a version next to the product name. Now if you open **Quarkus**, **Open Liberty**, of **WildFly** you don't see the product versions next to the product name on the line where there is the link to CCR and download. So I would like to see what is done in Payara also in Quarkus, OL, and WildFly, and of course for all CCR for MP 4.1, 5, and 6.

Also, if you can point me where the site lives and I can give this a shot too.

**Comment by rstjames** [comment]
Ok I understand. Thank you for explaining it more but when implementing all of this others did not want the version next to the name... I will bring this up on the next marketing call.

**Comment by aeiras** [comment]
@rstjames this ticket is added under Website space on the minutes.

**Comment by xstefank** [comment]
Let me know if I should explain why the version stated there is important ;)

**Comment by aeiras** [comment]
Do explain, Martin. Always better to put your thoughts in writing, especially via tickets like this. Gracias, MicroProfiler!

**Comment by xstefank** [comment]
We want to certify multiple implementations against the same platform version, so it is important to see that on the certification site that the team/company made effort to maintain MP support through several releases. Also we have a lot of releases (Quarkus every 2 weeks, WFLY every 3 months) if I check the site under MP 4.1 and I see WFLY, ok great, but which version? WFLY 27 if on jakarta namespace so as I user I need to start digging. I believe this should be directly on the site so I can see that if I want to use WFLY with MP 4.1 I need to pick 26. Also it is possible that the implementation stops supporting MP platform and the site gives the impression that the latest release still supports it.

**Comment by m-reza-rahman** [comment]
This is sorted. @rstjames should be adding versions retroactively to the site soon.

**Comment by rstjames** [comment]
All compatible products have a version.
