### ISSUE TITLE
[Translation] Release MicroProfile 6.0 - Release Blog Post German Translation

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#737]
Once third task in #726 about: Draft a release announcement blog post using template (technical person) is complete, add release blog post in German

**Comment by dalexandrov** [comment]
I'll pick this :)

**Comment by rstjames** [comment]
@emecas @dalexandrov Where are we at one this? Thank you :)

**Comment by m-reza-rahman** [comment]
MicroProfile 6 is getting pretty stale. If we really don't have time for this, it may be best to just drop this if it gets too far past February.

**Comment by dalexandrov** [comment]
@rstjames Please publish

**Comment by dalexandrov** [comment]
Article - https://docs.google.com/document/d/1-UlOJWJnpdc_mcP-7ubroFIeIEnzwZb10Pabv6akCr8/edit

Presentation – https://docs.google.com/document/d/1-UlOJWJnpdc_mcP-7ubroFIeIEnzwZb10Pabv6akCr8/edit

**Comment by dalexandrov** [comment]
Twitter:

```
#MicroProfileReleaseAnnouncement: #Microprofile Version 6.0 veröffentlicht!
Es unterstützt @JakartaEE 10 Core Profile. 📢 🚀

Um mehr zu lernen:

#ByCommunityForCommunity #OpenSource
```

**Comment by dalexandrov** [comment]
Picture:

```
MicroProfie Version 6.0 ist veröffentlicht!
```

**Comment by rstjames** [comment]
done

**Comment by aeiras** [comment]
wonderful, @rstjames. When will the media post go out?

**Comment by aeiras** [comment]
I will re-open this ticket and the other b/c it is helpful to at least add the Twitter post to help with closing the task. 
This is part of the new guidelines on how to make Release translations that Mitia wrote, which I still  need to review and for that, all the examples must exist. Thanks!

**Comment by emecas** [comment]
Tweet : https://twitter.com/MicroProfileIO/status/1650436969686609921

**Comment by aeiras** [comment]
@emecas, I added you as a contributor to the blog. :)
