### ISSUE TITLE
[Translation] Release MicroProfile 6.0 - Release Blog Post Spanish Translation

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#738]
Once third task in #726 about: Draft a release announcement blog post using template (technical person) is complete, add release blog post in Spanish

**Comment by emecas** [comment]
Since review process at #726 have been completed, starting Spanish translations for the related docs 

WIP - Spanish copies are available here:

Blog Post:    [[Spanish] MicroProfile 6.0 - Blog post](https://docs.google.com/document/d/1DY5ZWyHv_hB5GU2hWjGbpWZ8sPnbRWNuiESmf4x_fNk/edit)

Presentation:  [[Spanish] MicroProfile 6.0](https://docs.google.com/presentation/d/1YXifDyY8H2MwcQThemxrJlNyzcW2Hpkt/edit#slide=id.p1)

**Comment by aeiras** [comment]
I volunteer to review the documents by this Thursday, so that they can be put into the website on Thursday, etc @emecas :) You rock!!!

**Comment by emecas** [comment]
> I volunteer to review the documents by this Thursday, so that they can be put into the website on Thursday, etc @emecas :) You rock!!!

thank you @aeiras , I am done with both translations!!! :)

**Comment by aeiras** [comment]
@emecas, 

Great job on the 2 documents. I left comments on the documents. Do pull me in if you are blocked.  If there is no blockage, once you are done with the review, please translate the English tweet into Spanish, https://twitter.com/MicroProfileIO/status/1612780709004939264?s=20&t=I_3ylHSOeFCbBgRpmErIPw and pull @rstjames so that media can be done with a card in Spanish as well. :)

**Comment by emecas** [comment]
> @emecas,
> 
> Great job on the 2 documents. I left comments on the documents. Do pull me in if you are blocked. If there is no blockage, once you are done with the review, please translate the English tweet into Spanish, https://twitter.com/MicroProfileIO/status/1612780709004939264?s=20&t=I_3ylHSOeFCbBgRpmErIPw and pull @rstjames so that media can be done with a card in Spanish as well. :)

Thanks for the review.

1) I have accepted your suggestions in the blog post document and updated the chart (figure 1) with the translated version in the presentation.


2) Tweet in Spanish (@rstjames):

-----

#MicroProfileReleaseAnnouncement: ¡Se lanza #Microprofile 6.0! Adopta @JakartaEE 10 Core Profile. 📢 🚀

Más información http://ow.ly/u6As50MmsZR

#ByCommunityForCommunity #OpenSource

-----

For the card you could just replace `Now Available` by `Disponible` in here:

![image](https://user-images.githubusercontent.com/849502/211934280-f6deee39-a226-43c3-b218-f41f97fc6189.png)

Any other text could be keep as it.

**Comment by aeiras** [comment]
Amazing turnaround, Emerson. Let's publish your blog today. :) 
Use the same categories as the original posting to make sure it shows under the Compatible page under blogs as well. 

@rstjames, can you please help with the new Spanish card and media push this week? :)

**Comment by aeiras** [comment]
@emecas there is a new blog contributed by IBM, I wonder if you saw it and continue to be interested in being the Contributing content Stewward for MP? Saying no is ok. :)

**Comment by emecas** [comment]
> Stewward

Sure, let me know what is the issue, I am not aware of it right now , I will review it!!

**Comment by aeiras** [comment]
@emecas are you watching this repo?  
task is https://github.com/eclipse/microprofile-marketing/issues/752

**Comment by rstjames** [comment]
@emecas will you be posting the mp 6 spanish blog post? This will need to be done before I can send any tweets out. 
I will create the draft post with images. 
![MicroProfile-release-6 0_spanish](https://user-images.githubusercontent.com/12132146/213266229-da4d2493-6a80-497c-9997-0b69eb454c6e.jpg)

**Comment by emecas** [comment]
> @emecas will you be posting the mp 6 spanish blog post? This will nee to be done before I can send any tweets out. I will create the draft post with images. ![MicroProfile-release-6 0_spanish](https://user-images.githubusercontent.com/12132146/213266229-da4d2493-6a80-497c-9997-0b69eb454c6e.jpg)

Thank you for letting me know @rstjames I was not aware of that, but totally makes sense I need to manage the blog post in Spanish,  I will take care of it as soon as possible

**Comment by emecas** [comment]
Done: 
https://microprofile.io/2023/01/20/lanzamiento-de-microprofile-6-0-y-adopcion-del-perfil-jakarta-ee-10-core/

**Comment by m-reza-rahman** [comment]
Ready to tweet now, @rstjames.

**Comment by rstjames** [comment]
Tweeted https://twitter.com/MicroProfileIO/status/1618592479548153858
