### ISSUE TITLE
[Content Creation] Update MicroProfile 5.0 Whitepaper to encompass 6.0

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#740]
The PDF link is [here](https://drive.google.com/file/d/1RgY1Yw_fFqExUVSlh4BYuOmQQsYIAWxt/view). We need to update content to include MicroProfile 6.0 and, if possible, branding. The target date is for the MicroProfile 6.0 release

**Comment by aeiras** [comment]
@jclingan, 

@rstjames **cannot** start the design work in the document until the document is housed under the MP Community drive > [Content](https://drive.google.com/drive/u/0/folders/1kRrOzf0G7PtG8VJXKODgDpVNOUKSUxnR) > [2022](https://drive.google.com/drive/u/0/folders/1Cr1obCY5m3AzkDfMHECIg1zRcys8souJ)

Can you please export the document there? Thanks, John!

**Comment by aeiras** [comment]
About the White Paper, softly discussed that the whitepaper paid for with the 2021 working group budget will be updated when there is an MP release that has 3 or more implementations.   

The status of this ticket is put under "Won't fix" and will be revived when applicable.
