### ISSUE TITLE
[Blog Contribution] Publicize MicroProfile EclipseCon Community Day Content?

### ISSUE THREAD

**Issue by m-reza-rahman** [microprofile/microprofile-marketing#741]
There was quite a bit of important MicroProfile content at EclipseCon Community Day. I have summarized and shared that content here: https://reza-rahman.me/2022/11/19/jakarta-ee-and-microprofile-at-eclipsecon-community-day-2022/. Does it make sense to help publicize this? If so, how?

**Comment by aeiras** [comment]
@emecas, 

A new blog arrived, would you like to make it a part of your monthly contributing to reviewing blog content?

**Comment by m-reza-rahman** [comment]
I think so? What I do need to do?

**Comment by emecas** [comment]
> @emecas,
> 
> A new blog arrived, would you like to make it a part of your monthly contributing to reviewing blog content?

yes, I would take care of this.

@m-reza-rahman   would this be handle as a "Case 2" contribution ?  https://github.com/microprofile/wpsite

**Comment by m-reza-rahman** [comment]
Either way is fine really. Just let me know what's needed?

**Comment by emecas** [comment]
> Either way is fine really. Just let me know what's needed?

First of all, do you have already access to  MP WordPress ?

**Comment by m-reza-rahman** [comment]
I don’t have access. Do I need it?

**Comment by aeiras** [comment]
@m-reza-rahman, 

Welcome to MP Content Contributing. Based on your exchange with beautiful @emecas, your WordPress MP access should be in your inbox. You can adjust the email of MP WordPress at any time by submitting a ticket and providing your preferred email, etc., as suggested in the Guidelines. Please see below. 

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/10731224/207449677-d2e0b392-eb52-4e71-ac09-81fa38ecdf9a.png">

**Comment by m-reza-rahman** [comment]
Submitted for review. LMK what else is needed?

**Comment by emecas** [comment]
> Submitted for review. LMK what else is needed?

Thanks. I will take care of this, be back to you ASAP

**Comment by aeiras** [comment]
@emecas, you are so amazing to review and keep taps on this ticket while on vacation. 
I should have stepped sooner to help you, my apologies. 

Given that your review was completed on the post, Reza's blog is now published. https://microprofile.io/2022/12/16/jakarta-ee-and-microprofile-at-eclipsecon-community-day-2022/. 

Thank you Emerson for choosing to contribute on content review and publication this year, you truly are incredible. 

Welcome Reza to MP content contributing.

**Comment by m-reza-rahman** [comment]
Great! Will this be automatically posted to social media or is there something further I need to do?

**Comment by m-reza-rahman** [comment]
Hi @rstjames, can we re-open this please? It would be good to put this blog entry into the Twitter account I think. Here is some suggested text:

Want to get a quick summary of what is going on with MicroProfile and what's coming? Check out this blog entry by @reza_rahman summarizing the MicroProfile and Jakarta EE content at EclipseCon Community Day 2022. https://microprofile.io/2022/12/16/jakarta-ee-and-microprofile-at-eclipsecon-community-day-2022/

I think something like the first embedded graphic on the blog entry would be fine as a card?

/cc @aeiras

**Comment by m-reza-rahman** [comment]
Hi @edburns, do you have sufficient rights now to re-open this? /cc @Emily-Jiang

**Comment by aeiras** [comment]
@m-reza-rahman, 

As discussed on previews calls, your blog qualifies for quarterly media push for 2023 if you choose it. 
Do update the spreadsheet below to enable its proper documentation on yearly media under quarterly items and link this git issue to that update. Thanks! 

Once you have the message, @rstjames will take over the work. 

https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074

**Comment by m-reza-rahman** [comment]
Does it have to be quarterly? Honestly I think the entry is already a bit stale. Could we do it just once instead?

**Comment by m-reza-rahman** [comment]
Hi @rstjames, as discussed in the marketing meeting, could we kindly get this out as a tweet just once or twice in the new few weeks or so? If it'll take longer than than, we should just close and drop this? This content was kind of stale even in December...

**Comment by m-reza-rahman** [comment]
I am closing this. It’s a bit too stale now.
