### ISSUE TITLE
[Website - MPWG tab] Upload Primeton Technologies' logo - New Member

### ISSUE THREAD

**Issue by ZahraFazli** [microprofile/microprofile-marketing#742]
Please upload the attached Primeton Technologies' logo to the drive {https://drive.google.com/drive/u/0/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk} and the MicroProfile website: https://microprofile.io/
![1401-web](https://user-images.githubusercontent.com/50374570/203385232-bf8f1294-0bc4-49b4-8e20-9f36547ff8ec.png)

**Comment by aeiras** [comment]
@rstjames, 

Thank you for processing this ticket. 
It needs 2 items:

- website
- social media push with  media design.

**Comment by Emily-Jiang** [comment]
@rstjames any update on this?

**Comment by rstjames** [comment]
@Emily-Jiang  what would we like to say for the social media message?  I will create the image. 

Also the link to the drive gives a 404

**Comment by Emily-Jiang** [comment]
The google drive gives me 404 as well. I think we don't have access to the drive. @ZahraFazli can you grant us the access to the drive?
@rstjames as for the social media message: how about
`MicroProfile is very thrilled to announce that Primeton from China has joined the MicroProfile Working Group! We are looking forward to working with Primeton to increase MicroProfile's visibility in China!`
@aeiras any thoughts on this?

**Comment by aeiras** [comment]
Thanks for pulling you in, Emily. @Emily-Jiang we are still awaiting for Christina's approval to use their logo for swag on this ticket. Do you know her git ID to invite her to the ticket?  Ideally, she is involved in the social write-up or if the company has a blog, we can use that as well, etc. I shared the onboarding guidelines on that thread, hopefully it is useful. 

Now, about the text review, Primeton is a publicly traded company that surpasses business not just in China. My recommendation is to drop that part as follows:

**#MicroProfile is thrilled to announce Primeton Information Technologies is the newest member of the @MicroProfileIO Working Group! We look forward to collaborating with you!**

**#ByCommunityForCommunity  #OpenSource** 

@rstjames, 

let's make sure social uses the 2022 design card used to onboard members' announcements in 2022. Thank you for prioritizing this ticket, Triber.

**Comment by Emily-Jiang** [comment]
> Thanks for pulling you in, Emily. @Emily-Jiang we are still awaiting for Christina's approval to use their logo for swag on this ticket. Do you know her git ID to invite her to the ticket? Ideally, she is involved in the social write-up or if the company has a blog, we can use that as well, etc. I shared the onboarding guidelines on that thread, hopefully it is useful.
>
@aeiras I have sent her a message. I am not sure whether she has a git ID as I was told in China they use something different from github. She might have to set up a new ID. In order to save time, I am wondering whether we can ask her to send email to the microprofile-wg for the approval, which might be quicker. Thoughts?

**Comment by aeiras** [comment]
+1 Emily on sending the approval to this thread.  [[microprofile-wg] Fwd: 2022 Marketing Proposal](https://www.eclipse.org/lists/microprofile-wg/msg01743.html)
But first, she needs to become a Subscriber [Mailing list: microprofile-wg (81 subscribers)](https://accounts.eclipse.org/mailing-list/microprofile-wg). Once she confirms she has been subscribed to the mailing list, I can follow up on the marketing swag proposal we spoke today, only then she will get that message from the thread and be able to reply with her approval. 

Lets do this!

**Comment by aeiras** [comment]
or subscribe and send a new email with such approval, also works.

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/712 has been re-opened to update 2022 swag to include Primeton in shirt and hoody. :)

**Comment by mingyuehuang99** [comment]
Primeton is happy for this logo used on MicroProfile swags and io,thank you!

**Comment by mingyuehuang99** [comment]
I am so glad to represent primeton to join microprofile group， I wish microprofile could growing better and better，and I will do my best to make a contribution to this group！！：）

**Comment by Emily-Jiang** [comment]
> Thanks for pulling you in, Emily. @Emily-Jiang we are still awaiting for Christina's approval to use their logo for swag on this ticket. Do you know her git ID to invite her to the ticket? Ideally, she is involved in the social write-up or if the company has a blog, we can use that as well, etc. I shared the onboarding guidelines on that thread, hopefully it is useful.
> 
> Now, about the text review, Primeton is a publicly traded company that surpasses business not just in China. My recommendation is to drop that part as follows:
> 
> **#MicroProfile is thrilled to announce Primeton Information Technologies is the newest member of the @MicroProfileIO Working Group! We look forward to collaborating with you!**
> 
> **#ByCommunityForCommunity #OpenSource**
> 
> @rstjames,
> 
> let's make sure social uses the 2022 design card used to onboard members' announcements in 2022. Thank you for prioritizing this ticket, Triber.

@mingyuehuang99 are you happy with the welcome message below, which MicroProfile will announce this in the social media?
 **#MicroProfile is thrilled to announce Primeton Information Technologies is the newest member of the @MicroProfileIO Working Group! We look forward to collaborating with you!**
Feel free to add/update the above text.

**Comment by Emily-Jiang** [comment]
> or subscribe and send a new email with such approval, also works.

Thanks @aeiras ! I have got @mingyuehuang99 here 💯

**Comment by mingyuehuang99** [comment]
yes！ I think that is great text .
#MicroProfile is thrilled to announce Primeton Information Technologies is the newest member of the @MicroProfileIO Working Group! We look forward to collaborating with you!

**Comment by aeiras** [comment]
Emily, @Emily-Jiang -- you 👍 rock! 

Mingyue, @mingyuehuang99 - thank you for authorizing the update on the 2022 swag, your timing is fantastic! Your reply also enables [Re: [microprofile-wg] 2022 Marketing Proposal](https://www.eclipse.org/lists/microprofile-wg/msg01751.html) follow-up. Thank YOU for being so positive about joining our community, so fun! 

Lastly, I added you on https://github.com/eclipse/microprofile-marketing/issues/712 to ensure you approve the final logo. Stand by. :)

**Comment by mingyuehuang99** [comment]
@aeiras thank you for your help! I can see the #712 now,i will approve the final logo!  :）

**Comment by rstjames** [comment]
@rstjames do social media post

**Comment by rstjames** [comment]
post sent out 
https://twitter.com/MicroProfileIO/status/1600476333158633472
FB + linkedin

**Comment by Emily-Jiang** [comment]
@rstjames @mingyuehuang99 wants Primeton logo updated. 

Not sure why the message did not show up here.
mingyue huang <notifications@github.com> | mingyue huang <notifications@github.com> | 6:38 AM (5 hours ago)
-- | -- | --
mingyue huang <notifications@github.com>

mingyue huang <notifications@github.com>
	
6:38 AM (5 hours ago)
	
to Mention, eclipse/microprofile-marketing, me

[@aeiras](https://github.com/aeiras)@Emily-Jiang
halo,Our company Primeton want to update logo to the new one,both io and other use place ,thank you so much!!!:)
!this is the new logo.
[primeton logo](https://user-images.githubusercontent.com/119476657/206375734-552f0d3c-ae43-4489-8edd-c6d31db9303f.jpg)

**Comment by Emily-Jiang** [comment]
@mingyuehuang99 can you reconfirm this is your intention to update the logo of Primeton at microprofile.io and on swags?

**Comment by aeiras** [comment]
Hola Emily, 

Mingyue's private email works great on this request. 

@rstjames, can you please prioritize the logo update in MP.io as well? Thank you! 
https://drive.google.com/drive/u/0/folders/1egNtUlEajK4mS3NSAgLlTevxy6VLo1Z0

**Comment by rstjames** [comment]
all updated and SM out

**Comment by aeiras** [comment]
@rstjames, 

When is the media message scheduled?

**Comment by aeiras** [comment]
Ideally, tickets such as this on new members joining MP are closed with the link of social media. 

Thank you, Ryan. Ticket is re-opened for that reason.

**Comment by rstjames** [comment]
https://twitter.com/MicroProfileIO/status/1600476333158633472/photo/1

**Comment by aeiras** [comment]
Re-opening this ticket as part of Primeton onboarding in MP.io. 

Hola @mingyuehuang99, 

Under https://microprofile.io/workinggroup/#mptab-members Primeton needs to be added with you, and if an alternate exists, please do share her/his name and social media( if any) Please notice that under each individual information, social media (twitter, GitHub or whatever) added. The media is the choice of each member who is part of the company. Once you share your information, the page will be updated, the information can be adjusted via a new ticket at any time and without explanation. Thanks!

@rstjames,

**Comment by mingyuehuang99** [comment]
@aeiras 
Thank you for update Primeton members ,The alternate member is Bruce Liu,His Github id is jxta.liu@gmail.com  :)
Thanks!

**Comment by aeiras** [comment]
Thank you, @mingyuehuang99! 

I will create a new onboarding git issue for you to tackle diverse things without rushing. Ideally, you tackle the items within your own schedule. :) 

--
@rstjames, 

Thank you for adding Primeton to https://microprofile.io/workinggroup/#mptab-members with members:

- Mingyue Huang linked to https://github.com/mingyuehuang99
- Bruce Liu linked to https://github.com/jxtaliu

**Comment by mingyuehuang99** [comment]
Thank you ,@aeiras
I already accept the github invitation :)

**Comment by rstjames** [comment]
updated on site table 
<img width="1011" alt="Screenshot 2023-01-11 at 17 47 02" src="https://user-images.githubusercontent.com/12132146/211866001-cbdff00f-7751-48aa-9df1-de43c8c4d7f0.png">

**Comment by aeiras** [comment]
Ryan, 

the 2 members are using their hot ids. Please adjust the logo of their social. 💛

**Comment by aeiras** [comment]
> Thank you ,@aeiras
> I already accept the github invitation :)

that is fantastic, @mingyuehuang99! 
There are many tasks within the guidelines that you ought to tackle. Use your time and the git ticket to move forward. Cheers!
