### ISSUE TITLE
[General] Calendar update - 2022 Holidays

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#744]
Hey @jclingan, 

Can you please use your Zoom admin access to delete all MP meetings from December 17th to January 8th? 
The Marketing and Community calls are scheduled to start on January 8th and 9 consecutive. 

https://calendar.google.com/calendar/u/0/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=America/Los_Angeles

The MP holiday event is added to the calendar to show the regular OUT calls. 
Once deletions are completed, we can send this ticket to the community for a formal update, as usual! :) Thank YOU!

**Comment by Emily-Jiang** [comment]
I have cleared all of MP calls from MP calendar for the next three weeks, which is sufficient to notify everyone. I suggest not to touch the zoom entries as these were occuring calls so it is safer to leave them there. I've sent a note to googlegroup as well. I think this ticket can be closed.

**Comment by aeiras** [comment]
So fantastic, Emily! 

https://groups.google.com/g/microprofile/c/10XQ9YD5YmU

**Comment by aeiras** [comment]
FYI, it is always 4 weeks without calls. :)
