### ISSUE TITLE
[Website Improvements] Branding Resources page

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#745]
Hey @rstjames, 

There is 1 grammatical error that requires our attention:  Branding Resources: 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/10731224/204936118-c5e4e2a2-0f3d-43b6-8d00-7f06b8bb6afa.png">

It seems valuable for this page to have direct links to the Marketing Repo and the marketing mailing lists as follows:

My recommendation is to add them under the yellow section, **without a section in the page**, or if we can import the Git repo and mailing list and add them to the page on their own accord, then great. Your insight is welcomed on the how. 

1. https://github.com/eclipse/microprofile-marketing/issues   
2. https://groups.google.com/g/microprofile-marketing

Please use the links provided, as we must always log out from all access to avoid 404 errors when updating links to redirect visitors to other tools. 

Thank you,

**Comment by rstjames** [comment]
Page updated with buttons. No room to have it on the anchored menu bar
