### ISSUE TITLE
[Website Improvement ] MPWG page 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#746]
@rstjames, 

Andrii has questions for you on the Working Group page adjustments via the other ticket. To follow up on that work, I am creating a new ticket for additional improvements on the page:

Under the Member tab: https://microprofile.io/workinggroup/#mptab-members, it seems valuable to also add direct links below "... the members approve." of: 

1. New Member [Onboarding Guidelines](https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--Members-Onboarding)
2. MicroProfile Working Group [GitHub Repository ](https://github.com/microprofile/microprofile-wg/issues)
3. MicroProfile Working Group [Mailing list](https://accounts.eclipse.org/mailing-list/microprofile-wg)
4. MicroProfile Working Group [Google External Drive](https://drive.google.com/drive/folders/1de24s8S9VeGCVw3Bn8at5NmI0rWFxdQW)

Ideally, the website tickets like this get completed before MP goes into its Holiday on Dec 18th. Please ask away to make sure you are not blocked. Thanks/.

**Comment by rstjames** [comment]
add links to tab

**Comment by rstjames** [comment]
updated
