### ISSUE TITLE
[Website- MPWG tab Improvement ] Adjustment of Members logos

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#747]
@rstjames, 

The current way the logo members are shown is no longer efficient as MPWG has 11 Members including the Committers. 

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/10731224/205402573-bc421a28-6ab9-47be-a111-b50c437292a8.png">

Recommendations:

1. Remove them from current section, which will make the blue section less tall. A plus 1
2. Above Quotes, lets create the space where the logos are located, which includes its own link.

If you see anything else that can be improved about the Members' logo within the page and in other places in MP.IO, please share. 

Thanks, Ryan.

**Comment by rstjames** [comment]
Updated

**Comment by aeiras** [comment]
Looks much better, @rstjames. :)

Can the blue section be made compact? It seems there is too much empty space. I recommend more elegance on closing the empty void.  What's your take on it? 

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/10731224/207671715-b00a2180-63ab-4001-b87f-0fd9447ef9ed.png">
