### ISSUE TITLE
[Compatible Implementations Announcement] MP 5.0 - WildFly Preview 26.0.0.Final

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#748]
**Organization Name**
Name: [Red Hat](https://www.redhat.com/en)
 
 **Product Version and download URL**
URL: [WildFly Preview 26.0.0.Final](https://github.com/wildfly/wildfly/releases/download/26.0.0.Final/wildfly-preview-26.0.0.Final.zip)
 
 **Java runtime used to run the implementation**
[TCK results](https://github.com/wildfly/certifications/blob/MP5.0/WildFly_Preview_26.0.0.Final/microprofile-5.0/microprofile-full-platform.adoc) - JDK 8, 11, 17

 **Media Description**
 280 chararters includes the organization's name & URL or blog

 **Design Card**  (for MicroProfile designer)

 **Notes**

- MicroProfile 5.0 and it's WildFlye Preview (not just WildFly)
- CCR - https://github.com/eclipse/microprofile/issues/284

**Comment by rstjames** [comment]
Updated on the site.

**Comment by xstefank** [comment]
thanks

**Comment by aeiras** [comment]
Hola @xstefank Martin, 

MP social media needs to push the news via its hootsuite account, so the ticket on compatible announcements ought to always stay open until social media is covered with that media link posted. Stand By. @rstjames is on it!

**Comment by rstjames** [comment]
send you and site is updated https://twitter.com/MicroProfileIO/status/1603440211823927298
