### ISSUE TITLE
MP Mastodon (add to Hootsuite) 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#749]
- [ ] No need to move. MP media can add Mastodon to Hootsuite. 

- [ ] Ryan needs access to integrate the tool to hootsuite

**Comment by rstjames** [comment]
@aeiras need access to Mastodon to connect it to hootsuite

**Comment by aeiras** [comment]
@rstjames, 

I believe adding Mastodon to Hootsuite MP  in January seems sensible as the account will need to be rebranded which requires review, etc,  before its usage.  There are only 2 more days left to do this, not enough time for process to complete the task.   

This ticket will be one of the tasks to tackle in January. Thanks for the follow-up

**Comment by rstjames** [comment]
@aeiras Looked into this and Mastodon is currently not supported on scheduling platforms such as Hootsuite, Zoho Social, HubSpot etc. 

So we can not add it.

**Comment by aeiras** [comment]
Ok. so that is that, @rstjames. Thank you for looking into the integration. 
Lets keep it in mind and check it again in Q4.  Until then, this task is dropped.
