### ISSUE TITLE
Request to be added as a WP MicroProfiler New Contributor

### ISSUE THREAD

**Issue by davidsalter** [microprofile/microprofile-marketing#75]
David Salter davidmsalter@icloud.com

**Comment by aeiras** [comment]
Hola @davidsalter, 

Thank you for choosing to become the 37 MP wordpress Contributor, just fun! 

<img width="962" alt="image" src="https://user-images.githubusercontent.com/10731224/56915932-93313a80-6a6c-11e9-9c14-7ec135bd6a40.png">

[David's Twitter Blog post reference](https://twitter.com/GeefyGeorge/status/1121451994491817984)
