### ISSUE TITLE
[MPWG Website tab] Wrong link 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#751]
Ryan, 

Stuff has changed in GitHub, so old links no longer work.  Can you please look at all the links in MP.io to ensure viewers land on the correct content?
For all review links in github, you must be log-off to import link to the website. Doing so will fix current issues with access. 

Thank you in advance for fixing the Members Onboarding Process (yellow link) with the link below. 

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/10731224/206494007-af74620b-ef29-4be2-a01b-fd4f257e422c.png">

https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Working-Group:--New-Members-Onboarding-Guidelines

**Comment by rstjames** [comment]
@aeiras Please provide Member onboarding process link and I will update it. The rest of the links look ok

**Comment by rstjames** [comment]
all updated
