### ISSUE TITLE
[Blog Contribution] Fast iterative cloud-native Java application development with Liberty Tools

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#752]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7124&action=edit)**

 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
YK Chang (@yeekangc) gives a quick overview of the new generation of Liberty Tools for @openlibertyio which, among other things, help you write code confidently using MicroProfile & @JakartaEE APIs with validations, quick fixes, completions.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

**Comment by emecas** [comment]
Landing here

**Comment by emecas** [comment]
Approved and published 

Permalink: https://microprofile.io/2023/01/12/fast-iterative-cloud-native-java-application-development-with-liberty-tools/

Added tags:  cloud native`

- [x]  Ensure the content of post is relevant and applicable to Microprofile
- [x]  Check that content has the author(s) name
- [x]  Check that the content provides credit to collaborators
- [x]  Check that post has a “Page Header Image”
- [x]  The image should be between 1600px - 2000px wide and have a minimum height of 500px for best results.
         iberty-tools-marketplaces.png 1624 by 904 pixels 
- [x]  Check for grammatical errors
- [x]  Check for TMs and copyrights

**Comment by aeiras** [comment]
Fantastic work, Emerson! :) 
Hola Laura!
