### ISSUE TITLE
[MPWG tab update] 2023 Budget and Project plan

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#753]
@rstjames, 

Thank you for updating the https://microprofile.io/workinggroup/#mptab-program-plan-budget as follows:

**Description**
The MicroProfile yearly Project plan is drafted and worked on in the open with the MicroProfile community. The MicroProfile Budget is prepared by Eclipse Management Organization (EMO) based on the approved budget. Four (4) yearly fees are paid to the EMO totaling ~69% of the budget:
1) Working Group fees (15% of membership fees)
3) General and Administration (12% of membership fees)
2) Governance & Management, including Spec Management ( $30,000)
4) Shared Marketing Services Fee ($7,000)

Under Marketing Expenses allocation expenses, it’s acceptable to overspend in one line item and underspend in another without formally adjusting the approved budget. The EMO will adjust the expenditures based on the costs incurred.

---
**2023 updated Links** 

- 2023 Budget https://drive.google.com/drive/folders/19NVgyJ3RzU526A1_VT9R3g8q85JyaNFi
- 2022 Program Plan https://drive.google.com/drive/folders/19NVgyJ3RzU526A1_VT9R3g8q85JyaNFi
- 2023 Forecast budget https://docs.google.com/spreadsheets/d/1W1HT3lwmIHqOzF1Iz-Tx6fnDgIex02fbGRKDO3_nvwI/edit#gid=1728036894
-

**Comment by rstjames** [comment]
All updated

**Comment by aeiras** [comment]
@rstjames, 

This ticket has a part 2. Improvement section. 
I would like your thoughts on it before implementation. 

Can the Budget and Program Plan be added directly into the space?
Similar to what we did for the MP speaker presentation under https://microprofile.io/resources/branding/#pres-temp
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/10731224/211880870-4b7bc127-e8fb-471e-903c-e64f38dfb63a.png">

The addition can be just like the calendar insert on the MPWG page, with no extra wording. 

The documents and the space are updated **once** a year. We want the reader to stay in MP.io so adding the documents seems the best way. 

What is your take on this improvement? @rstjames

**Comment by rstjames** [comment]
@aeiras I am not able to do this until I have editing rights to the slided decks. But I can embed them when I have this.

**Comment by aeiras** [comment]
> @aeiras I am not able to do this until I have editing rights to the slided decks. But I can embed them when I have this.

Gotcha, @rstjames. 

I have copied the documents into the community drive https://drive.google.com/drive/folders/1XftsX68Dmc0ZWdCa3wYgpnZJy89QX3Gg.

1. The program plan is always pptx that we convert to PDF (later)
2. Budget is always PDF, if you need other format, you can modify it now. 

Thank you,

**Comment by rstjames** [comment]
@aeiras The program plan was added as a slide show but the budget pdf we can not. I think it is digested better as a linked pdf anyways

**Comment by aeiras** [comment]
Adjustment works fantastic, Ryan. 
In the year, the project plan is the most important document for the MPWG to look at and work towards. :)
