### ISSUE TITLE
[Compatible Implementations Announcement] Oracle, Helidon 3.1

### ISSUE THREAD

**Issue by edbratt** [microprofile/microprofile-marketing#756]
**Organization Name**
 Name: Oracle
 
 **Product Version and download URL**
 URL: [Helidon 3.1](https://helidon.io) 
[Documentation for Helidon 3.0](https://helidon.io/docs/v3/#/about/introduction)
 
 **Java runtime used to run the implementation**
JDK 17.0.4. [CCR](https://github.com/eclipse/microprofile/issues/291)

 **Media Description**
Helidon 3 is a compact Java framework that delivers complete MicroProfile 5 compatibility. Helidon also includes compatible implementations of GraphQL, LRA, Reactive Streams Operators, and Reactive Messaging. Helidon provides a convenient starter feature that allows you to generate your first MicroProfile application right away. Go to [helidon.io](https://helidon.io) and click the 'Starter' button.

 **Design Card**  (for MicroProfile designer)
Helidon Logo (frank.svg)as .svg is attached.
 **Notes**
 [MicroProfile 5 Certification, Helidon 3](https://github.com/helidon-io/helidon/wiki/Eclipse-MicroProfile-5-Certification,-Helidon-3)

![frank](https://user-images.githubusercontent.com/12281454/211943562-1ed69d78-8745-4729-8864-6dcd40f3a172.svg)

**Comment by aeiras** [comment]
@edbratt this ticket rocks!!!

Can you please drop Eclipse from the MicroProfile name?  
Keeping it violates the project's trademarks since Oct 1st, 2020.   
Further, if you could please inform the Oracle team of that fact, it will help protect the trademark on communications, internal and external, such as blogs and announcements. 

The ticket cannot be worked out until the adjustments are made to the Certification page.  I am doing that review under this ticket :) 

Congratulations to you and the Oracle Team!!!

**Comment by m-reza-rahman** [comment]
@edbratt to apply changes - dropping "Eclipse" from "Eclipse MicroProfile".

**Comment by edbratt** [comment]
I think I've done the update requested. Thank you. (PS, the TCK documentation link needed to change b/c I removed Eclipse from the title.)

**Comment by aeiras** [comment]
> I think I've done the update requested. Thank you. (PS, the TCK documentation link needed to change b/c I removed Eclipse from the title.)

Fantastic turnaround, @edbratt. I took the liberty of updating https://github.com/eclipse/microprofile/issues/291. 

@rstjames, 

Please follow the process and do pull Ed as you see fit on media template review, if needed.

**Comment by rstjames** [comment]
I will look into this tomorrow (friday)

**Comment by rstjames** [comment]
@edbratt ok with this? 

#MicroProfileCompatible Announcement:
We are happy to announce that #Helidon3 is now compatible with #MicroProfile 5.0.
Go to https://helidon.io/ and click the 'Starter' button.

#opensource @helidon_project
![MicroProfile-compatible-helidon3](https://user-images.githubusercontent.com/12132146/215533941-b5bbddf2-d287-419f-9361-8603477a56d0.jpg)

**Comment by rstjames** [comment]
@edbratt 
Updating the compatible page, but need the TCK link
https://microprofile.io/compatible/5-0/#overview

thank you!

R

**Comment by edbratt** [comment]
https://github.com/helidon-io/helidon/wiki/MicroProfile-5-Certification,-Helidon-3

**Comment by rstjames** [comment]
@edbratt thank you. all set

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1620468273358708743?s=20&t=jpm_5fFPu757Z-IDyzWUCQ

@rstjames, 

Thank you for the good work on this ticket. 💯 
Remember that tickets like this should also be closed with the social media link. Post it!
