### ISSUE TITLE
[Quote Submission] Microsoft

### ISSUE THREAD

**Issue by m-reza-rahman** [microprofile/microprofile-marketing#759]
**Quote**
Our goal is to help advance MicroProfile, as well as Jakarta EE, to deliver better outcomes for customers and the broader community. We’ll work closely with long-standing partners in the working groups. Our experience with running Java workloads in the cloud will be valuable to the working groups, and we look forward to building a strong future for Java together.

**Author**
Reza Rahman
Principal Program Manager, Java on Azure at Microsoft
https://twitter.com/reza_rahman
![microsoft](https://user-images.githubusercontent.com/3622346/214134610-1fded8cb-0dcf-4f2d-a524-0604329097a5.svg)

 **Design Card**  (for MicroProfile designer)

**Comment by aeiras** [comment]
> **Quote** Our goal is to help advance MicroProfile, as well as Jakarta EE, to deliver better outcomes for customers and the broader community. We’ll work closely with long-standing partners in the working groups. Our experience with running Java workloads in the cloud will be valuable to the working groups, and we look forward to building a strong future for Java together.
> 
> **Author** Reza Rahman Principal Program Manager, Java on Azure at Microsoft https://twitter.com/reza_rahman ![microsoft](https://user-images.githubusercontent.com/3622346/214134610-1fded8cb-0dcf-4f2d-a524-0604329097a5.svg)
> 
> **Design Card** (for MicroProfile designer)

review is recommend using suggested edit for the author to decline or approve as you see fit. 
 https://docs.google.com/document/d/1lU9NKqA4XlxQ1SjHBvmFI_8KUqoZVYxbJC9BvwWajGU/edit#

**Comment by m-reza-rahman** [comment]
The suggested changes are fine. Here is how the quote turns out:

> Microsoft’s goal is to help advance the MicroProfile and Jakarta EE technologies as the projects deliver better outcomes for customers and the global community. As we work closely with long-standing partners, our experience running Java workloads in the cloud will be valuable. We look forward to building a strong future for Java together.

Is there anything else I need to do so we can move this forward?

**Comment by aeiras** [comment]
Great turnaround, Reza. Thank you for submitting it. 

MSFT quote has been moved to approved spreadsheet for import to MP.io. 
https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit#gid=1123045040
---

@rstjames, 

Lets import Microsoft's quote using the company logo as done for IBM and others instead of person's quote, this is corporate import.  Questions, shoot. Thank you!

**Comment by m-reza-rahman** [comment]
Great! The corresponding social media amplification will just happen, right? Or do I need to do something further?

**Comment by aeiras** [comment]
> Great! The corresponding social media amplification will just happen, right? Or do I need to do something further?

Great question. The quotes will continue to get pushed as a group 1 per month using the https://microprofile.io/workinggroup/#testimonials. The quotes are part of the yearly social media spreadsheet we are working on.   

The group has chosen not to highlight any quote at standalone.

**Comment by m-reza-rahman** [comment]
OK. The quote is intended to be longer lasting, so should be fine.

**Comment by rstjames** [comment]
@m-reza-rahman @aeiras 
The quote has been added. We will fix the carousel functionality next. (bug)

**Comment by m-reza-rahman** [comment]
Hi @rstjames, can we kindly attribute the quote to me the same way it is for IBM (Ian Robinson) and Red Hat (Mark Little)? While I can provide the quote on behalf of Microsoft in this context, to be honest personal attribution is still required, even for very senior executives at Microsoft (several levels above my managers' paygrade :-)).

**Comment by rstjames** [comment]
Updated :)
