### ISSUE TITLE
MP session at Red Hat Summit

### ISSUE THREAD

**Issue by Theresa-Nguyen** [microprofile/microprofile-marketing#76]
1. Title: **Java and MicroProfile on Azure: Building microservices in style**
2. Speakers: Brian Benz (Microsoft), James Falkner (Red Hat)
3. Twitter:  @bbenz; @openatmicrosoft
4. URL: https://summit.redhat.com/conference/sessions
5. Date & Time: Wednesday, May 8, 3:30 - 4:15 PM
6. Abstract: This session dives into the steps required to design, build, deploy, and orchestrate a cloud-native microservices architecture using Java and Eclipse MicroProfile. We'll use Red Hat’s MicroProfile implementation known as Thorntail, optimized for deployment to Red Hat OpenShift Container Platform and integrated with Microsoft Azure services. Hear from Microsoft and Red Hat experts how adopting cloud-native, open source projects and open standards while making use of tools, APIs, and Java specifications that developers are already familiar with, can allow you to achieve superior productivity. This session includes an overview of MicroProfile and demonstrations of how to put it into practice in the cloud.

**Comment by bbenz** [comment]
Thanks Theresa!  Suggested tweet (sucks that we can't link to the session directly but whatevs.)

If you're at the @redhatsummit, @bbenz and @schtool will show you how to work with @java and @microprofileio to deploy microservices to containers, @kubernetesio and @openshift on @azure using free, open source tools on Wednesday, May 8, 3:30PM.

**Comment by Theresa-Nguyen** [comment]
Included all five sessions in one issue for faster turnaround.

**Comment by rstjames** [comment]
@Theresa-Nguyen All session need to be in separate issues. Especially if we get anymore help to push sessions on SM. @bbenz And if you 5 sessions this MUST be sumitted 2 weeks in advance for us to push in on MP SM.

**Comment by rstjames** [comment]
Session scheduled on twitter. It will go out today and the day before the session.
