### ISSUE TITLE
[MPWG page] Add Quote guidelines under Testimonials

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#760]
@rstjames, 

Can you please find a way to add https://github.com/eclipse/microprofile-marketing/wiki/Quote-Submissions-Guidelines:-MicroProfiler-Testimonials on the https://microprofile.io/workinggroup/#testimonials section?

After today's discussion, we need the how to in the section like a call to action to bring anyone who reads the quotes to submit quotes if desired. 

Thanks,

**Comment by rstjames** [comment]
Updated. 
![Screenshot 2023-01-30 at 17 52 25](https://user-images.githubusercontent.com/12132146/215542027-b63e4a93-d48a-42c2-83fb-d4356847680c.png)

**Comment by aeiras** [comment]
the improvement is fantastic, thank you!
