### ISSUE TITLE
[Social Media] DevNexus Talk - Jakarta EE and MicroProfile Highlights

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#761]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Edwin Derks
Twitter: @edwinderks
Josh Juneau
Twitter: @javajuneau

**Event**
[Link to the event/conference/Session](https://devnexus.org/presentations/jakarta-ee-and-microprofile-highlights/)

**Schedule**
2023/04/4-6

**Media Description**
Join @Java_Champions @edwinderks & @javajuneau on stage at https://github.com/devnexus April 4-6th! Their talk shares @MicroProfileIO & @JakartaEE important features through code examples and real-life scenarios.

Session details: https://devnexus.org/presentations/jakarta-ee-and-microprofile-highlights/

We hope to see you there!

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers

**Notes**
It is a duo session together with Josh Juneau, also a Java Champion.

**Comment by aeiras** [comment]
@ederks85 I am glad you found the documentation helpful :) Always there under Resources page in MP.io!

Now, the media message requires adjustments b/c it comes from MP social and not your personal accounts.  Please review and adjust as you see fit the message below. I used the abstract to insert a more focused message about your session. 
In the future when you submit messages about your sessions, always remember to answer _why should I skip other sessions to attend yours?_. The opportunity costs to the attendee needs to be stated in the message for the message to be a valuable call to action, specially something that amplify your contributions to MP and your desire to share that knowledge via events. Stay awesome!   


**Join @Java_Champions @edwinderks & @javajuneau on stage at @devnexus April 4-6th! Their talk shares @MicroProfileIO & @jakartaee's important features  through a number of code examples and the usage of APIs' real-life scenarios.** 

**https://devnexus.org/presentations/jakarta-ee-and-microprofile-highlights/**

**#SharingIsCaring #OSS💛**

**Comment by ederks85** [comment]
Thanks @aeiras for the review, I hope it is now in a preferred state.

**Comment by aeiras** [comment]
> Thanks @aeiras for the review, I hope it is now in a preferred state.

Thank you for the review, Edwin! 

@rstjames,

Josh and Edwin have provided their session ticket 2 months in advance. That means, MP media can highlight them 4 times, 1 on Feb, 2 in March, and 1 the day of their session. 

Can you please close this ticket next week with that scheduling?  Mil gracias, Triber!

**Comment by aeiras** [comment]
> @ederks85 I am glad you found the documentation helpful :) Always there under Resources page in MP.io!
> 
> Now, the media message requires adjustments b/c it comes from MP social and not your personal accounts. Please review and adjust as you see fit the message below. I used the abstract to insert a more focused message about your session. In the future when you submit messages about your sessions, always remember to answer _why should I skip other sessions to attend yours?_. The opportunity costs to the attendee needs to be stated in the message for the message to be a valuable call to action, specially something that amplify your contributions to MP and your desire to share that knowledge via events. Stay awesome!
> 
> **Join @Java_Champions @edwinderks & @javajuneau on stage at @devnexus April 4-6th! Their talk shares @MicroProfileIO & @jakartaee's important features through a number of code examples and the usage of APIs' real-life scenarios.**
> 
> **https://devnexus.org/presentations/jakarta-ee-and-microprofile-highlights/**
> 
> **#SharingIsCaring #OSS💛**

@rstjames this is the final media message.

**Comment by rstjames** [comment]
All scheduled 
![MicroProfile-devnexus-jakartaee_microprofile_highlights](https://user-images.githubusercontent.com/12132146/215793381-b4c85b35-97d6-41e6-a7b8-fe0157f50fca.png)

**Comment by aeiras** [comment]
Thank you, @rstjames!

Can you confirm that the posts are scheduled 4 times and not 2? Please check the advice on how to post them, 1 Feb, 2 March and 1 the day of the session.

**Comment by rstjames** [comment]
They are set to go out 4 time, But are more spread out evenly on mid months and day before the conference.
