### ISSUE TITLE
[Social Media] DevNexus Talk - Deep Dive MicroProfile 6.0 with Jakarta EE 10 Core Profile

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#762]
Join @Java_Champions @emilyfhjiang on stage at [@devnexus](https://github.com/devnexus) April 4-6th! Her talk shares @MicroProfileIO 6.0 important features through a live code demo @OpenLibertyIO.

https://devnexus.com/presentations/deep-dive-microprofile-6-0-with-jakarta-ee-10-core-profile

#SharingIsCaring #OSS💛

**Comment by aeiras** [comment]
Beautiful submission, @Emily-Jiang :) 

-

@rstjames, 

Same feedback as the one provided for Edwin and Josh's session. https://github.com/eclipse/microprofile-marketing/issues/761#issuecomment-1405251036 [_MP media can highlight them 4 times, 1 on Feb, 2 in March, and 1 the day of their session._]. Thank you for closing this ticket next week.

**Comment by rstjames** [comment]
@Emily-Jiang scheduled
Join @Java_Champions @emilyfhjiang on stage at @devnexus April 4-6th! Her talk shares #MicroProfile 6.0's important features through a live code demo @OpenLibertyIO 

https://devnexus.com/presentations/deep-dive-microprofile-6-0-with-jakarta-ee-10-core-profile

#SharingIsCaring #OSS 💛
![MicroProfile-devnexus-deep_dive](https://user-images.githubusercontent.com/12132146/215539565-c32bcbad-b9c9-4221-8760-b3297c3f91eb.png)

**Comment by rstjames** [comment]
They are set to go out 4 time, Spread out evenly on mid months and day before the conference.

**Comment by aeiras** [comment]
@rstjames, 

I am re-opening this ticket b/c I noticed via MP Twitter that Emily's card doesn't have her picture. https://twitter.com/MicroProfileIO/status/1620099593332527115?s=20&t=nz08RvJT42uEnvrxI32Zpg

While Edwin and Josh's tweet does https://twitter.com/MicroProfileIO/status/1620814782675779585?s=20&t=nz08RvJT42uEnvrxI32Zpg

-- 
The speaker media card should always have a picture of the speakers'. I think it was missed, glad MP media uses Hootsuite so fixing it is not problematic. 

Thank you for looking into this before the next message goes out.

**Comment by rstjames** [comment]
updated on hootsuite with images with her picture

**Comment by aeiras** [comment]
Thank you!
