### ISSUE TITLE
[Website] Change watermark year

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#764]
from 2021 to 2023. :) Thank you, @rstjames! 

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/10731224/216114175-a0218c51-6c1c-423c-a4c8-60f9aa9c385d.png">

**Comment by rstjames** [comment]
updated

**Comment by aeiras** [comment]
awesome!

@rstjames, do remember to update the agenda under "completed tasks" for tickets. 
Those behind actions ought to help the monthly stewards with agenda activity :) Thanks, Triber!
