### ISSUE TITLE
[2023 Yearly Social Media ] Call to action: MPWG Submit Quote

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#765]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#WordOnTheStreet: Submit your @MicroProfileIO quote and share why you invest your time & resources developing & using the #MicroProfileTechnology.

https://microprofile.io/workinggroup/#testimonials

#ByCommunityForCommunity #SharingIsCaring #OpenSource

**2022 issue**
https://github.com/eclipse/microprofile-marketing/issues/662

**Schedule**
1 per month

**Comment by rstjames** [comment]
![2023_microprofile_submit_quote](https://user-images.githubusercontent.com/12132146/220169420-fabc704a-2168-4428-a2ab-d9c81066a420.jpg)

**Comment by aeiras** [comment]
How about if we make it a question, like:

Submit your MicroProfile Testimonial
Why do you invest/adopt MicroProfile?
