### ISSUE TITLE
[2023 Yearly Social Media ] Call to action:  MPWG Prospectus highlight - Become a Member

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#766]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
Becoming a member of the MicroProfile Working Group demonstrates a commitment to the evolution and sustainability of #MicroProfile while ensuring the continued growth and development of a well-governed, vendor-neutral #OpenSource ecosystem.

Join us: https://microprofile.io/workinggroup/#prospectus

**Schedule**
1 month

**2022 issue** 
https://github.com/eclipse/microprofile-marketing/issues/664

**Comment by rstjames** [comment]
![2023_microprofile_Prospectus](https://user-images.githubusercontent.com/12132146/220168763-aae5d0e4-43dd-4a86-88a1-f8f002a3d540.jpg)

**Comment by rstjames** [comment]
Scheduled
