### ISSUE TITLE
[2023 Yearly Social Media ] Call to action: MPWG Charter - highlight

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#767]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#ByCommunityForCommunity: The MicroProfile Working Group Charter states that it is the #MicroProfileCommunity, who owns the responsibility to collaborate, maintain, release, promote, evangelize & market  #OpenSource Specifications.  #OSS

Learn more: https://bit.ly/3bUh8lN

**Schedule**
1 month

**2022 issue**
https://github.com/eclipse/microprofile-marketing/issues/664

**Comment by aeiras** [comment]
@rstjames, 

This ticket has same issue as the Branding Speakers' highlight. It doesn't have a landing space in the website. https://github.com/eclipse/microprofile-marketing/issues/770

Can you help create a landing space within the MPWG page that is similar to the Prospectus tab? 
https://microprofile.io/workinggroup/#prospectus

Like that in the social media that link is used instead of https://bit.ly/3bUh8lN

---

**Wording** 
MicroProfile Working Group Charter: Vision and Scope

The MicroProfile community values the following principles: Limited processes, Experiment and innovate, No backwards compatibility guarantee, Implementation first, Encourage brand adoption, Openness, Low barrier to entry

---

Again, the goal is to educate the community to find MicroProfile information in the website, not via "links" unrelated to the website. 

Q&A welcomed.

**Comment by rstjames** [comment]
@aeiras I am confused whats going on with this ticket? What link do we want to put?

**Comment by aeiras** [comment]
The Charter needs a landing link like the one you and Andrii created for the Prospectus and the Quote. 
Can you create a space like it for the Charter?

The goal is not to direct readers to the document but to the website. 

I provided the information to populate that space within the MPWG page. 

Further questions, shoot. Thanks, @rstjames!

**Comment by rstjames** [comment]
@aeiras OK still not 100% sure what you want.  

I see the charter button the top of the wg page. Do we just link top of the WG page? (not sure if there is a point to have a anchored link to the top of a page.

Do you want this added to a tab? If so which tab?
(adjusted the text) 
**The MicroProfile community values the following principles:** 
Limited processes, Experiment and innovate, No backwards compatibility guarantee, Implementation first, Encouraging brand adoption, Openness, and Low barrier to entry. LINK to page?

**Comment by aeiras** [comment]
Thank you for enabling this follow-up, @rstjames. 

The Charter being anchored in the WG page is important b/c:

1. it cuts the viewer clicks to 1 instead of 2 clicks. Remember, we wish MP.io to sustain all the MP information effectively with few clicks and proper links that can be socially distributed to bring awareness to the website navigation as the source of truth. 
2. Aside from the Community behind MP, the Charter is the most important thing on the page. Therefore, the new tab should be below the **quotes** anchored. 

-

**Comment by rstjames** [comment]
@aeiras lets get on a call about this... no matter what it will eb two licks to see the official charter on the Jakarta site. 

I will add a new table that says "charter" 
inside that tab would be this: 
- The MicroProfile community values the following principles:
Limited processes, Experiment and innovate, No backwards compatibility guarantee, Implementation first, Encouraging brand adoption, Openness, and Low barrier to entry. LINK to page?

**Comment by aeiras** [comment]
@rstjames, 

Apologies for confusing you. Now I am also confused b/c Jakarta has nothing to do with MP Charter. ???

https://github.com/eclipse/microprofile-marketing/issues/767#issuecomment-1414439792. This comment provides the new information for the landing space as we did for the MP Prospect. 

**Position of new tab:**

Above Prospectus tab.

**Wording of Charter**
**Title:** MicroProfile Working Group Charter: Vision and Scope

**Description:** The MicroProfile community values the following principles: Limited processes, Experiment and innovate, No backwards compatibility guarantee, Implementation first, Encourage brand adoption, Openness, Low barrier to entry 

[Link] https://www.eclipse.org/org/workinggroups/microprofile-charter.php

---

Example of the new tab ought to follow the format of the Prospectus tab https://microprofile.io/workinggroup/#prospectus

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/10731224/221956742-95537cc0-72f9-43f9-9def-d1965afcd1e3.png">

----

Happy to connect with you over zoom on this and send the minutes to marketing MP afterward within the ticket itself if a call is required after this follow up. Do advise what is needed. A.

**Comment by rstjames** [comment]
set for the year on SM
![2023_microprofile_charter](https://user-images.githubusercontent.com/12132146/222240571-fccd9285-2977-4e08-b8d9-e5b944b97eb1.jpg)

**Comment by aeiras** [comment]
Thank you for using the explanations in the ticket to create the [Charter tab](https://microprofile.io/workinggroup/#mptab-charter), @rstjames. Having it in 2 places on the page is a good improvement.
