### ISSUE TITLE
[2023 Yearly Social Media ] Call to action: Become a WordPress Contributor - blogs, sessions, webinars, etc 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#768]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#SharingIsCaring: Have you shared what you have learned with @MicroProfileIO? Become a MicroProfile Author by contributing your #MicroProfile blogs, recordings, tutorials, e-books, books, sessions...

Join: https://microprofile.io/blog/

#ByCommunityForCommunity #OpenSourceFUN

**Schedule**
Twice per month

**2022 issue**
https://github.com/eclipse/microprofile-marketing/issues/669

**Comment by rstjames** [comment]
![2023_microprofile_share_knowledge](https://user-images.githubusercontent.com/12132146/219706981-310b5001-5ec5-4c79-9503-56705ea65ce2.jpg)

**Comment by rstjames** [comment]
scheduled
