### ISSUE TITLE
MP at RivieraDev

### ISSUE THREAD

**Issue by pilhuhn** [microprofile/microprofile-marketing#77]
1. Title: What is new in Eclipse MicroProfile Metrics 2.0
2. Speaker: Heiko Rupp (Red Hat)
3. Twitter: @pilhuhn @rivieradev
4. URL: https://rivieradev.fr/session/545
5. Date & Time: May 16th, 2019, 13:30
6. Abstract: Eclipse MicroProfile Metrics defines a common way of exposing system and application metrics from MicroProfile applications and the respective servers.

In Metrics 1.x we have defined a model that allows you to easily annotate Java methods and fields etc. to expose their value or call counts.

During the last 2 years the MicroProfile Metrics team has received a lot of feedback which got incorporated into Metrics 2.0

In this talk you learn about MicroProfile Metrics, the news in Metrics 2.0 and also about SmallRye as an open source implementation of the specification

-------

1. Title: Create cloud-native MicroServices with MicroProfile and use the Istio service mesh to run them
2. Speaker: Heiko Rupp (Red Hat)
3. Twitter: @pilhuhn @rivieradev
4. URL: https://rivieradev.fr/session/541
5. Date & Time: May 15th, 2019, 9:00-12:00
6. Abstract: MicroProfile is a set of frameworks that started to cater for modern cloud-native development practices for Java. Some of the sub-specs are:

Metrics - get metrics about your application
Config - easily externalise the configuration of your application
Fault tolerance - take care of failures while calling other services
Distributed Tracing - do profiling of your micro services application over the boundaries of an individual server
Istio as one of the more popular service meshes also brings some of those features as part of the platform.

In this talk we will have a look at what Istio and MicroProfile provide and how you can best combine the two to run your application in an optimal way in a service mesh environment.

**Comment by pilhuhn** [comment]
Please hold this as changes will be coming

**Comment by rstjames** [comment]
@pilhuhn Any update? 
And please write a twitter message for your session.

**Comment by pilhuhn** [comment]
@rstjames Yes. There will only be the 1st session, not the lab and @jmartisk will deliver it.

"Join Jan Martiska at @RivieraDEV on May 16th to learn about news in MicroProfile Metrics 2.0.  https://rivieradev.fr/session/545 "

**Comment by rstjames** [comment]
@pilhuhn sorry this one stuck by me. Next time.
