### ISSUE TITLE
[Website improvement] Resources page add Speaker call to action guidelines

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#770]
Hey @rstjames, 

While creating the social media yearly tickets, I noticed that Resources lacks easy access to Submit a ticket if you are a speaker.  The blog tab is fantastic at it, see below. 
https://microprofile.io/resources/branding/

We need a similar highlight on the Branding page that will be the link used on the speakers' ticket https://github.com/eclipse/microprofile-marketing/issues/769

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/10731224/216169573-f5e21c6e-8bd1-436f-8799-57a7a57cfcb4.png">

Q&A is welcomed as you see fit. Thank you.

**Comment by aeiras** [comment]
@rstjames , 

The position of the call to action is lost at the end of the page. If moved to the top, it could fix the current issue. Clearly, if you find better ways to do it, implement as well. 

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/10731224/216170446-dc916fbc-12fa-4528-864e-8eb844596343.png">

**Comment by rstjames** [comment]
Not sure I agree. There is a submit a git issue button on top. I will try to move it up but will not look good next to the sticky header and the CTA on the lower on the page is connected to the presentation slide deck. Also there is a CTA on the Social media section too.

**Comment by aeiras** [comment]
@rstjames, 

I understand your feedback. 

I see 3 choices, either:

1. the Call 2 Action shared in the above comment becomes a part of the sub-menu, which creates a new tab that can be used on the social media tweet
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/10731224/216449364-627a3917-bf77-4463-b48e-d8f7a74a6303.png">

2. or https://microprofile.io/resources/branding/#   find an easy way for the viewer to find the Call to action by using the link of branding

 3. or we use the wiki link directly (**this is not ideal nor desired**) we wish to teach people how to reach the MP information directly from the website and not via links)

if you see any other options, do share them. :)

**Comment by rstjames** [comment]
Put the link for coverage in the linked menu but will take you to the github. This should work well

**Comment by aeiras** [comment]
> Put the link for coverage in the linked menu but will take you to the github. This should work well

Agree. Lets see how actions by ossDOERs show if latest improvement is better. :) 

Cheers,
