### ISSUE TITLE
[February Marketing Steward ] Reza 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#771]
@m-reza-rahman

I am closing the month's Stewardship by handing over the carryover Feb 6th minutes as a base for ongoing tasks. 

In the agenda, the link of the monthly steward [Basic responsibilities](https://docs.google.com/spreadsheets/d/1gb2D8wPoXIrvmndMt0fP4jDYC61YuvBwVEFqVskywU8/edit#gid=1720520940) is always found.  It doesn't mean you have to do the work, it means you delegate and make sure the ball doesn't drop when tickets arrive at this space. 

Cheers,

**Comment by aeiras** [comment]
Onboarding you to a few spaces:

- Contributor with Triage access to the marketing repo  - completed. https://projects.eclipse.org/projects/technology.microprofile/who
- WordPress access from Contributor to Editor to enable the content review & publishing of MicroProfilers. Your content must be reviewed by others and ought to not be post it without process. 
- Edit access to MP community drive granted https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8
- Write access to MP working group Repository- granted. https://github.com/microprofile/microprofile-wg/settings/access?guidance_task=

**Comment by m-reza-rahman** [comment]
I think this can be considered done.

**Comment by aeiras** [comment]
> I think this can be considered done.

@m-reza-rahman, 

It can be closed if you are choosing to contribute to 1 call and not cover the entire month. 
Usually, the whole month is recommended as it is easier to follow the close up in the month before handing over the open ticket via minutes update. 

If that is the case, the issue will be adjusted to reflect the call and also the spreadsheet with calendar Stweward needs to be adjusted as well.

**Comment by m-reza-rahman** [comment]
Yes, I'll host the month and Dmitry the next. Honestly don't need this issue open, but fine either way.

**Comment by aeiras** [comment]
How do you wish to be contacted by others?

**Comment by m-reza-rahman** [comment]
Is this issue really needed for that? Anyone is always welcome to contact me anyway via any of the mechanisms here: https://reza-rahman.me/contact. I am also the MicroProfile Slack, various mailing lists, etc?

**Comment by aeiras** [comment]
Thank you for enabling the below clarification, Reza. 

Yes, the issue is for you to pull MicroProfilers into Q&A as you see it relevant to unblocking **or** for MicroProfilers pulling you into stuff that is yet to be a git issue and might never become an actual task. 

In MP mktg private collaboration is usually discouraged.  Everyone provides his/her preference for communication during onboarding, especially when owning the monthly Steward responsibility.  There is a truly open-source process in place that enables open communication and open tracking in all tasks. 

As you saw with the MP zoom code, when private data is needed to be shared, private communications are a must. Those are fluid and easy to open and close ASAP. For all else, we use the Steward git ticket and the mailing list when core topics are relevant to the broader community not yet active in git issue tasks.  

Regarding communication channels, many of us (me included) are not and won't join MP slack. 

I hope this helps

**Comment by m-reza-rahman** [comment]
If folks really need to contact me specifically and none of the above works, I'd prefer they just open a ticket for the specific task at hand rather than keeping this open for an entire month. I hope this is OK.

**Comment by m-reza-rahman** [comment]
> Onboarding you to a few spaces:
> 
> * Contributor with Triage access to the marketing repo  - completed. https://projects.eclipse.org/projects/technology.microprofile/who
> * WordPress access from Contributor to Editor to enable the content review & publishing of MicroProfilers. Your content must be reviewed by others and ought to not be post it without process.
> * Edit access to MP community drive granted https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8
> * Write access to MP working group Repository- granted. https://github.com/microprofile/microprofile-wg/settings/access?guidance_task=

Hi @aeiras do you believe I have the correct access to perform these tasks for Dmitry? If not, how do we proceed?

**Comment by aeiras** [comment]
Dias @m-reza-rahman, 

Mitia has access to:

- MP Triage since early 2022
- WordPress - he can review and publish content
- MP community drive - I just sent him that access today.
- MPWG repository - since early 2022 - yet not sure he has accepted the invite.
