### ISSUE TITLE
Add Payara Logo to https://microprofile.io/workinggroup/#

### ISSUE THREAD

**Issue by Jadonblade** [microprofile/microprofile-marketing#772]
**Member**
Name: Payara Services
Organization logo: https://drive.google.com/file/d/1YeH1E4C06yiTC89yXRKlEXsgtB0Cl3AB/view?usp=share_link

**Website**
URL: https://www.payara.fish/

**Comment by aeiras** [comment]
Hey @Jadonblade, welcome back! 

@rstjames, thank you for working on this ticket. :) 

Collaborative Tasks: 

1. **Update Members tab:**  https://microprofile.io/workinggroup/#mptab-members .  (@Jadonblade if the 2 assigned members have a preferred social media, do share it so that it can be added to the website) 
2. **Social Media announcement**: uses the template description

---
Jadon, 

The [Onboarding guidelines](https://microprofile.io/workinggroup/#mptab-members) are there to support you and the team.

**Comment by Jadonblade** [comment]
Thanks @aeiras ! Glad to be back, just trying to get my head round it.

The representative will be:
Luqman Saaed
@gh_geek

The alternate will be:
Jadon Ortlepp
@Jadonblade 

Thank you very much for the quick work @rstjames

**Comment by rstjames** [comment]
Tweet when out announcing payara as a new member, updated the table and added the logo

**Comment by rstjames** [comment]
Are we using this ticket for the Payara quote? @aeiras

**Comment by aeiras** [comment]
> Are we using this ticket for the Payara quote? @aeiras

No, @rstjames. There is a ticket on that task being nicely worked with Reza and the member.

**Comment by aeiras** [comment]
> Thanks @aeiras ! Glad to be back, just trying to get my head round it.
> 
> The representative will be: Luqman Saaed @gh_geek
> 
> The alternate will be: Jadon Ortlepp @Jadonblade
> 
> Thank you very much for the quick work @rstjames

Today via the Community call we met 2 Payara members, fun stuff, Jadon. 

@rstjames has nicely updated the https://microprofile.io/workinggroup/#mptab-members  with the data you provided. Hugs

**Comment by Emily-Jiang** [comment]
Reopened this ticket to have the primary and alaternate rep updated based on [this](https://www.eclipse.org/lists/microprofile-wg/msg01919.html) email.

**Comment by aeiras** [comment]
from the MPWG steering call of 3/28 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/10731224/228338223-c40d849f-7387-4b37-80d5-694c566b9e74.png">

_Back to a topic earlier in the call, note that Alphonso and Luis are respectively primary and alternate reps from Payara to the MP steering committee, this was communicated on the steering committee mailing list (Wed, Feb 1, 4:41 PM ET), and is also documented in the spreadsheet in the MP community drive ...  https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=346790645_

**Comment by aeiras** [comment]
@rstjames, 

Thank you in advance for helping update the Payara members listed in the website with:
Primary: Alfonso Altamirano
Alternate: Luis Neto

**Comment by rstjames** [comment]
@Jadonblade 

Website is updated but is it possible to get Alfonso Altamirano &  Luis Neto twitter handles? 
Thank you!
