### ISSUE TITLE
[Translation] Release MicroProfile 6.0 - Release Blog Post Japanese Translation

### ISSUE THREAD

**Issue by kazumura** [microprofile/microprofile-marketing#773]
Add release blog (#726) post in Japanese

**Comment by aeiras** [comment]
You are amazing, @kazumura :)

**Comment by kazumura** [comment]
preview is ready.  
https://microprofile.io/?p=7160&preview=true

Please review it. @aeiras @emecas

**Comment by aeiras** [comment]
Hola snuggly @kazumura, 

translation looks great. Thank you for adding yourself and others to the translation credits, very important. 

I have published the post yet 2 things are missing:

@rstjames, 

Can you please update to Japanese the design card? If you need @kazumura's help, please pull him in. 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/10731224/217369313-8297dc5d-b2e5-4cfd-b5da-e688cd972dfc.png">

@kazumura, 

Can you please translate to Japanese the https://twitter.com/MicroProfileIO/status/1612780709004939264?s=20&t=Fa-KjZpwAZQgNENAbsfwTw

[#MicroProfileReleaseAnnouncement](https://twitter.com/hashtag/MicroProfileReleaseAnnouncement?src=hashtag_click): [#Microprofile](https://twitter.com/hashtag/Microprofile?src=hashtag_click) 6.0 is released! It adopts 
[@JakartaEE](https://twitter.com/JakartaEE)
 10 Core Profile. 📢 🚀

Learn more [Japanese link)

[#ByCommunityForCommunity](https://twitter.com/hashtag/ByCommunityForCommunity?src=hashtag_click) [#OpenSource](https://twitter.com/hashtag/OpenSource?src=hashtag_click)

The # doesn't need translations :) You and your team rock, thank you for choosing to participate in this initiative inspired by @emecas!

**Comment by aeiras** [comment]
oh Kenji, 

If you could add a picture to your WordPress profile that would be fantastic. 
<img width="144" alt="image" src="https://user-images.githubusercontent.com/10731224/217370745-a5e9b1b0-3586-414f-aa0d-6cf7045205bc.png">

**Comment by kazumura** [comment]
@aeiras 

> Can you please translate to Japanese the https://twitter.com/MicroProfileIO/status/1612780709004939264?s=20&t=Fa-KjZpwAZQgNENAbsfwTw

```
#MicroProfileReleaseAnnouncement: #Microprofile 6.0 がリリースされました！ 
@JakartaEE 10 Core Profile に対応しました。

詳細はこちら<"https://microprofile.io/2023/02/07/microprofile-6-0-release-japanese/">
```

**Comment by kazumura** [comment]
> oh Kenji,
> 
> If you could add a picture to your WordPress profile that would be fantastic. 

Done.

**Comment by aeiras** [comment]
Amazing, Kenji!!! :) 

@rstjames thank you for bringing your magic on the closing of this task!

**Comment by emecas** [comment]
@kazumura  wonderful work  , my Japanese level is zero, but for sure it is a first well accomplished milestone under the community-outreach multilingual initiative, thank you to every body  else who make this possible!! @aeiras  @rstjames  [長尾貴浩(Takahiro Nagao)](https://twitter.com/tnagao7)、笠井輝美(Terumi Kasai)

**Comment by aeiras** [comment]
Thank YOU, Emerson. You inspire all of us to help and contribute. Together, we are lowering the bar to entry on learning about MP technology via news and content in diverse languages. You rock! 

Ohh, Emerson, please whenever you can update the Working group ticket on this task as well. :) Community outreach fun!

**Comment by rstjames** [comment]
@kazumura is this ok? 
![MicroProfile-6 0_release_japanese](https://user-images.githubusercontent.com/12132146/217843992-501fe6e4-5ea9-4ab1-bbb6-08884df2facf.jpg)

**Comment by emecas** [comment]
> Thank YOU, Emerson. You inspire all of us to help and contribute. Together, we are lowering the bar to entry on learning about MP technology via news and content in diverse languages. You rock!
> 
> Ohh, Emerson, please whenever you can update the Working group ticket on this task as well. :) Community outreach fun!

[Done ](https://github.com/microprofile/microprofile-wg/issues/151#issuecomment-1424518369)

@aeiras  I guess you meant this : https://github.com/microprofile/microprofile-wg/issues/151 what is being tracked here https://github.com/microprofile/microprofile-wg/issues/174

**Comment by aeiras** [comment]
Correct, Emerson. Your collaborations are beautiful and valuable!

**Comment by kazumura** [comment]
> @kazumura is this ok? 

Great! Thanks. @emecas

**Comment by rstjames** [comment]
blog is updated and social media scheduled

**Comment by aeiras** [comment]
https://twitter.com/MicroProfileIO/status/1624024150451924993?s=20&t=ttAO9dTfvZGedBDMhe2c1Q
