### ISSUE TITLE
[Quote Submission] Steve Millidge, Payara Services, Corporate/Contributor, Commiter Quote

### ISSUE THREAD

**Issue by PriyaKhairaHanks** [microprofile/microprofile-marketing#774]
**[Quote Submissions Guidelines: MicroProfiler Testimonials](https://github.com/eclipse/microprofile-marketing/wiki/Quote-Submissions-Guidelines:-MicroProfiler-Testimonials)**

**Quote answers**
*60 word max*
Why are you investing the time and resources into the MicroProfile ecosystem?
Why do you think others should contribute to MicroProfile?

 **Design Card**  (for MicroProfile designer)

 **Notes**
 To help with everything

**Comment by m-reza-rahman** [comment]
Please do complete this when you can. Here is a recent hopefully helpful example: https://github.com/eclipse/microprofile-marketing/issues/759.

**Comment by PriyaKhairaHanks** [comment]
Payara Services - 
Word Count: 55
We are proud to continuously support and be a part of the MicroProfile Working Group. 
Our work in the MicroProfile Working Group also allows us to better implement our own MicroProfile certified products. Payara Platform as a whole is MicroProfile compatible but this is particularly important for Payara Micro, our lightweight microservices platform of choice.
Author 
Steve Millidge 
CEO and Founder, Payara Services

@m-reza-rahman

**Comment by m-reza-rahman** [comment]
Do you want the Payara logo to go with this or Steve's photo? Either way, could you kindly attach it? If possible, do please supply a high resolution photo?

**Comment by PriyaKhairaHanks** [comment]
Thanks @m-reza-rahman  
<img width="791" alt="orange_fish-white_text-blue_background--large (3)" src="https://user-images.githubusercontent.com/82879653/217488669-8ed2ffc1-b51f-4685-a558-e148fbbe8a60.png">

**Comment by rstjames** [comment]
@PriyaKhairaHanks  @m-reza-rahman 
The quote has been added to the website

let me know if there are any changes needed

**Comment by PriyaKhairaHanks** [comment]
Thank you @m-reza-rahman @rstjames !!

**Comment by aeiras** [comment]
> @PriyaKhairaHanks @m-reza-rahman The quote has been added to the website
> 
> let me know if there are any changes needed

@rstjames, 

Let's follow past conventions and remove the title from the Corporate quote. 
Under Steve's name, the company name suffices.  Thank you. 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/10731224/217601371-5fb06379-e3be-4651-a9ef-5172badc2f0e.png">

**Comment by rstjames** [comment]
Updated @aeiras
