### ISSUE TITLE
[MPWG Tab] Add EF ANTITRUST COMPLIANCE POLICY to Release Guideline tab

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#775]
@rstjames, 

Yesterday during the community call, we had an update on Antitrust compliance. 

Please help us add under https://microprofile.io/workinggroup/#mptab-release-guideline the [Eclipse Foundation Antitrust Compliance Policy](https://www.eclipse.org/org/documents/Eclipse_Antitrust_Policy.pdf)

Thank you,

**Comment by rstjames** [comment]
updated
