### ISSUE TITLE
[2023 API call Social media Quarterly reminders] MP Telemetry 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#776]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileTelemetry enables @jakartaee RESTful Web Services automatically to be traced if configured.
Join its weekly Monday discussions. Your participation ensures the continued growth & development of a well-governed, vendor-neutral #opensource API.

https://bit.ly/calendar-zoom-minutes

**Quarterly reminder**
 1 every quarter
Ideally, a reminder goes out 4 times per year, always on a Monday before the call. 

**Design Card**
Highlight Monday
6 to 6:30 AM PDT- time needs to be transferred to EU time

**Notes**

**Comment by rstjames** [comment]
![2023_microprofile_telemetry_call](https://user-images.githubusercontent.com/12132146/219700671-029ddfd1-b9bc-442c-a123-a035596d8acc.jpg)

**Comment by rstjames** [comment]
scheduled
