### ISSUE TITLE
[2023 API call Social media Quarterly reminders] MP OpenAPI Call

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#777]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileOpenAPI transforms any application into language-agnostic services that can be called from anywhere: on-premises, private cloud, public cloud, etc. Join its weekly Monday discussions. #opensource

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

**Quarterly reminder**
1 every quarter
Ideally, a reminder goes out 4 times per year, always on a Monday before the call.

**Design Card**
Highlight Monday
6:30 to 7 AM PDT- time needs to be transferred to EU time

Notes

**Comment by rstjames** [comment]
![2023_microprofile_openapi_call](https://user-images.githubusercontent.com/12132146/219700053-2a7020ee-8077-4aa4-8e24-1b6977563468.jpg)

**Comment by rstjames** [comment]
Scheduled
