### ISSUE TITLE
[2023 API call Social media Quarterly reminders] Marketing 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#778]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileMarketing highlights @MicroProfileIO around the world. It looks for #OSSContributors wishing to brainstorm new ideas, simplify processes, create and maintain effective communication messages, etc. Join its bi-monthly Monday discussions  #OSS
https://bit.ly/calendar-zoom-minutes

**Quarterly reminder**
1 every quarter
Ideally, a reminder goes out 4 times per year, always on a Monday before the call.

**Design Card**
Highlight Monday, 
Every other Monday
10 to 11 AM PDT

Notes

**Comment by rstjames** [comment]
![2023_microprofile_marketing_call](https://user-images.githubusercontent.com/12132146/219697303-14d6cfa9-ceae-488b-b39b-e4dfbfd7ed4d.jpg)

**Comment by aeiras** [comment]
nice

**Comment by rstjames** [comment]
Scheduled
