### ISSUE TITLE
[2023 API call Social media Quarterly reminders] MP Metrics

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#779]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileMetrics delivers details about the microservices runtime behavior by providing a unified way for @MicroProfileIO servers to export monitoring data to management agents. Join its weekly Tuesday discussions. #opensource 

https://bit.ly/calendar-zoom-minutes

**Quarterly reminder**
1 every quarter
Ideally, a reminder goes out 4 times per year, always on a Tuesday before the call.

**Design Card**
Highlight Tuesday
6 to 7 AM PDT- time needs to be transferred to EU time

**Notes**

**Comment by rstjames** [comment]
![2023_microprofile_metrics_call](https://user-images.githubusercontent.com/12132146/219695535-dcc698fe-f49b-4274-b161-56fb01ca8998.jpg)

**Comment by aeiras** [comment]
Misses the day. lets insert for standard as seen in the other cards.

**Comment by aeiras** [comment]
oh i see, it is a mix and match with location. I missed the day. very cool.

**Comment by rstjames** [comment]
Scheduled
