### ISSUE TITLE
Send MP logo high res to DevoxxUK for DevRoxx 2019 party sponsorship !

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#78]
@rstjames  lets send to Mark: mark.hazell@devoxx.co.uk the MP high res logo. 

Thank you!

**Comment by rstjames** [comment]
[MicroProfile-logo.zip](https://github.com/eclipse/microprofile-marketing/files/3129018/MicroProfile-logo.zip)

**Comment by rstjames** [comment]
I will email him now

**Comment by aeiras** [comment]
thank you! please close issue once you are done so i know he and team are not waiting for us. :)
