### ISSUE TITLE
[2023 API call Social media Quarterly reminders] MP Technical 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#780]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileTechnology looks for #OSSContributors wishing to brainstorm the creation of new technology, improve current @MicroProfileIO APIs, create and maintain documentation, etc. Join its bi-monthly Tuesday discussions #oss

https://bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

**Quarterly reminder**
1 every quarter
Ideally, a reminder goes out 4 times per year, always on a Tuesday before the call.

Design Card
Highlight Tuesday
11am - 12pm  PDT

Notes

**Comment by rstjames** [comment]
![2023_microprofile_Technical_call](https://user-images.githubusercontent.com/12132146/219694854-289ef606-45f5-41d7-a42a-713a7b66874e.jpg)

**Comment by rstjames** [comment]
scheduled
