### ISSUE TITLE
[2023 API call Social media Quarterly reminders] MP Community 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#781]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

Media Description
#MicroProfileCommunity participation ensures the growth, maintenance, and development of a well-governed, vendor-neutral #opensource project. Join and contribute to its bi-monthly Tuesday calls. #OSS

bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

Quarterly reminder
1 every quarter
Ideally, a reminder goes out 4 times per year, always on a Tuesday before the call.

Design Card
Highlight Tuesday
bi-monthly
11am - 12pm PDT 

Notes

**Comment by rstjames** [comment]
![2023_microprofile_community_call](https://user-images.githubusercontent.com/12132146/219692901-e5d43598-a31b-4cfe-afdb-e0c90799a269.jpg)

**Comment by rstjames** [comment]
scheduled
