### ISSUE TITLE
[2023 API call Social media Quarterly reminders]  MP GraphQL

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#782]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileGraphQL provides a "code-first" set of APIs that enables users to quickly develop portable #GraphQL-based applications in #Java. Join its monthly Wednesday calls. #opensource

bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

**Quarterly reminder**
1 every quarter
Ideally, a reminder goes out 3 times per year, always on a Wednesday before the call.  

**Design Card**
Highlight the first Wednesday of every month 
11am - 12 pm PDT

**Notes**

**Comment by rstjames** [comment]
![2023_microprofile_graphl_call](https://user-images.githubusercontent.com/12132146/219689183-8db7c889-9007-4751-807a-2920f5acf16a.jpg)

**Comment by aeiras** [comment]
super clean.

**Comment by rstjames** [comment]
scheduled
