### ISSUE TITLE
[2023 API call Social media Quarterly reminders] MP Context Propagation

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#783]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

**Media Description**
#MicroProfileContextPropagation defines a fluent builder API to programmatically obtain instances of #ManagedExecutor and #ThreadContext.  Join its monthly Thursday calls. #opensource

bit.ly/calendar-zoom-minutes

#ByCommunityForCommunity

**Quarterly reminder**
1 every quarter
Ideally, a reminder goes out 3 times per year, always on a Thursday before the call.

**Design Card**
Highlight Thursdays
1 per month occurrence 
6:30am- 7:30am PDT - Time needs to be. change to EU

**Notes**

**Comment by rstjames** [comment]
![2023_microprofile_Context_Propagation_Call](https://user-images.githubusercontent.com/12132146/219686767-6821f0b3-e0a6-47b3-bc25-9ef419fd6501.jpg)

**Comment by aeiras** [comment]
applicable to all API and MP calls, do you think adding also the day of the week the call happens is effective? When a constant, I think it should be in the card.  Yet, I will leave such change up to you or not. Thanks @rstjames

**Comment by aeiras** [comment]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/10731224/219738307-46f70395-e4ab-4f60-9331-900c5c220319.png">
 JWT design has the day. :)

**Comment by rstjames** [comment]
scheduled
