### ISSUE TITLE
[2023 API call Social media Quarterly reminders] JSON Web Token - JWT

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#784]
[Yearly Spreadsheet Media Inventory](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)

Media Description
#MicroProfileJSONWebToken - #MPJWT is used as the basis for interoperable authentication and authorization by providing role-based access control #RBAC microservice endpoints using #OpenID Connect, #OIDC.  Join its bi-monthly Thursday calls. #opensouce

bit.ly/calendar-zoom-minutes

Quarterly reminder
1 every quarter
Ideally, a reminder goes out 3 times per year, always on a Thursday before the call.

Design Card
Highlight Thursdays
twice monthly  occurrence
8am-9am PDT

**Comment by rstjames** [comment]
![2023_microprofile_json_web_token_call](https://user-images.githubusercontent.com/12132146/219684928-f7f14de9-5377-4e3d-b7e9-2ceab69ce175.jpg)

**Comment by aeiras** [comment]
looks good, it shows the day of the call!

**Comment by rstjames** [comment]
scheduled
