### ISSUE TITLE
[2023 - Content Contribution -  Social media Quarterly reminders]  Victor @Tuxtor - Spanish - 13 Videos

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#785]
2022 issue https://github.com/eclipse/microprofile-marketing/issues/668

https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074

**Description**

#MicroProfileVideoTutoriales: Si estas iniciando una aplicación con microservicios y @java,  Victor Orozco @tuxtor's 13 videos pueden ayudarte a explorar el camino #CloudNative con #Java y #MicroProfile a través de diversas implementaciones. #opensource

https://microprofile.io/2021/09/01/videotutoriales-recorriendo-microprofile-en-espanol/

**schedule**
6 times 
do not schedule on the weekends 

**Design**

Highlight victor pic
use only Spanish words on the card
add huge Video emoji or similar

**Comment by rstjames** [comment]
![2023_microprofile_spanish_videos](https://user-images.githubusercontent.com/12132146/219681491-82bae3da-b3e7-4d59-b09f-c3274fdae38a.jpg)

**Comment by aeiras** [comment]
This looks wonderful.

**Comment by aeiras** [comment]
i wonder if the word **Video Tutoriales** can be more explicit in the design, @rstjames?

**Comment by rstjames** [comment]
@aeiras 
![2023_microprofile_spanish_videos](https://user-images.githubusercontent.com/12132146/220161409-c2c3f92d-dd39-423a-aac1-ca0e30387d52.jpg)
fixed

**Comment by aeiras** [comment]
it looks great. 

always stating the facts in the media is preferred. Thank you, Ryan for improving it.

**Comment by rstjames** [comment]
Scheduled for 6 times
