### ISSUE TITLE
[2023 - Content Contribution - Social media Quarterly reminders] Emily & other IBMers- ebook

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#786]
2022 issue https://github.com/eclipse/microprofile-marketing/issues/672

https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074

**Description**

#MicroProfileBook: Practical Cloud-Native #Java Application Development with #MicroProfile, a book by @emilyfhjiang @AndrewMcCright @NottyCode @david_yk_chan & @iwalcorn, builds cloud-native applications using @OpenLibertyl0 @docker @IstioMesh. #OSS

ibm.biz/MicroProfileBook

**schedule**
6 times

**Design**

**Comment by rstjames** [comment]
![2023_microprofile_book](https://user-images.githubusercontent.com/12132146/219675542-bc6942c6-f6cb-419a-b03f-22678b0f183f.jpg)

**Comment by rstjames** [comment]
![2023_microprofile_book](https://user-images.githubusercontent.com/12132146/219679120-ec6e4896-b9ea-4551-9a6e-497d8d3e6632.jpg)

**Comment by rstjames** [comment]
scheduled for 6 times
