### ISSUE TITLE
[2023 social media - quarterly highlight] Budget and Program plan - Transparency

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#787]
https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074
**Description**

#MicroProfileTransparency:  The #MicroProfile yearly Program Plan is drafted and worked in the open with the #MicroProfileCommunity. The annual Budget covers the priorities in the Program Plan, publicly accessible. #ByCommunityForCommunity #opensource

https://microprofile.io/workinggroup/#mptab-program-plan-budget

**Schedule**

6 times in 2023
can be weekends and weekdays

**Comment by rstjames** [comment]
![2023_microprofile_budget_plan](https://user-images.githubusercontent.com/12132146/219671723-a307c3ec-bd6e-48dc-8828-eed7c2190814.jpg)

**Comment by aeiras** [comment]
@rstjames,

this media misses the Budget. Both, program & budget will be shared at stated in the description. Let’s add the budget as well. Thank you!

**Comment by rstjames** [comment]
scheduled to go out 6 times

**Comment by aeiras** [comment]
@rstjames, 

Did you adjust the card to include the budget?

**Comment by rstjames** [comment]
@aeiras yes
![2023_microprofile_budget_plan](https://user-images.githubusercontent.com/12132146/220871273-7152b6a1-2fdf-4d7d-9d3e-ec7178033baa.jpg)

**Comment by aeiras** [comment]
> @aeiras yes
> ![2023_microprofile_budget_plan](https://user-images.githubusercontent.com/12132146/220871273-7152b6a1-2fdf-4d7d-9d3e-ec7178033baa.jpg)

looks great, Ryan!
