### ISSUE TITLE
Onboard Dmitry to run March Meetings

### ISSUE THREAD

**Issue by m-reza-rahman** [microprofile/microprofile-marketing#788]
Onboard @dalexandrov to run the marketing meeting for March.

**Comment by m-reza-rahman** [comment]
> * Contributor with Triage access to the marketing repo  - completed. https://projects.eclipse.org/projects/technology.microprofile/who
> * WordPress access from Contributor to Editor to enable the content review & publishing of MicroProfilers. Your content must be reviewed by others and ought to not be post it without process.
> * Edit access to MP community drive granted https://drive.google.com/drive/u/0/folders/0B8_67yGf9LkLOTdPeHdRRl9aWG8
> * Write access to MP working group Repository- granted. https://github.com/microprofile/microprofile-wg/settings/access?guidance_task=

Hi @aeiras do you believe I have the correct access to perform these tasks for @dalexandrov? If not, how do we proceed?

**Comment by aeiras** [comment]
@m-reza-rahman, 

You can provide access to the MP community drive to Mitia.  I checked, and he didn't have access, so I provided him with that access to help.

Mitia has access to all the other tools you have listed. 

**Note:** A Monthly Steward doesn't need to grant access to the next MP marketing Steward.  Given how delicate the INFRA is and the tracking applied, https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1040459762 check INFRA Admin, we keep the circle small and trackable and do exactly what you are doing. Using git issues to enable onboarding via its own ticket and making sure any access beyond contributing is added to the INFRA sheet. 

@m-reza-rahman, as you offboard yourself from Feb Stewardship, please take a look at [Monthly Mktg-Call Stewards & Responsabilities](https://docs.google.com/spreadsheets/d/1gb2D8wPoXIrvmndMt0fP4jDYC61YuvBwVEFqVskywU8/edit#gid=1720520940)
and add, and adjust tasks to hopefully improve what currently is, if you find it applicable. 
Same feedback for @dalexandrov

**Comment by aeiras** [comment]
@dalexandrov, 

Welcome back to Stewardship on MP marketing! I think you have Reza to support you. Kudos! 

@m-reza-rahman, if you provided a Zoom access code to Mitia, please update the Infra sheet under zoom accordantly. All-access must be traced in the sheet. Thank you!

**Comment by m-reza-rahman** [comment]
> @m-reza-rahman, if you provided a Zoom access code to Mitia, please update the Infra sheet under zoom accordantly. All-access must be traced in the sheet.

Yes, he has the access code (as do I of course). It does not look like I have edit access to the sheet. You can either provide me edit access or simply make the updates. Either way is fine.

**Comment by m-reza-rahman** [comment]
Hi @dalexandrov, it looks to me like you are all set to go for March. Do you mind kindly assigning yourself to this issue and/or close it if you don't need it any more? You can of course always count on me if you need help/backup.

**Comment by aeiras** [comment]
> > @m-reza-rahman, if you provided a Zoom access code to Mitia, please update the Infra sheet under zoom accordantly. All-access must be traced in the sheet.
> 
> Yes, he has the access code (as do I, of course). It does not look like I have edit access to the sheet. You can either provide me edit access or simply make the updates. Either way is fine.

@m-reza-rahman, 

You should have no restrictions to edit anything in the drive, including the INFRA Admins document.  What email are you using to log into the MP Drive? If the email used to grant you access is incorrect, please share a new one. 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/10731224/220991331-a7793ead-7ae7-490e-bfd7-8c86beca403c.png">

**Comment by m-reza-rahman** [comment]
The correct email for anything Google related is m dot reza dot rahman at gmail dot com. Perhaps you were using the Lycos one?

**Comment by aeiras** [comment]
Access has been corrected. Thanks, Reza. 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/10731224/220995224-31f46e89-2e89-4fd2-a8ad-23e7259e10ba.png">

**Comment by m-reza-rahman** [comment]
Hmm. Something is still off. I simply asked for access to the sheet directly.

**Comment by aeiras** [comment]
That file is quite "restricted" beyond the regular drive, Reza. I always forget about it. 
I just sent you to edit access. You should be able to help with its upkeep from today onwards.

**Comment by m-reza-rahman** [comment]
Great, the Zoom access folks is updated in the sheet now.

**Comment by aeiras** [comment]
Hola @dalexandrov, 

Via suggested editing, I contributed to the agenda to add new tickets created to track the work in progress. 

I had a few issues finding the categories where to place the working tickets.  
Ideally, the agenda tracks this repository by sections or the MPWG yearly marketing goals at the bare minimum.  

Looking forward to seeing you rock MP work in March! :)

**Comment by dalexandrov** [comment]
Ok, I'll take care :)

**Comment by dalexandrov** [comment]
Completed!
