### ISSUE TITLE
DevRoxx 2019 Party with MP as its 5 sponsor Banner

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#79]
alone side with the other 4 Sponsors which include devoxxUK, lets create a fun banner to push event. 

The paper invites are not ready, once ready- we can push them too via virtual means. :)

**Comment by rstjames** [comment]
@aeiras Do we have any content? What do we want to say? 
When is this due?

**Comment by aeiras** [comment]
Monday  & Thursday next week! 
DevoxxUK team will create the party invite this week, after beer name is secured, eta tmw. 
I will add items to enable push once that is finalized.
