### ISSUE TITLE
[2022 Swag Distribution] Logistics

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#790]
@emecas, 

I hear you are once again the EF mediator on this. Amazing!

This ticket will be added to [2022 Tab- Swag Allocation - Steering Committee Members](https://docs.google.com/spreadsheets/d/1wZzuKyniHy1PEuKm2OAZ9laKquyZ0XiscEZb65BHvoE/edit#gid=0)

----

**Conversation via MP email forums**:

Community forum:
- [Swag Distribution Decisions at DevNexus](https://groups.google.com/g/microprofile/c/Zi05_tq9RPY)
- [Re: JavaLand?](https://groups.google.com/g/microprofile/c/VUWS3ZS4mr4)
- [Help Distribute MicroProfile Swag at DevNexus?
](https://groups.google.com/g/microprofile/c/iV9eliB8mIk)

Marketing forum:

- [2022 Swag Distribution](https://groups.google.com/g/microprofile-marketing/c/Wcj5mM_8njs)
- [Swag Distribution Decisions at DevNexus](https://groups.google.com/g/microprofile-marketing/c/Ed9Yuyc8cBE)
- [JavaLand?](https://groups.google.com/g/microprofile-marketing/c/2njyeR6YgOM)
- [Help Distribute MicroProfile Swag at DevNexus?
](https://groups.google.com/g/microprofile-marketing/c/I9ANW7pNTM8)

Working Group forum:

- [Re: [microprofile-wg] JavaLand?](https://www.eclipse.org/lists/microprofile-wg/msg01853.html)
- [Re: [microprofile-wg] [microprofile] Re: Swag Distribution Decisions at DevNexus](https://www.eclipse.org/lists/microprofile-wg/msg01849.html)
- [[microprofile-wg] Emerson Castaneda/Reza Rahman as Swag Delegates](https://www.eclipse.org/lists/microprofile-wg/msg01837.html)

--

**Comment by m-reza-rahman** [comment]
This is being sorted. I will close this once the last of the 2022 swag is sent out of the warehouse, hopefully very shortly.

**Comment by dalexandrov** [comment]
We need to spend the remaining $15K from 2022 on hoodies and stickers very soon to avoid any possible tax/spending complexities. We should look at spending some of this at DevNexus. Emerson and Reza are now official swag delegates for MicroProfile. Here is what is left over that we need to distribute:

250 hoodies
5000 stickers

**Comment by dalexandrov** [comment]
[Amelia] [Feb 16th - MPWG email about what is available with the 2022 $15K](https://www.eclipse.org/lists/microprofile-wg/msg01847.html)
[Spreadsheet - Swag Allocation - Steering Committee Members](https://docs.google.com/spreadsheets/d/1wZzuKyniHy1PEuKm2OAZ9laKquyZ0XiscEZb65BHvoE/edit#gid=0)  tracking and inventory history

**Comment by emecas** [comment]
@m-reza-rahman  @aeiras  

Shipping spreadsheet is practically completed with information for:

Destination | ID
-- | --
Red Hat | 1
Oracle | 2
Fujitsu | 3
Microsoft | 4
Tomitribe | 5
Primeton | 6
Atlanta JUG | 7
Garden State JUG | 8
iJUG | 9
IBM | 10
Payara | 11
Kevin Sutter (IBM) | 12

**Comment by yeekangc** [comment]
Where will we be shipping "Kevin Sutter (IBM)" (i.e. ID 12)?  Just noticed this.

How does it differ from "IBM" (i.e. 10)?

We can discuss the details over emails if that's better and easier.

Cc @Emily-Jiang @trulymobilenwp

**Comment by Emily-Jiang** [comment]
> Where will we be shipping "Kevin Sutter (IBM)" (i.e. ID 12)? Just noticed this.
> 
> How does it differ from "IBM" (i.e. 10)?
> 
> We can discuss the details over emails if that's better and easier.
> 
> Cc @Emily-Jiang @trulymobilenwp

No worries. This was handled already and the package should have been on its way if I am not mistaken.

**Comment by yeekangc** [comment]
Thanks, Emily!  Sorry for the confusion.  Emily and I chatted and we got it clear now.  =)

Thank you, all!

**Comment by emecas** [comment]
Update:

Today, I have provided track numbers via email for each one of these packages:

Company| -- | -- | -- | Confirmation notes
-- | -- | -- | -- | --
Red Hat | 1 | Roberto | Cortez  | Received Hoodies -  Issues with stickers (got stuck in custom, Roberto is taking care of that)
Oracle | 2 | Ed | Bratt | Confirmation in pending
Fujitsu | 3 | Kenji | Kazumura | Received , only hoodies - Expected: XS:1, S:1, M:6, L:6, XL:2, XXL:1, Sticker:400 Actually Shipped: XS:1, S:1, M:6, L:0, XL:0, XXL:1, Sticker:0 - On Review 
Tomitribe | 5 | Amelia | Eiras  | Received 
Atlanta JUG | 7 | Vincent | Mayers | Confirmation in pending
Garden State JUG | 8 | Mike | Redlich | Received 
IBM | 10 | DEVNEXUS 2023 SHOW MANAGEMENT/IBM | c/oFreeman | Confirmation in pending
Payara | 11 | DEVNEXUS 2023 SHOW MANAGEMENT/PAYARA | c/oFreeman | Confirmation in pending
Kevin Sutter (IBM) | 12 | Kevin | Sutter | Confirmation in pending

**Comment by aeiras** [comment]
Tomitribe swag has been received. Thank you!

Now we can ship swag to you, @emecas,  Kevin (nicely added above) & a few other MicroProfilers using the 2021 shirts and 2022 hoody received.

**Comment by aeiras** [comment]
Closing this!
