### ISSUE TITLE
[2023 - MP design Swag] Update designs to include new Members - Print Outside MPWG budget by Members

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#791]
@rstjames, 

Thank you for helping update the design on t-shirts and hoodies with the new folder[2023](https://drive.google.com/drive/u/0/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg)

The designs are for MPWG usage and not a part of the project's marketing budget.

**Comment by rstjames** [comment]
@aeiras what do you want me to do here? There is no 2023 swag created. We had the shirt and hoodie design from 2022 or 2021 not sure that elcipse said they would not print with the company logos on it

**Comment by aeiras** [comment]
@rstjames, 

please update the designs to include the new members, no changes to the design. 

The print will be done outside the project’s budget, using which ever vendors each member chooses. As before. No changes. 

Thank you 🙏

**Comment by m-reza-rahman** [comment]
Please note that it’s important to check with Microsoft brand marketing before using the Microsoft logo anywhere. We have explicit permission to include the Microsoft logo on the MicroProfile site in a very limited fashion. I would not be surprised if similar approvals are needed for Oracle, IBM, etc.

**Comment by aeiras** [comment]
Correct, Reza. 
 The 2023 design will be approved via a resolution by all members to enable its printing by any member. That is part of regular the design approval process once the Ryan helps with design update.

**Comment by aeiras** [comment]
Deluxe Printing, the trusted printing USA Vendor, has received the yearly request to update the MP back of the shirt within its systems. MP swag forum email was cc'd on yearly update requests. 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/10731224/221978815-2fd53740-0fc2-46c6-a7c9-f09bf55fc300.png">

**Comment by rstjames** [comment]
@Emily-Jiang Can you please help me get Primeton logo in vector format? I believe you were the one helping onboard them and the logo I got was not print quality. 
![image](https://user-images.githubusercontent.com/12132146/222452157-a9fc1d09-8dc4-4464-b0a8-6058d6a0516c.png)

When I have this logo I will be able to update all print data or if we are not able to get it I will need to recreate the logo

@aeiras if you know how to get this logo please let me know.

**Comment by aeiras** [comment]
@rstjames, 

Primeton provided the logo to update the 2022 swag in this ticket via the following comment:  https://github.com/eclipse/microprofile-marketing/issues/712#issuecomment-1342161355

Lets update the drive with their logo under Members' logos to avoid future delays. Thank you!

**Comment by rstjames** [comment]
@aeiras yes the provided a new logo but it is a "jpg" (for web use) not for print. I need a "vector" logo formate for printing.  

@Emily-Jiang and it would be great if they had a vertica version of the logo. That way the logo will be proportional on the swag with the other logos.

**Comment by aeiras** [comment]
gotcha. 

I have sent this issue via email to @mingyuehuang99.

**Comment by aeiras** [comment]
@rstjames, 

[MPWG Logos](https://drive.google.com/drive/u/0/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk) also misses the MSFT logos. I created the folder to host those files. Please help update the folder. Thank you.

**Comment by m-reza-rahman** [comment]
Who had provided you with the logo for the website? I will need to ask our branding and marketing folks, who will inevitably ask what this is for (and probably will not approve this usage of the logo).

**Comment by aeiras** [comment]
via swag https://drive.google.com/drive/u/0/folders/1LXgXYIYPSmUteMd0fA7lr9ZP9WE0U259 mock up
<img width="755" alt="image" src="https://user-images.githubusercontent.com/10731224/223233603-7982228c-8fc4-4743-a27b-c83b90ceffdc.png">

The 2023 shirt and hoody will be updated. The logos are used only for those two swag items and cover the 2023 membership listing as members change and design changes. 

MPWH Members, during onboarding, provide their company's logos directly to the drive or via email or ticket (for website usage). It is written in the onboarding guidelines as a requirement upon joining the WG. 

I hope this clarifies.

**Comment by m-reza-rahman** [comment]
If this is important right now, I will ask our branding folks - explaining to them what the intended use is. I also want to clarify - so the idea is that any member company of the working group (e.g. Tomitribe) wants the rights to print these shirts with the Microsoft logo on it?

**Comment by aeiras** [comment]
Correct, Reza. Thanks for the follow-up questions. 

Any member can print the approved t-shirt for any reason, say Conference booth, sessions, workshop, etc.
Those prints are private by Members who do not need further authorization for printing. As such, it lands **outside** using the MPWG **yearly** budget. 

Lastly, a member who responds with **-1** or a **0** on the Resolution of 2023 design will be removed from the swag design. Only +1 voting members are a part of the yearly MP design.

**Comment by m-reza-rahman** [comment]
OK. I will check with our branding folks. For now, I advise assuming a -1 vote from Microsoft with a clear explanation of why that is on the mailing list so that it is very visible to others that most likely will have very similar challenges with their own organizations.

**Comment by m-reza-rahman** [comment]
While I check on this, @rstjames, I would like to suggest a much less potentially problematic design idea - how about leaving out the logos and just printing a list of member names in alphabetical (probably with a time range added for accuracy like `Working Group Members - X, Y - A, B`) in the back? Kind of in the style of band tour shirts: https://www.apparelsearch.com/influence/products/images/concert_tour_t-shirt-1977.jpg. Our branding folks can't really object to the name of the company with generic font listed in a factual fashion. This gets around many awkward questions probably for a lot of people that don't need the hassle within their companies.

**Comment by aeiras** [comment]
Reza, 

I recommend MSFT sends the vote to the actual resolution email.   There is no rush, there is no advance printing of any form.  Avoid confusing MicroProfilers is always preferred. Thank you,

**Comment by m-reza-rahman** [comment]
There is a resolution email? Do you mind sharing a link please? Happy to share what our branding folks say once I confirm internally. I suspect it won't take long.

**Comment by aeiras** [comment]
there is no email yet because there is no 2023 design.  That’s why I ask for your patience on forum communications to avoid unnecessary noise. 
 
 This ticket remains the most important source tackling the swag design.  You could point to particular comments if it helps you with internal communications.

**Comment by mingyuehuang99** [comment]
halo, I  can provide the "ai format "of primeton logo,Is this ai format ok? ：）
[primeton logo.zip](https://github.com/eclipse/microprofile-marketing/files/10904316/primeton.logo.zip)

**Comment by mingyuehuang99** [comment]
@aeiras @rstjames 
halo, I can provide the  "ai format " of primeton logo,Is this ai format ok? ：）
[primeton logo.zip](https://github.com/eclipse/microprofile-marketing/files/10904326/primeton.logo.zip)

**Comment by m-reza-rahman** [comment]
To be honest, I am not entirely sure how to proceed. For now I will at least get my homework done internally. My challenge is that I think this is most likely not just an issue with Microsoft. To be honest I don't think many of the companies that we partner with in the Java ecosystem are really any different in this regard. Most have to abide by their marketing and branding structures too, and those are not terribly lax either. I have also already asked the Foundation for advice on this based on their experience working with many organizations similar to Microsoft. Hopefully they too will share some insights soon.

**Comment by m-reza-rahman** [comment]
The Foundation just got back to me about this. Here is what they shared: https://www.eclipse.org/lists/microprofile-wg/msg01755.html. Basically the Foundation's policy is to not print member logos on swag/clothing. I was not aware of this, but it makes total sense. I will further follow-up with an official response from our branding folks.

**Comment by rstjames** [comment]
Small issue with adding the new member logo Primeton. @mingyuehuang99 

The logo provided is longer than others member logos. When sizing it to fit equals as the other logos it is very small. Unless we move the characters above the logo. I do not know if this is agains branding for Primeton or is ok to do when there is no other solution. (refer to pictures attached) I found this layout of the logo online, but I do not know if its official 

<img width="627" alt="Screenshot 2023-03-09 at 10 13 19" src="https://user-images.githubusercontent.com/12132146/223976146-ddb06065-1db7-49a4-86f5-f1763d42bc20.png">
<img width="626" alt="Screenshot 2023-03-09 at 10 12 29" src="https://user-images.githubusercontent.com/12132146/223976158-7aef4e03-905a-4dd2-b457-e52c62b453bd.png">

**Comment by rstjames** [comment]
@mingyuehuang99 Hi could you please look at the message above. Thank you!

**Comment by mingyuehuang99** [comment]
@rstjames  Hi！ Move the characters above the logo is better，and i confirm that is official too.
thank you :)

**Comment by rstjames** [comment]
All has been updated on the drive: @aeiras 

shirt: 
https://drive.google.com/drive/folders/10HK2v2NVrploWgl66jE1o8B6YnYVAGc2?usp=share_link

hoodie:
https://drive.google.com/drive/folders/1gfoArj7GodC97Vwy6OciLOhjhQmzha-k?usp=share_link

**Comment by aeiras** [comment]
It looks great, @rstjames. 
Thank you. 

We will add the design to the Steering committee discussion next Tuesday.

**Comment by croundy** [comment]
It looks like we need to once again clarify that the Eclipse Foundation policy is that we do not include member/corporate logos on any Eclipse and/or working group clothing or other swag items. This policy applies regardless of whether working group or individual member budgets are being used to acquire the swag. This is a trademark usage issue, not a budget issue. MicroProfile is an Eclipse Foundation trademark and these designs are out of bounds. This has been previously addressed and resolved here:  https://www.eclipse.org/lists/microprofile-wg/msg01755.html

**Comment by hendrikebbers** [comment]
Can somebody please tell me the reason behind that problem? Sure Eclipse currently does not have the rights to print the company logos on the shirt but what is the general problem with collecting such rights. I can not find an answer in this issue or the mails.

**Comment by m-reza-rahman** [comment]
I’ll provide my honest two cents personally. It’s going to be a pretty steep uphill battle for me to get Microsoft legal, marketing, and branding to allow a third party to print the Microsoft logo on clothing, etc. It’s the way branding law works in the US. Giving the brand away frivolously makes it very difficult to protect it when needed. I am honestly shocked how IBM, Oracle, etc did not raise an objection with this much earlier.

Note, I am not a lawyer. Just someone that’s spent a good deal of their career working with very large US companies with globally recognized brands.

**Comment by hendrikebbers** [comment]
Thx @m-reza-rahman didn't know about that. Is it the same for paper flyers? So if we at Adoptium wants to print a flyer we can not print the logos of the wg members on it? Really interesting to see that there is a difference between having a logo on a website vs having it on a physical object. Would love to get more insights in that topic. maybe you or @croundy have a good reading tip or general advice for me?

**Comment by m-reza-rahman** [comment]
I would in general seek the Foundation’s advice before doing anything with logos. For the website, conference sponsor pages, etc there is usually an explicit release clause that Microsoft typically signs as part of the legal agreement.

By the way, it is pretty much always OK to use the word “Microsoft” as long as the context is clear and there is no effort to emulate the Microsoft logo font or otherwise misappropriate the brand. That’s what I suggested as a viable alternative for these shirts (and that’s what I would honestly suggest for things like flyers too). I am a bit confused why that’s not deemed sufficient honestly.

**Comment by hendrikebbers** [comment]
Thank you for the insights

**Comment by rstjames** [comment]
https://github.com/eclipse/microprofile-marketing/issues/792

Some ideas for scaling printing - If we can not print WG logos, can we print just the front MP logo?

**Comment by rstjames** [comment]
![MP_shirt-Back](https://github.com/eclipse/microprofile-marketing/assets/12132146/58d8434f-a3ff-467f-81fb-136f239261b2)
<img width="898" alt="front" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/d33ca7ae-f357-4dfa-b281-aaa312452e43">

Let me know what you all think. 
@m-reza-rahman @hendrikebbers @min

**Comment by m-reza-rahman** [comment]
I think this is fine. I hope the vote passes.

**Comment by aeiras** [comment]
History and tracing in MPWG channels:

- [MPWG forum - [[microprofile-wg] [DISCUSSION] "Self-Service" MicroProfile Shirts](https://www.eclipse.org/lists/microprofile-wg/msg01956.html)](https://www.eclipse.org/lists/microprofile-wg/threads.html#01956)
- [MPWG Marketing forum ](https://groups.google.com/g/microprofile-marketing/c/MQu_fXdqJPU)
- Git issue- [Simplifying/ scaling community self printing MP t-shirt #792](https://github.com/eclipse/microprofile-marketing/issues/792)

---- 

Awaiting informal community vote resolution summary.

**Comment by croundy** [comment]
From an Eclipse Foundation standpoint, we are good with the design.  This is approved with the understanding that the vote passed unanimously and that each member has received their own internal approvals. Thank you all!

**Comment by rstjames** [comment]
Thank you for the update on this topic @croundy . Could you please supply me with the correct eclipse foundation VECTOR logo that would be on the sleeve?

**Comment by croundy** [comment]
@rstjames sure, here is a png of the all white logo. I will email it to you as well. 

![EF_White](https://github.com/eclipse/microprofile-marketing/assets/72274403/0d569b81-bcd3-4871-baf1-bcd2c0bcec6f)

**Comment by rstjames** [comment]
@croundy thank you for the logo but do you have this white logo in SVG?

**Comment by croundy** [comment]
@rstjames here it is. Also sent to you via email.  
![EF_white](https://github.com/eclipse/microprofile-marketing/assets/72274403/eeebcc18-d31b-4314-8b15-a0a0e7dfc799)

**Comment by rstjames** [comment]
thank you! @croundy

**Comment by aeiras** [comment]
<img width="1228" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/9106973e-2586-465f-bec6-dd354ffe926d">

**Comment by pedanticdev** [comment]
Based on the consensus on the design and the granting of permission by the Eclipse Foundation, I believe the issue is resolved and as such this ticket can be closed.
