### ISSUE TITLE
[Blog Contribution] MicroProfile 6, Jakarta EE 10, and Java SE 20 support in Open Liberty 23.0.0.3 release

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#794]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7176&action=edit)**

 **Social Media Description**
 - [ ] MicroProfile 6.0 enables applications to use MicroProfile APIs with @JakartaEE Core Profile 10 and other updates, including the new MicroProfile Telemetry. @OpenLibertyIO 23.0.0.3 provides support for MicroProfile 6 as well as the Jakarta EE 10 profiles and Java SE 20.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by aeiras** [comment]
Happy April, Laura, @lauracowen 

Great blog, it belongs into 2 sections on MP.io :) 
https://microprofile.io/compatible/6-0/#

--
@rstjames, 
The blog has a design card, yet I don't think that design can be used for media posting. The blog belongs to MP 6.0, and Laura wrote the media description above.  Can you help with social media to close this ticket? Thank you!

**Comment by lauracowen** [comment]
Happy April all! :) Thanks

**Comment by rstjames** [comment]
I will post on SM about this blog this week. 

On the MP 6 compatible page it shows the 4 latest blog post for MP 6.o. This is not showing up because there are 4 new post. Please let me now what other changes

**Comment by rstjames** [comment]
Scheduled. 
![2023_microprofile_blog](https://github.com/eclipse/microprofile-marketing/assets/12132146/27b37395-2aa0-44e4-8e68-9093442975f7)

**Comment by lauracowen** [comment]
Nice graphic! :D
