### ISSUE TITLE
draft mock-ups of separate specification pages

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#795]
Need help to collect all required content for these pages. After we have a good example of what we would like, we can re create for each spec.

**Comment by Emily-Jiang** [comment]
One prototype @rstjames and I came up with for MicroProfile Config is [here](https://microprofile.io/microprofile-config/).

**Comment by Emily-Jiang** [comment]
@jclingan provided a feedback on today's live hangout: list the compatible implementations as well

**Comment by mpredli01** [comment]
Overall, I like the look-and-feel of the specification page. I do have a couple of minor suggestions:
[a] The font for denoting the class names, methods, etc. looks odd with it being italicized. A font such as Courier, Courier New or Consolas would be preferred and I believe is more "standard," as it were. Also, the contrast of light grey on white does not provide a good contrast.
[b] In the header under microprofile-config, I believe it would be less confusing if the text read "MicroProfile Config Specification" instead of "MicroProfile Configuration Feature."  I don't know if anyone else would feel the same.
[c] I am a +1 on adding the compatible implementations as John had suggested.

I would be interested in helping with getting these pages together.  I believe I have access when I posted a blog entry a couple of years ago.

Mike.

**Comment by aeiras** [comment]
In addition to listing in the page the compatible implementations as @jclingan nicely suggested, I recommend that blogs on the respective specifications get also added at the end of the page as we have under Compatible pages important feature. 

--
+ 1 to @mpredli01 on B standard name for all specifications.  Using the exact link to the git is fantastic + the microprofile-config to locate the git repo is excellent and applicable to introducing the pages for the specs. 

I further recommend:

1. adding the Community mailing list as a button - communication is key so we use Git and the community forum for work in addition to calls. 
2. add the calendar link as well as a button
3. moving as a button the How to Contribute link to the start of the page will create a total of 4 buttons: Git, Mailing list, Calendar, and How to contribute. That to me is the best way to introduce each spec page. 


Thank you, @rstjames and @Emily-Jiang for your work on this! :)

**Comment by aeiras** [comment]
@mpredli01 & @rstjames

MP website uses colors and fonts across. The information is found here:  https://microprofile.io/resources/branding/#color- FYI Mike.

**Comment by rstjames** [comment]
specification list home page
![screencapture-microprofile-io-2023-05-16-15_50_58](https://github.com/eclipse/microprofile-marketing/assets/12132146/72d20fef-b9cd-4003-9e78-ce4a32a81221)

Detail page
https://microprofile.io/microprofile-config/

**Comment by aeiras** [comment]
@rstjames, the landing page for the specifications is great @rstjames. 
Any progress in adjusting the test API with the suggestions sent above by MicroProfilers? 

Thank you and Emily for the dedicated time on this task. You two are amazing :)

**Comment by aeiras** [comment]
> specification list home page ![screencapture-microprofile-io-2023-05-16-15_50_58](https://user-images.githubusercontent.com/12132146/239280115-72d20fef-b9cd-4003-9e78-ce4a32a81221.png)
> 
> Detail page https://microprofile.io/microprofile-config/

feedback on naming each API. It ought to use the formal name of each specification. Even MP 5.0 uses the specs short names.  https://microprofile.io/compatible/5-0/

I will help with long names as done with the social media calls for each Spec when working on that later. FYI.   

Ideally, the landing page for each API uses the git repo name as currently done for the test API page, etc.

**Comment by Emily-Jiang** [comment]
@rstjames Thanks for the mockup! please update Open Telemetry to Telemetry in the above landing page.

**Comment by rstjames** [comment]
Specifications landing page has been updated. 

Other comments not implemented: (and my thoughts)

**specifications home page:** 
- adding the Community mailing list as a button - communication is key so we use Git and the community forum for work in addition to calls. 
- add the calendar link as well as a button
- moving as a button the How to Contribute link to the start of the page will create a total of 4 buttons: Git, Mailing list, Calendar, and How to contribute. That to me is the best way to introduce each spec page.

We have these links and buttons all over the site. They can be found and I think these pages should be left for technical info/ guidance. 4 buttons its way too much. 

![screencapture-microprofile-io-2023-06-13-18_17_36](https://github.com/eclipse/microprofile-marketing/assets/12132146/a050e4d2-20b0-4749-90bd-97d1fcf89cb9)


**specifcations detail page** (not implemented yet) 
Code snippets will be courier font.  (agree) 

[b] In the header under microprofile-config, I believe it would be less confusing if the text read "MicroProfile Config Specification" instead of "MicroProfile Configuration Feature." (ok with this... )

[c] I am a +1 on adding the compatible implementations as John had suggested. (not sure what this means)

**Comment by rstjames** [comment]
Update on Specification detail page @Emily-Jiang 
- code snippets fixed and spacing
- 
![screencapture-microprofile-io-microprofile-config-2023-06-29-15_12_34](https://github.com/eclipse/microprofile-marketing/assets/12132146/1781d001-2005-48de-88a0-a160ae90c4b2)

**Comment by aeiras** [comment]
Thank you, @rstjames and @Emily-Jiang, for your work on creating this draft to enable MicroProfilers' feedback :) 

**feedback as follows** 
using: https://microprofile.io/microprofile-config/


- Use the full-formal name of the API under the title introducing the page: Welcome to MicroProfile Configuration and mirror it as it was done under the usage of the Repo API name and below the full formal name. 
- The first paragraph introducing the API ought to be about the API's value for a developer. What problem does the API solve?   For example, I wrote this for social media MP JSON Web Token, which is written for Config social media push. https://twitter.com/MicroProfileIO/status/1654169280861159424?s=20
- Add the MP calendar link: "Join MP Config Calls." 
- Add the blog feature that brings all API content on Config WordPress Categories to the API page as it is done for the Compatible pages
- Let's add a banner that lists the following:
1) lines of code
2) number of contributors with a + 
3) numbers of commits

- Add an API documentation section. Already all API's have Spanish video tutorials + (this section will play nicely when written tutorials exist for all APsI: **Learn more about MP Configuration**  suffices as the title of the section 

-  TCK is or should be a super important detail for all API pages.  I recommend listing on the page: 
https://github.com/eclipse/microprofile-config/tree/master/tck

---

**Comment by aeiras** [comment]
@rstjames, do you have an update on this? 
The deadline to submit feedback was July 16th. https://groups.google.com/g/microprofile/c/Z4JocNME0v4

Let's go ahead and implement the suggested changes, enabling a quick overview before duplication. The idea is to initiate the API's page duplication by mid-next week. Starting July 24th, after the MP marketing call on Monday. 

Thank you for refocusing on this task.

**Comment by rstjames** [comment]
@Emily-Jiang I am not sure what content specification we want on each page and where to find it all. Can we have a quick call to clear it up?  

Example: should it be all this text on this page? 
https://download.eclipse.org/microprofile/microprofile-telemetry-1.0/tracing/microprofile-telemetry-tracing-spec-1.0.html

**Comment by aeiras** [comment]
Hola @rstjames and @Emily-Jiang, 
 
I see a new calendar event for this conversation. Kudos!  I will provide my feedback on this ticket. 

1. Every API needs to have its own ticket to mirror/host structural content similar to that found on the Config page. Doing so will also allow for corrections, etc that might be found on each page. 
2. The landing Specifications Page replaces the current project page in MP https://microprofile.io/projects/.  @rstjames, what is your recommendation for the layout of the API content? 

Cheers

**Comment by Emily-Jiang** [comment]
@rstjames  here are the stanadone repo links:
OpenTracing https://github.com/eclipse/microprofile-opentracing/
Context Propagation: https://github.com/eclipse/microprofile-context-propagation/
Reactive Messaging: https://github.com/eclipse/microprofile-reactive-messaging
Reactive Streams Operators:
https://github.com/eclipse/microprofile-reactive-streams-operators
LRA: https://github.com/eclipse/microprofile-lra
GraphlQL: https://github.com/eclipse/microprofile-graphql

There is no javadoc for MP Telemetry as it does not create APIs.

**Comment by rstjames** [comment]
**All pages that have been update/ made:**
https://microprofile.io/specifications/
https://microprofile.io/specifications/microprofile-telemetry/
https://microprofile.io/specifications/microprofile-open-api/
https://microprofile.io/specifications/microprofile-rest-client/
https://microprofile.io/specifications/microprofile-config/
https://microprofile.io/specifications/microprofile-fault-tolerance/
https://microprofile.io/specifications/microprofile-metrics/
https://microprofile.io/specifications/microprofile-jwt-auth/
https://microprofile.io/specifications/microprofile-health/
https://microprofile.io/specifications/microprofile-lra/
https://microprofile.io/specifications/microprofile-reactive-messaging/
https://microprofile.io/specifications/microprofile-graphql/
https://microprofile.io/specifications/microprofile-reactive-streams-operators/

**Comment by aeiras** [comment]
**Closing this and fellow related tickets**  
Based on July 26th MP Community call, the current draft pages do not fit the scalability & maintenance needed. 

 [Individual component specification pages (see Jakarta specification pages for reference) #145]( https://github.com/microprofile/microprofile-wg/issues/145)

David's explanation on the community call follows:

- [MPWG git comment](url) comments 7/26/23 re-focus the work https://github.com/microprofile/microprofile-wg/issues/145#issuecomment-1650470090

- follow up on the MP community forum thread  [Spec pages content alignment issue (discuss on MP Community call)](https://groups.google.com/g/microprofile/c/giNhrGTiKoA)
- https://groups.google.com/g/microprofile/c/giNhrGTiKoA/m/OWKXGSmOAAAJ
- https://groups.google.com/g/microprofile/c/giNhrGTiKoA/m/uHt0lVqhAAAJ

---

Thank you @rstjames and @Emily-Jiang for your work on this.

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
