### ISSUE TITLE
[Website] Analytics for MP.com + cookie banner. 

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#796]
Check access to analytics and connect cookie banner to the site for GDPR.

**Comment by Dexmaster** [comment]
![image](https://github.com/eclipse/microprofile-marketing/assets/6061000/adeb904b-430f-4432-b409-a8b5e35f4205)
Added basic cookie banner (with Cookie Policy page) for future use, disabled for now.

Cookie Policy page still will need Website Info to allow Users contact.
![image](https://github.com/eclipse/microprofile-marketing/assets/6061000/6c97c2d7-eb2c-4621-ab0c-ef16b4c62b9d)

**Comment by rstjames** [comment]
@aeiras do you know the answers to Andrii's questions above?

**Comment by aeiras** [comment]
@Dexmaster Andrii and @rstjames, Thank you for prioritizing this task! 

MPWG is a project under the EF. As such, any trademark/website questions are as follows: 

- Owner: Eclipse Foundation AISBL 

- Address: 
 Rond Point Schuman 11, Brussels 1040 Belgium
https://www.eclipse.org/legal/privacy.php
https://www.eclipse.org/legal/logo_guidelines.php 

- Country: Belgium

- Email: privacy@eclipse.org

- Phone: [+32 2 274 48 00](tel:+3222744800)

**Comment by Dexmaster** [comment]
Thank you, @aeiras updated the website data for the cookie policy page. The banner and cookie policy page are finished but disabled until needed.

**Comment by aeiras** [comment]
Excellent work, Andrii and Ryan. Thank you!

**Comment by aeiras** [comment]
Updated during the marketing call today. Closing this ticket.
