### ISSUE TITLE
Compatibility pages - list the releases of a particular products

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#797]
In the [compatibility website](https://microprofile.io/compatible/5-0/#overview), it becomes very crowded when a runtime has many certified versions listed. Do we want to keep the current style to list all of the releases or just list the latest release and then add a link to the previous release version?

**Comment by m-reza-rahman** [comment]
This is a trickly one. I think it's best to list the oldest and newest actually certified versions. Alternatively, just keep it as-is.

**Comment by rstjames** [comment]
The compatible products all have been updated with versions
