### ISSUE TITLE
[Blog Contribution] Tracing your microservices made easy with MicroProfile Telemetry 1.0

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#799]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7184&action=edit)**

 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
 - [ ]  [Yasmin Aumeeruddy](https://github.com/yasmin-aumeeruddy) introduces MicroProfile Telemetry (and OpenTelemetry) with a short demo.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by rstjames** [comment]
@lauracowen Could you please write a tweet for this blog post and I will push it on MP SM

**Comment by lauracowen** [comment]
@rstjames There's one in the original comment - it's just more concise than usual :) 

> [Yasmin Aumeeruddy](https://github.com/yasmin-aumeeruddy) introduces MicroProfile Telemetry (and OpenTelemetry) with a short demo.

**Comment by rstjames** [comment]
it is live and will be pushed on SM
![microprofile_blog_tracing_microservices](https://github.com/eclipse/microprofile-marketing/assets/12132146/c89a58e7-79bf-45bf-93a7-2c201a217237)
