### ISSUE TITLE
Source of Truth: Deprecate original https://github.com/microprofile/ github organization

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#8]
Before MP was moved to the Eclipse Foundation, original [repo](https://github.com/microprofile)

On Jan 2017, MP was moved under the EF umbrella, [formal repo](https://github.com/eclipse/microprofile) under the foundation umbrella.

**Comment by OndroMih** [comment]
I checked all repos, they are indeed deprecated and unused. I don't have permissions to modify the repos or add a description about deprecation so somebody else has to do it.

**Comment by aeiras** [comment]
@OndroMih i also don't have permissions to delete/archive. 

Triber @cesarhernandezgt is helping triple check that all can be archived.

**Comment by cesarhernandezgt** [comment]
> I checked all repos, they are indeed deprecated and unused. I don't have permissions to modify the repos or add a description about deprecation so somebody else has to do it.

Hi @OndroMih , not all the repos are unused. The following is my review abot all the repos from the https://github.com/microprofile/ organization.

- microprofile-site: It contains the backed that provides the data to current microprofile.io production data. Check for reference https://github.com/microprofile/microprofile-site#wp-engine
- wpsite: I created https://github.com/eclipse/microprofile-marketing/issues/30
- microprofile-site-config: it's used by https://github.com/microprofile/microprofile-site. Check for reference https://github.com/microprofile/microprofile-site#wp-engine
- microprofile-blog: I opened https://github.com/eclipse/microprofile-marketing/issues/31, but needs confirmation from Ryan.
- microprofile-presentations https://github.com/eclipse/microprofile-marketing/issues/11
- microprofile-bom https://github.com/eclipse/microprofile-marketing/issues/10
- microprofile-contributor-list https://github.com/eclipse/microprofile-marketing/issues/9

**Comment by cesarhernandezgt** [comment]
@aeiras  I suggest to change the tittle of this issue to: 
"Source of Truth: Deprecate original https://github.com/microprofile/ github organization "
The organization has 1 or more repos.

**Comment by aeiras** [comment]
done @cesarhernandezgt :)

**Comment by aeiras** [comment]
@dblevins this ticket is closed. :)
