### ISSUE TITLE
Please review blog post - Database Enabled Microservices with Tomee and MicroProfile

### ISSUE THREAD

**Issue by davidsalter** [microprofile/microprofile-marketing#80]
https://microprofile.io/?p=6219&preview=true

**Comment by aeiras** [comment]
@davidsalter your TomEE/MicroProfile crosspost blog is published. 👍 

On future video or blog/ code content contribution, please keep in mind by log-in back in to wordpress to see the adjustments:

- all links to re-address content must be clickable

- your blog gives the reader the exact time invested/required for content consumption, do state that on the description. 

- if possible, add your pic to your MP wordpress profile. 

**Please own closing this ticket and thanks for being awesome David.** 

#writingTHEtalk done formidably well, justfun!
