### ISSUE TITLE
[Translation] Release MicroProfile 6.0 - Release Blog Post Swedish Translation

### ISSUE THREAD

**Issue by LuisGalazM** [microprofile/microprofile-marketing#800]
Once third task in https://github.com/eclipse/microprofile-marketing/issues/726 about: Draft a release announcement blog post using template (technical person) is complete, add release blog post in Swedish

**Comment by emecas** [comment]
https://drive.google.com/drive/folders/1bPNVnkyXp8tu6Y-Q67o48BM4GPk5z6JL

**Comment by aeiras** [comment]
Hola @LuisGalazM, 

Thank you for choosing to become a contributor on Release transactions, you are amazing! 

@emecas leads the effort, so you are now in great hands.  :) 

Please check your inbox. You are now formally a MP Wordpress contributor. 
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/10731224/235535356-051fb7ef-78b2-4044-96c5-1c2d300d4794.png">

**Comment by LuisGalazM** [comment]
Presentation:
[https://docs.google.com/presentation/d/1lziLHhuvxj_6tGybZnN7KIWskbM1VQPe/edit](url)

Blog post:
[https://docs.google.com/document/d/1-bpHuQC3aNqQNKwSOqhTXWhPIeGfJPtBnYaMp8HFkIQ/edit](url)

**Comment by LuisGalazM** [comment]
Twitter:

#MicroProfileReleaseAnnouncement:  #Microprofile version 6.0 har släppts!
Den stöder @JakartaEE 10 Core Profile. 📢 🚀

För mer information gå in på:

#ByCommunityForCommunity #OpenSource

**Comment by LuisGalazM** [comment]
Picture:

MicroProfile version 6.0 har släppts!

**Comment by LuisGalazM** [comment]
@emecas @aeiras  el draft listo para un review

**Comment by aeiras** [comment]
Hola Luis, 

I will review it by the end of my day tomorrow before shifting the last steps to @rstjames  :)

 You truly are awesome!

**Comment by emecas** [comment]
**Fixing broken links:**

> Presentation: [https://docs.google.com/presentation/d/1lziLHhuvxj_6tGybZnN7KIWskbM1VQPe/edit](url)

https://docs.google.com/presentation/d/1lziLHhuvxj_6tGybZnN7KIWskbM1VQPe/edit
> 
> Blog post: [https://docs.google.com/document/d/1-bpHuQC3aNqQNKwSOqhTXWhPIeGfJPtBnYaMp8HFkIQ/edit](url)

https://docs.google.com/document/d/1-bpHuQC3aNqQNKwSOqhTXWhPIeGfJPtBnYaMp8HFkIQ/edit

**Draft Post:**

[https://microprofile.io/2023/05/06/microprofile-6-0…-10-core-profile/](https://microprofile.io/?p=7190&preview=true)

**Comment by aeiras** [comment]
nice work, Emerson. 
You are most welcomed to pull me in for final review. :) No rush while working with Luis on the review. 

Even better, I will just join to add Ryan to the last step and let all the work be lead by amazing you, Emerson! 🥇

**Comment by emecas** [comment]
thanks @LuisGalazM  @aeiras -  I  just added some suggestions in the presentation document and blog post document

**Comment by LuisGalazM** [comment]
@emecas ,  I fixed the picture and the suggestions

**Comment by emecas** [comment]
> @emecas , I fixed the picture and the suggestions

@LuisGalazM  just one last thing , one of the titles in the picture (Uppdaterade) has a red underline:

![image](https://github.com/eclipse/microprofile-marketing/assets/849502/54402c94-3198-49d7-b18a-8d4ce8e92f6d)

**Comment by LuisGalazM** [comment]
@emecas. ahi lo arregle

**Comment by emecas** [comment]
> @emecas. ahi lo arregle

LGTM 
Thanks @LuisGalazM 

@aeiras  it is your turn  now :)

**Comment by aeiras** [comment]
The two of you are truly formidable. :) 

@rstjames can you please help close this ticket?  Pull @LuisGalazM & @emecas if there are issues with publication over media and the such. 

@emecas you can publish the blog as the next step. Only then, Ryan can take over :)

**Comment by emecas** [comment]
> @emecas you can publish the blog as the next step. Only then, Ryan can take over :)

DONE @aeiras  , it is now published https://microprofile.io/2023/05/11/microprofile-6-0-lanserades-och-anvander-sig-av-jakarta-ee-10-core-profile/ , thanks for you contributions @LuisGalazM 

BTW I am following the effort [here](https://github.com/microprofile/microprofile-wg/issues/151#issuecomment-1424518369) as well

**Comment by rstjames** [comment]
@aeiras @LuisGalazM 
we need this tweet in Swedish and the text in Swedish for the image, after I can post it on social. 

#MicroProfileReleaseAnnouncement: #Microprofile 6.0 is released! It adopts
@JakartaEE 10 Core Profile. Learn more http://ow.ly/u6As50MmsZR #ByCommunityForCommunity #OpenSource

![image](https://github.com/eclipse/microprofile-marketing/assets/12132146/a9c1f37d-6ae0-4ca1-b764-6973a321b742)

**Comment by LuisGalazM** [comment]
@rstjames 

Twitter:

#MicroProfileReleaseAnnouncement: #Microprofile version 6.0 har släppts!
Den stöder @jakartaee Core Profile. 📢 🚀

För mer information gå in på: http://ow.ly/u6As50MmsZR 
#ByCommunityForCommunity #OpenSource

**Comment by LuisGalazM** [comment]
@rstjames 
Picture (This is the word order in Swedish): 

Microprofile 6.0
tillgänglig nu

**Comment by rstjames** [comment]
scheduled to go out :) @LuisGalazM 

![microprofile_release_6_swedish](https://github.com/eclipse/microprofile-marketing/assets/12132146/4e80e5c1-9ea3-47f4-9293-9e03e0bca55b)
