### ISSUE TITLE
[Blog Contribution] Rethinking microservices

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#801]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7202&action=edit)**

 **Social Media Description**
 - [ ]  @emilyfhjiang mounts a defence of appropriately designed and well-thought-out microservices, relating some history and myths, and providing guidance on best practices for the future.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by rstjames** [comment]
@lauracowen what is the status on this ticket? @Emily-Jiang

**Comment by rstjames** [comment]
Blog is live and scheduled to go out on Friday on social media
