### ISSUE TITLE
[Compatible Implementations Announcement] MP 4.1 - WildFly 26.1.3.Final

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#802]
**Organization Name**
Name: [Red Hat](https://www.redhat.com/en)
 
 **Product Version and download URL**
URL: [WildFly 26.1.3.Final](https://github.com/wildfly/wildfly/releases/download/26.1.3.Final/wildfly-26.1.3.Final.zip)
 
 **Java runtime used to run the implementation**
[TCK results](https://github.com/wildfly/certifications/blob/MP4.1/WildFly_26.1.3.Final/microprofile-4.1-full-certification.adoc) - JDK 8, 11, 17

 **Media Description**
Just mention please @WildFlyAS on Twitter.

 **Design Card**  (for MicroProfile designer)

 **Notes**

- CCR - https://github.com/eclipse/microprofile/issues/334

**Comment by rstjames** [comment]
website updated 

![microprofile_4 1_wildfly](https://github.com/eclipse/microprofile-marketing/assets/12132146/f15ede1c-dbb9-4cff-b23c-9337399cbc21)

@aeiras @xstefank Please confirm the tweet is ok

#MicroProfileCompatible Implementation Announcement: We are happy to announce that @WildFlyAS 26.1.3. is now compatible with #MicroProfile 4.1

Learn more about MicroProfile in #WildFly at https://microprofile.io/compatible/4-1/

#opensource

**Comment by rstjames** [comment]
scheduled
