### ISSUE TITLE
[Compatible Implementations Announcement] MP 5.0 - WildFly 27.0.0.Final

### ISSUE THREAD

**Issue by xstefank** [microprofile/microprofile-marketing#803]
**Organization Name**
Name: [Red Hat](https://www.redhat.com/en)
 
 **Product Version and download URL**
URL: [WildFly 27.0.0.Final](https://github.com/wildfly/wildfly/releases/download/27.0.0.Final/wildfly-27.0.0.Final.zip)
 
 **Java runtime used to run the implementation**
[TCK results](https://github.com/wildfly/certifications/blob/MP5.0/WildFly_27.0.0.Final/microprofile-5.0/microprofile-5.0-full-certification.adoc) - JDK 11, 17

 **Media Description**
Just mention please @WildFlyAS on Twitter.

 **Design Card**  (for MicroProfile designer)

 **Notes**

- CCR - https://github.com/eclipse/microprofile/issues/333

**Comment by rstjames** [comment]
#MicroProfileCompatible Implementation Announcement: We are happy to announce that  @WildFlyAS 27.0.0.Final is now compatible with #MicroProfile 5.0. 

Learn more about MicroProfile in #WildFly at https://microprofile.io/compatible/5-0
#opensource 

![microprofile_compatible_5 0-wildfly](https://github.com/eclipse/microprofile-marketing/assets/12132146/8594ca0d-2a31-49a3-a12f-750895a72670)

**Comment by rstjames** [comment]
scheduled
