### ISSUE TITLE
[Social Media - Infra Update] HootSuite 2023 Renewal

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#805]
The renewal status of MPWG Hootsuite media access via Tomitribe coverage has been sent to MP Media volunteers. This issue exists for OSS transparency. 

<img width="714" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/0aea0b41-809d-4e09-9c7b-0bf7b482c319">

**Comment by rstjames** [comment]
@aeiras we should close this right?

**Comment by aeiras** [comment]
yes.

**Comment by rstjames** [comment]
All is ok and working
