### ISSUE TITLE
Onbaord Luqman Saeed to run June/July Meetings

### ISSUE THREAD

**Issue by pedanticdev** [microprofile/microprofile-marketing#806]
As stated and dsicussed in the meetings of June 12 and 16th of June, 2023, I, Luqman Saeed will chair the marketing meetings for June and July. This is is to officially request to be taken through the induction process.

**Comment by aeiras** [comment]
> As stated and dsicussed in the meetings of June 12 and 16th of June, 2023, I, Luqman Saeed will chair the marketing meetings for June and July. This is is to officially request to be taken through the induction process.

Hola Luqman, @pedanticdev,

Thank you for enabling tracing onboarding. 
I will use individual git comments for each task to help you with helpful Q&A via those comments if anything is unclear, please ask.

**Comment by aeiras** [comment]
MP Community Google Drive - Edit access - **granted**

https://microprofile.io/workinggroup/#mptab-knowledge  You have been added under The Infrastructure Admins [Inventory](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=2015643674) lists and shows the MicroProfile core believe By Community For Community! The sheet contains individual volunteers across the ecosystem, who are trusted to uphold the keys to MicroProfile infra.

**Comment by aeiras** [comment]
MP WordPress Edit access - **Granted**

<img width="1168" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/0d2716e2-4df8-4245-b1a5-a7f89ee18581">

tracked[ here](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1028975568)

---
If you wish to test your access, you are most welcome to check how to use your EDIT access at https://microprofile.io/blog/  click Become a MicroProfile Author and help with MicroProfile content contribution processing by reviewing, posting, etc., our community content.     Current content contributions awaiting review are: https://github.com/eclipse/microprofile-marketing/issues/804 & https://github.com/eclipse/microprofile-marketing/issues/801

----
Note: As a WordPress editor, you should not publish your own/Payara content. 
When you contribute MP content via original content- publish directly via the website or crossposting, that content requires per-review by others outside your organization.

**Comment by aeiras** [comment]
MPWG mailing lists subscriptions -  **Bare minimum recommendations** - https://microprofile.io/workinggroup/#mptab-email-forums

MP has a few mailing lists, and 3 of them are required for marketing stewards: 

- [Community forum](https://groups.google.com/g/microprofile)
- [Marketing Forum](https://groups.google.com/g/microprofile-marketing)
- [Working Group]( https://accounts.eclipse.org/mailing-list/microprofile-wg)

**Comment by aeiras** [comment]
MicroProfile GitHub Triage Contributors - **Added**

https://projects.eclipse.org/projects/technology.microprofile/who

<img width="890" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/2b21edbc-798e-49e0-898d-8c6afce5e37a">

MP Triage Contributors' [documentation ](https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access)

--- 

On the fun side, I recommend you add a picture to your github if you wish. :)

**Comment by aeiras** [comment]
Zoom access - Granted by previews Marketing Steward via private.  The Zoom tab [tracking ](https://docs.google.com/spreadsheets/d/1bN00rsPpw54CnCjNHHdrty0bvSA5vi1ei7TDXSOf89o/edit#gid=1206744069)has been updated to include your access. 

-  [MP Zoom  ](https://github.com/microprofile/microprofile-wg/wiki/MicroProfile-Zoom-Admin)

**Comment by aeiras** [comment]
Based on the Stewards' monthly responsibilities listed [Mktg Call Steward Onboarding & Call Steward Responsibilities Work in progress by MicroProfilers](https://github.com/microprofile/microprofile-wg/wiki/Mktg-Call-Steward-Onboarding-&-Call-Steward-Responsibilities------Work-in-progress-by-MicroProfilers)

It is helpful to review and, when possible, to create documentation that will enable future Stewards to own the job you are choosing to own today, Luqman. :) Becoming scalable while contributing to MicroProfiler is the best form of volunteering & utilizing your time. :) 

1. [Marketing Repository- WIKI](https://github.com/eclipse/microprofile-marketing/wiki)
2. [Working Group Repository - Wiki](https://github.com/microprofile/microprofile-wg/wiki)

**Comment by pedanticdev** [comment]
This ticket can be closed as the necessary tasks of onboarding are done.
