### ISSUE TITLE
[Social Media] MicroProfile sponsorship on EclipseCon 2023 Java Community Day on 16th October

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#807]
Here is the tweet we should do to promote EclipseCon 2023 Java Community Day on 16th October

We are so thrilled to sponsor EclipseCon 2023 Java Community Day on 16th October together with @JakartaEE @adoptium organized by @iJUGeV to showcase Java! Please make effort to attend this event, which is going to be awesome! 
https://www.eclipsecon.org/2023/java-community-day

**Comment by Emily-Jiang** [comment]
cc @aeiras @rstjames I could not tag Dmitry but I notified him via twitter DM.

**Comment by dalexandrov** [comment]
Looks great!

**Comment by Emily-Jiang** [comment]
@rstjames please can you schedule a weekly tweet message to do the promotion?

**Comment by rstjames** [comment]
scheduled to go out twice 
![2023_microprofile_eclipsecon_sponsor](https://github.com/eclipse/microprofile-marketing/assets/12132146/96065905-8179-417e-ba6c-f98dfa58b42f)
