### ISSUE TITLE
[Quote Submission] Hunan AsiaInfo Anhui

### ISSUE THREAD

**Issue by AsiainfoAnhui** [microprofile/microprofile-marketing#808]
**[Quote Submissions Guidelines: MicroProfiler Testimonials](https://github.com/eclipse/microprofile-marketing/wiki/Quote-Submissions-Guidelines:-MicroProfiler-Testimonials)**

**Quote answers**
*60 word max*
Why are you investing the time and resources into the MicroProfile ecosystem?
We are trying to find a cloud development framework that can meet the requirements of business and technology separation in China to make business development easier, and MicroProfile is exactly what we are looking for.
Why do you think others should contribute to MicroProfile?
We understand the needs of business developers and can help MicroProfile grow in China. I'm happy to be a part of the team.
 **Design Card**  (for MicroProfile designer)

 **Notes**
 To help with everything

**Comment by Emily-Jiang** [comment]
@aeiras @rstjames please review to see whether you have any comments.

**Comment by AsiainfoAnhui** [comment]
dear all
I can't create a new folder for uploading logo in https://drive.google.com/drive/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk

**Comment by aeiras** [comment]
> dear all
> I can't create a new folder for uploading the logo in https://drive.google.com/drive/folders/1T8-qm8q0vb-94g4J2JifCEkM8FlaV0Hk

Welcome to MPWG @AsiainfoAnhui!  

Can you please provide an individual email so that you can gain access to the google drive? In the mean time, please share your logo via this ticket.

**Comment by aeiras** [comment]
> **[Quote Submissions Guidelines: MicroProfiler Testimonials](https://github.com/eclipse/microprofile-marketing/wiki/Quote-Submissions-Guidelines:-MicroProfiler-Testimonials)**
> 
> **Quote answers** _60 word max_ Why are you investing the time and resources into the MicroProfile ecosystem? We are trying to find a cloud development framework that can meet the requirements of business and technology separation in China to make business development easier, and MicroProfile is exactly what we are looking for. Why do you think others should contribute to MicroProfile? We understand the needs of business developers and can help MicroProfile grow in China. I'm happy to be a part of the team. **Design Card** (for MicroProfile designer)
> 
> **Notes** To help with everything

Your Members' quote is great. I have reviewed it and added, via suggested mode, a few improvements.  You don't need to accept my recommendations. Your quote can be shared in the website and via MP media as you shared it.  
Thank you for taking the time to review the quote using the google document where you can approve or decline improvements copied also below: https://docs.google.com/document/d/1lU9NKqA4XlxQ1SjHBvmFI_8KUqoZVYxbJC9BvwWajGU/edit

**Revised to** 
_Hunan AsiaInfo Anhui is looking for a cloud development framework that can meet the requirements of business and technology separation in China.  MicroProfile makes business development easier; it is precisely what we are looking for.  We understand the needs of business developers and wish to help MicroProfile grow in China. We are happy to be a part of the MicroProfile Working Group._

**Comment by aeiras** [comment]
@AsiainfoAnhui, 

While working on your members' quote, can you also provide the 2 Assigned MicroProfilers who are a part of the Steering committee?  
The MPWG page provides the Steering Committee names and preferred social media if any social media is used: Please see the link for reference. https://microprofile.io/workinggroup/#mptab-members

**Comment by AsiainfoAnhui** [comment]
The quote is great。

My google account is peakwong737@gmail.com

Representative: Peak Wong ， github account： wangfeng2@asiainfo.com
Alternate: ZhangZhenDe，github account: zhangzhende

thanks aeiras

**Comment by aeiras** [comment]
> The quote is great。
> 
> My google account is [peakwong737@gmail.com](mailto:peakwong737@gmail.com)
> 
> Representative: Peak Wong ， github account： [wangfeng2@asiainfo.com](mailto:wangfeng2@asiainfo.com) Alternate: ZhangZhenDe，github account: zhangzhende
> 
> thanks aeiras

You are amazing, Peak :)

First, on google folder MPWG access: 
Thank you for confirming you received EDIT access to the MPWG folder by creating the Hunan AsiaInfo Anhui's folder and adding your company logos.
#808 .  https://drive.google.com/drive/u/0/folders/1z2tIF_qbfPAmfdIK0Dz06nuNYwRNL9CJ

**Comment by aeiras** [comment]
> The quote is great。
> 
> My google account is [peakwong737@gmail.com](mailto:peakwong737@gmail.com)
> 
> Representative: Peak Wong ， github account： [wangfeng2@asiainfo.com](mailto:wangfeng2@asiainfo.com) Alternate: ZhangZhenDe，github account: zhangzhende
> 
> thanks aeiras

Second: MPWG Steering Commitee representatives: 

Only you Peak is currently listed in the EMO (Eclipse Foundation Organization) spreadsheet that tracks membership information.  I recommend you contact the EMO either via the [MicroProfile Working Group Eclipse mailing list](https://accounts.eclipse.org/mailing-list/microprofile-wg) https://microprofile.io/workinggroup/#mptab-email-forums or privately and submit an update to add Zhang Zhen De as an alternate. The website can only be updated once the EMO sheet is updated, as the document is the formal document that tracks the MicroProfile representatives. I hope this is helpful. 

 https://docs.google.com/spreadsheets/d/1QflmI_5NWLEGDGImibvMx5iSFUZisbnHjMvvOIcLRy0/edit#gid=346790645

--- 
Lastly 

Can you provide the social links of your and Zhang's git accounts instead of emails used for Github?

**Comment by aeiras** [comment]
> The quote is great。
> 
> My google account is [peakwong737@gmail.com](mailto:peakwong737@gmail.com)
> 
> Representative: Peak Wong ， github account： [wangfeng2@asiainfo.com](mailto:wangfeng2@asiainfo.com) Alternate: ZhangZhenDe，github account: zhangzhende
> 
> thanks aeiras

Third and most fun: Quote review completed:

Approved quotes spreadsheet[ inventory](https://docs.google.com/spreadsheets/d/14iCNpzj7BpvntOKG3u2ooEa-7LFceZTqk9OmqVqbDog/edit#gid=1123045040) now includes your company quote. And quote has been assigned to you on behalf of your employer. Please adjust the name in this ticket if you wish a different author to be added to the quote. Once we hear from you, the quote will be imported into  Testimonials https://microprofile.io/workinggroup/#testimonials using your company logo and the link as listed in the spreadsheet.

**Comment by AsiainfoAnhui** [comment]
Hi aeiras
I had uploaded logo to https://drive.google.com/drive/u/0/folders/1z2tIF_qbfPAmfdIK0Dz06nuNYwRNL9CJ
I had send a mail to microprofile-wg@eclipse.org to apply for adding an alternate in the EMO spreadsheet
The link of my github account is https://github.com/AsiainfoAnhui
The link of Zhang Zhen De github account is https://github.com/zhangzhende
Quotes is ok. 
Thank you for your help in the process

**Comment by rstjames** [comment]
@aeiras this is for me now?

**Comment by aeiras** [comment]
correct Ryan, thank you for your help onboarding AsianInfo Team 👍 

Tasks are:

1. add logo - already in the drive
2. add the corporate quote using the Excel-approved quotes spreadsheet information
3.  add Steering Committee members and social media to the members' tab. 

-- 4 task is updating the 2023 swag yet that needs a different ticket. I will follow up.

**Comment by aeiras** [comment]
> Hi aeiras
> I had uploaded logo to https://drive.google.com/drive/u/0/folders/1z2tIF_qbfPAmfdIK0Dz06nuNYwRNL9CJ
> I had send a mail to [microprofile-wg@eclipse.org](mailto:microprofile-wg@eclipse.org) to apply for adding an alternate in the EMO spreadsheet
> The link of my github account is https://github.com/AsiainfoAnhui
> The link of Zhang Zhen De github account is https://github.com/zhangzhende
> Quotes is ok.
> Thank you for your help in the process

It is our pleasure to help you and the AsianInfo Team! :)
This ticket will be closed by @rstjames with the 3 updates on https://microprofile.io/workinggroup/. 

---

There is 1 extra task (MPWG Swag 2023 design) that requires your attention, @AsiainfoAnhui. 

Can you please **submit a new git issue** and enable a Q&A to help you decide if your company desires to be added to the https://github.com/eclipse/microprofile-marketing/issues/791#issuecomment-1560061698 MP 2023 design? 

Relevant **history** via writing here https://github.com/eclipse/microprofile-marketing/issues/791#issuecomment-1571015685

You are the 12 members to join MPWG.  The 11 members already **voted + 1** to allow their company names to be added to the 2023 shirt and hoody.  https://github.com/eclipse/microprofile-marketing/issues/791#issuecomment-1608521060

Your company can choose to use the Swag design to self-print shirts and hoodies locally,  using the Swag drive designs, sizes, colours, etc. The design swag can also be printed using a portion of the 2023 marketing budget, as the project has done in the past. 

With a new git ticket, your company can accept or reject being added to the 2023 design.   MPWG cannot add you to the swag without your written consent.  MP is an Eclipse Foundation Trademark. As such, there must be tracing to protect the usage of companies and MP.   Such a ticket, should you have questions, can be used to clarify whatever is not clear. 

--- 
Again, thanks for choosing to contribute and introduce yourself via open mediums of communication. I appreciate it.  See your comments in the new ticket. Cheers!

**Comment by rstjames** [comment]
All has been updated. We have on bug on the WG logo sizing, but this will be solved today. 
- quote added
- logo added to home and wg page
- Organization- Representative- Alternate has been updated to the table on the WG page.

**Comment by aeiras** [comment]
Thanks Ryan!

**Comment by rstjames** [comment]
a welcome message will be sent out on social media and also promoting your quote. Thank you!
![2023_microprofile_asiainfo_quote](https://github.com/eclipse/microprofile-marketing/assets/12132146/621448b8-187a-414b-ac5f-569bd9ecec0b)
![2023_microprofile_new_wg_member_asiaInfo](https://github.com/eclipse/microprofile-marketing/assets/12132146/f6c22540-abe7-41c5-9ccc-6eecb2125679)

**Comment by aeiras** [comment]
@rstjames , 

Thank you for the update. 
The quote added is not the revised version of the quote as listed in the Excel document and in the website. 
can you please delete it from the media if already been shared and re-try with the correct quote?

**Comment by rstjames** [comment]
Fixed and updated on SM 
![2023_microprofile_asianInfo_quote](https://github.com/eclipse/microprofile-marketing/assets/12132146/317b865f-4446-4098-8d86-688e7cc57b43)

**Comment by rstjames** [comment]
The website was correct. @aeiras

**Comment by aeiras** [comment]
Great stuff!
