### ISSUE TITLE
A Compatible Implementation To be added to the Compatible page

### ISSUE THREAD

**Issue by dominikatasarz** [microprofile/microprofile-marketing#809]
**Product Name**
Payara Server Enterprise 6

 **Product Version and download URL**
 https://www.payara.fish/page/payara-enterprise-downloads/

 **Compatibile Implementation Request**
https://github.com/eclipse/microprofile/issues/323

**Comment by dominikatasarz** [comment]
I can't add a 'compatibility' label I'm afraid so can someone else add one please!

**Comment by rstjames** [comment]
@dominislawa I update the page. 
Is this download link correct? 
<img width="1113" alt="Screenshot 2023-07-19 at 16 51 04" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/c3d961b0-2e5d-4d15-aedf-88f4f0044a34">

And you can review this:
<img width="1314" alt="Screenshot 2023-07-19 at 16 57 17" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/7d41d4c0-cedd-44ca-b170-2df686ac2891">

**Comment by dominikatasarz** [comment]
@rstjames This was a link provided for certification request so it is now expired, the link to be listed on the compatibility page should be as above: https://www.payara.fish/page/payara-enterprise-downloads/

**Comment by rstjames** [comment]
updated

**Comment by dominikatasarz** [comment]
Thank you!
