### ISSUE TITLE
[Documentation ] Actionable steps for creation of official MP tutorial

### ISSUE THREAD

**Issue by pedanticdev** [microprofile/microprofile-marketing#811]
This ticket is to track the creation of official written MP tutorials. 

The first option, as suggested by David Blevins and accepted by the steering committee is to get people from the community that would this. The first step in this is getting the request for interest out.

**Comment by aeiras** [comment]
MicoProfile focum communications: 

-  [MicroProfile Tutorial Bid Proposal](https://groups.google.com/g/microprofile/c/7GWLcty0I5Y)

- [Fwd: VOTE: Funding MicroProfile Tutorial with 2023 Budget](https://groups.google.com/g/microprofile/c/WVJBUOVBm2I)
- [Funding MicroProfile Tutorial with 2023 Budget](https://groups.google.com/g/microprofile-marketing/c/MkZnAA2da5s)
- [MPWG Forum](https://www.eclipse.org/lists/microprofile-wg/msg02255.html)

**Comment by aeiras** [comment]
Tarun has a great ticket for the tutorial. Will close this ticket.
