### ISSUE TITLE
Standardize Spec Display

### ISSUE THREAD

**Issue by pedanticdev** [microprofile/microprofile-marketing#812]
As part of the implementation of #795 , @aeiras suggests the standardization of the display of all the MP specs to give a uniform display. In the meantime #795 can proceed while the issue of unifying the display of the specs can be handled separately, possibly via this ticket.

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296

Thank you @pedanticdev for bringing this topic to the community call! :)
