### ISSUE TITLE
Specifications overview page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#813]
https://microprofile.io/specifications/

![screencapture-microprofile-io-specifications-2023-07-25-14_54_02](https://github.com/eclipse/microprofile-marketing/assets/12132146/3f52d957-eca3-4536-b2d2-307f94be09d8)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
