### ISSUE TITLE
Specifications- microprofile telemetry page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#814]
https://microprofile.io/specifications/microprofile-telemetry/

![screencapture-microprofile-io-specifications-microprofile-telemetry-2023-07-25-15_06_35](https://github.com/eclipse/microprofile-marketing/assets/12132146/6cfea714-4b0f-423a-83de-b512fbcb90fc)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
