### ISSUE TITLE
Specifications- microprofile open ai page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#815]
https://microprofile.io/specifications/microprofile-open-api/

![screencapture-microprofile-io-specifications-microprofile-open-api-2023-07-25-15_08_30](https://github.com/eclipse/microprofile-marketing/assets/12132146/08fd357e-12cf-4da1-ac74-5cc36da8c520)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
