### ISSUE TITLE
specifications: microprofile-rest-client

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#816]
https://microprofile.io/specifications/microprofile-rest-client/

![screencapture-microprofile-io-specifications-microprofile-rest-client-2023-07-25-15_13_33](https://github.com/eclipse/microprofile-marketing/assets/12132146/7f460236-4c61-4aa4-81b8-d7c974524265)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
