### ISSUE TITLE
specifications microprofile-config page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#817]
https://microprofile.io/specifications/microprofile-config/
![screencapture-microprofile-io-specifications-microprofile-config-2023-07-25-15_14_29](https://github.com/eclipse/microprofile-marketing/assets/12132146/a9d4dc7c-4923-4346-aab1-c9c1ddcde22d)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
