### ISSUE TITLE
specifications: microprofile-fault-tolerance page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#818]
https://microprofile.io/specifications/microprofile-fault-tolerance/

![screencapture-microprofile-io-specifications-microprofile-fault-tolerance-2023-07-25-15_16_27](https://github.com/eclipse/microprofile-marketing/assets/12132146/3225c124-c147-4b19-92ba-02c84fa45ef1)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
