### ISSUE TITLE
specifications microprofile-metrics page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#819]
https://microprofile.io/specifications/microprofile-metrics/

![screencapture-microprofile-io-specifications-microprofile-metrics-2023-07-25-15_17_44](https://github.com/eclipse/microprofile-marketing/assets/12132146/3fa6e83d-6028-437b-9cf3-89b6e27a3597)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
