### ISSUE TITLE
nejug

### ISSUE THREAD

**Issue by bbenz** [microprofile/microprofile-marketing#82]
Name of the speaker: Brian Benz
Name of the session: Perfecting reliable code delivery for the cloud with MicroProfile and OpenTracing
twitter or/& git account, if available: @bbenz / bbenz
Link of the event or short session abstract: https://nejug.org/events/2019/05/microprofile-and-opentracing.html
Date/ time/location: Monday May 6, 6PM, Burlington, MA (Boston Suburbs)
Speaker must provide "Tweet message" (who better than the speaker to write this..):
Learn about reliable @java code delivery with @microprofileio and @opentracing at the next #nejug meetup, Monday May 6, 6PM at the @MSNewEngland offices (Burlington). https://nejug.org/events/2019/05/microprofile-and-opentracing.html

**Comment by rstjames** [comment]
@bbenz sorry this snuck by me. Maybe best to link me to the ticket next time. Can get tricky to keep track of all the requests.
