### ISSUE TITLE
specifications: microprofile-jwt-auth page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#820]
https://microprofile.io/specifications/microprofile-jwt-auth/

![screencapture-microprofile-io-specifications-microprofile-jwt-auth-2023-07-25-15_18_43](https://github.com/eclipse/microprofile-marketing/assets/12132146/aecc49ed-7fed-4a4e-837f-12193e8bbed6)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
