### ISSUE TITLE
specifications: microprofile-health page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#821]
https://microprofile.io/specifications/microprofile-health/
![screencapture-microprofile-io-specifications-microprofile-health-2023-07-25-15_19_40](https://github.com/eclipse/microprofile-marketing/assets/12132146/da4fe0e3-7f4d-413a-b5af-5149e51a5d2a)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
