### ISSUE TITLE
specifications: microprofile-opentracing page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#822]
https://microprofile.io/specifications/microprofile-opentracing/

![screencapture-microprofile-io-specifications-microprofile-opentracing-2023-07-25-15_21_38](https://github.com/eclipse/microprofile-marketing/assets/12132146/b6b7e21d-c168-4b0f-8831-a4be668f8455)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
