### ISSUE TITLE
specifications: microprofile-lra page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#823]
https://microprofile.io/specifications/microprofile-lra/

![screencapture-microprofile-io-specifications-microprofile-lra-2023-07-25-15_23_55](https://github.com/eclipse/microprofile-marketing/assets/12132146/cfa7c675-86ac-437c-b3fd-54b923344197)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
