### ISSUE TITLE
specifications: microprofile-reactive-messaging page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#824]
https://microprofile.io/specifications/microprofile-reactive-messaging/

![screencapture-microprofile-io-specifications-microprofile-reactive-messaging-2023-07-25-15_24_56](https://github.com/eclipse/microprofile-marketing/assets/12132146/53ee6c9d-2906-4d99-be8f-e264d9809784)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
