### ISSUE TITLE
specifications: microprofile-graphql page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#825]
https://microprofile.io/specifications/microprofile-graphql/

![screencapture-microprofile-io-specifications-microprofile-graphql-2023-07-25-15_26_28](https://github.com/eclipse/microprofile-marketing/assets/12132146/f4bcb6be-1b30-40a0-9ad2-465f7eb9682a)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
