### ISSUE TITLE
specifications: microprofile-reactive-streams-operators page

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#826]
https://microprofile.io/specifications/microprofile-reactive-streams-operators/
![screencapture-microprofile-io-specifications-microprofile-reactive-streams-operators-2023-07-25-15_27_34](https://github.com/eclipse/microprofile-marketing/assets/12132146/cdb65689-21dc-4779-97a0-38a2b4e24705)

**Comment by aeiras** [comment]
https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1654654296
