### ISSUE TITLE
[Swag 2023 Member Update] Hunan AsiaInfo Anhui

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#827]
Dear @AsiainfoAnhui, 

You are wonderful to submit an MPWG quote https://github.com/eclipse/microprofile-marketing/issues/808. 
One extra task that requires your attention (no rush) is integrating your company name into the 2023 Swag designs. 

Please check [[2023 - MP design Swag] Update designs to include new Members - Print Outside MPWG budget by Members #791](https://github.com/eclipse/microprofile-marketing/issues/791), specifically:

1. [MPWG members comments via the email forums](https://github.com/eclipse/microprofile-marketing/issues/791#issuecomment-1571015685)
2. MPWG 2023 vote https://github.com/eclipse/microprofile-marketing/issues/791#issuecomment-1608521060 

---

Via this ticket, your company can choose to vote to approve adding  Hunan AsiaInfo Anhui to the t-shirt and zip hoodies as shown here https://github.com/eclipse/microprofile-marketing/issues/791#issuecomment-1560061698. 

Questions are most welcome.

**Comment by AsiainfoAnhui** [comment]
Dear aeiras
We are very happy if our company name can be on t-shirt and zip hoodies. what can I do for it?

**Comment by aeiras** [comment]
Happy August @AsiainfoAnhui :) 

The 2023 swag vote results below are imported from the Google spreadsheet to the respective git ticket as well.

Using this ticket, you can approve Hunan AsiaInfo Anhui's name to be added to the current design as listed above in the design ticket. Example:  "**Hunan AsiaInfo Anhui approves adding its name in the 2023 MicroProfile swag**"— or similar wording.  This ticket suffices to update the t-shirt.

<img width="1012" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/2b85ff52-d55a-49e1-900d-3f18d8ade2ce">

**Comment by AsiainfoAnhui** [comment]
Happy August @aeiras 
Hunan AsiaInfo Anhui approves adding its name in the 2023 MicroProfile swag
:)

**Comment by aeiras** [comment]
> Happy August @aeiras
> Hunan AsiaInfo Anhui approves adding its name to the 2023 MicroProfile swag
> :)

You are wonderful @AsiainfoAnhui. It is excellent that MPWG 2023 swag will integrate you👍 

----

@rstjames,

Thank you in advance for helping us update the 2023 swag shirt with Hunan AsiaInfo Anhui's name. Please also remember to update the hoody, Triber.  https://github.com/eclipse/microprofile-marketing/issues/792#issuecomment-1615237930 The hoody is still missing from the drive. Could you please check the open swag ticket? 

Thank you,

**Comment by AsiainfoAnhui** [comment]
thanks all, we are very happy with you

**Comment by rstjames** [comment]
@aeiras @AsiainfoAnhui  is there a shorter version of the company name "Hunan AsiaInfo Anhui" is very long and difficult to fit on the shirt. Logo only says "AsiaInfo"

**Comment by rstjames** [comment]
Hi 
I am a bit confused we have "asiainfo" logo on the website, Can we use "asiainfo" for the name on shirts or must it be "Hunan AsiaInfo Anhui" ? 
The reason I am bring this up too is that "Hunan AsiaInfo Anhui"  is very long and hard to fit on the t-shirt. Also consistency on the site and shirts. 

@AsiainfoAnhui @aeiras

**Comment by AsiainfoAnhui** [comment]
Hi @rstjames 
It is ok, use "asiainfo" name on shirts. 
thanks

**Comment by rstjames** [comment]
Thank you @AsiainfoAnhui

**Comment by rstjames** [comment]
@AsiainfoAnhui your name has been added to the shirt and hoodie for MP 

<img width="917" alt="MP_shirt-Back" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/6b292836-a06f-44ec-b266-a6801c028187">
<img width="597" alt="mp-hoodie-back-2023" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/0bbbceef-1ee9-423d-9679-1902dbee0e20">

**Comment by AsiainfoAnhui** [comment]
Hi @rstjames 
It is very nice, They look very beautiful， How can we have the t-shirt and zip hoody? or do  we need to  print it ourselves?
thanks

**Comment by rstjames** [comment]
Hi @AsiainfoAnhui this is a good question. We right now are trying to find a scalable way for contributors to print/ order their own swag. In the near future I hope to use a website similiar to https://teespring.com/ . This would allow people to choose what swag they want, have it print, and shipped to them at "cost". No profits from the sale just the cost to print and shipping. 

But for now I can offer you the source files for the hoodie, shirt and stickers. They can be found here: https://microprofile.io/resources/#swag

**Comment by AsiainfoAnhui** [comment]
Hi @rstjames , I got it , thans
:)
