### ISSUE TITLE
[Website Improvements]  Individual component specification pages (see Jakarta specification pages for reference) MPWG repo #145

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#828]
Features and background on task:

- MPWG repo issue [Individual component specification pages (see Jakarta specification pages for reference) #145](https://github.com/microprofile/microprofile-wg/issues/145)
- David's specific comments and description on requirements: https://github.com/microprofile/microprofile-wg/issues/145#issuecomment-1650470090
- related to git ticket  [[draft mock-ups of separate specification pages](https://github.com/eclipse/microprofile-marketing/issues/new#top)
#795](https://github.com/eclipse/microprofile-marketing/issues/795)
and closed tickets https://github.com/eclipse/microprofile-marketing/issues/795#issuecomment-1649782637

**Comment by aeiras** [comment]
@rstjames, 

As discussed, previews work on this task is dropped and refocused. David has been added to the ticket. Should you have any questions, he is your task support. :)

**Comment by rstjames** [comment]
@dblevins is this what you were thinking? 
![screencapture-microprofile-io-2023-07-28-12_04_58](https://github.com/eclipse/microprofile-marketing/assets/12132146/b42e2b6f-f579-441a-b469-4a006cf89653)

**Comment by dblevins** [comment]
Items to add:

 - TCK Link
 - Status of the spec (under development, final)
 - Maven coordinates
 - Compatible Implementations

For the demo the Maven coordinates for JWT 2.1 are:

```
<dependency>
    <groupId>org.eclipse.microprofile.jwt</groupId>
    <artifactId>microprofile-jwt-auth-api</artifactId>
    <version>2.1</version>
</dependency>
```

**Comment by dblevins** [comment]
Note that specs under development may not yet have a links such as spec pdf, spec html, tck or compatible implementations

**Comment by dblevins** [comment]
Here is a compatible implementation to add to the JWT 2.1 page:

 - [Open Liberty 22.0.0.13-beta](https://github.com/eclipse/microprofile-jwt-auth/issues/312)

**Comment by dblevins** [comment]
Basic elements of a spec release page:

 - Spec name and title and status
 - Description from the Plan Review or Release Review ballot
 - Compatible implementations (this section will have links to approved Certification Requests)
 - Links (this will have the spec pdf, spec html, tck and maven coordinates)

These sections can have any heading  or be arranged on the page in any way that looks visually appealing.

**Comment by rstjames** [comment]
@dblevins 
here is the latested version. I used Metrics 5.1 because I could find most of the content we discussed should be there. 
Thoughts? 
- not sure what info should be on the Compatible Implementations so I just put a filler for now. 
- light code section or dark
- Think it could be "designed up" bit more but need to have all content we feel should be there. 
- 
![screencapture-microprofile-io-2023-08-24-11_23_26](https://github.com/eclipse/microprofile-marketing/assets/12132146/cb13d624-dd61-437c-95d1-aa55faebeb2d)

**Comment by Emily-Jiang** [comment]
@rstjames `TCK Results` should be `TCKs` to point to the download location for TCK jars.

**Comment by rstjames** [comment]
Updated layout and content: 
![screencapture-microprofile-io-2024-02-01-11_50_13](https://github.com/eclipse/microprofile-marketing/assets/12132146/09dd418c-d941-41f9-8829-616e03865eaa)

**Comment by rstjames** [comment]
@Emily-Jiang, how do I move this forward? For me to do this, I will need the template content for each spec. After that, I can make each individual page. 

I think each spec page should have its own ticket. That way, we can have content for each in one spot and review each before putting them live.

**Comment by jclingan** [comment]
I like having a ticket per spec page

**Comment by rstjames** [comment]
@Emily-Jiang I created git tickets for each specification; please check if I didn't miss something. Also, I created a doc that can be used for organizing each spec content.

https://docs.google.com/document/d/1i2I8zwvoVYx3Dx_d2hXqHwmqv-cVCFxNobWOOhpVhAo/edit?usp=sharing

Can you please read over this and let me know what you think?
@aeiras @jclingan you too :)

**Comment by aeiras** [comment]
@rstjames, 

Great work on drafting a how to template the Spec. I provided my feedback and recommend you lead the show and tell and finalize its review before documentation becomes a wiki under the MPWG repo.  Really good draft.
