### ISSUE TITLE
[Website Improvements] Set new logo to Helidon

### ISSUE THREAD

**Issue by dalexandrov** [microprofile/microprofile-marketing#829]
Please set new Logo to Helidon.

<img width="621" alt="Logo" src="https://github.com/eclipse/microprofile-marketing/assets/2016949/738bfa70-9372-4cc4-919c-29894eeaf321">
[Logo.png.zip](https://github.com/eclipse/microprofile-marketing/files/12393690/Logo.png.zip)

**Comment by rstjames** [comment]
Updated on https://microprofile.io/compatible/5-0/#compatible-implementations
