### ISSUE TITLE
[Blog Contribution] Modern Java in the Cloud, part 1: Introducing MicroProfile

### ISSUE THREAD

**Issue by madsop** [microprofile/microprofile-marketing#830]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7283&action=edit)**
 
 **Social Media Description**
 - [ ] @madsopheim introduces MicroProfile, in the first post in a blog post series on building and deploying modern Java applications.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by aeiras** [comment]
Hola @madsop, 

How fun you are choosing to crosspost your MP content series; kudos to you, Mad! :) 

[Modern Java in the Cloud, Part 1: Introducing MicroProfile](https://medium.com/compendium/modern-java-in-the-cloud-part-1-introducing-microprofile-a0554e89b6c)
--- Review on blog content as follows:

- MP trademark name is MicroProfile. Please drop the Eclipse from its name. It violates the trademark. When MP became a working group, it reset to its original preferred name, MicroProfile. 

<img width="705" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/9f781ef2-4301-4b3e-bbaf-c9b121e4fc17">

- Select appropriate  Categories for each of the blogs: 

<img width="283" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/fa9afac2-60a3-43d7-8d9a-34699d25ff5c">

- SEO is missing:
if you need help, we can help you set it up. 

---
Good start. Looking forward to seeing you rock it with MP's valuable content, MicroProfiler. 

--- 

You can choose to crosspost your MP sessions' recordings as well. I know you and Rustam have rocked it. If there are recordings, bring them to MP.io. your call!

**Comment by madsop** [comment]
Thank you for valuable feedback (as always), Amelia! I've updated the post with the correct name now, and I've done my best with the SEO part. Not my field of expertise, so improvements and suggestions are very welcome.

I like the idea of crossposting the sessions! I'll talk to Rustam and see what we can do.

**Comment by aeiras** [comment]
You are always fun, Mads. Stay strong 👍 

-- 

https://microprofile.io/blog/
Your post has been published with a few adjustments:

1. Under Categories, I dropped Community and added Jakarta EE and Kotlin.  Categories are key to any post; please keep them in mind and focus b/c readers use them to find focus content. 
2. Re-word your intro blog to the crossposting; review and adjust as you see fit. I replaced YOU with DEVELOPER. Your point of view goes first as the statement explaining why you care and why the series is becoming true. 

---

Great, you and Rustam will consider adding the recording of MP sessions to MP.io content. If you do, use each session abstract as the content of the blog and move on. :) 

---

@rstjames can you please take over Mads' blog to add a social media push? Thanks.

**Comment by rstjames** [comment]
scheduled to go out tomorrow and next month. 
![microprofile_modern_java_part-1](https://github.com/eclipse/microprofile-marketing/assets/12132146/637a7359-564a-45f6-ae0f-ebe525bf9c39)

**Comment by aeiras** [comment]
beautiful, @rstjames :)
