### ISSUE TITLE
[Documentation] Update Jakarta/MicroProfile Messaging Slides

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [microprofile/microprofile-marketing#831]
The slides here are a little bit outdated, especially regarding Memberships of the WGs and logos:

https://docs.google.com/presentation/d/1wVaGJssQKPDSRcgRSE52mmm2Lb55THyUc_dGj7F5SAg/edit#slide=id.gbcfab764b6_0_221

A review in a CN4J meeting or email mailing list discussion (minimum) should be done before the release of the new version.

**Comment by rstjames** [comment]
Moving this into a review/ update @jclingan @aeiras @Emily-Jiang 
Do we have updates on this?
