### ISSUE TITLE
[Blog Contribution] How to package your cloud-native MicroProfile app for faster startup

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#832]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7289&action=edit)**

 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
Learn how to repackage your MicroProfile (4.1+) cloud-native applications for faster startup with little or not refactoring and no compromise on Java language features. By @TomWatson5150, Vijay Sundaresan, @lauracowen

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by aeiras** [comment]
Published https://microprofile.io/author/laura-cowen/ 

You are wonderful Laura.
