### ISSUE TITLE
[Blog Contribution] MicroProfile 6.1 preview in Open Liberty 23.0.0.10-beta

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#833]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7291&action=edit)**

 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link
 
Try out MicroProfile 6.1 (Metrics 5.1, Telemetry 1.1, OpenAPI 3.1) in @OpenLibertyIO. Try it now.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by aeiras** [comment]
Hola Laura, @lauracowen

It seems that a version of the blog was moved to Trash. Was it you? Good job.  The formal announcement with that title was published already and highlights the IBM MP 6.1 release blog.  

<img width="1180" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/9abf49c0-0ff5-44c8-9351-c74b6e85b583">

**Comment by lauracowen** [comment]
Hi @aeiras
I've reopened this one as I think there was some confusion about which draft to edit and my draft was mistakenly edited as the MP6.1 release post (then moved to trash) when it was meant to be about the MP6.1 preview available in the recent Open Liberty beta. See #841 

Thx

**Comment by aeiras** [comment]
re-opened it. 

Did you move it to trash?  There is where I found the draft, Laura. 
Headed to the other issue. Thanks for the follow up and patience. :)

**Comment by aeiras** [comment]
Hey @lauracowen, 

I found the issue.  Your blog was published on Oct 16th; likely Emily did it, yet there was no follow-up in the ticket, and a duplicate was created and moved to trash... 

With EclipseCon starting on the 16th and presentations on MP 6.0, the timing was of the essence to get the blogs published. Glad that is the case. 

<img width="995" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/0634e937-a7e4-4c39-b57b-a289eff99810">

Thank you for working with me on this.

**Comment by lauracowen** [comment]
@aeiras I'm not exactly sure what happened. I think someone in Emily's team got confused about which they were supposed to be editing when producing the MP release post that you published directly on the MP blog. I think initially overwrote the draft I'd already created then I guess deleted it when it was realised it was a duplicate. Or something. I'm not sure. Anyway, I just retrieved the trashed draft and made it back to what I had originally created. Emily sent me a message on their behalf to apologise so I knew to check and fix it. :) All fine though.

**Comment by aeiras** [comment]
Glad we found out what happened. All good. 
Remember that when you submit a blog, if you get no response within 5 work days, ping us back so we can review and publish. 5 days is the window for the **Monthly Steward** to follow up and/or assign someone to tackle your ticket. :)
