### ISSUE TITLE
EclipseCon conference talks 

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#838]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Name: Emily Jiang
Twitter ID: @emilyfhjiang

**Event**
EclipseCon

**Schedule**
Day: Tuesday/Wednesday this week
Time: 8am and 1pm

**Media Description**
280 chararters
includes the Twitter ID of the Organizers & the name or Twitter ID of the speaker

If you are @EclipseCon this week, make sure to attend Emily's session @emilyfhjiang on @MicroProfileIO #Telemetry:

Topic: Through the looking glass: Effective observability for cloud native applications
Time:18 Oct 2023 - 16:15 - 16:50
Room:Bürgersaal 2

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers

**Notes**
To help with everything

**Comment by rstjames** [comment]
scheduled
