### ISSUE TITLE
EclipseCon talk: MicroProfile and Jakarta EE Panel

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#839]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Name: Emily Jiang
Twitter ID: @emilyfhjiang

**Event**
EclipseCon

**Schedule**
Day: Tuesday/Wednesday/Thursday this week
Time: 8am 

**Media Description**
280 chararters
includes the Twitter ID of the Organizers & the name or Twitter ID of the speaker

Hello @EclipseCon attendees,  please make sure to attend the panel discussion on @MicroProfileIO @JakartaEE to have your questions answered @emilyfhjiang @ivar_grimstad 

Topic: MicroProfile and Jakarta EE Panel Discussion
Time: 19 Oct 2023 - 11:35 - 12:10
Room: Bürgersaal 2

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers

**Notes**
To help with everything

**Comment by rstjames** [comment]
scheduled
