### ISSUE TITLE
Ship MP t-shirt to Phillip

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#84]
I mentioned in the MP hangout yesterday. It will be great to post MP t-shirts to contributors. @pilhuhn volunteered to post the t-shirts in Europe. Can MP marketing supply t-shirts and distributed out?

**Comment by aeiras** [comment]
Thanks @Emily-Jiang! :) There are 2 parts to this issue, will fix the quick one first and follow up on the other part: get MP swag inventory, efficiently stored, globally, which will need partners. Will create a new ticket for that one. Can you please adjust this ticket to be the shirt for Phillip only? Thanks! 

@pilhuhn (ups, i added other wonderful Phillip, fixed)  please confirm you still don't have a MP shirt?  I thought you have both TT and MP :) 
-- We have ordered internal MP shirts for Tribe distribution, ETA late next week for arrival. 
Traveling and won't get to shipping task until my return, early June. 

**Disclosure:**  I want to personally ship you the MP shirts (2) b/c you via your actions,  are beyond fantastic! ETA: package arrival  in June. Therefore, if you have no MP shirt, just sent me a private email with address and size and done!

**Comment by Emily-Jiang** [comment]
@aeiras I think you misunderstood this. What @pilhuhn volunteered is to ship t-shirts to other MP contributors. Basically we need to ship some t-shirts to @pilhuhn . I think @pilhuhn has MP t-shirts already. By the way, which Phillip do you mean?

**Comment by aeiras** [comment]
Yes, I didn't understand b/c I was the one to give MicroProfiler his MP t-shirt at Javaland a few years back. 

If it is about distribution, we are still not ready for such awesome volunteering task.
new issue created on that task that will take collaboration. :) Let me know if i got it right this time by following up. :)

**Comment by pilhuhn** [comment]
I have T-Shirts for myself. What I proposed on the call/chat was that if I have a bunch of T-Shirts, I can ship them from the office (I go there every once in a while) for those folks that help MicroProfile, just as we discussed. 
I think in my case shipping would be limited to Europe.

**Comment by aeiras** [comment]
That is wonderful to hear @pilhuhn :) 
SWAG global initiatiave is not ready for distribution yet. work in progress using [issue](https://github.com/eclipse/microprofile-marketing/issues/88):

**Comment by aeiras** [comment]
can you please close this issue? i will add label "it won't be fixed" b/c timing is not workable for now. cheers
