### ISSUE TITLE
[Blog Contribution] MicroProfile 6.1 preview in Open Liberty 23.0.0.10-beta

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#841]
**[MicroProfile.io WordPress](https://microprofile.io/wp-admin/post.php?post=7291&action=edit)**

Hi @aeiras
I can't seem to reopen closed issues so I've created this one from #833 as I think there was some confusion about which draft to edit and my draft was mistakenly edited as the MP6.1 release post (then moved to trash) when it was actually meant to be about the MP6.1 preview available in the recent Open Liberty beta. I've fixed the draft (linked above). Thanks

 **Social Media Description**
Try out MicroProfile 6.1 (Metrics 5.1, Telemetry 1.1, OpenAPI 3.1) in @OpenLibertyIO 23.0.0.10-beta now.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by aeiras** [comment]
@lauracowen :) Please take a look at my reply in another ticket copied here. Many thanks for being such an amazing content contributor! 

<img width="983" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/936af955-c357-4a67-93ca-ceaedaf36b58">
-----

@rstjames, 

Please tell us how often the MP.6 announcement blog will be reposted in the 4th quarter. 

Automatically, the implementor's blog is already posted within the Release announcement; @lauracowen do you wish 1 independent media post on the blog as well?  You wrote:

**Social Media Description**
Try out MicroProfile 6.1 (Metrics 5.1, Telemetry 1.1, OpenAPI 3.1) in @OpenLibertyIO 23.0.0.10-beta now.

**Comment by lauracowen** [comment]
@aeiras @rstjames If you can do an independent post, that'd be great, please but whatever works. It's a beta/preview so it'd be for people really eager to try things out rather than properly use yet. Thanks.

**Comment by aeiras** [comment]
Say no more, Laura. 

@rstjames can you please publish via media the IBM blog that deals with 6.1? Thank you!

**Comment by rstjames** [comment]
Scheduled for Monday next week
