### ISSUE TITLE
Microprofile.io has the building box update

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#842]
On the microprofile.io website, it dispalys "Open Telemetry 1.1", but it should be "Telemetry 1.1"
<img width="170" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10999780/3595fd89-2c7f-422b-8882-35932734482a">
It should be 
<img width="129" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10999780/854fb6ad-4fbe-4ef4-8c92-e4c610ffa335">

**Comment by rstjames** [comment]
updated
