### ISSUE TITLE
[Social media push via Hootsuite] Funded MP API tutorial 

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#843]
Please tweet this one every 2 days till 10th November.

We are pleased to invite you to bid for an official MicroProfile Tutorial. Proposals will only be accepted until November 10. For more details, please refer to https://t.co/atCRu7UVpm.

**Comment by Emily-Jiang** [comment]
@aeiras please review and update the tweet accordingly.

**Comment by Emily-Jiang** [comment]
@rstjames can you review and tweet this asap, please?

**Comment by aeiras** [comment]
@rstjames, 

Thank you for looking at this media ticket on Monday. 

@Emily-Jiang Hola! For all media, Ryan is the one to help since MP uses Hootsuite, which is connected to 3 social channels that push formal MP messages about MP. I cannot help with such tasks.  Cheers.
