### ISSUE TITLE
[Blog Contribution] MicroProfile Reactive Messaging 3.0 and MicroProfile Metrics vendor metrics in Open Liberty 23.0.0.11-beta

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#844]
**[MicroProfile Reactive Messaging 3.0 in Open Liberty 23.0.0.11-beta](https://microprofile.io/wp-admin/post.php?post=7317&action=edit)**

 **Social Media Description**

Preview of MicroProfile Reactive Messaging 3.0 in @OpenLibertyIO 23.0.0.11-beta, inc working with Jakarta EE 10, negative acknowledgements, emitters, and backpressure support.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by lauracowen** [comment]
Bump @aeiras

**Comment by lauracowen** [comment]
Bump @aeiras

**Comment by rstjames** [comment]
Published, and the tweet goes out tomorrow. @lauracowen @aeiras

**Comment by lauracowen** [comment]
@rstjames Thank you :)
