### ISSUE TITLE
[Social Media] JakartaOne Livestream 2023

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#845]
**[MP DevRel Branding Resources Community Support](https://github.com/eclipse/microprofile-marketing/wiki/MP-DevRel---Branding-Resources---Community-Support)**

**MicroProfiler**
Name: Emily Jiang
Twitter ID or Github ID emilyfhjiang
Picture, nice to have

**Event**
Link to the event/conference/Session
Organizer logo,  nice to have

**Schedule**
Day: 5th Dec
Time: 16:00 - 16:45 PM EST (GMT-05:00)

**Media Description**
280 chararters
includes the Twitter ID of the Organizers & the name or Twitter ID of the speaker
Join our #Java Champion and MicroProfile SME @emilyfhjiang  to learn about @MicroProfileIO #current #future @JakartaOneConf ! Completely #Free! 
Time: 5th Dec 16:00 - 16:45 PM EST (GMT-05:00)
Venue: sign up https://www.crowdcast.io/c/jakartane-05122023
The day is packed with amazing speakers! 

**Design Card** (for MicroProfile designer)
Minimal requirements highlight the MicroProfiler & the Organizers
![Emily](https://github.com/eclipse/microprofile-marketing/assets/10999780/f784fa7e-8398-47c1-a46c-c4383e183d34)

**Notes**
To help with everything

**Comment by Emily-Jiang** [comment]
@rstjames can you tweet about this talk?

**Comment by rstjames** [comment]
all set
![2023_microprofile_jakartaone_livestream](https://github.com/eclipse/microprofile-marketing/assets/12132146/6c4c9e56-a797-48e4-87c2-455af0db1fd5)

**Comment by Emily-Jiang** [comment]
Thank you @rstjames ! Looks awesome!
