### ISSUE TITLE
[Blog Contribution] New vendor metrics for MicroProfile Metrics in Open Liberty 23.0.0.11

### ISSUE THREAD

**Issue by lauracowen** [microprofile/microprofile-marketing#846]
**[New vendor metrics for MicroProfile Metrics in Open Liberty 23.0.0.11](https://microprofile.io/wp-admin/post.php?post=7320&action=edit)**

 **Social Media Description**
 - [ ]  280 max chararters includes the author's Twitter or Github ID & blog link

MicroProfile Metrics provides application and runtime metrics at the /metrics endpoint. @OpenLibertyIO 23.0.0.11 provides new metrics for the Open Liberty runtime ready to add to your dashboard without having to do any calculations for yourself.

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**
 To help with everything

**Comment by rstjames** [comment]
published and out in the world on social.

**Comment by lauracowen** [comment]
thank you!
