### ISSUE TITLE
[MPWG Website update - 2024 MPWG Budget/Plan  ] Import 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#848]
<img width="389" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/f44ac882-ad06-4d61-88f1-a8d9a6f1484f">

**Comment by aeiras** [comment]
Updated the MPWG External Budget and Plan folder https://drive.google.com/drive/folders/1SOKayoOIBAVQ1ZKLlWRud4M1F0sE4qZr

**Comment by aeiras** [comment]
OK, @rstjames, I finally got to this task. Thanks for your help updating the MPWG Budget via https://microprofile.io/workinggroup/#mptab-program-plan-budget

 **3 Tasks**

1) Replace the introduction to Program Plan & Budget as follows:

The MicroProfile yearly Program Plan is drafted and completed in the open with the MicroProfile community. Once it is approved by The Steering Committee, a MicroProfile budget is prepared by Eclipse Management Organization (EMO). The Steering Committee is required to review and vote on the budget proposed by the EMO. 

Five (5) yearly fees are paid to the Eclipse Foundation. Those fees are constant costs for MicroProfile. The fees take + ~80% of the MicroProfile budget:

1. Ops- Working Group Operations and Governance fee 
2. General & Administration - G&A fee (12%)
3. Trademark Surveillance fee
4. Events Support fee
5. Shared Marketing Services fee 

-----

2) Links listed under the  MicroProfile Program Plan & Budget archives the past MPWG Program Plans and Budgets as follows: 

- 2024 [MPWG Program Plan & Budget + Ballots](https://drive.google.com/drive/folders/1SOKayoOIBAVQ1ZKLlWRud4M1F0sE4qZr)
- 2024 [MPWG Budget Forecast Spreadsheet](https://docs.google.com/spreadsheets/d/18ktMQYgl_9nS-IGCoZXc-kFXC0fdhfjxa1fo0xDVoeE/edit#gid=950497108)

-----
3) Replace the Google Slides Program plan with 2024. The document is already in the drive. :)

**Comment by rstjames** [comment]
@aeiras can you please give me editing rights to the slides? It is the only way I can publish it to the web (embed it on the website)

other updates are done

**Comment by jclingan** [comment]
Granted.

**Comment by rstjames** [comment]
updated
