### ISSUE TITLE
[Event Marketing / Community Outreach] 2024 DevNexus Booth Logistics

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#849]
### The completion due date for all related tasks to this subject is March 18th to March 25th  (tasks with dependencies due by March 18th)

Please refer to the individual issues for additional details.

---

Vince sent the invite to the Marketing forum and private. 

<img width="1044" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/a23681cb-b2ae-494e-ba7c-865917dfe1dd">
----

**Tracing public forum communications:**

- MP Community, Mktg & MPWG message sent 12/11/23 by Amelia

[[ CALL TO ACTION ] 2024 DevNexus April 9-11 -- FREE OSS Booth invite - #849](https://groups.google.com/g/microprofile/c/vy2IEaJiLpM)

**Comment by aeiras** [comment]
Conference Information:

- https://devnexus.com
- April 9th- 11th
- Atlanta, GA
- 2,500 Attendees
-

**Comment by aeiras** [comment]
Hola @vincentmayers, 

Please follow up on the ticket so that this ticket can be assigned to you. 

As discussed in today's meeting, I will create the Excel spreadsheet with logistics + more on MPWG Devnexus 2024 Booth fun.

**Comment by aeiras** [comment]
Per today's marketing discussion, I created the **logistics spreadsheet** to enable MicroProfilers' asynchronous organization. 

- [2024 MP Devnexus Booth Logistics Folder](https://drive.google.com/drive/u/0/folders/1nvBg8JtG1KM9OBnfp82FPJnUol3l26LG)
- [2024 MP Devnexus Booth Logistics - diverse tabs](https://docs.google.com/spreadsheets/d/1ATMzQDm5k72kmbn6SDEhf5EbyGtXIANJPL1NuoB1GGA/edit#gid=0)

The spreadsheet and folder provide a starting point. The access is **Public EDIT**; any MicroProfilers who wish to contribute, especially if attending DevNexus, are welcome to join the logistic efforts by providing feedback & comments in the document(s) and on this ticket.

**Comment by aeiras** [comment]
Vince clarified the following points as Q&A reached him:

- MPWG booth is located under the OSS free booth section. 
- MPWG booth cannot be combined with any other project, e.g., suggestion by Reza during the call was Jakarta EE (the project has paid for its booth. The Jakarta EE booth is located under the paid section) 
- The AJUG contract agreement with OSS projects doesn't require the EF EMO to be involved in signing the agreement because there is no money $ crossing hands. He volunteered to accept the "soft requirement" as a member of the MPWG steering committee without signature.  **NO issue with Vendor neutrality.** 
- The MP community can access DevNexus if volunteering at the MP Booth. Though the recommended is four free passes, more could be granted to the MP Community. :) A genuinely amazing access gift! 

-------

@vincentmayers

MP will work on the booth design (highlighting the MPWG members )  and, with the help of the EF team (due to the costs involved), print the booth backdrop, retractable banners, and table runners +: 

1. Would you happen to have a recommended Vendor that can help with the printing & direct delivery? 
2. given the 6"x 8" booth size, what would be the recommended backdrop size?

**Comment by aeiras** [comment]
@emecas, this is your ticket! :)

**Comment by emecas** [comment]
> @emecas, this is your ticket! :)

Thanks 

I am still having issues to assign the ticket to myself , @aeiras  do you know who is in charge here to troubleshoot the problem, I already updated my GitHub user-id in my eclipse.org account

-----

Solved

**Comment by emecas** [comment]
Following the Marketing Call on 01/22/2024, we have decided to create individual tickets for each task/marketing topic/effort to facilitate better communication and planning. Please provide specific details for each topic so we can ensure adequate budget allocation.

- Design and provide a pull-up banner - https://github.com/eclipse/microprofile-marketing/issues/860
- Stickers - https://github.com/eclipse/microprofile-marketing/issues/861
- Monitor/Display for Demo  - https://github.com/eclipse/microprofile-marketing/issues/862
-  Booth Coverage Schedule  -  https://github.com/eclipse/microprofile-marketing/issues/863
-  T-shirts / swags  - https://github.com/eclipse/microprofile-marketing/issues/864

**Comment by aeiras** [comment]
@emecas using this general ticket, you can link all the other tickets as tasks and control the inventory. 
I will pin this ticket :)

**Comment by olga-timakova** [comment]
Hi everyone! I'm Olga, Conference coordinator at Eclipse Foundation. I'm helping Jakarta with the booth at Devnexus. Please let me know if you need any logistical/marketing support.

**Comment by emecas** [comment]
> Hi everyone! I'm Olga, Conference coordinator at Eclipse Foundation. I'm helping Jakarta with the booth at Devnexus. Please let me know if you need any logistical/marketing support.

Hi @olga-timakova,

We truly appreciate your offer to help with the subjects listed in this [here ](https://github.com/eclipse/microprofile-marketing/issues/849#issuecomment-1904568431).

There are several open tasks, and any support you could offer would be greatly beneficial.

To best understand your availability and preferred communication method, could you please let us know:

   -  What tasks do you feel most comfortable contributing to?
  -   How much time are you able to dedicate towards these tasks?
  -   What is your preferred method of communication (e.g., email, Slack, etc.)?

This information will help us efficiently connect you with the most suitable tasks and ensure clear communication throughout the process.

Thank you again for your willingness to help!

**Comment by olga-timakova** [comment]
> > Hi everyone! I'm Olga, Conference coordinator at Eclipse Foundation. I'm helping Jakarta with the booth at Devnexus. Please let me know if you need any logistical/marketing support.
> 
> Hi @olga-timakova,
> 
> We truly appreciate your offer to help with the subjects listed in this [here ](https://github.com/eclipse/microprofile-marketing/issues/849#issuecomment-1904568431).
> 
> There are several open tasks, and any support you could offer would be greatly beneficial.
> 
> To best understand your availability and preferred communication method, could you please let us know:
> 
> * What tasks do you feel most comfortable contributing to?
> * How much time are you able to dedicate towards these tasks?
> * What is your preferred method of communication (e.g., email, Slack, etc.)?
> 
> This information will help us efficiently connect you with the most suitable tasks and ensure clear communication throughout the process.
> 
> Thank you again for your willingness to help!

Hi @emecas I went through the list of open tasks and I see there is no updates on the roll up banner. I think I can contribute to this. I'm ordering the banner for Jakarta from our trusted vendor and can make an order for you as well. In regards to design - we had a nice banner at EclipseCon that I think we can use as a base. Please let me know what info you would like to include and I will work with our design team on it. 
[Microprofile.pdf](https://github.com/eclipse/microprofile-marketing/files/14522033/Microprofile.pdf)
What budget do you have for the banner?

We can communicate via email: olga.timakova@eclipse-foundation.org or here in GitHub.

**Comment by emecas** [comment]
> Hi @emecas I went through the list of open tasks and I see there is no updates on the roll up banner. I think I can contribute to this. I'm ordering the banner for Jakarta from our trusted vendor and can make an order for you as well. In regards to design - we had a nice banner at EclipseCon that I think we can use as a base. Please let me know what info you would like to include and I will work with our design team on it. [Microprofile.pdf](https://github.com/eclipse/microprofile-marketing/files/14522033/Microprofile.pdf) 

@olga-timakova, thanks for the initial design, it looks great! To finalize the banner, we'll need to determine the standard dimensions and potential costs from your preferred vendor.

For everyone else (@aeiras, @jclingan, @rstjames, @m-reza-rahman) - what are your thoughts on the current design?  Are there any additional elements we should consider including?

>What budget do you have for the banner?

We're still finalizing the budget for the banner along with t-shirts and stickers. We're waiting on the Eclipse Foundation's cost details for items #861 and #864 to give the MPWG a clearer picture.


Finally, does anyone have information on monitor availability for booth demos?
