### ISSUE TITLE
MP and Jakarta talk by Emily (QCon in Beijing)

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#85]
https://2019.qconbeijing.com/presentation/1411
Date: 6th May 14:00-14:45
Room: 305

**Comment by aeiras** [comment]
same feedback as other ticket, avoid throwing debt research to others and provide required data on each session submision via issue. 💯 process without delays !:) safe travels

**Comment by aeiras** [comment]
fyi: you are a committer so you can label, add project as must for the issues you submit to this Repo. do not assign ticket to anyone. :) cheers

**Comment by rstjames** [comment]
@Emily-Jiang closing issue because lack of information and session has passed.
