### ISSUE TITLE
MicroProfile.io/resources site content issue

### ISSUE THREAD

**Issue by ttelang** [microprofile/microprofile-marketing#852]
Please fix or remove following sections.

https://microprofile.io/resources/#section-one
![Screenshot 2023-12-16 at 3 56 39 PM](https://github.com/eclipse/microprofile-marketing/assets/133903/e0864c8e-45fd-43ec-8d84-5e19d8cd1047)

https://microprofile.io/resources/#section-two
![Screenshot 2023-12-16 at 3 56 50 PM](https://github.com/eclipse/microprofile-marketing/assets/133903/d23d2a4d-2609-4342-8e96-3134b5d6bf6b)

https://microprofile.io/resources/#section-three
![Screenshot 2023-12-16 at 3 56 57 PM](https://github.com/eclipse/microprofile-marketing/assets/133903/f258c7fe-0564-4864-9305-dd10c6b00708)

**Comment by rstjames** [comment]
thanks for catching this @ttelang UPDATED

**Comment by ttelang** [comment]
Thanks for the fixes, verified it looks good now.
