### ISSUE TITLE
[Compatible Implementations Announcement] WebSphere Liberty, 23.0.0.12

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#854]
**Organization Name**
 Name: IBM
 
**Product Name, Version and download URL (if applicable):<br/>**

[IBM WebSphere Liberty 23.0.0.12](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~WebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=23.0.0.12&platform=All&function=fixId&fixids=wlp-jakartaee10-23.0.0.12&includeSupersedes=0)
 
**Link to CCR (GH issue in the eclipse/microprofile repository)**
Link: https://github.com/eclipse/microprofile/issues/399

**Media Description**
280 chararters includes the organization's name & URL or blog
We are very pleased to announce that WebSphere Liberty 23.0.0.12 is a compatible implementation for MicroProfile 6.1 https://github.com/eclipse/microprofile/releases/tag/6.1. Enjoy the new release!

 **Design Card**  (for MicroProfile designer)

 **Notes**
 To help with everything

**Comment by rstjames** [comment]
sent out

**Comment by Emily-Jiang** [comment]
@rstjames please also add this to the 6.1 compatible page. I will update the template to highlight the compatible page update as well.

**Comment by rstjames** [comment]
@Emily-Jiang the TCK link sends you to a page that makes you login to IBM. Is this right? 
Can you also send me the "download link" I am not sure I have the correct one.

**Comment by rstjames** [comment]
all updated

**Comment by DerFrZocker** [comment]
> @Emily-Jiang the TCK link sends you to a page that makes you login to IBM. Is this right? Can you also send me the "download link" I am not sure I have the correct one.

The TCK link on the [MicroProfile compatible](https://microprofile.io/compatible/6-1/#overview) site for WebSphere still redirects to a login page. Isn't that against the [TCK process](https://github.com/microprofile/microprofile-wg/blob/main/tckprocess.adoc#public-tck-results-summary), where the TCK results must be:
> Be publicly visible with no password protection or sign-up

Or did the process change?

**Comment by Emily-Jiang** [comment]
> > @Emily-Jiang the TCK link sends you to a page that makes you login to IBM. Is this right? Can you also send me the "download link" I am not sure I have the correct one.
> 
> The TCK link on the [MicroProfile compatible](https://microprofile.io/compatible/6-1/#overview) site for WebSphere still redirects to a login page. Isn't that against the [TCK process](https://github.com/microprofile/microprofile-wg/blob/main/tckprocess.adoc#public-tck-results-summary), where the TCK results must be:
> 
> > Be publicly visible with no password protection or sign-up
> 
> Or did the process change?

Good point! @rstjames can you update the TCK result  link to [this](https://www.ibm.com/support/pages/microprofile-61-tck-results-summary) one

**Comment by rstjames** [comment]
Updated
