### ISSUE TITLE
Jan 8th 2024 MicroProfile Marketing video for YouTube

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#855]
Here is the [link to the video](https://drive.proton.me/urls/4P70R3VX4G#bJQRdk0zJEWy) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=id.7upe6b5brfww) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/20WGuKF4dvI
