### ISSUE TITLE
Jan 9th 2024 MicroProfile LiveHangout video for YouTube

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#856]
Here is the [link to the video](https://drive.proton.me/urls/A5HFQQR9DW#2oLVONZQKysl) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/169CiDbekplRdmoerMQyEPxMVijJGP7OYM5wYDUbF4yw/edit#bookmark=id.8rilex96j3m4) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/0-jo3fb8PNg done
