### ISSUE TITLE
[General]2024 yearly schedule of Social Media across the board - MicroProfilers ( Amelia/Ryan/Emerson)

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#859]
Tasks: 

- [Amelia] Onboard @emecas on the HOW using previews years examples: [Consecutive Yearly Media Messages](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1667854410)
- [Ryan] create a new social card design: [Social Media](https://drive.google.com/drive/u/0/folders/1iLUTCmITijSipZcwB__CmKGPs3_e-e69)
- [Emerson] Review social media wording for all posts. Each post needs its own ticket: [2023 cards and content](https://docs.google.com/spreadsheets/d/1-j0SmFHSRw4pXMsdsY1x0R2HffIUZ3SQni_5zpoBdE8/edit#gid=1254202074)
- [Ryan] schedule the year across post using Hootsuite (FB, Twitter & Linked)
-

**Comment by emecas** [comment]
We had a highly informative and productive 1.5-hour meeting with Amelia today. I'm now fully immersed in the spreadsheet and the tasks at hand. We'll be creating new tickets under the '2024' tab to monitor our progress. Additionally, we'll be augmenting and expanding the spreadsheet to include a 'How-To' section for on-boarding and annual procedures, as well as any relevant topics from previous years that we want to include

**Comment by emecas** [comment]
I have started working on this (progresses):

#### Workflow Proposal:

I propose implementing a workflow with task states linked to a GitHub project. This would enhance task management and provide a clear picture of progress.  For now I am going to keep status in the spreadsheet by task.

Note: This project was the closest thing I have found from 2020-2022, it seems a good start point (https://github.com/eclipse/microprofile-marketing/projects/4)

#### Template Update:

I submitted pull request #882 to update the template for new issues related to consecutive yearly media messages [Consecutive Yearly Media Messages.md](https://github.com/eclipse/microprofile-marketing/pull/882).

#### Automation Potential:

The repetitive nature of some tasks suggests exploring automation possibilities. This could significantly increase efficiency and streamline processes.

**Comment by aeiras** [comment]
PR reviewed and merged. Great improvement as stated in the PR comments, @emecas!

**Comment by emecas** [comment]
Progresses 2024:

- https://github.com/eclipse/microprofile-marketing/issues/895
- https://github.com/eclipse/microprofile-marketing/issues/913
- https://github.com/eclipse/microprofile-marketing/issues/912
- https://github.com/eclipse/microprofile-marketing/issues/916
- https://github.com/eclipse/microprofile-marketing/issues/914
---
- https://github.com/eclipse/microprofile-marketing/issues/920
- https://github.com/eclipse/microprofile-marketing/issues/921
