### ISSUE TITLE
DevNexus Booth Logistics -  Design and provide a pull-up banner

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#860]

**Comment by aeiras** [comment]
For this task, Vince needs to be reached. He is the best equipped at helping with banner recommended sizes and other stuff we could consider. Design starts after getting the exact requirements.

**Comment by emecas** [comment]
03/07/2024 - Asked about dimensions and budget (cost) pull-up banner in email chain with EF and https://github.com/eclipse/microprofile-marketing/issues/849 in https://github.com/eclipse/microprofile-marketing/issues/849#issuecomment-1984869078 to Olga T

**Comment by aeiras** [comment]
@rstjames lets work with @emecas to create a retractable banner as we have done in the past for MP. 
Focus on member logos being on the top of the banner and all messaging in the bottom.  ETA before next Monday. 

Cheers you two.

**Comment by rstjames** [comment]
Rough roll up design concept 
![Screenshot 2024-03-18 at 19 19 23](https://github.com/eclipse/microprofile-marketing/assets/12132146/6bfb6d51-69d2-4fde-b0c3-1e0ca9eab938)

**Comment by jclingan** [comment]
I like the idea of adding the MicroProfile Spec "[Chart](https://docs.google.com/presentation/d/1A3Hbr-O7QFepUP5M0X2hKfqFiO1PZgnBWWhMyovu9JU/edit#slide=id.p8)" in the blue box. To make it last a bit longer (reusable), remove the version numbers. I'd also include the standalone specs. Not sure if we should "assume" JWT Bridge as well.

We don't have to color-code based on "new" specs since we remove versions.  I also don't think we have to categorize platform spec vs standalone. Metrics will be moving to standalone.

**Comment by rstjames** [comment]
@emecas what is the size for these rollups?

**Comment by rstjames** [comment]
@jclingan thoughts? 
![mp_rollupMockup-2](https://github.com/eclipse/microprofile-marketing/assets/12132146/a63f19a9-4502-47ea-9b91-ffbd7bb48ddc)

**Comment by rstjames** [comment]
One more option: @jclingan @aeiras @emecas 
![mp_banner-3Artboard 3](https://github.com/eclipse/microprofile-marketing/assets/12132146/75a5717b-1638-4be7-af3d-c22469a82335)

**Comment by aeiras** [comment]
> One more option: @jclingan @aeiras @emecas ![mp_banner-3Artboard 3](https://private-user-images.githubusercontent.com/12132146/315326580-75a5717b-1638-4be7-af3d-c22469a82335.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzY3NzIsIm5iZiI6MTcxMTAzNjQ3MiwicGF0aCI6Ii8xMjEzMjE0Ni8zMTUzMjY1ODAtNzVhNTcxN2ItMTYzOC00YmU3LWFmM2QtYzIyNDY5YTgyMzM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE1NTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Y2M0ZTliMGNhMDI3MzU4ODM4M2NlYWIwZGQ1ZWMxNjdiNTM1ZjBhM2JkZDdkN2UzMGVjZWIzNTY0OGM4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIo7WyforMRJHzNhd7RXpbgOeM7e2WMQYtWvy39qeLQ)

I love it @rstjames! 

The only improvement I see, if it is still possible to change before sending it to print is to move the **Optimizing Enterprise Java for a Microservices Architecture** below the APIs listing. At the bottom is better b/c the table and people will cover the banner, so the higher the most important information is, the better.

**Comment by rstjames** [comment]
@aeiras Not sure the flow is good this way. Best practice is logo, statement and other info. If we put " Optimizing Enterprise Java for a Microservices Architecture" at the bottom, there is no flow. You need to go to the bottom to get first info what this company is about.  

Can make " Optimizing Enterprise Java for a Microservices Architecture"  smaller... this might help

logos normally go at the bottom. But we want to promote the partners in MP... so need some info before them

**Comment by aeiras** [comment]
I see your point, and given the lack of time, it is better to leave it as it is based on your feedback. Members' logos, as large as they are, are great. 

**Now**, when we talk about continuity of messaging, the MP banner is missing **By the Community, For the Community**, which is the most important message MP stands for.  It is shown and printed on all MP shirts.  Is there a way to include it without removing what it currently is? 
<img width="480" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/8ee73f53-07bb-4987-9528-386340609ab5">

I really like the design and playful usage of the Marks, @rstjames!

**Comment by rstjames** [comment]
latest version: Not print data @aeiras 
<img width="447" alt="Screenshot 2024-03-21 at 17 44 46" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/57e77c5e-22ac-44ad-ac6e-23e8a4c79375">

**Comment by aeiras** [comment]
Thank you for integrating the feedback,  @rstjames!  

MicroProfile Specifications must always be plural. Please add the **S.**. 

Aside from that, everything looks good and complete. If any other MicroProfiler sees issues or has feedback, please send it ASAP. Banner printing is against the clock and won't be able to integrate late feedback -

----

 @emecas and @rstjames, you are doing a great job mediating these tasks with the EF team to get MPWG to DevNexus. :)

**Comment by rstjames** [comment]
@emecas @aeiras 
Updated print files for the banner:
[microprofile_EconomX_large_print.pdf](https://github.com/eclipse/microprofile-marketing/files/14721326/microprofile_EconomX_large_print.pdf)
