### ISSUE TITLE
DevNexus Booth Logistics - Stickers 

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#861]

**Comment by aeiras** [comment]
MP Vertical Logo printing information is as follows: [google drive information](https://docs.google.com/document/d/1uoVx9qQJ7_inqlc-FfPKaTRxzN4q-H06cqghhxeKOrM/edit)

- [Source File](https://drive.google.com/drive/u/0/folders/0B7PK4ZIk1mjAWmFrSHl2U1lNRkk?resourcekey=0-9RbuKNezWos7NosAKDyOlg)
- Style: Die cut 2"x 1.37" 
<img width="584" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/f7b2c5ac-e9c5-467f-91ce-e1a5b49db275">

----

1000 stickers are recommended. 
Leftovers can be given to JUGs in attendance at DevNexus.

**Comment by aeiras** [comment]
@emecas the above is the date I was referring in today's meeting, MicroProfiler.

**Comment by emecas** [comment]
03/07/2024  - Asked about budget for printing the sticker in email chain with EF and #849 in [this reply](https://github.com/eclipse/microprofile-marketing/issues/849#issuecomment-1984869078) to Olga T

**Comment by emecas** [comment]
Real dimensions shipped to DevNexus 2024:

3.3 '' x  1.85 ''
(7.7 cm x 4.7 cm)

cc: @aeiras  @rstjames
