### ISSUE TITLE
DevNexus Booth Logistics - Monitor/Display for MP Demo

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#862]
Due Date: ?
To Do: Draft the Demo and present it in next marketing call

**Comment by emecas** [comment]
@aeiras @rstjames I'm having trouble accessing the MicroProfile presentation template from the following link: https://microprofile.io/resources/branding/#pres-temp.

I tried accessing the shared presentations folder, but unfortunately, I couldn't find the template itself to make a copy for the upcoming Demo.While I found two DevNexus 2018 presentation documents, they lack the complete design elements available in the official template.

**Comment by aeiras** [comment]
Hola Emerson, 

Thank you for bringing this to our attention. The download link leads you to an empty folder that should have the presentation : 
https://docs.google.com/presentation/d/1YNyhYRAhybpSoPAEm__sQ_zNKrUHKQi87G0j5e7GiWc/edit#slide=id.g88e5e7c2f7_0_78

Emerson, see the above link with the 42 slides.  NOW, it is available when you click Google Slides on the right side below the visual presentation on the website. It is not UX-intuitive, so we must fix this by adding the slides to the folder.  

Ryan,

I added the PPT document to the drive (emerson, you have 2 ways to get it now 💛). Ryan, I wonder if you can follow up on this to understand what happened with the copy in the drive, adjust, fix...  Thank you. 

Cheers,

**Comment by emecas** [comment]
This is a first draft for the presentation annotated with comments about WIP and ideas:

https://docs.google.com/presentation/d/1HjCF_MicYoc08tO1SYko_Sicy_aiw3IL5LYl_K94qoI/edit?usp=sharing  

To discuss in  the next marketing call Mar 06

@aeiras @rstjames you are welcome for any early review!!!!

**Comment by rstjames** [comment]
Hi everybody. @emecas @aeiras 
Very strange. I'm not sure where the template would have gone or what affected the link, but I have another solution that could help organize this. Add the template to the "Google slide template gallery." This means, when someone wants to use the Google slide template, they only need to click the link:  File> New>Template from gallery> and save it to where they want it... This way, it can not get lost. 

<img width="593" alt="Screenshot 2024-02-23 at 9 31 07" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/1644d977-cadb-416b-ba5c-3cdd75cc992e">

But the issue with this is that it is in the Tomitribe gallery...? @aeiras 

<img width="854" alt="Screenshot 2024-02-23 at 9 36 02" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/a56f266b-30fd-4c70-8518-ea16b56ec8e2">


Or I would add a page at the beginning of the slides reminding people to make a "copy." 

I guess we can solve this on the next MP call.

**Comment by Emily-Jiang** [comment]
@emecas thanks for putting together a template. Slide 15 should be reworked as it was predated and it should list the working group members. Can you please enable commenting for the template?

**Comment by emecas** [comment]
> @emecas thanks for putting together a template. Slide 15 should be reworked as it was predated and it should list the working group members. Can you please enable commenting for the template?

Thanks @Emily-Jiang, you must be able to comment now

**Comment by emecas** [comment]
> Hi everybody. @emecas @aeiras 
> Very strange. I'm not sure where the template would have gone or what affected the link, but I have another solution that could help organize this. Add the template to the "Google slide template gallery." This means, when someone wants to use the Google slide template, they only need to click the link:  File> New>Template from gallery> and save it to where they want it... This way, it can not get lost. 
> 
> But the issue with this is that it is in the Tomitribe gallery...? @aeiras 
>
> Or I would add a page at the beginning of the slides reminding people to make a "copy." 
> 
> I guess we can solve this on the next MP call. 
> 

Thank you, @rstjames, for following up. It's a good idea about adding the extra slide to remember to make a copy . See you in the next  MP marketing call

**Comment by aeiras** [comment]
@emecas, great job creating the demo draft. 
I provided feedback via comments in the slides. 

--- 
@rstjames can you help with the design of the DevNexus demo? Thanks, Triber.

**Comment by emecas** [comment]
03/07/2024 - Asked about monitor availability in email chain with EF and https://github.com/eclipse/microprofile-marketing/issues/849 in reply https://github.com/eclipse/microprofile-marketing/issues/849#issuecomment-1984869078 to Olga T
