### ISSUE TITLE
DevNexus Booth Logistics - T-shirts / swags

### ISSUE THREAD

**Issue by emecas** [microprofile/microprofile-marketing#864]
[Print data- t-shirt ONLY](https://drive.google.com/drive/u/0/folders/0B7PK4ZIk1mjAT3hTWjJMM2lGYU0?resourcekey=0-6HJOanvfrcZB2uhDjjhf0A)

----
**material**
Unisex Next-Level style 6210 -  “midnight-navy”  
**mockup sizing**
Front design: 9” wide and 6.9” tall

**Comment by aeiras** [comment]
@rstjames, can you please update the 2024 shirt following the 2023 design? Members update

**Comment by aeiras** [comment]
@emecas this ticket is now linked to this ticket : ) https://github.com/eclipse/microprofile-marketing/issues/866

**Comment by rstjames** [comment]
@aeiras @emecas all update on the drive https://drive.google.com/drive/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg&usp=drive_link

**Comment by jclingan** [comment]
My only comment is on the color. The typical dark blue background looks good. In the past, we've had a brighter blue background that was "egad, that's ugly" blue :-)

**Comment by jclingan** [comment]
@m-reza-rahman brought up the need to review "printing the working group members" with the Eclipse Foundation.

**Comment by rstjames** [comment]
@emecas I suggest the darker blue shirt

<img width="424" alt="Screenshot 2024-03-20 at 17 19 52" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/e7974068-dfa8-4f79-aa57-c1db51666930">

**Comment by emecas** [comment]
Adding quote information:

@aeiras  what would be required for approval?

![image](https://github.com/eclipse/microprofile-marketing/assets/849502/cc44a3c0-9f2f-4e9f-a8cf-27178cef4c19)
