### ISSUE TITLE
[Website -MPWG Page update] list Emerson as the Committer Representative

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#865]
Emerson Castañeda with twitter ID https://twitter.com/emecas

Thank you @rstjames

**Comment by rstjames** [comment]
@aeiras you would like him on this list? 

what about these parts? Does he have an orginization? 
Organization - Representative- Alternate

<img width="622" alt="Screenshot 2024-02-06 at 15 42 40" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/3f604ed4-73d9-443c-aff0-e74802a6007b">

**Comment by aeiras** [comment]
@rstjames thanks for the follow up. 

NO organization. Directly covers the Committer Representative with no alternative.

**Comment by rstjames** [comment]
updated

**Comment by aeiras** [comment]
@rstjames, 

Lets place Emerson on top as listed in the chart. Notice that the spot currently repeats twice. Lets fix that. Thanks. 
<img width="801" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/9bc36747-a4ad-47ce-85fb-6b9f32d96949">

**Comment by rstjames** [comment]
@aeiras fixed

Also should we remove [Garden State Java User Group](https://gsjug.org/) from the list?

**Comment by emecas** [comment]
Thank you @rstjames 

Thank you @rstjames! I've checked it both on a regular browser and the mobile version, and everything seems to be working as expected. The layout looks great on both platforms, and the content is easy to read , also the Tweeter link is working correctly.

https://microprofile.io/workinggroup/#mptab-members

I am wondering why some representative  don't have a (Tweeter, GitHub or any other) link ?

**Comment by aeiras** [comment]
> @aeiras fixed
> 
> Also should we remove [Garden State Java User Group](https://gsjug.org/) from the list?

@rstjames, 

Emerson holds a formal position in the working group, so the name under Company must be: Committer Representative as listed above.

**Comment by aeiras** [comment]
> Thank you @rstjames
> 
> Thank you @rstjames! I've checked it both on a regular browser and the mobile version, and everything seems to be working as expected. The layout looks great on both platforms, and the content is easy to read , also the Tweeter link is working correctly.
> 
> https://microprofile.io/workinggroup/#mptab-members
> 
> I am wondering why some representative don't have a (Tweeter, GitHub or any other) link ?

@emecas, 

The social media is not standardized. Each Member can use whatever social media of their choosing.  
Twitter is not the it. 
FB is not the it. 

It goes by wherever the member is and what is their country trend. :) 

I hope this clears up your good question.

**Comment by rstjames** [comment]
@aeiras Updated

**Comment by aeiras** [comment]
thank you, Ryan!
