### ISSUE TITLE
[2024 T-shirt Update] check for logos +  MPWG Approval via Vote

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#866]
@rstjames, 

Due to DevNexus, the MP t-shirt is needed.  Thanks for being awesome with the prompt update on 2023.

**Comment by rstjames** [comment]
@aeiras updated the files https://drive.google.com/drive/folders/0B7PK4ZIk1mjAdHJycUxEZjFaNTA?resourcekey=0-iEZNjUww8ArPa9r3PKbRVg&usp=drive_link

**Comment by rstjames** [comment]
<img width="899" alt="back_2024" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/fe42afc9-b82e-4ea4-b66a-04a9094744d4">
<img width="898" alt="front_2024" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/144b76ec-63ef-457f-97a2-bcc0f7a1cb58">

**Comment by aeiras** [comment]
Thank you, @rstjames!
---- 

@emecas, please use the below guide on your communications with the EF team.  
 The t-shirt material and colour. Also, let's use the inventory of the spreadsheet under Swag: 200 shirts, including 2XL and 1000 stickers, to enable the price estimate. 

https://docs.google.com/spreadsheets/d/1ATMzQDm5k72kmbn6SDEhf5EbyGtXIANJPL1NuoB1GGA/edit#gid=447290905 

**Fabric style and colour** 
NEXT LEVEL 6210 MID-NAVY

**Art dimension for front shirt**
9" wide X 7 Tall  

**Back t-shirt**
**Must** be larger than 10" wide x 12" tall [based on past print with fewer logos and wording] 

**Panthone colours:**
Base /White    Plastisol 
PMS 143 C


----- 
**For reference to help the EF marketing team** 

Adding preferred print as done with Deluxe Printing order
[2019 Shirt Ordering Form.pdf](https://github.com/eclipse/microprofile-marketing/files/14185768/2019.Shirt.Ordering.Form.pdf)

<img width="732" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/904e0826-6155-462d-9919-82488511d93a">

**Comment by aeiras** [comment]
@emecas, we don't want a blue shirt. Must be dark blue /grey if NEXT LEVEL 6210 MID-NAVY is not available, something similar to it is desired. This was discussed on yesterday's call by the group.

**Comment by aeiras** [comment]
@emecas, 

Are you comfortable submitting the ballot to get the design approved via the WG forum? Or do you prefer @jclingan helps you? 
There is NO need to wait for the approval ballot to get the price estimates from the EF. 

@jclingan can you please advice?   We don't have a business ballot template yet... o_n my to-do_... until that is done, i wonder if you can help Emerson with this task.

**Comment by rstjames** [comment]
Here is the same colors "mockup" from 2021. 
![MP-shirt-Front-2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/12163a3b-eb03-4324-b5c3-0ad439f7522f)
![MP-shirt-back-2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/0bb9b40d-8ea4-425d-bc61-d94fb84be913)

**Comment by aeiras** [comment]
@rstjames, the new mock-ups are great. @jclingan, any comments? Lets push for a vote if everything looks good. :) 

The preview mockups are now hidden. :) Thank you!

**Comment by aeiras** [comment]
@jclingan I recommend we submit the vote next Monday until the following Monday, 7 days. :) What is your take on this? Thanks!

**Comment by emecas** [comment]
@jclingan  @aeiras  I totally missed this,  I can submit anytime , how do you like to manage the voting for this!!!

**Comment by aeiras** [comment]
@rstjames, 

Can you please prioritize updating the swag to current members?  

Thanks, @emecas for the reminder. 2024 removes Garden State.

**Comment by emecas** [comment]
Related to #877

**Comment by rstjames** [comment]
@aeiras should AsianInfo be removed from the t shirt?

**Comment by rstjames** [comment]
Updated shirt: 
![MP-shirt-Front-2024](https://github.com/eclipse/microprofile-marketing/assets/12132146/bb4ac1ed-7907-4b4c-8716-1e9e050ec871)

<img width="869" alt="MP-shirt-back-2024" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/89049ae7-1351-4c0b-b026-d6bd3c96be76">

**Comment by aeiras** [comment]
> @aeiras should AsianInfo be removed from the t shirt?

@rstjames, 

Yes. AsianInfo needs to be removed from the shirt and website. Please file a ticket for that task. Thank you. 

The steering committee will vote to invite Garden State JUG as a Guest.   The passing of that vote means that Garden state will be added back. I will create a ticket once the results are out. Thanks.

**Comment by rstjames** [comment]
<img width="938" alt="Screenshot 2024-03-04 at 11 31 50" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/88ae9240-1ef0-4ffa-aab0-8d3e37410d94">
@aeiras

**Comment by aeiras** [comment]
closing this ticket as it is related to https://github.com/eclipse/microprofile-marketing/issues/877

@emecas fyi
