### ISSUE TITLE
[Infra- SurveyMonkey] Enable Emerson as the Committer Rep to have access to tool

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#867]
Based on the work done on https://github.com/eclipse/microprofile-marketing/issues/568, Edwin needs to be removed as a past Committer Rep, and Emerson needs to gain access. 

---- Via this ticket, we need to contact the EF Infra team to request the access update.

**Comment by aeiras** [comment]
Hola Infra Team [eclipsewebmaster](https://github.com/eclipsewebmaster)

Thank you in advance for helping us with this INFRA tooling update request.

**Comment by aeiras** [comment]
@emecas, please take the time to understand the [MPWG SurveyMonkey Data Protection Impact Assessment (DPIA)](https://github.com/microprofile/microprofile-wg/wiki/MPWG-SurveyMoney-Data-Protection-Impact-Assessment-(DPIA))

**Comment by emecas** [comment]
> Hola Infra Team [eclipsewebmaster](https://github.com/eclipsewebmaster)
> 
> Thank you in advance for helping us with this INFRA tooling update request. 

@eclipsewebmaster , may you please help us with this

**Comment by emecas** [comment]
From MPWG Steering Committee Call 06/25 - Links to keep present under this subject:

 - MPWG SurveyMoney Data Protection Impact Assessment (DPIA)
   https://github.com/microprofile/microprofile-wg/wiki/MPWG-SurveyMoney-Data-Protection-Impact-Assessment-(DPIA)
   
 - Why, When and How to Conduct Surveys 
   https://github.com/microprofile/microprofile-wg/wiki/Why,-When-and-How-to-Conduct-Surveys

**Comment by aeiras** [comment]
@emecas, 

surveys has been forgotten... 

Before or when you get your access to SurveyMonday, you must accept the DPIA in writing via this ticket. One sentence suffices. It is part of the process, as explained long ago. If the document is not clear, let's fix it by opening a new ticket to tackle it. Also, it is crucial that you help improve the wiki on running surveys by going. Do keep it in mind. 

Question shoot. You rock for starting the survey initiative again, MicroProfiler.

**Comment by Emily-Jiang** [comment]
@emecas please open up a gitlab issue [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/)

**Comment by emecas** [comment]
> @emecas please open up a gitlab issue [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/)

Issue created here:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4798

**Comment by aeiras** [comment]
Emerson and I have access to MPWG SurveyMonkey as of 6 days ago as listed on issue 4798.
