### ISSUE TITLE
Jan 22nd 2024 MicroProfile Marketing Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#868]
Here is the [link to the video](https://drive.proton.me/urls/H0YWN5VQE4#FY9IgDN56jwt) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=id.dj0c34hemh6w) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/XfwzqoQEJWY updated
