### ISSUE TITLE
[2024 Social media] Design for social media cards creation 

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#870]
@rstjames, 

Here we go again. Please brainstorm and share 2 to 3 designs to enable feedback on the feel and look of 2024 MP social media cards. 

Thank you for rocking it.

**Comment by rstjames** [comment]
Here are 2.5 versions one is similar to the other but dark and light. 
Thoughts? 
![Twitter Post_3](https://github.com/eclipse/microprofile-marketing/assets/12132146/e15b141a-efca-428b-bb03-f55a784139a5)
![Twitter Post_2](https://github.com/eclipse/microprofile-marketing/assets/12132146/abf78dac-d3da-436a-90ce-5f5f45ca189b)
![Twitter Post_1](https://github.com/eclipse/microprofile-marketing/assets/12132146/4a4153ec-12be-446c-9df1-e927ddd79e84)

**Comment by aeiras** [comment]
I like the 3rd version, darker with the light yellow around. 

@rstjames, lets send this ticket to the marketing forum to request feedback on direction. 

@emecas what is your take on the direction of the design? :)

**Comment by Emily-Jiang** [comment]
I like the 1st option. Thank you @rstjames for the design!

**Comment by aeiras** [comment]
Marketing forum email by @rstjames [social media images for 2024
0](https://groups.google.com/g/microprofile-marketing/c/9N7QSgfY2V0)

**Comment by rstjames** [comment]
Here is the newest version with elements taken from other designs. I formatted the time /date and location in this way because it makes it scalable for other content and also easy to digest quickly from a viewer.  @Emily-Jiang @aeiras @emecas 
<img width="1249" alt="Screenshot 2024-02-23 at 10 54 09" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/591aa14b-9820-4179-abe4-d221ced244de">

**Comment by Emily-Jiang** [comment]
Looks awesome! Thanks @rstjames !

**Comment by aeiras** [comment]
it looks better @rstjames. Great job integrating the feedback :) 

@emecas, 

The 2024 design card based is above.  Now, you can create the tickets to schedule 2024 constant messaging. Cheers.

**Comment by rstjames** [comment]
I think this can close @aeiras
