### ISSUE TITLE
[Website] Deprecated Slack link - update to current access

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#871]
Update to new slack link: https://microprofile.io/workinggroup/#mptab-social

**Comment by rstjames** [comment]
@aeiras  No conversations are happening on there... except for some personal pings when there is a quick question. And not sure how to update this think to what we have. 

Should I remove this?

**Comment by rstjames** [comment]
https://join.slack.com/t/microprofile-wg/shared_invite/zt-2a4v72to7-04lWDgjAvKEnvy343qqusw

**Comment by rstjames** [comment]
updated
