### ISSUE TITLE
February 5th 2024 MicroProfile Marketing Meeting video for YouTube

### ISSUE THREAD

**Issue by jclingan** [microprofile/microprofile-marketing#873]
Here is the [link to the video](https://drive.proton.me/urls/349G0YSZ10#heV1r7l68Myn) for upload to YouTube. Please [update the Meeting Minutes](https://docs.google.com/document/d/1IEuuIowvv5epov_rNLva51IjRMgUGlbfPi-lInecJRI/edit#bookmark=id.3jfxgkr5i5gu) with a link to the recording.

Thanks!

**Comment by rstjames** [comment]
https://youtu.be/2Y2yNh6irko updated
