### ISSUE TITLE
Remove GS JUG from 2024 MP shirts

### ISSUE THREAD

**Issue by rstjames** [microprofile/microprofile-marketing#877]
And update print files and mockups

**Comment by rstjames** [comment]
The files have been update and added to the drive: @aeiras 

<img width="1225" alt="Screenshot 2024-02-28 at 21 51 46" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/dc056f64-b3ae-44e1-b484-41edd69f38a4">

https://drive.google.com/drive/folders/1VuGDwQ_NNdU5nwQV-3a-sDfLhOfLAzid?usp=drive_link

**Comment by aeiras** [comment]
Thank you, @rstjames!

---

@emecas, 

Please connect with @jclingan to initiate the 7-day business vote ASAP. Questions, shoot and thanks for owning this effort.

**Comment by emecas** [comment]
02/29/2024 - Followed in [microprofile-steering]  to defined what else is required start voting ASAP  CC: @jclingan

**Comment by rstjames** [comment]
@emecas @aeiras should AsianInfo be removed too?

**Comment by emecas** [comment]
> @emecas @aeiras should be removed, too? 

Thanks @rstjames , by following the recent communication from EF, I would think so:

> _On Feb 28, 2024, at 12:42 PM, <microprofile-steering@eclipse.org> wrote:_
> 
> 
> _All:_
> 
> _Please note Hunan AsiaInfo Anhui Technology Limited no longer holds membership with the MicroProfile Working Group._  
> _As a result, their logo needs to be removed from https://microprofile.io/workinggroup/._
> 
> _Also, I'd like to draw your attention that the Garden State Java User Group logo appears to be missing.  While they are_
> _currently a Guest member, they should be included in the member's list on the website._
> 

Also, following the replies about the plan on extending to Garden State Java User Group an invitation by the Steering Committee as a guest member. Would not have more sense keeping their logo?

**Comment by rstjames** [comment]
Updated shirt: I added to the drive as "10 members" drive. Ten logos are a bit trickier @aeiras @emecas 

https://drive.google.com/drive/folders/1VuGDwQ_NNdU5nwQV-3a-sDfLhOfLAzid?usp=drive_link

<img width="1026" alt="Screenshot 2024-03-01 at 13 55 02" src="https://github.com/eclipse/microprofile-marketing/assets/12132146/9222786b-6768-4f71-adf1-a1b5b5ec7ed6">

**Comment by aeiras** [comment]
@rstjames  this version looks good. 
It will add Garden State formally after the JUG is voted as a guest. I will file a ticket for changes to MPWG members to connect the latest updates. 

Thank you.

**Comment by aeiras** [comment]
As discussed today, the latest changes look good, @rstjames!

@emecas, this is a go after today's call review-- the ballot template is ready for your review and usage. :)

**Comment by emecas** [comment]
> @emecas, this is a go after today's call review-- the ballot template is ready for your review and usage. :)

thanks @aeiras ,  where is it ?

**Comment by emecas** [comment]
> > @emecas, this is a go after today's call review-- the ballot template is ready for your review and usage. :)
> 
> thanks @aeiras , where is it ?

answering to myself https://github.com/eclipse/microprofile-marketing/issues/840#issuecomment-1977652831 :)

**Comment by aeiras** [comment]
Good updates everyone. closing this one. :)
