### ISSUE TITLE
[Social Media] LinkedIn Post: Crafting the Official MicroProfile API Tutorial 

### ISSUE THREAD

**Issue by ttelang** [microprofile/microprofile-marketing#878]
I am planning to create a LinkedIn Post as below: 

------------
I am thrilled to share my latest endeavor: Developing the Official MicroProfile API Tutorial in collaboration with the Eclipse MicroProfile Working Group.  

As the landscape of cloud-native development evolves, equipping developers with the knowledge and skills to navigate these changes is essential. The Official MicroProfile API Tutorial is being created to meet this need, offering a comprehensive resource for developers at all stages of their journey. 

This initiative is a collaborative effort, and the support of the Eclipse MicroProfile Working Group has been invaluable. I am deeply grateful for the opportunity to contribute to the MicroProfile community. I am eager to see how these tutorials will evolve with the collective input and expertise of the group.

I invite you to join us on this journey at https://github.com/ttelang/microprofile-tutorials for your feedbacks and suggestions for improvements. Your insights, feedback, and contributions are essential to create a comprehensive and enriching learning resource. Together, we can shape the future of enterprise Java microservices.

I want to extend my heartfelt gratitude to [Reza Rahman](https://www.linkedin.com/feed/#), [Clark Roundy](https://www.linkedin.com/feed/#), [Kito Mann](https://www.linkedin.com/feed/#), [Emily Jiang](https://www.linkedin.com/feed/#), [John Clingan](https://www.linkedin.com/feed/#), Amelia Eiras and many more community members for their invaluable support and guidance as I embarked on this journey.

Stay tuned for more updates about our progress!

#MicroProfile #EclipseMicroProfile #Java #Microservices #OpenSource #Learning #Development #API #Tutorials #WorkInProgress
---------------

Kindly review and suggest any changes in case required.

Best Regards,

Tarun Telang
Twitter ID: https://twitter.com/taruntelang
Github: https://github.com/ttelang
LinkedIn: https://www.linkedin.com/in/taruntelang/

**Comment by ttelang** [comment]
The sessions label got added automatically. Looks like I used the wrong template for this issue. This is issue is created regarding LinkedIn Post, it's not a SEssion.

**Comment by aeiras** [comment]
@ttelang, 

Thank you for drafting such a great insight to your MP contribution. It is important for YOU to highlight your efforts and for MP to highlight you. 

My blog feedback is added in a Google document under the Tutorial folder created for the tutorials. Remember, when asking for reviews on the business side of things such as blogs, the easiest way to collaborate is Google Docs via _suggested mode_.  
https://docs.google.com/document/d/1S3Vjtm9AXKykuZh4W34f8Wp7_ylYz4DZlDgwzoHkjLA/edit

- Feel no pressure to accept any or all suggestions. 

---
**Important:**
Please keep in mind that the project's name is MicroProfile, not Eclipse MicroProfile. The working group project's name is MicroProfile Working Group.   Any place in your tutorial content that has the Eclipse inserted in the project's name **must** be deleted as it violates the MicroProfile registered mark. 

---
**Lastly**, 
Once you have published the blog, can you please consider crossposting it to (guidelines [Case 2](https://github.com/microprofile/wpsite) ) the MP blog? 

I have added you as an MP WordPress contributor so you can contribute to MP blogs. :) 
<img width="1091" alt="image" src="https://github.com/eclipse/microprofile-marketing/assets/10731224/8473e2e7-dec5-4196-b6fd-badb4ca64f0f">

https://microprofile.io/blog/

**Comment by ttelang** [comment]
Posted over LinkedIn - https://www.linkedin.com/posts/taruntelang_github-ttelangmicroprofile-tutorials-activity-7165873128760365056-fdbQ?utm_source=share&utm_medium=member_desktop

**Comment by ttelang** [comment]
Added a MP blog as a cross post -  https://microprofile.io/wp-admin/post.php?post=7343&action=edit

**Comment by aeiras** [comment]
@ttelang, 

The blog is published in the MP blog. You rock!  https://microprofile.io/2024/02/21/crafting-the-official-microprofile-api-tutorial-in-collaboration-with-the-microprofile-working-group/
--- 

Please review and adjust the social media message below. It will share your blog via the MP Hootsuite account: 

The @MicroProfileIO API Tutorial is being created by @taruntelang with feedback from MicroProfilers💛Learn more about Tarun's journey and join the journey.   https://microprofile.io/2024/02/21/crafting-the-official-microprofile-api-tutorial-in-collaboration-with-the-microprofile-working-group/

#SharingIsCaring #MicroProfileTutorials #OpenSourceTutorials #OSS #Java

---
Once you review is completed, @rstjames will help post the blog and schedule its reposting every 2 weeks for 2 months.

**Comment by rstjames** [comment]
@ttelang also where does the image in the blog come from?

**Comment by rstjames** [comment]
![microprofile_api_tutorial](https://github.com/eclipse/microprofile-marketing/assets/12132146/48858eaf-6bb6-45fa-ade2-fa44fd9b8130)

**Comment by rstjames** [comment]
All scheduled
