### ISSUE TITLE
[Swag- Website]  t-shirts, hoodies, Koozies, stickers - Website section under Branding Page

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#88]
**Brainstorming minimum requirements: **
SWAG [drive document/public edit access](https://drive.google.com/open?id=1x2Ul1mn0EtH67tdl5kxFPNnoLV2cbYlv)

[ForumThread](https://groups.google.com/forum/#!msg/microprofile/ZfAfC85-FXc/ROWjmnx9AQAJ)
- create a MP Swag tab (MP Website)

- [ ] set up the minimal parameters on how MP shirts are distributed.  Ideas are:  to someone writing a blog; giving a session-- there are MANY active ways for contributing to MP

- [ ] push via media that action [available swag is happening & how to earn/own it]

- Make it easy for Partners & Individuals to support funding effort MPswag:

- [ ] in COM swag page state clearly to the peny $ the dedicated amount to SWAG: t-shirt and stickers 

- [ ] [ ] choose 1 country in each continent

- [ ] choose 1 JUG group/individual in each country/continent

-  full transparency of tshirt inventory and who supports financially and with storage via JUG and distribution means:

- [ ]   exact inventory and proactive inventory updates on  distribution (~excel sheet) by JUG/individuals - controlled 

... work in progress.

**Comment by aeiras** [comment]
@jeanouii & @rstjames I have added you to the issue b/c you attend the MP marketing calls and this topic needs to be stated there on next call.
  All follow up must be done via this ticket  or the documenet -- directly. Thanks.

**Comment by Emily-Jiang** [comment]
+1. I have been championing for this to happen. I will visit Dublin Jug on 31st July. Can we get some t-shirts and stickers to be shipped there?

**Comment by aeiras** [comment]
Bringing life the MP SAWG won't be possible by your dates Emily. 
None else has provided feedback, so that is a show stopper to implement into website and enable anyone to sponsor and choose where/whom & how to sponsor. That is the easy part, yet getting the logistics in place is just be beginning in that doc you see. :) 

**INSIGHT:** 
I created the intial crude SWAG draft, sent to [forum ](https://groups.google.com/forum/#!msg/microprofile/ZfAfC85-FXc/ROWjmnx9AQAJ). 
This topic & ticket has not been yet discussed in the Community call. 

The goal is to create a new page in the website  CALL TO ACTION: SWAG Sponsorship. 
CTA will  enable anyone, _including individuals_ to sponsor their preferred swag from t-shirts, to shirts, etc.

The US logistics are set and until we secure other print shirt continents vendors' to avoid extra costs on shipping, ect, we won't be able to easily iterate this awesome initiave. 

I recommend you help make better the document. 
@jeanouii is 1 of the dedicated Tribers during the MP Mktg bi-monthly call. Ideally on next call, both of you, if you are able to attend next call, that is. 

From my side, I don't believe that it is a show stoper to continue pushing this initiave via this git, THE  **document** (which is living and welcoming feedback)

Ryan won't be back from Vacation until middle of July, so no adjustments can be done into website until later july.

**Comment by aeiras** [comment]
until the CTA is available, every partner who desires own its own sponsorship b/c we haven't set up the mediums to enable everyone to own such awesome sponsorship. I am pretty excited to get for MP to get this live in Q4.

**Comment by aeiras** [comment]
Similar to the Apache Software Foundation store **but smaller:**  https://www.apache.org/foundation/buy_stuff.html

**Comment by aeiras** [comment]
After today's 2021 Budget call, there is a chance for revival. MP Mktg forum email sent[MPWG Swag as it relates to Individuals + ORG Donating Swag to the MP Community](https://groups.google.com/g/microprofile-marketing/c/3xCWTBx4oGY)

**Comment by aeiras** [comment]
@vincentmayers, 

This ticket is pending and is exactly what you brought in on today's meeting. :)

**Comment by caitmm43** [comment]
@aeiras hey there, is this ticket still pending / in progress, or should it be closed?  Thanks!  :)

**Comment by aeiras** [comment]
caitmm43 Caitlin, 

We need to pull in Vince, who mentioned his desired to help with the task. 
The set up of a new page in the website where anyone can buy a sticker, hoody, or t-shirt directly from the Printer Vendor will be most helpful. 

It is up to Vince to review current document and see if it is worth keeping it or archiving and creating a new doc. :)

**Comment by aeiras** [comment]
new ticket once there is an owner for this activity is preferred. :)
