### ISSUE TITLE
[Blog Contribution] Announcing the New Github Repository for the MicroProfile Tutorial Content

### ISSUE THREAD

**Issue by ttelang** [microprofile/microprofile-marketing#881]
Below are the details of my blog post announcing the eclipse/microprofile-tutorial repository and inviting community members to share feedbacks and suggestions to the Tutorial Content.

**Content copy/edit review (available & optional)
- [Announcing the New MicroProfile Tutorial Repository on GitHub](https://docs.google.com/document/d/1MbqvLmE41RqBD3kpdPd3hbeTUNE82G9A6sGggsp_Gnc)  - Kindly review the draft of this post.
 
 **Social Media Description**
 - Announcing the MicroProfile Tutorial Repo! A new GitHub repo for MicroProfile Content. Dive in, contribute, and learn. #MicroProfile #Java #OpenSource

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

Tarun Telang
Twitter ID: https://twitter.com/taruntelang
Github: https://github.com/ttelang
LinkedIn: https://www.linkedin.com/in/taruntelang/

**Comment by aeiras** [comment]
@ttelang the blog reads great. 
Please add it to the MP blog for publishing. As soon as it is there, its social distribution via MP media can start. You truly rock!

**Comment by ttelang** [comment]
> @ttelang the blog reads great. Please add it to the MP blog for publishing. As soon as it is there, its social distribution via MP media can start. You truly rock!

Added the blog https://microprofile.io/wp-admin/post.php?post=7347&action=edit in MP blog for publishing.

**Comment by aeiras** [comment]
> Below are the details of my blog post announcing the eclipse/microprofile-tutorial repository and inviting community members to share feedbacks and suggestions to the Tutorial Content.
> 
> **Content copy/edit review (available & optional)
> 
> * [Announcing the New MicroProfile Tutorial Repository on GitHub](https://docs.google.com/document/d/1MbqvLmE41RqBD3kpdPd3hbeTUNE82G9A6sGggsp_Gnc)  - Kindly review the draft of this post.
> 
> **Social Media Description**
> 
> * Announcing the MicroProfile Tutorial Repo! A new GitHub repo for MicroProfile Content. Dive in, contribute, and learn. #MicroProfile #Java #OpenSource
> 
> **Design Card** (for MicroProfile designer)
> 
> * [ ]   Minimal requirements highlight the MicroProfiler & the title of the blog
> 
> Tarun Telang Twitter ID: https://twitter.com/taruntelang Github: https://github.com/ttelang LinkedIn: https://www.linkedin.com/in/taruntelang/

@rstjames, 

Can you please use MP hootsuite to publish the tutorial using @ttelang's social description ?

Today the post was published. 

Lets schedule the post for 3 months, 1twice per month to bring awareness to the Tutorial new Repo. 

Q&A welcomed! Thank you.

----

@ttelang, 
You can follow up with @rstjames on anything related to the media post and similar. :) Valuable post!

**Comment by rstjames** [comment]
@ttelang just wanted to check where the image comes from? So we don't get hit with copywrite issues later

**Comment by rstjames** [comment]
![microprofile_tutorial_repo](https://github.com/eclipse/microprofile-marketing/assets/12132146/7697a662-27e5-4452-a159-a7cdc029c72e)

**Comment by rstjames** [comment]
All scheduled
