### ISSUE TITLE
MP swags @Devoxx UK

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-marketing#90]
Are there any MP swags @DevoxxUK? If no, can we ensure to make them available?

**Comment by aeiras** [comment]
None that I know of.  Tribers MP swag in EU distribution is zero at this time. Q2 2019, means update inventory yet not on time for DevoxxUK. 

Currently, all MP swag is **privately** distributed by Partners who choose to provide them to their employees. 

From the Tomitribe part, we provide MP _shirts and stickers_ to active community individuals as we see they will distrubute them fairly (means, constantly giving sessions on MP & also asking those who want shirts to #writeTHEtalk to earn shirts) etc. 

Currently, IBM and TT are the only 2 Partners who have sessions at devoxxUK. 

Now, the MicroProfile Project has been invited to sponsor as OSS project = $0 costs for DevRoxx Community Party. 
If you, via IBM, can bring some shirts to give away at the party, that would be amazing !

MP drive folder under SWAG have all data about current swag and how to print it : )
Hope this is helpful.
