### ISSUE TITLE
Interview Alex Lewis for MP Blog

### ISSUE THREAD

**Issue by ederks85** [microprofile/microprofile-marketing#93]
Edwin Derks to interview Alex Lewis on how involvement in MP started and create a MP blog out of the results

**Comment by ederks85** [comment]
GDoc link: https://drive.google.com/open?id=1nhOKAgXWMMZZQYU4Wr2OSE1ExY6Iz2DEip0IOJPY8sE

**Comment by ederks85** [comment]
I have received Alex's input on the interview questions. Going to process it to a blog.

**Comment by aeiras** [comment]
Wow, amazing! ;)

**Comment by aeiras** [comment]
@ederks85 whats your fun eta on importing the interview to WP? :)

**Comment by aeiras** [comment]
Hola @mblevins65, 

Using “suggestive mode” via the drive, can you please help us copy/edit the grammar of interview link above? 
Ideally, we will have the finalized version no later than next Wednesday. 
Thanks for the follow up 💛

**Comment by aeiras** [comment]
@ederks85, 

Can you please drop the newest version of the interview to the folder to enable the copy/editor to work on it? 
Easy if you update the first link with latest version above! Questions — always welcomed! ⭐️

**Comment by ederks85** [comment]
@aeiras I have updated the Google Doc and in the meantime added the content as a blog post (Onboarding Alex Lewis into MicroProfile) in Wordpress. It is submitted for review so it can be taken up for further processing.

**Comment by aeiras** [comment]
You and Alex are amazing!
Confirming that WordPress import is perfect. 

With Alex and the copy/editor we will take it from here Edwin to have interview push before the end of June! :)

**Comment by aeiras** [comment]
also Edwin-- the only thing you will notice that _I will_  adjust is the fun INTRO by adding especific data, links, ect. 
The rest of the interview will be just regular adjustments as the editor see fits with Alex. 

enjoy your holiday and thanks for transfering fun steps to final push. :)

**Comment by ederks85** [comment]
You're welcome @aeiras and please, do whatever is necessary ;).

Note that I have put a few updates from Alex on the content in the Google Doc. These have to be transferred to WP. I appreciate that you confirm that you, Alex and the copy/editor will take it from here. I will now leave my keyboard and not get in between anymore.

**Comment by aeiras** [comment]
Confirmation that we gotchU-- @ederks85 ! :)

**Comment by aeiras** [comment]
@alewis001 lets follow this ticket with future updates. I have pulled the copy/editor to work on grammar stuff. your job is to accept or decline that imput in the next 3 days. :) 
@mblevins65 will use "suggestive mode" :)

**Comment by alewis001** [comment]
Ok. No problem. I'll keep an eye on the google doc for comments/updates.

**Comment by mblevins65** [comment]
@alewis001 
editing is complete.  Very few changes needed.  Congrats, it reads well.

**Comment by aeiras** [comment]
Thank you @mblevins65! 

@alewis001 please pull me in via comments once you are done with the final review, so i can update the version in wordpress and schedule it to be published on 6/27, sUPER FUN! :)

**Comment by alewis001** [comment]
I don't have any further comments. @ederks85 has done a great job and if @mblevins65 is happy with the edit, then so am I :) 

@aeiras Is there anything else/topic/question you would like to see discussed in the post? The timeline probably doesn't permit any additional work, especially with Edwin on vacation, but I thought I'd ask just in case.

**Comment by aeiras** [comment]
@alewis001 after you  accept or decline Peggy's feedback, I will import updated version to Wordpress and it will be schedule to go live tmw.  :)

**Comment by alewis001** [comment]
All feedback accepted in the doc.

**Comment by aeiras** [comment]
Now- my task starts :) thank YOU amazing MicroProfilers! 

Alex, your dedication and that of Edwin to take the time to prioritize the very first iteration of MP to MP interview about diving into this project ecosystem is beyond awesome!

I take it from here, you and Edwin have handed this ticket beautifully- it matters b/c issue is part of the new documentation that will welcome anyone to own what you just did! 

documented [here](https://github.com/eclipse/microprofile-marketing/wiki/Interviewing-New-MicroProfilers).

**Comment by aeiras** [comment]
- [ Interview Tweet] https://twitter.com/MicroProfileIO/status/1144245946743607296
