### ISSUE TITLE
MP Session at SouJava

### ISSUE THREAD

**Issue by ivargrimstad** [microprofile/microprofile-marketing#94]
Speaker: Ivar Grimstad
Session: MicroProfile Patterns - Implemented by Eclipse MicroProfile
May 8, 2019, São Paulo

https://www.eventbrite.com/e/encontro-tecnico-do-soujava-tickets-60835179660

**Comment by aeiras** [comment]
shot wonderful MicroProfiler, push is likely not possible given that session is 2 days away. 

@ivargrimstad tweet lots and I will re-tweet instead... 
Remember for future sessions submissions via git below requirements ping-in as an issue in main issue page:

Create a new issue & provide the details below:

Name of the speaker;
Name of the session;
twitter or/& git account, if available;
link of the event or short session abstract;
Date/ time/location; AND
Speaker must provide a "tweet message" for their session. (who better to write it than the speaker)
REMEMBER: When possible, issues ought to be submitted at least two(2) weeks before the event. Thank you for #sharingMPknowledge
