### ISSUE TITLE
MP Media Design Banner Scalability by Continent is Needed

### ISSUE THREAD

**Issue by aeiras** [microprofile/microprofile-marketing#96]
@rstjames after you are back from #RRR and without rush given the other MP focus, lets bring back the Q4 2018 MP event banner design we created that could be used by speakers without much work on their side. 

Why?
The project needs to enable the speakers who forget to submit within 2weeks before the events a way to still push via their media a cool MP template that states the requirements about session and event.

Minimum requirements:

- today's MP banner items

- added space for the speaker or their marketing team to add the Event/JUG logo without any help.

Re-tweeting from MP those last minute events is the optimal outcome! 
Lastly, please use the Design drive under MP for such work and lets create new issues for each design created that needs feedback. 

**Ideally,**  I would like for the 5 continents to have their very own MP desig when a session is given on that continent. That is practical, scalable and just fun. 

Your feedback welcomed. lets keep this new feature uncomplicated. Start small with maybe Latin America.

**Comment by rstjames** [comment]
@aeiras 
I uploaded the session PSD templates to the drive. There is an image for 1 person session, 2 person session and 3 person session. 
This is the link 
https://drive.google.com/drive/u/1/folders/1whC7SmGGGdP0u5xyck3U-74s8J5s5tV_

**Comment by aeiras** [comment]
@rstjames the links gives me a 404 error Triber. Please try again.

**Comment by rstjames** [comment]
@aeiras not sure what the issue is. It is in the same drive as all MP docs/ resources.

**Comment by aeiras** [comment]
I see no Resources folder Ryan. 
Conferences doesn't contain the designs either.

**Comment by rstjames** [comment]
@aeiras I relocated the Designs to "Conferences" folder. 
FOLDER NAME:
SESSION IMAGE TEMPLATE (PSD) 
https://drive.google.com/open?id=0B8_67yGf9LkLQjhoWkthR1dPZzQ

**Comment by aeiras** [comment]
@rstjames Now i see folder, excellent! Thank you for beautifully scaling the designs. 
If there is a way to link it to MP resources tab to enable anyone in need to grab them when needed, that would be cool, yet I don't know how to. If it takes too much time, we will need to drop it for now. 

- thinking a box somewhere under resources that says to those who speak MP session template here for up to 3 speakers. or similar.

**Comment by rstjames** [comment]
@aeiras if we do this maybe we should make sure we put all link to logo files and any other items that contributors may need. What else can we add into one folder?

**Comment by aeiras** [comment]
@rstjames great follow up Ryan! 🥋

Folder 📁 ought to contain:

1) media design templates
2) MP session templates 
3) the MP logo: two marks
