### ISSUE TITLE
DevDays Europe 2019 talk

### ISSUE THREAD

**Issue by jeanouii** [microprofile/microprofile-marketing#97]
Conference Name: DevDays Europe 2019Conference website and social media links: https://devdays.lt/enterprise-java/

About the sessionTitle: Lightweight Enterprise Java with MicroProfileDate and hour: May 16th - 2pmTweet message: Join @tomitribe #triber @JLouisMonteiro at #devdays2019 on 05/16 for "Lightweight Enterprise Java with MicroProfile" - Attend to learn more about @java microservices & @MicroProfileIO.

Speaker name: Jean-Louis Monteiro (@JLouisMonteiro)

**Comment by rstjames** [comment]
@jeanouii All set up. 2 tweets will be sent out.
