### ISSUE TITLE
Website rendering issues on FireFox

### ISSUE THREAD

**Issue by rdebusscher** [microprofile/microprofile-marketing#99]
On my Firefox (v66, Mac) the Website microprofile.io rendering is broken.  This is the sequence of screens that you see when going to the site.

- A 'raw' version of the site, incorrect positioning of the elements (see attachment)
- Screen goes blank
- Indication of the 'progress image'
- correct site shows.

This all takes about 2-3 seconds and the incorrect site is visible for about 0.5 seconds.

There is no issue with Chrome.
<img width="1160" alt="Screenshot 2019-05-22 at 07 44 29" src="https://user-images.githubusercontent.com/1228265/58150375-bc597b00-7c66-11e9-8f92-c4676ffc4505.png">

**Comment by aeiras** [comment]
@rstjames can you please check Rudy's feedback and see where the issue lies? 

Thanks @rdebusscher

**Comment by rstjames** [comment]
@rdebusscher what version are you using of Firefox. I checked the site and everything looks good. 
The older versions could be the reason for issues. Please update and let me know

**Comment by rstjames** [comment]
@rdebusscher any update on this?

**Comment by aeiras** [comment]
hola @rdebusscher, 

do you have further feedback on this ticket? if not, please close it. thanks!

**Comment by rdebusscher** [comment]
At that time, the latest version of Firefox showed the rendering issue.

Today it seems okay with the latest version of Firefox.
